lightningnetwork/lnd

README.md

Rusty's name had a small typo.

Fix name typo in README

---

README.md
cmd/lncli/commands.go
peer.go

Fixes and documentation for installing via `go get`.

Make lnd go-gettable

---

channeldb/channel.go
channeldb/channel_test.go
lnwallet/btcwallet/btcwallet.go
lnwallet/btcwallet/signer.go
lnwallet/channel.go
lnwallet/channel_test.go
lnwallet/interface.go
lnwallet/interface_test.go
lnwallet/reservation.go
lnwallet/script_utils.go
lnwallet/script_utils_test.go
lnwallet/wallet.go
peer.go

As far as I see we generate `PW2SH` output in funding transaction and in specification [they use](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#witness-program) `witnessScript` field name. I think we should stick with this one in order to not create confusion later (if we gonna use [`P2WSH nested in P2SH`](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#p2wsh-nested-in-bip16-p2sh) for backward wallets compatibility).

BIP-141 name fix

---

README.md

[trivial] typo in README

---

lnd_test.go
lnwire/commit_signature.go
peer.go

By investigating the logs it looks for me like the `Carol` node don't have enough time to include the `HTLC` in commitment transaction and update channel state in `channeldb`, so the temporary solution proposes to do channel info requests during some time and only after it throw the error.

Temporary fix multihop

---

channeldb/channel.go
channeldb/db.go
channeldb/error.go
channeldb/meta.go
channeldb/meta_test.go
lnd.go

In this commit the: 
- Upgrade mechanism for database was added which makes the current schema rigid and upgradeable. 
- Additional bucket `metaBucket` was added which stores key that house meta-data related to the current/version state of the database. 
- Function `createChannelDB` was modified to create this new bucket+key during initialisation. 
- Backup logic was added which makes a complete copy of the current database during migration process and restore the previous version of database if migration failed.

#50 Add database versioning 

---

fundingmanager.go
htlcswitch.go
lnd_test.go
lnwallet/channel.go
lnwallet/channel_test.go
lnwallet/script_utils.go
lnwallet/size.go
lnwire/error_generic.go
peer.go
rpcserver.go

@Roasbeef In this commit I wanted to show what have been done in [#28 issue](https://github.com/lightningnetwork/lnd/issues/28), and would like to get the feedback - Am I doing things right or maybe there is much better way to estimate the size of commitment transaction? For now there is big error (`94 weight`) between estimated transaction cost and actual one, and before dig into problem I think it would be better to show you in which direction I am going to.
- **Related BIPs:**
- [BIP 141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki)
- [BIP 144](https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki)
- **Related issues:**
- [btcwallet #424 - Add support for new Segregated Witness standard output types](https://github.com/btcsuite/btcwallet/pull/424)
- [btcd …

Adhere to max-weight limits within LCP state machine #28

---

lnwire/lnwire.go
lnwire/signature.go
lnwire/signature_test.go

Formatting changes are due to `go fmt`. If you'd like these reverted, please let me know.
I have changed the writeElement and readElement functions to represent the signatures as 64 bytes on the wire with R being the first 32 and S being the second 32 bytes, both big-endian and zero-padded. The interaction between these functions and the rest of the code is not changed.

Change signature encoding to 64 bytes fixed on wire

---

chainntnfs/btcdnotify/btcd.go

Break out of loop once txIndex is found.
Get correct block height for txConfirmation.

Some minor fixes

---

README.md
brontide/README.md
chainntnfs/README.md
channeldb/README.md
lnrpc/README.md
lnwallet/README.md
lnwire/README.md
routing/README.md
zpay32/README.md

This pull request makes a link from each license badge.
Previously:
[![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)]
Now:
[![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](https://github.com/lightningnetwork/lnd/blob/master/LICENSE)

Add a link to the license for README license badges

---

docker/btcd/Dockerfile
docker/lnd/Dockerfile

docker-compose fails to start because the starting scripts do not have execution permissions.

Add chmod +x to start scripts in dockerfiles

---

zpay32/zbase32check.go
zpay32/zbase32check_test.go

This pull request adds a check to zpay32's `Decode` function for data that's too short but validly encoded. This prevents a panic caused by accessing outside the slice bounds reported in issue #127 by `Ylbam` on IRC.

zpay32: Fix decoding when payment request is too short.

---

rpcserver.go

Fix for #144 issue.
The proper fix should be discussed with @Roasbeef, at this point solution is done just on order node work without crashing.

rpcserver: fix pendingchannels panic

---

channeldb/channel.go
channeldb/channel_test.go
lnwallet/channel.go
lnwallet/script_utils.go
lnwallet/script_utils_test.go
lnwallet/wallet.go
lnwire/lnwire.go
lnwire/single_funding_complete.go
lnwire/single_funding_complete_test.go

TODO: fix deriveStateHintObsfucator to set correct obsfucator for the channel. According to the [spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#commitment-transaction) the payment-basepoints from `open_channel` and `accept_channel` are needed, and they don't seem to be implemented yet.
Since I am pretty new to writing Go, please let me know if I have done something wrong.

Use 48-bit commitment transaction numbers

---

docs/INSTALL.md

Not sure if this case makes sense to you, but it seems to be what happened in my case (on Mac OS), and this solution worked.
I also  wondered why in the `sed` command it says "any user/pass you like" and not "the one you picked before", as I did in my case, since that seemed to make sense. :)

Explain what to do if btcd.conf not found

---

lnwallet/channel.go
lnwallet/channel_test.go
lnwallet/interface_test.go
lnwallet/script_utils_test.go
lnwallet/wallet.go
utxonursery.go

Currently non-HTLC outputs will be accepted in the commitment
transaction as long as it is non-zero. We change this by not allowing
outputs with a value lower than the dust limit. The value of such
an output will go towards transaction fees.

Avoid dust outputs in commitment transactions

---

server.go

If error occurred on peer initialisation then `p` is nil which cause
panic while accessing peer variables.

server: fix panic when error occurres on peer intialisation 

---

gotest.sh
lnd_test.go
lnwire/channel_announcement_test.go
lnwire/signature.go
networktest.go

Hmm, looks like timeout hasn't been added there for a reason, but without it, locally, test is not working for me. And also the amount of time to run the integration tests jumped from `~57` sec to `~62` which means this timeout justified, at least on my machine.
I think that it is related to the fact that channel announce is spawned as `goroutine` (in `funding manager`) and for some reason goroutine scheduler postpone its execution.

tests: add timeout in 'revoked uncooperative close retribution' test

---

lnwallet/channel.go
lnwallet/channel_test.go

This PR aims to fix several things with ChannelDeltas:
* toChannelDelta now handles duplicate payment hashes
* fixes a bug that created incorrect ChannelDeltas
* ~Exclude dust HTLC outputs in ChannelDeltas~
See commit messages for more info.

Various ChannelDelta fixes

---

README.md

The Markdown for badges in the README has newlines incorrectly separating the
images from the associated URL link, causing the link URLs to show up as text.
This removes the newlines so that the badges render properly.

Fixing badges in README

---

docker/README.md
docker/lnd/Dockerfile

docker: change container golang version; fix readme

---

config.go
docker/README.md
docker/lnd/Dockerfile

Error `connection refused` was thrown when user tries to get "Alice" to connect to "Bob" node due to port mismatch introduced in this change [1] here.
This commit updates the port value to reflect the new change introduced in [1].
Reference:
[1] https://github.com/lightningnetwork/lnd/commit/72772ce4df051501cf4936e9fedd62bb13463bf2

docs: update docker step-by-step readme

---

docs/INSTALL.md

This fixes a typo in docs/INSTALL.md in the btcd RPC port.

docs: Fix port in sample lnd.conf

---

docker/lnd/start-lnd.sh

This commit contains replacement of previous --rpccert flag on newest --bitcoin.rpccert flag in docker lnd config. Before this change, the lnd nodes has been dropped at startup.

docker: update docker instructions to be aware of multi-chain config (2)

---

docs/INSTALL.md

In order to specify multiple external IP addresses in the configuration
file, each IP address must be on a separate line, preceded by “externalip=“.

docs: fix entry for externalip

---

breacharbiter.go
channeldb/channel.go
fundingmanager.go
lnd.go
lnd_test.go
lnwallet/channel.go
lnwallet/channel_test.go
lnwallet/interface.go
lnwallet/interface_test.go
lnwallet/reservation.go
lnwallet/script_utils.go
lnwallet/wallet.go
peer.go
routing/notifications_test.go
routing/router.go
rpcserver.go
server.go

This PR replaces the hard-coded 5000 satoshi fees with calls to the
FeeEstimator interface. This should provide a way to cleanly plug in
additional fee calculation algorithms in the future. This change
affected quite a few tests. When possible, the tests were changed to
assert amounts sent rather than balances so that fees wouldn't need to
be taken into account. There were several tests for which this wasn't
possible, so calls to the static fee calculator were made.
This PR addresses Issue #52.

lnwallet: replace hard-coded fees with calls to FeeEstimator interface

---

fundingmanager.go
lnd_test.go
networktest.go

Fix bug with synchonizing blockchain by adding several retries. Allow
to launch individual tests. Increase timeout for async payments.

tests: small improvements

---

config.go
lnd.go

- Still use port `8080` by default

Add a command line arg that allows users to specify the REST port

---

lnwallet/channel.go
lnwallet/channel_test.go

If an HTLC’s value is below a node’s dust limit, the amount for that
HTLC should be applied to to the fee used for the channel’s commitment
transaction. This PR also adds minor refactoring of the dust limit unit tests.

lnwallet: apply dust amounts to fees

---

config.go
params.go

Support for regtest allows us to create integration tests to verify
interoperability with other implementations. This seems to work, and
allows to connect to `btcd` and indirectly to `bitcoind` so we can run
lnd on the same network as eclair and c-lightning.
For details about my integration framework check this repo:
https://github.com/cdecker/lightning-integration

Add regtest support to lnd

---

channeldb/channel.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/test_utils.go
lnwallet/channel.go
lnwallet/channel_test.go
lnwire/lnwire_test.go
lnwire/message.go
lnwire/update_fee.go
peer.go

This PR adds support for sending and receiving the `update_fee` message specified in BOLT#2.
It does not currently implement the actual logic for when to send this message.
TODO:

Add update_fee message as specified in BOLT2

---

chainntnfs/btcdnotify/btcd.go
chainntnfs/neutrinonotify/neutrino.go

Makes cancellation of neutrino and btcd notifications block until notification dispatcher has processed the cancellation request. This commit also unifies the logic across all cancellation handling in regards to formatting and documentation.
The issue is primarily created because of a quirk in go, allowing buffered channels to be read after they have been closed. The solution is to ensure the notification channels are properly drained and closed before yielding to the caller of Cancel.  By doing so, we can ensure that the channel is both empty and closed before allowing the caller to attempt a read on the buffered channel. Under this proposal, we can safely remove the use of done channels used to synchronize epoch cancellation since draining the channel is sufficient to ensure that the …

Synchronized Spend and Epoch Notification Cancellation

---

htlcswitch/switch.go

Because the .String() method of an amount already includes a unit string
("BTC" usually), it was printing "0.00000001 BTC satoshi".

htlcswitch: Fix typo in logging

---

networktest.go

This PR uses the `StopDaemon` RPC to stop `lnd` instead of SIGINT (or SIGKILL on Windows).
Currently, tests often fail with the reason:
```lnd_test.go:67: Error outside of test: *errors.errorString lnd finished with error (stderr):```
This is because `lnd` exits with error code 130 (stopped by SIGINT). When `StopDaemon` is used, the process exits without an error code. However, the code in this PR doesn't watch for an error returned from the RPC server as the connection is often dropped by `lnd` as it shuts down before the response can be sent/read.

networktest: use StopDaemon RPC to stop lnd instead of SIGINT

---

channeldb/graph.go
channeldb/graph_test.go
discovery/service.go
fundingmanager.go
lnd.go
lnd_test.go
routing/errors.go
routing/notifications_test.go
routing/pathfind_test.go
routing/router.go
routing/router_test.go
server.go

As specified in BOLT#7, we should ignore any node announcements for nodes that we have not gotten any channel announcements for. This is to prevent an attacker to DoSing the network by creating a lot of cheap nodes.
- We are now sending a node announcement (self) after every channel announcement
- When we receive a channel announcement we are adding a node to the graph which only has the pubkey field set. The rest will be set when a node announcement for the same node is received.
Fixes #138.

Ignore node announcements for nodes not found in any existing channel

---

chainntnfs/btcdnotify/btcd.go
chainntnfs/neutrinonotify/neutrino.go

Resolves a synchronization error that prevents channels from being closed properly, resulting in failed test cases due to timeouts.
Issue occurs when spend notifications has already been delivered when Cancel is called.  The delivery of notifications removes the reference to the spendChan from the registry's internal map, preventing the channel from being properly closed during the actual Cancel.  The solution is to close each channel after queuing the notification, this way we ensure that any subsequent reads will see the properly closed spendChan and exit.
Still in the process of ensuring other flakes are not produced or further related to this issue.

Close spendChan after delivering ntfn

---

fundingmanager.go
lnd.go
server.go

Previously, calling `CurrentNodeAnnouncement` twice in a row, would cause the first returned `NodeAnnoucement` to be modified by the second call, since a pointer to the stored struct is returned. This PR changes that by instead returning a copy of the current `NodeAnnouncement`, making the second call not altering the first one.

Make CurrentNodeAnnouncement threadsafe

---

channeldb/channel.go
fundingmanager.go
fundingmanager_test.go
lnd.go
lnd_test.go
rpcserver.go

This PR adds the following persistence to the FundingManager:
- After the funding transaction has been confirmed on-chain, the channel is added to an internal database, marking it `markedOpen`. If the `fundingLocked` message now fails to be sent before a shutdown happen, the FundingManager will retry sending the message on restart.
- After the `fundingLocked` message has been successfully sent, the channel is marked `fundingLockedSent`. Again, if the FundingManager now fails to announce the channel to the network, it will retry upon restart.
- After the announcement has been sent, we delete the channel from this internal database, as the opening process is complete.
Added fundingManager test that goes through the basic, normal workflow without any restarts.
TODO:
Addresses #182

Persist state of the channel opening process in FundingManager

---

fundingmanager.go
htlcswitch/mock.go
lnd.go
lnd_test.go
peer.go
rpcserver.go
server.go

This commit alters the synchronization patterns used in the server such that the internal state is protected by a single mutex.  Overall, this simplifies the ability to reason about the behavior and manipulation of the internal state, which has resolved a few flakes related to race conditions that were observed beforehand.
This PR originated as a fix for synchronizing the message broadcast, but has expanded into a full refactor of the server's synchronization.  A significant portion of this refactor was spent properly synchronizing disconnections from peers.  We observed a some flakes related to the timing of disconnections, particularly during restarts.  We also modified the implementation of `assertNumConnections` to poll for 3 seconds to ensure that the remote peer has acknowledged a …

Server-Peer Synchronization

---

lnd_test.go
networktest.go

This PR fixes several instances of a `<-time.After` inside a `select` inside a `for` loop, where the other channel read is from a ticker. In these instances, the `time.After` channel was re-created with every tick, so the timeout would never trigger.
Another timeout instance was fixed where the timeout was `20 * time.Second * time.Second` instead of just `20 * time.Second`.

tests: fix several timeout issues

---

fundingmanager_test.go
lnwallet/channel.go
lnwallet/channel_test.go
mock.go
peer.go
peer_test.go
test_utils.go

This PR adds a simple fee negotiation flow on channel shutdown. Currently, the algorithm works as follows:
- The node picks a desired fee and send it to the remote.
- When the node receives a fee proposal from the remote, it accepts it if it is in the range `[0.5*desired, 2*desired]`.
- If the remote's fee is not in this range, the node will propose the average of its own last sent fee and the remote's, restricted to this range.
Both nodes in the channel will broadcast the closing transaction the moment they have the signatures for a transaction with the agreed fee.
TODO:

Add fee negotiation on channel cooperative shutdown.

---

README.md
docker/README.md
docs/INSTALL.md
docs/grpc/javascript.md
docs/grpc/python.md

Python and Javascript gRPC guides
- Now serve as complete standalone guides programmatically pulled into [dev.lightning.community](http://dev.lightning.community)
- Contains code examples for Simple, Response-streaming, and Bidirectional RPCs
Consolidate installation docs
Remove characters from the docker guide that break utf-8 encoding (you have to decode it with `latin-1` codec which is too hacky to implement as special logic in the dev site rendering code

Flesh out gRPC guides, consolidate installation docs

---

lnrpc/rpc.proto
rpcserver.go

- Add descriptions for methods, messages, and fields in rpc.proto
- Add command mapping from rpc to lncli
Comments in this file will be directly parsed into the API Documentation as descriptions of the associated method, message, or field. These descriptions should go right above the definition of the object, and can be in either block or /// comment format. 
One edge case exists where a // comment followed by a /// comment in the next line will cause the description not to show up in the documentation. In that instance, simply separate the two comments with a blank line.
A RPC method can be matched to an lncli command by placing a line in the beginning of the description in exactly the following format:
```
lncli: `lncliname`
```
Failure to specify the exact name of the command will …

Make rpc.proto suitable for documentation generation

---

cmd/lncli/main.go
config.go
glide.lock
glide.yaml
lnd.go
macaroons/auth.go
macaroons/service.go
macaroons/store.go
networktest.go
rpcserver.go

This is an initial macaroon implementation. It partially fixes issue #20.
`lncli` already includes the client-side macaroon usage with basic replay protection (an additional caveat that makes the request good for only 1 minute by default). To authenticate your request to `lnd` with your own framework, put the hex-encoded macaroon in the GRPC request's metadata under the key `macaroon`. To authenticate your request to `lnd` via the REST proxy, put the hex-encoded macaroon in an HTTP header called `Grpc-metadata-macaroon` like so:
```
$ curl -k --header "Grpc-metadata-macaroon: 303031316C6F636174696F6E206C6E640A303033326964656E74696669657220302D31306563323637613262306566633137613235376662363561616463656161610A3031326363696420616C6C6F77207665726966796D65737361676520676574696E666F206C697374706 …
```

Initial macaroon implementation

---

lnd_test.go
networktest.go

Fixes timeouts during integration tests on slower machines.

test: reposition context creation and extend TLS timeout

---

docs/INSTALL.md

The installation instructions for btcd were missing a 'git clone' command.

add 'git clone' line for btcd

---

lnwire/lnwire_test.go

This corrects the fuzz test in `TestLightningWireProtocol` for `MsgCommitSig` to avoid creating an empty slice since the decoded message only creates a slice when there are greater than zero signatures and an empty slice is not considered equal to a nil slice under reflection.
This can be tested by running the `TestLightningWireProtocol` 100 times in a loop with and without this change.
For example, here is the redacted output prior to this PR:
```base
$ for i in $(seq 0 1 100); do go test -run TestLightningWireProtocol; done
```
```
...
lnwire_test.go:127: messages don't match after re-encoding: (*lnwire.CommitSig)(0xc04204a900)({
ChanID: (lnwire.ChannelID) (len=32 cap=32) 19fda145e1053c5d36890e5169101beeb80875fea036c0b8de1c7bc66c427739,
CommitSig: (*btcec.Signature)(0x8bcac0)({
R: …
```

wire: Correct fuzz test for MsgCommitSig.

---

channeldb/invoice_test.go
channeldb/payments_test.go

This modifies the tests that deal serializing the `Invoice` type to limit the creation date to seconds since Go1.9 added the concept of a monotonic component to times which does not round trip through
`MarshalBinary` and `UnmarshalBinary` and therefore causes the tests to fail.
In particular, it modifies the creation dates in the `randInvoice`, `makeFakePayment`, `makeRandomFakePayment`, and `TestInvoiceWorkflow` functions.
This results in allowing `TestOutgoingPaymentSerialization`, `TestOutgoingPaymentWorkflow`, and `TestInvoiceWorkflow` to pass.

channeldb: Fix payment serialization tests.

---

channeldb/graph.go

This PR fixes a nil pointer dereference that happened because the bucket was never checked for nilness.

trivial: Check correct bucket for nil

---

invoice/amountunits.go
invoice/bech32.go
invoice/invoice.go
invoice/invoice_internal_test.go
invoice/invoice_test.go
lnwire/lnwire.go
lnwire/signature.go
lnwire/signature_test.go

This PR adds a package `invoice` that contains the necessary logic for encoding and decoding invoices as specified by BOLT#11.
The file `bech32.go` is copied from `btcutil` and modified to allow strings to be longer than 90 characters (as BIP173 does not allow strings that long).
When encoding an invoice it is expected that the caller provides a `SignCompact` method that sign the hash of the data by btcutil's `SignCompact` method:
```go
sign := btcec.SignCompact(btcec.S256(), privKey, hash, true)
```
The `recoveryID` added to the invoice is `sign[0] - 27 - 4`. The signature bytes added to the invoice then becomes `append(sign[1:64], recoveryID)`. 
Similarly when decoding an invoice, we either 
1) do pubkey recovery by 
```go
headerByte := recoveryID + 27 + 4
compactSign := …
```

BOLT #11: Invoice Protocol for Lightning Payments

---

lnwire/features.go

This commit fixes an incorrectly calculated size of a `*FeatureVector` in the `serializedSize()` function.  
Deserialized messages read in via `lnwire.ReadMessage` are eventually passed to `NewFeatureVectorFromReader` in `features.go`.  In the loop on [line 152](https://github.com/lightningnetwork/lnd/blob/master/lnwire/features.go#L152), if a flag is invalid, it is not added to `f.flags`.  
This is fine, except for the fact that when serializing the now deserialized message, the `Encode` function on [line 192](https://github.com/lightningnetwork/lnd/blob/master/lnwire/features.go#L192) allocates a `[]byte` of length `f.serializedSize()`.  If there are missing indices because of `NewFeatureVectorFromReader` not processing invalid flags, serializedSize() can more than likely calculate an …

serializedSize() fix

---

cmd/lncli/main.go
lnd.go
macaroons/auth.go
macaroons/constraints.go

Support for additional macaroon constraints

---

breacharbiter.go
breacharbiter_test.go
lnd_test.go
lnwallet/channel.go
lnwallet/script_utils.go
lnwallet/signdescriptor.go
lnwallet/size.go
lnwallet/witnessgen.go
server.go
utxonursery.go

This PR builds upon the initial work of #241 by enabling the breach arbiter to sweep 2nd layer HTLCs. In it's current state, this PR:
Looking into a fix for issue #256 as this seems like the appropriate time to resolve this. A fix has been implemented, though it will be added in a separate PR to keep this one from spreading further.
This PR builds upon #308 which adds HodlHTLC mode.  The modified integration test (`testRevokedCloseRetributionRemoteHodl`) requires the remote node to be started with the `--htlchodl` flag in order to properly test that we are sweeping extended-but-unsettled HTLCs.

Breach Arbiter Sweep 2nd layer HTLCs

---

glide.lock
glide.yaml
routing/chainview/neutrino.go

This should hopefully fix flakiness on neutrino notifier tests.

dependencies: Bump neutrino version.

---

fundingmanager.go
fundingmanager_test.go
htlcswitch/link.go
htlcswitch/mock.go
lnd.go
lnwallet/channel.go
peer.go
server.go

This PR contains several improvements to the way `fundingLocked` messages are sent and handled, to be able to continue the channel opening process in edge cases like restarts and disconnects.
This closes issue #303.
1. We now ignore a duplicate received `fundingLocked`.
2. In the case we start the `channelLink` and the number of updates recorded on that channel is 0, we resend the `fundingLocked` message. This is and intermediate step before merging #231.
3. In case the `fundingManager` gets restarted before the channel opening process is finished, we set up channel barriers again, such that `waitUntilChannelOpen` correctly will wait for it to finish.
4. Instead of sending the `fundingLocked` message synchronously to the peer, we add a listener to a new queue in the `server`, such that …

FundingLocked improvements

---

channeldb/channel.go
channeldb/invoices.go
channeldb/waitingproof.go
lnwallet/channel.go
lnwallet/sigpool.go
routing/heap_test.go
routing/pathfind.go
routing/router.go

Issue #276 - Use `sort.Slice` function rather than re-creating `sort.Sort` interfaces. Use `binary.Read/Write` with `bool` arguments within `channeldb`.

Utilize new golang 1.8 features within the codebase -#276

---

utxonursery.go
utxonursery_test.go

This PR marks the first of several to follow aimed at refactoring the persistence and on-chain handling of HTLC outputs in the utxo nursery.
We introduce two new types in this PR:
- `babyOutput`: A struct representing a CLTV delayed output that will mature into a `kidOutput` after the CLTV output has been spent. HTLCs that need incubation will begin their two stage journey through the utxo nursery in this state.
- `CsvSpendableOutput`: An interface for accessing and generating sweep transactions that spend from CSV delayed outputs. This is an extension of the `SpendableOutput` interface introduced during the recent breach arbiter refactoring, in efforts to modularize on chain handling.  The existing `kidOutput` struct now implements this new interface, and direct access to internal state …

Adds second layer HTLC output types to UtxoNursery

---

server.go

This commit fixes several race conditions exhibited by the server during unexpected peer disconnections. Instead of delaying the cleanup of a peer's resources to the `peerTerminationWatcher`, the server is now able to fully disconnect a peer without releasing its mutex. The bulk of the solution was to add an `ignorePeerTermination` map, which allows the server to record internally which peers it has intentionally removed.  With this, the `peerTerminationWatcher` now only executes in full in the event that the counterparty disconnects unexpectedly.

Fixes server race conditions during unexpected peer disconnect

---

.travis.yml
gotest.sh

This PR adds: 
- Functionality to `gotest.sh` to log the output of `lnd` instances used for integration testing to file.
- Uploading of those log files to [termbin.com ](http://www.termbin.com) from TravisCI integration builds.
As an example of a build with this enabled, you can look at [this build](https://travis-ci.org/samvrlewis/lnd/builds/286942025), which is a build from my `ci_logging_test` branch. That branch has the same diff as my `ci_logging` branch but with a small inclusion to allow TravisCI builds to work (as I described in [my comment](https://github.com/lightningnetwork/lnd/issues/302#issuecomment-335133834) the other day). If you scroll to the end of the job logs where `RACE=false` you'll see a `after_script` section with an output like this:
```
output0.log uploaded to …
```

Add upload of integration logs from TravisCI builds (fixes #302)

---

breacharbiter.go
lnwallet/btcwallet/btcwallet.go
lnwallet/interface.go
lnwallet/size.go
lnwallet/size_test.go
lnwallet/wallet.go
mock.go

The fee estimation code for funding transactions has a few problems. Aside from a few numerical errors (eg. not accounting for the vin and vout length varint sizes), I noticed that fee estimation was duplicated in a few places. Hopefully this is a little cleaner.
Beyond just a refactor, I think there are further enhancements required to be compatible with wallets that have unspent P2PKH outputs, or pay-to-witness nested in P2SH. I'm not sure what the best way to solve this is -- seems like we need to query the WalletController for the output type to perform accurate fee estimation. Open to suggestions here, but that can be done in a future PR.

lnwallet: Better transaction fee estimation for funding transactions.

---

lnwallet/channel_test.go

This commit fixes the TestChannelBalanceDustLimit unit test in channel_test.go. The unit test does not account for the fees required by adding an HTLC. As a result, Alice's balance drops below 0 at certain points. By using the correct fee, this is avoided. The negative balance can be observed [here](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L1846) in `ourBalance`.

wallet: channel test fee fix for added HTLC

---

lnwallet/interface_test.go

This PR adds a new test to make sure reorganizations work correctly.

lnwallet: add reorg test

---

lnwallet/channel.go
lnwallet/script_utils.go
lnwallet/script_utils_test.go
lnwallet/wallet.go

Refactor some of the commitment code in channel.go. Helps in the implementation of https://github.com/lightningnetwork/lnd/pull/350.
Create struct holding all commitment keys to clean up code and avoid deriving keys multiple times.
This moves the commitment transaction generation code out of fetchCommitmentView into createCommitmentTx. Aside from being a pretty clean logical split, this allows the transaction generation code to be unit tested more effectively.

lnwallet: Commitment refactor

---

htlcswitch/link.go
lnwallet/channel.go

The updateLog struct contains pointers that refer to the state of the commitment chains. Instead, query the commitments directly. This also adds the flexibility of possibly supporting multiple unACKed commitments.

lnwallet: Simplify updateLog struct by removing redundant pointers.

---

fundingmanager_test.go

This commits make the fundingmanager tests poll for database state
for a time, instead of using an explicit sleep before accessing the
DB. This should address some of the flakes encountered on Travis,
where db writes might take longer than usual.

fundingmanager test: poll or database state instead of using timeouts.

---

fundingmanager.go

This PR tackles the first step of issue #305.  `waitForFundingConfirmation` is decoupled from the channel announcements and `sendFundingLockedAndAnnounceChannel` is now decoupled into `sendFundingLocked` and `sendChannelAnnouncement`.
A future PR will handle:
1) Waiting for 6 confirmations before channel announcement in `sendChannelAnnouncement`.
2) Adding the channel to the channel graph immediately after sending the `FundingLocked` message.

funding: decouple funding wait from fundingLocked and chanAnn

---

channeldb/graph.go
channeldb/graph_test.go
lnd_test.go
routing/chainview/btcd.go
routing/chainview/interface.go
routing/chainview/interface_test.go
routing/chainview/neutrino.go
routing/chainview/queue.go
routing/notifications_test.go
routing/router.go
routing/router_test.go

This PR makes the channel router re-org aware, by making the router handle stale blocks delivered from the chain view. The channel graph now gets support for "reverse pruning", through the method `DisconnectBlockAtHeight`. This method will remove edges from the channel graph that gets "negative confirmations" because of a reorg, leaving the database in a state consistent with the best height the router is aware of.
This PR also introduces a new queue implementation for ordered block events, modeled after the `htlcswitch`'s `packetQueue`. This is used to ensure the notifications about connected/disconnected blocks from the chain view is handled by the router in the correct order.
Several tests are added to ensure the re-org awareness is working as expected in the affected parts of the …

ChannelRouter and graph re-org awareness

---

chainntnfs/neutrinonotify/neutrino.go
glide.lock
glide.yaml
routing/chainview/neutrino.go

This PR updates `lnd` to be able to use the `btcd` and `neutrino` code which complies with the updated cfilter BIP.

Neutrino BIP fixes

---

nursery_store.go

This commit introduces a new type called a `NurseryStore` which abstract many of the persistent operations required by the utxo nursery. The code in this commit is intentionally introduced as dead code, as the utxo nursery will later be modified to hook into the new database. It is designed to support incubation of commitment and htlc outputs, and includes full chain segmentation!
Output States
==========
- Crib Outputs: Two-stage Htlc outputs that are initially locked using a CLTV delay, followed by a CSV delay.
- Preschool Outputs: Unconfirmed commitment outputs that are locked using a CSV delay.
- Kindergarten Outputs: CSV delayed outputs for which the maturity height has been realized.
- Graduated Outputs: All outputs that have been swept back to the wallet, preceding state is …

Adds Nursery Store, preliminary step to 2nd-layer HTLC persistence

---

routing/chainview/btcd.go
routing/router.go

This PR alters the behavior of the router's logic on startup, ensuring that the chain view is filtered using the router's latest prune height. Before, the chain was filtered using the `bestHeight` variable, which was uninitialized, benignly forcing a rescan from genesis. In tracking this down, we realized that we should actually be using the prune height, as this is representative of the channel view loaded from disk. The best height/hash are now only used during startup to determine if we are out of sync.
I've also updated the logging statement to be more helpful, and only print to trace 🙂

router: prevent rescan on startup

---

lnwallet/interface_test.go

This PR adds a timeout to the `testReorgWalletBalance` test's node disconnect loop, which would otherwise cycle forever until the tests are interrupted by a timeout panic. It also makes the test look for a peer disconnection, not necessarily a peer count of 0, which is more robust in case there is a pre-existing peer connection from another source.
The PR also fixes a small variable capitalization issue caught by the linter.

lnwallet: add timeout to reorg test

---

htlcswitch/mock.go
lnwallet/btcwallet/signer.go
lnwallet/script_utils.go
mock.go

This PR makes the various signing operations within `lnd` use
signDesc.HashType instead of SigHashAll when signing
transactions. This will allow the creator of the transaction
to specify the sighash policy when creating the accompanying
sign descriptor.

Use dynamic SigHash type when signing transactions.

---

cmd/lncli/commands.go

This commit inspects the error from an RPC call, and
prints an encrypted wallet help text if the error has
status code Unimplemented. This is done to help a user
that is trying to issue lncli commands before unlocking
the wallet, since the RPC server won't be active and
every call will return this status code.
I chose not to explain the `--noencryptwallet` option,
as we want to move towards users encrypting their wallets.

lncli: Print help text in case of encrypted wallet.

---

fundingmanager.go
lnd_test.go
networktest.go
rpcserver.go

Improve integration test reliability in a few ways.
- Improve error handling for node failures in integration tests: If an lnd node encounters a fatal process errors, we now log the error asynchronously, instead of calling Fatalf on the test instance. This is because calling Fatalf in a separate goroutine does not actually end the test immediately as expected, but rather just kills the goroutine. This ensures that we see server errors on all nodes before the test process exits.
- Better error handling in lightningNode.Start(): There is an issue currently where if an error occurs in Start() before the LightningClient is initialized, the process won't be killed and the program will segfault (because Stop() tries to call a method on the nil LightningClient). This handles some of those edge …

Integration testing fixes

---

chainntnfs/btcdnotify/btcd.go
chainntnfs/interface_test.go

Came across this as I was working on https://github.com/lightningnetwork/lnd/issues/27.
As described in the commit messages, the race condition happens when a notification is being registered to the notifier at the same time as a block containing that notification is generated. This causes both the `attemptHistoricalDispatch` and the `checkConfirmationTrigger` functions to add the same confirmation intent to the confirmation heap. It's probably a fairly rare case that's more likely to come up in tests than real use, but I think the ramifications of it occurring are fairly bad.
When the tx eventually does reach the required number of confirmations, this causes the confirmation to be written to the `Confirmed` channel twice and, because the channel is buffered with a size of 1, this can …

chainntnfs: Fix btcdnotify race condition causing double heap add

---

chainntnfs/btcdnotify/btcd.go
chainntnfs/neutrinonotify/neutrino.go
chainntnfs/queue.go
chainntnfs/queue_test.go

This creates a new type implementing a concurrent-safe unbounded FIFO queue. It is used in at least one place in chainntnfs/neutrinonotify to improve efficiency and reduce complexity. 
@Roasbeef Do you think this is safe?
chainntnfs is probably not the right package for this, it's probably better off in a util package of some sort (`lnutil` maybe?). Open to suggestions on where it should live.

chainntnfs: Use new ConcurrentQueue in neutrino notifier.

---

lnwallet/wallet.go

Fix wrong calculation of overshot amount which causes coin select
function to go into infinite loop. If overshoot amount is calculated
by subtraction of `totalSatoshis` and `amtNeeded` than on the second
iteration of loop amtNeeded already include `requiredFee` inside, which
causes continuation of coin selection.

lnwallet: fix infite loop inside coin select func

---

.travis.yml
networktest.go
rpcserver.go

For a calls to ListChannels we now only set the
`ActiveChannel.Active=true` if the link is found by the
`htlcswitch`. This is done to be able to make it possible
to tell if a newly opened channel has been added to
the htlcswitch, such that we can synchronize on this
during tests before we attempt to close the channel.

Only consider channel active if added to switch

---

docker/lnd/start-lnd.sh

Fixes: https://github.com/lightningnetwork/lnd/issues/420
A back slash was missing in the `start-lnd.sh` script.

docker: add missing backslash to start-lnd.sh

---

docker/btcd/Dockerfile

The btcd docker container fails to build with Golang 1.7 because this
version of Go is missing time.Until (used by the btcd server)

docker: btcd requires Go 1.8 or newer and fails to build with 1.7

---

docs/macaroons.md

Recently we've received many questions about what macroons, how they work, how they're used in `lnd`, and our future plans for this. This PR adds a new section to the documentation explaining mcaroons written by @aakselrod.

docs: add new section for macaroons

---

lnwallet/btcwallet/signer.go

The TODO indicated that the `fmt.Errorf` call should be changed
to use the errors package, which allows for wrapping of errors
as necessary.

This removes a TODO from signer.go

---

LICENSE
cmd/lncli/main.go
config.go
lnd.go
lnwire/message.go
signal.go
version.go

Early in the lifetime of the project here were a few files we either
copied entirely, or used as the basis for code within lnd. Before this
PR, this was not recognized by retaining the original copyright. With
this commit, we remedy that by explicitly noting the copyright in the
relevant files.
Fixes #423.
cc: @davecgh @marcopeereboom

 multi: retain original copyright on files copied/modified from btcsuite

---

docs/INSTALL.md
docs/code_contribution_guidelines.md
docs/go-fuzz/README.md
docs/macaroons.md

Multiple typos fixed in 4 documents.

Fixed typos in the docs

---

lnwallet/channel.go

Properly handles the returned error from the channel sigpool's start method. The bug is currently benign, since `Start()` only ever returns nil.

lnwallet/channel: handle error from sigpool start

---

htlcswitch/interfaces.go
htlcswitch/link.go
htlcswitch/mock.go
htlcswitch/switch.go
lnwallet/channel.go
peer.go
rpcserver.go

This PR set out to remedy the issues that many users have reported surrounding their channels not being shown as "active" after the funding process has completed. 
The original logic surrounding process retransmitted `FundingLocked` message and also re-sending the message was written without mind for the requirements around re-sending the `ChannelReestablishment` message upon reconnect. This was drawn to my attention after realizing I had a flapping connection to a `c-lightning` node. The funding flow with the node didn't complete before I shutdown my local node. As a result, both nodes needed to retransmit the `FundingLocked` as we hadn't done any channel updates yet. However, my local `lnd` node was unable to do so for the following reasons:
* Before this PR, [we wouldn't add a channel …

multi: fix reliable re-processing+re-transmission of FundingLocked factoring in ChannelReestabilshment 

---

fundingmanager.go

This commit adds additional logging around the sending
of fundingLocked and channel announcements.
This should help in debugging disappearing fundingLocked 
messages, as we will have a better indication whether they
are sent or not.

[Trivial] fundingmanager: add more logging after funding confirmation

---

channeldb/invoice_test.go
channeldb/invoices.go
lnd_test.go
rpcserver.go

This PR contains two commits that resolve a TODO from `channeldb/invoices.go`: https://github.com/lightningnetwork/lnd/compare/master...mlerner:ml/settle-date?expand=1#diff-9f84ce21f17bb10010b2d2b19cb17e3cL421
1) Add `SettleDate` to the channeldb representation of an invoice.
2) Update the rpcserver so that invoice related commands map the `SettleDate` stored in the database to the RPC representation of an invoice.

channeldb: update channeldb to set and store SettleDate for invoices

---

htlcswitch/link.go

Addresses #470.
Per [BOLT-2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#updating-fees-update_fee), there seemingly aren't any issues with skipping transmission of `update_fee` in this case. Upon receipt of the next block the channel will retry to update its fee (if appropriate)

htlcswitch/link: Only send update_fee message when channel is eligable

---

docs/INSTALL.md

This is a nit-pick, but the golang-1.8-go package puts binaries in `/usr/lib/go-1.8/bin` and I was a little bit confused about that. This PR adds a small note on the problem

docs: note on golang-1.8-go bin path

---

docs/grpc/python.md

`os.path.expanduser` is needed to evaluate paths relative to the user's home directory

docs: Fix python path typo

---

server.go

This PR reorders logic in the peer termination watcher such that we short circuit earlier if we already have pending persistent connection requests. Before, the debug statement may have indicated that a reconnection was being attempted, even though it may have exited before submitting the request to the connection manager.

Improve Consistency of Logging and Actions in peerTerminationWatcher

---

lnd_test.go

This PR modifies the channel force close integration test to use the new `completePaymentRequests` method introduced by @jimpo. This helps to ensure that the timing constraints in this test are consistent with our other integration tests.

lnd_test: use completePaymentRequests in channel force close itest

---

lnd_test.go

This commit adds a small cancellation check to the invoice subscription integration test. Calls to Fatalf were observed on travis after the test had ended stemming from the subscriber's goroutine, which could happen if the subscription is late. It also extends the timeout on the test from 5 to
10 seconds.

lnd_test: invoice subscription cancel lingering goroutine

---

cmd/lncli/commands.go

Uses syscall.Stdin rather than 0 for terminal.ReadPassword() calls.
Fixes issue #498

lncli: Fix "invalid handle" error

---

server.go

This commit fixes a deadlock that could occur when
a peer disconnected during a call to sentToPeer. In
This particular case, a message would successfully
be queued, the peer would shutdown, and we would
block waiting for an error to be returned on the
message's error channel, which would deadlock.
This fixes that by also checking for peer shutdown.

[trivial] server: fix deadlock in sendToPeer at peer shutdown

---

discovery/bootstrapper.go

Use `net.JoinHostPort()` when constructing address from DNS seed. This allows for ipv6 addresses to be correctly formatted.
This should resolve #465

discovery: correctly format ipv6 addresses from dns seed

---

discovery/gossiper.go

This commit makes sure we are not attempting to create a
channel announcement with a nil ChannelAuthProof, as that
could cause a crash at startup whe the gossiper would
attempt to reprocess an edge coming from the fundingmanager.
It also makes sure we check the correct error returned from
processRejectedEdge.
Fixes the crash reported in #512

[trivial] discovery: check proof for nilness before creating chanAnn

---

cmd/lncli/commands.go

Currently `lncli closechannel` will exit and print nothing, giving the user no information.
This fixes a typo and displays the help when no args are passed.

Display help with closechannel

---

docs/grpc/python.md

added missing import, fix `;` typo in docs

docs: fix python example code issues

---

breacharbiter.go
breacharbiter_test.go
channeldb/channel.go
channeldb/db.go
fundingmanager_test.go
lnd_test.go
lnwallet/channel.go
lnwallet/channel_test.go
mock.go
peer.go
peer_test.go
server.go

This PR partially addresses #327, by completing the reliable handoff between the wallet and the breach arbiter. This is accomplished by having the breach arbiter asynchronously ack back to the wallet after successfully writing the retribution info to disk. If the channel's `closeObserver` successfully receives the acknowledgment, it will mark the channel as pending closed. Otherwise the handoff will be reattempted after the next initialization of the channel. The changes to the close observer were also ported to the sending side of the UnilateralClose channel, though the portion related to receiving the acknowledgment has been left commented out until the downstream subsystem has been made to signal back.
In order to add idempotence to the handoff, the breach arbiter now performs the same …

Reliable Breach Arbiter Handoff

---

server.go

Peers are treated as transient by default. When a peer is disconnected,
no attempt is made to reconnect. However, if we have a channel open
with a peer that peer will be added as persistent. If a persistent peer
becomes disconnected then we will attempt to reconnect.
This behavior implies that a fresh node - those without any channels -
will fall off the network over time as remote nodes restart or due to
connectivity changes. This change marks bootstrap peers as persistent
and ensures that the node remains connected to those specific peers over
time. This does not keep the node connected in the case that all
bootstrap peers are down.
This relates to #451

Add bootstrap peers to set of persistent peers for connection retry

---

lnd_test.go
lntest/harness.go

This commit adds a new test, that in a small network
of 4 nodes, tests that a private channel can be used
for routing payments by the endpoints of the channel,
while the existence of the channel is not known to
the rest of the network.

Private channel integration test

---

discovery/gossiper.go
discovery/gossiper_test.go
routing/router.go

This PR attempts to fix two flakes that often happened during tests, causing Travis to be less happy than ideal.
Before this change, announcements would be de-duped in the `gossiper` by keeping track of their `channel IDs`, and always keeping the last seen message. This is however not always correct, as some of the announcements (`channel_updates` and `node_announcements`) carry a timestamp, where newer messages invalidates all older ones. Since we never inspected the timestamp, we could end up discarding a new announcement if we got handed an old one.
This PR solves this by discarding announcements having older timestamps than what we already have in our map of de-duped announcements.
Since we potentially receive thousands of different announcements more or less at once, we let the …

Fix announcements flakes

---

lnd_test.go
lntest/node.go

This PR adds a line containing an integration test's name to Alice and Bob's log output, to help in debugging integration tests.

Add integration test case name to node output

---

lnrpc/README.md

The docs were out-of-date with the code.

rpc: remove SetAlias from the rpc docs

---

.travis.yml

Hi, 
I noticed this issue on lnd
https://travis-ci.org/lightningnetwork/lnd/jobs/329707733#L467
````0.20s$ add-apt-repository -y ppa:bitcoin/bitcoin
Error: must run as root
````
Also after fixing that ````apt-update```` gave the error in Travis: ````apt-update: command not found````
Correct me if I'm wrong but I think it should be ````sudo apt-get update````
According to Travis: https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-from-a-custom-APT-repository

Travis: fix sudo required and apt-get update command

---

zpay32/invoice.go
zpay32/invoice_internal_test.go
zpay32/invoice_test.go

This PR introduces the following changes:
- Refactor parsing each tagged field of an invoice into its own method.
- Remove duplicate code when parsing the timestamp.
- Sanity check parsing each tagged field. In this case, only: empty fallback address field and routing info field length not multiple of 51 bytes. Fixes #553.
- Properly parse the field data length. Fixes #516.
- Add unit tests for each parsed tagged field.
I think I covered all of the possible test input scenarios for parsing each tagged field, but let me know if there are any missing.
There's also a lot of overlap between `invoice_internal_test.go` and `invoice_test.go`. I'm not familiar with how we would go about simplifying that. Maybe someone with more Go knowledge could chime in here :)

invoice: refactor parsing data tagged fields and add unit tests

---

config.go
lnd.go
lntest/node.go
sample-lnd.conf

This change is to allow setting the rpc listener interface to something other than `localhost`. This is useful for containerized environments where you may need to expose the rpc server on a different interface.
This removes the `peerport` and `rpcport` flags in favor of an array of `listen`'s and `rpclisten`'s. It appears that the existing `listen` flag was not being used at all. It now mirrors the way the `btcd` flags work.
A `--restlisten` flag is added to specify interfaces to listen on for the gRPC REST proxy.
It also adds a `--nolisten` flag to disable listening on any interfaces for incoming peer connections.
This would supersede #406 if approved.
Resolves #647.

Use "listen" and "rpclisten" flags instead of of peerport and rpcport

---

config.go
lnwire/node_announcement.go
rpcserver.go
server.go
server_test.go

* This commit allows the node's 'alias' and 'color' to be configured.
* This implements the `SetAlias` command on the rpcserver and
in `lncli`.
* Adds node alias info to the output of the `getinfo` command
* ~~~Adds the '[lucasb-eyer/go-colorful](https://github.com/lucasb-eyer/go-colorful)' dependency for hex color code parsing.~~~
* Addresses #273; related to previous work of #342.
This is my first PR (substantive) to `lnd`; feedback welcomed 😄

cmd/lncli+lnd: Add alias and color customization

---

config.go

This fixes config parsing such that:
* In the case of `btcd`, `lnd.conf` or command line options MUST specify BOTH `btcd.rpcuser` and `btcd.rpcpass` in order to avoid attempting to get authentication parameters from `btcd.conf` or NEITHER to get the parameters from `btcd.conf`; otherwise an error is returned asking the user to specify both or neither.
* In the case of `bitcoind`, `lnd.conf` or command line options MUST specify ALL OF `bitcoind.rpcuser`, `bitcoind.rpcpass`, and `bitcoind.zmqpath` in order to avoid attempting to get authentication parameters and the ZMQ path from `bitcoin.conf` or NONE to get the parameters from `bitcoin.conf`; otherwise an error is returned asking the user to specify all or none.
This should fix #621 when merged; however, in order to fix the underlying …

config.go: check for RPCUser AND RPCPass (AND ZMQPath for bitcoind)

---

server.go

This commit aims to reduce the contention on the server's primary
mutex by (1) replacing it with a RWMutex, and (2) not holding an
exclusive lock throughout the duration of the SendToPeer method.
For the latter, we now only have to hold a shared lock until all
messages have been queued, where as before an exclusive lock
was held until all messages had been acknowledged by the target
peer's write handler. Since the initial syncing of announcements
with peer now comprises a couple thousand messages on testnet,
these changes should help keep the server from deadlocking while
completing any long-lived syncing operations. A couple of other
methods were also changed to only acquire shared locks where
appropriate.

Server: Reduce Contention due to Exclusive Locking

---

cmd/lncli/commands.go

typo as I referenced in https://github.com/lightningnetwork/lnd/issues/674

fix typo in Description of SendPayments

---

docs/grpc/ruby.md

This commit adds a basic set of instructions for installing the necessary
gRPC dependencies to be able to drive `lnd` using Ruby.

docs/grpc: added instructions for writing gRPC clients in Ruby

---

discovery/gossiper.go
lnd_test.go
multimutex/multimutex.go
routing/router.go

This PR fixes three bugs/flakes:
Fixes a bug that could cause announcements to get lost, and resulted in flaky integration tests.
After a set of announcements was broadcasted, we would reset (clear) the announcement batch, making any announcement that was added between the call to `Emit()` and `Reset()` to be deleted, without ever being broadcast.
We can just remove the `Reset()` call, as the batch will actually be reset within the call to `Emit()`, making the previous call only delete those messages we hadn't sent yet.
Fixes a bug within the `gossiper` where a goroutine would read the database, make some decisions based on what was read, then write its data to the database, but the read data would be outdated at this point. For instance, an `AuthProof` could have been added between …

gossiper/tests: Integration test bug/flake fixes.

---

cmd/lncli/commands.go
htlcswitch/link.go
rpcserver.go
zpay32/invoice_test.go

Fixes #564.
This PR introduces the following changes:
* Allows the creation of invoices without an amount.
* Handles incoming HTLCs paying an invoice without an amount.
* Allows payments using invoices without an amount, where the amount is specified at time of payment.
* Adds tests to decode and encode an invoice without an amount.

Support invoices without amount specified

---

autopilot/agent.go
autopilot/agent_test.go

This makes the autopilot controller re-evaluate its state in the case that it fails to open a channel. This seems to help on testnet where many nodes are not connectable.

autopilot: Make autopilot aware of channel open failures

---

docs/code_contribution_guidelines.md
lnrpc/README.md

I'm submitting these changes since I was working on another PR (#562) that involved modifying some `protobuf` definitions. I had some trouble doing so due to being new to the project.
I've confirmed the documented steps below work as intended. We could also just integrate them into `gen_protos.sh` to make things simpler. I'm open to discussion :)

docs: clarify how to generate protobuf definitions

---

brontide/noise_test.go

This adds a test of encryption/decryption of 1002 copies
of a message "hello" so as to test the test vectors in the
final section of BOLT 8 ("transport-message test").
It also corrects some typos in the preceding section of the
same function (TestBolt0008TestVectors).
(Re: the typos, you may choose to interpret it differently :) ... but at least one of the corrections there is actually necessary. I also added a sanity check of the chaining key variable, which perhaps is not needed but I guess doesn't hurt).
As a newbie to Go, I may have done something stupid here, apologies if so.
If this is useful, it might be worth adding a few more test cases to cover the remaining few error conditions that aren't yet covered in noise.go. Coverage is at 92% for that module after this.

Add tests for key rotation from BOLT8 test vectors

---

cmd/lncli/main.go
glide.lock
glide.yaml
lnd.go
lntest/node.go
macaroons/auth.go
macaroons/constraints.go
macaroons/service.go
macaroons/store.go
rpcserver.go
walletunlocker/service.go

This PR reworks the macaroon authentication framework to use the v2 macaroon format and bakery API. It also replaces the code in each RPC method which calls the macaroon verifier with interceptors which call the macaroon verifier instead. In addition, the operation permissions are reworked to fit the new format of "allow" commands (specifically, entity/operation permissions instead of method permissions).

multi: upgrade macaroons to v2, replace per-method auth with interceptors

---

chainregistry.go
config.go
lnd.go
lntest/node.go

This PR restructures the layout of the data and log directories used by lnd. The primary motivation for doing so is to separate chain-specific data from the channel graph data, which _can_ be shared across multiple chains. Chain-specific data predominately includes the `wallet.db` files, but also includes files required by neutrino when the RPC backend is not in use. 
Example of new data directory structure
----------------------------------------
```
data/
├── admin.macaroon                                                  
├── chain                                                           
│   ├── bitcoin                                                     
│   │   └── testnet                                                 
│   │       ├── block_headers.bin …
```

Cleanup Directory Structure

---

cmd/lncli/commands.go

Just like lnd --help usage and descriptions are capitalized. However with lncli --help this is not the case. This pull requests makes it just like lnd --help.

Capitalizing usage and description for lncli --help

---

docs/INSTALL.md

Remove header from bitcoind configuration example.  After doing some further testing, it seems that bitcoind will ignore the config if a header is included.  This is a followup to [PR](https://github.com/lightningnetwork/lnd/pull/702)

remove header from bitcoin conf documentation example

---

fundingmanager.go
lnwallet/wallet.go

In this commit, we modify the logic executed when we decide that we
need to fail a funding flow. Before this commit, if the remote party
disconnected while we were attempting to fail the funding flow with an
error. Then we'd never actually cancel the reservation. This meant that
any inputs selected for that transaction would be locked until a
restart.
We fix this issue by always cancelling the reservation first, and
ensuring that failure to cancel the reservation doesn't prevent us from
sending the error.
Finally, we add some additional logging on the `debug` level for 
transactions generated during the initial funding flow. 
Partially addresses #710.

funding: during funding error fail before sending Error to peer 

---

rpcserver.go

Inbound boolean is backwards internally, flip for display purposes on ListPeers.

rpcserver: flip inbound bool for display, fix internally later

---

htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/test_utils.go
lnwallet/channel.go
lnwallet/channel_test.go
lnwallet/sigpool.go
peer.go

This PR fixes a bug that could happen in some cases where we received updates from the remote peer increasing our balance.
The reason for this is that the previous version of `availableBalance` used the remote node's `logIndex` when calculating the balance currently available to us for new HTLCs. If the remote has sent us an update that _increases_ our balance, we think we have more balance available. The problem is that when the remote receives our new HTLC, it cannot know for sure if we have received the update increasing our balance, as we haven't ACKed it yet. We should therefore assume that the remote will reject the HTLC we are adding, since we don't have the balance available.
The proposed fix for this is to use the `ackedIndex` in `availableBalance` instead.
A test that makes the …

Use remoteACKed index when calculating availableBalance.

---

cmd/lncli/main.go
lnd.go
macaroons/auth.go
macaroons/service.go
macaroons/store.go
macaroons/store_test.go
walletunlocker/service.go

This PR enables macaroon root key encryption in the database to prevent attackers with access to the filesystem or backups from being able to generate their own macaroons and steal money via RPC. It makes the following changes to support this:
* Updates the `RootKeyStore` code with a `CreateUnlock()` and a `Close()` method in order to set a password, and zero the encryption key in memory on close
* Wraps the `bakery.Bakery` in a `macaroons.Service` which can pass `CreateUnlock()` and `Close()` requests to the underlying `RootKeyStore` and makes several functions into methods on the new struct (in particular, `UnaryServerInterceptor()`, `StreamServerInterceptor()`, and `VerifyMacaroon()`
* Updates the `walletunlocker` and `lncli` packages, as well as the main `lnd.go` file, to work with …

multi: macaroon root key encryption

---

routing/router.go

"we're closed" should be "were closed"

trivial: typo

---

autopilot/agent.go
autopilot/interface.go
chancloser.go
channeldb/channel.go
channeldb/channel_test.go
channeldb/db.go
channeldb/graph.go
channeldb/invoices.go
cmd/lncli/commands.go
contractcourt/channel_arbitrator.go
discovery/gossiper.go
fundingmanager.go
htlcswitch/circuit.go
htlcswitch/interfaces.go
lnrpc/rpc.swagger.json
lnwallet/btcwallet/btcwallet.go
lnwallet/channel.go
lnwallet/script_utils.go
lnwallet/wallet.go
nursery_store.go
nursery_store_test.go
routing/notifications.go
routing/router.go
rpcserver.go
server.go
utxonursery.go

I noticed a couple of places in the API documentation where "it's" was used in place of "its" so I went ahead and cleaned these up wherever I could find them in the code.

Fixing it's/its typos in comments

---

autopilot/agent.go
config.go
lnwire/lnwire.go
sample-lnd.conf

Adds color and alias examples to the sample config, closes #682 
Also clarifies the behavior of externalip when no port is specified, which caused confusion in #683, closes #651

Help text & sample config improvements

---

config.go
lnd.go

This commit adds the `tlsextraip` flag to the cli to add an
ip to the generated certificate. This is usefull when using
a loadbalancer to access the node.
Fixes #684.

config: adds an extra tls ip to config

---

utxonursery.go

Fixes a minor indexing bug that could cause the
utxonursery to accidentally overwrite CSV
witnesses with other CLTV witnesses when populating
a sweep txn. Each type of output is treated
separately internally, the bug is introduced by
using the relative indexes of both sets as the final
indexes into the txins.
The fix adds an offset, equal to the number of CSV
outputs, to the relative indexes of the CLTV inputs.
This matches the order in which CSV and CLTV outputs
are added to the raw txn.

utxonursery: fix witness overwriting bug on sweep txn

---

breacharbiter_test.go
channeldb/channel.go
fundingmanager.go
fundingmanager_test.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/test_utils.go
lnd.go
lnd_test.go
lnwallet/channel.go
lnwallet/channel_test.go
lnwallet/interface_test.go
lnwallet/reservation.go

This PR is a continuation of #371, which fixes issue #298.
~~A few TODOs are left as comments in the code, and must be addressed before merge:~~

Validate channel constraints

---

zpay32/invoice_test.go

Add encode/decode tests for non-ASCII description strings.
Closes #673. Related to https://github.com/lightningnetwork/lightning-rfc/pull/338.

zpay32: Add tests for non-ASCII(UTF-8) descriptions

---

chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/btcdnotify/btcd.go
chainntnfs/neutrinonotify/neutrino.go

In this commit, we fix a lingering bug related to the way that we
deliver block epoch notifications to end users. Before this commit, we
would launch a new goroutine for *each block*. This was done in order
to ensure that the notification dispatch wouldn’t block the main
goroutine that was dispatching the notifications. This method archived
the goal, but had a nasty side effect that the goroutines could be
re-ordered during scheduling, meaning that in the case of fast
successive blocks, then notifications would be delivered out of order.
Receiving out of order notifications is either disallowed, or can cause
sub-systems that rely on these notifications to get into weird states.
In order to fix this issue, we’ll no longer launch a new goroutine to
deliver each notification to an awaiting …

chainntnfs: ensure all block epoch notifications are sent *in order*

---

chainregistry.go
config.go
docs/configuring_tor.md
glide.lock
glide.yaml
lnd.go
lnwallet/interface_test.go
sample-lnd.conf
torsvc/net.go
torsvc/torsvc.go

In this commit, we follow up the recent addition of outbound Tor support with:
* The ability to specify _stream isolation_ for outbound connections.
* Adding example usage to `sample-lnd.conf.
* Creating a new document in the `docs` folder that walks through how to set up Tor support.
* Utilizes newly added attributes to neutrino configuration to ensure that all Bitcoin P2P traffic is also proxied over Tor if specified.  
After this PR, when users are using `neutrino` as a backend with Tor enabled, they can be sure that _all_ network traffic is properly being proxied over Tor!

tor: add stream isolation, additional documentation, neutrino support

---

cmd/lncli/commands.go
docker/README.md
fundingmanager_test.go
lnrpc/rpc.pb.go
lnrpc/rpc.proto
lnrpc/rpc.swagger.json
peer.go
pilot.go
rpcserver.go
server.go

Mentioned here: https://github.com/lightningnetwork/lnd/issues/508#issuecomment-353575130
This removes peer_id from the RPC/cli stuff and the internal usage of the peer ID, relying just on the public key
Obviously this is a breaking interface change but lnd isn't exactly stable yet so this spares any deprecation process

Remove peer_id

---

breacharbiter.go
chancloser.go
contractcourt/channel_arbitrator.go
contractcourt/contract_resolvers.go
lnwallet/btcwallet/btcwallet.go
lnwallet/interface.go
lnwallet/interface_test.go
lnwallet/wallet.go
utxonursery.go

~~This PR utilizes the new errors introduced in https://github.com/Roasbeef/btcwallet/pull/10 to properly not treat `ErrRejectDuplicate` as errors we need to take action on, as it means the transaction we are trying to publish already exists.~~
This PR adds inspection of different errors returned from the wallet backend, and adds concrete error types to `PublishTransaction`.
Needs https://github.com/lightninglabs/neutrino/pull/41.
Fixes #529.

Ignore ErrRejectDuplicate errors

---

lnwallet/btcwallet/btcwallet.go

Adds an extra case to the select statement to catch
an error produced by btcd. The error is meant to signal
that an output was previously spent, which can appear
under certain race conditions in spending/broadcasting.
This caused our final itest to fail because it would
not try to recraft the justice txn.

lnwallet/btcwallet/btcwallet: adds extra double spend case

---

docs/INSTALL.md

Reason for continuing to use the roasbeef fork of btcd is no longer segwit missing from master, but the neutrino work that is missing from master. See issue: https://github.com/lightningnetwork/lnd/issues/740

update reason for using btcd fork to be regarding neutrino additions

---

fundingmanager.go

This PR fixes two cases where the funding flow could fail, but the reservation was not cancelled, leading to locking outputs unnecessarily.

Reservation cancellation during failing funding flow

---

fundingmanager.go
fundingmanager_test.go

This is a work in progress of issue #386 
I have added a check before a channel times out that we are not the initiator for the channel.
I have added a test to check this behavior
I also fixed an issue I found in [assertNumPendingChannels](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager_test.go#L545).
The assertion could incorrect return true before a fundingmanager action had been correctly applied.
E.g If a closechannel command was tested,  closing the last remaining channel.
`assertNumPendingChannels(1)` and `assertNumPendingChannels(0)` would both return true
I can stick this in a separate issue if required

WIP: Handling non-confirmed funding transactions

---

routing/router_test.go

In `routing/router_test`  `FindRoutes` is passing `DefaultFinalCLTVDelta` in place
where `numPaths` is expected. 
This PR fixes `router_test` by passing a default `numPaths` to `FindRoutes` so that final cltv delta are correctly passed.

Fix FindRoutes in router test

---

docs/grpc/ruby.md

it looks like this field name was changed from `value` to `amt` in https://github.com/lightningnetwork/lnd/commit/ffbcf7db4f09cb932123029d201a9feef7894d7d
but this one was missed.

fix incorrect documentation in ruby.md from value to amt

---

glide.lock
glide.yaml

This commit resolves an issue where glide would try to install an older
version of x/crypto, which for me resulted in blake2b not exposing the
interfaces required by the new aezeed package. Using the explicit
version has seemed to resolve this entirely.

glide: add explicit version to x/crypto deps

---

fundingmanager.go
lnwallet/errors.go
lnwallet/interface_test.go
lnwallet/reservation.go
lnwallet/wallet.go
lnwire/error.go

This PR changes the `failFundingFlow` method to accept an error, which will
only be sent to the remote the peer if it is among the errors found in
`ReservationErrors` or `ErrorCode`. This is done to ensure we don't send
errors that contain information we don't want to leak.
Fixes #661.

Wire protocol errors

---

glide.lock
glide.yaml
keychain/btcwallet.go

This commit bumps the version of btcwallet used in lnd
to incorporate a fix for a reentry deadlock observed during
address creation.
For more information see:
https://github.com/Roasbeef/btcwallet/pull/18/

update btcwallet+keychain to include waddrmgr deadlock fix

---

htlcswitch/link.go
htlcswitch/link_test.go
lnwallet/channel.go
lnwallet/channel_test.go
lnwallet/reservation.go
lnwallet/transactions_test.go
lnwire/msat.go
zpay32/invoice_internal_test.go

In this PR, we correct a _minor_ deviation (with tangible ramifications) of our implementation from the specification. In the spec, all integers are unsigned unless otherwise state. However, our definition of `lnwire.MilliSatoshi` was an `int64`. As many of the other implementations used the equivalent of an `uint64`, users have been reporting certain compatibility issues due to this divergence. 
To remedy this, we'll now properly use:
```go
type MilliSatoshi uint64
```
Once this initial change was made, a number of bugs emerged. Many of these weren't bugs under the existing logic as negative integers were possible, and the checks assumed so. Once we moved to unsigned integers, integer underflow went silently undetected. As a result, we've tightened up several consistency checks through …

lnwire+lnwallet+htlcswitch: modify lnwire.MilliSatoshi to be unsigned, fix fee related bugs that emerged

---

glide.lock
glide.yaml
htlcswitch/failure.go
htlcswitch/iterator.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/test_utils.go
lnd_test.go
server.go

This PR adds necessary infrastructure to reliably and safely forward sphinx packets. The two changes include:
1. Encoding/Decoding of `OnionErrorEncrypter`: This will allow the switch to persist the keys required to encrypt an error to the sender in case a forwarded packet returns a failure.
2. Batched Replay Protection: Atomically compare batches of sphinx packets against a persistent log to catch replays.
Note: The shared secrets held by `OnionErrorEncrypter`s are currently stored in plaintext on-disk. I will make a follow up PR to address this, where encoding will just write the original onion packet, and decoding is followed by an additional reconstruction step to rederive the shared secrets upon startup. This extra step will occur upon startup in the newly refactored circuit map.
The …

Switch Persistence [1/4]: Infra for Sphinx Batched Decoding and Replay Protection

---

breacharbiter_test.go
channeldb/channel.go
channeldb/channel_test.go
channeldb/forwarding_package.go
channeldb/forwarding_package_test.go
channeldb/invoices.go
htlcswitch/test_utils.go
lnwallet/channel.go
lnwallet/channel_test.go

This PR lays the groundwork for integrating forwarding packages into the switch. Forwarding packages will serve as the primary component in recovering from failures, as they will hold and direct how to reconstruct the switch's in-memory state prior to a crash.
Overview
=======
After receiving a revocation from the remote party, we construct and persist a forwarding package containing all Adds, Settles, and Fails that were locked in as a result. Internally, a forwarding package treats Adds separately from Settles and Fails. This is due to the fact that these two categories of HTLCs have different semantics during forwarding:
- Adds are always propagated on a best effort basis and must pass various levels of validation. As such their final destination is not fully determined at the time …

Switch Persistence [2/4] Infra for Forwarding Packages

---

breacharbiter_test.go
htlcswitch/link.go
htlcswitch/link_test.go
lnwallet/channel.go
lnwallet/channel_test.go

This PR melds #775 and #777, by exposing the primary APIs needed to facilitate the upcoming additions to make the switch persistent. The changes are exposed in a way such that nearly all of the code is dead, but can still be built, compiled and tested using our existing test suite.
My thinking is that we can use this as a meeting point off which to base the remaining changes internal to the switch.

Switch Persistence [2.5/4]: Establish Switch-Sphinx-Wallet APIs for Switch Persistence

---

docker/lnd/Dockerfile

Per #815, https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/circuit.go#L21 depends on go version >= 1.9
Before this change:
```
Building lnd
Step 1/11 : FROM golang:1.8
...
Step 9/11 : RUN go install . ./cmd/...
---> Running in 7f5d6ac430e5
htlcswitch/circuit.go:21: syntax error: unexpected = in type declaration
ERROR: Service 'lnd' failed to build: The command '/bin/sh -c go install . ./cmd/...' returned a non-zero code: 2
```
After:
```
Building lnd
Step 1/11 : FROM golang:1.9
1.9: Pulling from library/golang
3e731ddb7fc9: Pull complete
47cafa6a79d0: Pull complete
79fcf5a213c7: Pull complete
68e99216b7ad: Pull complete
9fc7abc9c77e: Pull complete
7fefae002ae5: Pull complete
7eef770e7cf3: Pull complete
fea064ba669b: Pull complete
Digest: …
```

Update go version for Docker lnd build

---

docker/README.md

`lncli` command `walletbalance` apparently no longer supports the `--witness_only` argument. With the deprecated argument:
```
root@8a9ad8528430:/go/src/github.com/lightningnetwork/lnd# lncli walletbalance --witness_only=true
Incorrect Usage: flag provided but not defined: -witness_only
NAME:
lncli walletbalance - Compute and display the wallet's current balance
USAGE:
lncli walletbalance [arguments...]
[lncli] flag provided but not defined: -witness_only
```
After removing that argument:
```
root@8a9ad8528430:/go/src/github.com/lightningnetwork/lnd# lncli walletbalance
{
"total_balance": "1505000000000",
"confirmed_balance": "1505000000000",
"unconfirmed_balance": "0"
}
```

Remove deprecated --witness_only arg

---

docs/INSTALL.md

Ran into this issue `htlcswitch/circuit.go:21: syntax error: unexpected = in type declaration`
#815

Needs 1.9 type alias which was introduced

---

breacharbiter_test.go
channeldb/channel.go
channeldb/channel_test.go
fundingmanager.go
fundingmanager_test.go
htlcswitch/test_utils.go
lnd.go
lnwallet/channel_test.go
lnwallet/wallet.go
test_utils.go

This commit alters the behavior of the fundingmanager to
rebroadcast the funding transaction of all pending-open
channels upon restart. This is applied only to single-funder
channels for which we are the initiator, and helps ensure that
funding txns do not get stuck in the face of failures or restarts.

Rebroadcast Funding Txn

---

lnd_test.go

Simple change to move the breach retribution tests to after everything else. In the past, this has left Alice and Bob in a weird state, which seems to be causing some flakes in the switch persistence tests.

lnd_test: move retribution tests after switch persistence

---

lnwallet/interface_test.go

This commit extends the amount of time we wait for transaction to enter the mempool from 10 to 30 seconds. The wallet's interface tests seem to be particularly slow when run with the race flag, a problem which is only exacerbated by the slowness of travis.
The bug in question is:
```
--- FAIL: TestLightningWallet/btcwallet/bitcoind:publish_transaction (28.59s)
interface_test.go:1362: tx not relayed to miner: timeout after 10s
```
which can sometimes arise on neutrino as well.
With 10s and the race flag, I was able to repro the issues locally fairly consistently. I have not seen it arise with the longer timeout.

lnwallet/interface_test: extend publish timeout

---

fundingmanager.go
htlcswitch/link.go
lnwire/channel_id.go
peer.go

This adds functionality in the peer for inspecting the `channelID` of a received error message, and handing it off to the `fundingmanager` in case of a pending channel ID, or the `channelLink` otherwise. It also handles the case of an all-zero channel ID, meaning that it should be forwarded to all channels with the peer.
Logic is also added to the `link`, in order to fail the channel in the event of receiving the error.

Wire error handoff

---

cmd/lncli/main.go
config.go

In this PR, we introduce new configuration flags in order to specify the base directory for `lnd` and supported backend nodes (i.e. `btcd`, `bitcoind`, etc.).
Currently, there's no way to have all of `lnd`'s data under a single directory other than just using the default. This PR introduces a new flag to modify that. This is especially useful for testing environments, where you wish to have everything contained within a specific directory. Fixes #248.
Also, there's no way of pointing `lnd` to use a specific `bitcoind` datadir. Some users have set paths other than the default for different purposes. This PR introduces a flag to the supported backend nodes to help remedy that. Fixes #670.

config+cmd/lncli: add flags to specify the base directory for lnd and supported backend nodes

---

htlcswitch/link_test.go

This commit increases the time we wait for a message to be sent for
several test cases, aiming to decrease the false negative rate on
Travis.

link test: increase timeout for message sends

---

fundingmanager.go
fundingmanager_test.go
lnd.go
lnwallet/reservation.go
lnwallet/wallet.go

In this PR, a timeout is added to each `ChannelReservation`, which cancels the reservation when reached. On each successive message in the `ChannelReservation` workflow the timeout is reset, so that timeouts only occur after an idle period in the workflow.
This PR takes care of #60. Instead of creating a goroutine that periodically sweeps any zombie reservations, this PR adds a timer to each reservation, which cancels the reservation when it expires. In that way, a zombie reservation will be cleaned up (and thus resources freed up) as soon as possible.

funding: implement reservation zombie sweeper

---

chainparams.go
chainregistry.go
keychain/btcwallet.go
keychain/interface_test.go
lnwallet/btcwallet/btcwallet.go
lnwallet/btcwallet/config.go
lnwallet/btcwallet/signer.go
lnwallet/interface_test.go

In order to support independent key derivation for both BTC and LTC, this PR adds the ability to parameterize keyrings generated by the new `keychain` package using a BIP 44 coin type. Each of our chain params now carries `CoinType` field, which is passed down to the btcwallet using `activeNetParams`. Three coin type constants are now defined in the `keychain` package, in accordance with [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md):
1. `keychain.CoinTypeBitcion = 0`
1. `keychain.CoinTypeTestnet = 1`
1. `keychain.CoinTypeLitecoin = 2`
The `keychain` tests have been extended to also test derivation for each of these scopes.

Configurable CoinType for HD Derivation

---

Gopkg.lock
Gopkg.toml
routing/chainview/bitcoind.go

Since `btcwallet` now requires `NotifyBlocks()` to be called with the `bitcoind` back-end, the `bitcoind` implementation of `routing/chainview` needs to call it. This PR enables that.

routing/chainview: bitcoind back-end now requires explicit `NotifyBlocks()`

---

lnd_test.go

This commit removes two unnecessary disconnect/reconnect attempts
from the switch itest. Both occur after the primary test has been
completed, and were being executed before doing a final sanity check
that the path is still usable. Nothing about the test behavior should
change.
Honestly don't remember the reason they were added in the first place,
might have been stragglers. This should fix an issue where the final payment
reports `UnknownNextPeer` due to the links not having fully reactivated.

lnd_test: removes unnecessary disconnects from switch itest

---

chainregistry.go
config.go
docs/INSTALL.md
fundingmanager.go
fundingmanager_test.go
lnd.go
rpcserver.go

Adds `litecoind` backend and configuration for `lnd`. Internally, this uses the same driver as `bitciond`, so we are able to reuse the majority of the logic. The node configuration options have also been expanded to include `ltcd` and `litecoind` distinctly.
The supported backend types are:
- `bitcoind.node=[btcd|bitcoind|neutrino]`
- `litecoind.node=[ltcd|litecoind]`
supporting analogous configurations to `bitcoind`, e.g.
- `litecoind.rpcuser`
- `litecoind.rpcpassword`
- `litecoind.zmqpath`
- etc.
Note, due to some limitations of the cli tooling, both will display `[btcd|bitcond|neutrino|ltcd|litecoind]` as options, but will fail if backends for the wrong chain are swapped.
I've also moved the majority of the chain-related constants into `chainregistry.go`, and updated them to include …

Litecoind Backend

---

discovery/gossiper.go

Fixes a typo in the log message formatting.

discovery: format log message with Errorf

---

docs/INSTALL.md

The port numbers used in the ZMQ examples are inconsistent between:
- The initial explanation of ZMQ
```
They must be combined in the same ZMQ socket
address (e.g. `--zmqpubrawblock=tcp://127.0.0.1:28332` and
`--zmqpubrawtx=tcp://127.0.0.1:28332`).
```
- The sample bitcoin.conf
```
zmqpubrawblock=tcp://127.0.0.1:18501
zmqpubrawtx=tcp://127.0.0.1:18501
```
- The lnd command-line example:
```
lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=REPLACEME --bitcoind.rpcpass=REPLACEME --bitcoind.zmqpath=tcp://127.0.0.1:28332 --externalip=X.X.X.X
```
I changed the sample bitcoin.conf port numbers to 28332 so they match the rest of the examples.

Docs: Inconsistent ZMQ port numbers in examples

---

sample-lnd.conf

It looks like, since https://github.com/lightningnetwork/lnd/pull/506, `defaultchanconfs` is nested under `bitcoin`. Using this parameter at the top level generates a warning message:
```
2018-03-17 23:07:08.273 [WRN] LTND: /home/bitcoin/.lnd/lnd.conf:7: unknown option: defaultchanconfs
```
and using it nested under `bitcoin` does not.

move defaultchanconfs setting in sample-lnd.conf to bitcoin section

---

macaroons/store.go

Solves the issue [mentioned in Slack](https://lightningcommunity.slack.com/archives/C6BKD3RKR/p1521328392000048) where if the wallet unlocker is unable to bind to any ports at startup then this store will be Close()'d even though it was never unlocked, causing a panic.

macaroons: don't attempt zeroing key from mem if it doesn't exist

---

peer.go

In this commit, we fix a goroutine leak that could occur if while we
were loading an error occurred in any of the steps after we created the
channel object, but before it was actually loaded in to the script. If
an error occurs at any step, we ensure that we’ll stop toe channel.
Otherwise, the sigPool goroutines would still be lingering and never be
stopped.

peer: ensure we stop the channel if error happens in loadActiveChannels

---

config.go
lnd.go

Self explanatory.
Needed for NodeJS, as the grpc library only allows TLS connections to domains and not IP addresses.
https://github.com/grpc/grpc/issues/2691

[Feature] Add TLSExtraDomain to config

---

config.go
fundingmanager.go
pilot.go
rpcserver.go

In this PR, we raise the min channel size to 20k satoshis. This
will be evaluated before we check for dusty commitments. The goal of
this is to ensure ample room for fees at current, and future fee
levels.
We also, we add two new configuration parameters to allow users
to specify the min and max size that the autopilot agent will create.
This is useful as now users can set the values to more or less the same
size, which will allow them to control the size of each created
channel.
Before this commit, if this wasn’t set, then the agent would try to
shove as much money into a channel up until the max chan size. This was
nice on testnet, but on main net, users will likely not want all their
funds to be in a single channel, and instead be distributed across many
channels. With things like AMP, …

funding+pilot: increase min channel size, allow specifying chan size range for autopilot

---

routing/errors.go
routing/router.go
routing/router_test.go

In this PR, we add a new field to the LightningPayment struct:
PayAttemptTimeout. This new field allows the caller to control exactly
how much time should be spent attempting to route a payment to the
destination. The default value we’ll use is 60 seconds, but callers are
able to specify a diff value. Once the timeout has passed, we’ll
abandon th e payment attempt, and return an error back to the original
caller.
In this PR, we also address a number of edge cases that were unaccounted
for when responding to errors that can be sent back due to an HTLC
routing failure. Namely:
* We’ll no longer stop payment attempts if we’re unable to apply a
channel update, instead, we’ll log the error, prune the channel and
continue.
* We’ll no remember which channels were pruned due to insufficient
fee …

routing: add timeout during pay attempts, don't exit if unable apply update, account for all onion errors 

---

config.go
lnd.go
rpcserver.go

In this PR, we add a new default macaroon type: `invoice.macaroon`. The capabilities that this macaroon can unlock are restricted only to: listing invoices, generating invoices, subscribing for invoice notifications, and also generating new addresses. 
We've received several requests from those working to integrate `lnd` into their exchange or merchant workflow to have an macaroon that can _only_ generate invoices. The advantage of this is that a developer can provision a box or process, that can speak to `lnd` but _only_ to generate new invoices, or to poll for the status of existing invoices. This is a boon for security as it implements a strict separation of invoices, allowing services to create isolated instances with locked down permission only sufficient to carry out their task. …

rpc+lnd: add new invoice-only macaroon

---

docs/grpc/python.md

In this PR, we add an example of how to use macaroons with the python grpc library. 
In this PR, we also update the python grpc example to use the correct cipher suite to ensure the ssl handshake works. The current example code does not work with the latest version of LND.
In this PR, we also update python 2 syntax to python 3.

docs: add macaroon example to python docs, update syntax to python 3

---

docs/code_contribution_guidelines.md

NetworkHarness file seems to be moved from `networktest.go` to `lntest/harness.go`
ref) `fd4af6d`

docs: Update old link to networkHarness framework

---

lnwallet/channel.go
lnwallet/channel_test.go

This PR attempts to fix a number of issues that would arise because we allowed creating and receiving HTLC signatures that didn't match the number of HTLC outputs on the commitment.
Fixes #547

HTLC number mismatch fixes

---

routing/pathfind.go
routing/pathfind_test.go
routing/router.go
routing/router_test.go
routing/testdata/basic_graph.json

In this PR, we reverse an existing assumption in the codebase: if we ever get a non-final CLTV related routing error, then we're at fault as we're not yet properly synced to the chain. Since this assumption was added, we actually ensure that we're fully synced to the chain, before the rest of the daemon starts up, so this assumption is no longer valid. 
As is now, if we attempt to route through a node that doesn't know what the current height is well cease payment attempts all together as it was assumed be a terminal error. This PR fixes that by simply pruning away nodes that disagree with our view of the current chain, allowing us to route around these faulty nodes. We also add a test case that failed before this new modification. The test ensures that we'll properly route around nodes …

routing: route around height disagreements during htlc routing attempts 

---

config.go

Fixed formatting for autopilot config params, as well as added check for
`MaxChannels` param which was presumably a mistaken copypaste from the
`MaxChannelSize' param.

config: Fix formatting, missing param check.

---

config.go

Fix #915 by capturing the current daemonName and using that in
error messages.

Fix error labels when missing LTC configuration

---

breacharbiter_test.go
lnd_test.go
lnwallet/btcwallet/blockchain.go
lnwallet/btcwallet/btcwallet.go
lnwallet/channel_test.go
lnwallet/interface_test.go

In this PR, we fix an existing rounding related bug in the codebase.
The RPC interface for btcd and bitcoind return values in BTC rather than
in satoshis. So in several places, we're forced to convert ourselves
manually. The existing logic attempted to do this, but didn't properly
account for rounding. As a result, our values can be off due to not
rounding incorrectly.
The fix for this is easy: simply properly use btcutil.NewAmount
everywhere which does rounding properly.
Fixes #939.

 lnwallet: use btcutil.NewAmount for BTC -> SAT conversions

---

chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/btcdnotify/btcd.go

This PR attempts to fix a race that could occur during integration tests, where the backend would respond to a `NotifySpent` call before we had added the `spendNotification` to our map of clients, resulting in the notification being lost.

Add spend notification to client map before recording it with backend

---

htlcswitch/switch.go

Missing space results in `unable to get channel links: unable to locate channel link bydestination hop id` log messages

htlcswitch: trivial whitespace

---

chainregistry.go

When in neutrino mode, it seems that the node is not closed during the cleanup, so if a block is received between the time the DB is closed and the server is closed (or if the process is still running after the server is shutdown like on a mobile app), the code panic's and crashes with:
panic: unable to write block header: database not open
goroutine 41 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).handleHeadersMsg(0x9a1ec0a0, 0x9a3e6030)
/ext-go/1/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:1164 +0x2224
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).blockHandler(0x9a1ec0a0)
/ext-go/1/src/github.com/lightningnetwork/lnd/vendor/github.com/lightning …

Neutrino, stop the chainservice before node DB.

---

channeldb/channel.go
channeldb/channel_test.go

Modifies the MarkAsOpen operation to also update the ShortChanID and IsPending fields in-memory. Before, only the on-disk representation was updated, which may have lead to stale data channel states being passed in-memory.

channeldb: update ShortChanID in-mem during MarkAsOpen

---

rpcserver.go

This signal is no longer needed, as the breacharbiter is given
the UnilateralClosure chain event.

[mini] rpcserver: remove uneccessary signal to breacharbiter at force close

---

Makefile
cmd/lncli/main.go
lnd.go
version.go

This commit continues the work started by @sp4ke, in creating
a simple Makefile for lnd. The following commands are included:
Building
=====
* `make` - builds everything (deps, lnd, and lncli) from scratch
* `make deps` - installs dep if needed, then runs dep ensure
* `make install` - builds lnd and lncli
Testing
=====
* `make check` - runs unit and itests
* `make unit` - runs the unit tests for all packages
* optional `pkg=<subpackage>`
* optional `case=<unit-test-case-regex>`
* `make itest` - installs lnd and runs integration tests
* optional `icase=<integration-test-case-regex>`
Util
===
* `make fmt` - go fmt's all files
Compiling `lnd` and `lncli` with the Makefile will now inject the most recent commit hash! See `lnd --version` and `lncli --version`.

Makefile w/ dep

---

contractcourt/chain_watcher.go

This PR sets the `Curce` of the `DoubleTweak` keys in `breachRetribution` to `nil`, as it would cause massive log spam, and cause timing issues within some of the integration tests.

[mini] contractcourt/chain_watcher: don't print curve of DoubleTweak

---

docs/grpc/python.md

In this PR, we fix incorrect usage of `decode` where it should have been `encode` when converting a macaroon from binary to hex. Also include `import codec` so the macaroon reading example can be copied pasted directly.
Sorry for typos in previous PR :)

docs: encode macaroon in python grpc example

---

contractcourt/channel_arbitrator.go

This commit mitigates a problem within the ChannelArbitrator, where
after a restart we would start up in the state StateBroadcastCommit but
fail to broadcast out commitment because a conflicting transaction (most
likely our own commitment) was already broadcast. A more complete fix
for this case will be added later, but this commit let the
ChannelArbitrator continue, trying to close out the channel.
Partially mitigates #880 before the bigger `contractcourt` revamping is landed.

contractcourt/channel_arbitrator: ignore ErrDoubleSpend on force close

---

rpcserver.go
zpay32/invoice.go
zpay32/invoice_internal_test.go

In this commit, we fix a logic error in our routine for converting a
uint64 to/from base32. Before this commit, we assumed that the max
number of groups was 12. However, the math.MaxUint64 (1<<64 - 1) can
actually consume more than 12 groups with an extra set of bits. Before
this commit, we would panic when attempting to parse an invoice
generated like so:
* addinvoice --amt 1337000 --expiry 99999999999999999
To fix this issue, we modify our logic to expect at most 13 groups.
Additionally, we've added a new test that would panic before applying
this commit.
As an additional layer of defense, we'll reject any expiry greater 
than 1 year.
Fixes #972.

zpay32+rpc: ensure we can encode an expiry of math.MaxUint64, limit to 1 year in seconds

---

fundingmanager.go
fundingmanager_test.go
lnd.go
lnd_test.go
lntest/harness.go
lntest/node.go
server.go

Complementary to #981.
This commits changes the behavior of our connection
reestablishment, and resolves some minor issues that
could lead to uncancelled requests or an infinite
connection loop.
- Will not attempt to Remove connection requests with
an ID of 0. This can happen for reconnect attempts
that get scheduled, but have not started at the
time the server cancels the connection requests.
- Adds a per-peer cancellation channel, that is
closed upon a successful inbound or outbound
connection. The goroutine spwaned to handle the
reconnect by the peerTerminationWatch now
selects on this channel, and skips reconnecting
if it is closed before the backoff matures.
- Properly computes the backoff when no entry in
persistentPeersBackoff is found. Previously, a
value of 0 would be returned, …

server: cleanup persistent connection retries

---

fundingmanager.go
lnd.go
server.go

This PR sets out to fix a number of issues that have been reported related to the way we attempt to automatically re-establish connections to: persistent peers that disconnect from us, and also persistent peers that we have channels open with. 
First, we'll no longer add boostrap peers to out set of persistent connections. We do this as the only peers that we're concerned with, are the ones that we have channels open with. This had also caused issues if the chosen peers were incompatible with us for w/e reason, which would cause us to continually re-connect to them over and over again. 
Additionally, we'll now look up the "proper" port of a peer for reconnection purposes. This ensures that when a peer disconnects, even if it was an inbound connections, we'll use the correct port when …

server+connmgr: fix issues w.r.t automatically re-establishing connections. 

---

config.go

If only a port is given as a config value for a listener we'll default to only binding that port to localhost.
#734

config: default naked ports to localhost

---

config.go

`lnd` can't detect `bitcoind` configuration if the config file has spaces around the `=` character, e.g.:
```ini
zmqpubrawblock = tcp://127.0.0.1:28332
zmqpubrawtx = tcp://127.0.0.1:28332
rpcuser = rpcuser
```
I had to dig into the source code to understand what was wrong.
This patch solves this problem, bitcoind's config parsing source code can be seen at https://github.com/bitcoin/bitcoin/blob/master/src/util.cpp

Support space characters surrounding = in bitcoind configuration files

---

brontide/listener.go
brontide/noise_test.go

Addresses #994 by buffering incoming brontide handshakes asynchronously.

brontide/listener: make handshake asynchronous

---

docs/INSTALL.md

Attempt # 2 with no git history
Install docs needed path
```
cd $GOPATH/src/github.com/lightningnetwork/lnd
```
before `git pull` instructions

Correcting install docs to add path for upgrade instructions section

---

htlcswitch/interfaces.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
lnwallet/channel.go
lnwallet/sigpool.go
peer.go

In this PR we fix a slight bug that would at times mean that we drop a connection _before_ an error we intend to send has been delivered. As a result of this bug, if we rejected a commitment, then the remote party may never actually get an error, resulting in a potential connection loop. 
We fix this issue by allowing callers to decide if `SendMessage` should block until completion or not. 
We also add a new `InvalidHtlcSigError` to allow other implementations to more easily debug _why_ an HTLC sig was invalid.

htlcswitch+lnwallet: ensure the Error is sent to remote peer before d/c, add detailed err for htlc sig rejection

---

lnd_test.go
lnwallet/channel.go
lnwallet/channel_test.go

In this commit, we fix an existing bug w.r.t to the way we handle certain classes of contract breaches. Before PR this commit, within NewBreachRetribution the order of the keys when generating the sender HTLC script was incorrect. As in this case, the remote party is the sender, their key should be first. However, the order was swapped, meaning that at breach time, our transaction would be rejected as it had the incorrect witness script.
We first include an extension to one of the revocation integration tests to trigger a failure. We do this by sending a new set of HTLCs from Carol to Dave (in addition to the ones from Dave to Carol), such that, the final breached commitment has HTLCs in both directions. 
We then including a commit with the fix: swap the ordering of the keys. After this …

lnwallet+test: properly generate the sender HTLC script in a contract breach scenario

---

docker/btcd/start-btcctl.sh
docker/btcd/start-btcd.sh
docker/lnd/start-lnd.sh
docker/ltcd/start-ltcctl.sh
docker/ltcd/start-ltcd.sh

It is better to replace bash shell with potentially long-running
last script command. This way the running command will receive all
potential unix process signals directly.
A concrete example which motivated this change:
Exec of btcd is needed for graceful shutdown of btcd during
`docker-compose down`. Docker Compose properly sends this signal to our
start-btcd.sh bash shell but it is not further signalled to the running
btcd process. Docker Compose then kills whole container forcefully after
some timeout.
An alternative solution would be to trap SIGTERM in our bash script and
forward it to running btcd. Which would be IMO ugly and error prone.

docker: replace bash shells with last command

---

aezeed/README.md
aezeed/cipherseed_test.go

I added the text that @Roasbeef wrote in his PR #773 as a README in the `aezeed` package.
Also I added some tests and test vectors, removing one of the TODOs that was in the test.
Additionally, the test file had a typo in it.

aezeed: add tests and README

---

htlcswitch/switch.go

In this commit, we fix an issue where users would be displayed negative
amounts of satoshis either as sent or received. This can happen if the
total amount of channel updates decreases due to channels being closed.
To fix this, we properly handle a negative difference of channel
updates by updating the stats logged to only include active
channels/links to the switch.
Fixes #998.

htlcswitch: fix periodic calculation of satoshis sent/received

---

.gitignore

This stops ripgrep from complaining about
invalid use of **; must be one path component
See https://github.com/BurntSushi/ripgrep/issues/373

lnd: use single asterisk for gitignore wildcards

---

breacharbiter.go
chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/btcdnotify/btcd.go
chainntnfs/interface.go
chainntnfs/interface_test.go
chainntnfs/neutrinonotify/neutrino.go
contractcourt/chain_arbitrator.go
contractcourt/chain_watcher.go
contractcourt/contract_resolvers.go
discovery/gossiper_test.go
fundingmanager_test.go
mock.go

This PR adds a new bool `mempool` to the `RegisterSpendNtfn` method, making it possible to tell the backend to only notify spends on block inclusion of the spend transaction. Prior to this, `btcd` would always notify when a spend entered the mempool, `neutrino` would notify only on block inclusion, while `bitcoind` also only notifies on block inclusion (as far as I can tell, at least that was what I was able to do during tests).
This is a stepping stone for getting all the backends to act similarly with regards to spend notifications, enabling them all for the integration tests. Note that this PR doesn't change the behaviour of the notifiers if `mempool=true`, and still `btcd` is the only notifier that will notify on mempool spends.
The reason we make mempool spend notifications optional, …

chainntnfs: optionally only notify spends on block inclusion

---

config.go
log.go
sample-lnd.conf

Adding possibility to configure more how many logs to keep, or to disable deletion of all logs alltogether, with the new config option maxlogfiles (0 = disable deleting old files)
Adding maxlogfilesize (in MB)

Make log rotation configurable

---

fundingmanager.go
fundingmanager_test.go
lnwallet/reservation.go

This PR fixes a few bugs that could occur when the user specified a custom value for `remote_csv_value` or `min_htlc_msat`. We wouldn't preserve these custom values properly, and instead use the default values when later trying to create a commit transaction. This lead to the local and remote node creating incompatible commitments, leading to channel breakdown.

[bugfix] Custom remote_csv_delay and min_htlc_msat

---

Gopkg.lock
Gopkg.toml

Once this is merged in, the default version of `neutrino` packaged with `lnd` will now be fully compliant with the latest versions of BIP157 and BIP 158. 
NOTE: **if using neutrino after this merged in, you'll need to _wipe_ the old cfindex, then rebuild**

build: update to point to BIP158+BIP157 compliant btcd+btcutil+neutrino

---

discovery/gossiper.go
htlcswitch/interfaces.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/switch.go
htlcswitch/test_utils.go
lnd_test.go
lnwire/short_channel_id.go
peer.go
routing/router.go
routing/router_test.go
rpcserver.go

In this commit, we fix an existing bug in the forwarding logic in the link. Before this commit, we would actually apply the fee policies of the _incoming_ link when accepting new HTLC's. This was incorrect as we should actually be applying the fees of the _outgoing_ link, as we'll be using that link's payment bandwidth to support the HTLC. This bug cause a ton of issues when routing on mainnet, as we would reject an HTLC for violating the policy of the incoming link, then send the policy of the incoming link. The router would them prune the _outgoing_ link, as that is the proper policy that _should_ have been applied. This process would then at times repeat tens of times, until we gave up with a timeout error. 
To fix this issue, we've added a series of new methods to the link and switch …

htlcswitch: properly apply the fee constraints of the *outgoing* link when accepting HTLC's

---

contractcourt/chain_arbitrator.go
contractcourt/channel_arbitrator.go
lnwallet/channel.go

This commit renames ForceCloseSummary to LocalForceCloseSummary, and
adds a new method NewLocalForceCloseSummary that can be used to derive a
LocalForceCloseSummary if our commitment transaction gets confirmed
in-chain. It is meant to accompany the NewUnilateralCloseSummary
method, which is used for the same purpose if a remote commitment is
seen in-chain.
This PR is a building block for an upcoming, larger change to the `contractcourt` package, where we will only act on a channel's commitment that gets confirmed in-chain. In this case it will be useful to fetch a `LocalForceCloseSummary` if we find our commitment in-chain, without having to "ForceClose" the channel a second time.

[refactor] lnwallet/channel: add NewLocalForceCloseSummary

---

fundingmanager.go

This commit fixes an issue in funding manager startup,
where a goroutine reads from a range value. The method in
question could cause a channel to be announced at the
wrong time.
This may have been a cause for certain channels having
phantom HTLCs before they had even received the funding
locked message from the remote peer.
This is fixed simply by using the locally scoped
variable passed in as an argument to the goroutine.

fundingmanager: fixes range-goroutine scoping bug

---

contractcourt/chain_watcher.go

Adds some missing calls to `Unlock` in `contractcourt/chain_watcher` when returning while mutex is held.

contractcourt/chain_watcher: release mutex on return

---

docs/macaroons.md

The invoice.macaroon feature was added in PR https://github.com/lightningnetwork/lnd/pull/904 but there is no reference to this on the current documentation, this PR is a small change to let know to the user that this option is available.

Add reference to invoice.macaroon in macaroon documentation file

---

contractcourt/chain_arbitrator.go
contractcourt/chain_watcher.go
lnd_test.go

In this PR, we extend the closeChannelAndAssert testing utility
function to ensure that the channel is no longer marked as "pending
close" in the database. With this change, we hop to catch a recently
reported issue wherein users report that a co-op close channel has been
fully confirmed, yet it still pops up in the `pendingchannels` command.
In this PR, we fix a long standing bug where at times a co-op
channel closure wouldn't be properly marked as fully closed in the
database. The culprit was a re-occurring code flaw we've seen many times
in the codebase: a closure variable that closes over a loop iterator
variable. Before this instance, I assumed that this could only pop up
when goroutines bind to the loop iterator within a  closure. However,
this instance is the exact same issue, but …

contractcourt: fix co-op chan close issue by not closing over loop iterator variable

---

chainntnfs/btcdnotify/btcd.go
chainntnfs/interface_test.go

This commit fixes a recently introduced bug (https://github.com/lightningnetwork/lnd/pull/969) in the btcdnotifier, where
we would skip all spend clients waiting for a confirmed spend in
txUpdates. The regular case where a spend is included in a new block was
correctly handled in onBlockConnected, but the txUpdates queue is also
used for confirmed spends during rescans, which we would miss. This
commit fixes that by checking if the tx update is confirmed or
unconfirmed, and acts accordingly.

Notify on confirmed spends during btcd rescans

---

zpay32/invoice_test.go

Issue: https://github.com/lightningnetwork/lnd/issues/882
Blocked by: https://github.com/Roasbeef/btcd/pull/19
In this pull request was only added tests to check correctness of prefix in encoded invoice

Wrong BOLT11 prefix in regtest

---

docs/grpc/javascript.md

Shout out to @adrienemery for updating the python docs AND providing info in this thread: https://github.com/lightningnetwork/lnd/issues/861#issuecomment-373811976
In order to prevent other users from missing the `GRPC_SSL_CIPHER_SUITES` changes due to https://github.com/lightningnetwork/lnd/pull/776, i've added documentation to the JS/NodeJS examples.
In this PR
1. we add an example of how to use macaroons w/ js grpc
2. update the nodejs grpc example to use the correct cipher suite w/ `GRPC_SSL_CIPHER_SUITES`. The current example code does not work w/ current LND

updated js docs for macaroons and grpc ssl cipher

---

docs/code_contribution_guidelines.md

According to install.md, the minimum version of Go supported at the 
moment is 1.9, so update the Go version referenced in Contribution 
Checklist to 1.9 as well.

docs: update Go version to 1.9 in Contribution Checklist

---

lnd.go

GOMAXPROCS will be set automatically after Go 1.5. The minimum version
supported at the moment is 1.9, so setting GOMAXPROCS to NumCPU is not
necessary anymore.

main: Stop setting GOMAXPROCS to NumCPU explicitly

---

server.go

The current user-facing error message when a user attempts an operation on a non-connected peer is confusing: "unable to find peer". This message suggests to the user that the peer is not present/accessible on the Internet at all, when in fact the peer is not connected.
A new wording of "peer is not connected" is proposed. In fact the comment on the error constant is in line with the new wording ("signals that the server has no connection to the given peer."). This PR proposes a less confusing wording in the interest of improving the user experience.
Example command to verify the new error message:
`lncli openchannel 039cc950286a8fa99218283d1adc2456e0d5e81be558da77dd6e85ba9a1fff5ad3 --local_amt 100000 --push_amt 0`
This PR is part of the general initiative to improve lnd error messages …

server: change PeerNotFound to PeerNotConnected

---

zpay32/invoice.go

When using invoice.Decode, for instance with "lncli decodepayreq", if the network of the invoice does not match the active network, an error message of "wrong network" will be returned. Unfortunately this error message is not detailed enough to indicate to the user what they have done wrong (see conversations on LND slack). This PR provides a more descriptive error message to decrease user confusion.
Example command:
`lncli decodepayreq lnbc10u1pdd8ksmpp5gaektzj5krc6hykdayavctnwk33sm8385dq7nt7gp6a8uylyullsdp9gdhkjmnsv9hxjceqgdhk6mt4de5hg7fqffshycqzysvee2c49hz0wuzrggrntmc4p8ppk880ekhagre5sd9kk3hmt35dzjgzw5p2sp7vp9fnzhzly76yn89qmx0577tpeqnq5u02zzg57fj9sp8yyffl
`
Old output:
`[lncli] rpc error: code = Unknown desc = unknown network`
New output:
`[lncli] rpc error: code = Unknown desc = …

invoice: improve "wrong network" error message

---

cmd/lncli/commands.go

The current cli docs for closechannel do not indicate where to find eligible funding_txids nor that funding_txids are also called channel_points, depending on context. This PR aims to clear up that confusion.

lncli: make locating funding_txids easier

---

lnd_test.go
rpcserver.go

In this PR, we fix a recently introduced bug that could lead to a panic when including the routing hints in an invoice.
A test case has also been added to ensure the routing hints are added correctly.

rpcserver: add missing continue if link wasn't retrieved from the switch

---

routing/router.go
routing/router_test.go

In this commit we fix an lingering bug in the Mission Control logic we execute in response to the FailUnknownNextPeer error. Historically, we would treat this as the _next_ node not being online. As a result, we would then prune away the vertex from the current reachable graph all together. It was recently realized, that this would at times be a bit _tooo_ aggressive if the channel we attempt to route over was faulty, down, or the incoming node had connectivity issues with the outgoing node.
In light of this realization, we'll now instead only prune the _edge_ that we attempted to route over. This ensures that we'll continue to explore the possible edges. Additionally, this guards us against failure modes where nodes report FailUnknownNextPeer to other nodes in an attempt to more closely …

routing: stop pruning edges in response to FailUnknownNextPeer

---

docs/grpc/javascript.md

Creating and adding metadata in single line resulted in null `metadata`

doc: Correct javascript macaroon example

---

lnd_test.go

This commit removes the mining of a block within the integration tests, that
would lead to a flake during runs. The reason was that the sweeoing
transaction was actually broadcast already at this point, and this block
was mined with the assumption that it wasn't. However, test would pass
more often than not because the UTXO nursery would be working on
graduating new heights, whcih is a bit slow, so in most cases the block
would be mined before it had broadcast the sweeping transaction.
By removing this block we ensure that the sweeping transaction will be
found for sure in the waitForTxInMempool call below.

Integration tests: remove racy block generation

---

lnd_test.go
lntest/harness.go
lntest/node.go

Addresses #1134.
Now the log file names look like this:
```text
output-0-Bob-00000000.log
output-1-Alice-00000000.log
output-1-Alice-02d80659.log
output-2-Carol-00000000.log
output-3-Carol-00000000.log
output-4-Carol-00000000.log
output-5-Carol-00000000.log
output-6-Carol-00000000.log
output-7-Carol-00000000.log
output-8-Carol-00000000.log
output-9-Carol-00000000.log
...
```
I suspect that this might also solve #1133. I cannot say with certainty what the problem with termbin is, but I suspect that the files `output0.log` and `output1.log` just got too big and therefore couldn't be uploaded any more (maybe there is a size limit at termbin?).
Now, the output of node 0 and 1 are split into several files, so they remain smaller. But proper investigation is still necessary to not just postpone …

Integration tests: give nodes a name and print that name in log file name

---

.travis.yml

As mentioned in #1133, the log files of the integration tests should be uploaded when run on TraviCI.
But this fails as the service [termbin](http://termbin.com) seems to truncate files after 1MB and refuse upload of files bigger than 16MB.
What I propose here is a very simple fix:
Upload all log files to [file.io](https://file.io) as well as termbin.
Their service allows for files up to 5GB and sets a default expiration of 14 days (could be configured if that is not enough).
The output would look something like this:
```
{"success":true,"key":"25Sosc","link":"https://file.io/25Sosc","expiry":"14 days"}
```
Advantages:
* Integration test log files can be viewed again
* No additional maintenance script to delete old files is needed
* Free service with a nice attitude: 
> It was created …

Integration tests: upload logs from TravisCI to file.io as well

---

docs/INSTALL.md

Using localhost to connect lnd to bitcoind on Windows is very slow.  Use 127.0.0.1 instead.
Fixes #1177. 
Fixes #1027.

docs/INSTALL: add advice for using 127.0.0.1 for bitcoind backend

---

cmd/lncli/commands.go

As reported in #1191, if you issue the `unlock` or `create` command again after the wallet is already unlocked, you get a strange error message:
```
[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.
```
This is because the `UnlockerService` is shut down after successful unlock and therefore the unlock commands aren't recognized on the gRPC interface any more (status=Unimplemented).
I improved the error message for this special case since the current message is very misleading.
Fixes #1191.

lncli: improve error message for unlock commands

---

docs/code_contribution_guidelines.md

From reading the contribution guidelines, it was not really clear to me that lines of code should not be longer than 80 characters and that the tab character should be counted as 8 chars.
So after asking @halseth in the chat, we agreed that this should be mentioned in the guidelines.

docs: add line wrap to contribution checklist

---

discovery/gossiper.go
routing/router.go
routing/validation_barrier.go
routing/validation_barrier_test.go

This commit improves the shutdown of the router's
pending validation tasks, by ensuring the pending
tasks exit early if the validation barrier
receives a shutdown request.
Currently, any goroutines blocked by `WaitForDependants`
will continue execution after a shutdown is signaled.
This may lead to unnexpected behavior as the relation
between updates is no longer upheld. It also has the
side effect of slowing down shutdown, since we
continue to process the remaining updates.
To remedy this, `WaitForDependants` now returns an error
that signals if a shutdown was requested. The blocked
goroutines can exit early upon seeing this error,
without also signaling completion of their task to
the dependent tasks, which should will now properly
wait to read the validation barrier's quit signal.

router: Validation Barrier Shutdown

---

htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/switch.go
peer.go
server.go

In this commit, we ensure that any time we send a TempChannelFailure
that's destined for a multi-hop source sender, then we'll always package
the latest channel update along with it.
Fixes #1126.

htlcswitch+server: ensure we always send an update w/ a TempChannelFailure

---

htlcswitch/link_test.go
lnwallet/channel.go

This commit removes a faulty check we did to determine if the channel
commitments were fully synced. We assumed that if out local commitment
chain had a height higher than the remote, then we would have state
updates present in our chain but not in theirs, and owed a commitment.
However, there were cases where this wasn't true, and we would send a
new commitment even though we had no new updates to sign. This is a
protocol violation.
Now we don't longer check the heights to determine if we are fully
synced. A consequence of this is that we also need to check if we have
any pending fee updates that are nopt yet signed, as those are
considered non-empty updates.
Fixes #1127

Empty commitsig fix

---

routing/chainview/neutrino.go

This commit alters the neutrino chainview such that it caches the filter entries corresponding to watched outpoints at the moment they are added to the filter. Previously, we would rederive each filter entry when reconstructing the relevant filter entries, which would lead to unnecessary work on the gc. Now, each is created at most once, and reused across subsequent reconstructions.

routing/chainview/neutrino: cache filter entries

---

peer.go
server.go

This commit adds a simple scheduling mechanism for
resolving potential deadlocks when dropping a stale
connection (via pubkey inspection).
Ideally, we'd like to wait to activate a new peer until
the previous one has exited entirely. However, the current
logic attempts to disconnect (and wait) until the peer
has been cleaned up fully, which can result in
deadlocks with other portions of the codebase, since
other blocking methods may also need acquire the mutex
before the peer can exit.
When existing connections are replaced, they now
schedule a callback that is executed inside the
peerTerminationWatcher. Since the peer now waits for
the clean exit of the prior peer, this callback is
now executed with a clean slate, adds the peer to
the server's maps, and initiates peer's Start() method.

server: Peer Async Disconnect w/ Scheduled peerConnected

---

docs/INSTALL.md

The make file contains installing lncli, which has to be installed manually when not using make.

docs/INSTALL: update non-make installation to include lncli

---

docs/INSTALL.md

This PR adds a note about not connecting too many consumers of the `bitcoind` RPC (LND or otherwise) for fear of missing crucial updates.  If you check bitcoind's documentation, it says the default number of threads for the RPC is 4.  I'm making the assumption that one `lnd` instance will only consume one thread.
If this assumption is wrong, this PR will need to be adjusted to reflect the maximum recommended number of `lnd` instances.
Some related discussion and testing in #1174.

Update Bitcoind docs with a note about multiple LND instances

---

fundingmanager.go
fundingmanager_test.go
lnd.go
lnwallet/errors.go
lnwallet/fee_estimator.go
lnwallet/interface_test.go
lnwallet/reservation.go

In this PR, we fix an issue where sometimes transactions wouldn't provide enough of a fee to be relayed by the backend node. This was caused due to `bitcoind` no longer using the minimum relay fee when estimating fees (see https://github.com/bitcoin/bitcoin/commit/fd29d3df299bd06c0e6bb218863e0c855b3b91af). This would especially cause issues when sweeping outputs after a contract breach, etc. Now, we'll fetch the minimum relay fee from the backend node and ensure it is set as a lower bound if the estimated fee ends up dipping below it.
We also enforce that the channel reserve is above the dust limit. The minimum channel size has also been modified to reflect this change. This allows us to avoid dust outputs from being created in the commitment transactions. This fixes some incompatibility …

lnwallet: enforce fee floor and dust-reserve adherence

---

docker/lnd/Dockerfile

PR closes #1167.  Only modified the `lnd` Dockerfile.
Functionally identical to before.  Changes are:
* Copies the repository into the container before building, to allow local changes to be used.
* Uses alpine containers for smaller resultant images
* Uses a disposable build container for even smaller resultant image.

Docker: Build LND locally rather than pulling down from GitHub

---

docs/macaroons.md
lnd.go
macaroons/README.md
macaroons/constraints_test.go
macaroons/service.go
macaroons/service_test.go
rpcserver.go

This is an extension/replacement for PR #344.
With permission of @mrwhythat I have integrated his commits and updated his work to the current state of the `macaroons` package.
Unfortunately, with the upgrade to macaroons v2 not much of his initial commits remain. Should they still be included to give him credit for his work?
Also I added a more technical documentation in the README.md of the `macaroons` package.
An integration test as mentioned in #284 is still missing. But I am working on that and will create another PR once I'm finished.

macaroons: add unit tests and documentation

---

lnwallet/channel.go
lnwallet/channel_test.go

This PR attempts to fix a lingering bug within `channel.go` where the log counters would get out of sync with the HTLCs in the index after a restore.
Additionally, we remove some redundant restoration code to simplify the logic.
Fixes #1247 
(potentially also fixes #1124).

HTLC restoration

---

walletunlocker/service.go
walletunlocker/service_test.go

Replace hard coded internal version with KeyDerivationVersion specified
in keychain package.

walletunlocker: use KeyDerivationVersion for generating cipher seed

---

docs/INSTALL.md

Currently, the `lnd` docs state ZMQ is "likely enabled" if you compile 'bitcoind' from source, yet the `bitcoind` build docs do not all explicitly mention installing the ZMQ library. 
In the `bitcoind` docs, the [`build-unix.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md) has explicit instructions to install ZMQ, but the [`build-osx.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md) and [`build-windows.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md) do not mention it at all.  
So it is actually quite easy to compile from source without ZMQ enabled (and `bitcoind` will function just fine without it). Doing so results in a `connection refused` error when `lnd` attempts to connect to the localhost on startup, and this …

Update docs with more detailed info for ZMQ support

---

channeldb/channel.go

In this commit, we modify the existing updateChanBucket function to no
longer auto-create buckets if they don't exist. We do this in order to
fix a class of bug that could arise wherein after a channel has actually
be closed (and the parent buckets removed) a method that mutates the
channel state is called, which then re-creates the relevant set of
buckets. As a result, subsequent calls to any RPCs which need to read
all the channels will fail as most of the fields won't actually be
populated.
After this commit, the fullSync method is the only one that's able to
create the full bucket hierarchy.

channeldb: modify updateChanBucket to no longer auto-create buckets

---

docker/btcd/Dockerfile
docker/lnd/Dockerfile
docker/ltcd/Dockerfile

Similar to #1169 but implements multi-stage builds and alpine containers for btcd and ltcd.
Before:
```
btcd                   latest          7eefac9c9dd2        2 minutes ago       917MB
ltcd                   latest          8315899a2994        3 minutes ago       895MB
```
After:
```
btcd                   latest          8ca9cde8a96b        3 minutes ago        56.5MB
ltcd                   latest          532bd4f40cef        3 minutes ago        42.5MB
```
Also includes a fix for an issue in `lnd`'s Dockerfile related to recent changes to the Makefile that no longer creates binaries in the main directory.

Docker: Use multi-stage builds and Alpine containers for btcd and ltcd

---

lnd.go
server.go
signal.go

lnd: add interrupt handler to handle shutdown requests while syncing chain backend

---

lnd.go

nitspick
```
$ lnd --bitcoin.active --bitcoin.simnet ...
...
2018-05-24 01:14:14.503 [INF] LTND: Version 0.4.1-beta commit=
2018-05-24 01:14:14.503 [INF] LTND: Active chain: Bitcoin (network=simmnet)
```

lnd: fix typo in log message on launch

---

breacharbiter.go
chancloser.go
channeldb/channel.go
contractcourt/chain_arbitrator.go
contractcourt/chain_watcher.go
lnd_test.go
lnwallet/channel.go
peer.go
rpcserver.go

This PR fixes an issue where we could go through a cooperative close, and marking the channel as closed in the DB before it was confirmed. This would lead to potential issues as we wouldn't start the necessary submodules to watch for the final close on restarts. 
In #1017 we changed the definition of a closed channel to be a channel that has had its closing tx confirmed. This PR makes this true also for cooperative closes.

[bugfix] Wait for confirmation before marking channel cooperatively closed

---

contractcourt/channel_arbitrator.go
htlcswitch/hodl/config.go
htlcswitch/hodl/flags.go
htlcswitch/hodl/mask_test.go
htlcswitch/interfaces.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/linkfailure.go
htlcswitch/mock.go
lnd_test.go
peer.go

This PR adds the option to force close a channel in case of a failure within the link. Now calls to `fail(...)` will always mark the channel inactive and disconnect the peer, and can optionally force close the channel.
Putting PR up to get some initial feedback.

[htlcswitch] Optionally force close channel on link failure

---

lnwallet/channel.go
lnwallet/channel_test.go

This PR fixes an issue that would cause us to forward a settle or fail prematurely, i.e. we would forward a settle or fail before it was fully committed by both commitment transactions. 
Previously, we had such a check for `Add` htlcs, and ensure that neither the `addCommitHeightRemote` and `addCommitHeightLocal` were both non-zero.  Here, we add the same constraints to `removeCommitHeightRemote` and `removeCommitHeightLocal`.
We also change the logic around when an `Fail` or `Settle` should be forwarded by requiring equality between the remote height and `removeCommitHeightRemote`. Currently, we use `>=` to determine when we should forward an HTLC in order to mimic the logic for `Add`s.
This change is more minor, and shouldn't result in any observed difference in behavior, but should …

[lnwallet] Only Forward Committed Settles and Fails

---

lnwallet/channel.go
lnwallet/channel_test.go

This commit fixes a bug which would cause the add heights of the HTLCs
in the update log to be set wrongly. At times, an add height could be
incorrecly set, leading to the HTLCs not being accounted for correctly
during evaluating the HTLC views. This was caused by the assumption that
if the HTLC was not on the pending remote commit, then it was locked in
on both the local and the remote commit, which is not always true.
Instead of making this assumption, we instead now inspect the three
commits: the local, remote and pending remote; and set the add heights
accordingly. This should ensure that HTLCs are subtracted from the
balances only when they are first added.
Fixes #1293. 
Fixes #1267. 
Fixes #1261. 
Fixes #1292.

lnwallet/channel: set add heights based on the locked in commits

---

fundingmanager.go
fundingmanager_test.go
server.go

This PR consists of several commits meant to simplify and reduce the cases where we can end up deadlocking on sending errors on the error channels within `fundingmanager`. 
The biggest change is that we now determine whether to send on the `resCtx.err` channel inside `failFundingFlow`.
After this change we will send on the `resCtx.err` channel only _after_ a call to `cancelReservationCtx`, making sure it won't be attempted again (which would cause a deadlock).
We also increase the buffer of the `updateChan` to 2, so we can safely send on it during the funding workflow without blocking.
Fixes #1254.

Reduce fundingmanager chan send deadlock scenarios

---

docs/DOCKER.md

Link must be /docker/README.md, relative to the repository's root. Previously it was relative to /docs, resulting in 404.

Fixed link to /docker/README.md

---

lnwallet/channel.go
lnwallet/channel_test.go

We check if the channel is FullySynced instead of comparing the local
and remote commit chain heights, as the heights might not be in sync.
Instead we call FullySynced which recently was modified to use compare
the message indexes instead, which is _should_ really be in sync between
the chains.
The test TestChanSyncOweRevocationAndCommitForceTransition is altered to
ensure the two chains at different heights before the test is started, to
trigger the case that would previously fail to resend the commitment
signature.

[bugfix] lnwallet/channel: use FullySynced to check chanSync special case

---

rpcserver.go

In this commit, we fix an existing panic bug related to the recently
added routing hints feature. If it's the case that the remote node
didn't send us their edge, then when we go to compare the public keys to
see if they match, we may attempt to deref an nil pointer.
In order to fix this, we'll instead check the edgeInfo, which is
guaranteed to also exist if the channel was found in the database. As a
defensive step, before we go to actually aces the struct, we'll check
that's it's non-nil and proceed if it is nil.

rpc: ensure we don't attempt to create a routing hint with a nil edge

---

discovery/gossiper.go
discovery/syncer.go

In this commit, we fix an existing deadlock in the
gossiper->server->peer pipeline by ensuring that we're not holding the
syncer mutex while we attempt to have a syncer filter out the rest of
gossip messages.

discovery: ensure gossiper syncer has idempotent exit/start, fix deadlock 

---

channeldb/waitingproof.go

In this commit, we modify the waiting proof slightly to acept dupliacte
waiting proofs, rather than reject them. Otherwise, it's possible that
the remote node first sends us their half of the waiting proof (before
we do), we write that to disk, then upon restart, we'll try to add it
again, but be rejected by the system.
Fixes #1315.

channeldb: don't reject duplicate waiting proofs

---

channeldb/waitingproof.go

This commit synchronizes the in-memory cache with the
on-disk state to ensure the waiting proof store is
externally consistent. Currently, there are scenarios
where the in-memory state is updated, and not reverted
if the write fails. The general fix is to wait to apply
modifications until the write succeeds, and use a
read/write lock to synchronize access with db operations.
NOTE: This should rebased after #1323 to match the
behavior wrt. accepting duplicate waiting proofs.

channeldb/waitingproof: improve external consistency of store

---

rpcserver.go
server.go

This PR attempts to fix a small bug where inbound peers were being tracked as outbound and outbound as inbound.
I went through the rest of the connection logic and our uses of inbound/outbound connections seem to be consistent with their respective meanings. Inbound connections should be connections initiated by the remote peer, while outbound connections should be initiated locally.
I believe the small patch below should be enough to remedy this issue, although I might have missed something.
Fixes #997.

server: fix inbound/outbound peer connection logic

---

htlcswitch/link.go

This commit removes a possible deadlock in the switch,
which can be triggered under certain failure conditions.
Previously, we would acquire the link's read lock for
the duration of HtlcSatisfiesPolicy, though we only
need to use it grab the current policy. The deadlock could
be caused in the cases where we attempt to log the failure,
which access the read-protected ShortChanID method.

htlcswitch/link: remove deadlock in htlc validation

---

fundingmanager.go
htlcswitch/link.go

In this commit, we add and enforce a min fee rate for commitment
transactions created, and also any updates we propose to the remote
party. It's important to note that this is only a temporary patch, as
nodes can dynamically raise their min fee rate whenever their mempool is
saturated.
Fixes #1330.

funding+htlcswitch: enforce min fee rate of 253 sat/kw on commitments

---

discovery/gossiper.go
discovery/gossiper_test.go
htlcswitch/interfaces.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/test_utils.go
lnpeer/peer.go
peer.go
server.go

This PR alters the gossiper such that it can send direct messages to a remote peer without needing to acquire the server's lock in the majority of cases. Currently, each call to `server.SendToPeer` acquires the server's mutex to obtain the active peer, which causes contention especially during initial sync w/o the newer optimized graph sync protocol.
To accomplish this, the primary interface for peers has been moved to a new `lnpeer` package. For now, this houses only the interface, though a later refactoring would move the current logic into `lnpeer`, and further flesh out the appropriate interfaces. This allows two of the primary subsystems that send wire messages (the htlcswitch and gossiper) to share a common interface, `lnpeer.Peer`.
`lnpeer.Peer` is mostly a direct copy of the …

discovery: bypass server for direct message sends

---

htlcswitch/switch.go
htlcswitch/switch_test.go

Alters the htlcswitch to reject duplicate links and purge all link indexes upon removal. Previously we would only purge either the live or pending indexes.
Fixes #1348. 
Fixes #1342.

Switch duplicate links

---

discovery/gossiper.go
htlcswitch/switch.go
htlcswitch/switch_test.go
lnd_test.go
lntest/harness.go
lnwallet/channel.go
peer.go
server.go

Fixes #1337. 
Fixes #1360. 
Fixes #1361. 
Fixes #1365. 
Fixes #1366.

test+server: finalize inbound/outbound fixes, update itests to account for fixes

---

cmd/lncli/commands.go

I have heard too many people being confused about this. I believe this belongs in the help text of openchannel command.
Fixes #1259.

Add clarification for push_amt argument to openchannel

---

Gopkg.lock
Gopkg.toml
config.go
docs/nat_traversal.md
lnd.go
lnwire/node_announcement.go
nat/pmp.go
nat/traversal.go
nat/upnp.go
sample-lnd.conf
server.go

In this PR, we address the following:
* Add new flags and documentation to toggle UPnP and NAT-PMP support.
* Add two different NAT traversal techniques: UPnP and NAT-PMP.
* Automatically detect the public facing IP address, using the specified NAT traversal technique, and advertise it to the network.
* Watch for dynamic IP changes periodically and broadcast a new node announcement with the updated IP address.
This currently does not support devices behind multiple NATs and will likely be not supported. Ideally, we can avoid this with the use of hidden services.
I would appreciate testing using the NAT-PMP technique as I do not have compatible equipment to do so.
Replaces #518, fixes #185.

server: add support for NAT traversal and watching dynamic IP changes

---

lnd_test.go
lntest/node.go

This PR adds to commits to ensure proper cleanup during integration tests:
1. We shut down nodes created temporarily during the test cases using defers instead of at the end of the test. This makes it easier to remember to shut them down, as it is done right after they are started.
2. We add shutdowns for a few nodes that were missing it.

integration tests: shut down nodes using defer

---

discovery/bootstrapper.go
server.go

In this commit, we address an existing issue with regards to the inital
peer bootstrapping stage. At times, the bootstrappers can be unreliable
by providing addresses for peers that no longer exist/are currently
offline. This would lead to nodes quickly entering an exponential
backoff method used to maintain a minimum target of peers without first
achieving said target.
We address this by separating the peer bootstrapper into two stages: the
initial peer bootstrapping and maintaining a target set of nodes to
maintain an up-to-date view of the network. The initial peer
bootstrapping stage has been made aggressive in order to provide such
view of the network as quickly as possible. Once done, we continue on
with the existing exponential backoff method responsible for maintaining
a target …

server: improve initial peer bootstrapping

---

rpcserver.go

rpcserver: return err when paying 0 amt invoice and amt is not specified

---

htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/switch.go
htlcswitch/switch_test.go
htlcswitch/test_utils.go
peer.go
server.go
test_utils.go

In this PR, we modify the behavior of links updating their commitment fees. Rather than attempting to update the commitment fee for each link every time a new block comes in, we'll use a timer with a random interval between 10 and 60 minutes for each link to determine when to update their corresponding commitment fee. This prevents us from oscillating the fee rate for our various commitment transactions.
We also move the block height dependency from the links in the switch to the switch itself. This is possible due to a recent change on the links no longer depending on the block height to update their commitment fees. We'll now only have the switch be alerted of new blocks coming in and
links will retrieve the height from it atomically.
Fixes #1129.

htlcswitch: randomize link fee updates

---

lntest/harness.go

This commit adds a poll 20 ms interval to WaitPredicate, similar to what
is done for WaitInvariant. This makes the predicate not being checked
super-rapidly, potentially filling the logs with useless info over the
wait predicate interval.

lntest/harness: add pollIntervall to WaitPredicate

---

htlcswitch/link.go
htlcswitch/link_test.go

I added some basic table driven tests for `ExpectedFee` in htlcswitch/link.go

htlcswitch: add basic table driven tests for ExpectedFee

---

utxonursery.go

Alters the utxonursery to rebroadcast finalized sweep txns
that sweep kindergarten (CSV-delayed) outputs. Currently, we
reregister for confirmation notifications, but we make no
attempt to rebroadcast. The htlc-timeout transactions are
rebroadcast correctly, so this changes make the handling of
crib and kinder outputs symmetric on startup.
Fixes #1305

utxonursery: rebroadcast finalized kinder txns on startup

---

fundingmanager.go
peer.go

Fixes a nil dereference + cleanup of channel shutdown on error in `fundingmanager`.

[bugfix] Channel stop bugfixes

---

channeldb/channel.go
channeldb/channel_test.go

In this PR, we improve the consistency of a channel's forwarding packager. Each `ChannelPackager` maintains the short channel id of the channel it managers. We made recent changes to improve the consistency of update a channel's short channel id, and refreshing any changes from disk. However, these updates were never carried over to the `ChannelPackager`'s short channel id.  FWIW, this problem has existed even before these changes, though now the solution is done in tandem with the existing serialization points.
Two assertions have been added to `TestRefreshShortChanID`, ensuring that the packager's short channel id is updated. Checking out the commit with the tests shows these assertions failing, which are then fixed with the changes to `channeldb/channel.go`.

Update channel packager sid

---

lnwire/lnwire_test.go
lnwire/query_short_chan_ids.go

In this commit, we implement zlib decoding and encoding for the `EncodingSortedZlib` encoding type. Before this commit, we only supported the sorted plain encoding. When decoding we utilize an `io.LimitedReader` to ensure that we can precisely (as much given the runtime+GC) control how much memory we allocate during decoding. On top of that, we also add a package level mutex to limit the total number of decoding instances to one. This ensures that we don't multiply our allocation limit across all peers.

lnwire: implement cautious zlib decoding for channel range queries

---

htlcswitch/switch.go

In this commit, we modify the removeLink method to be more asynchronous.
Before this commit, we would attempt to block until the peer exits.
However, it may be the case that at times time, then target link is
attempting to forward a batch of packets to the switch (forwardBatch).
Atm, this method doesn't pass in an external context/quit, so we can't
cancel this message/request. As a result, we'll now ensure that
`removeLink` doesn't block, so we can resume the switch's main loop as
soon as possible.
Fixes #1441.

htlcswitch: in removeLink use new goroutine to stop existing link

---

breacharbiter.go
breacharbiter_test.go
mock.go

This commit handles a racy condition within the breacharbiter's justice
tx procedure. For backends that have no mempool we would check if an
HTLC output was spent and then try broadcasting the justice tx, but this
would fail since we wouldn't detect the spend before it was in a block.
The result was that we would continuously attempt to broadcast the
transaction, effectively ending up in an endless (until the second-level
tx actually comfirmed).
Instead we now register for spend notifications in case broadcasting the
transaction fails, and then wait for any of the notifications to be
sent before trying again.
This is a necessary step to be able to make lnd work well only with
confimed transactions, and was a better solution than introducing
timeouts within the broadcast loop (which …

breacharbiter: wait on spend events instead of timeout

---

cmd/lncli/main.go
config.go
lncfg/address.go
lncfg/address_test.go
lnd.go
sample-lnd.conf
server.go

This PR fixes #1224.
Thanks a lot to @Richard87 for [his initial proposal](https://github.com/lightningnetwork/lnd/pull/495#issuecomment-355931289), I was able to use quite a lot of that code.
As described in the issue, Unix sockets are only supported for the gRPC and REST listeners. It doesn't make sense for the p2p listener to listen on an Unix socket.
Currently, TLS cannot be disabled on any of the servers, not even for the loopback interface. So the same applies for Unix sockets, they still require a client certificate to connect.

rpc: add support for unix sockets

---

config.go
lncfg/address.go
lncfg/address_test.go
server.go

In this PR, we attempt to fix a regression w.r.t. parsing and resolving onion addresses throughout the config introduced in the unix sockets PR. We now properly parse and resolve onion addresses and set of tests has been added to ensure this.

lncfg+config: parse and resolve onion addresses

---

lnd_test.go
routing/pathfind.go
routing/pathfind_test.go

This PR fixes two problems in the routing package:
- Fee calculation for a hop does not include the fee that needs to be paid to the next hop
- The incoming channel capacity "sanity" check does not include the fee to be paid to the current hop
It also updates the multi hop payment integration test to cover the fee miscalculation.

routing: fix route fee calculation and channel capacity check

---

routing/pathfind.go
routing/pathfind_test.go

Fixes https://github.com/lightningnetwork/lnd/issues/1346
This PR:
- implements a new weight function
- contains a unit test that failed with the previous weight function and succeeds after this change
- alternative way to build a channel test graph in code
The reason for creating an alternative method to build the test graph is that the current json file contains info that is not relevant for the unit test (pubkeys, channel id, channel point, flags). This makes it harder to maintain and also more difficult to understand the structure.
In this PR these non-relevant properties are (deterministically) generated at run time. 
Then there was still the choice whether to stick with json or move the graph definition to go code. In my opinion, expressing the graph in go code can make it easier to …

routing: routing may come up with suboptimal routes (weight function)

---

docs/INSTALL.md

This PR simply adds instructions for those that're running Windows WSL (Bash on Windows), and are having trouble running the make command, which seems to be a common issue.

Add make instructions for Windows WSL users

---

htlcswitch/link.go
htlcswitch/switch.go
routing/router.go
rpcserver.go

I was profiling single hop throughput the other day and noticed a few easy low hanging fruits to increase perf a bit:
1. In many areas were were using `spw.Sdump` _without_ wrapping the call in a `newLogClosure` instance. As a result, even if the log level wasn't hit, we'd still incur the expensive calls to the `reflect` package.   
2. The call to update the database in `ackSettleFail` wasn't using `Batch`, so as a result, it would cause multiple goroutines trying to send an HTLC to block. 
As a bonus, the `--debughtlc` flag now works again!

htlcswitch+routing: minor forwarding perf improvements

---

lnwire/lnwire_test.go
lnwire/query_short_chan_ids.go

Modifies the behavior of the quick test for
MsgQueryShortChanIDs, such that the generated
slice of expected short chan ids is always nil
if no elements are returned. This mimics the
behavior of the zlib decompression, where
elements are appended to the slice, instead of
assigning to preallocated slice.
We also alter the behavior of the regular
short channel id encoding, such that it returns a nil
slice if the decoded number of elements is 0. This is
done so that it matches the behavior of the zlib
decompression, allowing us to test both in using the
same corpus.

[lnwire]: align behavior of query sids corpus for zero-length slices

---

config.go

In the event that the default Tor DNS host wouldn't resolve, it would
prevent `lnd` from starting due to the failed lookup. This should fail
silently as it's only crucial during bootstrapping. However, if the user
has explicitly modified this, we should let them know of the error
immediately.
Related to #1463.

config: only normalize and resolve tor DNS host if it has changed

---

server.go

Noticed we were printing the byte slices, instead of hex strings

server: log pubkey hex in connection callbacks

---

invoiceregistry.go

format comment to match function casing (`AddDebugInvoice`) and clarify grammar as to what are able to obtain the proper preimage

update comment for AddInvoice

---

channeldb/addr.go
channeldb/addr_test.go
channeldb/channel.go
channeldb/codec.go
channeldb/forwarding_log.go

Adds `net.Addr` and `[]net.Addr` to the channeldb codec.
Builds on #1457 and #1454

channeldb: expand codec to include net.Addr types

---

fundingmanager.go

In this commit, we fix an issue where we would always assume the dust
limit was Bitcoin's dust limit, rather than the active chain. This would
lead to issues when attempting to open channels on the Litecon chain.

fundingmanager: determine our dust limit based on active chain

---

routing/chainview/bitcoind.go
routing/chainview/btcd.go

Modifies granularity of chainview filter locking for btcd and bitcoind, such that a lock is only acquired once per block connected/filter update. Also fixes a bug (likely benign) that could cause spent outputs to linger in the filter map.

[routing/chainview] improve filter locking granularity in btcd/bitcoind

---

discovery/gossiper.go
discovery/gossiper_test.go
fundingmanager.go
fundingmanager_test.go
htlcswitch/link_test.go
htlcswitch/mock.go
lnd.go
lnpeer/peer.go
peer.go
server.go

In this PR, we introduce a similar optimization to the one done in #1345. Currently, each call to `server.SendToPeer` acquires the server's mutex to obtain the active peer. We work around this by passing the `peer` struct itself within the internal `fundingManager` messages.
Fixes #1495.

fundingmanager: send messages directly to peers

---

invoiceregistry.go

In this commit, we update the main invoiceEvents channel within the
invoiceregistry to now have an initial buffer size of 100. We do this as
it's been reported by users that on start up they're unable to actually
create or settle invoices manually. Traces have shown that this is due
to contention while holding the invoice mutex. To attempt to solve this,
we add an additional buffer to the channel as most sends will now be
routinely non blocking.

invoiceregistry: make the invoice ntfn chan buffered

---

channeldb/graph.go
channeldb/graph_test.go
routing/router.go

IN this PR, we extend a recently merged PR to prune all unconnected graph vertexes on start up, just as we do for link nodes which on longer have an active channel. This change ensures that we maintain a compact lively channel graph at all times. 
Fixes #1607.

channeldb+routing: prune unconnected graph vertexes on start up 

---

breacharbiter.go
chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/btcdnotify/btcd.go
chainntnfs/interface.go
chainntnfs/interface_test.go
chainntnfs/neutrinonotify/neutrino.go
contractcourt/chain_arbitrator.go
contractcourt/chain_watcher.go
contractcourt/chain_watcher_test.go
contractcourt/contract_resolvers.go
discovery/gossiper_test.go
fundingmanager_test.go
htlcswitch/mock.go
lnd_test.go
lntest/node.go
mock.go

This PR removes the option to register spend notifications that will be triggered on spends detected in the mempool. This is done to ensure unified behavior across all backends, as they don't necessarily (most notably Neutrino) have a mempool.
This is a step in enabling integration tests also with `bitcoind` and `neutrino` backends.
The commits are linearly ordered in such a way that one–by–one spend registration is changed over from a mempool spend to a confirmed spend, accompanied by any test changes that are needed to make them pass. This means that any commit that doesn't have a corresponding test change, **_should_** pass the tests without additional changes. 
Finally we remove the option for mempool spends altogether, when all usages are eliminated.
The most notable test change is …

Only act on confirmed spends

---

breacharbiter.go
lnwallet/size.go
utxonursery.go

In this commit, we correct our size estimates for to-local scripts,
which are used on the commitment transaction and the htlc
success/timeout transactions. There have been observed cases of
transactions getting stuck because our estimates were too low, and cause
the transactions to not be relayed.
Our previous estimate for the commitment to-local script was correct
though comment had outdated script. Though the estimate is greater
than the actual size, this has been updated with a proposed estimate
of 79 bytes.
This estimate makes the assumption that CSV delays will be at most
4 bytes when serialized. Since this value is expressed in relative block
heights, this should be more than sufficient for our needs, even though
the maximum possible size for the little-endian int64 is 9 bytes (plus …

lnwallet/size: correct commit to-local and 2nd stage script/witness sizes

---

rpcserver.go

AddInvoice with zero or negative values result in a strange error message:
also negative values are implicitly converted to uint in NewMSatFromSatoshis(), that leads to incredibly high amounts.

AddInvoice: check for negative amt

---

htlcswitch/hodl/config_debug.go
htlcswitch/hodl/config_production.go

This PR places the `hodl.Config` struct behind a build flag,
so that the command line flags are hidden in production
builds.
```
Production help before commit:
Tor:
--tor.active
--tor.socks=
--tor.dns=
--tor.streamisolation
--tor.control=
--tor.v2
--tor.v2privatekeypath=
--tor.v3
hodl:
--hodl.exit-settle
--hodl.add-incoming
--hodl.settle-incoming
--hodl.fail-incoming
--hodl.add-outgoing
--hodl.settle-outgoing
--hodl.fail-outgoing
--hodl.commit
--hodl.bogus-settle
Help Options:
-h, --help
Production help after commit:
Tor:
--tor.active
--tor.socks=
--tor.dns=
--tor.streamisolation
--tor.control=
--tor.v2
--tor.v2privatekeypath=
--tor.v3
Help Options:
-h, --help
```

Hide hodl config production

---

make/testing_flags.mk

go test's default timeout is 10m, which is no longer enough during
integration tests. This commit increases it to 20m.

make: if timeout not set, use 20m instead of default 10m

---

htlcswitch/link.go
htlcswitch/link_test.go

This PR corrects our exit hop logic to return
FailFinalExpiryTooSoon if the following check is true:
```golang
pd.Timeout-expiryGraceDelta <= heightNow
```
Previously we returned FailFinalIncorrectCltvExpiry, which
should only be returned if the packet was misconstructed.
Fixes #1615

[htlcswitch/link] use FailFinalExpiryTooSoon as exit hop

---

lnd_test.go

This commit makes sure the channels that are force closed also are put
into the state "waiting close" before the commitment transaction is
confirmed, and exits this state when it confirms.
This was previously not checked, as this check was added before the
"waiting close" state was introduced.
Also fixes #1627

[integration tests] assert waiting close also for force closes

---

routing/router.go
routing/router_test.go

In this commit, we add an additional defensive guard within `generateSphinxPacket` to ensure a caller of over the RPC interface cannot cause `lnd` to panic due to under-specifying the required set of inputs. 
Fixes #1651.

routing: ensure generateSphinxPacket can handle being passed empty set of routes

---

discovery/gossiper.go

Corrects an instance that holds a reference to a boltdb
byte slice after returning from the transaction. This
can cause panics under certain conditions, which is
avoided by creating a copy of the key.

discovery/gossiper: copy bolt key to prevent panic

---

htlcswitch/link.go
htlcswitch/link_test.go
peer.go

In this commit, we prevent the htlcManager from
being woken up by the batchTicker when there is no
work to be done. Profiling has shown a significant
portion of CPU time idling, since the batch ticker
endlessly demands resources. We resolve this by only
selecting on the batch ticker when we have a
non-empty batch of downstream packets from the
switch.

htlcswitch/link: conditional batch ticker

---

channeldb/channel.go
channeldb/db.go
contractcourt/chain_watcher.go
htlcswitch/link.go
htlcswitch/link_test.go
lnd_test.go
lnwallet/channel.go
lnwallet/channel_test.go
peer.go

This PR implements the logic required for "data loss protection", as described in BOLT#2: https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#message-retransmission
When syncing channel states we will now detect the cases where _we_ probably have lost our local state, meaning broadcasting our commitment would be unsafe as it could be considered a breach. Instead we store the `my_current_per_commitment_point` sent to us by the remote in the database. This commitment point can later be used to reclaim our funds if the remote party decides to unilaterally close the channel using the corresponding state.
If we detect that the remote party probably has lost state, we'll be a good citizen and force close the channel using our latest commitment.
@Roasbeef: what is …

Data loss protection

---

discovery/gossiper.go
discovery/syncer.go
discovery/syncer_test.go

In this commit, we allow the gossiper syncer to store the chunk size for
its respective encoding type. We do this to prevent a race condition
that would arise within the unit tests by modifying the values of the
encodingTypeToChunkSize map to allow for easier testing.

discovery/syncer: store chunk size within gossiperSyncerCfg

---

lnwallet/channel.go
lnwallet/script_utils.go
lnwallet/script_utils_test.go
watchtower/blob/justice_kit.go
watchtower/blob/justice_kit_test.go

This PR introduces the encryption/decryption primtives for watchtower blobs, as well as the version 0 encoding scheme for the `blob.OfJustice` payload. The v0 encoding creates a constant size plaintext of 265 bytes, and allows a watchtower to sweep the to-local and (optionally) to-remote commitment outputs. Future versions can be made to support sweeping of HTLC outputs by using an alternate version. In the meantime, we choose a constant size encoding to not leak the number of outputs being swept.
```
blob of justice version 0 plaintext encoding:
sweep address:               34 bytes
revocation pubkey:           33 bytes
local delay pubkey:          33 bytes
csv delay:                    4 bytes
commit local revocation sig: 64 bytes
has p2wkh output:             1 byte
p2wkh pubkey: …
```

[watchtower/blob]: Blob of Justice encryption/decryption and v0 plaintext encoding

---

chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/btcdnotify/btcd.go
chainntnfs/interface_test.go
chainntnfs/neutrinonotify/neutrino.go
chainntnfs/txconfnotifier.go
chainntnfs/txconfnotifier_test.go

In this PR, we modify our `bitcoind` and `btcd` chain notifiers to handle historical confirmations and spends asynchronously. This was motivated by users experiencing slow startups due to blocking during long rescans.
Fixes #1569.
Fixes #1616.
Fixes #1648.

chainntnfs: handle historical confs and spends asynchronously

---

lnd.go
server.go

In this commit, we move the initialization of the server into the
funding manager itself. We do this as it's no longer the case that _any_
RPC needs to access the funding manager. In the past, this was the
only reason that the funding manager was instantiated outside of the
server: to be able to respond to queries _before_ the server was
started.
This change also fixes a bug as atm, the funding manager will try to
register for notifications _before_ the ChainNotifier itself has fully
started.
Fixes #1672.

funding+server: move initialization of funding manager into the server

---

channeldb/db.go
channeldb/error.go
channeldb/meta_test.go

This PR adds a check that fails `channeldb.Open` when we detect a user reverting to an older database version. This allows lnd to revert to older commits w/ the same db version, but prevents us from reverting past the last migration.
Inspired by issues reported #1671

channeldb: fail Open on db reversion

---

server.go

Noticed this issue while checking out the logs from #1700.
In this commit, we fix a small bug where we would increase epochErrors
by one even if connections were successfully established. Due to this,
we would stay stuck inside of the peer bootstrapper loop without
requerying for new peers.

server: prevent increasing epochErrors if conn was established

---

lnd_test.go

some RPC calls are reusing the context of priors calls without resetting the timeout to 15 seconds. In a loaded system, this may lead to a random error since the 15 seconds may not cover all RPC calls.

Travis - set context timeouts 

---

Gopkg.lock
Gopkg.toml
chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/bitcoindnotify/driver.go
chainntnfs/interface_test.go
chainregistry.go
config.go
docs/INSTALL.md
lnwallet/interface_test.go
routing/chainview/bitcoind.go
routing/chainview/interface_test.go
sample-lnd.conf

In this PR, we introduce a nice optimization with regards to `lnd`'s interaction with a `bitcoind` backend. Within `lnd`, we currently have three different subsystems responsible for watching the chain: `chainntnfs`, `lnwallet`, and `routing/chainview`. Each of these subsystems has an active RPC and ZMQ connection to the underlying `bitcoind` node. This would incur a toll on the underlying `bitcoind` node and would cause us to miss ZMQ events, which are crucial to `lnd`. We remedy this issue by sharing the same connection to a `bitcoind` node between the different clients within `lnd`.
We now also require the backing `bitcoind` node to use different hosts to provide its ZMQ raw block and raw transaction notifications (`zmqpubrawblock` and `zmqpubrawtx`). This was needed as the …

multi: share the same bitcoind connection between multiple rescan clients

---

Gopkg.lock
Gopkg.toml

In this commit, we update the set of deps to use the latest version of
btcd. Namely this version fixes a bug in re-org handling logic, ensures
that btcd will always respond to getheaders (fixes #511), and also
ensure that it will properly respond to cfheaders messages which is
required for the neutrino sync to operate smoothly.

build: update to use latest btcd

---

fundingmanager.go
fundingmanager_test.go
lnwallet/interface_test.go
lnwallet/reservation.go
lnwallet/wallet.go
mock.go

Two commits to improve the handling of funding tx broadcasting errors.
This commit makes sure we delete a pending channel from the set of
activeReservations within the fundingmanager immediately after the
channel is moved to the openChannelBucket in the DB. Previously we
wouldn't do this before the funding tx was confirmed, making it possible
that failing the funding flow at a later point would try to cancel a
non-existent reservation context.
This commit moves the responsibility for publishing the funding tx to
the network from the wallet to the funding manager. This is done to
distinguish the failure of completing the reservation within the wallet
and failure of publishing the transaction.
Earlier we could fail to broadcast the transaction, which would cause us
to fail the funding flow. …

Move funding tx broadcasting to Fundingmanager

---

config.go
server.go

noiseDial is only called from server.go, has nothing to do with configuration,
and moving it removes config.go's reliance on btcec and brontide.

Move noiseDial from config.go to server.go

---

Makefile

enhance make file to stop the cover testing in case one of the tests failed. This release the travis resorces sooner.
Without this fix some tests may fail but the travis job run may looks good (green)
Also see #1587

Travis - Stop cover tests in case of errors

---

chainregistry.go
docs/INSTALL.md
sample-lnd.conf

In this commit, we fix a bug recently introduced where we would
construct the parameters required to connect to a bitcoind backend, but
never actually started the connection.

chainregistry: correctly establish connection to bitcoind

---

rpcserver.go

In a previous commit, we modified our fee rates to be sat/kw internally
as it was possible that the estimated fee rate was not enough to
properly broadcast the transaction. To remedy this, we decided to add a
fee floor, but this would only be enforced when querying the fee
estimator. In this commit, we attempt to do the same thing, but for fee
rates input manually by the user.

rpcserver: enforce fee floor for fee rates input by the user

---

chancloser.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/switch.go
htlcswitch/switch_test.go
peer.go
server.go

This PR reverts the switch's current `AddLink` behavior, such that it rejects duplicate links with the same channel id. At the moment, we will hot swap in another link without fully shutting down the first, which is dangerous as the two can share a mailbox.
In a related commit, we changed `RemoveLink` such that it called `go link.Stop()`, and processed in the background to avoid deadlocking on the forwarding index mutex. The result of this is that it is possible for a prior `Stop()` to still be executing by the time a new link is added with the same channel id.
In order to recreate the behavior of replacing the old link with a new one, `RemoveLink` has been altered to return the removed link if it was found, and to not call/spawn `link.Stop()` at all. Instead, the caller is now …

[htlcswitch]: revert replace link, ensure removed links are stopped

---

Gopkg.lock
Gopkg.toml
channeldb/channel_test.go
contractcourt/chain_watcher.go
fundingmanager.go
keychain/btcwallet.go
keychain/derivation.go
keychain/interface_test.go
lnwallet/channel.go

In this PR, we fix to related but distinct issues. First, we now ensure that the auxiliary channel recovery information (which allows access to the final key state) is properly populate each time a `channeldb.CloseChannelSummary` is created. Without this information, users may have been unable to properly re-sweep or manually sweep any funds which may be left on the chain due to unforeseen circumstances. Second, we now ensure that the `keychain.KeyLocator` field will always be set for keys derived using `DeriveNextKey`. This is crucial to ensure that we'll be able to properly start to create static channel back ups in the future, as we'll need to know how to re-derive select keys to be able to sweep funds where channels have been force closed due to the data loss protection feature …

multi: ensure closed channel summaries are fully populated, ensure KeyLocators are always set

---

peer.go
server.go

This PR adds asynchronous starting of peers,
in order to avoid potential DOS vectors. Currently,
we block with the server's mutex while peers exchange
Init messages and perform other setup. Thus, a remote
peer that does not reply with an init message will
cause server to block for 15s per attempt.
We also modify the startup behavior to spawn
peerTerminationWatchers before starting the
peer itself, ensuring that a peer is properly
cleaned up if the initialization fails. Currently,
failing to start a peer does not execute the bulk
of the teardown logic, since it is not spawned
until after a successful Start occurs.
The final commit is purely just a code move to place
the relevant methods in closer proximity, and
organize them roughly in the expected execution
order.
Prerequesities:

[server]: Start Peers Asynchronously

---

walletunlocker/service.go

In this commit, we fix a bug where it's possible that changing the
wallet's password fails due to not being able to remove non-existent
macaroon files. Since it's possible to run lnd without creating them,
changing the wallet's password would always result in a failure.

walletunlocker: avoid returning error if macaroon files don't exist

---

pilot.go

This commit fixes a small bug that could cause us to disconnect an
already connected peer if no addresses where provided to the ConnectPeer
method. Now we instead first check if we are already connected, and
return early.

autopilot: check if already connected before returning error

---

Gopkg.lock
Gopkg.toml
cmd/lncli/commands.go

... as it is slow, pulls in an unnecessary dependency, and frankly doesn't work with the current graph size.
This is a cut-out of the current testnet graph as seen from my node:

Remove --render option from `lncli describegraph` 

---

contractcourt/contract_resolvers.go
lnd_test.go

This commit attempts to fix an inconsistency in when we consider an HTLC
to expire. When we first launched the resolver we would compare the
current block height agains the expiry, while for new incoming blocks
we would compare against expiry-1.
This lead to a flake during integration tests, during a call to
RestartNode after _exactly_ enough blocks for the HTLC to expire. In
some cases the resolver would see the new blocks and consider the HTLC
to be expired (because of the -1), while in some cases resolver would
shut down before seeing the new blocks, and upon restart wouldn't act on
the new height because we did not compare against -1.
This commit fixes this by doing the same comparison in both cases.
Fixes #1632

contractcourt/contract_resolvers: correct off-by-one HTLC expiry

---

config.go
htlcswitch/switch.go
lnd_test.go
lntest/harness.go
peer.go
server.go

Fixes #1605
`server` is not very unit testable at the moment. Should consider extracting some of the logic behind interfaces to make it easier to test additions like these.

Send ChannelUpdate with Disabled bit if channel inactive for 20 minutes

---

htlcswitch/switch.go

Some small changes related to code health that have been split from #1698.
- Remove go-errors package
- Add concrete errors for switch exiting
- Remove unnecessary defer closure

[htlcswitch]: improve code health of switch

---

Makefile

This error occurred when I tried to execute `make unit`.
I think updating revision is not assumed in this case. (it is related to
https://github.com/lightningnetwork/lnd/pull/1714)
```
cd <path>/src/github.com/btcsuite/btcd && git checkout f899737d7f2764dc13e4d01ff00108ec58f766a9                           
fatal: reference is not a tree: f899737d7f2764dc13e4d01ff00108ec58f766a9 
```
To prevent this error, I added `git fetch --all` before `git checkout`.
Fixes #1750.

exec git fetch before git checkout

---

htlcswitch/circuit_map.go
htlcswitch/circuit_test.go
htlcswitch/link.go

This PR relaxes the very strict behavior of `DeleteCircuits` originally implemented w/in the circuit map. In light of 1) the split mailbox issue prior to #1551, and 2) upcoming changes to cleanup stray references/circuits w/in the switch #1698,  this will need to be in place to properly clean up stray references as the batches may not correspond 1:1 to a batch of HTLCs settled on the commitment transaction that locked them in. See commit messages for more details

[htlcswitch]: Relax Circuit Deletion

---

htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/switch.go
htlcswitch/test_utils.go

This PR fixes a long-standing, albeit benign, issue within the HTLC switch. The channels and switch maintain persistent references, essentially log pointers, to any htlcs that may need to be reforwarded internally after the switch is restarted or a peer reconnects. In this PR, we fix a instance where one of these references was not set for any packets failed by the switch. The end result is that we would continue to retransmit them internally with each restart/connection and never cleanup these references.
The switch fails all packets using a single method `failAddPacket` in multiple places. To test that this reference is being set properly, I chose to extend `TestChannelLinkMultiHopUnknownNextHop` which is one place where this method is used.
In doing so, I noticed that this test was …

[htlcswitch]: Set AddRef on failed packets

---

channeldb/channel.go
channeldb/forwarding_package.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/switch.go
lnwallet/channel.go
lnwallet/errors.go

In this PR, we add some additional logic to cleanup spurious internal retransmission of htlc packets. #1747 addressed the root cause of most issues seen on this front, though this PR adds logic to clean up the aftermath.
should get rid of:
```
2018-07-27 20:23:25.255 [ERR] HSWC: ChannelLink(528615:1949:1) Failing link: unable to settle incoming HTLC: No HTLC with ID
```
```
2018-07-27 20:23:25.255 [ERR] HSWC: ChannelLink(528615:1949:1) unable to fail incoming HTLC: No HTLC with ID
```
Depends on:

[htlcswitch] fwdpkg cleanup

---

chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/bitcoindnotify/bitcoind_debug.go
chainntnfs/bitcoindnotify/driver.go
chainntnfs/btcdnotify/btcd.go
chainntnfs/btcdnotify/btcd_debug.go
chainntnfs/btcdnotify/driver.go
chainntnfs/height_hint_cache.go
chainntnfs/height_hint_cache_test.go
chainntnfs/interface_test.go
chainntnfs/neutrinonotify/driver.go
chainntnfs/neutrinonotify/neutrino.go
chainntnfs/neutrinonotify/neutrino_debug.go
chainntnfs/txconfnotifier.go
chainntnfs/txconfnotifier_test.go
chainregistry.go
lnd_test.go
lnwallet/interface_test.go

The role of the `heightHint` parameter within the `ChainNotifier` interface is to give them a lower bound on when to start looking for the earliest occurrence of the event. Usually this value isn't used as we remain online for the lifetime of the event. However, we currently have a concept of a "historical dispatch" of an event. This occurs when the stateless chain notifier instance is already live, and we receive a notification for an event with a `heightHint` value that is in the past. In this case, depending on various factors, we may have to fetch a set of blocks in the worst case to scan forward to determine if we need to dispatch an event. This can lead to some efficiency issues due to re-doing this process on every restart.
In this PR, we address this by introducing a persistent …

chainntnfs: introduce persistent height hint layer to ChainNotifier implementations

---

discovery/gossiper.go
discovery/gossiper_test.go
fundingmanager.go
fundingmanager_test.go
routing/errors.go
routing/router.go
server.go

This PR attempts to fix a few edge cases within the gossiper, where we wouldn't be consistent in how we returned errors when processing an announcement.
After this change, the gossiper and the router should satisfy the following expectations:
1. When a `ErrIgnored` or `ErrOutdated` is returned from the `router`, it means that the information provided by the ignored announcement (or newer information) is already present in the graph. This means that the caller can safely continue. Previously this was not always the case, as we might have decided to defer adding the information to the graph, or we returned one of the two errors in cases where the information was not already present.
2. We now **always** eventually return a result on the error channel for a processed announcement. Previously …

Unify gossiper and router announcement handling

---

autopilot/agent.go
autopilot/agent_test.go
pilot.go

Adds a new external signal alerting autopilot that
new nodes have been added to the channel graph or
an existing node has modified its channel
announcment. This allows autopilot to examine its
current state, and attempt to open channels if our
target state is not yet met.

[autopilot]: add OnNodeUpdate trigger

---

htlcswitch/link_test.go

In this commit, we increase the fwdpkg gc interval
to avoid having it conflict with switch tests that
inspect forwarding packages. The current timeout is
a little too short on travis, and sporadically fails
TestChannelLinkCleanupSpuriousResponses, which was
added recently.

htlcswitch/test_utils: increase fwdpkg gc interval

---

lnrpc/rpc.proto

I found this link that serves a 301 to a newer repository own by Lightning Labs. I guess it makes change to change it in the proto file.

change lightning-api repo link redirect

---

autopilot/agent.go
autopilot/agent_test.go
pilot.go

In this commit, we modify the balanceUpdate autopilot signal to update
the balance according to what's returned to the WalletBalance callback
rather than explicitly tracking the balance. This gives the agent a
better sense of what the wallet's balance actually is.

autopilot/agent: use updateBalance rather than tracking balance explicitly

---

autopilot/graph.go
autopilot/interface.go
autopilot/prefattach.go
autopilot/prefattach_test.go
discovery/bootstrapper.go

In this PR, we modify the Node interface to return a set of raw
bytes, rather than the full pubkey struct. We do this as within the
package, commonly we only require the pubkey bytes for fingerprinting
purposes. Before this commit, we were forced to _always_ decompress the
pubkey which can be expensive done thousands of times a second.
This was noticed while profiling a node that was running with relatively high autopilot settings: 
```
.          .    176:           if err := g.ForEachNode(func(node Node) error {
30ms     14.66s    177:                   nID := NewNodeID(node.PubKey())
```

autopilot: modify the graph interface to return raw bytes for node pubkeys, not entire key

---

Gopkg.lock
Gopkg.toml

In this commit, we update to the latest versions of btcwallet+neutrino
that fix a number of bugs within lnd itself. Namely, we ensure that we
no longer print out garbage bytes, properly reconnect btcd after being
disconnected, ensure we don't add duplicate utxos, and finally ensure
that we always start the rescan from the wallet's initial birthday.
Fixes #1775.
Fixes #1494.
Fixes #444.

build: update to latest versions of neutrino+btcwallet

---

server.go

This PR modifies the method lnd uses to reestablish connections to persistent peers, to reconcile reported issues of LND not reestablishing connections automatically.
Currently, link nodes only ever store a single address, that corresponds to the address known at the time a channel is first opened. If we have a link node for a given peer, we will examine the addresses it contains (which is only one), and compare it any known policy for that peer. If the host matches, but the port number has been changed, we will try to reconnect only to `host:<advertised-port>`.
If a link node doesn't exist for a peer, we will try to reconnect to all known addresses listed in the policy. This differs from the above case, as when a link node is found, we may only pick out _one_ address from the policy.
The …

server: Reconnect to all known addrs for persistent peers

---

channeldb/db.go
channeldb/graph.go
channeldb/graph_test.go
channeldb/migrations.go

In this PR, we attempt to fix a number of issues with regards to the edge update index. To summarize, the edge update index is responsible for only storing the _latest_ update for each edge policy. When a new update arrives, we'd attempt to remove the old entry within the index before adding the new one. However, none of the entries were being removed due to some offset miscalculations. To remedy this, we correctly calculate each offset and add a database migration to properly prune all stale entries within the index.
This will also fix a number of issues with regards to gossip peer queries. Whenever a peer requested for channels within a time horizon, we'd end up sending them stale entries, causing them to attempt to fetch channel announcements for them, even though they no longer …

channeldb: properly prune stale entries within edge update index

---

rpcserver.go

All fields including: 
* lnrpc.Invoice.Value 
* lnrpc.Payment.Value
are showing amount in satoshies and only lnrpc.Invoice.AmtPaid is assigned with the milli satoshies value.
This PR fixes this inconsistency.

amount paid should be in satoshies as other fields used for amount

---

discovery/gossiper.go
peer.go
server.go

This commit moves the gossip sync dispatch
such that it is more tightly coupled to the
life cycle of the peer. In testing, I noticed
that the gossip syncer needs to be dispatched
before the first gossip messages come across
the wire.
The prior spawn location in the server happens
after starting all of the peer's goroutines,
which could permit an ordering where the
gossip syncer has not yet been registered.
The new location registers the gossip syncer
within the read handler such that the call
blocks before any messages are read.

peer: Synchronous registration of gossip queries

---

config.go

This PR enforces that the ZMQ options MUST be distinct for `bitcoind` and `litecoind`. Otherwise, the optimization to allow using different sockets for `rawblock` and `rawtx` notifications does not apply.
We also defer creating the base lnd directory until all flag parsing is done. We do this as it's possible that the config file specifies a lnddir, but it isn't actually used as the directory has already been created.

config: ensure ZMQ options are not equal and defer creating lnddir until all flag parsing is done

---

chan_series.go
channeldb/error.go
channeldb/graph.go
channeldb/graph_test.go
discovery/gossiper.go
discovery/gossiper_test.go
discovery/utils.go
lnwire/announcement_signatures.go
lnwire/channel_announcement.go
lnwire/channel_update.go
lnwire/lnwire_test.go
lnwire/node_announcement.go
lnwire/onion_error_test.go
server.go

In this commit, we fix an existing bug within the codebase. For all gossip messages we stored, validated and propagated, we wouldn't also include any extra data up to the full length of the message. As a result, in the future if we upgrade in the forwards compatible manner by adding _new_ (possibly unknown fields to ourselves) to the end of a message, then we would be unable to properly validate an propagate the valid versions. 
In order to fix this, both in the database and in our wire parsing, if after we parse the regular message there are any additional bytes, we'll also read those and store those in the database. We ensure that in all cases where we read these announcements from disk, we properly include the extra bytes in the wire messages before we write them out onto the socket.

channeldb+discovery: ensure we store, validate and propagate announcements with opaque data

---

Gopkg.lock
Gopkg.toml

This PR adds constraints to non-direct imports:
- github.com/aead/siphash
- golang.org/x/sys
- gopkg.in/errgo.v1
Since they are not direct imports, we must use the 
`[[override]]` stanzas to ensure we pull the correct
version. At times, this could cause `Gopkg.lock` to
not be in sync with `Gopkg.toml`

dep: constrain siphash, x/sys, and errgo.v1 + upd neutrino

---

peer.go
test_utils.go

In this commit, we fix a small bug with regards to the persistent peer
connection pruning logic. Before this commit, it'd be the case that we'd
prune a persistent connection to a peer if all links happen to be
inactive. This isn't ideal, as the channels are still open, so we should
always be atttempting to connect to them. We fix this by looking at the
set of channels on-disk instead and prune the persistent connection if
there aren't any.

peer: prune persistent peer connection on zero on-disk channels

---

server.go

In this commit, we remove signaling for initial routing
dumps, which create unnecessary log spam, bandwidth, and
CPU. Now that gossip syncing is in full force, we will
instead opt to use the more efficient querying/set
reconciliation. Other nodes may still request initial
gossip sync from us, and we will respond.

server: Stop requesting initial graph sync 

---

autopilot/agent.go
autopilot/agent_test.go
autopilot/interface.go
autopilot/prefattach.go
autopilot/prefattach_test.go

This PR modifies the autopilot agent to track
all pending connection requests, and forgo further
attempts if a connection is already present.
Previously, the agent would try and establish
hundreds of requests to a node, especially if the
connections were timing out and not returning.
This resulted in an OOM OMM when cranking up
maxchannels to 200, since there would be close
to 10k pending connections before the program was
terminated. The issue was compounded by periodic
batch timeouts, causing autopilot to try and
process thousands of triggers for failing
connections to the same peer.
With these fixes, autopilot will skip nodes that we
are trying to connect to during heuristic selection.
The CPU and memory utilization have been significantly
reduced as a result.

autopilot: prevent duplicate conns to same peer

---

Gopkg.lock
Gopkg.toml

In this commit, we update btcwallet to the latest version which fixes a
panic bug when attempting to notify a relevant transaction.

build: update btcwallet to latest version

---

cmd/lncli/commands.go

Adds whitespaces missing on command description,
without those whitespaces at the end of the line
it showed the words together

Missing whitespaces on lncli queryroutes command description

---

discovery/gossiper.go
discovery/syncer.go
discovery/syncer_test.go

This PR adds a simple rate limiting mechanism to the gossip syncers, that mitigates the ability of remote peers to abuse the query mechanism. #1798 fixes the issue from the sender-side, by removing additional queries made for immature channels. This fix, however, will only be available on upgraded nodes, as older peers will continue to endlessly request additional queries.
For nodes that have a modest number of channels, it may be incorrect to assume that all of their peers will upgrade in a timely fashion. If a user has a channel with an older peer, their options are between tolerating an endless stream of sync messages or closing the channel. Even if all peers were updated, #1784 does highlight that resources can be allocated disproportionately in response to this behavior. 
This PR …

discovery/syncer: delay replies after initial sync to prevent DOS

---

channeldb/channel.go
channeldb/db.go

In this PR, we fix a bug in the bucket creation code in
createChannelDB. This bug can cause migrations on older nodes to fail,
as we expect the bucket to already have been created. With this commit,
we ensure that all the buckets under the main node and edges bucket are
properly created. Otherwise, a set of the newer migrations will fail to
apply for nodes updating from 0.4.

channeldb: fix bucket creation hierarchy in createChannelDB

---

lnd_test.go

This fixes a flake within `testGarbageCollectLinkNodes` where we wouldn't properly check reconnection, since we were asserting the nodes didn't connect using a wait predicate. This led to the test passing in certain cases, since the predicate would be satisfied before the nodes had reconnected.
This PR changes this to a `WaitInvariant` to ensure we stay disconnected for 5 seconds.
Since we will prune the persistent connections only on peer connection, we must also do an extra restart to trigger the pruning logic, to make the test reliably pass.

[integration tests] Fix flake in persistent connection pruning test

---

channeldb/migrations.go

In this commit, we no longer assume that the bucket hierarchy has been
created properly when applying the latest DB migration. On older nodes
that never obtained a channel graph, or updated _before_ the query sync
stuff was added, then they're missing buckets that the migration expects
them to have.
We fix this by simply creating the buckets as we go, if needed.

channeldb: relax bucket assumptions for latest db migration

---

Gopkg.lock
Gopkg.toml
discovery/syncer.go

This PR replaces the simplistic rate limiting
technique added in 557cb6e, to use the
golang.org/x/time's rate limiter. This has the
benefit of performing traffic shaping to meet a
target maximum rate, and yet tolerate bursts. Bursts
are expected during initial sync, though should become
more rare afterwards. Performing traffic shaping with
this mechanism should improve the ability of the gossip
syncer to detect sustained bursts from the remote peer,
and penalize them appropriately.
This commit also modifies the default parameters to
accept bursts of 10 queries, with a target maximum
rate of 1 reply every 5 seconds.

discovery: Traffic shaping of gossip query replies

---

release.sh

This PR adds a build for the `ARMv6` platform to `release.sh`. That's the platform that the *Raspberry Pi Zero* and the *Raspberry Pi Zero W* are built on. It does that by [providing `GOARM=6`](https://github.com/golang/go/wiki/GoArm#supported-architectures) to the `go build`.
This generates an entirely new package `lnd-linux-armv6-XYZ.tar.gz`.
For consistency, it also changes the release name of the previous `linux-arm` build to `lnd-linux-armv7-XYZ.tar.gz`.
It would be fantastic to have `Linux ARMv6` included, so that Pi Zero hackers (like me) don't have to build the released binaries ourselves or don't have to rely on unofficial releases.

release: Add ARMv6 platform to release.sh

---

config.go
docs/configuring_tor.md
server.go
tor/controller.go
tor/controller_test.go

As of Tor version `0.3.3.6`, support has been added to create v3 onion services through Tor's control port. In this PR, we extend our current Tor controller implementation to support this.

tor+server: add automatic support for v3 onion services

---

cmd/lncli/commands.go
config.go
docker/lnd/start-lnd.sh
docs/INSTALL.md
lnd.go
lntest/node.go
macaroons/README.md
sample-lnd.conf
walletunlocker/service.go

This PR begins the process of deprecating the confusing `noencryptwallet` flag, which has initially designed for testing purposes. As people have started to use this flag in the wild, it cannot be fully removed in one fell swoop due to backwards-compatibility requirements, though this will start the process of deprecating its use.
The primary change in this PR is to rename the flag to `noseedbackup`, as this the more critical information the user should be aware of when using this setting. The help description printed presents a more alarming tone than the prior message, and includes the caveat that no seed will be provided.
References to noencryptwallet have been migrated to noseedbackup in comments throughout the codebase. The section on disabling wallet encryption has also been removed …

Start deprecating noencryptwallet

---

Gopkg.lock
Gopkg.toml
chainntnfs/bitcoindnotify/bitcoind.go
chainregistry.go
lnwallet/btcwallet/btcwallet.go
lnwallet/interface_test.go
routing/chainview/bitcoind.go

In this PR, we add a new test to the set of lnwallet integration
tests. In this new test, we aim to ensure that all backends are able to
display unconfirmed transactions in ListChainTransactions. As of this
commit, this test fails as no backends will return unconfirmed
transactions properly.
In this PR, we fix a bug in the arguments to GetTransactions for the
btcwallet implementation of the WalletController interface. Before this
commit, we wouldn't properly return unconfirmed transactions. The issue
was that we didn't specify the special mempool height of "-1", as the
ending height. The mempool height is actually internally converted to
the highest possible height that can fit into a int32.
In this commit, we set the start to zero, and end to -1 (actually
2^32-1) to properly scan for …

lnwallet+rpc: allow unconfirmed transactions to be returned over RPC, fix SubscribeTransaction unconf for neutrino

---

channeldb/migrations.go

In this commit, we fix a bug in the latest migration that could cause
the migration to end in a panic. Additionally, we modify the migration
to exit early if the bucket wasn't found, as in this case, no migration
is required.
Fixes #1874.

channeldb: don't use KeyN in latest migration

---

rpcserver.go

Fixes #1915
Since we also get unconfirmed transactions from `r.server.cc.wallet.ListTransactionDetails()` in `GetTransactions` of `rpcserver.go`, we need to check if `tx.BlockHash` might be nil.

rpcserver: handle unconfirmed TX properly when listing all transactions

---

tor/controller.go

Allow parsing `key=value` pairs from Tor control's responses when `value` contains one or more `=` characters.
Fixes #1931

tor/controller: fix response parsing for values containing the '=' character

---

discovery/gossiper.go
routing/ann_validation.go
routing/notifications_test.go
routing/pathfind_test.go
routing/router.go
routing/router_test.go

The intention of this PR is to fix https://github.com/lightningnetwork/lnd/issues/1707.

payment failure message with attached channel_update not validated

---

server.go

over Tor
In this commit, we fix a small bug where we would attempt to start the
Tor controller even if we were not requested to automatically create and
onion service in order to listen for inbound connections over Tor.

server: start tor controller if we should listen for inbound connections

---

chainntnfs/neutrinonotify/neutrino.go

This commit removes shadowing of the currentHeight
variable when registering for neutrino spend
notifications. Currently, a locally scoped variable
is used when determining if the backend is fully
synced before attempting to call GetUtxo, which
means that the variable won't be updated after
breaking out of the loop. As a result, this could
cause us to scan unnecessarily if the backend is
catching up, e.g. after being offline for some time.

chainntnfs/neutrinonotify/neutrino: remove height shadowing

---

contractcourt/chain_arbitrator.go
contractcourt/channel_arbitrator.go
contractcourt/contract_resolvers.go
server.go
utxonursery.go
utxonursery_test.go

This commit fixes an issue within the utxo nursery, where we would use
the best height as height hint when registering for confirmation
notifications for kid outputs.
This would in many cases not be correct, as the output could be
confirmed deeper, leading to failure of getting confirmations on
backends where a height hint is required.

[utxonursery] Use kidoutput broadcast height as height hint

---

discovery/gossiper.go

In this commit, we add an additional error check for
ErrNoGraphEdgesFound when restransmitting stale channels during the
gossiper's startup. We do this to prevent benign log messages as we'll
log that we were unable to retransmit stale channels when we didn't have
any channels in our graph to begin with.
This fixes the log message:
```
DISC: unable to rebroadcast stale channels: error while retrieving outgoing channels: no graph edges exist
```

discovery/gossiper: check ErrNoGraphEdgesFound for restransmitStaleChannels

---

Makefile
server.go
utxonursery.go
utxonursery_test.go

This PR adds test coverage to utxonursery.
In addition to this it fixes a bug where IncubateOutputs doesn't add to the waitgroup and might leave lingering goroutines after nursery is stopped.

utxonursery: add test coverage

---

lnwallet/btcwallet/btcwallet.go
lnwallet/interface.go
mock.go
server.go

This paves the way for lnd to work with hardware wallets, in which case it will not have access to the private key

remove the need for lnwallet to have access to the private key

---

discovery/gossiper_test.go
fundingmanager.go
fundingmanager_test.go
htlcswitch/link_test.go
htlcswitch/mock.go
lnpeer/peer.go
peer.go
server.go

This commit makes the AddNewChannel expect an OpenChannel instead of a
LightningChannel struct. This moves the responsibility for starting the
LightningChannel from the fundingmanager to the peer, and we can defer
the channel restoration until we know that the channel is not already
active.
Fixes #1575
EDIT: This is a simpler solution than #1906, which also fixes the issue.

Defer channel restoration until after channel active check.

---

channeldb/channel.go
channeldb/error.go
peer.go
server.go

In this PR, we ensure that we only create the sub-bucket for channels once: at the time of creation. We do this as otherwise it's possible that a method that mutates a channel's state is called after it has already been closed on-chain, leading to the channel bucket being recreated.
This PR also includes minor changes to prevent sending active/inactive channel updates for channels that have yet to be announced to the network. I noticed these while looking at the logs of the issue linked below.
Fixes #1917.

channeldb: ensure channel buckets are only created once

---

routing/chainview/bitcoind.go
routing/chainview/btcd.go
routing/chainview/neutrino.go

It was previously Debug, which would spam the logs at startup, and not
provide very useful (human-readable) information.

[trivial] routing/chainview: demote logging of new utxos for filter to Trace

---

breacharbiter.go
contractcourt/chain_arbitrator.go
contractcourt/contract_resolvers.go
log.go
server.go
sweep/input.go
sweep/log.go
sweep/sweeper.go
utxonursery.go
utxonursery_test.go

This PR makes changes that prepare for the new Sweeper struct.
- Create new subsystem for sweeping
- Move sweep tx generation code to sweep subsystem.
- Clean up SpendableOutput and CsvSpendableOutput structs.
- Make Cltv expiry part of a sweep input.
- Remove duplicated sweep tx generation code from Success and Commit resolvers
A follow PR is #1960, which builds the sweeper around the sweep tx generation and uses that from `utxonursery`.

sweep: prepare for sweeper

---

sweep/sweeper.go

This commit restores the sweep behavior of
filtering inputs with unknown witness types
from the final sweep transaction. Currently,
such inputs will be included without adding
anything to the weight estimate, possibly
creating a transaction with insufficient fees.
Follow up of #1978

sweep/sweeper: ignore unknown witness types

---

Gopkg.lock
Gopkg.toml

In this commit, we update neutrino to the latest version which includes
a fix for a recent regression. Additionally, this new version adds some
new logging statements to help us track down a lingering issue wherein
filter headers are written out of order.

build: update neutrino to latest version

---

contractcourt/contract_resolvers.go
server.go
sweep/input.go
sweep/log.go
sweep/sweeper.go
utxonursery.go

In this commit, we modify the newly introduced UtxoSweeper.CreateSweepTx
to accept the confirmation target as a param of the method rather than a
struct level variable. We do this as this allows each caller to decide
at sweep time, what the fee rate should be, rather than using a global
value that is meant to work in all scenarios. For example, anytime
we're sweeping an output with a CLTV lock that's has a dependant
transaction we need to sweep/cancel, we may require a higher fee rate
than a regular force close with a CSV output.

multi: modify sweeper.CreateSweepTx to accept conf target, style changes

---

docs/INSTALL.md

Every time I try to update lnd by following these instructions it fails. Most recently like this:
$ make
Compiling dependencies.
dep ensure -v
grouped write of manifest, lock and vendor: failed to export github.com/lightninglabs/neutrino: fatal: failed to unpack tree object 838f7ba74d217d188efc223604bd280b4e3f0238
: exit status 128
Makefile:116: recipe for target 'dep' failed
make: *** [dep] Error 1
I found that if I `make clean` before running `make` then it doesn't fail.

Improve 'updating' instructions

---

routing/heap.go
routing/pathfind.go
routing/pathfind_test.go
routing/router.go
routing/router_test.go
rpcserver.go

In this PR the dependency of unmarshallRoute on edge policies being
available is removed. Edge policies may be unknown and reported as nil.
SendToRoute does not need the policies, but it does need pubkeys of the
route hops. In this commit, unmarshallRoute is modified so that it
takes the pubkeys from edgeInfo instead of channelEdgePolicy.
In addition to this, the route structure is simplified. No more connection
to the database at that point. Fees are determined based on incoming and
outgoing amounts.

lnrpc+routing: fix unmarshallRoute and simplify route structure

---

discovery/gossiper.go

Currently logs e.g.:
> [ERR] DISC: unable to send channel update -- could not find peer &{17c36a0 79c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 ec91a238a2f
0c097359a0f9fc5a8a64a2bfd2666fd559dd95df91cd39e71b270}: peer is not connected

discovery/gossiper: fix logging on failed channel update

---

contractcourt/contract_resolvers.go

This PR modifies the signing and sweeping of commit to-remote sweeps and htlc success sweeps, such that we validate the generated transaction's sanity before publication. It also ensures that the resolvers checkpoint the transaction before publishing. This ensures that we will watch for the same txid after a restart in case a crash happens between publication and checkpointing. If such a crash happens, both will attempt to publish the sweep transaction again in order to ensure the transaction propagates.
In addition, we return an error if checkpointing fails from a number of places within the contract resovlers, and also ignore errors that can arise from duplicate publications of the same htlc success transaction.
Note: would like to add some unit tests exercising this behavior, though …

conctractcourt: check sweep sanity + reliable publication

---

chan_series.go
channeldb/graph.go
discovery/gossiper.go
lnd_test.go
lnwallet/fee_estimator.go
server.go

In this commit, we remedy the `genNodeAnnouncement` method to ensure that it also updates the on-disk node announcement. Before this commit, in both the Tor code, and the dynamic IP update code (for NAT traversal), we would fail to update the on-disk version of the node announcement. As a result, we would never propagate a new authenticated announcement to the network. 
Along the way, we clean up some duplicated node with the help of a new `LightningNode.NodeAnnouncement` method.

server: ensure each time we update a node ann we also update the on-disk version 

---

watchtower/wtwire/create_session.go
watchtower/wtwire/create_session_reply.go
watchtower/wtwire/error.go
watchtower/wtwire/error_code.go
watchtower/wtwire/features.go
watchtower/wtwire/init.go
watchtower/wtwire/message.go
watchtower/wtwire/state_update.go
watchtower/wtwire/state_update_reply.go
watchtower/wtwire/wtwire.go
watchtower/wtwire/wtwire_test.go

This PR adds the preliminary set of wire messages that will be used to negotiate and backup encrypted sweep info, that can be used by a watchtower in the event that it must sweep a revoked commitment transaction. The design borrows heavily from the existing [`lnwire`](https://github.com/lightningnetwork/lnd/tree/master/lnwire) package, which implements the Lightning wire protocol.
NOTE: Keep in mind that nothing in this PR has been formalized under a BOLT specification. We are moving ahead with the implementation in LND in order to facilitate experimentation on testnet. As such, these features will not be available for mainnet until more solidification has occurred. Furthermore, they are likely to change after thorough review.
Looking forward to hearing feedback and criticisms :) …

[watchtower/wtwire]: Watchtower Wire Messages

---

watchtower/server/interface.go
watchtower/server/log.go
watchtower/server/mock.go
watchtower/server/server.go
watchtower/server/server_test.go
watchtower/wtdb/breach_hint.go
watchtower/wtdb/mock.go
watchtower/wtdb/session_id.go
watchtower/wtdb/session_info.go
watchtower/wtdb/session_state_update.go

This PR builds on #1512, by adding the server-side handling of watchtower clients. This allows clients to negotiate sessions and send state updates. The `wtwire` package has been extended with more concrete fail codes, and the `SessionInitReply` has been altered to return an arbitrary `Data` field (instead of `RewardPubKey`), which seems more useful for negotiating session parameters.
The server's db and clients have been mocked out and protected using a build flag, so that we can have adequate black-box testing of the server's behavior. A fairly comprehensive set of test vectors have been added for state update sequences and checking that the errors from the database are being converted into the appropriate wire fail codes.
Things not in the this PR:
- watchtower acceptance policy, …

[watchtower/server] Server-Side Wire Protocol

---

Makefile

Linting will fail if code is not formatted with the -s flag, so make
sure we always use it when formatting.
Inspired by https://github.com/elastic/beats/pull/780

make: ensure make fmt is run with -s flag

---

chan_series.go
channeldb/graph.go
channeldb/graph_test.go
discovery/gossiper.go
discovery/gossiper_test.go
fundingmanager.go
fundingmanager_test.go
lnd_test.go
routing/router.go
rpcserver.go

In this commit, we ensure that we don't include routing hints for
unadvertised nodes at the time of invoice creation. Otherwise, this
would lead us to leak these unadvertised nodes to anyone who can get
their hands on the invoice being created. To prevent this, we'll now
look at the network graph and ensure that the node in unadvertised if
all of their edges are unadvertised and only extend to us.

rpc+server: ensure we don't leak unadvertised nodes within invoice routing hints

---

Gopkg.lock
Gopkg.toml

In this commit, we update to the latest version of neutrino. This
version has an important bug fixes which fixes an issue where we
wouldn't detect a duplicate incoming cfheader message, and panic due to
trying to write the same header twice.

build: update to latest neutrino commit

---

docs/configuring_tor.md

I recently ran lnd with tor for the first time. While following instructions on [configuring_tor file](https://github.com/lightningnetwork/lnd/blob/4dd4f7cf452709d90fa1d16062b13874623c929a/docs/configuring_tor.md), I wasn't able to run it at first because I didn't add `listen=localhost` in my config file (#2034).
I think we should add it to the instructions.
I also add another minor issue because my tor version was not 0.3.3.6, I think it should help to add this requirement in the same file.

update 'configuring_tor' file

---

chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/btcdnotify/btcd.go
chainntnfs/neutrinonotify/neutrino.go
chainntnfs/txconfnotifier.go
chainntnfs/txconfnotifier_test.go

In this PR, we modify the `TxConfNotifier` to isolate confirmation notifications while a historical dispatch is being processed. The purpose of this is to segment which notifications should have their height hints updated in the cache. During a historical rescan, we don't yet know if the txn is in the chain, so we shouldn't continue to update its height hint until after finishing the rescan. Once the rescan finishes, the notification is grouped along with all other notifications at tip so that their height hints can progress as blocks are added.
This PR also introduces:
- a reorg safety delta to height hints, currently 144 blocks
- with the recent LRU cache added to neutrino, this shouldn't result too much unnecessary network I/O
- the height hint is still clamped to whatever the client …

chainntnfs: Isolate conf notifications during historical scans

---

lnwallet/btcwallet/btcwallet.go
lnwallet/interface.go
lnwallet/wallet.go
mock.go

This change was inspired by #1984 - the underlying call to
ListUnspent supports a (min, max) range so it makes sense that
the WalletController interface can also support this; a
default no-maximum can be expressed using a MaxInt32 value.

Add a maxconfirms argument to ListUnspentWitness

---

watchtower/blob/justice_kit.go
watchtower/blob/justice_kit_test.go

This PR fixes an oversight in the previous
design of the watchtower blob, by introducing
a length byte for sweep addresses. The previous
format supposed that addresses would be padded
to 42 bytes, but had no indication of the
address's actual length.
To remedy this, we introduce a single byte
indicating the actual size of the address,
such that the padding can be removed upon
decoding.
In addition, the watchtower/blob unit tests are
modified to use ` t.Run` so that the unit test
names are properly displayed in logs.

[watchtower/blob] variable length sweep addr

---

chainntnfs/bitcoindnotify/bitcoind.go
chainntnfs/bitcoindnotify/bitcoind_test.go
chainntnfs/btcdnotify/btcd.go
chainntnfs/btcdnotify/btcd_test.go
chainntnfs/height_hint_cache.go
chainntnfs/height_hint_cache_test.go
chainntnfs/interface_test.go
chainntnfs/neutrinonotify/neutrino.go
chainntnfs/txnotifier.go
chainntnfs/txnotifier_test.go
chainregistry.go
lnwallet/interface_test.go

In this PR, we attempt to re-enable the height hint cache for the different `ChainNotifier` implementations. This will lead to performance improvements upon startup when running a full node backend without `txindex` or when running as a light client, like Neutrino.
~~Depends on #1787 and #2004.~~

chainntnfs: re-enable height hint cache

---

htlcswitch/switch.go

TPS log statement that announces sending and receiving of satoshis with inaccurate totals is intended as a limited, low signal log statement and should not print to the standard log level.

htlcswitch: Limit low-signal tps log statement to debug log

---

config.go
fundingmanager.go
fundingmanager_test.go
lnwallet/errors.go

Implements proposal in #1884.
Progress:
Fixes #1884.

Option to disable incoming push amounts on channel opening

---

lnd_test.go

(Split off from #2116)
Seems to be no longer needed.

[Integration tests] remove log disabling hack

---

watchtower/blob/justice_kit.go
watchtower/blob/justice_kit_test.go
watchtower/lookout/interface.go
watchtower/lookout/justice_descriptor.go
watchtower/lookout/justice_descriptor_test.go
watchtower/lookout/log.go
watchtower/lookout/lookout.go
watchtower/lookout/lookout_test.go
watchtower/lookout/mock.go
watchtower/lookout/punisher.go
watchtower/wtdb/mock.go
watchtower/wtdb/session_info.go

This PR introduces the `watchtower/lookout` package, which handles the responsibility of monitoring the chain for possible breaches and responding by decrypting and broadcasting any justice transactions that its clients had previously uploaded. Together with the `watchtower/server`, which receives and stores encrypted blobs from clients, this represents that second primary service enabling the tower to act on behalf of the tower's clients.
At a high level, the lookout service receives input via two sources: block events and it's database. Incoming state updates are continually written to the database, and are made available to the lookout as soon as the tower successfully persists the encrypted blob. As new blocks come in, the tower searches for any breach hints matching the txid prefixes …

[watchtower/lookout]: on-chain breach monitoring

---

discovery/gossiper.go
discovery/gossiper_test.go
routing/router.go

In this PR, we allow the gossiper to also broadcast the corresponding node announcements, if we know of them, of a channel when constructing its full proof. We do this to ensure peers (other than our
remote peer) receive all the relevant announcements for a channel.
This also addresses an existing flake in the integration test `testNodeAnnouncement`. This problem arose due to the node announcement being sent before the connection between Dave (node announcement sender) and Alice (node announcement receiver) was initiated and the full channel proof was constructed.

 discovery/gossiper: send node anns when constructing full chan proof

---

Gopkg.lock
Gopkg.toml
lnwallet/btcwallet/btcwallet.go
lnwallet/btcwallet/signer.go
lnwallet/interface_test.go

In this PR, we update our `btcwallet` dependency to include the latest changes that aim to address the recently discovered `SendOutputs` issue. This issue was caused by the wallet no longer requesting to be notified of when a transaction that pays to a change address confirms on-chain. This has been addressed by the dependent `btcwallet` PRs listed below.
This PR also includes fixes for minor issues that arose once addressing the original issue. Descriptions for those can be found in their respective commit in-line.
Depends on #2175, https://github.com/btcsuite/btcwallet/pull/571, https://github.com/btcsuite/btcwallet/pull/573.
Fixes #2011.

build+lnwallet: notify wallet upon relevant transaction confirmation

---

Gopkg.lock
Gopkg.toml

In this commit, we update to the latest version of btcwallet. This
version includes a bug fix which ensures that the wallet birthday sanity
check only executes once and not each time the deamon is restarted.

build: update to latest version of btcwallet

---

Gopkg.lock
Gopkg.toml

In this commit, we update our btcwallet dependency that includes a fix
to address an issue that would cause users to be stuck in an infinite
loop by fetching the same candidate birthday block due to its height not
being updated if the sanity check was attempting to fix an estimate in
the future.
Fixes #2195.

build: update btcwallet dep to fix birthday block sanity check infinite loop

---

channeldb/channel.go
channeldb/channel_test.go
channeldb/db.go
channeldb/db_test.go
channeldb/legacy_serialization.go
channeldb/migrations.go
channeldb/migrations_test.go
contractcourt/chain_watcher.go
htlcswitch/link.go
lnd_test.go
lnwallet/channel.go
lnwallet/channel_test.go
peer.go

This PR makes the latest channel reestablishment message being stored as part of the channel close summary, such that it can be sent even when a channel ahs been closed.
This makes it possible for nodes to recover from the case where they have been offline, lost state, and comes back online, attempting to reseync the channel.
Note: This PR contains a DB migration. To ensure deserialization code is not changed in the future, and breaking old migrations, a versioned copy of the current deserialization logic is added to the file `legacy_serialization.go`. Backwards compatible addition of the new field turned out to be complex because of the presence of optional fields (see the now removed commit https://github.com/lightningnetwork/lnd/commit/14648b236fa5f203a76e876d75026735f2356d1f).
TODO:

Data loss protect resending

---

docs/code_contribution_guidelines.md

Changing link in `docs/code_contribution_guidelines.md` as per issue 
Fixes #2214

Docs: code_contribution_guidelines change link

---

.travis.yml
Makefile

This PR restructures the Travis build pipeline to speed up the existing build, and prepare for multibackend integration test builds.
* The builds using `go 1.10` are removed. We only run on `go 1.11.x` now.
* The integration test and unit-coverage build is separated into two builds. 
* The build directories are cached, which makes building as well as the unit-race runs significantly faster.
Overall the longest build is now about 16 minutes if a cache exists. This is down from about 28 minutes.
This PR adds caching for a few directories used by Travis, to speed up the bulid process. 
|            | go 1.9.4 | go 1.10 | go 1.9.4 (cache) | go 1.10 (cache) |
|------------|----------|---------|------------------|-----------------|
| race=false | 28m 31s  | 23m 46s | 27m 36s          | 21m 08s …

travis cache

---

config.go

Adds simple check to validate color after parsing config file.
Closes #2082

config: validate node color after reading config

---

docker/btcd/Dockerfile

It looks the current master branch of `btcd` doesn't use Glide.
Fixes #2254.

Fix the build error.

---

Makefile

While going through the [Installation tutorial](https://dev.lightning.community/guides/installation/), I'm getting the following error after running `make btcd` (on MacOS 10.14.1):
```sh
make btcd
Installing btcd.
go get -v github.com/btcsuite/btcd/@v0.0.0-20180823030728-7d2daa5bfef28c5e282571bc06416516936115ee
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
ignoring go.mod;
see 'go help modules'
go: cannot use path@version syntax in GOPATH mode
make: *** [btcd] Error 1
```
This appears to be related to https://github.com/lightningnetwork/lnd/pull/2253 &mdash; which also needed to set `GO111MODULE=on` before installing `btcd`.
I should caution, though, that my experience with Go is nearly nonexistent, so if there's a better way to handle this, I'm all for it 😄.

update `make btcd` command with `GO111MODULE=on`

---

htlcswitch/link_test.go

As can Currently when running integration test without tag=debug (race = false), 3 tests fails . (as can be seen here [on Travis](https://travis-ci.org/lightningnetwork/lnd/jobs/405774237) by searching "--- fail"):
--- FAIL: TestChannelLinkTrimCircuitsNoCommit (0.76s)
link_test.go:3806: line: 2741: wrong number of open circuits: want 0, got 2
--- FAIL: TestChannelLinkBandwidthConsistency (3.89s)
link_test.go:1534: line 1939: alice's link bandwidth is incorrect: expected 399994624000 mSAT, got 499995656000 mSAT
--- FAIL: TestMask (0.00s)
mask_test.go:91: htlcswitch tests must be run with '-tags debug'
Avoid that by skipping these tests.
Note that while 3 tests failed, the travis job is still marked green. This is handled by #1593

Travis - prevent FAIL during integration test

---

discovery/gossiper_test.go

This commit adds a new test TestNodeAnnouncementNoChannels that ensures
a node announcement for an unknown node is not forwarded by the gossiper.
Also updates the router mock to mimic the Router's `IsStaleNode` behaviour.

[Tests] No forwarding of stale node announcements

---

cmd/lncli/commands.go
rpcserver.go

When calling `queryroutes` from gRPC, the default value for the `num_routes` parameter  is set to zero. Having a default value of zero is confusing as there would be little point of making the call if you wanted to fetch zero results. Additionally, the documentation states that the default should be 10.
This is inconsistent with the CLI, where the default of 10 is correctly applied.
Also, the documentation for the cli `queryroutes` command has bad output which this PR addresses as below:
**Output from  `lncli queryroutes --help` (before changes):**
```
--num_max_routes value     the max number of routes to be returned (default: 10) (default: 10)
```
Set the default value as `10` when no value is provided by the caller.
**Updated output from  `lncli queryroutes --help` (after changes):** …

queryroutes: set queryroutes numRoutes param default to 10

---

Makefile

I noticed that the `go.sum` file was changing when running unit tests. Fixed by not hardcoding the btcd dependency date, and  instead using the whole version string. 
Also gets the version string from `go.mod` instead of `go.sum`, as it will always hold the current dependency.

[make+mod] fetch correct btcd version

---

routing/missioncontrol.go
routing/pathfind.go
routing/pathfind_test.go
routing/router_test.go

This PR consist of the first part of #2091 (Strict channel enabling):
1. The path finding algorithm is modified to ignore the disable bit for local channels, allowing us to send payments on these channels even though they are publicly disabled. The assumption is that bandwidth hints of local channels will be set to a value reflecting their active status.
This essentially decouples the graph's disabled status from the local path finding, as the local channel status will be more up-to-date than what is found in the graph.

path finding: Disable bit decoupling

---

channeldb/graph.go
discovery/gossiper.go

To avoid inserting invalid signatures into the DB.
Maybe maybe fixes #2016

Validate own node announcement, signature length

---

config.go
server.go

In case of spotty wifi coverage a mobile device will rapidly switch from wifi to 4G and vice versa. In these cases the persistent peer will disconnect and the backoff period will increase exponentially. After a couple reconnects we are talking about minutes which makes for bad user experience.

Server: make maximum backoff configurable

---

autopilot/graph.go
autopilot/prefattach.go
autopilot/prefattach_test.go

This PR fixes a recently introduced bug in the `prefAttach` `NodeScores` implementation, which wouldn't properly populate the `Addrs` field in the returned node struct. This is fixed, and the unit tests are amended to assert this.
In addition we make a small change to the returned set of nodes, by skipping nodes having no channels in the graph. They would've been given a score of 0 regardless.

[autopilot] populate addresses in NodeScores

---

routing/pathfind.go
routing/pathfind_test.go
routing/router_test.go
rpcserver.go

This commit fixes a crash that could be triggered by sending an empty
hop list to the SendToRoute rpc.
Fixes #2297

routing: check for empty hops list

---

lnrpc/README.md

The installation instructions for protobuf are no longer accurate, and if followed, would lead to creation of a different set of proto definitions on latest master, and errors in installations of the grpc-gateway tools. 
The two main reasons for the errors are:
1. Instructions for installation of the  google.golang.org/genproto package are not included in the README file. Installing the latest version cause failure when installing the grpc-gateway packages. That is, when running 'go install ./protoc-gen-grpc-gateway ./protoc-gen-swagger' the following errors appear:
../../../google.golang.org/genproto/googleapis/api/annotations/http.pb.go:63:26: undefined: proto.InternalMessageInfo
To fix this, instructions for installing the package were added to the last commit that was still based on …

lnrpc: update protobuf generation installation instructions.

---

autopilot/agent_test.go

This fixes a Travis test flake that would occur as a race between the two signals `OnChannelOpenFailure` and `OnNodeUpdates`. If `OnNodeUpdates` was consumed first the agent would consume the `needMoreChansResp` and `nodeScoresResp`, but skip the connection to the node since it was still pending. Fixed by removing the `OnNodeUpdates` call.
An additional commit to ensure the heuristic exits cleanly on failure and test exit is added.

autopilot: fix flaky Agent test

---

lnd_test.go

(Split off from #2116)
This commit adds a call to waitForTxInMempool before mining blocks we
assumed previously would always confirm a tx. This ensures that the tx
in question has actually propagated to the miner's mempool before mining
the block.
Requires: 
Follow-up: Replace calls to `Generate` expecting txs in mempool to avoid more races.

[Integration tests]: make sure miner have seen tx before mining

---

.gitignore
lnd_test.go
lntest/harness.go

Split off from https://github.com/lightningnetwork/lnd/pull/1621.
This PR saves the `btcd` chainbackend/miner debug logs from a test run, which is useful when debugging integration test failures.

Save integration tests backend logs

---

lnd_test.go

Split off from #2116
To ensure the test properly time out in case of a failed RPC call.

lnd_test: use context with timeout when instead of context.Background

---

htlcswitch/link.go

In this commit, we fix a minor discrepancy with the spec. We should
return a FinalFailExpiryTooSoon error, rather than a
FinalFailIncorrectCltvExpiry error, when the last HTLC of a route (exit
hop) has an expiration height that is deemed too soon by the final
destination of the HTLC.
Fixes #2227.

htlcswitch/link: return FinalFailExpiryTooSoon for last htlc

---

channeldb/graph.go
routing/router.go
routing/router_test.go

This PR removes several cases of the call to `CreateBucketIfNotExists` within the channel database, from calls where we were not adding anything to the buckets, but rather querying or deleting. This ensures we are not creating empty buckets unnecessarily, and makes it easier to keep track of where the different buckets are initially created.
Note that this change shouldn't alter behaviour of the DB, and aims to return the same errors as would have been returned even when the buckets were created.

channeldb: avoid creating empty buckets

---

release.sh

Whenever there is a new tagged release I find it useful to use `release.sh` targeting my own architecture. This PR introduces the option to specify a subset of systems/architectures or to try experimental ones without editing it.
Example:
```sh
LNDBUILDSYS="linux-arm64 darwin-amd64" ./release.sh
```
Notice that this is totally optional. When `LNDBUILDSYS` is unset the script works as always did.

release: update release script to allow user to specify systems

---

.github/pull_request_template.md

In this PR, we add a PR template which will insert this PR contribution checklist for all new PR's. It's more or less the checklist at the bottom of our contribution guidelines. However, since that's buried at the bottom, it's easy for new contributors to miss it. Making a template ensures that all contributors that propose a PR (after this is in) will see and (hopefully) adhere to the checklist.

github: add PR contribution checklist

---

utxonursery.go

A pointer to the loop variable was passed to the waitForSweepConf
goroutine, causing the wrong output to be graduated from
kindergarten.

utxonursery: fix bound variable bug

---

cmd/lncli/main.go

In this commit, we increase the gRPC block size from 4MB to 50MB.
Recently, the output of `lncli describegraph` has hit the block size cap
due to the expansion of the mainnet graph. Without this attempts to
fetch the graph return an error of:
```
[lncli] rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4246753 vs. 4194304)
```
With this commit, we give ourselves some breathing room. It's important
to note that the max message size limit is a _client side_ setting. As a
result, any developers driving `lnd` with gRPC will also need to raise
their block size limit as well if they wish to fetch the graph over
gRPC.

cmd/lncli: increase lightning gRPC block size to 50MB

---

docs/grpc/ruby.md

Otherwise mainnet DescribeGraph calls will fail because the response size is larger than the default 4MB.

Show in gRPC Ruby doc how to avoid GRPC::ResourceExhausted exceptions

---

release.sh

In this commit we update the release script to properly include the
commit hash in compiled binaries of lnd and lncli. In the future, we
should ditch the release script and extend the Makefile to support this
use case.
Fixes #2389.

build: fix release script to include commit hash

---

channeldb/channel_test.go
channeldb/db.go

In this commit, we address an issue with the FetchWaitingCloseChannels
method where it would not properly return channels that are unconfirmed
and also have an unconfirmed closing transaction because they were
filtered out. We fix this by modifying the filtering logic to only apply
when the channel has already confirmed.
Related to #2217.

channeldb/db: prevent filtering channels with unconfirmed close txs

---

keychain/btcwallet.go
keychain/derivation.go
keychain/interface_test.go

In this commit, we extend the DerivePrivKey method to allow callers that
don't know the full KeyLocator information to attempt to derive a
private key via a brute force mechanism. If we don't now the full
KeyLoactor, then given the KeyFamily, we can walk down the derivation
path and compare keys one by one. In order to ensure we don' t enter an
infinite loop when given an unknown public key, we cap the number of
keys derived at 100k.
An upcoming feature to lnd that adds static channel backups will utilize
this feature, as we need to derive the shachain root given only the
public key and key family, as we don't currently store this KeyLocator
on disk.
Split off of #2313.

keychain: extend DerivePrivKey to derive based on pubkey+KeyFamily

---

invoices/invoiceregistry.go
invoices/log.go
log.go
rpcserver.go
server.go
witness_beacon.go

Isolates the invoice registry in a separate package. It is preparation for the creation of an invoices sub server.

invoices: create package

---

lnwallet/channel.go

Make comment spelling consistent with type

lnwallet: fix trivial comment typo

---

htlcswitch/switch_test.go

Ensures events are properly flushed on `FwdEventTick`. Should also help with the flaky coverage reports.

[tests] Force tick on FwdEventTicker

---

autopilot/agent.go
autopilot/choice.go
autopilot/choice_test.go

This is a follow-up to #2006 that adds unit tests for the `weightedChoice` and `chooseN` algorithms.
In working on the test cases I noticed that the algorithms became slow when handling a large number of choices. This turned out to mostly be caused by map allocations and iterations. A commit to optimize this by instead keeping what we need in slices is added.
Builds on #2304

[autopilot] weighted choice unit tests and optimizations

---

config.go
server.go

This PR adds a `--minbackoff` configuration option, which allows one to specify the minimum backoff used when reconnecting to persistent peers. The current value is hard coded at 1 second, which remains the default configuration.
This is useful in integration tests that depend on reliably disconnecting peers, and testing behaviors in the absence of a successful reconnection. We can simulate this even by now setting the min back off to a reasonably high value, such as to not interfere with the tests.
Prepration for #2411

server: configurable min backoff

---

watchtower/lookout/lookout.go
watchtower/lookout/punisher.go

Fixes some logging statements related to txids and session ids that were done incorrectly throughout the watchtower/lookout package.

watchtower/lookout: correct txid + session id logging

---

routing/router.go

Noticed in profiling that this log message generates a ton of garbage (about 5% of my nodes resident memory), which is unnecessary when not running with trace logs. Wrapping this in a log closure should help slim down the memory requirements of validating gossip traffic.

routing/router: avoid naked spew of channel policies

---

rpcserver.go

Noticed in testing that we don't print anything when receiving an RPC request to connect to peer. This PR adds this, and fixes the use of parentheses in another logging state to match the use of brackets elsewhere.

rpcserver: add connectpeer log, fix existing formatting

---

docker/lnd/Dockerfile

running `docker-compose build` currently fails from `/lnd/docker` because `lnd/Dockerfile` is outdated.  This PR updates the dependencies.

update lnd dockerfile image

---

log.go
netann/log.go

In preparation for #2411, this PR introduces the NANN subsystem logger and tidies the imports in `log.go`

netann: Add NANN subsystem logger

---

lnd_test.go
rpcserver.go

fixes #2274
This PR adds a loop that sums the amount of PendingHtlcs to the UnsettledBalance field for Channels. Also adds a test in lnd_test to ensure that the UnsettledBalance field is actually updated.

rpcserver+lnd_test: fixing unassigned UnsettledBalance field

---

breacharbiter_test.go
contractcourt/chain_watcher.go
lnwallet/channel.go
lnwallet/channel_test.go

In this PR, we remove the passed `breachTxn` argument from `NewBreachRetribution`. We already store the transaction on disk, which we retrieve via the state number. Currently, we pull values from both the argument and the transaction loaded from disk, which is unnecessary since they should both be the same.
We modify this method to only inspect the on-disk transaction, as this allows `NewBreachRetribution` to be queried for a specific state number w/o needing to have the breach transaction itself.
This is a preliminary step to adding the watchtower client, which may need to be able to retroactively sign justice transactions for any particular revoked state. This also implies that the client/links don't have to do any bookkeeping/recording of breach transactions outside the wallet.

lnwallet: Remove breach txn from NewBreachRetribution

---

contractcourt/chain_watcher.go
lnwallet/channel.go

This PR modifies `lnwallet.BreachRetribution` to expose the remote CSV and commitment key ring.
This information is currently only accessible from the existing interface by manually parsing the scripts in the sign descriptors, which is cumbersome and error prone. In addition, we fix an existing issue wrt to not nilling curves before spewing in the cnct, which show up on trace.
In the context of the watchtower client, the `RemoteDelay`, `DelayKey`, `NoDelayKey` and `RevocationKey` are to be readily embedded in the justice kits sent to the watchtowers.

lnwallet: Add keyring and remote CSV delay to BreachRetribution

---

lncfg/address.go
lncfg/address_test.go

In this PR, we extend the `lncfg` package to support parsing of `lnwire.NetAddress` strings. As we will be rolling out watchtowers initially via the use of private towers, users will have to specify a `pubkey@addr` string in their config files. Here, we add logic to support parsing and validating a raw string value that can be given to the watchtower client.
We introduce a new `ParseLNAddressString` method, which is meant to mirror the `ParseAddressString` method introduced previously. Internally, `ParseLNAddressString` calls `ParseAddressString`, retaining the capability of using default ports and resolving TCP addrs via a custom resolver.
The unit tests are extended to assert `ParseLNAddressString` can support the variety of valid address types accessible to users today. We also make …

lncfg: NetAddress parsing

---

htlcswitch/link.go
htlcswitch/switch.go
lnwallet/channel.go
lnwallet/channel_test.go

Instead of special casing the UpdateFee messages, we instead add them to
the update logs like any other HTLC update message. This lets us avoid
having to keep an extra set of variables to keep track of the fee
updates, and instead reuse the commit/ack logic used for other updates.
This fixes a bug where we would reset the pendingFeeUpdate variable
after signing our next commitment, which would make us calculate the new
fee incorrectly if the remote sent a commitment concurrently.
A test to exercise the previous failure case is added.
Fixes #2348 
Fixes #1908

[bugfix] Process fee updates as any other update message

---

docker/btcd/start-btcctl.sh
docker/btcd/start-btcd.sh

The default network for both btcr and btcctl is mainnet which requires no network to be defined when passing command line arguments.
https://github.com/btcsuite/btcd/blob/master/chaincfg/doc.go#L34
https://github.com/btcsuite/btcutil/blob/master/doc.go#L38
This PR allows no network argument to be passed when running the btc docker containers.  Simnet is left as default and both `testnet` and `mainnet` can passed as arguments to docker.
for example:
`sudo NETWORK="mainnet" docker-compose run btcd`
`sudo NETWORK="mainnet" docker-compose run btcctl getblockchaininfo`
Fixes #2237

enable btcd and btcctl mainnet to be invoked from docker

---

watchtower/blob/justice_kit.go
watchtower/blob/justice_kit_test.go
watchtower/blob/type.go
watchtower/blob/type_test.go
watchtower/lookout/justice_descriptor_test.go
watchtower/lookout/lookout.go
watchtower/lookout/lookout_test.go
watchtower/wtdb/session_info.go
watchtower/wtpolicy/policy.go
watchtower/wtserver/server.go
watchtower/wtserver/server_test.go
watchtower/wtwire/create_session.go
watchtower/wtwire/create_session_reply.go
watchtower/wtwire/wtwire.go

This PR refactors the internal handling of session parameters within the existing watchtower packages in preparation for the watchtower client integration.  First, we introduce a `blob.Type` bitvector, composed of `blob.Flag`s. Blob types are meant to replace the `uint16` versioning scheme, and are used to signal what features the client is requesting from the tower.
Two flags are introduced: `FlagReward` and `FlagCommitOutputs`:
- `FlagReward` is used to indicate if the tower will be getting a portion of the breached balance. Otherwise, the tower will sweep all funds to the client.
- `FlagCommitOutputs` instructs the tower that the payload is the fixed-size, v0 blob format. This is added as a flag so that it could, in theory, be turned off and replaced with a different encoding.
Finally, …

wtpolicy: migrate to using wtpolicy.Policy + blob bitvector flags

---

log.go
watchtower/conf.go
watchtower/conf_experimental.go
watchtower/config.go
watchtower/errors.go
watchtower/interface.go
watchtower/log.go
watchtower/standalone.go

In this PR, we introduce the `watchtower` package used to configure and run a watchtower. The top level `watchtower.Standalone` struct couples the `lookout` and `wtserver` subsystems, enabling the full server-side protocol and breach monitoring. It also initializes the WTWR subsystem logger, which will be inherited by both the lookout and wtserver packages.
In order to facilitate the package's use as an extension to LND or a standalone daemon, the `watchtower.Config` provides a common interface for all of the towers resources and configurable parameters. These resources are then passed down to the appropriate subsystems so that they can faithfully perform their duties. Some of these options are to be configured from the command line, which leads us to:
As these parameters begin to be …

watchtower pkg

---

.gitignore
lnd_test.go
lntest/btcd.go
lntest/harness.go
lntest/node.go

This PR alters the integration test setup to use a chain backend separate from the miner. This is done to make it possible to switch the chain backend with a different implementation (currently we are using `btcd`).
The separation of chain backend and miner increases the delay of transaction and block propagation, since there is one extra node every event must be relayed through. This caused some test flakes to manifest themselves, and they are fixed one by one in the commits before splitting backend and miner. 
A follow-up PR will enable `bitcoind` and `neutrino` as chain backends.

[Integration tests] Split chain backend and miner

---

watchtower/wtserver/server.go
watchtower/wtwire/summary.go

This PR makes some preliminary changes in advance of the watchtower client and watchtower capstone integrations.
The primary additions are the `wtpolicy.Policy`, which bundles up the negotiable watchtower parameters with the aim of later exposing them via command line. Since the same policy is shared between client and server, the struct is placed in it's own `wtpolicy` package. We also define `blob.Type` which allows for further negotiation at the session level (see #2439 for more info).
In addition, this PR adds log messages for wtserver messages that are sent and received, doing so with a `MessageSummary` method in `wtwire`. This code can then be shared across client and server, to ensure both sides see mirrored log messages. This final top-level PR is predominately this change. …

[watchtower] add wtpolicy.Policy and wtserver message logging

---

docs/INSTALL.md

In this commit, we modify the Linux installation instructions to use the
pre-built archives rather than install from the ppa. We do this as
typically the ppa lags behind the latest releases, and also by
downloading it in this new manner, we're able to verify the sha256 sum
of the installed Go release.

docs/INSTALL.md: update Go installation options for Linux

---

watchtower/wtserver/server.go
watchtower/wtserver/server_test.go

Small PR that ensures the wtserver will return the proper reward script for the client to include in it's transaction. Prior, we incorrectly used the address's `ScriptAddress`. This went unnoticed until doing the full e2e integration tests when no funds showed up in the tower's wallet.

watchtower/wtserver/server: return valid reward script

---

docs/code_contribution_guidelines.md

In this commit, we add a new section to the code contribution guidelines
explaining how to use `go mod replace`. This will be a common procedure
for any developer that needs to make a change in any of our sister
projects, so it's nice to have this outlined in a single place.

docs: add new section to contribution guidelines for go mod replace

---

release.sh

In this commit, we update the release script to include a directory
containing all of our vendored dependencies. This makes out releases
more self contained as they can be built using `go build -mod=vendor`
without requiring any package fetching.
Additionally, we pacakge the entire source as well.
Fixes #1550.

build: update release.sh to contain vendor archive + source code

---

rpcserver.go

This prevents certificate issues when accessing the gRPC REST proxy externally.
Fixes #1567.

rpcserver: forward gRPC proxy requests to localhost when listening on all interfaces

---

autopilot/combinedattach.go
autopilot/interface.go
autopilot/prefattach.go
autopilot/prefattach_test.go
lnd.go
pilot.go

Follow-up to #2341. 
We make a new autopilot heuristic `WeightedCombAttachment` that combines scores from multiple sub-heuristics into one that can be used by the agent. 
To make this possible we make sure the `NodeScore` API always returns scores in the range `0.0-1.0`.
For now we only use the existing heuristic with a weight of 1.0, but this will change in the follow-up PRs. 
Builds on #2341

[autopilot] Weighted combined attachment heuristic

---

go.mod
go.sum

In this commit, we update our btcwallet dependency to point to the
latest version. This latest version redefines what the wallet will
consider as an initial sync. We'll now define it by determining if the
wallet has synced up to its birthday block, rather than looking at the
number of UTXOs in the wallet. This was needed, especially for light
clients, because it would cause unnecessary rescans to happen from the
wallet's birthday if the wallet had no UTXOs.

build: update btcwallet dependency to new initial sync definition

---

contractcourt/chain_arbitrator.go
contractcourt/channel_arbitrator.go
contractcourt/channel_arbitrator_test.go
contractcourt/htlc_success_resolver.go
contractcourt/htlc_timeout_resolver.go
lnd_test.go
lnwallet/channel.go
server.go

In this PR, we extend the `htlcSuccessResolver` to settle the invoice,
if any, of the corresponding on-chain HTLC sweep. This ensures that the
invoice state is consistent as when claiming the HTLC "off-chain".
Partly addresses #2032 (the receiver side).

contractcourt: settle invoice when claiming HTLC on-chain

---

autopilot/agent.go
autopilot/agent_test.go
autopilot/combinedattach.go
autopilot/interface.go
autopilot/manager.go
autopilot/prefattach.go
cmd/lncli/autopilotrpc_active.go
config.go
lnrpc/autopilotrpc/autopilot.pb.go
lnrpc/autopilotrpc/autopilot.proto
lnrpc/autopilotrpc/autopilot_server.go
pilot.go

This PR adds a new configuration option `--autopilot.heuristic` that lets the user set the heuristics to use during operation. Several heuristics can be set and weighted, making it possible to use a combination of different heuristics to open channels. Example:
```
lnd --autopilot.heuristic=externalscore:0.4 --autopilot.heuristic=preferential:0.6
```
The default value is, as before, `--autopilot.heuristic=preferential:1.0`
It also adds a new RPC to the autopilot subserver, called `QueryScores`, that essentially works as a dry-run of the possible heuristics. It will query the available heuristics with the current channel graph, returning the scoring given. The weighted, active heuristic will also be queried.
A command`lncli autopilot query` is added to hit the new RPC.  
Builds on #2341 …

[Autopilot] Add heuristic dry-run option

---

chanbackup/backup.go
chanbackup/backup_test.go
chanbackup/backupfile.go
chanbackup/backupfile_test.go
chanbackup/crypto.go
chanbackup/crypto_test.go
chanbackup/log.go
chanbackup/multi.go
chanbackup/multi_test.go
chanbackup/pubsub.go
chanbackup/pubsub_test.go
chanbackup/recover.go
chanbackup/recover_test.go
chanbackup/single.go
chanbackup/single_test.go
keychain/derivation.go

In this PR, we introduce a new package that implements our current scheme for static channel backups (SCB's). Note that the serialization format will likely change to use a TLV schema rather than a raw packed format. However the serialization is isolated to a single instance and can easily be modified when we decide on the final TLV format. As a result, this PR c an be reviewed as is. 
Depends on #2369. 
For encryption, we utilize `chacha20poly1305` with a random 24 byte nonce. We use a larger nonce size as this can be safely generated via a CSPRNG without fear of frequency collisions between nonces generated. To encrypt a blob, we then use this nonce as the AD (associated data) and prepend the nonce to the front of the ciphertext package.
For key generation, in order to ensure the user …

chanbackup: add new package implementing static channel backups

---

lnrpc/walletrpc/walletkit_server.go

trivial: typo fix

---

config.go

In this commit, we increase the default trickle delay from 30s to 1m30s.
We do this as before we implement the new INV gossip mechanism, we want
to de-emphasise the quick propagation of updates through the network
which eats up bandwidth.

config: increase default trickle delay from 30s to 1m30s

---

Makefile

Testing out a different method of computing coverage results that hopefully is more accurate. The current script used by `unit-cover` does not correctly account for cross-package coverage. I found that https://github.com/ory/go-acc properly accounts for areas of code base that I know to be tested indirectly. As a result, our coverage gets a nice 2.6% bump.
This will allow us to make refactorings like #2481 simpler, and not have to worry as much about our code's location relative to the testing files. I would be interested in seeing how the coverage changes on that PR while using this as the coverage tool.

build: more reliable coverage using go-acc

---

htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/switch_test.go
lnd_test.go
lnwire/onion_error.go
routing/router.go

Fixes #2321 (see issue for details). 
One implementation level thing to note is that we'll still expect this error on the network when decoding and during routing retry attempts. Otherwise, we won't be able to parse the errors from nodes in the wild that haven't upgraded to this new version. 
Replaces #2363.

multi: deprecate IncorrectHtlcAmount 

---

breacharbiter_test.go
channeldb/channel.go
channeldb/db.go
channeldb/db_test.go
channeldb/error.go
channeldb/graph.go
channeldb/migrations.go
channeldb/nodes.go
contractcourt/chain_arbitrator.go
lnwallet/channel.go
lnwallet/channel_test.go
peer.go
rpcserver.go

In this PR, we add number of methods that will be used for the final SBC implementation. Along the way we refactor some core functionality within the package to ensure that we're able to properly re-use database transactions at higher levels. See the commits for further details along with the parent PR to this. 
Broken off of #2313.

channeldb: prepatory modifications for full SCB implementation 

---

channeldb/addr.go
channeldb/addr_test.go

Addresses that don't pass these added checks, would previously cause us to fail reading the node from the DB.

Validate addresses before writing them to DB

---

watchtower/wtpolicy/policy.go
watchtower/wtserver/server.go
watchtower/wtserver/server_test.go
watchtower/wtwire/create_session.go
watchtower/wtwire/summary.go

This PR extends session negotiation to include a `RewardBase` parameter, which is used in conjunction with the proportional `RewardRate` to give users and towers full mx+b control over the tower payouts. For example, the base can be set to a multiple of dust to ensure that the tower's output isn't too small to manifest on chain. With only a proportional reward, it could be the case that the tower receives nothing up until som threshold if the fee rate is low or the channel is small.

wtpolicy+wtwire+wtserver: add base reward

---

watchtower/lookout/justice_descriptor_test.go
watchtower/wtmock/peer.go
watchtower/wtmock/signer.go
watchtower/wtserver/server_test.go

This PR adds a `watchtower/wtmock` package where all reusable mocks for watchtower unit tests will end up. This makes them easily accessible from various packages without needing to reimplement them in each individual package

watchtower/multi: move MockSigner+MockPeer to wtmock

---

peer.go
server.go

In this commit, we modify our default local feature bits to require the
Data Loss Protection (DLP) feature to be active. Once full Static
Channel Backups are implemented, if we connect to a peer that doesn't
follow the DLP protocol, then the SCBs are useless, as we may not be
able to recover funds. As a result, in prep for full SCB deployment,
we'll now ensure that any peer we connect to, knows of the DLP bit. This
could be a bit more relaxed and allow _connections_ to non-DLP peers,
but reject channel requests to/from them. However, this implementation is
much simpler.

server: require the DLP bit for all incoming/outgoing connections

---

lnwire/features.go

In this commit, we fix a bug in the way we defined our even/odd features
for a particular feature. The check for if a feature bit is part of a
pair assumes that the pair bit has the exact same name as the bit being
queried. The way we defined our feature map didn't take note of this
assumption, as a result, any attempts to require a new bit moving from
optional to required would fail since the bit would be found, but the
names differed.

lnwire: ensure even/odd features have the same base name

---

lnwire/onion_error.go
lnwire/onion_error_test.go

In this commit, we modify the decoding of the `FailUnknownPaymentHash`
message to ensure we're able to fully decode the legacy serialization of
the onion error. We do this by catching the `io.EOF` error as it's
returned when _no_ bytes are read. If this is the case, then only the
error type was serialized and not also the optional amount.

lnwire: ensure we're able to decode legacy FailUnknownPaymentHash

---

lnpeer/write_buffer_pool.go
lnpeer/write_buffer_pool_test.go
peer.go
queue/gc_queue.go
queue/gc_queue_test.go
server.go

In this PR, we implement a write buffer pool for LN peers. Currently, each peer object embeds a 65KB byte array, which is used to serialize messages before writing them to the wire. As a result, every new peer causes a large memory allocation, which places unnecessary burden on the garbage collector when faced with short-lived or flapping peers. This has been observed historically on well-peered nodes and more recently reported by @alexbosworth on y'alls node.
The solution proposed here implements a buffer pool, that dynamically grows and shrinks based on the demand for write buffers corresponding to active peers. This greatly helps when there is a high level of churn in peer activity, even if there is only one flapping peer.
To accomplish this, the bulk of this proposal implements a new …

peer: write buffer pool

---

contractcourt/briefcase_test.go
contractcourt/commit_sweep_resolver.go

Now that the sweeper is available, it isn't necessary anymore for the
commit resolver to craft its own sweep tx. Instead it can offer its
input to the sweeper and wait for the outcome.
When this PR is merged, a follow up is to use sweeper in `htlcSuccessResolver` too.

cnct: use sweeper in commit resolver

---

lnrpc/autopilotrpc/autopilot_server.go
lnrpc/invoicesrpc/invoices_server.go
lnrpc/walletrpc/walletkit_server.go

1. Remove unused "os" import from lnrpc/autopilotrpc. This would cause the build to fail since the import is not used. It was not detected since the file is under a build flag.
2. Cleanup other subserver imports by running `goimports`

[trivial] cleanup subserver imports

---

utxonursery.go

Previously we would use the best known height as height hint, which
could lead to using a height hint above the actual block it confirms,
hence losing track of the confirmation.

utxonursery: use baby expiry as height hint

---

chainntnfs/neutrinonotify/neutrino.go

Would otherwise update height hint cache even on error during rescan.

chainnrnfs/neutrino: return on historicalConf error

---

chainntnfs/interface_test.go

In this commit, we modify the main interface-level tests for neutrino to
skip the block catch up re-org test. We do this, as the test itself is
very unstable and only passes occasionally by the grace of RNGesus.
What's needed to ensure it passes reliably is to extend neutrino with a
cache of the last N blocks disconnected. Sample output of the affected
test when run:
```
--- SKIP: TestInterfaces/neutrino_test_catch_up_on_missed_blocks_w/_reorged_best_block (0.00s)
interface_test.go:1574: skipping re-org test for neutrino
```

chainntnfs: skip catch up re-org test for neutrino temporarily

---

rpcserver.go

A recent change in this area of the codebase refactored some code to
make way for the deprecation of the streaming multi-route `SendToRoute`
method. Along the way, it removed the parsing of the `PaymentHashString`
field for the sync `SendToRouteSync` which is meant to be used via the
REST interface. In this commit, we fix this by populating _both_
`PaymentHash` and `PaymentHashString`. This is OK, as
`extractPaymentIntent` will check both values to extract the hex-encoded
payment hash if it's specified.

rpc: fix regression in SendToRouteSync payment hash parsing

---

fundingmanager.go

gives unnecessary output such as
```
2019-02-06 11:26:45.338 [INF] FNDG: Announcing ChannelPoint(cf659a58d68f206531136bf19dea82863a488937f9f4c3d489c450ad81c1724e:0), short_chan_id=(*lnwire.ShortChannelID)(0xc000670a60)(1977:1:0)
```

[trivial] fundingmanager: don't spew log shortChanID

---

watchtower/wtwire/features.go

In light of #2570, this PR ensures that the local names of wtwire feature bits are uniform between even/odd features. This ensures that `Has` properly returns true if the feature vector supports optional or required for a given feature bit

watchtower/wtwire/features: make wtwire features uniform

---

watchtower/wtserver/server.go
watchtower/wtserver/server_test.go
watchtower/wtwire/init.go
watchtower/wtwire/message.go
watchtower/wtwire/wtwire.go
watchtower/wtwire/wtwire_test.go

This PR modifies the `wtwire.Init` message to send only connection-level features and the chain hash of the chain that each client is on. The previous message sent local and global features to mimic the design of the `lnwire.Init` message, though there has been some rough consensus that we will move away from that in favor of an `Init` message of this form.
This change fixes two things:
- The global features don't need to be advertised at the connection level, as they have no impact on the connection. The move to calling the "connection features" is supposed to be more indicative that the feature bits only impact the behavior of the protocol over the lifetime of the established connection.
- Adding the chainhash ensures that a client doesn't accidentally back up its state to server on the …

watchtower/multi: send connection features + chain hash in Init

---

lnwire/error.go

This commit changes the `MaxPayloadLength` function for error messages to return `65535` instead of `65536`.  Max message size is the former.

lnwire: change error's MaxPayloadLength to 65535

---

docker/ltcd/Dockerfile

This PR fixes the build error with the ltc dockerfile https://github.com/lightningnetwork/lnd/issues/2623.  This is the same issue that was resolved for btcd here: https://github.com/lightningnetwork/lnd/pull/2253.
I also split out the seperate instructions using `RUN` instead of stringing them together with `&&` because with `RUN` it's easy to see which execution statement failed.  Not using `RUN` will result in smaller image sizes, but since this `Dockerfile` uses a multistage build, the net result is the same.
Fixes #2623

fix glide build error with docker ltcd

---

watchtower/config.go
watchtower/standalone.go
watchtower/wtserver/server.go
watchtower/wtwire/features.go
watchtower/wtwire/init.go
watchtower/wtwire/init_test.go

This PR is an extension of #2606 and #2605, adding a `CheckRemoteInit` helper method to the `wtwire.Init` message. Once the client is merged, this will checked in three different places with in the code base, so it makes sense to centralize this logic. We also add unit tests to ensure that the combination of features bits proposed via client and server will work together from the perspective of both the client and server.
Depends on:

wtwire: add CheckRemoteInit helper

---

go.mod
go.sum

This latest version of neutrino contains some fixes that make lnd a bit
snappier when running on mobile devices. We'll now wait until we have our
first peer before we try to sync the chain. We'll also no longer try to fail
to query filter checkpoints if we don't actually have any to fetch.

build: update to latest version of neutrino

---

channeldb/graph_test.go
routing/router.go
routing/router_test.go

Since we should always get a `ChanInfo` before a channel update, we can exit early if we receive a `ChannelUpdate` for an edge not in the graph.
Earlier we would attempt to `GetUTXO` in the case we couldn't find it in the graph, which is a heavy operation for some backends, with the subsequent `UpdateEdgePolicy` failing regardless.
Broken off of #2279

routing: ignore ChannelUpdates for unknown channels

---

config.go
lnd_test.go
netann/chan_status_manager.go
netann/chan_status_manager_test.go
netann/channel_state.go
netann/channel_update.go
netann/channel_update_test.go
netann/interface.go
peer.go
server.go
test_utils.go

In this PR, we introduce a new subsystem called the `netann.ChanStatusManager` responsible for managing the announcement of channel updates which toggle a channel's disabled bit. Most of the logic has been moved into a new `netann` package, which offers greater unit testability of the subsystem's behavior.
The `netann.ChanStatusManager` exposes two methods:
```golang
func RequestEnable(outpoint wire.OutPoint) error {}
func RequestDisable(outpoint wire.OutPoint) error {}
```
Together, these allow other subsystems to request a toggle in a particular direction. The `netann.ChanStatusManager` then handles the task of dropping duplicate requests, and also ensuring that it's network behavior follows a well-defined state machine.
At any point, the `netann.ChanStatusManager` categorizes known …

netann: channel status manager

---

channeldb/db.go
channeldb/meta_test.go
channeldb/migrations.go
channeldb/migrations_test.go
discovery/gossiper.go
discovery/gossiper_test.go
discovery/message_store.go
discovery/message_store_test.go
discovery/mock_test.go
discovery/reliable_sender.go
discovery/reliable_sender_test.go
server.go

In this commit, we address an issue where it's possible that we failed
to send the channel update message for a channel to the remote peer due
to them being offline. This would cause issues with private channels, as
a channel update message is needed for the remote peer to be aware of
the channel's forwarding policy. Due to the latest changes to
NotifyWhenOnline, we can now attempt to send the message every time we
detect the remote peer is online until success.
Depends on #1505.
Fixes #1347.

discovery/gossiper: reliably send channel update msg to remote peer

---

channeldb/db.go
channeldb/meta_test.go
channeldb/migrations.go
channeldb/migrations_test.go
discovery/gossiper.go
discovery/gossiper_test.go
discovery/message_store.go
discovery/message_store_test.go
discovery/mock_test.go
server.go

In this PR, we add a new store within the database that'll be responsible for storing gossip messages which we need to reliably send to peers. This aims to replace the current messageStore that exists within the gossiper, so much of this logic is borrowed from there. One of the main differences between the two is that we now index messages with a new key format in which we take into account the message's type. This allows us to store different messages for a specific channel with a peer. The new key format will require a migration, which has been included in this PR as well.
This will serve as a basis for #1595.

channeldb+discovery: add gossip message store

---

cmd/lncli/commands.go

Closes #2647 
Still calling `printJSON()` here as it was in the past, but now am returning an error back up to `main()` where `fatal()` is called if an error is returned which returns the correct error code and prints the error to stderr.
`sendPaymentRequest` isn't tested anywhere right now, hence why no tests were added. I can add tests if you'd like, though I'm probably not the right person to properly test this properly from scratch, and it's probably out of scope a bit.
logging level
(the tab …

lncli: returning non 0 exit code when paying invoice fails

---

lnd_test.go

Removes a warning I am always getting. Apparently `lnd_test.go` is not linted in travis.

lnd_test: remove unkeyed field references

---

go.mod
go.sum

In this commit, we update lnd to build against the latest version of
neutrino. This new version fixes a bug left behind as a result of the
btcd filter bug fix. When we were comparing filters in order to ban
invalid peers, we used the old OP_RETURN filtering rather than the new
one. As a result, we might've rejected a valid filter/block as we were
applying the old (incorrect) rules.

build: update to latest neutrino build

---

breacharbiter_test.go
channeldb/witness_cache.go
channeldb/witness_cache_test.go
contractcourt/channel_arbitrator.go
contractcourt/htlc_incoming_contest_resolver.go
contractcourt/htlc_outgoing_contest_resolver.go
contractcourt/htlc_success_resolver.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/test_utils.go
invoices/invoiceregistry.go
lntypes/preimage.go
lnwallet/channel.go
lnwallet/channel_test.go
lnwallet/interface.go
lnwallet/test_utils.go
lnwallet/transactions_test.go
mock.go
server.go
witness_beacon.go

This PR adds batched writes for witnesses discovered in HTLC forwarding. At the same time, we correct a nuanced consistency issue related to a lack of synchronization with the channel state machine. Forcing the individual preimage writes to be synchronized with the link incurs a heavy performance penalty (about 80% from my measurements). Batching these allows us to minimize the number of db transactions required to write the preimages, allowing us to reinsert the batched write into the link's critical path and resolve the possible inconsistency. In fact, the benchmarks actually showed a slight performance improvement, even with the extra write in the critical path.
See commit messages for more details.

htlcswitch: batch preimage writes/consistency fix

---

docs/INSTALL.md

This PR is about bumping go1.11.4 to 1.11.5 in the Linux part of the INSTALL.md file because 1.11.5 is now the last stable release. It modifies the package name from 1.11.4 to 1.11.5 and the hashes associated with them. 
This was initially an Issue but Roasbeef commented that I should turn this into a PR.

INSTALL.md : bump to go.1.11.5 on Linux

---

brontide/conn.go
brontide/noise.go
peer.go
pool/read.go
pool/worker.go
pool/worker_test.go
pool/write.go
server.go

This PR is a follow up to #2419 and #2385, introducing an `lnpeer.WritePool` and `brontide.ReadPool`.  Requests to read/write messages are submitted to the respective pool, which maintains a set of workers that handle the encoding/decoding. This builds on the prior PRs, since each pool is backed by a `lnpeer.WriteBufferPool` and `brontide.ReadBufferPool`, ensuring that buffer used in each are efficiently reused before being returned to the runtime. 
With #2419 and #2385, the total memory that will be allocated is linear in the number of peers/connections maintained by the daemon. With the read and write pools, we modify that to be at most linear in the _number of specified workers_. More importantly, these changes completely decouple read and write buffer allocations from the …

lnpeer+brontide: reduce memory footprint using read/write pools for message encode/decode

---

contractcourt/commit_sweep_resolver.go

The wrong error variable was returned, causing a resolution failure to
be interpreted by the channel arbitrator as a success.
Fixes #2687

cnct: fix error returning bug

---

docker/README.md

A small mistake in docker guide. 
-Change network from simtest to testnet for connection to testnet faucet.

Change network from simtest to testnet for connection to testnet faucet

---

docs/INSTALL.md

Change the following two BIP links In the „Using Neutrino“ section:
- BIP 157: broken link -> https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki
- BIP 158: link to auxiliary files -> https://github.com/bitcoin/bips/blob/master/bip-0158.mediawiki

docs/INSTALL.md: fix links to BIPs

---

peer.go

This reverts commit db2c104111c3c12e1651120fe5a51ce03dad8c58.
In #2474, a commit was added to reduce the write timeout from 50s to 5s as the existing timeout is rather long in the context of TCP. An issue arises when the remote peer is unable to validate gossip messages as quickly as we are sending them, causing 1) the remote peer's discovery message stream to backup, and 2) the backpressure to be applied to the sender side after any connection level buffers are also full. The result is that the sender disconnects prematurely, and causes connection loops when large amounts of gossip traffic need to be sent (e.g. on initial sync or if node is offline for a bit).
As a temporary measure, this PR reverts the commit and restores the 50s timeout. As of #2474, this 50s timeout is owned by the …

Revert "peer: reduce write timeout to 10s"

---

discovery/gossiper.go
discovery/mock_test.go
fundingmanager_test.go
htlcswitch/link_test.go
htlcswitch/mock.go
lnpeer/peer.go
peer.go
server.go

peer: deprioritize gossip traffic

---

Makefile

When using the unit test flakehunter and specifying a package, after the
first successful run, all of the tests would be run, rather than just
the ones within the specified package.

Makefile: fix unit test flakehunter when running on specific package

---

Makefile

Actually install btcd when running `make btcd`...

Makefile: actually install btcd w/ make btcd

---

channeldb/channel.go
contractcourt/chain_arbitrator.go
lnwallet/channel.go
lnwallet/channel_test.go

In this PR, we ensure that it isn't possible for a state mutation to take place _after_ the force close process has began. Before this commit, it may have been possible for a link to trigger/accept a new state update concurrently while a channel was being updated. We'll now mark the channel as borked in the `ForceClose` method which will:
* Prevent all channel database commitment mutation calls from going through 
* Prevent the target link reconnecting 
Along the way, another bug was fixed that would cause an error in the state machine from silently passing through, in the event that a call to `SignNextCommitment` failed at the database update state.

lnwallet: within ForceClose, mark the channel as borked, prevent mutations for borked channels

---

contractcourt/htlc_success_resolver.go
fundingmanager.go
lnwallet/btcwallet/btcwallet.go
utxonursery.go
watchtower/lookout/punisher.go

In this PR, we update our btcwallet dependency to the latest version, which includes some minor improvements to our error handling when broadcasting transactions.
Along the way, we also address a lingering issue within some subsystems that are responsible for broadcasting transactions. Previously, ErrDoubleSpend indicated that a transaction was already included in the mempool/chain. This error was then modified to actually be returned for conflicting transactions, but its callers were not modified accordingly. This would lead to conflicting transactions to be interpreted as valid, when they shouldn't be.
Depends on https://github.com/btcsuite/btcwallet/pull/597.
Fixes #2657.

lnwallet/btcwallet: remove invalid transactions from the wallet when broadcast fails

---

autopilot/agent.go
autopilot/agent_test.go

This commit fixes a regression in how we allocate funds to attempted
channels. We would earlier stay within the channel size limits, but we
wouldn't account for funds consumed by other channels being opened in
parallel.
We fix this by introducing a loop which greadily tries to distribute the
funds among the channels to open, and reduces the number of channels to
open in case not enough funds are available to satisfy the channel size
limits.
Fixes https://github.com/lightningnetwork/lnd/issues/2609

[autopilot] distribute available funds among channels

---

contractcourt/chain_arbitrator.go
contractcourt/chain_watcher.go
contractcourt/chain_watcher_test.go
lnwallet/channel_test.go
lnwallet/test_utils.go

In this PR, we fix an off-by-one error when handling force closes from the remote party. Before this commit, if the remote party broadcasts state 2, and we were on state 1, then we wouldn't act at all. This is due to an extraneous +1 in the comparison, causing us to only detect this DLP case if the remote party's state is two beyond what we know atm. A test that fails when run on master has been added to demonstrate the bug, and confirm that it has been fixed. 
Fixes #2764.

contractcourt: fix off-by-one error in closeObserver

---

config.go
tor/controller.go

This PR should fix #2388 and #2176 in the following ways:
* allowing NULL authentication when attempting to create a hidden service automatically
* when automatic hidden service configuration is disabled, defaulting to listening on localhost and allowing manual override for manual or alternative hidden service configuration
This allows `lnd` to work better in environments where the Tor daemon lives on a different machine, such as Whonix or OnionPi, and where certain Tor control protocol requests and responses are filtered.
Fixes #2388 
Fixes #2176

Tor null auth and listen fixes

---

watchtower/wtclient/backup_task.go
watchtower/wtclient/backup_task_internal_test.go
watchtower/wtclient/candidate_iterator.go
watchtower/wtclient/client.go
watchtower/wtclient/client_test.go
watchtower/wtclient/errors.go
watchtower/wtclient/interface.go
watchtower/wtclient/log.go
watchtower/wtclient/session_negotiator.go
watchtower/wtclient/session_queue.go
watchtower/wtclient/stats.go
watchtower/wtclient/task_pipeline.go
watchtower/wtdb/client_session.go
watchtower/wtdb/session_info.go
watchtower/wtdb/tower.go
watchtower/wtmock/client_db.go
watchtower/wtmock/peer.go
watchtower/wtserver/server.go
watchtower/wtserver/server_test.go
watchtower/wtwire/create_session_reply.go
watchtower/wtwire/error_code.go

This PR presents the bulk of the `wtclient` package, a reliable subsystem that backs up revoked states to a configured watchtower. #2516 introduced the logic for constructing justice transactions and encrypting them. Here we add the remainder of the capabilities that aggregates all revoked states, assigns them to a particular session, then signs justice transactions and uploads them to the proper tower.
Great care is taken to ensure that the `wtclient.TowerClient` can do all of this in a non-blocking fashion, ensuring that we maintain LND's high throughput and performance in HTLC forwarding. However, this too creates difficulties of its own, as we must ensure that the whole process is reliable, and will continue until completion if the daemon is shutdown or killed intermittently. Thus, …

watchtower/wtclient: reliable, asynchronous pipeline for revoked state backups

---

config.go
lncfg/workers.go
lncfg/workers_test.go
server.go

This PR adds CLI configuration hooks for worker pools to allow users to set the desired number of works in the daemon-level read, write and sig pools. At the moment, these are chosen as a multiple of `runtime.NumCPU()`, which may provide the pool with too few resources on low end devices. At the same time, nodes that have a large number of peers may an inadequate number of workers even if they have a decent number of CPUs. In general, it is best to decouple these sorts of constants from the runtime, and let higher level applications decide these values as needed.
```
workers:
--workers.read=     Maximum number of concurrent read pool workers. (default: 16)
--workers.write=    Maximum number of concurrent write pool workers. (default: 16)
--workers.sig=      Maximum number of concurrent …
```

lncfg: add CLI worker configuration

---

cmd/lncli/commands.go

Increases the default window from 250 to 25k. Many
users have reported attempting recovery with the
default value only to find an empty wallet. This
change should help ensure that the first recovery
attempt succeeds for the majority of nodes that
have modest load. It might prudent to consider
increasing this value further in the future if
the issue persists or average node age increases.

cmd/lncli: increase default recovery window to 2.5k

---

contractcourt/channel_arbitrator_test.go
contractcourt/contract_resolvers_test.go
contractcourt/htlc_outgoing_contest_resolver.go
contractcourt/htlc_timeout_resolver.go
contractcourt/htlc_timeout_resolver_test.go
utxonursery.go

In this commit, we simplify the existing `htlcTImeoutResolver` with some
newly refactored out methods from the `htlcTimeoutContestResolver`. The
resulting logic is easier to follow as it's more linear, and only deals
with spend notifications rather than both spend _and_ confirmation
notifications. Along the way we add some new tests in order to exercise 
the refactored logic. 
Fixes #2782.

 contractcourt: simplify htlcTimeoutResolver

---

watchtower/wtdb/mock.go
watchtower/wtserver/create_session.go
watchtower/wtserver/delete_session.go
watchtower/wtserver/interface.go
watchtower/wtserver/server.go
watchtower/wtserver/server_test.go
watchtower/wtserver/state_update.go
watchtower/wtwire/delete_session.go
watchtower/wtwire/delete_session_reply.go
watchtower/wtwire/message.go
watchtower/wtwire/wtwire_test.go

This PR adds a new handler to the watchtower server, allowing a client to delete an active session. The new `wtwire.DeleteSession` message can be sent to by the client, instructing the server to remove the session corresponding to the public key used in the brontide handshake. The tower then responds with a `wtwire.DeleteSessionReply` to return the result. In the short term, this request will not be used by the wtclient package. We plan to do so after implementing the appropriate heuristics as to when exactly the client should delete a particular session. However, implementing this on the server-side allows us to retroactively add session deletion in the client without needing to introduce any additional feature bits or negotiation.

watchtower/wtserver: add DeleteSession request

---

README.md

Eliminate the reference to Bitcoin testnet which is now dated

README: remove testnet3 specificity

---

breacharbiter.go
breacharbiter_test.go
mock.go

See second commit message for details

breacharbiter: watch for spends on all inputs until reaching terminal states

---

lnwire/features.go
lnwire/init_message.go

This commit fixes an incorrectly calculated `maxAllowedSize` for feature vectors that also affected the maximum payload length of the `init` message.  The maximum message size for any message is `65535` bytes, yet the old `maxAllowedSize` added the brontide MACs (???) to the overall "usable" size and calculated the length of the feature vectors from that.  Anyways, fixed that here.

lnwire: features "maxAllowedSize" fix

---

chancloser.go
contractcourt/chain_arbitrator.go
lnd_test.go
netann/chan_status_manager.go
test_utils.go

This PR reorders logic when closing channels to sign the disabling update before closing the channel in the database. Currently the disable is attempted asynchronously after the close, after which the channel may be removed from the graph and leads to logs generated in #2696.
The fix is simply to do the disables synchronously before closing the channels either cooperatively or unilaterally. The integration test framework has been updated to assert that a disable message is always sent after closing if the channel policy indicates it was enabled at the time of the closure.
The one exception to this was the reorg channel funding itest, for which this cannot happen because the channel has been removed from the channel graph. A separate assertion that ignores the disable assertion is added to …

cnct+chancloser: disable channel before closing

---

channeldb/channel.go
channeldb/graph.go
channeldb/invoices.go

In this commit, we convert all the `Update` calls which are serial, to
use `Batch` calls which are optimistically batched together for
concurrent writers. This should increase performance slightly during the
initial graph sync, and also updates at tip as we can coalesce more of
these individual transactions into a single transaction.

channeldb: convert all Update calls to use Batch

---

server.go

This PR solves the following use case: 
1. connect to other node from a node running on a mobile device and open a channel.
2. switch networks from wifi to cellular
3. it takes more than 1 minute for the mobile node to re-connect to the remote node.
My Investigation shows that when switching networks the connection immediately closes on the mobile but stays open on the remote node until timed out. 
During this time further attempts to connect are done from the mobile but the remote node rejects them preferring the local connection using the following logic: https://github.com/lightningnetwork/lnd/blob/master/server.go#L2047
It looks like there is an implicit assumption at this point that the existing peer local connection is outbound, which is not the case I am describing (in my case both …

Reconnect to peer when switching networks

---

lncfg/workers.go
peer.go
server.go

peer: catch write timeouts, retry with backoff

---

docs/MAKEFILE.md

Commit ca28c0b removed the dep section,
so it shouldn't be mentioned as a target in other targets.
Also, Glide doesn't seem to be used anymore as well.
logging level
per default)
already exist

docs/MAKEFILE: Remove mention of dep and Glide

---

htlcswitch/switch.go

Tiny addition. Added target node's pubkey on the insufficient capacity error.
It helps identify nodes that could use more inbound liquidity (i.e. potential fees).

htlcswitch/switch: log target node on insufficient cap error

---

rpcserver.go

This is a better alternative than retrieving it from the graph as it's
possible that the channel is pruned from it doing to not having any
updates within the past two weeks.
Fixes https://github.com/lightningnetwork/lnd/issues/2823.

rpcserver: retrieve Channel ChanId from OpenChannel record

---

signal/signal.go

In this commit, we modify the primary `signal` package to instead catch
all signals. Before this commit, it would only catch the interrupt
signal sent from the kernel. With this new commit, we'll now also catch
(or attempt to catch): `SIGABRT`, `SIGTERM`, `SIGSTOP`, and `SIGQUIT`.

signal: catch all termination signals by default

---

chainregistry.go
lnd_test.go

In this commit, we lower the default CLTV delta from 144 (1 day) to 40
blocks (~7 hours). We do this as the initial value was purposefully very
high, and was only in place as place holder in earlier versions of the
software. Such a high value can also discourage path finding algorithms
from taking lnd paths due to the negative impact of CLTV value in widely
deployed heuristics.

lnd: lower default CLTV delta from 144 to 40

---

rpcserver.go

AFAIK average degree of graph is calculated as twice the number of edges divided by number of vertices. Also now the value makes more sense, because now it means average number of channels connected to single node.

rpcserver: correct avg degree in GetNetworkInfo

---

channeldb/db.go
channeldb/error.go
channeldb/graph.go
channeldb/graph_test.go
discovery/gossiper.go
discovery/gossiper_test.go
routing/ann_validation.go
routing/router.go
routing/router_test.go
server.go

In this PR, we introduce a new persistent index for zombie edges to quickly reject announcements for edges we've previously deemed as zombies. Care has been taken to ensure we don't reject fresh updates for edges we've considered zombies.

channeldb+routing+discovery: reject zombie announcements

---

lnrpc/routerrpc/log.go
log.go

This PR register the `routerrpc` sub server logger so that its log level can be set.

routerrpc: register router sub server logger

---

lnd_test.go
lntest/harness.go
lntest/timeouts.go
lntest/timeouts_darwin.go

Splits out the `lntest` timeout constants into darwin and non-darwin variants. This is required for the `async_payment_benchmark` to pass reliably, as it suffers from a regression starting with go1.12+darwin after correcting the standard library's usage of fsync. See https://github.com/golang/go/issues/26650 and https://github.com/golang/go/issues/27415.

lntest/timeout: split into darwin and non-darwin timeouts

---

discovery/gossiper.go
discovery/gossiper_test.go
discovery/reliable_sender.go

In this commit, we address an assumption of the gossiper's recently introduce reliable sender. The reliable sender is currently only used for messages of unannounced channels. This makes sense as peers should be able to retrieve messages from the network if they've previously announced. However, within isMsgStale, we assumed that the reliable sender would be used for every ChannelUpdate being sent, even if the channel is already announced. Due to this, checking if the policy is stale was unnecessary. But since this isn't the case, we should actually be checking whether it is stale to prevent sending it later on.

 discovery: check if stale within isMsgStale for ChannelUpdate messages

---

channeldb/channel.go
channeldb/channel_cache.go
channeldb/channel_cache_test.go
channeldb/db.go
channeldb/graph.go
channeldb/invoices.go
channeldb/migrations.go
channeldb/options.go
channeldb/reject_cache.go
channeldb/reject_cache_test.go
config.go
lncfg/caches.go
lncfg/interface.go
lncfg/workers.go
lnd.go

This PR adds two caches housed within the channeldb to optimize two existing hot spots related to gossip traffic.
The first is dubbed a _reject cache_, whose entries contain a small amount of information critical to determining if we should spend resources validating a particular channel announcement or channel update. This improves the performance of [`HasChannelEdge`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/graph.go#L601), which is a subroutine of [`KnownEdge`](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L2272) and [`IsStaleEdgePolicy`](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L2281).
Each entry in the reject cache stores the following:
```golang
type rejectCacheEntry struct {
upd1Time int64
upd2Time int64 …
```

channeldb: add reject and channel caches

---

chainntnfs/bitcoindnotify/bitcoind.go

This PR fixes a bug that would cause the
notifier not to commit spend hints for items
that are not found. This is done by calling
UpdateSpendDetails with a nil detail, permitting
the notifier to begin updating the spend hints
with new blocks that arrive at tip. The change
is designed to mimic the behavior for historical
confirmation dispatch.
The symptom of this bug is needing to do many
long rescans on startup, even if new blocks
arrive after the rescan had completed. With
this change, nodes will have to do the scans
once more before their hints will be properly
updated. Restarts from then on should not
have this behavior.

chainntnfs: Always commit bitcoind spendhints

---

signal/signal.go

In this commit, we modify the set of default signals we attempt to catch in
order to execute a graceful shutdown. Before this commit, we would attempt
to catch/register for `SIGSTOP`. There're two issues with this
1. `SIGSTOP` is meant to be used in combination with `SIGCONCT` to allow a
process to be paused/resumed. Therefore, our action of shutting down once
received was incorrect.
2. `SIGSTOP` doesn't exist on windows, so users aren't able to compile on
this platform without modifying the codebase.

signal: don't attempt to catch SIGSTOP

---

discovery/sync_manager.go

In this commit, we address a bug where we'd attempt to replace the
stale active syncer when it transitioned to a passive syncer. This
replacement logic is only intended to happen when the active syncer
disconnects, as rotateActiveSyncerCandidate chooses and queues its own
replacement.

discovery: only replace stale active syncer if disconnected

---

cmd/lncli/commands.go

This is specifically on multi_file argument description

Remove equal sign on verifychanbackup cmd argument

---

lnd_test.go

This prevents a panic during test failure due to a child test calling
FailNow on a parent test context. The sub tests now capture the
testing.T object provided in each closure as opposed to ignoring it and
using the parent context.
```
--- FAIL: TestLightningNetworkDaemon/channel_backup_restore (81.16s)
lnd_test.go:78: Failed: (channel backup restore): exited with error: 
*errors.errorString Node restart failed: process did not exit
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:7577 (0xce9082)
assertDLPExecuted: t.Fatalf("Node restart failed: %v", err)
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:13647 (0xd0e544)
testChanRestoreScenario: assertDLPExecuted(
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:13851 (0xd25717) …
```

lnd_test: use child harness chan backup restore cases

---

channeldb/graph.go
channeldb/graph_test.go

This commit modifies FilterKnownChanIDs to skip edges that
we ourselves have deemed zombies. This prevents us from requesting
the updates from the remote peer, as this wastes bandwidth and cpu
cycles.
With the addition of regular historical spot checks in #2740, this will
prevent upgraded LND nodes from rerequesting these channels from
unupgraded LND nodes or implementations that don't filter out 
zombies. There are currently 3.3k zombie channels, so this would save
at least 3MB on historical syncs with such peers.

channeldb/graph: filter zombie channels in FilterKnownChanIDs

---

config.go
contractcourt/chain_arbitrator.go
contractcourt/channel_arbitrator.go
contractcourt/channel_arbitrator_test.go
htlcswitch/link.go
htlcswitch/link_test.go
htlcswitch/mock.go
htlcswitch/test_utils.go
lnd_test.go
peer.go
server.go

After the merge of #2839, a minimum cltv delta of 14 blocks is enforced for outgoing htlcs. This is a problem when forwarding to the final node which has an invoice with a cltv < 14. This happens in the wild.
In this case, `lnd` doesn't forward and returns an `ExpiryTooSoon` failure to the sender.
This PR reverts the parameters to their original values. 
It does not fully revert #2839, but instead introduces a clearer way to configure the relevant parameters and sets them to their original values. It replaces the original `broadcastRedeemMultiplier` and `expiryGraceDelta`.
In follow up #2887 the parameters are tuned further to improve the go-to-chain behaviour and forwarding policies.

htlcswitch: revert forwarding policy block delta requirements

---

config.go
server.go

This commit adds optional jitter to our initial reconnection to our
persistent peers. Currently we will attempt reconnections to all peers
simultaneously, which results in large amount of contention as the
number of channels a node has grows.
We resolve this by adding a randomized delay between 0 and 30 seconds
for all persistent peers. This spreads out the load and contention to
resources such as the database, read/write pools, and memory
allocations. On my node, this allows to start up with about 80% of the
memory burst compared to the all-at-once approach.
This also has a second-order effect in better distributing messages sent
at constant intervals, such as pings. This reduces the concurrent jobs
submitted to the read and write pools at any given time, resulting in
better reuse of …

server: stagger initial reconnects

---

discovery/sync_manager.go

Restores use of lazy sending for gossip messages, which wasn't caught in reviewing #2740

discovery/sync_manager: restore lazy gossip sends

---

htlcswitch/link.go

This is the quick fix version of #2913

htlcswitch: do not check final cltv for accepted invoices

---

chainregistry.go

To avoid the ChainService still attempting to access the database when
it gets closed, re-order the stop order such that the Chainservice gets
stopped before closing the DB.

chainregistry: stop Neutrino before closing DB

---

discovery/sync_manager.go
discovery/syncer.go
discovery/syncer_test.go

This commit reduces the number of channels a syncer will request from
the remote node in a single QueryShortChanIDs message. The current size
is derived from the chunkSize, which is meant to signal the maximum
number of short chan ids that can fit in a single ReplyChannelRange
message. For EncodingSortedPlain, this number is 8000, and we use the
same number to dictate the size of the batch from the remote peer.
We modify this by introducing a separately configurable batchSize, so
that both can be tuned independently. The value is chosen to reduce the
amount of buffering the remote party will perform, only requiring them
queue 500 responses, as opposed to 8000. In turn, this reduces larges
spikes in allocation on the remote node at the expense of a few extra
round trips for the control …

discovery: make batch size distinct from chunk size, reduce to 500

---

chainregistry.go
go.mod
go.sum

In this commit, we fix an oversight that overrode the default ban
duration for neutrino to 5s from the default 24 hrs. We correct this by
raising the ban duration to 48hrs. In the future in order to ignore
these peers persistently, we'll need to start to persist our ban list.
However that's a change for another time.

lnd: increase neutrino ban duration to 48hrs from 5s

---

channeldb/graph.go
channeldb/graph_test.go

This commit modifies FetchChanInfos to skip any channels that are not in
the graph at the time of the call. Currently the entire call will fail
if the edge is not found, which stalls a gossip sync in the following
scenario:
1. Remote peer queries for a channel range
2. We return the set of channel ids in that range
3. A channel from that set is removed from the graph, e.g. via close.
4. Remote peer queries for removed edge, causing the query to fail.
To remedy this, we will now skip any edges that are not known in the
database at the time of the query. This prevents the syncer state
machines from halting, which otherwise could only be resolved by
disconnecting and reconnecting.

channeldb/graph: skip unknown edges in FetchChanInfos
