lightningnetwork/lnd

- discovery/gossiper.go
- discovery/gossiper_test.go
- discovery/utils.go
In this PR, we add a new test case to exercise a recent bug fix to
ensure that we no longer broadcast private channel policy changes. Along
the way, a few helper functions were added to slim down the test to the
core logic compared to some of the existing tests in this package. In
the future, these new helper functions should be utilized more widely for
tests in this package in order to cut down on some of the duplicated
logic.
Fixes #2904. 
Fixes #2907.
> discovery: don't send private chan updates to wider network

- chanrestore.go
- htlcswitch/link.go
- server.go
In this PR, we fix a few issues that would cause the itests for the new SCB system to fail randomly based on timing:
1. Ensure we send the chan sync message in a synchronous manner to the remote peer. Otherwise, if we fail early, then we'll exit w/o ever sending the message to the peer. 
2. Don't exit during the restoration process if we're already connected to the remote peer.
> multi: peer related SCB fixes 

- htlcswitch/link.go
- htlcswitch/link_test.go
This PR is a temporary fix for hodl invoices not being settled correctly.
> htlcswitch: ensure commit tx gets updated after settle hodl invoice

- docker/btcd/Dockerfile
- docker/lnd/Dockerfile
- docker/ltcd/Dockerfile
- docs/INSTALL.md
This is a follow-up PR to #2830, which already updated the Go version in the contribution checklist.
Pinging @cfromknecht, who mentioned in [this PR comment](https://github.com/lightningnetwork/lnd/pull/2830#pullrequestreview-223480557) that it would be nice to also have the installation docs updated before the final 0.6 release.
A few things to note here:
1. I'm not sure about the macOS installation. On https://formulae.brew.sh/formula/go it's mentioned that the `go` package is "also known as `go@1.12`", but while https://formulae.brew.sh/formula/go@1.11 is a valid URL, https://formulae.brew.sh/formula/go@1.12 is not. So maybe someone with a Mac can test that `brew install go@1.12` works at all?
2. Similar to a Mac, I don't have a FreeBSD installation, so I can't test that either. I …
> Update Go version from 1.11 to 1.12

- cmd/lncli/commands.go
🙃
logging level
per default)
already exist
> lncli: fix exportChanBackup description typo

- htlcswitch/link.go
In this commit, we fix a bug that would cause a node with a hodl HTLC to
cancel back the HTLC upon restart if the invoice has been settled, but
the HTLC is still present on the commitment transaction. A fix for the
HTLC still being present (not triggering a new commitment) has been
fixed recently. However, for older nodes with a lingering HTLC, on
restart it would be failed back.
In this commit, we make the check stricter by only performing these
checks for HTLCs that are in the open state. This ensures that we'll
only check this constraints the first time around, before the HTLC has
been transitioned to the accepted state.
> htlcswitch: only perform CLTV checks for HTLCs with open invoices

- discovery/gossiper.go
If both policies don't exist, then this would result in a panic. Since they don't exist, we can assume the policy we're currently evaluating is fresh.
> discovery: check nil policy within isMsgStale

- routing/notifications.go
If the router is not yet started, return an error to avoid a deadlock
waiting for it to handle the subscription request.
> routing/notifications: check router started on SubscribeTopology

- routing/pathfind_test.go
- routing/router.go
This commit removes the QueryRoutes route cache. It is causing wrong
routes to be returned because not all of the request parameters are
stored.
The cache allowed high frequency QueryRoutes calls to the same
destination and with the same amount to be returned fast. This behaviour
can also be achieved by caching the request on the client side. In case
a route is invalidated because of for example a channel update,
the subsequent SendToRoute call will fail. This is a trigger to call
QueryRoutes again for a fresh route.
> routing: remove route cache

- cmd/lncli/commands.go
Removes the unused `time_limit` flag from the `closechannel` command that appeared to be leftover from a [previous refactor](https://github.com/lightningnetwork/lnd/pull/120#discussion_r100228100).
Resolves this confusion from Slack: https://lightningcommunity.slack.com/archives/C6BKD3RKR/p1555259641159800
> cmd/lncli: remove unused time_limit flag

- nat/pmp.go
- nat/upnp.go
- server.go
I noticed that the `nat=true` feature works really well to detect when the external IP address of a NAT device has changed (in my case using UPnP). But this requires that `lnd` also takes over the creation of the port forwarding (e.g. `9735`). In my case after every IP change the port forwardings were gone. I assume my NAT device removes them when the line is disconnected and re-established. 
In `lnd` I found no code that would re-create the port forwardings in this case. Port forwardings are only setup in `newServer` at server start (`configurePortForwarding` in line 405).
This PR make sure that the forwardings are re-created after a change in the external IP is detected.
> Re-create forwardings after externalIP change

- chainparams.go
- config.go
- lnd.go
This PR adds the configuration needed to run LND with Litecoin on simnet. The change is minimal and has no impact for users that don't enable this mode. When using this configuration, the user is being warned that this mode is not officially supported.
Fixes #1830.
> config: Experimental support for Litecoin/simnet

- sample-lnd.conf
This appears to be a copy&paste mistake?! For `lnd` it should be `lncli debuglevel --show`, right?
```
$ lncli debuglevel --show
{
"sub_systems": "ARPC ATPL BRAR BTCN CHBU CHDB CHNF CMGR CNCT CRTR DISC FNDG HSWC INVC IRPC LNWL LTND NANN NTFN NTFR PEER RPCS RRPC SGNR SPHX SRVR SWPR UTXN WLKT WTWR"
}
```
> Update sample-lnd.conf - use lncli to show debug levels

- config.go
- lncfg/address.go
TCP addresses resolved through `net.ResolveTCPAddr` give a default network of "tcp", so we map back the correct network for the given address. This ensures that we can listen on the correct interface (IPv4 vs IPv6).
Fixes https://github.com/lightningnetwork/lnd/issues/2776.
Related: https://github.com/golang/go/issues/17615#issuecomment-256445349
> lncfg: parse network for TCP addresses to listen on correct interface

- lnd_test.go
- rpcserver.go
fixes #2920
This an early PR, this updates SendCoins in `rpcserver.go` to prevent an onchain transaction to a users own Pubkey. 
Updated to check all use of pubkeys in SendCoins.
> rpcserver: Prevent SendCoins to Pubkey

- go.mod
- go.sum
This is a Linux-specific fix to an issue, where running `lnd` with `nat=true` causes instant crash on some distributions of linux.
Currently used version of this library depends on `ip` and `route` being located in `/usr/bin/`.  Not surprisingly, many distributions (ex. Alpine) don't have them there. `v1.0.5` fixes it by relying on `$PATH` instead: https://github.com/jackpal/gateway/commit/5795ac81146e01d3fab7bcf21c043c3d6a32b006. 
already exist
> Update jackpal/gateway to v1.0.5

- lntest/harness.go
This would cause the method to return before the peer list check was
performed.
> [trivial] lntest: don't return from ensureConnected on non-error

- Makefile
- breacharbiter.go
- breacharbiter_test.go
- chainparams.go
- chainregistry.go
- chancloser.go
- channel_notifier.go
- chanrestore.go
- cmd/lnd/main.go
- config.go
- doc.go
- fundingmanager.go
- fundingmanager_test.go
- lnd.go
- lnd_test.go
- log.go
- mock.go
- nursery_store.go
- nursery_store_test.go
- peer.go
- peer_test.go
- pilot.go
- rpcserver.go
- server.go
- server_test.go
- subrpcserver_config.go
- test_utils.go
- utxonursery.go
- utxonursery_test.go
- witness_beacon.go
This PR renames the `main` package to `lnd`, and moves the `lnd` entry point into `cmd/lnd`.
This intends to make `lnd` suitable for use as a library, for instance within in other apps. This is also a prerequisite for using `lnd` with `gomobile`.
> Move daemon from main to lnd package

- keychain/derivation.go
- watchtower/wtclient/client.go
- watchtower/wtclient/client_test.go
- watchtower/wtclient/derivation.go
- watchtower/wtclient/interface.go
- watchtower/wtclient/session_negotiator.go
- watchtower/wtdb/client_session.go
- watchtower/wtdb/mock.go
- watchtower/wtdb/tower.go
- watchtower/wtmock/client_db.go
- watchtower/wtmock/keyring.go
- watchtower/wtserver/create_session.go
- watchtower/wtserver/delete_session.go
- watchtower/wtserver/server.go
- watchtower/wtserver/server_test.go
- watchtower/wtserver/state_update.go
- watchtower/wtwire/create_session_reply.go
- watchtower/wtwire/delete_session_reply.go
- watchtower/wtwire/error_code.go
In this PR, we address some of the last major architectural changes planned for the `wtclient` before it is ready to be integrated with its database and into the lnd daemon.  The primary component is encompassed by deriving the session private keys from the user's seed, which are used to encrypt brontide traffic with the tower and authenticate requests. To do so, we add a new key family:
```golang
// KeyFamilyTowerSession is the family of keys that will be used to
// derive session keys when negotiation sessions with watchtowers. The
// session keys are limited to the lifetime of the session and are used
// to increase privacy in the watchtower protocol.
KeyFamilyTowerSession KeyFamily = 8
```
The initial version of the wtclient #2618 generated these randomly and stored them in plaintext …
> wtclient: session private key derivation

- pool/worker.go
This commit increases the default worker timeout currently backing the
read and write pools. This allows the read and write pools to sustain
regular bursty traffic such as ping/pong without releasing their buffers
back to the underlying gc queue. In the future, jitter can be added to
our ping and/or gossip messages to reduce the concurrent usage of read
and write pools, which will make this change even more effective.
> pool/worker: increase worker timeout to 90s

- brontide/conn.go
- brontide/noise.go
- brontide/noise_test.go
- lncfg/workers.go
- peer.go
This PR modifies the behavior of the peer writes messages to the wire, such that we are able to gracefully handle timeout errors and resume partially sent messages. As of #2819, if a message is partially written to the wire due to a timeout error, we will try to write the full message again. In turn, this will produce an authentication error on the remote side (after it is able to read the number of bytes specified in the header) since the middle of the latter ciphertext will not pass as the MAC check.
We resolve this by splitting the `Write` call into two subroutines, `WriteMessage`  and `Flush`. `WriteMessage` encrypts the plaintext and buffers the ciphertext on the underlying connection. A subsequent call to `Flush` will then attempt to write the bytes out on the wire. If a timeout …
> peer: resume partial writes due to timeouts

- discovery/chan_series.go
- discovery/gossiper.go
- discovery/gossiper_test.go
- discovery/sync_manager.go
- lnrpc/routerrpc/router_backend.go
- lnrpc/routerrpc/router_backend_test.go
- lnrpc/routerrpc/router_server.go
- routing/missioncontrol.go
- routing/notifications_test.go
- routing/pathfind.go
- routing/pathfind_test.go
- routing/payment_session.go
- routing/payment_session_test.go
- routing/route/route.go
- routing/router.go
- routing/router_test.go
- routing/validation_barrier.go
- rpcserver.go
- server.go
Moves types `Route`, `Hop` and `Vertex` to a new package `routing/route`, to decouple the type from the `routing` package.
A pre-requisite for reliable payments, where we want to have access to the `Route` struct from `channeldb` in order to serialize and store it.
> multi: move Route to sub-pkg routing/route

- chainparams.go
- chainregistry.go
- config.go
- lnd.go
This PR enables regtest mode for ltcd/litecoind in lnd.
Related PRs:
~https://github.com/ltcsuite/ltcd/pull/10 was recently merged into LTCD to prevent failures of `invalid genesis block`.~
LTCD archived the issue here: https://github.com/ltcsuite-archive/ltcd/pull/10
Changes include:
1. Updating LTCD version in lnd
2. Adding regtest configuration to `config.go`
3. renaming `regtestNetParams` to `bitcoinRegTestNetParams`
> add litecoin regtest to lnd

- discovery/sync_manager.go
- discovery/syncer.go
- discovery/syncer_test.go
- lnpeer/errors.go
- peer.go
This PR modifies the `discovery.GossipSyncer` to send all replies and and gossip filter backlogs synchronously. This serves to throttle the rate at which the serving node writes messages to the wire, which has been observed to result to a disconnect if the remote node's discovery stream is filled up. Testing on my node has shown overall more stable connections, as this helps in more closely aligning our sending rate to the throughput of the other node. 
In the process, we make a pair of syncer's state machines totally isolated, which facilitates a nice removal of duplicate test code in `discovery/syncer_test.go` since the requesting side can now be tested independently of the remote peer's state machine.
See commit messages for more details.
> discovery: make gossip replies synchronous

- contractcourt/chain_watcher.go
- contractcourt/chain_watcher_test.go
In this commit, we modify the way we detect local force closes. Before
this commit, we would directly check the broadcast commitment's txid
against what we know to be our best local commitment. In the case of DLP
recovery from an SCB, it's possible that the user force closed, _then_
attempted to recover their channels. As a result, we need to check the
outputs directly in order to also handle this rare, but
possible recovery scenario.
The new detection method uses the outputs to detect if it's a local
commitment or not. Based on the state number, we'll re-derive the
expected scripts, and check to see if they're on the commitment. If not,
then we know it's a remote force close. A new test has been added to
exercise this new behavior, ensuring we catch local closes where we have
and don't …
> contractcourt: detect local force closes based on commitment outputs

- tor/controller.go
- tor/controller_test.go
The current method would not allow version strings like 0.4.0.5 since it would check every number of the version string individually.
> tor: use string comparison to check min supported version

- go.mod
- go.sum
- htlcswitch/failure.go
- htlcswitch/link.go
- htlcswitch/mock.go
- htlcswitch/packet.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- htlcswitch/test_utils.go
- lnd_test.go
- lnwire/onion_error.go
- routing/pathfind_test.go
- routing/route/route.go
- routing/router.go
In this commit, as a prep for the latest iteration of the EOB design within the spec, we update the `lightning-onion` repo to the latest version. The second commit in this PR updates any relevant callers to use the new API. This commit was broken off of #2455. The ultimate spontaneous payment implementation will still proceed within #2455 once the re-worked code to encode/decode EOBs from the onion is finished.
> router+build: update to the latest version of lightning-onion

- config.go
This commit fixes a bug where it was impossible to run lnd in litecoin's simnet mode because of code duplication. As a result `numNets > 1` conditional was always true when running lnd with `cfg.Litecoin.SimNet` flag.
> config: fix litecoin simnet mode

- peer.go
This commit modifies sendMessage to break on the server's quit channel,
which allows synchronous callers of SendMessage or SendLazyMessage to
receive an error during server shutdown which can be independent of a
particular peer's shutdown.
As of https://github.com/lightningnetwork/lnd/pull/2916, all replies
made by gossip syncers were modified to be synchronous. In certain
cases, This would prevent the syncers from shutting down promptly, as
they would try to offload a batch a of messages that could not be
aborted. Now, an error will be propagated back to the caller, allowing
them to detect the error condition, and reevaluate their own quit
signals, releasing any waitgrouped goroutines and permitting a quick
shutdown.
Fixes #3048
> peer: break sendMessage on server quit

- routing/router.go
This commit reevaluates the router's quit channel between each block
during the initial call to syncGraphWithChain, which, in the worst case,
may have to scan several thousand blocks on startup if the node has not
been active for some time. Without this, attempting to stop the daemon
will not exit until the rescan has completed, which for certain backends
could be several hours.
> routing/router: break rescans on router quit

- autopilot/agent_constraints.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/txnotifier.go
- chainntnfs/txnotifier_test.go
- cmd/lncli/commands.go
- contractcourt/chain_watcher_test.go
- discovery/syncer.go
- lnd_test.go
- lnrpc/autopilotrpc/driver.go
- peer.go
- pool/write.go
- routing/payment_session.go
- rpcserver.go
- tor/controller.go
- utxonursery.go
- watchtower/wtclient/client.go
- watchtower/wtclient/errors.go
- watchtower/wtclient/session_negotiator.go
- watchtower/wtdb/client_session.go
- watchtower/wtdb/session_state_update.go
- watchtower/wtpolicy/policy.go
- watchtower/wtwire/error.go
Fixes spelling errors found by https://goreportcard.com/report/github.com/lightningnetwork/lnd#misspell
> multi: fix spelling mistakes

- channeldb/graph.go
- channeldb/graph_test.go
Nilling the key would cause signature verification to crash if the
returned key was used.
A test to exercise the behavior is added.
Split off from #3063
> [reliable payments] channeldb/graph: don't nil curve of returned PubKey

- channeldb/payments.go
- channeldb/payments_test.go
We will store the routes used during payment attempts, so we need
serialization code.
Split off from #2761
> [Reliable payments] add routing.Route (de)serialization + test

- chainntnfs/neutrinonotify/neutrino.go
- contractcourt/channel_arbitrator_test.go
- lnwallet/btcwallet/blockchain.go
- lnwallet/btcwallet/btcwallet.go
- lnwallet/interface.go
- lnwallet/wallet.go
- mock.go
- routing/notifications_test.go
- routing/router.go
- sweep/test_utils.go
This PR makes sure long running calls to `GetUTXO` gets cancelled in case we are shutting down.
This is done by adding a `quit` channel to `BtcWallet`, and cancelling the call in case of shutdown.
Fixes #2300. 
Replaces https://github.com/lightningnetwork/lnd/pull/1781
> Cancel long-running Neutrino GetUTXO calls on quit

- htlcswitch/link_test.go
- htlcswitch/payment_result.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- htlcswitch/test_utils.go
- routing/mock_test.go
- routing/router.go
- routing/router_test.go
- server.go
This PR consists of two important pieces of #2761: 
We define `PaymentResult` and the  method `GetPaymentResult`
exposed by the `switch`.
This lets us distinguish an critical error from a actual payment result
(success or failure). This is important since we know that we can only
attempt another payment when a final result from the previous payment
attempt is received.
In order to achieve this we let the `router` handling generating `paymentID`s,
since they are used to later query the `switch` for the final result.
In this commit we move handing the deobfuscator from the router to the
switch from when the payment is initiated, to when the result is
queried.
We do this because only the router can recreate the deobfuscator after a
restart, and we are preparing for being able to handle …
> [reliable payments] Move payment error deobfuscation to router

- Dockerfile
- docker/lnd/Dockerfile
Now that the official releases are built with subservers, can/should we build docker images with subservers by default too?
This one-line change is all I needed to do to build LND with subservers so loop would work with the docker image.
(Checklist not applicable - it's a one-line change to a docker file rather than a go file.)
> Build LND subservers when building docker image

- lnrpc/invoicesrpc/invoices.pb.go
- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
This fixes typos in the comments of the rpc proto definition.
These are what I came across when reading through the API documentation.
> lnrpc: fix typos

- fundingmanager.go
- fundingmanager_test.go
The previous value was set to two days, which may not be enough to
handle large fee spikes where users still which to submit channels with
a low fee and don't mind lowering their time preference. Since the
timeout is only applied to channels that we don't initiate, there's real
downside since it's not our funds that are locked up.
> fundingmanager: bump max non-initiator funding timeout to 2 weeks

- config.go
- lnd.go
Allows setting multiple `--tlsextraip` and `--tlsextradomain` to be used when generating tls certs.
fixes #1492
> config: allow adding multiple tls ips and domains

- discovery/sync_manager.go
- discovery/sync_manager_test.go
To handle the case where we have been without peers, and get a new
connection, we reset the historical scan booleans when the first active
syncer is connected to trigger another historical sync.
This would cause integration tests to be flaky (especially with Neutrino), since we would risk not getting graph updates after having being disconnected.
> discovery/sync_manager: restart historical sync on first connected peer

- channeldb/codec.go
- watchtower/wtclient/backup_task.go
- watchtower/wtclient/backup_task_internal_test.go
- watchtower/wtclient/client.go
- watchtower/wtclient/client_test.go
- watchtower/wtclient/interface.go
- watchtower/wtclient/session_negotiator.go
- watchtower/wtclient/session_queue.go
- watchtower/wtdb/client_chan_summary.go
- watchtower/wtdb/client_db.go
- watchtower/wtdb/client_db_test.go
- watchtower/wtdb/client_session.go
- watchtower/wtdb/codec_test.go
- watchtower/wtdb/db_common.go
- watchtower/wtdb/tower.go
- watchtower/wtdb/tower_db.go
- watchtower/wtdb/version.go
- watchtower/wtmock/client_db.go
This PR adds a `wtdb.ClientDB`, which is persistent implementation of the `wtclient.DB` interface. With this, we now have full persistence of both the client and server-side portions. This allows to begin fully testing the of the client and server in our integration tests, and also do more extensive testing in the wild now that we can be certain we won't be inflating our on-chain addresses.
> watchtower/wtdb: add bbolt-backed ClientDB

- Makefile
- make/testing_flags.mk
Previous to this commit, running `make unit-cover pkg=xx`
would ignore the selected package and run unit tests and
coverage for all packages.
After this commit, the package selected with pkg= is the
only one that is tested and coverage output generated for.
Note: I kept the lnrpc filter for this case too (not 100% sure I understand it), also I think it's a bit suboptimal using `grep` here, so if someone prefers to make a better version than this I'm all for it! :)
> Allow unit-cover target for make to filter by package

- breacharbiter_test.go
- contractcourt/briefcase.go
- contractcourt/briefcase_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_watcher.go
- contractcourt/chain_watcher_test.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- lnwallet/test_utils.go
In this commit, we address a TOOD, and end up fixing a lingering bug related to commitments on chain. Before this commit, it was possible that `lnd` would unnecessarily cause an incoming link to force close on chain if the outgoing link was in an indeterminate state. We fix this issue by always checking for HTLCs that we need to time out on the incoming link based on all valid commits. With this fix, we'll no longer go to chain unnecessarily which wastes chain fees and may also increase off-chain HTLC fail delays. 
Fixes #2045.
> multi: always fail pending htlcs on commitment confirmation

- contractcourt/commit_sweep_resolver.go
- lnwallet/fee_estimator.go
- server.go
- sweep/fee_estimator_mock_test.go
- sweep/sweeper.go
- sweep/sweeper_test.go
- sweep/walletsweep.go
- utxonursery.go
- utxonursery_test.go
In this PR, we introduce support for arbitrary client fee preferences when accepting input sweep requests. This is possible with the addition of fee rate buckets. Fee rate buckets are buckets that contain inputs with similar fee rates within a specific range, e.g., 1-10 sat/vbyte, 11-20 sat/vbyte, etc. Having these buckets allows us to batch and sweep inputs from different clients with similar fee rates within a single transaction, allowing us to save on chain fees. Implementing these fee rate buckets also lays down the groundwork required for being able to bump the fee rates for particular inputs.
We also get rid of the UtxoSweeper's default fee preference. Any clients using it to sweep inputs specify the same default fee preference to not change their behavior. Each of these can be …
> sweep: add support for multiple fee preferences to UtxoSweeper

- .travis.yml
- Makefile
- lnd_test.go
- lntest/btcd.go
- lntest/harness.go
- lntest/neutrino.go
- lntest/node.go
- make/testing_flags.mk
- rpcserver.go
This PR enables integration tests for Neutrino. It us currently blocked by a number of other PRs, but putting it put to make Travis comfortable with this new node type.
> Neutrino integration tests

- routing/route/route.go
- routing/route/route_test.go
Also adds a simple unit test for the TotalFees method.
This fixes a crash that could happen if the `rpcserver` tried to list a payment that didn't have any payment attempt recorded: https://github.com/lightningnetwork/lnd/blob/28fdf9712d88c104ca039dc56d5242d3822c00d0/rpcserver.go#L4150
> route: return 0 fee from TotalFees for empty route.

- chanbackup/backupfile.go
It has been reported that on Windows, the current file swap process
doesn't properly work since we still have the file open when we try to
rename it. In order to fix this, we'll now close the file _before_ we
rename it.
> chanbackup: close temp SCB file before rename

- discovery/gossiper.go
- discovery/gossiper_test.go
- server.go
In this PR we split a list of announcements in the gossiper into sub batches. These are broadcasted at regular intervals instead of all at once. 
See #2979  
logging level
per default)
already exist
> Broadcast gossip announcements in sub batches

- .gitignore
- chainregistry.go
- config.go
- fundingmanager.go
- fundingmanager_test.go
- lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
- lntest/itest/lnd_test.go
- lntest/node.go
- make/testing_flags.mk
- rpcserver.go
- server.go
- subrpcserver_config.go
This PR moves the itests from the root into their own package. We started giving every itest its own file and a separate itest package is good not to clutter the root with those individual test files.
> lntest: move itest into package

- cmd/lncli/commands.go
Added the command line flags `conf_target` and `sat_per_byte` to the command `closeallchannels`.
[Was requested by joaoalmeida on Slack](https://lightningcommunity.slack.com/archives/C9RDCG8KT/p1522529600000079).
> added conf_target and sat_per_byte to closeallchannels

- lnwallet/channel.go
- lnwallet/commit_sort.go
- lnwallet/commit_sort_test.go
Updates commitment transaction sorting to be consistent with https://github.com/lightningnetwork/lightning-rfc/pull/491
Fixes #2234
> lnwallet: add commitment transaction sorting with CLTV tie breaker

- go.mod
- go.sum
In this commit, we update to the latest version of btcd which includes a
fix for notifying based on pkScripts for spends/confirmations within the
ChainNotifier.
> build: update to latest btcd version

- autopilot/agent.go
- autopilot/manager.go
- breacharbiter.go
- chanbackup/pubsub.go
- fundingmanager.go
The change has been implemented only for `fundingManager` as its meant mostly to gather feedback. I noticed many modules using manual CAS operations to guarantee that the start/stop subroutines run at most once.
One characteristic of the current implementation is that subsequent callers will return immediately even if the first call has not completed yet. This is contrary to what one of the comments implies when it says: "This method will block until all goroutines have exited." causing a potential race condition for subsequent callers.
If there is interest in the change, I can replace other manual CAS operations with `sync.Once` blocks.
> multi: replace manual CAS with sync.Once in component start/stop

- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/payment_result.go
- htlcswitch/payment_result_test.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- htlcswitch/test_utils.go
- lntest/itest/lnd_test.go
- routing/mock_test.go
- routing/payment_lifecycle.go
- routing/router.go
This PR is a follow-up from #2761. It adds a persistent `pendingPaymentStore` to the `Switch`, needed to store payment results when the `router` is not available to handle them.
After a restart, there is no connection between an HTLC in flight on the network and the `router` payment flow that initially sent the HTLC. The `router` will eventually call `GetPaymentResult` to retrieve the result of the HTLC, but we have no guarantees this will be done before the result is received. This can lead to the result getting dropped, which is not ideal.
We introduce a `pendingPayementStore` which has two primary functions:
1. It stores `PaymentResult`s when they are received, regardless of whether there are any subscribers (the `ChannelRouter`) to the corresponding HTLC. This ensures that the …
> [reliable payments] persist htlcswitch pending payments

- routing/router.go
This is now redundant since we have one at the db-level via #2847
> routing/router: remove router-level reject cache

- routing/payment_lifecycle.go
- routing/router.go
- rpcserver.go
This commit moves the default timeout out of router and thereby fixes a bug that caused SendToRoute to not return the actual error, but a timeout result instead. SendToRoute only tries a single route, so a timeout should never happen.
> routing+lnrpc: move default payment timeout out of router

- .gitignore
- make/testing_flags.mk
`output.log` file paths were moved in #3087
> [trivial] Update output log file location to itest package

- lnwallet/btcwallet/btcwallet.go
In this commit, we patch a small bug in the newly added raw tx hex field
for ListTransactions. We now ensure that we also set the raw tx hex
field for unconfirmed transactions.
> lnwallet/btcwallet: also include raw tx hex for unconf txns

- routing/router.go
- routing/stats.go
This PR puts all of the CRTR logs during IGD on trace, and logs aggregate stats every 30s if there is anything new discovered
> routing/router: log aggregate graph processing stats

- lnwallet/btcwallet/btcwallet.go
Initialize addressType to UnknownAddressType instead of the default (null value) which is lnwallet.WitnessPubKey.
Without this change, if both IsPayToWitnessPubKeyHash and IsPayToScriptHash returns false, the address is considered to be WitnessPubKey which is obviously false.
> Initialize addressType to UnknownAddressType

- go.mod
- go.sum
Depends on https://github.com/btcsuite/btcwallet/pull/618.
Since we'll no longer fetch blocks headers for the _whole_ chain, but only for the latest 10,000 blocks, 
this somewhat addresses #1528 and #1545.
Fixes #1854.
Fixes #3166.
> build: update btcwallet dependency to include initial sync improvements

- channeldb/channel.go
- channeldb/graph.go
- channeldb/migrations.go
- contractcourt/briefcase.go
bbolt documentation states that this is not safe and leads to undefined
behavior.
`channeldb/migrations` and `contractcourt/briefcase` are the only places in the codebase where the `ForEach` modification was done. `
`channeldb` had a few cases of cursor modification.
> Avoid modifying bucket during ForEach loop, and Cursor traversal

- autopilot/interface.go
- config.go
- pilot.go
This PR adds a new configuration option `conftarget` for channels opened by autopilot.
> [autopilot] make confirmation target configurable

- rpcserver.go
> rpc: update updatechanpolicy to allow zero fees

- lnrpc/walletrpc/walletkit_server.go
In this commit, we modify the parsing of user provided outpoints to
ensure that we catch a nil (empty) output early. Otherwise, passing a
set of incorrect arguments would cause `lnd` to crash.
> lnrpc/walletrpc: reject nil outpoints as args

- routing/router.go
- zpay32/hophint.go
Since nilling the pubkey curve will lead to a nil-pointer exception if
the key is later used for signature verification, we make sure to make a
copy before nilling and spewing.
Fixes #3185
> routing+zpay32: copy pubkeys before nilling Curve and spewing

- go.mod
- go.sum
- lnwallet/btcwallet/btcwallet.go
- lnwallet/interface_test.go
In this commit we fix a hidden bug in the transaction creating logic
that was only manifested recently due to higher fees on Bitcoin's
mainnet. Before this commit, we would use the target fee rate to
determine if an output was dust or not. However, this is incorrect, as
instead the relay fee should be used as this matches the policy checks
widely deployed in Bitcoin full node today.
To fix this issue we now properly use the relay fee when computing dust.
This fixes the issue for the `EstimateFee` call, but the `SendOutputs`
call also has a similar issue. However, this must be fixed within
`btcwallet` itself, so it has been left out of this commit
Fixes #3217.
> lnwallet/btcwallet: use relay fee not tx fee rate for dust check

- routing/router.go
- watchtower/wtclient/client.go
Reduces the stat tickers in the wtclient and router from 30s to one minute to reduce spammy-ness.
> routing+watchtower/wtclient: prints stats once per minute

- watchtower/wtclient/client.go
- watchtower/wtclient/session_queue.go
- watchtower/wtdb/client_session.go
Tidies up some log messages that I've noticed were incorrect. Almost all of the BackupIDs were being improperly formatted because the of the pointer receiver on `String()`, when they are passed in by value to log functions.
> watchtower/multi: fix logging in wtclient

- watchtower/wtclient/candidate_iterator.go
- watchtower/wtclient/client.go
Filters out sessions that are not with the currently active tower from becoming candidates, which ensures that newly revoked states go to the chosen tower.
> watchtower/wtclient: filter non-target towers from candidates

- Dockerfile
- docker/lnd/Dockerfile
Current docker builds don't have the routerrpc subsystem included when building. I've just added the " routerrpc" subsystem to the two LND Dockerfiles.
logging level
per default)
already exist
> Docker builds don't work with Loop

- rpcserver.go
> lnd: reject custom fee when force closing channel

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/interface.go
- chainntnfs/interface_test.go
- chainntnfs/txnotifier.go
This PR refactors the dispatch logic for historical confirmation notifications on backends with txindex enabled. Currently these dispatches are done on txid which should be sufficient, but we modify this to also assert that the transaction contains the correct scriptpubkey in the output. This better aligns the dispatch logic with all other dispatch paths, which already dispatch on scripts in order to support neutrino. Under some nuanced circumstances, this prevents false positive dispatches when interacting with `loopd`.
> chainntnfs: stricter historical confirmation matching

- chainregistry.go
- discovery/bootstrapper.go
- server.go
- watchtower/wtclient/session_queue.go
In this commit we add a second DNS seed to make lnd's process of bootstrapping an initial set of peers more robust. Along the way, we modify the primary DNS `SampleNodeAddrs` method to no longer retry, and also simply try the next seed if it fails to connect to one. Additionally, it is now no longer required that a DNS seed uses our "secondary fall back" mechanism. 
Reviewers can test that this PR will fall back to the newly added seed if the primary is down by modifying the domain in `chainregistry.go`, and ensuring that a new `lnd` instance is still able to find peers.
> multi: add secondary DNS seed for bootstrap, add exponential back off to initial bootstrap

- chanrestore.go
> chanrestore: return error instead of nil if failed derivation

- docs/watchtower.md
- sample-lnd.conf
- watchtower/wtclient/client_test.go
- watchtower/wtdb/client_session.go
- watchtower/wtpolicy/policy.go
This PR adds documentation for setting up watchtowers and configuring watchtower clients, and also resolves some logging issues related to double-hex encoded channel id's. It also bumps the default sweep rate from 3 sat/byte to 10, which provides a more comfortable default; the value can always be modified via `wtclient.sweep-fee-rate`.
> docs: watchtower guide + bump default sweep fee rate

- .github/CODEOWNERS
In this commit, we create the initial CODEOWNERS file for `lnd`. This
file is a new-ish feature of Github that allows the maintains of a
project to define the individuals who are deemed to be experts of a
particular section of the codebase. Automated review assignment systems
can then use this file to generate required reviewers for a section of
the project. The CODEOWNERS file isn't meant to be a strict guideline,
but instead can be used to ease the burden of finding reviewers for a
particular section of the codebase.
It's also possible to enforce that the CODEOWNERS for a particular
file/package sign-off on relevant changes, thereby blocking review
unless they're involved. However, for now we'll simply use it to guide
the review assignment project, leaving creating blocking review …
> CODEOWNERS: create initial code owners config

- .github/CODEOWNERS
pointed out by @Crypt-iQ https://github.com/lightningnetwork/lnd/pull/3269#discussion_r301823625
> CODEOWNERS: fix aezeed typo

- cmd/lncli/commands.go
- rpcserver.go
Closes simple version of #3240.
logging level
per default)
already exist
> rpcserver: ForwardingHistory end_time defaults to time.Now()

- lnwallet/btcwallet/btcwallet.go
- lnwallet/interface_test.go
- rpcserver.go
Right now, the DestAddresses field of the transactions returned in the stream obtained by the grpc function SubscribeTransactions is nil.
This PR solves that by:
- Adding the addresses in the wallet for unconfirmed transactions
- Passing the addresses to the Transaction object in the rpcserver.
> Add addresses to transactions returned by SubscribeTransactions

- rpcserver.go
This PR fixes a bug that prevents restart LND, after it has stopped, at the same process.
The problem resides in the fact that an array of permissions is initialized as a package variable and when creating the RPCServer, all subserver permissions are appended to this variable, while checking for duplicates.
On subsequent restart this array is left with the data from the previous run and being populated again with the same permissions causing a duplicate error.
The solution I propose is simple, just to extract out the initial permissions to
a separate function and call it from the context is is needed.
> rpc: fix calculating RPC permissions.

- lnrpc/walletrpc/walletkit.pb.go
- lnrpc/walletrpc/walletkit.proto
Keep docs consistent and also needed for proper mobile RPC doc parsing.
> [trivial] lnrpc: make BumpFee doc start with RPC name

- go.mod
- go.sum
This allows us to not depend on external hosts for third-party dependencies other than the standard hosts: github.com, google.golang.org, and gopkg.in.
> build: use github mirror of bsaes dependency

- go.mod
- go.sum
* We address an issue where we would unnecessarily time out bitcoind ZMQ connections if there are no messages to be read. This would cause connections to be torn down, which would then trigger the reconnection logic and prevent us from detecting this issue.
* A new sanity check within the wallet is done to prevent adding unconfirmed transactions that the wallet has already recognized as confirmed.
> build: update dependencies to prevent unnecessary bitcoind ZMQ timeouts

- lnrpc/invoicesrpc/addinvoice.go
right now it is possible to add 21 route hints which results in an error.
closes #3305
> invoicesrpc: fix route hint off-by-one-error

- channeldb/graph.go
- routing/heap.go
- routing/heap_test.go
- routing/pathfind.go
These commits add a `visitedNodes` map that tracks if the Djikstra's algorithm in `findPath` has already visited this node before.  Previously, when evaluating the best node, we would look at all of the incoming edges and repeat the `processEdge` flow for already visited nodes.  The second commit enables the `TestNewRoutePathTooLong` test by fixing the excessive hops graph to correctly be parsed.
> routing: tracking visited nodes in findPath

- chainregistry.go
- lnd.go
A cleanup closure is not included when an error is returned, causing the defer to execute and triggering the following panic:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x105da38]
goroutine 1 [running]:
github.com/lightningnetwork/lnd.Main(0x2083e40, 0xc0004f6db0)
/home/user/lnd/lnd.go:208 +0x2bfa
main.main()
/home/user/lnd/cmd/lnd/main.go:14 +0x26
```
Fixes https://github.com/lightningnetwork/lnd/issues/3308.
> lnd: prevent panic on nil neutrino cleanup

- lnrpc/routerrpc/config.go
- lnrpc/routerrpc/config_active.go
- lnrpc/routerrpc/config_default.go
- routing/missioncontrol.go
- routing/missioncontrol_test.go
- routing/mock_test.go
- routing/nodepair.go
- routing/payment_lifecycle.go
- routing/payment_session.go
- routing/payment_session_source.go
- routing/payment_session_test.go
- routing/router.go
- routing/router_test.go
- server.go
This PR moves the last payment-specific mission control state into the global mission control instances.
Builds off of #3188 
The PR is a base for #3221 and #3164
> routing: globalize mc

- aezeed/cipherseed.go
- aezeed/cipherseed_test.go
- aezeed/errors.go
In this commit, we publicly export the `word` field as it makes it
easier to programmatically interact with the package when attempting to
re-derive proper `cipherseed` instances.
> aezeed: publicly export the `word` field  in `ErrUnknownMnenomicWord`

- autopilot/agent.go
- autopilot/agent_test.go
- autopilot/interface.go
- fundingmanager.go
- fundingmanager_test.go
- lnwallet/interface_test.go
- lnwallet/reservation.go
- lnwallet/wallet.go
- lnwallet/wallet_test.go
- mock.go
- pilot.go
- server.go
This is an alternative to #3017.
Since the funding manager and wallet can't know up front the how much it will cost us in fees to fund a channel, it will always cost us more than `chanSize` in total. This makes it hard to spend all the funds remaining in the wallet into a channel, since we won't have enough to cover the additional fee.
This PR attempts to fix this by letting one specify a "spend amount" instead of a "channel size" when opening a channel. This makes the wallet do coin selection that results in a decrease in balance equal to this spend amount, instead of spending `chanSize+fees`.
We make the autopilot use this new option, making it better at staying within its budget, and also able to open channels that utilizes the whole wallet balance.
Fixes #986
> [funding+autopilot] Make the funding manager and autopilot fee aware

- channeldb/graph.go
- channeldb/graph_test.go
- routing/pathfind_test.go
- routing/router.go
- routing/router_test.go
This PR replaces https://github.com/lightningnetwork/lnd/pull/2799.
Since there were some major changes regarding zombie channels, I preferred to create a new PR instead of rebasing. It seemed easier to implement and review this way.
The PR introduces a different, more optimized, approach to prune zombie channels.
"zombie channels" stands for channels that their last channel policy update time was earlier than "channel expiry", configured by default to a period of 14 days or, when AssumeChannelValid=false, those that have both ChannelEdgePolicy with their disable bit on.
From my understanding the second part (disabled channels) of the prune serves as a heuristic to prune on-chain closed channels on devices with low resources.
The current approach iterates all channels in the graph in …
> Optimize prune zombie channels

- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/switch.go
- lntest/itest/lnd_test.go
- server.go
- test_utils.go
This PR makes the outgoing link pipeline the settle to the
switch as soon as it receives it. Previously, it would wait for a
revocation before sending it, which caused increased latency on
payments as well as possibly never settling on the incoming link.
A duplicate settle is still sent to the switch, but it is handled
gracefully. A new AckEventTicker was added to the switch which
acknowledges any pending settle / fail entries in an outgoing
link's fwd pkgs in batch. This was needed in order to reduce the
number of db txn's which would have been incurred by acking whenever
we receive a duplicate settle without batching.
Fixes #3069
> htlcswitch: pipeline settles to switch

- keychain/derivation.go
According to [this](https://github.com/lightningnetwork/lnd/blob/master/keychain/derivation.go#L24) and [this](https://github.com/btcsuite/btcwallet/blob/master/waddrmgr/manager.go#L1348) the derivation path for "special" keys is not `201'` and the `keyFamily` is always hardened.
Fixed this because it confused me when trying to find out how keys are really derived.
> keychain: fix comment about derivation path

- cmd/lncli/commands.go
Require that users confirm their passphrase when providing their own seed with a passphrase.
Currently implemented as an infinite loop until passwords match, can be limited to a set number of retries if that's the UX wanted. 
Fixes #1507
> cmd: Add passphrase confirmation when creating wallet from existing seed

- lnd.go
Allow startup to continue without syncing to chain when in regtest mode, as is already the case for Bitcoin/Litecoin simnet. 
Fixes #3336.
> lnd: Add regtest exception for wait to sync on startup

- lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
- lntest/itest/lnd_test.go
- routing/payment_session.go
- routing/payment_session_test.go
Partially fixes #3055 and adds the block padding to only `sendpayment` this time.
> routing: add block padding to sendpayment

- config.go
This prevents spending unconfirmed funds by default. Users will have to explicitly set this to 0 in order to do so.
> config: default autopilot min confs to 1

- go.mod
- go.sum
In this commit, we update neutrino to a new version that has a fix for a
possible sync stall that can occur if a response that we believe has
timed out, later comes back from the source peer.
> build: update neutrino to version w/ stall fix

- queue/go.sum
- ticker/go.mod
Apparently my IDE runs `go mod tidy` on all subfolders that have a `go.mod` in them.
This is quite annoying since it always changes my git working tree to dirty.
So the easiest fix would be to commit the changes, which I hereby suggest.
I know, I should probably use a "real" IDE that doesn't do stuff like this but I really like IntelliJ...
> ticker+queue: run go mod tidy

- channeldb/db.go
- go.mod
- go.sum
- watchtower/wtdb/db_common.go
Fixes #3241.
These options could really be specified anywhere that bbolt is opened, so if that's of interest I can also do that.  But the only other large database I had on my machine was `wallet.db` which is the `btcwallet` repo.  Perhaps watchtowers might use a lot of space, or there could be some design parameters that change in the future where the other databases start using more space (macaroons.db etc).  Should I add these options to all the tests so they reflect the new behavior?
Updated bbolt dependency to v1.3.3 per https://github.com/etcd-io/bbolt/pull/153
The only downside is that if the db txn has to be rolled back in case of failure, the freelist must be built again temporarily which can be heavy with big databases.  I think this is an acceptable tradeoff since this …
> channeldb: specify freelist bbolt options by default

- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
There is no shell command for:
`$ lncli subscribechannelevents`
```
No help topic for 'subscribechannelevents'
```
This leads to an error when regenerating the docs with https://github.com/lightninglabs/lightning-api.
The current documentation does not contain the shell command for lncli subscribechannelevents either for the same reason: https://api.lightning.community/?shell#subscribechannelevents
Fixed when removed from rpc.proto.
> lnrpc: remove lncli subscribechannelevents

- config.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/test_utils.go
- peer.go
The current value was based on the previous default CLTV delta of 144 blocks. This has been lowered to 40 since lnd v0.6.0-beta, making the current value of 5000 blocks a bit high. Lowering it to one week should be more than enough to account for the other major lightning implementations. Eclair currently has a default CLTV delta of 144, while c-lightning's is 14.
The value can be configured through the `--max-cltv-expiry` flag.
Fixes https://github.com/lightningnetwork/lnd/issues/3286.
> htlcswitch: make max cltv expiry configurable and lower default

- channeldb/payments.go
- channeldb/payments_test.go
- lnrpc/routerrpc/config.go
- lnrpc/routerrpc/config_active.go
- lnrpc/routerrpc/config_default.go
- lnrpc/routerrpc/router_backend.go
- lnrpc/routerrpc/router_backend_test.go
- lnrpc/routerrpc/router_server.go
- lnwire/onion_error.go
- routing/missioncontrol.go
- routing/missioncontrol_store.go
- routing/missioncontrol_store_test.go
- routing/missioncontrol_test.go
- routing/mock_test.go
- routing/payment_lifecycle.go
- routing/router.go
- routing/router_test.go
- server.go
This PR adds persistence to mission control by storing the raw payment results and reprocessing them on startup.
> routing: persistent mission control

- log.go
Most likely because of a typo, NTFR was mapping to ntfnLog instead of
ntfrLog.
Originally added in 59e2be5306a77fff24bf2e8be1ba335247ef5beb
> [trivial] log: correct NTFR -> ntfrLog mapping

- README.md
In this commit, we update the link to the security PGP key to a gist. We
do this as recent DoS attacks against popular keservers have rendered
many of them unresponsive or only partially operating. As a temporary
measure, we link to a gist until an alternative solution is found.
> README: update link to security PGP key

- log.go
- peernotifier/log.go
- peernotifier/peernotifier.go
- server.go
This PR adds a peer notifier package which supplies clients with peer online/offline subscriptions and a corresponding rpc endpoint. 
It is intended for use in work related to #3332 to incorporate peer online/offline events in channel scoring. 
logging level - peer logger was used, it felt like the most appropriate?
> Peernotifier: Add Peer Notifier package

- log.go
- rpcserver.go
Not all errors that occur when serving client requests in the gRPC
server are logged. As a result, at times, we can be lacking critic
information that can be used to debug issues that pop up. With this PR,
we create a basic streaming+unary interceptor that will log all errors
that occur when servicing calls.
The current format looks something like this in the logs when an error
occurs:
```
[ERR] RPCS: [/lnrpc.Lightning/SendCoins]: decoded address is of unknown format
```
> rpc: add unary+streaming interceptors to log all errors

- lnd.go
Some time ago, we modified `lncli` to accept larger responses from the
server, up to 50MB. However, we failed to update the REST proxy, which
is in a sense, a client to the regular RPC server. As a result, users
can't currently hit the `/v1/graph` endpoint, as it'll fail with an
error.
In this PR, we update the proxy's dial options to allow it to receive
larger responses from the actual gRPC server. This is only a temporary
measure however, as we'll eventually want to expose some sort of
pagination for the end client.
> REST: increase max msg size for REST proxy

- .golangci.yml
- Makefile
- channeldb/channel.go
- htlcswitch/switch.go
- macaroons/constraints_test.go
- watchtower/wtdb/client_db.go
- watchtower/wtdb/codec.go
`gometalinter` has been deprecated: https://github.com/alecthomas/gometalinter/issues/590
Line length check is NOT enabled, since it will fail many places throughout the codebase. It looks like it was never working properly with the old linter.
> [build, tooling] change linter gometalinter->golangci-lint

- tlv/truncated.go
- tlv/truncated_test.go
This PR fixes a bug in DTUint16 and DTUint32, which would cause them
to read too many bytes from the reader. This is due to the fact that
ReadFull was being called on a slice that could be greater than the
underlying type. This is not an issue for DTUint64, since the 8-byte
buffer corresponds to the maximum possible size of a uint64. The
solution is to clamp the buffer to 2 and 4 bytes respectively.
A series of tests are also added to exercise these cases.
> tlv: fix decoding bug for truncated uint16 and uint32

- Makefile
- make/testing_flags.mk
Something about having submodules causes `go list` not to pick them up, so we edit the Makefile to restore tests, coverage, and linting
> Makefile: ensure submodules are linted, covered, and tested

- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
- lnrpc/invoicesrpc/invoices_server.go
Fixes a synchronization issue where a single invoice subscriber could receive duplicate and/or out of order invoice updates.
Modification required in master to reliably reproduce the test `TestHoldInvoice` failing:
```
case newClient := <-i.newSingleSubscriptions:
// DEBUG: To trigger test fail, remove.
time.Sleep(time.Second)
err := i.deliverSingleBacklogEvents(newClient)
```
>  invoices: fix synchronization issue with single invoice subscribers

- htlcswitch/link.go
- htlcswitch/switch_test.go
- lntest/itest/lnd_test.go
- routing/missioncontrol.go
- routing/mock_test.go
- routing/payment_lifecycle.go
- routing/payment_session.go
- routing/payment_session_source.go
- routing/payment_session_test.go
- routing/result_interpretation.go
- routing/result_interpretation_test.go
- routing/router.go
- routing/router_test.go
This PR overhauls the interpretation of failed payments. It changes the interpretation rules so that we always apply the strongest possible set of penalties, without making assumptions that would hurt good nodes.
Main changes are:
* Apply different rule sets for intermediate and final nodes. Both types of nodes have different sets of failures that we expect. Penalize nodes that send unexpected failure messages.
* Distinguish between direct payments and multi-hop payments. For direct payments, we can infer more about the performance of our peer because we trust ourselves.
* In many cases it is impossible for the sender to determine which of the two nodes in a pair is responsible for the failure. In this situation, we now penalize bidirectionally. This does not hurt the good node of the …
> routing: failure attribution

- discovery/gossiper.go
- discovery/gossiper_test.go
There's no need to broadcast these as we assume that online nodes have already received them. For nodes that were offline, they should receive them as part of their initial graph sync.
Depends on #3355.
> discovery: prevent broadcast of anns received during initial graph sync

- tlv/stream.go
- tlv/tlv_test.go
Builds on #3407, which contains the original report and fix by @Crypt-iQ. Primary difference is the addition of a test that confirms the fix works.
Supercedes #3407
> tlv: limit decoded record size

- lnd.go
The server was kept alive long after it stopped being used. This caused
problems for services using long-lived GRPC connections which might be
created before wallet unlocked. They got stuck connected to the wallet
unlock service needing a restart.
logging level
per default)
already exist
> lnd: close the wallet unlock grpc server

- config.go
- htlcswitch/switch.go
- lntest/itest/lnd_test.go
- server.go
In this PR, we add a flag to the command line config `--rejecthtlc` and a 
field in the HTLC Switch config `RejectHTLC bool`.
The user should be able to start lnd with the `--rejecthtlc` flag which will
mean that lnd will reject any onward HTLCs. The switch will still allow receiving
HTLCs meant for the node and can still send HTLCs.
fixes #1298 and #2109
> htlcswitch+config+server: adding RejectHTLC flag

- cmd/lncli/commands.go
Fixes https://github.com/lightningnetwork/lnd/issues/3452.
> cmd/lncli: return error upon missing channel backup when parsing

- cmd/lncli/commands.go
This PR fixes a dropped error in the `lncli` command.
> cmd/lncli: Fix dropped error

- chainntnfs/interface_test.go
- chainntnfs/test_utils.go
In this commit, we lower the mempool spend check timeout to be twice as
long as the trickle interval of the miner node, which will greatly
improve the execution time of this specific test. We're able to do this
now since we can specify custom trickle intervals for our test
harnesses.
> chainntnfs/interface_test: lower mempool spend check timeout

- .travis.yml
- lntest/bitcoind.go
- lntest/btcd.go
- lntest/itest/lnd_test.go
- lntest/neutrino.go
This PR enables the `bitcoind` backend for integration tests.
> [itests] Bitcoind integration test

- config.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/test_utils.go
- lnwallet/channel.go
- peer.go
In this PR, we begin to enforce a maximum channel commitment fee for channel initiators when attempting to update their commitment fee. Now, if the new commitment fee happens to exceed their maximum, then the fee update won't be proposed and the channel will remain with its previous commitment fee. Note that this won't cause the channel to be closed, but will likely be done at a later time.
A default of up to 50% of the channel initiator's balance is enforced for the maximum channel commitment fee. It can be modified through the `--max-channel-fee-allocation` CLI flag.
Fixes #3006.
> htlcswitch: avoid proposing fee updates exceeding max fee allowed

- htlcswitch/circuit_map.go
- htlcswitch/hop/forwarding_info.go
- htlcswitch/hop/network.go
- htlcswitch/hop/payload.go
- htlcswitch/hop/type.go
- htlcswitch/iterator.go
- htlcswitch/iterator_test.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/switch.go
- htlcswitch/test_utils.go
Builds on #3441 
This PR begins the process of moving our hop payload processing within lnd into its own subpackage, `htlcswitch/hop`. This will allow the processing to be imported into the `htlcswitch` and `contractcourt`, and also have a single `hop.Payload` object that can be shared with the invoice registry. The last four commits are predominately a code move, but it will be nice to make progress on the more trivial things so we can do less rebasing on #3442 
This will also allow @joostjager to add his follow up in moving the `HopIterator` components into this package, and establish a stable base to continue mpp/amp development
> htlcswitch/hop: new package for hop payload parsing/encapsulation

- pilot.go
This PR adds a couple of missing variables in log message in initAutoPilot method.
> trivial: fix log message in initAutoPilot

- .gitignore
- Makefile
- cmd/lnd/main.go
- lnd.go
- mobile/README.md
- mobile/bindings.go
- mobile/gen_bindings.sh
- mobile/sample_lnd.conf
- rpcserver.go
This PR adds the necessary APIs and build scripts in order to compile `lnd` for mobile platforms.
Follow [gomobile](https://github.com/golang/go/wiki/Mobile) in order to intall `gomobile` and dependencies.
Remember to run `gomobile init`! (otherwise the `lnd` build might just hang).
Install [`falafel`](https://github.com/halseth/falafel):
```
go get -u -v github.com/halseth/falafel
``` 
```
make ios
```
```
make android
```
`make mobile` will build both iOS and Android libs.
After the build has succeeded, the libraries will be found in `mobile/build/ios/Lndmobile.framework` and `mobile/build/android/Lndmobile.aar`. Reference your platforms' SDK documentation for how to add the library to your project.
TODO
> [mobile] Mobile RPCs

- docs/INSTALL.md
Add 'Creating a wallet' section, explaining that 'lncli create' must be run
with a new instance. Also describe the password prompt and mnemonic this
command presents to the user.
> Update INSTALL.md to include first wallet creation

- channeldb/channel.go
- channeldb/graph.go
- channeldb/invoices.go
- channeldb/payment_control.go
This PR fixes a bug where errors are checked, but not returned.
> channeldb: return errors instead of nil 

- channeldb/migration_09_legacy_serialization.go
- channeldb/migrations_test.go
In this commit, we ensure that the test for migration 9 uses the same
encoding/decoding functions as was present in the repo when the
migration was first added. Otherwise, the test will fail as it'll try to
use the decoding functions of master (migration 10 and onwards) rather
than the decoding function of migration 9.
> channeldb: ensure test for migration 9 is fully enclosed

- htlcswitch/hop/payload.go
- htlcswitch/hop/payload_test.go
- tlv/record.go
- tlv/stream.go
- tlv/stream_test.go
Builds on #3441 
This commit adds an additional return value to `Stream.Decode`, which
returns the set of types that were encountered during decoding. The set
will contain all known types that were decoded, as well as unknown odd
types that were ignored.
The rationale for the return value (rather than an internal member) is
so that the stream remains stateless.
This return value can be used by callers during decoding to make
assertions as to whether specific types were included in the stream.
This is need, for example, when parsing onion payloads where certain
fields must be included/omitted depending on the hop type.
> tlv+htlcswitch: validate presence/omission of parsed onion payload types

- htlcswitch/log.go
Logging for the hop package is controlled via the parent htlcswitch
package. Unfortunately the parent package only controlled the
initialization, but didn't enable the logger when the log level came
in from the main lnd package.
> htlcswitch/hop: fix logging

- channeldb/payment_control_test.go
- channeldb/payments_test.go
Previously the route to compare was modified in order for DeepEqual to function properly. This created problems when tests were ran in parallel (travis build failing).
> channeldb/test: make route comparison a pure function

- contractcourt/channel_arbitrator.go
- contractcourt/commit_sweep_resolver.go
- contractcourt/contract_resolvers.go
- contractcourt/htlc_incoming_contest_resolver.go
- contractcourt/htlc_outgoing_contest_resolver.go
- contractcourt/htlc_success_resolver.go
- contractcourt/htlc_timeout_resolver.go
Small change that contributes to the end goal of being able to run the integration tests without errors.
> cnct: do not log resolver shutting down as error

- config.go
- mobile/sample_lnd.conf
This pull request adds a new config `norest` that disables the REST gRPC proxy API.  
The rationale behind it is that lndmobile projects (https://github.com/lightningnetwork/lnd/pull/3282)  do not need the TCP REST API as they're using in-mem gGRPC, but it could be useful for other applications and projects as well.  
Disabling it also makes sure that two different wallets do not collide with each other as they otherwise would do if they're both listening on the same interface/port:
```
[ERR] LTND: Unable to set up wallet password listeners: listen tcp4 127.0.0.1:8080: bind: address already in use
...
[INF] LTND: Shutdown complete
```
the positive and negative (error paths) …
> config: Add norest config for disabling REST API

- breacharbiter_test.go
- contractcourt/briefcase_test.go
- htlcswitch/payment_result_test.go
- htlcswitch/test_utils.go
- invoices/invoiceregistry_test.go
- lnwallet/test_utils.go
- macaroons/service_test.go
- routing/pathfind_test.go
- routing/router_test.go
- test_utils.go
lnd: Fix dropped errors in tests.
routing: Fix dropped errors in tests.
contractcourt: Fix dropped errors in tests.
htlcswitch: Fix dropped errors in tests.
invoices: Fix dropped error in tests.
lnwallet: Fix dropped errors in tests.
macaroons: Fix dropped error in tests.
This PR fixes dropped error variables in tests across the project.
> Cross-Project Sweep to Fix Dropped Test Errors

- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
Fixes the 'unable to find incoming resolution' error that occured when trying to resolve incoming htlcs below the dust limit that are not actually present on the commitment tx.
> cnct: do not create an action for incoming dust htlcs

- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
Earlier we would not react to breaches, as these are handled by other
subsystems. Now we advances our state machine in case of breach, such
that we'll gracefully exit, and won't have leftover state in case of a
restart.
In particular this was a problem on restarts, as the channel arbitrator 
would fail to recognize channels pending
close that were in the breached state. This lead to the state machine
not progressing correctly, and in some cases crashing since we would
attempt to force close an already closed channel.
Needed for #3016
> [contractcourt] Gracefully advance channel arbitrator state machine on breach

- lnwallet/interface_test.go
This PR fixes a test in `lnwallet` where some of the error conditions could never be recorded, because they were happening inside a goroutine. 
`T.Fatal()` is a convenience function that combines `T.Log()` and `T.FailNow()`. 
From the godoc of `T.FailNow()`: 
> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.
To see this in action, take a look at `main_test.go` in my [example repo](https://github.com/alrs/fatalfail/).
> lnwallet: fix goroutines in tests

- Makefile
- release.sh
Allows lnd to still be compiled with go1.12.x, tho users with go1.13 can
still verify release binaries.
> Makefile+release: only use -trimpath on release script

- docker/lnd/Dockerfile
New go minimum version required is 1.13 as per [this](https://github.com/lightningnetwork/lnd/pull/34589) change.
Docker build will fail due to missing trimpath.
> Update Dockerfile go version to 1.13

- fundingmanager.go
- fundingmanager_test.go
- htlcswitch/link.go
- lntest/itest/lnd_test.go
- lnwire/error.go
- lnwire/lnwire.go
- peer.go
Since the ErrorCodes are not part of the spec, they cannot be read by
other implementations.
Instead of only sending the error code we therefore send the complete
error message.
> [lnwire+funding] Don't send ErrorCode on wire

- go.mod
- queue/go.mod
In a `go.mod` file, you can specify the minimum version that is needed to compile the module.
At the moment we have three different values:
* root (lnd) -> `go 1.13`
* ticker -> `go 1.12`
* queue -> no go version
This PR adds version `1.12` to `queue` and downgrades the version in the root `go.mod` to `1.12`.
With these changes I was able to make the project using go `1.12` and the command `go mod tidy` didn't yield any more diffs.
> lnd+queue: specify go 1.12 in all go.mod files

- config.go
Fix a trivial typo in config.go:
"setto" -> "set to"
> trivial: fix typo in config.go

- go.mod
- go.sum
- lnwallet/btcwallet/btcwallet.go
- lnwallet/interface_test.go
Earlier we would not return `ErrDoubleSpend` if a transaction failed to publish because there was an existing, RBF-signaling, transaction in the mempool. This could happen in cases where we attempted to force close the channel, but a different closing transaction was already broadcasted.
Now we'll properly now that this error is not critical, such that we can continue resolving the closing channel.
Depends on https://github.com/btcsuite/btcwallet/pull/647
Needed for #3016
> Handle RBF signaling publication failures in wallet

- docker/README.md
This instruction did not get updated when the docker-compose file removed the `alice` service. This changes makes the command work and is consistent with the instructions in the previous section.
Fixes https://github.com/lightningnetwork/lnd/issues/3408
> fixed 1-line errant docker-compose command in instructions

- discovery/bootstrapper.go
- discovery/gossiper.go
- discovery/syncer_test.go
The most important part of this PR is taking test goroutines from `discovery` and exfiltrating their test results through error channels.
`discovery: use error channels with test goroutines`
Along for the ride are a bevy of linter nits:
`discovery: error string lint fixes`
`discovery: lint fix to remove append loop`
> discovery: Goroutine Test Fixes and Linting

- fundingmanager.go
- fundingmanager_test.go
This PR contains a set of commit to clean up the `fundingmanager` state machine. We now share a common codepath between all funding flows, both as initiator and responder. We also reuse this codepath at restart, greatly reducing the number of cases we handle.
> Fundingmanager state machine cleanup

- lnwire/commit_sig.go
- lnwire/revoke_and_ack.go
- lnwire/update_add_htlc.go
- lnwire/update_fail_htlc.go
- lnwire/update_fail_malformed_htlc.go
- lnwire/update_fee.go
- lnwire/update_fulfill_htlc.go
- peer.go
This PR fixes a long standing TODO, creating a minimal interface for messages that are destined for links. This allows a much simpler method of extracting the channel id rather than type switching every message individually. Several PRs in the future will build on this as we begin to refactor the peer and make it easier to test.
> peer: link updater refactor

- chancloser.go
- channeldb/channel.go
- channeldb/channel_test.go
- channeldb/db_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_arbitrator_test.go
- contractcourt/chain_watcher.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
- htlcswitch/link.go
- lntest/itest/lnd_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- lnwallet/test_utils.go
- peer.go
This PR makes us store the closing TX we propose to the database, such that the ChainArbitrator can re-publish them at startup for channels in state `waiting close`.
This is meant to handle the case were we attempt to close the channel, but go down before the tx has propagated to the network. Now we'll instead store this tx the moment it is ready, such that we can re-publish it.
Builds on https://github.com/lightningnetwork/lnd/pull/3510
> [contractcourt] Republish close tx on startup

- .golangci.yml
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
In this commit, we fix an existing bug in the package, causing
resolutions to be restarted without their required supplementary
information. This can happen if a distinct HTLC set gets confirmed
compared to the HTLCs that we may have had our commitment at time of
close. Due to this bug, on restart certain HTLCS would be rejected as
they would present their state to the invoice registry, but be rejected
due to checks such as amount value.
To fix this, we'll now pass in the set of confirmed HTLCs into the
resolvers when we re-launch them, giving us access to all the
information we need to supplement the HTLCS.
> contractcourt: supplement resolvers with confirmed commit set HTLCs

- cmd/lncli/commands.go
- lnd.go
- lnrpc/routerrpc/router_backend.go
- lnrpc/walletrpc/walletkit_server.go
- lntest/harness.go
- lntest/itest/lnd_test.go
- lntest/node.go
- macaroons/auth.go
- macaroons/constraints.go
- macaroons/service.go
- macaroons/store.go
- rpcserver.go
- walletunlocker/service.go
- walletunlocker/service_test.go
This PR changes packages across the project to use the standard library `context` package instead of the old `golang.org/x/net/context`.
> Use stdlib "context" Package

- channeldb/meta_test.go
- channeldb/migration_11_invoices.go
- channeldb/migration_11_invoices_test.go
If the db migration is performed while there are accepted hodl invoices, held htlcs may be released on startup. 
Now that all invoice htlcs are tracked in the database, we are able to keep apart replays from new htlcs. For invoices that were accepted while running the previous version, there is no htlc entry present in the database. The consequence of this is that the htlc is evaluated as new and that it should again match the final cltv delta requirement, which may not necessarily be the case anymore. If it doesn't match, the held htlc is released and the node does not get paid.
> channeldb: safe invoice migration

- Dockerfile
The latest golang docker images is based on golang 13. lnd does not compile with golang 13 docker image. It is a good practice to specify version information in the Dockerfile. This ensures, that the correct docker image is used. I also removed the CMD, because in this case it is redundant to ENTRYPOINT.
If possible it would be great, to have the latest images available at docker hub as well. ATM there is a very old image at Docker hub, that did not worked for me.
/legacycode
> Fixed dockerfile by adding version numbers to base containers

- lnwire/features.go
Final version of spec allocated 12/13 to option_static_remote_key.
https://github.com/lightningnetwork/lightning-rfc/blob/master/09-features.md
> lnwire/features: static_remote_key bits, 10/11 -> 12/13

- build/release/README.md
- build/release/release.sh
In this commit, we create a new `build/release` package which houses the
container and scripts that we need to do deterministic builds across
Windows, Linux, and MacOS. As a result, all builds of `lnd` will now
take place from within this container environment. The container will
mount to the local `lnd` directory, resulting in all the build artifacts
being present in the host's cwd.
With this new system, it's now possible for all `lnd` developers, as
well as users to verify the posted build binaries. This wasn't possible
in prior release as only in Go 1.13 did deterministic builds becomes
easier/possible. See the new `README.md` for further details.
> build/release: create new release package for reproducible builds

- lnwallet/channel.go
- lnwallet/channel_test.go
Without this, it was possible for a combination of our balance and max fee allocation to result in a fee rate below the fee floor causing the remote party to reject the update and close the channel.
> htlcswitch: enforce fee floor on max fee allocation

- fundingmanager.go
- lnwallet/channel.go
- lnwallet/chanvalidate/validate.go
- lnwallet/chanvalidate/validate_test.go
- lnwallet/wallet.go
- routing/router.go
In this commit, we create a new `chanvalidate` package which is to house
all logic required for 1st and 3rd party channel verification. 1st party
verification occurs when we find a channel in the chain that is
allegedly ours, while 3rd party verification will occur when a peer
sends us a channel proof of a new channel.
In the scope of the recent CVE, we actually fully verified 3rd party
channels, but failed to also include those checks in our 1st party
verification code. In order to unify this logic, and prevent future
issues, in this PR we move to concentrate all validation logic into a
single function. Both 1st and 3rd party validation will then use this
function. Additionally, having all the logic in a single place makes it
easier to audit, and also write tests against.
> chanvalidate: create new channel validation package 

- chainntnfs/test_utils.go
- chainregistry.go
- channeldb/db.go
- channeldb/options.go
- config.go
- go.mod
- go.sum
- keychain/interface_test.go
- lnd.go
- lnwallet/btcwallet/btcwallet.go
- lnwallet/btcwallet/config.go
- lnwallet/interface_test.go
- routing/chainview/interface_test.go
- walletunlocker/service.go
- walletunlocker/service_test.go
With the introduction of https://github.com/lightningnetwork/lnd/pull/3278 and https://github.com/btcsuite/btcwallet/pull/634, all of the databases used within `lnd` specified the `NoSyncFreelist` option, resulting in increased memory performance, but with an increase in startup time since they have to reconstruct their freelist. In https://github.com/lightningnetwork/lnd/issues/3544 it was discovered that this can be an issue with mobile clients due to their lower resources. To remedy this, we add a `--sync-freelist` flag to `lnd` that can be enabled to prevent this behavior. Note that the default is to not have the databases sync their freelist, which is the current behavior as of the master branch.
Fixes https://github.com/lightningnetwork/lnd/issues/3544.
> config: add sync freelist cli flag

- build/release/release.sh
Notably, solaris/amd64 and illumos/amd64 were added in go1.13. The
others were have been supported previously but were not build targets
> build/release: update release targets

- lntest/harness.go
We might hit a connection refused error in cases where the peer connects
to us exactly as we try to connect to it. We retry the connection within
a wait predicat, as it should be the case that the other peer
establishes the connection, and the two peers actually connects.
Should resolve the flake
```
--- FAIL: TestLightningNetworkDaemon/data_loss_protection (12.68s)
lnd_test.go:99: Failed: (data loss protection): exited with error: 
*errors.errorString unable to connect Dave to carol: rpc error: code = Unknown desc = dial tcp 127.0.0.1:19799: connect: connection refused
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:8239 (0xd4e2c3)
testDataLossProtection.func1: t.Fatalf("unable to connect %v to carol: %v", …
```
> lnd_test: give peers more time to successfully attempt connection

- cmd/lncli/commands.go
- rpcserver.go
Closes https://github.com/lightningnetwork/lnd/issues/3357.  When
start_time isn't specified, its default value is 0.  This meant when
users explicitly specified a start_time of 0, we would incorrectly set
start_time to 24 hours in the past.  Now, n0 means n0.
logging level
per default)
already exist
> rpcserver: startTime defaults to the unix epoch

- build/release/README.md
This PR aims to extract the verification portion from our release notes to our release guide with clear and concise steps. Along the way, steps have been included to also verify the integrity of the release binaries themselves, not just the archives, allowing users to no longer trust the release manager(s) built the proper binaries.
> build: expand reproducible build system with build and verification steps

- channeldb/db.go
- channeldb/error.go
- channeldb/legacy_serialization.go
- channeldb/migration_09_legacy_serialization.go
- channeldb/migrations.go
- channeldb/migrations_test.go
- channeldb/payments_test.go
In this commit, we revert #3485, thereby reverting to our existing migration policy. The prior stricter policy created a large burden on applications that package `lnd` as they're forced to deploy special code to handle certain upgrade paths. In addition, it was realized that the policy was most damaging to mobile deployments as it's customary for users to skip versions, making the stricter upgrade policy difficult to manage without dramatically affecting the end user.
> channeldb: revert to prior migration policy 

- discovery/gossiper.go
It was missing a space
`addingto waiting batch` -> `adding to waiting batch`
> discovery/gossiper: fix minor typo

- build/log.go
- build/logrotator.go
- config.go
- lnd.go
- log.go
- rpcserver.go
Since we want to use persistent logging with log file rotation in other projects like loop as well, it would be nice if we could reuse the code directly instead of copy/pasting it.
This PR moves most of the log file rotation code and the code used for parsing and setting the log level into the `build` package.
> build+lnd: refactor reusable log file rotator code into build package

- build/prefix_log.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- lnwallet/channel.go
This pr unifies logging statements in `link` and `channel` via a prefix logger.
> build+htlcswitch+lnwallet: add prefix logger

- breacharbiter.go
- input/input.go
- input/witnessgen.go
- server.go
- sweep/store.go
- sweep/store_test.go
- sweep/sweeper.go
- sweep/sweeper_test.go
- sweep/test_utils.go
- sweep/txgenerator.go
- sweep/txgenerator_test.go
- utxonursery.go
This PR has the goal to make the sweeper module usable outside of `lnd`.
This is achieved by reworking the `WitnessType` into an interface.
There is a list of `StandardWitnessType`s that represent all internally known witness types of lnd.
In internal functionalities like `breacharbiter` or `utxonursery` only the standard witness types are used.
Only the `input` package's `MakeBaseInput` accepts generic witness types so the sweeper can be used to sweep custom witness outputs outside of lnd.
> input+sweep: rework witness type into interface to be used externally

- config.go
- server.go
- tor/controller.go
This option is required when the Tor server is not running on the same host as lnd. Otherwise peers can't connect to lnd through the onion service.
For example let's say you have a Kubernetes cluster and have a single Tor server which can be used by all the internal services. Then you can start lnd with `--tor.active --tor.v3 --tor.sock=tor:9050 --tor.control=tor:9051 --tor.targetipaddress=$MY_POD_ID`.
> Tor option to override target IP address

- docs/code_contribution_guidelines.md
There is a spacing issues, and thus a formatting 
issue, in the file, code_contribution_guidelines.md
logging level
per default)
already exist
> Fix Formatting of *Wrong*

- macaroons/service_test.go
- macaroons/store_test.go
macaroons: defer service.Close() after error check in tests
macaroons: explicitly drop unneeded variables in tests
> macaroons: Test Improvements

- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- htlcswitch/test_utils.go
This PR fixes inconsistencies in the returned failure messages when forwarding non-strict.
> htlcswitch: fix non-strict forwarding failures

- chainntnfs/txnotifier.go
- chainntnfs/txnotifier_test.go
When a confirmation notification for a script hash is registered, the notifier panics with a nil pointer dereference in case two transactions send funds to this script and are confirmed at different block heights.
The test that triggers the panic is added in the first commit with a fix for it in the second commit.
> chainntnfs: fix nil pointer on address reuse

- routing/heap.go
- routing/heap_test.go
- routing/pathfind.go
This PR brings down path finding time by using the channel cache and some other small optimizations. The goal was to bring the time down to ~10ms range. Using a benchmark, described below, it started at 220ms/72mb per path finding operation and with these changes it comes down to 9ms/1.1mb.
I've written [a benchmark](https://github.com/lightningnetwork/lnd/commit/fd34d90b89d500118ab10763c408cc55c2b969cf) based on a dump of the main net graph (its a few months old now) in order to test these changes. The bench is roughly as follows:
- The first time only, a DB is built using the graph dump JSON
- The DB is used for a simple path finding run to prime the channel cache
- Path finding runs in a nested benchmark as many times as `go test` sees fit
A second bench, almost equal to the first one …
> routing, channeldb: several optimizations for path finding

- lntest/harness.go
- rpcserver.go
- server.go
We do this as a general sanity check to ensure channels cannot be closed while either the backend is still syncing or the server is still starting.
> rpcserver: ensure server has started before CloseChannel

- fundingmanager.go
Since the funding flow requires messages to go through, make use of
sync version of SendToPeer. Using the async version we would risk that
the message was dropped and the process would stall (it would properly
continue after a restart though).
Only the `FailFundingFlow` stays async.
As discussed in https://github.com/lightningnetwork/lnd/pull/1910#discussion_r327391106, this was unintentionally made async in an earlier PR.
> fundingmanager: make SendToPeer sync

- lnwire/msat.go
- routing/pathfind.go
- routing/router.go
- routing/router_test.go
- routing/unified_policies.go
- routing/unified_policies_test.go
This pr makes path finding (and build route) aware of non-strict forwarding. Before deciding on a path edge, it calculates a single unified policy for the complete set of channels between two nodes.
> routing: non-strict path finding

- docker/lnd/Dockerfile
Currently, changing the source code causes the docker layer cache to break the caching of package installation (make, git, etc). This makes rebuilds of the container due to source code changes unnecessarily expensive.
If we execute the source COPY command as an individual command, _after the installation of the OS packages_, then rebuilds of the container will be much quicker.
- [ x] If this is your first time contributing, we recommend you read the [Code
- [ x] All changes are Go version 1.11 compliant
- [ x]  The code being submitted is commented according to the
- [ x]  For new code: Code is accompanied by …
> Add source after installing apk packages to avoid breaking docker cache

- go.mod
- go.sum
- lnrpc/README.md
- lnrpc/gen_protos.sh
- lnrpc/rpc.pb.gw.go
- lnrpc/rpc.swagger.json
Fixes #3168
When using the REST gateway, fields that have the type `bytes` in `rpc.proto` cannot be used in query or path parameters (see #552 which lead to workarounds like #592).
The root cause of this is that the version of `grpc-gateway` we use doesn't support mapping to `[]byte` yet.
Trying to use `bytes` parameters results in `{"error":"unsupported field type uint8","code":3}`.
This has been fixed in https://github.com/grpc-ecosystem/grpc-gateway/pull/489.
Unfortunately, we can't use the newest version of `grpc-gateway` (which would be `1.11.3` at the moment) because that has a bug that messes up our `rpc.swagger.json` (https://github.com/grpc-ecosystem/grpc-gateway/issues/746).
After some trial and error, I found that version `1.8.6` is the newest version that works for our use …
> proto+lnrpc: update gRPC-REST gateway to v1.8.6

- autopilot/agent.go
- autopilot/agent_test.go
- autopilot/manager.go
- pilot.go
This PR adds a new signal to the autopilot agent, meant to signal
when any of the available heuristics has gotten an update.
We currently use this to trigger a new channel opening after the
external scores have been updated.
> [autopilot] Trigger channel opening on external score update 

- make/testing_flags.mk
This fixes the logging of used backend in the default (btcd) case.
Otherwise the `${backend}` variable would be left unset.
> [trivial] make: default backend variable to btcd

- routing/router.go
Running lnd with thread sanitizer found the following:
```
Write at 0x00c000797568 by goroutine 21:
github.com/lightningnetwork/lnd/ticker.(*T).Pause()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/ticker/ticker.go:115 +0x96
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).networkHandler()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/routing/router.go:1067 +0x12d7
Previous read at 0x00c000797568 by goroutine 150:
github.com/lightningnetwork/lnd/ticker.(*T).Resume()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/ticker/ticker.go:103 +0x47
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).processUpdate()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/routing/router.go:1347 +0x8d4 …
```
> ticker: add tickerMtx to prevent data race

- docs/INSTALL.md
- docs/MAKEFILE.md
By just following the docs on how to run unit tests, most users would see failed tests because they don't have `bitcoind` on their `$PATH`. We should explicitly mention this to avoid getting more issues like #3681.
> docs: bitcoind is required for unit tests

- contractcourt/htlc_outgoing_contest_resolver.go
- contractcourt/htlc_outgoing_contest_resolver_test.go
This PR adds test coverage for the outgoing contest resolver. Currently this resolver is also hit via one of the channel arbitrator tests (`TestChannelArbitratorLocalForceClosePendingHtlc`), but covering it in an isolated unit test has the following benefits:
* Makes it easier to test multiple scenarios for the outgoing contest resolver.
* Because the resolver itself is covered, it allows the channel arbitrator test to be refactored with mock resolvers. This makes it easier to also cover multiple scenarios there. For anchor outputs, refactoring of the channel arbitrator is expected (#3587).
> cnct/test: add outgoing contest resolver test

- routing/missioncontrol.go
- routing/missioncontrol_test.go
- routing/probability_estimator.go
- server.go
Previously we used the a priori probability also for our own untried channels. This led to local channels that had seen a success already being prioritized over untried local channels. In some cases,  depending
on the configured payment attempt cost, this could lead to the payment taking a two hop route while a direct payment was also possible.
> routing: use distinct probability estimation for local channels

- htlcswitch/link.go
- htlcswitch/link_isolated_test.go
- htlcswitch/link_test.go
- lnwallet/channel.go
Builds on top of #3564.
This PR fixes two known bugs in the commitment tx update sequence:
* Sending an commit sig message that didn't sign any new updates ("empty commit sig")
* Not sending a commit sig message when it is expected.
In addition to that, several simplifications are carried through where values were tracked in the link that can also be obtained from the channel.
> htlcswitch: fix empty commit sig and no commit sig

- contractcourt/briefcase.go
- contractcourt/channel_arbitrator.go
- contractcourt/commit_sweep_resolver.go
- contractcourt/contract_resolvers.go
- contractcourt/htlc_incoming_contest_resolver.go
- contractcourt/htlc_incoming_resolver_test.go
- contractcourt/htlc_outgoing_contest_resolver.go
- contractcourt/htlc_outgoing_contest_resolver_test.go
- contractcourt/htlc_success_resolver.go
- contractcourt/htlc_timeout_resolver.go
- contractcourt/htlc_timeout_resolver_test.go
This PR makes the instantiation of resolvers stricter and thereby opens up the path to also add initialization logic to a resolver.
Spin off of #3644
> cnct: add resolver constructors

- lnd.go
- signal/signal.go
If the lnd package is referenced, the interrupt signal handler will be initialized causing lncli to not properly exit on ctrl-c.
This commit prevents this by making the initialization of the interrupt interceptor an explicit action.
> lncli: do not hang on ctrl-c

- contractcourt/briefcase_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
- contractcourt/contract_resolvers.go
- contractcourt/htlc_incoming_contest_resolver.go
- contractcourt/htlc_incoming_resolver_test.go
- contractcourt/htlc_outgoing_contest_resolver.go
- contractcourt/htlc_outgoing_contest_resolver_test.go
- contractcourt/htlc_success_resolver.go
- contractcourt/htlc_timeout_resolver.go
- contractcourt/interfaces.go
- htlcswitch/hop/iterator.go
- server.go
Also for on-chain resolution, we may require access to the onion payload. An example of this is the resolution of an mpp shard. We need the mpp fields in order to properly offer the htlc to the invoice registry.
> cnct: decode onion for incoming contest resolver

- htlcswitch/failure.go
- htlcswitch/link_test.go
- routing/payment_lifecycle.go
- routing/route/route.go
This pr contains several changes to improve the information that is logged when a payment attempt fails, which will hopefully help us in debugging routing/mission control related issues.
> routing+htlcswitch: improve failed payment logging

- cmd/lncli/main.go
This PR increases the gRPC max receive size again, this time from 50MiB to 200MiB.
The operation that hits the maximum is `lncli listchaintxns` with about 2.6k transactions on testnet (see https://github.com/lightninglabs/lndmon/issues/48).
As mentioned in #2374, this only affects `lncli`, users of the gRPC API need to set this value on the client side.
> Increase block size to 200 gigamegs!

- routing/router.go
Found while running the integration tests with `-race`. Reuse of `err` variable when resuming payments in goroutines.
```
Write at 0x00c000a680f0 by goroutine 147:
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start.func1()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/routing/router.go:536 +0x251
Previous write at 0x00c000a680f0 by goroutine 143:
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start.func1()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/routing/router.go:536 +0x251
Goroutine 147 (running) created at:
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/routing/router.go:521 +0x42c
github.com/lightningnetwork/lnd.(*server).Start.func1() …
```
> routing: fix race condition when resuming payments

- Dockerfile
- docs/DOCKER.md
Add `build-arg` to docker for choosing which branch, tag or commit to run during build time.
> specify a tag, branch or commit during docker prod build

- lnd.go
Follow-up for #3730. The REST proxy needs the same max message receive size as other clients, otherwise some calls might run into an error.
> lnd: increase max message receive size for REST proxy

- docker/btcd/Dockerfile
- docker/lnd/Dockerfile
- docker/ltcd/Dockerfile
The maintainer instruction is deprecated, see:
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
Also unified the maintainer value. Please check if this is correct, because in one you used `laolu@lightning.network`, in another just `lightning.engineering` without `laolu@`, while according to some commits in the repo the email addresses of your companies' engineers seems to be `<name>@lightning.engineering`.
> Replace maintainer by label in Dockerfiles

- channeldb/db.go
- channeldb/db_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_arbitrator_test.go
- lntest/itest/lnd_test.go
- rpcserver.go
In this commit, we update the `AbandonChannel` method to also remove the
state from the countract court as well as the channel graph. Abandoning
a channel is now a three step process: remove from the open hannel
state, remove from the graph, remove from the contract court. Between
any step it's possible that the users restarts the process all over
again. As a result, each of the steps below are intended to be
idempotent. The final step will always fail once the log of the channel
arbitrator has been clead up, giving the user a signal that all channel
state has been removed.
We also update the integration test to assert that no channel is found
in the graph any longer. Before this commit, this test would fail as the
channel was still found in the graph, which can cause other issues for
an …
> rpc+cnct: update AbandonChannel to also remove cnct and channel graph state 

- lntest/itest/lnd_test.go
- lntest/itest/macaroons.go
- lntest/node.go
This PR adds a new integration test for the macaroon authentication of the gRPC interface, as mentioned in #284.
The following six scenarios are tested:
1. Expect an error when using no macaroons.
1. Expect an error when using an invalid macaroon.
1. Expect an error when trying to invoke a `write` with a read-only macaroon.
1. Expect an error when the first-party caveat `TimeoutConstraint` is not satisfied.
1. Expect an error when the first-party caveat `IPLockConstraint` is not satisfied.
1. Expect a successful response when the correct macaroon with valid first-party caveats is used.
Closes #284.
> itest: add tests for macaroon authentication

- lntest/itest/lnd_test.go
This fixes an issue that would lead to a flake during intergration
tests. Carol would start up with a outdated state and attempt to force
close the channel. At the same time she would connect to Dave,
triggering the dataloss protection. Dave would respond by force closing
the channel, and Dave transaction would in some cases have a higher fee,
resulting Carol's tx being replaced.
We fix this by suspending Dave until Carol's close tx is mined.
> lnd_test: fix race condition on simultanous force closes

- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
Fixes a typo introduced in #3499
> lnrpc: fix nanonsecond typo

- chanbackup/recover.go
- lntest/itest/lnd_test.go
While recovering a multi backup file, if for some reason one of the channels in that backup already exists, the whole recovery is aborted.
This leaves the restore in a half-finished state and a re-try or resume is not possible.
With this small fix, the same multi-file can be added again and all channels that were not imported before can now be added.
> chanbackup: continue recovery if channel already exists

- Makefile
- make/testing_flags.mk
Makes it easier to spot failures without scrolling through pages of
successful tests.
> Makefile: non-verbose unit tests

- mobile/README.md
- mobile/gen_bindings.sh
* Point to `lightninglabs` fork of falafel.
* Add more comments to build script.
> [mobile] Update readme and comments

- channeldb/channel.go
- fundingmanager.go
- fundingmanager_test.go
- lnwallet/chanfunding/assembler.go
- lnwallet/chanfunding/canned_assembler.go
- lnwallet/chanfunding/coin_select.go
- lnwallet/chanfunding/coin_select_test.go
- lnwallet/chanfunding/log.go
- lnwallet/chanfunding/wallet_assembler.go
- lnwallet/interface_test.go
- lnwallet/reservation.go
- lnwallet/wallet.go
- log.go
- mock.go
In this commit, we create a new package `chanfunding`, that introduces a number of abstractions to our funding workflow. The base implementation of the core new abstraction (`chanfunding.Assembler`), is`chanfunding.WalletAssembler`. Construction of this concrete implementation of the new interfaces involved heavily refactoring much of the code within `wallet.go`. As a result, much of the channel funding code now lives outside of the `lnwallet` package. 
The second instance of a new channel funder introduced in this PR is the `chanfunding.CannedAssembler`. This channel funder is used in the scenario wherein the "shape" of the funding output is agreed upon _outside_ the normal protocol, while the construction of the commitment transaction and so forth are carried out as normal. Instances …
> chanfunding: create new package to abstract over funding workflows

- routing/heap.go
- routing/pathfind.go
- routing/pathfind_test.go
When the (virtual) payment attempt cost is set to zero, probabilities are no longer a factor in determining the best route. In case of routes with equal costs, we'd just go with the first one found. This commit refines this behavior by picking the route with the highest probability. So even though probability doesn't affect the route cost, it is still used as a tie breaker.
> routing: improve equal cost route comparison

- docker/btcd/start-btcctl.sh
- docker/btcd/start-btcd.sh
- docker/ltcd/Dockerfile
- docker/ltcd/start-ltcctl.sh
- docker/ltcd/start-ltcd.sh
The ports exposed in the Dockerfile for Litecoin `ltcd` are wrong. It is therefore not possible to connect to the `ltcd` container from another container without this fix.
The Litecoin ports are as follows:
* Mainnet: Server `9333` and RPC `9334`
* Testnet: Server `19335` and RPC `19334`
* Simnet: Server `18555` and RPC `18556`
Those ports can easily be verified by starting the docker-container for `ltcd` (`NETWORK="testnet" docker-up -d ltcd`) and check the log (`docker logs ltcd`). 
Further, the Litecoin "segnet" has apparently been merged into the "testnet" and the network options has been changed accordingly inside the start scripts `start-ltcd.sh` and `start-ltcctl.sh` (follows the start script for `btcd`). There is not option to set network to "segnet" for `ltcd` anymore.
> docker: fix ltcd ports

- lnwire/query_short_chan_ids.go
- lnwire/query_short_chan_ids_test.go
- lnwire/reply_channel_range.go
- lnwire/reply_channel_range_test.go
This PR modifies our decoding of short channel id arrays to also assert that the decoded ids are in order for the plain encodings. We already do so for the zlib encoding, though this isn't tested directly. Here we correct the decoding make this assertion for plain encodings, and add unit tests to both `QueryShortChanIDs` and `ReplyChannelRange` to ensure that they fail with this error when presented with duplicate or unsorted channel ids for either plain or zlib.
> lnwire: assert sorted short channel ids

- mobile/gen_bindings.sh
Subservers might depend on each other (notably walletrpc depends on
signrpc) so running goimports ensures they properly import each other.
> mobile: run goimports on generated files

- fundingmanager.go
- htlcswitch/link.go
- lnrpc/routerrpc/router_backend.go
- peer.go
In this PR, we make the `SendToRoute` RPC call consistent with
all the other payment RPCs which will properly adhere to the current max
payment sat limit. This is a prep commit for the future wumbo soft cap
that will eventually land in lnd. Along the we also add some additional consistency 
checks to ensure our externally advertised `MaxHTLC` routing policy is consistent 
with this value.
> multi: make SendToRoute consistent with other payment RPC

- cmd/lncli/commands.go
SCB restore closes all open channels, which may result in significant on-chain fees. 
The current implementation of lncli create does not warn users.
We need to warn users that this is what will happen if they try to do an SCB restore, and get their affirmative consent.
> Warn user before doing SCB restore

- chanbackup/single.go
- chanbackup/single_test.go
- chanrestore.go
- lntest/itest/lnd_test.go
Replacement for/extension of #3690.
If a channel is unconfirmed, the block height of the ShortChannelID in the SCB is zero. This will lead to problems when trying to restore that channel as the spend notifier would get a height hint of zero.
To work around that problem, we add the channel broadcast height to the channel ID so we can use that as height hint on restore.
I tested this on regtest and it seems to work as expected.
> chanbackup: encode broadcast height in chan ID for unconfirmed channels

- zpay32/invoice.go
- zpay32/invoice_internal_test.go
- zpay32/invoice_test.go
This fixes an issue with bech32 decoding where inserting a specific character in the checksum might generate a valid signature albeit with a different destination node than the original invoice.
This fixes the issue by ensuring that the last tagged field has all the required data instead of silently discarding a partial field, such as a field with only a type element but no length elements.
I tested this behavior in other implementations. c-lightning and lightning-payencode (python) fail to decode invoices with a partial field. Bolt11 (node) accepts it.
This should probably be clarified in BOLT-11 so that the behavior is consistent across implementations.
For context: https://github.com/sipa/bech32/issues/51
> zpay32: Fix broken last tagged field

- chancloser.go
- channeldb/channel.go
- channeldb/channel_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_arbitrator_test.go
- lntest/itest/lnd_test.go
- lnwallet/channel.go
- peer.go
This PR adds granularity to our internal tracking of closed channels, allowing us to store closing transactions for both unilateral and cooperative closures. In the case that a channel is unilaterally closed and then later force closed, the contractcourt is now able to reliably publish both until either confirm. We also fix a race condition in the rpc interface to make the coop close status externally consistent with the coop close requests.
> republish force and coop closes on startup

- .travis.yml
- Makefile
This PR introduces staging to our travis pipeline. Currently all instances perform:
- compilation of lnd
- linting
- compilation and installation of btcd binaries
- installation of bitcoind binaries
In total this adds about 3 minutes to each of our 5 instances, resulting in roughly 12 minutes of redundant execution time. Additionally, if if a build fails to compile or lint we detect this 5 separate times, consuming precious instances from other builds.
We alleviate this by adding an initial `Build` phase, which runs a single instance performing the actions above. This has the benefit of quickly sanity checking the pr before moving on to the more expensive unit or integration test suites, and failing faster for common mistakes. It also warms up the build caches for the `Test` stage in one …
> travis: staged builds

- lnwire/channel_id.go
This PR removes an unnecessarely large 32 byte buffer in favor of a small 2 byte buffer and cleans up type conversion between uint16 and uint32 values.
> lnwire: fixing buffer size and cleaning up uint16/32 conversion

- fundingmanager.go
- peer.go
In this commit, we partially revert #3790 by leaving the current default max in flight and max htlc (chan update level) settings in place. We're planning on going wumbo sometime next year, so by leaving these in place, we ensure a more graceful update within the network, as only the end points and not the internal network needs to update. This upgrade path is more consistent with the end-to-end principle, and will allows users of the network to take advantage of the larger payments as soon as the end points are upgraded.
> peer+funding: revert link level payment clamps 

- chainntnfs/bitcoindnotify/bitcoind.go
This PR was in response to issue #3807 and it adds a space after "finished" in a log message found in lnd/chainntnfs/bitcoindnotify/bitcoind.go 
Let me know if I have done anything incorrectly as this is my first PR ever
> bitcoindnotify: add missing space in log message in bitcoind.go

- discovery/syncer.go
- discovery/syncer_test.go
In this commit we fix in a bug in `lnd` that could cause other
implementations which implement a strict version of the spec to
disconnect when trying to sync their channel graph using the gossip
query feature. Before this commit, we would embed the request to a
`QueryChannelRange` in the response, causing some clients to reject the
response as the `FirstBlockHeight` and `NumBlocks` field would be
identical for each chunk of the response.
In order to remedy this, we now properly set these two fields with each
returned chunk. Note that even after this commit, we keep our existing
behavior surrounding the `Complete` field as is. Otherwise, current
`lnd` clients which rely on this field (rather than the two
aforementioned fields) wouldn't be able to properly detect when a set of
responses to …
> discovery: properly set FirstBlockHeight and NumBlocks in responses

- log.go
Previously only the last registered logger would receive debug level changes.
> build: prevent loggers from overwriting each other.

- zpay32/invoice.go
- zpay32/invoice_test.go
Fixes #3823, this is split out from #3679 so that this can be fixed faster in master.
> zpay32: ensure feature vector is always populated

- channeldb/invoice_test.go
- channeldb/invoices.go
- channeldb/migration_01_to_11/migration_09_legacy_serialization.go
- channeldb/migration_01_to_11/migration_10_route_tlv_records.go
- channeldb/migration_01_to_11/migrations.go
- channeldb/migration_01_to_11/migrations_test.go
- channeldb/migration_01_to_11/payments.go
- channeldb/migration_01_to_11/route.go
- channeldb/payments.go
- channeldb/payments_test.go
- htlcswitch/hop/payload.go
- htlcswitch/hop/payload_test.go
- invoices/interface.go
- invoices/invoiceregistry_test.go
- invoices/update.go
- lnrpc/routerrpc/router_backend.go
- lnrpc/routerrpc/router_backend_test.go
- record/custom_records.go
- routing/pathfind.go
- routing/payment_session.go
- routing/route/route.go
- routing/router.go
- rpcserver.go
When a payment with custom records is made, path finding wasn't informed of the tlv requirement for the final hop.
This PR also contains a type change that prepares for counting payload bytes during path finding. For that we need to have the custom records available in `findPath` in an easy to read format.
> multi: fix custom record payment

- channeldb/payments.go
- channeldb/payments_test.go
- lnrpc/routerrpc/router_backend.go
- record/custom_records.go
- rpcserver.go
This PR adds a sanity check right before serializing the custom records hop data. It should never happen that this check fails because we check custom records at every entry point. Only because the consequences of a bad record slipping through could be bad, we think that a sanity check here is justified.
> channeldb: custom records sanity check

- cmd/lncli/invoicesrpc_active.go
Make `lncli addholdinvoice` send value in millisatoshi (ValueMsat introduced by commit fcbf1bc07a032f1f95ecf64ba9a216dd229dfb59). 
New flag `--amt_msat` is introduced for this purpose, while `--amt` and unnamed command-line argument are still supposed to be in satoshi for backward compatibility.
> lncli addholdinvoice: allow specifying msat with --amt_msat

- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
Block padding is added for `SendPayment`, but if some applications decide to manually roll their payment loop using `QueryRoutes` in combination with `use_mc`, they may run into this issue.
> lnrpc: clarify block padding requirement for QueryRoutes

- feature/deps.go
- feature/deps_test.go
- feature/manager.go
- lnwire/features.go
- peer.go
Split off from #3679
This PR adds a new `feature.ValidateDeps` method to the `feature` package, which can be used to ensure that all transitive dependencies of a given feature are advertised in the feature vector. With base amp, for example, the dependency chain is `option_mpp` -> `option_payment_addr` -> `option_onion_tlv`. When validating, we want to fail if `option_mpp` is set but either of two dependencies are not. As more feature bits are added, these chains could become several layers deep. Things like AMP or extended gossip queries will continue to add to these constraints, and this gives a simple way of expressing and validating these relations.
We then add this transitive validation to remote init features and when parsing BOLT11 invoices, additionally verifying that the payment …
> feature: add transitive feature bit validation

- lnd.go
- mobile/bindings.go
- rpcserver.go
This allows the caller to know when lnd is ready to accept RPC calls,
which is important for mobile applications where everything happens in
process.
Fixes #3614
> [mobile] make Ready signal for custom listeners

- channeldb/channel.go
This PR is a preparation for the addition of the anchor resolver. By keeping the open channel data around, we can avoid persisting the anchor resolutions in the database. This simplifies the implementation and reduces the number of execution paths (especially after a restart of `lnd`).
It also opens up the possibility to convert other resolvers to exist in memory only, although this is a long term goal - if it is a goal at all.
In general, having the channel data available allows for more flexibility in implementations.
> cnct: keep open channel data after channel commitment tx confirms

- chanfitness/chanevent.go
- chanfitness/chaneventstore.go
- chanfitness/chaneventstore_test.go
- rpcserver.go
This PR fixes a bug in the `chanfitness` subsystem which would not set the open time for channels with peers that are offline at startup. This open time (renamed to monitored since in this PR) is important because it indicates how long we have been monitoring the remote peer's offline status. 
Previously, open time would be set on the first event for a channel. For peers that are online at startup, this event would be immediately added to reflect the current state of the peer. Channels with peers that remain offline and do not have an event will not have their opened time set. 
This PR fixes this by setting `monitoredSince` for all channels on startup. 
It also switches `chanfitness` over to querying by channel outpoint, as this is preferred in lnd. 
This bug was first picked up in #3741 …
> Bugfix: Chanfitness open time for offline peers

- chainregistry.go
- contractcourt/commit_sweep_resolver.go
- contractcourt/commit_sweep_resolver_test.go
- contractcourt/interfaces.go
- lnrpc/walletrpc/walletkit_server.go
- server.go
- sweep/backend_mock_test.go
- sweep/interface.go
- sweep/sweeper.go
- sweep/sweeper_test.go
- sweep/tx_input_set.go
- sweep/tx_input_set_test.go
- sweep/txgenerator.go
- utxonursery.go
- utxonursery_test.go
This PR enables the sweeper to sweep inputs that are positively-yielding, but by itself wouldn't reach the dust limit for the sweep transaction output value at the chosen fee rate.
They way to deal with this is to attach additional wallet input(s) to bring up the output value of the transaction.
This is a preparation for sweeping anchor outputs that are too small to reach the dust limit of the sweep tx output.
There are also a few commits in this PR that aren't strictly necessary for the functionality that this PR adds, but are included anyway to prevent touching the code again in the follow-up.
Next step after this PR is to add forced sweeping of negatively yielding inputs.
> sweep: add wallet inputs to reach dust limit

- cert/selfsigned.go
- lnd.go
- mobile/bindings.go
- mobile/gen_bindings.sh
- mobile/sample_lnd.conf
- rpcserver.go
This adds initial macaroon support for mobile lnd.
Currently the admin macaroon is used, in the future we can be more granular, even let the applications supply macaroons themselves.
Builds on https://github.com/lightningnetwork/lnd/pull/3775
Depends on
> [mobile] mobile macaroons support

- rpcserver.go
Require peers read access to subscribe to peer events
> lnrpc: Add macaroon entry for peers subscription

- go.mod
- go.sum
- routing/payment_lifecycle.go
- routing/route/route.go
- routing/router.go
- routing/router_test.go
Depends on https://github.com/lightningnetwork/lightning-onion/pull/45
A follow up pr https://github.com/lightningnetwork/lnd/pull/3841 will also limit path finding to the maximum payload size of 1300 bytes.
Fixes https://github.com/lightningnetwork/lnd/issues/3712
> routing: send to route max hops check

- lntest/itest/lnd_test.go
Since CSV locked outputs specifies the first block where they are
allowed to be included, they can actually be added one block earlier
into the mempool.
This led to a flake, where the sweep tx was already in the mempool at
the time we mined the last block, causing the next mempool check to
fail.
Fixes 
```
--- FAIL: TestLightningNetworkDaemon/channel_force_closure (49.83s)
lnd_test.go:100: Failed: (channel force closure): exited with error: 
*errors.errorString failed to get sweep tx from mempool: wanted 1, found 0 txs in mempool: []
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:3266 (0xd993f9)
testChannelForceClosure: t.Fatalf("failed to get sweep tx from mempool: %v", err)
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go: …
```
> lnd test: fix csv mempool sweep time

- channeldb/invoice_test.go
- channeldb/invoices.go
- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
This pull request is a partial fix for issue lightningnetwork#1404 where part of the problem comes from
not being able to filter out expired invoices due to those not being canceled 
(fixed in PR lightningnetwork#3694) while also having a misleading definition of what pending invoice
state means.
The PR changes the meaning of the `pending_only` flag in `listinvoices`
RPC to list invoices that are either in `ContractOpen` or `ContractAccepted`
state. Previously when the `pending_only` flag was set the `listinvoices`
RPC returned all invoices that are not settled which equals to invoices in `ContractOpen`, `ContractAccepted` or `ContractCanceled` state.
> channeldb+invoices: fix what pending invoice means in ChannelDB

- cmd/lncli/main.go
- lncfg/address.go
WithDialer is deprecated, use WitchContextDialer instead.
> [trivial] lncfg+lncli: replace WithDialer->WitchContextDialer

- autopilot/graph.go
This PR fixes an issue that happens when adding a new channel edge
between two nodes in a memChannelGraph. Originally a channel edge held a
node value which made the graph different when iterating from the two
endpoints of an edge. This is simply fixed by holding pointers instead.
> autopilot: fix memChannelGraph channel edge addition

- zpay32/invoice.go
- zpay32/invoice_test.go
This commit updates the BOLT11 test vectors to use the updated versions
from the spec (with TLV bit set). This also pointed out that the
ordering was inconsistent with the spec, in that the payment secret
should be serialized before the feature vector.
This uses the updated test vectors stemming from [this comment](https://github.com/lightningnetwork/lightning-rfc/pull/719#discussion_r358910138)
> zpay32: update spec test vectors, write features last

- lnrpc/routerrpc/router.pb.go
- lnrpc/routerrpc/router.proto
- lnrpc/routerrpc/router_backend.go
- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
Alternative to #3859 
Primary distinction is that `nil` or empty features will fall back to using the graph, rather than
needing an extra bool to override in the case of empty features. In practice, it seems unlikely that one would need to override with empty features since most things going forward will at least be built on `var_onion_optin`.
> routerrpc: allow dest_features graph fallback

- routing/result_interpretation.go
- routing/result_interpretation_test.go
Fixes an off by one error that skipped assigning a success pair. Added a test that previously failed because of this bug.
> routing: fix gap in result interpretation

- routing/pathfind_test.go
This commit fixes a potential bug in our test harness, by ensuring that
the constructed node policies are configured _after_ sorting. Currently
the node pubkeys are sorted, but additional parameters (max htlc,
disabled, etc) are applied using the unsorted policies.
Most of the constructors used today use the symmetric channel
constructor, so this shouldn't cause an issue with the majority of our
tests. We recently introduced an asymmetric channel constructor for
which this could have been an issue, however, no known issues were
discovered.
Lastly, we remove the direction from the configuration altogether, and
derive it purely from the final sorting of the pubkeys.
> routing/pathfind_test: construct sorted edge policies

- lnwallet/interface_test.go
You can verify they are not running by manually running `make unit case=TestLightningWallet pkg=lnwallet` and verifying they all take 0s to execute.
This also fixes a broken test in the TestLightningWallet test suite.
> Re-enable TestLightningWallet tests

- cmd/lncli/autopilotrpc_active.go
This commit fixes a typo in the NAME descriptor for `lncli autopilot query`. Prior to this commit:
```
$ lncli autopilot query -h
NAME:
lncli autopilot query - Query the autopilot heuristcs for nodes' scores.
USAGE:
lncli autopilot query [command options] [flags] <pubkey> <pubkey> <pubkey> ...
OPTIONS:
--ignorelocalstate, -i  Ignore local channel state when calculating scores.
```
The word "heuristics" is misspelled as "heuristcs". After this commit:
```
$ lncli autopilot query -h
NAME:
lncli autopilot query - Query the autopilot heuristics for nodes' scores.
USAGE:
lncli autopilot query [command options] [flags] <pubkey> <pubkey> <pubkey> ...
OPTIONS:
--ignorelocalstate, -i  Ignore local channel state when calculating scores.
```
> Fix typo in "query" rpc for autopilot.

- lntest/harness.go
- lntest/itest/lnd_test.go
- lntest/node.go
To use the node and network harnesses from the lntest package in other projects, it is necessary to fix the macaroon path to have all macaroons in the same directory (without this fix, the admin, readonly and invoice macaroon are in the `data/` directory of lnd while all the sub-server macaroons are in the `data/chain/bitcoin/regtest/` folder).
Also it is useful if we can specify the location of the `lnd-itest` binary so we don't have to use the same folder structure/depth in other projects.
Finally, to get access to a node's data directory, we need to export the node's config struct.
> itest: make harnesses usable in external projects

- lntest/node.go
This changes the HarnessNode structure to hold onto the client grpc
connection made during startup so that it can close it during shutdown.
This is needed because the grpc.Dial function spins a new goroutine that
attempts to maintain an open connection to the target endpoint and
without calling Close() in the connection while shutting down the node
we leak this goroutine to the rest of the tests.
The easiest way to verify this is the case is by running an interactive profile of the test binary during `make itest` and noticing a large number of goroutines stuck in the grpc lib.
> lntest: Don't leak node's grpc conn

- routing/notifications.go
routing: clean up locking on topology change
This is a trivial code clean up to avoid acquiring the reader lock twice. Fixes a race condition where the topologyClients could have changed while releasing the reader lock resulting in a wrongly logged count or worst case, return from the function.
> routing: clean up locking on topology change

- chanfitness/chaneventstore.go
- chanfitness/chaneventstore_test.go
Uptime calculations rely on an initial online event to determine peer state which was removed in #3799. The change was appropriate for channel that are offline at start (since an event will be recorded if the peer comes online), but it introduces a race between peers coming online and existing channels being added to the store. If the peer comes online before the channel is added to the store, no online event is added (and the channel with an online peer appears to be offline). This change re-adds the channel online event in `addChannel` so that channels with already online peers have an initial online event.  
This edge case of needing a first online event seems unavoidable, and buggy, so I am going to follow up with a refactor of the unit tests to better cover this code. The issue here …
> chanfitness: Bugfix save initial peer online event

- discovery/sync_manager_test.go
- discovery/syncer.go
- discovery/syncer_test.go
- lnwire/query_channel_range.go
- peer.go
In this PR, we make a series of changes to properly adhere to the specification with the `QueryChannelRange` and `ReplyChannelRange` messages. Previously, we'd look at the `Complete` field of a `ReplyChannelRange` message to determine if we had received all replies to a query. This isn't the use of the field however, and instead we should be inspecting the block range of each `ReplyChannelRange` message to determine this.
One of the main takeaways that motivates most of the changes outlined in this PR is the following:
```
- MUST respond with one or more `reply_channel_range` whose combined range
cover the requested `first_blocknum` to `first_blocknum` plus
`number_of_blocks` minus one.
```
Due to the large number of nodes out there that rely on the previous mechanism for graph sync, we …
> discovery: use block ranges from ReplyChannelRange to determine end marker

- go.mod
- go.sum
- routing/router.go
In this PR, we update the routing package to use the new
`sphinx.NewOnionPacket` method. The new version of this method allows us
to specify _how_ the packet should be filled before it's used to create
a mix-header. This isn't a fundamental change (totally backwards
compatible), instead it plugs a privacy leak that may have revealed to
the destination how long the true route was.
> routing: use updated sphinx.NewOnionPacket method

- feature/required.go
- peer.go
- routing/pathfind.go
- routing/pathfind_test.go
- watchtower/wtwire/init.go
- watchtower/wtwire/init_test.go
- zpay32/invoice.go
- zpay32/invoice_test.go
This PR brings us inline with recent modifications to the [spec](https://github.com/lightningnetwork/lightning-rfc/pull/723), that
say we shouldn't pay nodes whose feature vectors signal unknown required
features, and also that we shouldn't route through nodes signaling
unknown required features.
Currently we assert that invoices don't have such features during
decoding, but now that users can specify feature vectors via the rpc
interface, it makes sense to perform this check deeper in call stack.
This will also allow us to remove the check from decoding entirely,
making decodepayreq more useful for debugging.
We also fix one of the test vectors which had been incorrectly copied
from https://github.com/lightningnetwork/lightning-rfc/pull/719.
Feature bit 9 was missing from the current …
> routing: ignore unknown required features in pathfinding

- docker/README.md
- docker/btcd/start-btcctl.sh
- docker/docker-compose.ltc.yml
- docker/ltcd/start-ltcctl.sh
https://i.gifer.com/52an.gif
https://github.com/lightningnetwork/lnd/issues/2509
build and start both `lnd` and the `btcd` backend with a single command `docker-compose up`.  In order to enable docker-compose to bring up the services, I removed service definitions that aren't needed for running the environment.  The docs have been updated with new instructions for how to run `btcctl` now that it's not a separate service.
Also, this PR Moves `ltc` to a separate docker-compose file.  A future PR can allow `ltc` to be brought up with a single command and inherit from `docker-compose.yml`.
> docker-compose up

- cmd/lncli/commands.go
Clarifies that last_hop is not the destination, but the penultimate node
in the path, i.e. the last intermediary.
> lncli: improve last_hop help message

- invoices/invoiceregistry.go
- rpcserver.go
This PR:
* Does a pre-check for key send htlc expiry values to prevent empty invoices filling up the database.
* Increases the default final cltv delta that payment RPCs use so that a receiver running `lnd` won't reject it. This allows key send payments via `lncli` without specifying the `final_cltv_delta` flag.
> invoices: streamline key send cltv delta picking and validation

- channeldb/invoice_test.go
- channeldb/invoices.go
This PR removes channeldb.FetchAllInvoices which was only used in tests to prepare expectation sets. The refactor also changes expectation set creation to be independent from the DB.
> channeldb: remove FetchAllInvoices which was test only and unused

- lnd.go
- mobile/bindings.go
This PR fixes a regression from #3783, where TLS support was added on mobile, but we forgot to add the TLS credentials also to the wallet unlocker client.
Fixes #3905
> [mobile] Set walletunlocker TLS credentials

- cmd/lncli/commands.go
With the introduction of custom record sending and receiving, it became possible to attach arbitrary data to a payment. One obvious use case is attaching a human-readable message to a payment. Especially in the case of spontaneous key send payments, this can give the receiver some context on the payment.
For example: tipping. Usually people sending a tip would want to include some information on who they are or what the tip is for. For Lightning this may be even more desired than for other payment methods, because payments are anonymous by default. 
Attaching and retrieving the message was already possible before, but this PR makes it easier to do so by introducing an additional `lncli` flag `--data` to attach one or more custom records:
`lncli sendpayment -d …
> lnrpc+lncli: add send support for custom data records

- htlcswitch/failure.go
- htlcswitch/failure_detail.go
- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- lnrpc/routerrpc/router_server.go
- routing/mock_test.go
- routing/router.go
- routing/router_test.go
This PR is change 1 of 4 proposed to add a htlc event notifier to lnd.
1: This PR
2: #3844
3: #3781
4: #3848 
--------------
This PR changes the structure of the errors that we use within htlcswitch. This change is necessary for introducing metadata (which should not be exposed on the wire) to  failures that occur within the switch.
- The `ClearTextError` interface is introduced to represent all of the non-opaque errors that the switch handles. 
- `ForwardingError` is updated to implement this interface, and covers the case where receive an error from a peer along the route of one of our own payments
- A `LinkError` implementation of the interface is added to cover the case where we fail a send/receive/forward on our incoming/outgoing link
- A `FailureDetail` enum that adds metadata to …
> [htlcnotifier 1/4]: Introduce Internal Errors

- cmd/lncli/commands.go
Changes docs to specify that `sendcoins` can accept base58 _or_ bech32. Previously the docs stated only base58 was permitted.
Fixes #3883
> lncli: fix sendcoins docs, allow base58 or bech32 addrs

- routing/errors.go
- routing/router.go
This shortcut does not work when the destination is a private node. We also don't have this shortcut for regular payments. This commit aligns the behavior between SendPayment and QueryRoutes.
> routing: remove path finding shortcut

- mobile/gen_bindings.sh
Dials with "localhost" to be compatible with the old TLS certificates: https://github.com/lightninglabs/falafel/commit/65b58cc372b686d92c1ec8730629cc8f5e7c508d
> mobile: bump falafel dep to 0.7

- build/release/release.sh
In this commit, we change the release script slightly to return the
latest tag if there're multiple tags at head. Otherwise the release
script will fail if our final tag is at the same commit as the prior
release candidate tag.
> build/release: update release script to handle multiple tags at head

- invoices/update.go
To prevent log lines showing "unknown" as the fail reason
> invoices: add missing String() cases

- rpcserver.go
This PR fixes various cases of missing payments and potential deadlocks within the bidirectional `sendPayment` in the `rpcserver`. See commit messages for detailed info.
> rpcserver: fix error handling in bidirectional sendPayment

- mobile/bindings.go
Since spaces where trimmed only after checking for empty strings, an
empty flag '-- ' would be passed along to lnd. Intead we trim first to
properly ingore such flags.
> [mobile] trim arg spaces before comparison

- channeldb/channel_test.go
- channeldb/db.go
- channeldb/invoice_test.go
- channeldb/invoices.go
- channeldb/options.go
- invoices/invoiceregistry_test.go
- invoices/test_utils_test.go
This PR fixes a leftover of the mpp invoice registry pr #3415. There we took a shortcut to expose `Now` as a public field on the database in order to unblock the stack of dependent prs. This is now converted to a proper `clock.Clock` dependency.
> channeldb: inject clock into database

- channeldb/channel.go
- channeldb/channel_test.go
- channeldb/db_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
This PR persistently stores updates received from the remote party until we've produced a signature that includes these updates. Previously those updates were only stored in memory and dropped across restarts. This lead to the production of an invalid signature and channel force closure.
Fixes #3822 
Fixes #3126
> htlcswitch+lnwallet+channeldb: invalid sig fix

- go.mod
- go.sum
- keychain/interface_test.go
- walletunlocker/service_test.go
With this PR we crank down the scrypt options used by the `btcwallet` to speed up unit tests, especially when running with the race detector.
Results on my machine **before** the change (run with `go clean -testcache && go test ./keychain -race && go test ./walletunlocker -race`):
```
ok      github.com/lightningnetwork/lnd/keychain        150.092s
ok      github.com/lightningnetwork/lnd/walletunlocker  123.689s
```
**After** the change:
```
ok      github.com/lightningnetwork/lnd/keychain        3.834s
ok      github.com/lightningnetwork/lnd/walletunlocker  6.728s
```
> keychain+walletunlocker: use fast scrypt options for unit tests

- invoices/invoice_expiry_watcher.go
- invoices/invoice_expiry_watcher_test.go
- invoices/invoiceregistry.go
This PR intends to fix slow first startup time when there are many
invoices that need to be canceled. The slowdown is caused by a combination
of adding invoices to the expiry watcher one-by-one and slow
cancellation. Due to slow cancellation and the unbuffered channel which
we use to pass invoices to the expiry watcher blocks the registry.
With this fix we'll instead batch add invoices to the expiry watcher and
thereby won't block the registry startup.
> invoices: fix slow startup with many expired invoices

- routing/missioncontrol.go
- routing/missioncontrol_test.go
- routing/result_interpretation.go
- routing/result_interpretation_test.go
Previously we only penalized the outgoing connections of a failing node. This turned out not to be sufficient, because the next route sometimes went into the same failing node again to try a different outgoing connection that wasn't yet known to mission control and therefore not penalized before.
> routing: penalize node-level failures harder

- lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
To ensure lnd is able to pick up an on-chain preimage properly after a
restart, we suspend Alice and check that the payment is listed correctly
as succeeded after a restart.
Builds on #3190
> [integration tests]: restart Alice after on-chain settle

- brontide/noise.go
- fuzz/brontide/fuzz_utils.go
- fuzz/brontide/random_actone.go
- fuzz/brontide/random_actthree.go
- fuzz/brontide/random_acttwo.go
- fuzz/brontide/random_init_decrypt.go
- fuzz/brontide/random_init_enc_dec.go
- fuzz/brontide/random_init_encrypt.go
- fuzz/brontide/random_resp_decrypt.go
- fuzz/brontide/random_resp_enc_dec.go
- fuzz/brontide/random_resp_encrypt.go
- fuzz/brontide/static_actone.go
- fuzz/brontide/static_actthree.go
- fuzz/brontide/static_acttwo.go
- fuzz/brontide/static_init_decrypt.go
- fuzz/brontide/static_init_enc_dec.go
- fuzz/brontide/static_init_encrypt.go
- fuzz/brontide/static_resp_decrypt.go
- fuzz/brontide/static_resp_enc_dec.go
- fuzz/brontide/static_resp_encrypt.go
This PR adds fuzzing harnesses for all three acts of the brontide handshake.  Ideally, we would fuzz other things as well.  The harnesses are located in the `fuzz/brontide` directory.  The fuzzers should always fail the brontide MAC checks, barring some sort of bug.  
There are some limitations with go-fuzz compared to something like AFL: go-fuzz has no "persistent mode" where the target program isn't restarted between fuzzing runs.  This means that we can't properly fuzz encryption+decryption thousands of times and trigger the key rotation from occurring.  I have never used it before, but I think something like [smat](https://github.com/mschoch/smat) could be used for persistent fuzz runs.
TODO:
> fuzz: adding fuzz harnesses for acts 1-3, encryption+decryption

- record/amp.go
- record/record_test.go
- routing/route/route.go
- routing/route/route_test.go
This PR adds the currently proposed AMP record from https://github.com/lightningnetwork/lightning-rfc/pull/658, and
implements the sanity checks when encoding a particular `route.Hop`. For now, this could will
remain dead until a number of other components are in place, but this serves as a starting point to
begin implementing the remainder of the proposal that depends on these primitive definitions
before ultimately enabling it externally.
Related to #3939.
> record+routing/route: add AMP record

- config.go
- htlcswitch/failure_detail.go
- htlcswitch/link_test.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- server.go
This PR adds some protection against circular liquidity attacks, as described in #3771. 
Two types of protection against circular routes are identified:
1. Same channel circles: disallow htlcs with the same incoming and outgoing channel ID
Update: after discussion, decided to only implement (1), which simplifies the PR.
~2. Pair channel circles: disallow forwarding of htlcs over a pair of channels when a htlc has already forwarded a htlc with that hash in the opposite direction~
Context for not implementing (2):
1. Effect on base MPP: base MPP uses duplicate htlcs, which are indistinguishable from circular routes (in almost all cases, except for payments which reverse over the same channel pair)
2. Pair channel effectiveness: pair channel protection is probably quite easy to get around, …
> htlcswitch: Disallow circular routes on same channel

- lnd.go
Linter is failing for `openTime := time.Now().Sub(startOpenTime)`, update it to use `time.Since` to appease the lintergods.
> lnd: fix gosimple linter failure

- invoices/invoiceregistry.go
- invoices/update.go
Fixes a possible deadlock caused by sending on a channel inside a lock.
> invoices: fix htlc timer deadlock

- channeldb/channel_test.go
- channeldb/db.go
- channeldb/db_test.go
The first commit is just a change to tests, replacing boiler plate channel setup with a default channel which can be overridden with functional options. 
In this PR, the booleans in `fetchChannels` are replaces with optional filters. This change allows us to decrease the number of calls we need to fetch certain sets of channels (`FetchAllOpenChannels` and `FetchWaitingCloseChannels`) and generally allows for more flexibility in channel queries. 
This is also a first step in investigating the addition of a `RequiresExport` flag that would allow channels to remain in the open channels bucket after close so that we can export accounting data. If we do go with this approach, we would need to filter these channels out somewhere (so they are not included with open channels calls), and this PR …
> channeldb: Replace fetchChannels pending/waiting bools with optional filters

- contractcourt/htlc_incoming_contest_resolver.go
- contractcourt/htlc_incoming_resolver_test.go
- contractcourt/interfaces.go
- contractcourt/mock_registry_test.go
- htlcswitch/failure.go
- htlcswitch/failure_detail.go
- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/mock.go
- htlcswitch/packet.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
- invoices/resolution.go
- invoices/resolution_result.go
- invoices/update.go
This PR is change 2 of 4 proposed to add a htlc event notifier to lnd.
~1: #3843~
2: This PR
3: #3781
4: #3848 
--------------
Some refactoring is done in the invoice registry:
- The `HtlcResolution` struct is replaced with an interface implemented by settle and fail resolutions.
- Resolution results are split up into separate enums for settles, fails and accepts
- The callback we use in `NotifyExitHopHtlc` is updated to return a `HtlcResolution` rather than just a resolution result so that we do not need to switch on enum type in multiple places
- A side effect of this is that the resolution result for accepts cannot be logged by the caller because a nil resolution is returned. Temporary logging is added to surface these accept results, with the intention of future refactors introducing …
> invoiceregistry+htlcswitch: Introduce resolution types and add link errors

- lnrpc/signrpc/signer_server.go
When the InputIndex is not 0, the index is not currently copied into the
underlying SignDescriptor structure and the signature generated is not
valid.
> Copy InputIndex into the underlying SignDescriptor struct

- routing/graph.go
- routing/integrated_routing_context_test.go
- routing/integrated_routing_test.go
- routing/mock_graph_test.go
- routing/pathfind.go
- routing/router.go
- routing/unified_policies.go
Adds an integrated routing test of probability extrapolation for untried channels. 
The difference between this test and the existing pathfinding tests, is that this test focuses on the feedback loop from result interpretation via mission control updates and probability estimation back to pathfinding. Improvements like probability extrapolation were previously only validated by reasoning, while this setup makes it possible to assert the improvement in a test and guard it for the future.
> routing/test: integrated routing test

- sweep/bucket_list.go
- sweep/sweeper.go
- sweep/sweeper_test.go
Allows certain sweep inputs to be kept in separate transactions at all times. This is a preparation for anchor outputs. Before the commitment tx confirms, there are three potential anchors that can be cpfp'ed. We want to cpfp them all, but if done in the same transaction, the transaction would guaranteed to be invalid.
Exponential backoff would eventually get the txes published too, but having exclusive groups makes the process faster.
> sweep: add exclusive groups

- go.sum
Ran `go mod tidy` to get rid of old dependencies in `go.sum` that were upgraded in #3927.
> gosum: remove old btcwallet dependencies

- lnwallet/channel.go
- lnwallet/channel_test.go
The unit test TestNewBreachRetributionSkipsDustHtlcs triggered a state
transition from Bob, even though it was Alice that had added the HTLCs.
This is wrong since it will lead to Bob still owing Alice a commitment,
which is not accounted for in the unit tests.
We add a sanity check that the add heights has been set for all entries
found in the logs, and return an error otherwise. This won't happen
during normal operation, but it does reveal the mistake in the unit
test, which is fixed by making Alice trigger the transition.
In addition we resolve a long standing TODO by removing a (purposeful)
panic in the channel state machine. Old version of lnd had a bug that
could lead to the parent entries being lost during channel restore. A
panic was added to get to the bottom of if.
This is now …
> Fix TestNewBreachRetributionSkipsDustHtlcs incorrect state transtion

- config.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_arbitrator_test.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- server.go
- test_utils.go
This PR main goal is to reduce force closed channels in a mobile node.
In case of an outgoing pending htlc, a forwarding node needs to make sure it is either cancelled or resolved on-chain after timeout.
While for an online node it is more likely that its counterpart peer will send `update_fail_htlc` before it will need to use the timeout transaction, in mobile node it is a bit different.
By its nature, mobile node is most of the time not online, which in case of pending htlc it is likely to miss the time slot for getting the `update_fail_htlc` and when comes online it will close the channel on-chain.
While in a forwarding payment the timeout transaction should be used immediately to eliminate the risk in loosing funds, it looks to me that in an initiated payment it is not risky to keep …
> contractcourt: keep channels with timed-out initiated htlcs.

- docker/README.md
This PR fixes a small typo in the docker docs.
> docs: add terminal symbol to docker readme example commands

- lnwallet/channel.go
- lnwallet/channel_test.go
This PR clamps down the number of received HTLCs to `MaxAcceptedHTLCs`.
> lnwallet: limit received htlc's to MaxAcceptedHTLCs

- htlcswitch/htlcnotifier.go
- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- htlcswitch/test_utils.go
- peer.go
- server.go
This PR is change 3 of 4 proposed to add a htlc event notifier to lnd.
1: #3843
2: #3844
3: This PR
4: #3848 
Since the PR is dependent on the preceding PRs, it has been rebased on #3844.
**Only the last 9 commits are eligible for review.**
--------------
This PR adds a `htlcnotifier` to the `htlcswitch` which provides a stream of notifications with the following types of events:
- Forwards: when we forward a HTLC or initiate a send from our node
- Forward Failures: when a HTLC we forwarded fails down the line
- Settles: when a HTLC we forwarded is settled, or we receive a payment
- Link Failures: when we fail a HTLC on our incoming or outgoing link
> [htlcnotifier 3/4]: Add HTLC Notifier

- htlcswitch/link.go
- htlcswitch/link_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
This PR makes the balance calculation take into account the extra fee needed to be paid by the initiator when sending non-dust HTLCs. This is a case that could previously be hit both if we as an initiator couldn't pay the HTLC fee, and when the remote (as initiator) couldn't pay to add our HTLC to the commitment.
This PR mitigates this by in those cases reporting a lower number, ensuring the pathfinding algorithm won't attempt to use the channel in such cases. 
Fixes #3787.
> lnwallet: Make available balance HTLC fee aware

- .travis.yml
By default, Travis-CI does `git clone --depth=50` which limits the
repo to the last 50 commits. Because we do linting against an old
commit, it cannot be found any more. We remove the limit completely
to not run into this problem again.
> travis: remove git clone depth limitation to fix linter

- go.mod
- go.sum
In this commit, we update to the latest `btcwallet` version that
includes a fix for how we perform rescans. Before this commit, the
wallet would load ALL the created keys into the wallet to perform a
rescan. This is unnecessary, as many of the keys we create are actually
used in contracts, so the wallet can't spend them directly anyway.
For neutrino nodes, this would've caused them to attempt o match more
items in the filter than necessary, possibly resulting in an increased
number of false positive block fetches.
> build: udpate to latest btcwallet version with rescan addr fix

- cmd/lncli/commands.go
The listinvoices `--reversed` flag is changed to `--paginate-forwards` to fix #3986.
Currently, if one likes to start to paginate from the beginning of the invoices history
one has to set `--reversed=False`, which is not very intuitive. Otherwise the 
`--reversed` flag has no effect at all, as it is set by default. The downside of the change
is that it diverts from the grpc API, where the reversed flag still is present.
If this change is wanted I would apply it also to the payments listing in PR #3960.
> lncli: change listinvoices reversed flag to paginate-forwards

- README.md
The current link in the README for slack is expired. This link was updated in https://github.com/lightningnetwork/lnd/issues/4005.
This PR updates the docs to the correct url
> change slack link from invite to lightning.engineering

- chancloser.go
This fixes a race during channel closing, where the last channel state
update was still not finished when we set the channel close bit in the
database. This lead to a flake during integration tests, where the last
state update would not finish, and the channel wasn't closes
successfully.
We fix it by first unregistering the channel, making sure it is removed
fully from the link before doing the db modification.
Fixes 
```
--- FAIL: TestLightningNetworkDaemon (74.86s)
lnd_test.go:15365: Running 61 integration tests
--- FAIL: TestLightningNetworkDaemon/route_fee_cutoff (51.38s)
lnd_test.go:103: Failed: (route fee cutoff): exited with error:
*errors.errorString unable to close channel: timeout reached before channel close initiated
/github.com/lightningnetwork/lnd-worktree/lntest/itest/lnd_te …
```
> chancloser: unregister channel before db modification

- sample-lnd.conf
removed wtclient.private-tower-uris due it was replaced by wtclient.active
> sample-lnd.conf: remove deprecated wtclient option

- channel_notifier.go
- channelnotifier/channelnotifier.go
- fundingmanager.go
- fundingmanager_test.go
- lntest/itest/lnd_test.go
- rpcserver.go
Fixes #3816.
Currently there is a discrepancy between the backups obtained through the gRPC call and the content of the automatically created `channel.backup` file. The RPC backups do contain pending channels while the backup file does not.
This PR aims to fix that discrepancy.
> chanbackup: update on-disk backup file with unconfirmed channels

- README.md
- docs/safety.md
This PR adds a document that describes the security/safety mechanisms that are implemented in
`lnd` and a list of established best practices concerning the safe operation of an `lnd` node.
> doc: add Operational Safety Guidelines document

- input/size.go
- input/size_test.go
- lnwallet/size_test.go
This PR corrects a bug in TxWeightEstimator that could result in
underestimations for transactions involving NestedP2WPKH and NestedP2WSH
inputs. The scriptSig data push is now accounted for in a proper size
constant, and the input count is now incremented in both. This would
only be detectable in the event that the number of non-nested inputs and
the total number of inputs straddle the discontinuities in the
CompactSize encoding, e.g. 253, 2^16-1, or 2^32-1.
Fortunately this doesn’t impact any critical LN fee calculations (that could result
in invalid commitment signatures and a force close) since we don’t use these input
types.
> input/size: correct NP2WKH and NP2SH input count

- config.go
- docs/configuring_tor.md
- server.go
- tor/README.md
- tor/controller.go
Tested and confirmed locally that all three authentication methods (`SAFECOOKIE`, `HASHEDPASSWORD`, `NULL`) work as intended. `SAFECOOKIE` remains as the default unless a control password is provided.
Replaces https://github.com/lightningnetwork/lnd/pull/2548.
> server+tor: add support for Tor HASHEDPASSWORD authentication method

- .github/pull_request_template.md
- .travis.yml
- Makefile
- lnrpc/.clang-format
- lnrpc/README.md
- lnrpc/chainrpc/chainnotifier.pb.go
- lnrpc/chainrpc/chainnotifier.proto
- lnrpc/invoicesrpc/invoices.pb.go
- lnrpc/invoicesrpc/invoices.proto
- lnrpc/routerrpc/router.proto
- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
- lnrpc/signrpc/signer.pb.go
- lnrpc/signrpc/signer.proto
- lnrpc/walletrpc/walletkit.proto
- lnrpc/watchtowerrpc/watchtower.pb.go
- lnrpc/watchtowerrpc/watchtower.proto
- lnrpc/wtclientrpc/wtclient.proto
- scripts/install_travis_proto.sh
Replaces/continues #3112/#3110 by @cfromknecht.
This PR installs/compiles the `protoc`, `protobuf`, `genproto` and `grpc-gateway` libraries/binaries in the exact version as specified in `lnrpc/README.md` on Travis and then compiles all `.proto` files.
If the git worktree becomes dirty in the process, that means the protos weren't compiled correctly or with a wrong version and the CI build is failed.
The build process also makes sure the protos are properly formatted, using `clang-format` with custom rules (`lnrpc/.clang-format`) to do so.
Fixes #3094
> travis: format, compile and verify protos

- Makefile
There are different versions of clang-format being installed on
different versions of ubuntu that apparently produce different
results when formatting the proto files. This is likely too much
of a hurdle for new contributors to also manually install the
correct version of a command line tool just to format stuff.
> Makefile: don't format proto on Travis

- peer.go
If a peer receives a channel reestablish message shortly after the
channel has been closed, it will resend its own channel reestablish
message. In the meantime the other peer could also have seen the channel
being closed and will also resend its own message. This leads to a
resend loop that never terminates.
To avoid two peers getting into this situation, we now allow only one
such resent message per conenction.
Noticed during integration tests: https://travis-ci.org/lightningnetwork/lnd/jobs/650839757?utm_medium=notification&utm_source=github_status
> peer: avoid chansync resend loop

- .travis.yml
- cmd/lncli/commands.go
Fixes a compilation issue introduced in #4066 that is only present when compiling for windows.
To catch bugs like that in the future, this PR also adds windows cross-compilation to the Travis build.
> travis+lncli: fix windows build

- go.mod
- go.sum
In this commit, we update to a new version of `x/crypto` that drops
broken ARM assembly that can cause a segfault in systems like raspis.
The broken assembly was removed in this commit to the runtime:
https://github.com/golang/go/commit/8b774103d3f833775e7e214bf51a37b3cfa39615.
Fixes #4052.
> build: update to x/crypto version w/o broken poly1305 arm assembly

- chanbackup/backup.go
- chanbackup/pubsub.go
- chanbackup/single.go
- chanbackup/single_test.go
- chanrestore.go
- lncfg/protocol_legacy_on.go
- lntest/itest/lnd_test.go
- lnwallet/commitment.go
In this PR, we add SCB support for anchor commitments and update the integration tests to add a single case to cover SCB file recovery for anchor commitments. We only add a single case here in order to leave the more encompassing itest overhaul for all commitment types to: https://github.com/lightningnetwork/lnd/pull/4001
> chanbackup: add SCB support for anchor commitments

- docker/btcd/Dockerfile
There was a recent change merged into btcd that isn't backward
compatible with older RPC clients. To make sure our docker quick
start example still works, we need to pin down btcd to the version
that is still compatible with lnd.
Fixes the problem that was described in #4076.
> docker: pin down btcd version

- config.go
Default values in --help message are handled automatically by go-flags package.
> [trivial] config: remove default values from flag descriptions

- lnrpc/routerrpc/router.proto
- lnrpc/rpc.proto
#3848 not formatted with the new check, not rebased on the change that added the check to travis, so not picked up on the build.
> routerrpc: run rpc-format on routerrpc

- chainregistry.go
Comment says default value is 0, when it is in fact 1.
> [Docs] fix defaultBitcoinMinHTLCInMSat comment

- lntest/itest/lnd_test.go
Previously this was flaky, especially on macOS.
> itest: wait for file writing in wait predicate

- go.mod
To fix external projects depending on lnd, we need to bump the queue
package to a new version for the changes to be picked up.
> mod: bump version of cert and queue packages

- aezeed/cipherseed_rpctest.go
- go.mod
- go.sum
- htlcswitch/link.go
- lntest/itest/lnd_test.go
- lntest/timeouts.go
- lnwallet/btcwallet/btcwallet_rpctest.go
- macaroons/security.go
- macaroons/security_rpctest.go
- macaroons/security_test.go
- macaroons/store.go
This PR modifies the `aezeed`, `macaroons` and `lnwallet/btcwallet` packages to use fast scrypt options when compiled with the itest build tag to speed up the node creation/startup in the integration tests.
The faster wallet unlock also brought to light some flakes in the itests that have been addressed.
> itest: use fast scrypt options for aezeed, macaroons DB and wallet DB

- chainregistry.go
- config.go
- docs/INSTALL.md
- lnwallet/chainfee/estimator.go
- sample-lnd.conf
This PR fixes issue #2990 
logging level
per default)
already exist
> multi: support config bitcoind fee estimate mode

- channeldb/channel.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
This PR fixes the error log intro'd in #3143 when pipelining settles to the switch, and makes logging less spammy and more informative.  The PR breakdown is as follows:
- First commit changes the fallback in `NextLocalHtlcIndex` to `RemoteCommitment` since `LocalCommitment` lags behind for the `LocalHtlcIndex` field. Without this bug fix, open circuits could get prematurely trimmed, resulting in more error logs. A test case is included to check that the fix works.
- Second commit returns `ErrLinkShuttingDown` so that the link logs when it's getting shut down. Also changes the order of the `ackDownStreamPackets` and check-if-link-quit call for consistency since the packets should be ACKed before going down.
- Final commit changes the switch to only log an error if a `update_fail_htlc` …
> htlcswitch: log fixes

- .gitignore
- brontide/noise.go
- lntest/itest/lnd_test.go
- lntest/node.go
Typo found when working on other issues, also added the `coverage.txt` to `.gitignore`.
> trivial:typo fix and add coverage.txt to gitignore

- contractcourt/channel_arbitrator.go
- lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_local_timeout_test.go
- lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
- lntest/itest/lnd_multi-hop_local_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/lnd_multi-hop_remote_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/lnd_multi-hop_test.go
- lntest/itest/lnd_test.go
- sweep/txgenerator.go
- sweep/txgenerator_test.go
This PR adds integration tests for a select set of integration tests with the channel type set to anchor:
basic funding flow
channel force closure
test multi-hop htlc local force close immediate expiry
test multi-hop htlc receiver chain claim
test multi-hop local force close on-chain htlc timeout
test multi-hop remote force close on-chain htlc timeout
test multi-hop htlc local chain claim
test multi-hop htlc remote chain claim
These are selected since they together test establishing channels of this new type in combination with the previous channel types, sweeping of commitment outputs, and HTLC sweep scenarios.
The goal is to later enable the whole integration test suite for this channel type, but it requires changes to most notably the channel backup format and watchtower.
[desc copied …
> lntest/itest: select anchor commitment format and sweeping itests

- routing/missioncontrol.go
- routing/missioncontrol_state.go
- routing/missioncontrol_state_test.go
- server.go
Puts a mechanism in place to prevent a failure for a low amount from being overwritten very soon after by a higher amount failure. This would cause the more useful information (the lower amount failure) not to be used for the next pathfinding round and thereby makes convergence to a final state for the payment slower.
This improvement is most significant for aggressive mpp sending. In that case, many htlcs can fail in short succession, leading to non-ideal mission control updates.
Spin off of #3967
> routing: minimum failure relaxation interval

- config.go
- docs/watchtower.md
- lnd.go
- server.go
- watchtower/config.go
- watchtower/standalone.go
Picks up where https://github.com/lightningnetwork/lnd/pull/3613 left off. I think I gave credit correctly to @orbitalturtle by adding them as a Co-author in the first commit message. The old PR created two `TorContoller`s, one in the `server`, one in the watchtower server. Now, a `TorController` is instead created in `lnd.go` and passed to both subsystems to avoid creating multiple connections to Tor's ControlPort.
Closes #3302
> watchtower: automatically create tor hidden service if enabled

- lntest/itest/lnd_test.go
- rpcserver.go
This PR consolidates our request parsing for `OpenChannel` and
`OpenChannelSync` which removes a good deal of code duplication. At the
same time, we fix a bug in `OpenChannelSync` by introducing a missing
check for max channel size.
The checks missing from `OpenChannel` are:
- ensure wallet is synced
The checks missing from `OpenChannelSync`:
- max channel size
- remote pubkey is self
Additionally, `OpenChannelSync` only parsed the `NodePubkeyString` field
which was officially deprecated in 0.9 in favor of `NodePubkey`. In aligning
the request parsing, we permit usage of the deprecated `NodePubkeyString`
field for REST to maintain backwards compatibility and allow users time to
switch now that parsing of `NodePubkey` will be supported. In 0.11 we can
consider removing `NodePubkeyString` …
> rpcserver: align OpenChannel + OpenChannelSync request parsing

- contractcourt/chain_watcher.go
In this commit, we add some additional logging of the commitments at
play when we detect a channel closure on-chain. This should help to
debug things more in the future as we don't log the full commitments
anywhere.  We also now also print the type of commitment as well, as a
follow up from the recent anchor outputs work. In the near future, as we
implement a dynamic commitments update protocol, always logging the
commitment type as well will likely be useful for debugging purposes.
> contractcourt: add additional logging of commitments at play

- contractcourt/chain_watcher.go
Follow up from #4138, adds missing channel point arguments
> contractcourt/chain_watchter: fix broken log stmts

- lntest/itest/lnd_test.go
In #4130, OpenChannel was changed to assert that the wallet is fully
synced before allowing a channel open. This introduced flakes on travis,
which are resolved here by using a wait predicate when calling
OpenChannel.
Note there is one existing call that was not converted, because it is
interested in the returned error. This call does not have a wait
predicate surrounding it, but this shouldn't cause a flake because other
channels are opened earlier in the test that will have already waited
for the wallet to sync up.
An example of the flake:
```
--- FAIL: TestLightningNetworkDaemon/max_pending_channel (2.36s)
lnd_test.go:105: Failed: (max pending channel): exited with error: 
*errors.errorString unable to open channel: rpc error: code = Unknown desc = channels cannot be created before the …
```
> lntest/itest/lnd_test: wait when calling OpenChannel

- lnwallet/channel.go
- lnwallet/channel_test.go
- lnwallet/commitment.go
Fixes #4118 
This PR fixes an issue in which HTLC signatures sent to the remote peer could be improperly ordered. This can occur when multiple HTLCs share the identical payment hashes and amounts, but have differing CLTV values. In particular, if these HTLCs are added in such a way that subsequence has descending CLTVs, the HTLC signatures would not reflect the HTLC tie-breaker used to sort the commitment.
#3412 partially fixed the issue, by ensuring that we properly sort the actual commitment and second-level transaction refer to the proper txid in their previous outpoint, however it failed to apply this sorting when generating the signing jobs and hence the final ordering that is sent on the wire.
> lnwallet: apply BIP69+CLTV tie-break to HTLC signature order

- channeldb/channel.go
- channeldb/channel_test.go
- peer.go
See commit messages for more details, summary:
- fixes bug where `HasChanStatus` always returns true
- fixes bug where `ChannelStatus` string always reported `ChanStatusDefault`, which is displayed over rpc
- changes from blacklist to whitelist when filtering channels to load into the switch since the former is brittle
> channeldb: correct HasChanStatus for ChanStatusDefault, fix rpc channel status

- Makefile
- cmd/lncli/main.go
- config.go
- lnd.go
#4163 changed the way the `-ldflags` are assembled in a way that the Windows shell doesn't like (escaping a quote doesn't work the same way as in any other _sane_ shell).
Also the `build.Version()` used to return the version and the commit. Currently when building master, the `--version` flag of both `lnd` and `lncli` don't show the commit anymore. This PR also fixes that problem.
> make+lnd+config: fix Windows build and version string

- routing/integrated_routing_context_test.go
- routing/payment_session.go
- routing/payment_session_source.go
- routing/payment_session_test.go
Problems can occur for legacy payments or keysend payments (which are also non-mpp).
> routing: do not split payment if destination does not support mpp

- channeldb/payments.go
- routing/integrated_routing_test.go
- routing/pathfind.go
- routing/pathfind_test.go
- routing/payment_session.go
Splitting pre-check to see if the total balance is sufficient for the payment. Otherwise splitting won't ever result in a successful payment, but small shards may be held by the recipient until mpp timeout.
> routing: payment splitting pre-check

- cert/selfsigned.go
Fixes  #4201.
It seems macOS 10.15 and iOS 13 [have new requirements for TLS certificates](https://support.apple.com/en-us/HT210176) that also apply to self-signed certs. If these requirements aren't met, the certificate is rejected, even if the self-signed CA is added to the list of trusted authorities (or when adding an "exception for this certificate" in a browser).
This PR adds the required
> TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.
to the self-signed certificates.
NOTE: After merging this PR, we must tag the `cert` submodule with a new version!
> cert: define ExtendedKeyUsage as required by macOS 10.15/iOS 13.

- lnwallet/chainfee/rates.go
- lnwallet/channel.go
- lnwallet/channel_test.go
Fixes #4208
This enforces the _actualized_ fee rate of the  commitment transaction,
rather than the fee floor used for estimation. The new value of 250
sat/kw corresponds to 1 sat/byte, rather than 253 which is only rounded
up during estimation to account for the fact that BOLT 3 rounds down to
the nearest satoshi and that the vbyte fee estimation is lossy.
This check was added as part of #3821 to catch any bugs in the new
anchor commitment format. The bug is not present in any official
release of lnd, but does affect master,  0.10.0-beta.rc1, and
0.10.0-beta.rc2.
For affected users, restarting with this commit should return the channel to
normal operation unless any pending htlcs have already timed out and
caused the channel to go to chain.
> lnwallet: absolute fee floor sanity check

- .travis.yml
- Makefile
- build/release/README.md
- build/release/release.sh
- make/release_flags.mk
This PR unifies the make commands and the release script.
This is necessary to make use of the new `-ldflags` assembled by the `Makefile`.
New usage:
```bash
make release
make release tag=v0.10.0-beta.rc3
make release sys=linux-amd64
```
> make+build: call release script from make

- cmd/lncli/cmd_open_channel.go
- docs/psbt.md
It was previously not stated clearly enough that the transaction created for the PSBT channel funding flow **must not** be published outside of `lnd`'s channel funding flow.
It appears especially with Wasabi Wallet it is very easy to click the wrong button and publish the finished PSBT by accident. This can lead to loss of funds if `lnd` doesn't accept the transaction because the amount was wrong (as happened in  #4223).
It is also possible the funding flow fails even _if_ `lnd` accepts the PSBT after it's al ready been published.
> lncli+docs: add safety warning about not publishing PSBT manually

- chainregistry.go
There seems to be a misinterpretation of a variable between the btcwallet and gozmq libraries. When establish a ZMQ connection, it expects a timeout, which is used to set read deadlines and determine how long we should wait before attempting a reconnection. Within btcwallet and lnd however, this is is interpreted as a polling duration, explaining the current value of 100ms. Under load, especially on less-capable hardware, this leads to high resource usage as we get into a constant reconnection loop. To remedy this, we use a timeout of 5s instead, which is a much more reasonable value for read timeouts, and is also what's used for LN peers.
> chainregistry: increase zmq connection timeout with bitcoind backend

- config.go
This PR resolves the issue where the instance hangs if tor.socks and tor.control use the same host:port. This addition simply returns an error message if they are equal.
Fixes #4154
> tor: socks and control can not use the same host:port

- server.go
A peer's remote address isn't known to us if we accepted the connection over Tor, instead we know the address the onion service used to dial to lnd. If said peer also doesn't have any advertised addresses, then we don't have enough information to attempt a reconnect, so we avoid doing so. Allowing the reconnection to happen isn't necessarily an issue, but not allowing it prevents the configured SOCKS proxy from dialing to private addresses.
Fixes https://github.com/lightningnetwork/lnd/issues/4191.
> server: ignore reconnection for unadvertised inbound peers over Tor

- docs/code_contribution_guidelines.md
Reading the code contribution guidelines, I noticed that there are contradictory informations about how a tab character should be treated: 
https://github.com/lightningnetwork/lnd/blob/20a776d70398299241ac6b76e11a3b4fe8495b68/docs/code_contribution_guidelines.md#L488
vs.
https://github.com/lightningnetwork/lnd/blob/20a776d70398299241ac6b76e11a3b4fe8495b68/docs/code_contribution_guidelines.md#L626
Looking at the commit history and PR https://github.com/lightningnetwork/lnd/pull/1196 it seems that 8 seems to be the agreed tab size.
> docs: fix tab size (8 spaces) in contribution guidelines

- tlv/truncated.go
This PR fixes function header comments for the functions `numLeadingZeroBytes32` and `numLeadingZeroBytes64` -- the inaccuracies probably happened through copy-and-paste.
> tlv: fix comments for numLeadingZeroBytes{32,64} funcs

- Makefile
- fundingmanager.go
- lntest/itest/log_check_errors.sh
- lntest/itest/log_error_whitelist.txt
- lntest/itest/log_substitutions.txt
This additional check allows us to get more out of the integration test suite:
* Detect previously unseen errors in de logs caused by newly introduced bugs that don't fail the tests directly.
* Make us aware when we start logging a new error condition that isn't really an error.
> itest: check for new errors in logs

- lntest/itest/log_check_errors.sh
- lntest/itest/log_error_whitelist.txt
The itest [ERR] log check fails because recently some character cases have changed. Didn't rebase the pr before we merged and travis doesn't automatically build every pr against latest master.
> itest: case insensitive log errors check

- channeldb/payments.go
- rpcserver.go
In this commit, we eliminate an extraneous copy in the `QueryPayments`
method. Before this commit, we would copy each payment from the initial
FetchPayments call into a new slice. However, pointers to payments are
return from `FetchPayments`, so we can just maintain that same reference
rather than copying again when we want to limit our response.
> channeldb: eliminate extra copy in QueryPayments

- Dockerfile
This is just a one line change to the Dockerfile to add the ``jq`` tool to our Docker image.
Using ``jq`` we can parse lncli output and extract individual fields.
> add jq tool to Docker image so we can parse lncli output

- docs/grpc/javascript.md
- docs/grpc/python.md
To reflect the recent changes in the API docs, the instructions/HOW-TOs for JavaScript and Python needed some polishing.
Fixes #4233
> docs: update instructions for JavaScript and Python on how to use gRPC

- cmd/lncli/cmd_pay.go
The new table format for the pay command started to use the
`Millisecond()` method on `time.Duration`. However, this method was only
added in Go 1.13, so this breaks the build for Go 1.12. We replace this
by manual division. `time.Duration` "natively" is in nanoseconds, so we
covert to milli seconds by dividing my `time.Millisecond`, which is
1,000,000.
> cmd/lncli: remove usage of Millisecond() for Go 1.12

- .github/workflows/main.yml
This PR implements all actions currently running on Travis CI to be run as GitHub Actions.
It seems the actions in the main repository will only be executed once the PR is merged. [Preview the actions here.](https://github.com/guggero/lnd/actions)
A complete run seems to finish in `30m 23s`, not bad :tada:
It seems GitHub allows up to 10 jobs to run simultaneously, so this could be the starting point for parallelizing the integration tests more.
> github: add GitHub Actions configuration

- channeldb/db.go
- channeldb/db_test.go
- channeldb/meta_test.go
- channeldb/options.go
- config.go
- lnd.go
This PR adds an additional configuration option, `dry-run-migration`, which if true will abort any attempt to do a migration. The intention is that users running on master can leave this option on in their config, and will be alerted anytime pulling in new changes will cause a migration from which they cannot revert.
This is also useful for testers willing to try out a migration in order to find bugs before the migrations are merged into master. Testers can use this setting to confirm that migrations are otherwise successful and don't have performance issues as we've seen with some migrations historically.
The setting can be overridden when starting lnd after confirming the dry run is successful by passing `--dry-run-migration=0` to start lnd and commit the migration w/o having to modify …
> Dry run migration

- contractcourt/commit_sweep_resolver.go
- contractcourt/commit_sweep_resolver_test.go
- lntest/itest/lnd_test.go
Fix an issue that started happening after commit 9acb2366656481c94f365e2e12d02f3129c4fb91.
After that commit, the commit sweeper for a channel arbitrator would no longer wait for a spend notification but rather for a specific number of blocks leaving open the possibility that a sweep by the remote party (such as when the channel was actually breached by the local party) would leave the channel forever in a pending state.
This fixes that by noticing that sweep errors where the sweep was not made by us should still cause the channel to be considered fully resolved.
The first commit surfaces the issue by verifying the state of pending channels after the testRevokedCloseRetribution integration test.
> contractcourt: fix lingering contract after local breach

- lnrpc/signrpc/signer.pb.go
- lnrpc/signrpc/signer.proto
- lnrpc/signrpc/signer.swagger.json
- lnrpc/walletrpc/walletkit.pb.go
- lnrpc/walletrpc/walletkit.proto
Replace `/**` with `/*` as in #4250, `ListSweeps` subject to strange rebase/merge order so it wasn't in the original PR. `InputScript` previously had a triple asterix so it fooled find and replace.
> lnrpc: remove double asterix comments

- autopilot/graph.go
- channeldb/graph.go
- channeldb/graph_test.go
- routing/router.go
- rpcserver.go
In perusing channeldb, I noticed `ForEachNode` accepted a `kvdb.RwTx`,
even though we should only require a read tx since one can't modify
a bbolt bucket while iterating. Turns out the argument was unused in the 
codebase can can be remove entirely.
> channeldb: remove Tx arg from ForEachNode

- .github/workflows/main.yml
The continue-on-error was added to make sure the log files of the
failed itests would always be uploaded. But this has the side effect
of marking the whole job successful, even if the itest job itself
failed. The failure condition in the log file steps already solve
that, so the continue-on-error is not needed anymore.
> github: remove continue-on-error

- lnwallet/channel.go
Fixes a silent error causing not enough signatures to be produced.
> lnwallet: return signer error

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/interface.go
- chainntnfs/neutrinonotify/neutrino.go
- contractcourt/chain_watcher_test.go
- discovery/gossiper_test.go
- fundingmanager_test.go
- htlcswitch/mock.go
- lnrpc/chainrpc/chainnotifier_server.go
- mock.go
- sweep/test_utils.go
The crash reproduces by calling one of the sub server endpoints after the RPC server is ready and before the ChainNotifier sub system starts.
The code was changed to return an error in that case allowing the caller to retry later.
> Fix crash when ChainNotifier is being accessed too early.

- .github/workflows/main.yml
Checkout v1 has a known flake:
https://github.com/actions/checkout/issues/23#issuecomment-572688577.
Example failed build:
https://github.com/lightningnetwork/lnd/pull/4213/checks?check_run_id=683943940
> github: update checkout action to v2

- go.mod
No new tag was pushed after changes to the `queue` package in #3972 and #4192. This leads to external dependencies picking up the old version.
> mod: update to queue/v1.0.4

- go.mod
- go.sum
- lntest/itest/log_error_whitelist.txt
- lnwallet/btcwallet/btcwallet.go
This update introduces backwards compatibility for btcd nodes running versions prior to `v0.20.1-beta`.
Fixes https://github.com/lightningnetwork/lnd/issues/4255.
> build: update to latest btcd and btcwallet versions

- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/mock.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- lntest/itest/lnd_test.go
- lntest/itest/log_error_whitelist.txt
Experiment to see how synchronous hand-off to the link could work.
Tried it out on the mpp send payment itest. To make sure that the async hand-off would lead to an extra payment attempt, I added a 100 ms sleep in the link before adding the htlc to the channel.
This is the original timing diagram, which shows the temp. chan failure originating from ourselves (@ 0)
With sync hand-off, it looks like this:
Fixes #4181
> htlcswitch: sync local payment hand-off to link

- peer.go
Fixes #4297.
Integers used atomically MUST be aligned properly, otherwise the
sync library will crash on purpose. Therefore non-aligned struct
members must come later.
> peer: fix struct alignment

- channeldb/payment_control_test.go
- go.mod
- go.sum
- htlcswitch/switch_test.go
- htlcswitch/test_utils.go
The btcsuite/fastsha256 [registers itself in the crypto package](https://github.com/btcsuite/fastsha256/blob/master/sha256.go#L15) of
golang as a replacement for sha256. This causes problems in TLS1.3
connections that require the hash implementations to be serializable
and results in the `tls: internal error: failed to clone hash` error.
By removing all uses of the library we fix that error which appears to
occur for REST connections from modern browsers that support TLS1.3.
> channeldb+htlcswitch: don't use fastsha256 in tests

- lnwallet/btcwallet/signer.go
This prevents a panic when providing an incompatible output index for the transaction.
Fixes https://github.com/lightningnetwork/lnd/issues/4301.
> btcwallet: add transaction outputs bounds check to FetchInputInfo

- lnd.go
In this commit, we fix a regression in our DB open time logging that was
introduced in #4015. Obtaining the target backend from the configuration
will actually also open the database, so we need to include that in the time
delta as well.
> lnd: fix regression in DB open time logs

- cmd/lncli/commands.go
Fixes 2 typos in the help dialog for `lncli closechannel` (attribute `--delivery_addr`)
> lncli: Fix typos in closechannel help dialog

- clock/test_clock.go
- clock/test_clock_test.go
This PR makes it possible to wait for all test tickers to be constructed. This is useful when the tickers are registered concurrently.
> clock: optionally wait until tickers are registered in TestClock

- channeldb/invoice_test.go
- channeldb/invoices.go
- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
- rpcserver.go
This PR addresses three bugs in our current invoice subscriptions:
- No backlog can be delivered until an invoice is settled.
- `SubscribeNotifications` can return before registration and backlog delivery have finished, which can lead to duplicate notifications, even in a single process.
- The database operations for retrieving backlogs are not synchronized in the same manner as the `AddInvoice`, `CancelInvoice` etc, leading to inconsistent reads on the database state and in some cases can lead to duplicate notifications when the registry is processing concurrent operations.
> channeldb+invoices: minor invoice subscription fixes

- build/version.go
In this commit, we bump the version to a `.99` minor version to reflect
the fact that master is ahead of _both_ `v0.10.0-beta`, and the upcoming
`v0.10.1-beta` release.
> build: bump version to lnd v0.10.99-beta

- channeldb/db.go
- channeldb/error.go
- channeldb/invoice_test.go
- channeldb/invoices.go
- channeldb/log.go
- channeldb/migration/create_tlb.go
- channeldb/migration/create_tlb_test.go
- channeldb/migration/log.go
- channeldb/migtest/migtest.go
- htlcswitch/test_utils.go
- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
- invoices/test_utils_test.go
- invoices/update.go
- lntest/itest/log_error_whitelist.txt
- lntest/timeouts.go
- lntest/timeouts_darwin.go
This PR adds a new persistent index on invoices to allow efficient
lookups and updates by payment address. This is stepping stone
to enable AMP payments where the payment hash will not be
associated with the target invoice.
Since 0.9, all new invoices include a random payment address,
however older invoices do not have this value. New invoices will
be added to the payment address index on a rolling basis, but 
the payment hash index will continue to serve as a fallback in case
the target invoice was created prior to this commit. As such,
no migration is needed for invoices created prior to this commit, 
but we include one to bump the db version number and initialize
the top-level index bucket.
This also unblocks #4167, since it allows us to insert a random
payment address for experimental …
> channeldb: index payments by payment addr, use payment hash as fallback

- config.go
- lnd.go
- log.go
- rpcserver.go
To get rid of another global (and exported) variable, we refactor the `config.go`, `lnd.go` and `log.go` to make it possible to pass in a log writer through the main `Config` struct.
> config+log: remove global RootLogWriter variable

- channeldb/invoices.go
We recently renamed kvdb.ReadBucket to kvdb.RBucket in #4252, but this
was not detected in #4285 since this new code didn't produce a
conflict.
> channeldb/invoices: correct stray kvdb.ReadBucket to RBucket

- routing/pathfind.go
- routing/pathfind_test.go
- routing/payment_session.go
Previous behavior led to the payment loop being abandoned immediately, resulting in a payment stuck in state in_flight.
Fixes #4319
> routing: don't treat bad features as an unexpected error

- channeldb/invoice_test.go
- channeldb/invoices.go
- contractcourt/channel_arbitrator.go
- htlcswitch/link_test.go
- htlcswitch/test_utils.go
- invoices/invoiceregistry.go
- invoices/test_utils_test.go
- invoices/update.go
- lnrpc/invoicesrpc/addinvoice.go
- lnrpc/invoicesrpc/invoices_server.go
- lnrpc/invoicesrpc/utils.go
Previously it wasn't possible to store a preimage in the invoice database and signal that a payment should not be settled right away. The only way to hold a payment was to insert the magic `UnknownPreimage` value in the invoice database. This commit introduces a distinct flag to
signal that an invoice is a hold invoice and thereby allows the preimage to be present in the database already.
Preparation for (key send) hodl invoices for which we already know the preimage.
This PR is a spin-off of #4167
> invoices: add explicit hodl invoice flag

- go.mod
- go.sum
- lntest/itest/log_error_whitelist.txt
This PR bumps etcd to v3.3.22 stable version while also fixing the invalid version of go-systemd dependency which prevented using LND head as a dependency in other projects.
> build: bump etcd to v3.3.22

- netann/channel_announcement.go
- netann/channel_announcement_test.go
This was the only field not properly set when creating a `lnwire.ChannelAnnouncement` from a `channeldb.ChannelEdgeInfo`.
Fixes https://github.com/lightningnetwork/lnd/issues/4322.
> netann: decode features when creating chan ann from stored chan info

- channeldb/kvdb/etcd/db.go
- channeldb/kvdb/etcd/db_test.go
- channeldb/kvdb/etcd/embed.go
- channeldb/kvdb/etcd/stm.go
- channeldb/kvdb/kvdb_etcd.go
- channeldb/kvdb/kvdb_no_etcd.go
- lncfg/db.go
- lnd.go
This PR removes the retry goroutine from the STM as the retry loop
is only running when the STM transaction is encapsulated in Update/View
whereas for self-standing transactions we use a different approach.
By removing the goroutine we won't catch panics thrown that are supposed
to be catched outside of the STM.
Furthermore the PR also integrates the LND abort context to the STM  to fix
blocking upon exit when multiple transactions keep conflicting with each other.
> lnd+kvdb+etcd: remove retry goroutine from the STM and integrate abort context

- lnrpc/signrpc/signer.pb.go
- lnrpc/signrpc/signer.proto
- lnrpc/signrpc/signer.swagger.json
- lnrpc/signrpc/signer_server.go
This is meant to handle a quirk in which key descriptors obtained through walletrpc.DeriveKey don't result in the derived key being persisted to the wallet's database, unlike with DeriveNextKey. Due to this and some fallback logic in the wallet with regards to empty key locators, if a request only specified the compressed public key, the signature returned would be over a different key, namely the one derived from (family=0, index=0).
> signrpc: parse both KeyDescriptor fields for SignOutputRaw requests

- channeldb/invoice_test.go
This PR replaces reflect.DeepEqual tests and spew.Dump prints with testify's require.Equal to make diffs smaller and test outputs more readable, as testify provides localized diffs.
I realized this being a problem a couple of times while changing channeldb and spending time with local rewrites to ease debugging.
Additionally the PR changes basic asserts to specific requires, which is more readable and also fails the test immediately.
> invoices+test: replace DeepEqual + spew dump with testify

- chainntnfs/txnotifier.go
- chainntnfs/txnotifier_test.go
This addresses a panic when a notification is canceled after its been detected as included in a block and before its confirmation notification is dispatched.
> chainntnfs: remove queued confirmation notification in CancelConf

- lnrpc/walletrpc/config_active.go
- lnrpc/walletrpc/walletkit_server.go
- lnwallet/btcwallet/btcwallet.go
- lnwallet/interface.go
- rpcserver.go
- subrpcserver_config.go
This ensures proper coin selection synchronization between lnd and users of the RPC to avoid potential double spend errors.
> rpc: acquire global coin select lock in related RPCs

- breacharbiter_test.go
This fixes a possible race condition during TestBreachSpends that could
cause the test to fail in a flaky way.
The error returned in PublishTransaction (publErr) could be modified by
the main test goroutine before PublishTransaction had a chance to
return, causing the wrong error value to be returned.
This was mostly visible as a flake during TestBreachSpends/all_spends
where adding a one second delay in the old code between the send in
publTx and the call to publMtx.Lock() would cause the last iteration of
the test loop to fail.
This is fixed by moving the lock and locally storing the expected error
value to before the send so that each call to PublishTransaction is
guaranteed to return the correct error value.
> breacharbiter: fix flaky race condition in test

- Makefile
Compiling with this flag cuts down on the binary size by several megabytes.
> Makefile: add -w to -ldflags to strip DWARF symbols

- discovery/syncer.go
- discovery/syncer_test.go
One line change to `syncer.replyChanRangeQuery` to ensure endBlock calculation doesn't overflow.  Adds a test that performs multiple queries to ensure the correct start / end block values are supplied to the channel graph filter.
Fixes #4393
> discovery: prevent endBlock overflow in replyChanRangeQuery

- channeldb/db.go
- channeldb/db_test.go
- lntest/itest/log_error_whitelist.txt
This was initially done as there were a few assertions throughout the codebase requiring a channel's policy to be known. Now that these have been addressed, we no longer need to store restored channels in the graph, as their policies where incomplete anyway.
> channeldb: remove graph insertion of restored channels

- lnwire/query_short_chan_ids.go
- lnwire/query_short_chan_ids_test.go
This fixes a decoding error when the list of short channel ids within a
QueryShortChanIDs message started with a zero sid.
BOLT-0007 specifies that lists of short channel ids should be sorted in
ascending order. Previously, this was checked within lnwire by comparing
two consecutive sids in the list, starting at the empty (zero) sid.
This meant that a list that started with a zero sid couldn't be decoded
since the first element would _not_ be greater than the last one
(namely: also zero).
Given that one can only check for ordering starting at the second
element, we add a check to ensure the proper behavior.
A unit test is also added to ensure no future regressions on this
behavior.
Extracted from #4346
> lnwire: fix decoding for initial zero sid

- chanbackup/pubsub.go
- chanbackup/pubsub_test.go
In this commit, we fix a bug that could possibly cause a user's on disk
back up file to be wiped out, if they ever started _another_ lnd node
with different channel state. To remedy this, before we swap out the
channel state with what's on disk, we'll first read out the contents of
the on-disk SCB file and _combine_ that with what we have in memory.
We also add an additional defense against starting up with an
invalid SCB state. With this commit, we'll now fail to start up if we're
unable to update or read the existing SCB state from disk. This will
prevent an lnd node from starting up with an invalid SCB file, an SCB
file it can't decrypt, or an SCB left over from another node.
Fixes #4377
> chanbackup: always combine with on-disk state when swapping, refuse to start w/ invalid files

- contractcourt/channel_arbitrator.go
looks like there are two places missing `ChannelStatus` when calling `MarkChannelClosed`, while [this call](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/channel_arbitrator.go#L2292) did use one.
> contractcourt: add ChannelStatus in MarkChannelClosed

- htlcswitch/switch_test.go
Previously fixed by this commit,
[channeldb+htlcswitch: don't use fastsha256 in tests](https://github.com/lightningnetwork/lnd/commit/a17ddc5dd1849ae9f6b01fb59cd5659167bd9848#diff-9ca6c00aa4cbaaa08aaa8bd697703398)
And broken by this commit,
[htlcswitch: introducing interceptable switch.](https://github.com/lightningnetwork/lnd/commit/0f50d8b2eddf95531ecb376e358514dd50b07bac#diff-9ca6c00aa4cbaaa08aaa8bd697703398R14)
This PR removes fastsha256.
> htlcswitch: remove fastsha256 in test

- discovery/gossiper.go
This fixes a possible race condition on the gossiper which is surfaced by some flaky itests. An intermediate commit tries to improve the odds of triggering it by introducing some artificial delays in key points.
Reviewers can look for the error's "signature" by running `make build-itest itest-only icase="multi-hop_htlc/committype=anchors/remote_force_close"` then `grep "premature" lntest/itest/*.log`: when the error is triggered, you can find a log message 
> "DISC: Update announcement for short_chan_id(...), is premature: advertises height 510, only height 509 is known
But you **don't** get a message indicating the premature announcement has been re-processed:
> DISC: Re-processing 1 premature announcements for height 510
You **only** get this message when the fix is added. Since this is …
> discovery: correctly lock premature messages

- config.go
- invoices/invoice_expiry_watcher.go
- invoices/invoice_expiry_watcher_test.go
- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
- server.go
Adds a new option to `lnd` to hold received keysend payments in the accepted state for a configured period of time. During this time, an application can inspect the payment parameters and decide whether to cancel or settle this payment.
Example: a keysend payment with an embedded order comes in. The payment is held and an external application checks that the paid amount is sufficient for the ordered goods. If not, the payment is canceled without the need to refund anything. If the amount is sufficient, the payment is settled and the order processed.
This PR makes development of applications like [tlvshop.com](https://tlvshop.com/) possible without forking `lnd`.
> multi: hold keysend payments

- channeldb/channel.go
- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
- lntest/itest/lnd_test.go
- lnwallet/chancloser/chancloser.go
- rpcserver.go
This is useful when we wish to have a channel frozen for a specific amount of blocks after its confirmation. This could also be done with an absolute thaw height, but it does not suit cases where a strict block delta needs to be enforced, as it's not possible to know for certain when a channel will be included in the chain. To work around this, we add a relative interpretation of the field, where if its value is below 500,000, then it's interpreted as a relative height. This approach allows us to prevent further database modifications to account for a relative thaw height.
> multi: add relative thaw height interpretation

- config.go
- netann/host_ann.go
- netann/host_ann_test.go
- server.go
In this commit, we add a new sub-system, then `HostAnnouncer` which
allows a users without a static IP address to ensure that lnd always
announces the most up to date address based on a domain name. A new
command line flag `--external-hosts` has been added which allows a user
to specify one or most hosts that should be periodically resolved to
update any advertised IPs the node has.
Fixes #1624.
Fixes #2262.
> netann: add new HostAnnouncer to support dynamic IPs via domains

- chanbackup/backupfile.go
In this commit, we fix a bug introduced with the recent bug fix for SCB
state+fail combination. On windwos a rename operation will fail is the
fail one is attempting to rename is still open. Therefore we need to
close the file after we read the contents, to ensure the follow up
rename operations once the channel state changes will succeed.
Fixes #4450.
> chanbackup: always close SCB file after reading

- feature/default_sets.go
- feature/manager.go
- fundingmanager.go
- fundingmanager_test.go
- lncfg/protocol.go
- lncfg/protocol_experimental_off.go
- lncfg/protocol_experimental_on.go
- lncfg/protocol_legacy_off.go
- lncfg/protocol_legacy_on.go
- lntest/itest/lnd_multi-hop-payments.go
- lntest/itest/lnd_test.go
- lntest/itest/lnd_wumbo_channels_test.go
- lntest/itest/log_error_whitelist.txt
- lnwire/features.go
- rpcserver.go
- server.go
In this commit, we add support for wumbo channels! Wumbo channels are enabled by default, and can be enabled , using a new config flag: `--protocol.wumbo`. As a stop gap to smarter security parameter (num confs and csv delay), we jump straight to the current maximum for these values if we detect wumbo channel funding.
> multi: I wumbo, you wumbo, he she wumbo

- lnrpc/rpc.proto
> trivial: fix make rpc-format

- invoices/resolution_result.go
In this commit, we add a String() method to the failure resolution
outcome. Without this, logs aren't very useful as the integer version of
the outcome is printed rather than the description.
> invoices: add String() method to failure resolution outcome

- chainntnfs/bitcoindnotify/bitcoind_test.go
- chainntnfs/btcdnotify/btcd_test.go
- chainntnfs/height_hint_cache.go
- chainntnfs/height_hint_cache_test.go
- chainntnfs/interface_test.go
- chainregistry.go
- config.go
- lnwallet/interface_test.go
Disable Height Hint Cache Queries is a new configuration option that, as the name implies, disables queries on the height hint cache. This allows lnd node operators to recover from stuck pending channels due to cached incorrect-height hints. The following describes the problem:
**Problem description**
A busy node that goes offline for several days can end up with a lot of closed channels. If the node remains down long enough, when it restarts it will look for channel closure transactions by scanning the chain. Because such rescans of the chain are "expensive" (performance/time), a cache called the "height hint cache" is used. But if this cache has the wrong height in it, the node will never be able to find the channel closure transactions. For example, If the cached height is 630,000, but …
> New config option - disable height hint cache queries

- .travis.yml
- Makefile
- mobile/bindings.go
- mobile/gen_bindings.sh
Fixes compilation error originating from moving of the config parsing: #4286 
The config parsing itself could probably be made more mobile aware, but for now we restore the same flow as has been used.
Also adds a Travis build step for making sure the mobile bindings builds with the `mobile` tag set. 
Fixes https://github.com/lightningnetwork/lnd/issues/4382
> mobile+make: restore mobile compilation

- autopilot/agent.go
- autopilot/betweenness_centrality_test.go
- autopilot/centrality_testdata_test.go
- autopilot/interface.go
- autopilot/top_centrality.go
- autopilot/top_centrality_test.go
This PR adds a very simple autopilot heuristic to the already existing heuristics, that simply calculates the betweenness centrality of the current graph and returns normalized node scores with the exception of the ones we already have channels with.
This method successfully approximates Maximum Betweenness Improvement (MBI) given sufficient number of new edges added but is considerably worse than estimating MBI with a real greedy algo which would add ghost edges to all nodes and select the one which would result in the largest centrality value for our node.
> add modified greedy topK centrality heuristic to autopilot

- lnwire/features.go
Fixes minor typos in the feature set for Wumbo.
> lnwire: fix minor typos in wumbo features

- lnwallet/channel.go
- lnwallet/channel_test.go
The `remoteLogUpdateToPayDesc` function now properly restores the `addCommitHeightLocal` field of a settle or fail's parent add. It would otherwise be set to the default value of 0, and cause a force closure when receiving a commitment due to our validation of commitments:
```
[alice] 2020-07-02 05:18:29.235 [ERR] HSWC: ChannelLink(501:1:0): failing link: 
ChannelPoint(e6863e99fd180ac0c34211ddd20eca852484ce5ac3ffa29c5747006d85bf54f0:0): unable to accept new 
commitment: parent entry 194 for update 194 had zero local add height with error: invalid commitment
```
This occurs because the `addCommitHeightLocal` field is only populated for a restored add if the add is on the local commitment. `TestChannelRestoreCommitHeight` is expanded in `lnwallet/channel_test.go` to demonstrate the fix …
> lnwallet/channel.go: restore bug fixes

- cmd/lncli/commands.go
The password instruction in the same function and many other related outputs use Printf except of Println.
> lncli: remove new line from password confirmation

- channeldb/channel.go
- lnwallet/channel.go
- lnwallet/channel_test.go
This changes the removal logic for the updates stored under `unsignedAckedUpdatesKey`. Before this change, the logs were removed when we signed the next commitment. However, if we sign a commitment and go down, the unsignedAckedUpdates will have been removed. This means that if a settle/fail was just signed for, there won't be any way to restore it since it was just deleted. 
This fixes another long-standing force close bug that could occur with missing updates in the update logs. Since we want to remove the updates after they're completely locked in, we filter them when we receive a revocation. We filter as it's possible for more things to have been added to the key since our last signature.
For additional context, see the unit test or the commit descriptions of 1b9db8e and 90f2cb9
> channeldb/channel.go: remove unsignedAckedUpdatesKey when we receive revocation

- .travis.yml
- go.mod
- go.sum
- lntest/harness.go
- lntest/itest/log_error_whitelist.txt
- lntest/itest/log_substitutions.txt
Fixes https://github.com/lightningnetwork/lnd/issues/4454.
Depends on #4482, only the last three commits are relevant.
This PR adds an integration test to Travis that runs on the ARM architecture.
We specifically use the golang cross compilation feature to create a 32bit binary, even though the VM that Travis runs is an ARM64 CPU.
With this we aim to track down the segmentation fault error that we suspect is happening with `go1.14.x`.
> travis: add integration test on ARM

- channeldb/channel.go
- channeldb/channel_test.go
- channeldb/db_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
This PR fixes a long-standing force close bug. Currently, when we send a revoke for our current commitment, we store all of the remote log updates that we need to sign for. Similarly, this PR stores the local log updates that the remote needs to sign for once we receive a revocation.
Fixes #4263 
Fixes #4435 
Fixes #4134
Fixes #4137
Fixes #4134 
Fixes #4246
> channeldb+lnwallet: store updates the peer should sign under new key

- .travis.yml
To make sure build runners aren't blocked with 30 minute tasks if a PR is invalid because of compilation or linting issues, we add the sanity check stage back again.
I experimented with running the three tasks in parallel but it turned out to be slower than running them in sequence.
> travis: add sanity check stage

- channeldb/channel_test.go
- channeldb/db.go
- channeldb/db_test.go
- channeldb/forwarding_log_test.go
- channeldb/graph_test.go
- channeldb/invoice_test.go
- channeldb/kvdb/etcd/bucket.go
- channeldb/kvdb/etcd/db_test.go
- channeldb/kvdb/etcd/driver_test.go
- channeldb/kvdb/etcd/readwrite_bucket.go
- channeldb/kvdb/etcd/readwrite_bucket_test.go
- channeldb/kvdb/etcd/readwrite_cursor.go
- channeldb/kvdb/etcd/readwrite_cursor_test.go
- channeldb/kvdb/etcd/readwrite_tx.go
- channeldb/kvdb/etcd/readwrite_tx_test.go
- channeldb/kvdb/etcd/stm.go
- channeldb/kvdb/etcd/stm_test.go
- channeldb/meta_test.go
- channeldb/nodes_test.go
- channeldb/payment_control_test.go
- channeldb/payments_test.go
- channeldb/reports_test.go
- channeldb/waitingproof_test.go
- channeldb/witness_cache_test.go
- nursery_store_test.go
- sweep/store_test.go
- utxonursery_test.go
This PR is part of a multi PR effort to speed up our etcd wrapper and make all tests succeed:
Key derivation: https://github.com/lightningnetwork/lnd/pull/4411
Range cache: https://github.com/lightningnetwork/lnd/pull/4433
Integration tests: https://github.com/lightningnetwork/lnd/pull/4402
This PR enables testing some remaining packages that use channeldb on etcd backend. 
Furthermore the PR also changes the flattened bucket key derivation such that the bucket/value prefix becomes a postfix instead. This fixes incompatibility with the bbolt backend, where buckets containing bucket keys were not picked up by our cursor wrappers. The issue was discovered on while investigating failing nursery tests which are also migrated to be able to run on etcd too.
> kvdb+etcd+tests: change etcd flattened bucket key derivation to make it compatible with bbolt

- mobile/gen_bindings.sh
After the `WalletUnlocker` was split into its own file in acd105fccb8b95177f29da11aa595a675a15fb21, we did no longer generate mobile bindings from it.
> mobile: remember walletunlocker.proto

- channeldb/kvdb/config.go
- config.go
- lncfg/db.go
- lnd.go
In this commit, we make sure that `cfg.SyncFreeList`, and
`cfg.Bolt.NoSyncFreeList` cannot be set together. Atm, only the latter
value is actually read when we go to open `bbolt`. We also make another
change to force the DB config value to reflect the outer config value if
it's set.
Without this commit, those that update to `v0.11` and were running with
`--sync-freelist=1`, would be met with a regression as `lnd` would
reconstruct the free list from scratch on start up. This may have
resulted in long start up times for those with very large free lists.
> config: make bbolt freelist settings mutually exclusive

- lnrpc/chainrpc/chainnotifier_server.go
This corrects the output of the chain notifier RPC error. It has been displayed as: "chain notifier RPC **isstill** in the process of starting"
> rpc: add missing space to error message

- docs/rest/websockets.md
- lnrpc/websocket_proxy.go
- lntest/itest/rest_api.go
This fixes a bug that was found by @kaloudis (and @frennkie) and reported offline.
Without this fix our new WebSocket proxy basically cannot be used in any browser environment.
For security reasons, browsers are limited in the header fields they can
send when opening a WebSocket connection. Specifically, the macaroon
cannot be sent in the Grpc-Metadata-Macaroon header field as that would
be possible for normal REST requests. Instead we only have the special
field "Sec-Websocket-Protocol" that can be used to transport custom
data. We allow the macaroon to be sent there and transform it into a
proper header field for the target request.
> Bugfix: Allow browsers to send macaroon in WebSocket calls

- config.go
According to the recent discussion `noseedbackup` is not deprecated.
This change clarifies the message about deprecation.
Closes #4499
logging level
per default)
already exist
> Updated deprecation message of noseedbackup

- chainregistry.go
- config.go
- lncfg/db.go
- lnd.go
- peer/brontide.go
- peer/config.go
- pilot.go
- rpcserver.go
- server.go
In this follow up PR to the recent `etcd` backend PR, we modify our data storage to support a new hybrid system. For operations that require lower read latency, or which read data sources which can easily be re-populated (the graph as an example), we use a _local_ bolt option. If a replicated database is active (in this case `etcd`), then we'll use that replicated database for just about everything else. 
Admittedly, the current implementation is a bit crude in that it creates two new backends `LocalDB` and `RemoteDB`, which are then passed into the appropriate context based on the replication needs of the data. This results in two new pointers in the server, which will force the caller to decide on if the data should remain local for low latency access, or should be replicated along with …
> multi: create split local/remote database structure 

- chainntnfs/txnotifier.go
If a concurrent call to cancel is made while the notifier is shutting
down, this would cause a panic (close of closed channel) since the
events are not removed from the notification sets.
> chainntnfs/txnotifier: remove events on teardown

- lnrpc/invoicesrpc/addinvoice.go
In this commit, we update the hop hint selection to account for the fact
that with MPP, a single payment may consume multiple channels. As is, if
a user only has two 0.5 BTC channels, and tries to make a 1 BTC channel,
then the current logic won't include any hop hints.
In this commit we fix this with a simple algorithm for selecting hop
hints:
* randomly shuffle all hop hints
* add hop hints until we exceed our max, or the set of available
bandwidth for all hop hints sums to 2x the invoice payment size
This ensures that users don't always get the same set of routing hints
when they go to pay, which may prevent proper payments as users may be
trying to use the same set of channels causing HTLCs to fail. We add 2x
here to give some margin of error if the active channels are used for
other …
> lnrpc/invoicesrpc: extend hop hint selection to account for MPP 

- go.mod
- go.sum
- lnwallet/wallet.go
In this commit, we make a new wrapper method around the internal
`WalletController` method to ensure it holds the coin select mutex while
the balance is being computed.
We also update `btcwallet` to a new version that fixes a race condition.
> btcwallet: update btcwallet version, ensure ConfirmedBalance holds the coin select mutex 

- go.mod
- go.sum
In this commit, we update our btcwallet dep to the latest version. This
version includes a bug fix for dust calculation. Without this bug fix,
users would potentially significantly overpay on fees, as dust was
computed using the desired fee of the transaction rather than the min
relay fee.
> build: update to btcwallet version with dust bug fix

- breacharbiter.go
- contractcourt/chain_arbitrator.go
- contractcourt/channel_arbitrator.go
- contractcourt/htlc_success_resolver.go
- fundingmanager.go
- fundingmanager_test.go
- labels/labels.go
- lntest/harness.go
- lntest/itest/lnd_test.go
- lnwallet/chancloser/chancloser.go
- server.go
- utxonursery.go
- watchtower/lookout/punisher.go
Follow up labelling of external transactions with labels for the transaction types we create within lnd. Since these labels will live a life of string matching, a version number and rigid format is added so that string matching is less painful. We start out with channel ID, where available, and a transaction "type". External labels, added in a previous PR, are not updated to this new versioned label because they are not lnd-initiated transactions. Label matching can check this case, then check for a version number.
> multi: add labels to lnd native transactions

- channeldb/forwarding_package.go
- htlcswitch/switch.go
Not necessary to open a write tx.
> [trivial] htlcswitch: use kvdb.View for loading fwdpkgs

- chainparams.go
- chainregistry.go
- config.go
- fundingmanager_test.go
- lnd.go
- mock.go
- pilot.go
- rpcserver.go
- server.go
This commit removes the `activeNetParams` global in `chainparams.go`. This is necessary to isolate code from the lnd package so we can import it for use in tests, other projects, etc.
> lnd: removing activeNetParams global, passed around instead via configs

- make/testing_flags.mk
This PR enables having a dev build with all subservers with an optional `with-rpc=1` build param.
> build: add all subservers to dev build with an optional with-rpc build param

- README.md
The old key expires in a month or so. We recently updated the key to use
a newer expiry date. This commit updates the link to point to the
updated gist.
This command can be run to verify the new expiry date: 
```
curl https://gist.githubusercontent.com/Roasbeef/6fb5b52886183239e4aa558f83d085d3/raw/5fa96010af201628bcfa61e9309d9b13d23d220f/security@lightning.engineering | gpg --list-packets --verbose
```
> README: update link to security disclosure GPG key

- watchtower/lookout/justice_descriptor_test.go
- watchtower/lookout/lookout_test.go
- watchtower/lookout/mock.go
- watchtower/wtclient/client_test.go
Several watchtower unit tests were not being executed by make unit since
they require the dev tag to be passed in. All tests still pass.
> watchtower: remove dev tag from unit test files

- channeldb/invoice_test.go
- channeldb/invoices.go
- config.go
- invoices/invoice_expiry_watcher.go
- invoices/invoice_expiry_watcher_test.go
- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
- server.go
This PR adds configurable garbage collection to remove canceled invoices when LND starts up and also to delete newly canceled ones on the fly. As users might have many of such invoices where collecting and deleting them may take a long time, garbage collection on startup is off by default.
> invoices: garbage collect settled/canceled invoices

- build/log_shutdown.go
- build/logrotator.go
- cmd/lncli/cmd_open_channel.go
- cmd/lnd/main.go
- config.go
- go.mod
- go.sum
- healthcheck/diskcheck.go
- healthcheck/diskcheck_solaris.go
- healthcheck/diskcheck_windows.go
- healthcheck/healthcheck.go
- healthcheck/healthcheck_test.go
- healthcheck/log.go
- lncfg/healthcheck.go
- log.go
- mobile/bindings.go
- sample-lnd.conf
- server.go
- signal/signal.go
This PR wraps our existing logger in one which will request graceful shutdown when the `Critical` logging level is used. This wrapper is used to add two health checks to lnd which will shutdown if we do not succeed after sufficient backoff/retry:
1. Check that we have a connection to our chain backend
2. Check that we have some space available on disk
The regularity and strictness (ie, number of retries we allow) of this check are made configurable, so that users can turn them off/ make them less strict, or turn them off entirely if they cause issues (particularly thinking about neutrino flakes).
Windows is windows, so we need to have a special windows space check (`_windows`, TIL!). 
Partially addresses #4306 (does not cover failed disk writes, so issue not entirely fixed)
Fixes #1557 …
> healthcheck: add regular chain backend and disk space checks

- go.mod
The PR #4421 updated the cert package. To make lnd usable as dependency
in other projects after the PR was merged, we need to tag and update the
cert package.
> mod: update cert to v1.0.3

- lntest/itest/log_error_whitelist.txt
- lntest/itest/log_substitutions.txt
Fixes a replacement pattern in the error whitelist that caused some errors not to be white listed.
> itest: fix pattern for short_chan_id in err whitelist

- lnd.go
- rpcserver.go
This commit adds the same CORS functionality that's currently in the main gRPC proxy to the WalletUnlocker proxy. This ensures the CORS configuration is carried through all API endpoints.
> lnd: Add CORS support to the WalletUnlocker proxy

- lnwallet/btcwallet/btcwallet.go
A transaction with an unsupported address would prevent the method from returning any other transactions and would instead return an error.
Fixes https://github.com/lightningnetwork/lnd/issues/4568.
> btcwallet: skip unsupported addresses in ListTransasctionDetails

- contractcourt/briefcase.go
Was looking into the itest logs, found this weird line,
```go
2020-08-28 16:43:19.897 [DBG] CNCT: ChannelArbitrator(255e8b3abfa890f33966bfe61a32b39bb86a766809312fa3c90ec21663499a10:0): checking commit chain actions at height=461, in_htlc_count=0, out_htlc_count=0
yeee: *bdb.db
2020-08-28 16:43:19.894 [ERR] CHFT: Close channel 255e8b3abfa890f33966bfe61a32b39bb86a766809312fa3c90ec21663499a10:0 unknown to store
```
> trivial: remove unused print

- fundingmanager.go
As a follow-up to #4560 we actually need to hold the reservation mutex
during the full loop where we count the pending reservations. Otherwise
the results might become inaccurate for concurrent funding flows.
> fundingmanager: hold lock during loop

- lnrpc/routerrpc/router_server.go
Fixes  #4594.
When using `routerrpc.EstimateRouteFee`, the routing algorithm is invoked without setting a probability source which results in a crash in the router.
> routerrpc: pass in probability source

- build/version.go
As a preparation for external projects that require some features of the `master` branch to be in the not-yet-released version `v0.11.1-beta`, we tag the master branch with version `v0.11.99-beta` so the version check can be added in those projects.
> build: bump version of master branch to v0.11.99-beta

- cmd/lncli/cmd_macaroon.go
- cmd/lncli/cmd_profile.go
- cmd/lncli/commands.go
- cmd/lncli/macaroon_jar.go
- cmd/lncli/macaroon_jar_test.go
- cmd/lncli/main.go
- cmd/lncli/profile.go
Inspired by  #1237.
Easily manage multiple `lnd` nodes by storing all global options (like `--rpcserver`, `--tlscertpath`, `--macaroonpath` and so on) in profiles for easy use. Macaroons can be stored in cleartext (hex encoded) or encrypted with `snacl/secretbox` for added security.
Example profile file (stored and picked up in `~/.lncli/profiles.json`):
```
{
"profiles": [
{
"name": "zane",
"rpcserver": "localhost:10019",
"lnddir": "/home/guggero/.lnd-dev-zane",
"chain": "bitcoin",
"network": "regtest",
"tlscert": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----\n",
"macaroons": {
"default": "admin",
"timeout": 60,
"jar": [
{
"name": "admin",
"data": "0201036c6e6402eb01030a1042d25b1373217e6a4ae3650e37fb13f6120..."
}
]
}
},
{
"name": "test",
"rpcserver": "localhost:10008", …
```
> lncli: add profiles for easy multi-node management

- lnd.go
- macaroons/service.go
- macaroons/service_test.go
- rpcserver.go
This is part 2 of the series, part 1 can be found here: #4463. Only the last 3 commits are new.
When external subservers register themselves to be served through the
same gRPC interface as the main lnd RPC, their requests are also
intercepted by the main lnd macaroon interceptor.
If the external subservers want to use their own macaroons that are
independent of lnd's, they need a way to overwrite the default validator
of the macaroon interceptor. We add this mechanism with the concept of
external validators.
> Advanced macaroons 2/2: Custom macaroon validator for external subservers

- sample-lnd.conf
When starting up with lnd.conf that contains the sample line
"tor.active", lnd crashes and prints the error:
malformed key=value (tor.active)
Using "tor.active=true" instead works as expected.
> docs: fix "tor.active" item in sample-lnd.conf

- channeldb/channel.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- lnwallet/commitment.go
- lnwire/features.go
- peer/brontide.go
This PR makes the necessary changes to the anchor commitment type to make it compliant with the final spec version as defined in https://github.com/lightningnetwork/lightning-rfc/pull/688
There are two changes needed:
1. We set the feature bit to `20/21`. This means that we now require this bit to be advertised to signal anchor support. The old bit will be ignored by new nodes.
2. The anchor amounts are given back to the initiator in a coop close scenario. This means that existing nodes having anchor channels will disagree on the final coop close fee _if only one of the channel parties update_. However if both update closing proceeds as normal. In the worst case force closing works as before.
3. Anchors are no longer experimental.
NOTE: Watchtowers are still not supported for anchor …
> [anchor commitment] Make the anchor commitment type spec compliant

- cmd/lncli/commands.go
This PR adds `outgoing_chanid` to `lncli queryroutes` as a simple way to enforce the first hop.
> lncli: add outgoing_chanid to queryroutes

- cmd/lncli/cmd_macaroon.go
Due to a misunderstanding about how the entities/actions are encoded
inside the macaroon, only the first action was printed per entity.
Even though we add them as separate pairs in the macaroon service (for
example "offchain:read" and "offchain:write"), they are grouped in the
serialized macaroon ("offchain:read,write").
> lncli: print all permission actions

- cmd/lnd/main.go
Recently discovered that we display the help twice when `--help` is requested.
This PR is a trivial fix for that.
> config: prevent displaying usage twice if --help was requested

- cmd/lncli/main.go
- cmd/lncli/profile.go
- config.go
- lnd.go
- sample-lnd.conf
- server_test.go
This commit enables lnd to request and renew a Let's Encrypt certificate. This certificate is used both for the grpc as well as the rest listeners. It allows clients to connect without having a copy of the (public) server certificate.
In addition to this, it fixes a bug where wildcard ip instantiation (introduced in https://github.com/lightningnetwork/lnd/pull/2247) wasn't carried out for the wallet unlocker service.
Most important: the `lnd` instance must be reachable via a domain name. Let's Encrypt certificates are tied to domain names.
New flags added to the `lnd` command line and `lnd.conf`:
* `--letsencryptport`
The port on which lnd will listen for Let's Encrypt challenges. Let's Encrypt will always try to contact on port 80. Often non-root processes are not allowed to bind to …
> lnrpc: let's encrypt certificates

- lnd.go
- walletunlocker/service.go
This is required to make restart work for LndMobile builds.
Not calling `UnloadWallet` would make `UnlockWallet` stall forever on the second run as the file is already opened.
This was pretty much a non-issue for the normal UNIX daemon build, as sending `stopDaemon` or `SIGINT` would close down the process and Go's runtime would presumably handle any open files.
But on mobile builds, this is not the case, thus we have to explicitly close it down.  
Right now I'm just grabbing the loader all the way to `Main` and `defer`-ing the call so that it will execute once we get a `shutdownChan` signal, I'm unsure if this is the best approach.
N.B: wallet has to be opened for the main RPC server to function properly.
This is a part of an on-going work to address mobile restarting problems #4492.
> lnd: Call loader.UnloadWallet on shutdown

- config.go
This PR disables the disk space healthcheck by default. Since this check is less critical than our chain connection, and may disrupt existing nodes that upgrade (specifically mobile), we disable it by default. 
Tagging 0.11.1 for now, label should be removed if we decide not to include health checks in 0.11.1.
> config: disable disk space health check by default

- healthcheck/diskcheck_netbsd.go
- healthcheck/diskcheck_openbsd.go
Without these changes, the disk check portions won't compile on these
platforms.
> healtcheck: add extra build tags+files for netbsd and openbsd

- lnrpc/routerrpc/config.go
- lnrpc/routerrpc/routing_config.go
- routing/integrated_routing_context_test.go
- routing/pathfind.go
- routing/pathfind_test.go
- routing/router_test.go
- sample-lnd.conf
- server.go
In https://github.com/lightningnetwork/lnd/pull/2802 probability based routing was introduced. One of the control parameters introduced is the payment attempt cost.
The payment attempt cost is a virtual cost that is assigned to a failed payment attempt. This parameter influences the trade off between cheap and reliable routes. Specifically it adds an extra term to the pathfinding cost function of `attempt_cost / probability`.
Probability estimation is based on past failures and successes. The impact of failures on probability estimates diminishes relatively quickly (default "half life time" is one hour), but success experiences keep having a constant effect on probability until a failure happens.
For a presentation about mission control, see …
> routing: proportional attempt cost

- .travis.yml
To speed up tests and also not DoS termbin and file.io, we only upload
the integration test logs on failure.
> travis: only upload log files on test failure

- chainntnfs/txnotifier.go
- chainntnfs/txnotifier_test.go
When we cancel a confirmation request, we should remove the request from
the height map regardless of the current height. Otherwise we end up in
the situation when the height is reached, the notification is attempted
sent which results in a crash.
> [bugfix] txnotifier: delete ntfn by confirm height always

- sample-lnd.conf
This PR removes the duplicate `tor.streamisolation` option from `sample-lnd.conf` example config file. It looks like the option was accidentally added by 2284d8c.
> docs: remove duplicate "tor.streamisolation" option from sample-lnd.conf

- config.go
- lnd.go
- sample-lnd.conf
To make it possible to request a Let's Encrypt certificate by using a
different IP address where the port 80 might still be free, we add the
IP part to its configuration as well instead of just the port.
This makes it possible to use an IPv6 address for the ACME request if
all available IPv4 addresses already have their port 80 occupied.
I've tested this successfully with IPv6 as I'm suffering from having all IPv4 port 80 occupied.
> lnd+config: allow Let's Encrypt listen IP to be set

- .github/workflows/main.yml
- Makefile
- channeldb/kvdb/etcd/commit_queue.go
- channeldb/kvdb/etcd/commit_queue_test.go
- channeldb/kvdb/etcd/db.go
- channeldb/kvdb/etcd/db_test.go
- channeldb/kvdb/etcd/embed.go
- channeldb/kvdb/etcd/stm.go
- channeldb/kvdb/etcd/stm_test.go
- make/testing_flags.mk
~rebased on https://github.com/lightningnetwork/lnd/pull/4411~
now on master since #4411 is merged
This PR adds (and integrates) `commitQueue` which' purpose is to detect conflicts for concurrently applied transactions and effectively reduce retries, by applying queuing up conflicting transactions for sequential execution, while leaving all non-conflicting ones to run freely (potentially in parallel).
> etcd: STM transaction queue to effectively reduce retries for conflicting transactions

- breacharbiter.go
- contractcourt/anchor_resolver.go
- contractcourt/channel_arbitrator.go
- input/input.go
- lntest/itest/lnd_channel_backup_test.go
- lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_local_timeout_test.go
- lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
- lntest/itest/lnd_multi-hop_local_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/lnd_multi-hop_remote_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/lnd_multi-hop_test.go
- lntest/itest/lnd_test.go
- lnwallet/channel.go
- sweep/sweeper.go
- sweep/sweeper_test.go
- sweep/test_utils.go
- sweep/tx_input_set.go
- sweep/txgenerator.go
- sweep/txgenerator_test.go
- sweep/walletsweep.go
- sweep/weight_estimator.go
- sweep/weight_estimator_test.go
This PR modifies the sweeper to take into account potential unconfirmed parent transactions. This enables tracking of the current fee estimate for anchors of not yet confirmed commitment transactions. Previously an anchor-commitment that wouldn't confirm needed to be bumped manually.
`2020-09-08 11:20:19.860 [INF] SWPR: Creating sweep transaction 1b76f06cd667c4d611ce9bd397634e97ac5539e960507c5ad0202965dcae481d for 2 inputs (7d1d2012a7ba95cd8140c47f4688ae0114ae9a88ebfadda107408fd937cfa92b:0 (CommitmentAnchor), ab682225912097d789c33b06b14d1d730869a3869e9b558537085ab2dcef2250:1 (WitnessKeyHash)) using 20000 sat/kw, tx_weight=719, tx_fee=0.0002546 BTC, parents_count=1, parents_fee=0.0001124 BTC, parents_weight=1116`
> cnct+sweep: cpfp-aware anchor sweeping

- config.go
Fixes https://github.com/lightningnetwork/lnd/issues/4572.
With this PR we make sure that all directories where lnd could
potentially want to write files to are created on startup. This fixes
the case where the lnddir isn't set but all other paths point to
explicit locations with non-existend parent directories.
We don't create the log dir as that's done by the log rotator already.
> config: create all directories

- watchtower/blob/justice_kit.go
- watchtower/blob/justice_kit_test.go
- watchtower/blob/type.go
- watchtower/blob/type_test.go
- watchtower/lookout/justice_descriptor.go
- watchtower/lookout/justice_descriptor_test.go
- watchtower/lookout/lookout_test.go
- watchtower/wtclient/backup_task.go
This PR is the first in a series that will enable watchtower support for anchor channels in 0.12.
We start by adding a new `blob.FlagAnchorChannel` indicating whether an encrypted blob is
supposed to spend an anchor channel. Upon successful decryption, this bit is used to signal
that the tower needs to craft the justice txn such that properly spends a `to_remote_confirmed`
p2wsh input rather than the legacy `to_remote` p2wkh input.
The good news is that these changes require no modification of the encrypted payload format.
The anchor payloads are equal size and contain exactly the same witness info as the legacy
payloads, only requiring light modifications to the reconstruction logic.
> watchtower: conditionally reconstruct justice txns for anchor channels

- sample-lnd.conf
The godocs [page](https://godoc.org/github.com/lightningnetwork/lnd#Config) for lnd mentions that a disabled `sync-freelist` translates to an increased startup time. This would mean it'd decrease the startup time when enabled, and is wrongly stated to do the opposite here.
> docs: fix sync-freelist documentation

- chainregistry.go
- config.go
- docs/INSTALL.md
- lncfg/neutrino.go
This PR adds the ability to alter the neutrino useragent string so that neutrino clients can identify themselves as they please.
It exposes the neutrino `UserAgentVersion` and `UserAgentName` config options which can be set by starting lnd with the `--neutrino.useragentversion=` and `--neutrino.useragentname=` flags.
This enables btcd nodes to better identify connecting clients. For example, it could be used in conjunction with [btcd's `agentblacklist` and `agentwhitelist` settings]( https://github.com/btcsuite/btcd/pull/1418) to ensure that only clients that identify themselves in a specific way are allowed to connect.
> Ability to configure neutrino useragent

- fuzz/brontide/fuzz_utils.go
Docker build revealed that the brontide fuzzers are broken since the ECDH changes.
> fuzz/brontide: fix fuzz_utils.go NewBrontideMachine callsites

- brontide/noise_test.go
- macaroons/constraints_test.go
This commit fixes a go 1.15 vet check.
In doing so it uncovers that the time caveat check is actually reversed.
Since we should check that the caveat is added, we should only fail the
check when the caveat prefix is not equal.
> [tests] reverse macaroon time caveat check, fix go 1.15 vet check.

- go.mod
- go.sum
- lntest/bitcoind.go
- lntest/btcd.go
- lntest/itest/lnd_test.go
- lntest/neutrino.go
This PR tries to make it easier to catch flakes in itest. It,
- catches error when miner tears down.
- caches error when chain backend cleans up.
- disables chain backend retrying connection to the miner.
The last one is somewhat tricky. Before this fix, the `btcd` chain backend automatically retries connecting to the miner on several occasions,
- during the test setup, when miner was not ready, it tried to connect and failed, then it would retry it in 5s, as shown in the log,
```python
2020-08-29 16:24:04.980 [DBG] CMGR: Retrying connection to 127.0.0.1:11160 (reqid 1) in 5s
```
- in the test `testOpenChannelAfterReorg`, we manually disconnected the chain backend and the miner. Still, the chain backend retried in 5s and succeeded.
- and other occasions, which can be found in the logs. …
> Itest: proper connect/disconnect miner

- lntest/itest/log_error_whitelist.txt
Looks like the whitelist needs to be updated.
> itest: update log error whitelist

- htlcswitch/switch.go
Properly randomize link selection instead of relying on the undefined order of a map.
> htlcswitch: randomize non-strict forwarding

- healthcheck/healthcheck.go
In this commit, we bump up the logging for failed healthchecks from
`debug` to `info`. This should help us get to the bottom of the current
set of reported false positives that are causing `lnd` nodes to
erroneously shutdown.
> healthcheck: bump logging for failed healthchecks to info

- cmd/lncli/walletrpc_active.go
- docs/psbt.md
- go.mod
- go.sum
- lnrpc/walletrpc/walletkit_server.go
~Depends on https://github.com/btcsuite/btcwallet/pull/722.~
Fixes https://github.com/lightningnetwork/lnd/issues/4670.
This PR fixes an oversight in the way nested SegWit inputs are added to the unsigned TX of a PSBT.
The fix itself is in `btcwallet`.
We also fix a small cosmetic issue in the way the locked UTXOs are returned and displayed in the command line.
> PSBT funding: don't include scriptSig field for nested SegWit inputs

- config.go
- sample-lnd.conf
Correct me if I'm wrong, but this seems incorrect, and local testing confirms.
Input:
> autopilot.heuristic={topk_centrality:1}
Result:
> strconv.ParseFloat: parsing "1}": invalid syntax
Input:
> autopilot.heuristic=topk_centrality:1
Result:
> heuristic topk_centrality not available. Available heuristics are: [ 'preferential'  'externalscore'  'top_centrality' ]
It's causing confusion, e.g. here: https://www.reddit.com/r/lightningnetwork/comments/j29ai3/how_to_enable_the_new_autopilot_heuristic_in_v0110/
> [autopilot] change default heuristic to top_centrality

- channeldb/payment_control.go
- htlcswitch/payment_result.go
- htlcswitch/payment_result_test.go
- htlcswitch/switch.go
- routing/mock_test.go
- routing/router.go
~~This commit makes GetPaymentResult return a channel that should be closed by the caller when the result from the result channel is handled. This instructs the Switch that it is safe to delete the result from its
database.~~
~~We make the router close this channel after it has successfully recorded the result, or decided it can re-attempt~~
This is a follow-up from #2762 and is not critical for the operation of `lnd`, but the network results would never be deleted from the Switch's store, causing them to take up space. This fixes that by deleting them when we *know for sure* that the router has handled the result, and won't need it anymore.
~~There is still a gap that can happen if we crash after the router has acked the result, but before the switch has deleted the payment, but in the …
> [reliable payments] switch result store clean-up

- .github/workflows/main.yml
- .travis.yml
- Makefile
This commit updates our CI to build and run against the newly release Go 1.15 version. I don't think we should merge this quite yet, as in the past we've been burned by attempting to upgrade to the latest Go version _too quickly_. However, once we're confident in this new version, then we can start to use any new language and standard library features that were included as part of Go 1.14.
> build: build and run CI against Go 1.15

- lntest/itest/log_error_whitelist.txt
Adds the following error to the itest error whitelist:
`<time> [ERR] HSWC: ChannelLink(<chan>): failing link: ChannelPoint(<chan_point>): received error from peer: chan_id=<hex>, err=unable to resume channel, recovery required with error: remote error`
> itest: add error to whitelist

- .github/workflows/main.yml
- .travis.yml
- scripts/install_bitcoind.sh
Because the bitcoind mirror is extremely slow, we spend at least 2 to 3
minutes of each bitcoind related test on just downloading the binary. We
can achieve the same result by just pulling the docker image and
extracting the binary from that.
Speedup (observed):
- GitHub: `0:13 min` now vs. `2:37 min` before
- Travis: `0:18 min` now vs. `2:25 min` before
> Travis+GitHub: update bitcoind to 0.20.1, extract bitcoind binary from docker image to speed up download

- fuzz/brontide/random_actone.go
- fuzz/brontide/random_actthree.go
- fuzz/brontide/random_acttwo.go
- fuzz/brontide/random_init_enc_dec.go
- fuzz/brontide/random_init_encrypt.go
- fuzz/brontide/random_resp_enc_dec.go
- fuzz/brontide/random_resp_encrypt.go
- fuzz/brontide/static_actone.go
- fuzz/brontide/static_actthree.go
- fuzz/brontide/static_acttwo.go
- fuzz/brontide/static_init_enc_dec.go
- fuzz/brontide/static_init_encrypt.go
- fuzz/brontide/static_resp_enc_dec.go
- fuzz/brontide/static_resp_encrypt.go
- fuzz/lnwire/accept_channel.go
- fuzz/lnwire/fuzz_utils.go
- fuzz/lnwire/node_announcement.go
- fuzz/lnwire/open_channel.go
- fuzz/wtwire/fuzz_utils.go
This allows gofuzz to store the mutating input as coverage if it reaches any new coverage, even if it didn't make it to the end of the test.
> fuzz: change return values to 1 rather than 0 or -1

- .github/pull_request_template.md
- .github/workflows/main.yml
- Makefile
- sample-lnd.conf
This PR adds a check to the GitHub workflow that checks that all command line flags of `lnd` that are available using the default build tags are described in the `sample-lnd.conf` file.
All currently missing flags are also added to that file with a separate commit.
> GitHub workflow: Check all command line flags are described in sample-lnd.conf

- fuzz/zpay32/decode.go
- fuzz/zpay32/encode.go
These can be expanded on in the future. Haven't turned up anything which is good. Encoding is currently done with a static key for test determinism. Can be expanded in the future for another test with random key.
> fuzz/zpay32: add Decode/Encode fuzz tests.

- lntest/itest/lnd_test.go
This fixes itest flakes that happen when a payment is attempted that
ends up causing a channel closure.
completePaymentRequests() attempts to monitor the open channels after a
payment is attempted in order to identify that payment was actually
dispatched to a remote node before returning.
However, when the payment actually causes a channel closure (for
example, because the receiver sent an incorrect preimage) this logic
fails in that the channel will no longer the found in the list of open
channels. This could cause a flake when there was enough time for the
channel to close before performing the check.
One example of such a flaky test is failing_link.
This fixes the issue by also checking whether the total number of
channels was reduced, which indicates (assuming itest operations are …
> itest: Fix flakes when payments cause chan closure 

- chanfitness/chaneventstore.go
Stop the ticker after the goroutine reading from it has exited, to avoid
triggering the race detector.
> chanfitness/chaneventstore:  stop ticker after goroutine

- lntest/harness.go
- lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_local_timeout_test.go
- lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
- lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
- lntest/itest/lnd_multi-hop_local_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/lnd_multi-hop_remote_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/lnd_test.go
- lntest/itest/log_error_whitelist.txt
This PR was split off from #4655 and contains some cleanup and two smaller flake fixes.
Possibly the second flake fix isn't necessary if #4268 is implemented. I'm not too familiar with HTLCs and their CSVs.
> itest: cleanup and flake fix

- lntest/itest/lnd_multi-hop_htlc_local_timeout_test.go
- lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
- lntest/itest/lnd_multi-hop_local_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/lnd_test.go
Many instances where the itests mine `defaultCSV` blocks (to wait for a sweep of a CSV-encumbered output) have an off-by-one error. This causes flaky tests when the CI slows downs during mining.
This fixes those tests by introducing a debug function to slowly mine blocks (thus causing the buggy tests to show themselves) then adjusting the number of mined blocks as needed.
> itest: fix off-by-one mining while waiting for CSV-encumbered outputs

- signal/signal.go
SIGABRT is used by the Go runtime to forcefully terminate all
goroutines, even if they are in a deadlocked state.
It is useful in development (to get a glimpse of any potential race or
hang conditions) and in production to forcefully terminate execution
when a standard SIGQUIT won't do.
This modifies the signal package to _not_ trap SIGABRT and let it be
handled in the standard way by the runtime.
> signal: do not trap SIGABRT

- lnwallet/btcwallet/btcwallet.go
A while back, changes were made to the wallet such that it waits for the backend to be synced before beginning to store the latest 10,000 blocks of the chain. This inherently broke sync progress implementations based on the best_header_timestamp result from the GetInfo RPC for neutrino-based nodes as the wallet is no longer tracking all blocks in the chain. To work around this, we now make sure to return the backend's best header timestamp instead of the wallet's, allowing said sync progress implementations to work again.
One potential drawback of the approach taken in this PR is that the best header timestamp can decrease (causing the sync progress to momentarily decrease) if it's called twice in succession, the first being right as the chain backend is synced and the second being right …
> btcwallet: return chain best timestamp while backend is syncing

- .gitignore
- .travis.yml
- Makefile
- lntest/bitcoind_common.go
- lntest/btcd.go
- lntest/fee_service.go
- lntest/itest/lnd_channel_backup_test.go
- lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
- lntest/itest/lnd_test.go
- lntest/itest/lnd_test_list_off_test.go
- lntest/itest/lnd_test_list_on_test.go
- lntest/itest/test_harness.go
- lntest/node.go
- make/testing_flags.mk
- scripts/itest_part.sh
Depends on https://github.com/lightningnetwork/lnd/pull/4268, only the last 8 commits are new.
This PR splits all integration tests in 4 distinct groups and runs them in parallel. This creates a bit of overhead by creating the test harness (mining btc node, chain backend btc node and two lnd nodes) four times.
But that easily offset by running the tests in parallel and saturating the CPU much better.
(master at 9c9ce15ca679b15b73d00c6e912ea93d1458b5eb)
(this PR at 15420639767e0bffe01d8fa22cc73c5de13390da)
- Btcd: 62%
- Bitcoind with txindex: 58%
- Bitcoind without txindex: 59%
- Neutrino: 64%
- Btcd ARM: 70%
- Btcd Windows: 55%
There still are some flakes in the itests. But I feel that they are on an acceptable level with all the recent fixes. Still, the following list gives an indication …
> Travis: run itests in parallel, get ~60% speedup overall

- lnwallet/chanfunding/coin_select.go
- lnwallet/chanfunding/coin_select_test.go
It seems that the dust-output and high-fee test cases for `CoinSelectSubtractFees` were not independently testing the code as the one triggered the other and vice versa due to testing with low fee values that gave rise to dust outputs (see also comments for the commits).
Also a new test case `"spend with change"` was added to check that a non-zero change output can be created.
logging level
per default)
already exist
cases it can be justifiable …
> chanfunding: Add/improve tests for CoinSelectSubtractFees

- aezeed/cipherseed.go
- aezeed/cipherseed_test.go
A user complained about getting a misleading error after a typo in the
mnemonic. The word was `hear` and it passed the check even when it is
not in the list of valid words.
The reason is that we where checking if the word is in the variable
`englishWordList` (which includes all the words) instead of checking if the
variable is in the `defaultWordList` (which is basically `englishWoldList`
split by spaces). That means that `hear` passed the check because `heart`
appears in the list.
Related issue [4733](https://github.com/lightningnetwork/lnd/issues/4733)
> aezeed: fix mnemonic word validation

- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/linkfailure.go
- peer/brontide.go
According to BOLT#1, a when receiving an error from the remote, we MUST fail the targeted channel: https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#the-error-message
This PR implements this behavior by marking the channel `Borked` in cases like this. We don't automatically force close, to avoid the remote tricking us into force closing.
> Mark channels borked in case of remote error

- config.go
- lncfg/address.go
- lnd.go
- rpcserver.go
- sample-lnd.conf
Supersedes #2277, disabling TLS for REST ~~and gRPC~~ connections.
> RPC: add --no-rest-tls option

- Makefile
- docs/MAKEFILE.md
- lntest/itest/lnd_test.go
- make/testing_flags.mk
To make it easier to hunt down the flakes in the integration tests, we add a way to run the same flaky tests multiple times in parallel to try to provoke the flaky behavior. This can also be done for multiple tests in a row if a dependency is expected.
Example:
```
make flakehunter-parallel icase='(data_loss_protection|channel_backup)' backend=neutrino
```
> itest: add parallel flakehunter

- watchtower/wtclient/candidate_iterator.go
- watchtower/wtclient/client.go
- watchtower/wtdb/client_db.go
- watchtower/wtdb/client_db_test.go
- watchtower/wtmock/client_db.go
This addresses a potential panic when a tower has one of its candidate sessions chosen, but its only reachable address was removed by a user-initiated RPC before the fact.
Fixes #4739.
> watchtower: prevent removal of last tower addr

- chainreg/chainregistry.go
- server.go
Previously we were using `GetBestBlock` for all of our healthchecks. This was running into some issues with `bitcoind`, because the `GetBestBlock` rpc call uses the csmain lock, which is widely used, and would block for extended periods of time (5 minutes sometimes!). `btcd` has more granular locking, so it does not face these issues. 
This PR updates our chain backend health check to use the `uptime` api because it has no locking. Another option would be to use something like `estimatesmartfee` which uses a less common lock in `bitcoind` and does not need us to make an ad-hoc `rpcclient`. Decided against this because `estimatesmartfee` could crunch through mempool data unnecessarily. 
Fixes #4669.
> multi: use bitcoind uptime api for healthcheck

- config.go
- docs/recovery.md
- go.mod
- go.sum
- lnd.go
- sample-lnd.conf
Depends on https://github.com/btcsuite/btcwallet/pull/723.
This PR adds the functionality of `btcwallet`'s `dropwtxmgr` command to `lnd`. Users can trigger the functionality by specifying the command line flag `--reset-wallet-transactions` or setting the value `reset-wallet-transactions=true` in the configuration file.
The new flag removes all transaction history from the internal on-chain wallet, resulting in a full chain-rescan starting at the wallet's birthday.
> Implement btcwallet's "dropwtxmgr" command as --reset-wallet-transactions flag

- lnrpc/routerrpc/router_server.go
The 'payment already exists' case is common in restart scenarios. With this change it is no longer necessary to string-match on the error message. Implementation is identical to `SendPaymentV2`.
> routerrpc: map errors to grpc status code

- lnrpc/invoicesrpc/addinvoice.go
- lnrpc/invoicesrpc/invoices_server.go
- lnrpc/invoicesrpc/utils.go
- lntest/itest/lnd_single_hop_invoice_test.go
- rpcserver.go
This PR changes the `AddInvoice/AddHoldInvoice `RPC endpoints to be able to get routing hints and populate them in the resulted invoice.
In fact the `RoutingHints` already existed in both `lnrpc.Invoice` and `lnrpc.AddHoldInvoiceRequest` but were ignored and this change only adds them to the invoice.
This is useful in the following cases:
1. When ones want to expose specific private channels, or to get payment via them.
2. When the default routing hints logic skips some channels due to incomplete graph state (see issue https://github.com/lightningnetwork/lnd/issues/3660). This is specifically important to enable receiving funds on mobile wallets that just bootstrapped with a new channel.
> Allow user specify routing hints in private invoice.

- lnd.go
#4715 needed to be rebased again before merge, this PR adds the missing return param that is currently breaking the build. 
```
github.com/lightningnetwork/lnd
./lnd.go:1324:5: not enough arguments to return
have (nil, error)
want (*WalletUnlockParams, func(), error)
make: *** [build] Error 2
```
> lnd: return missing shutdown parameter

- .gitignore
- lntest/harness.go
- lntest/itest/lnd_macaroons_test.go
- lntest/itest/lnd_test.go
- lntest/itest/log_error_whitelist.txt
- lntest/node.go
This PR changes the itest harness to make it possible to restart the harness nodes (Alice & Bob) before each icase while also changing the way we name icase node logs, to make it easier to see which logs belong to which icase.
> itest: clean harness state before each icase and better naming for icase logs

- lncfg/chain.go
- sample-lnd.conf
- server.go
Fixes https://github.com/lightningnetwork/lnd/issues/3817.
Need to manually test on testnet, but should be pretty straightforward.
> discovery: allow DNS seeds to be overwritten

- feature/default_sets.go
It's been sometime since we introduced this new safety enhancing feature
bit. At this point, we're now moving to require it as it makes our SCB
recovery system more robust, and it's also an implicit feature bit for
for anchor commitments as they're defined now.
> feature: flip static remote key from optional to required

- contractcourt/briefcase.go
- contractcourt/briefcase_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
Fixes #4481:
* Use a shared transaction to do initial lookups when starting our arbitrators 
* Use a single block epoch notification stream for all channel arbitrators
With the change set as is, we reduce the number of database transactions we use from 2n to 1. However, if any of these channels are no longer in default state, they will still perform additional db transactions as they advance their state in `stateStep`. Using a single block notification stream reduces goroutines required to deliver blocks from 2n to n. 
(n = number of arbitrators)
Having some grief with the itests for these, still figuring it out. 
We’ve also discussed the prospect of passing a single transaction into `stateStep` so that we can step all of our transactions with a single tx on block arrival and startup. …
> contractcourt: batch startup reads and block epoch notifications

- .github/workflows/main.yml
- channeldb/db.go
- channeldb/kvdb/backend.go
- channeldb/kvdb/bolt_compact.go
- channeldb/kvdb/config.go
- channeldb/kvdb/log.go
- channeldb/log.go
- channeldb/options.go
- go.mod
- healthcheck/diskcheck.go
- healthcheck/diskcheck_netbsd.go
- healthcheck/diskcheck_openbsd.go
- healthcheck/diskcheck_solaris.go
- healthcheck/diskcheck_windows.go
- htlcswitch/decayedlog.go
- htlcswitch/decayedlog_test.go
- lncfg/db.go
- lnd.go
- make/release_flags.mk
- sample-lnd.conf
- server.go
Fixes https://github.com/lightningnetwork/lnd/issues/4131.
Can be turned on with `--db.bolt.auto-compact` in the command line or `db.bolt.auto-compact=true` in the configuration file.
This PR also includes two changes that aren't directly related to compaction:
- Compile for every architecture on Travis to make sure all architecture dependent compilation succeeds.
- Remove `darwin-386` from the list of target architectures as it isn't supported by `go 1.15.x` anymore.
> channeldb/kvdb/bolt: automatically compact database on startup

- lnrpc/walletrpc/walletkit.pb.go
- lnrpc/walletrpc/walletkit.proto
- lnrpc/walletrpc/walletkit.swagger.json
- lnrpc/walletrpc/walletkit_server.go
- lntest/itest/lnd_test.go
> multi: update listsweeps to allow sweeps that are not in ListTransactions

- build/log.go
- build/log_test.go
- config.go
- sample-lnd.conf
This makes it possible to specify both a global+subsystem loglevels,
like:
```
--debuglevel=debug,PEER=info,SRVR=trace
```
> build/log: support parsing global+subsystem levels

- channeldb/kvdb/config.go
- lncfg/db.go
- lntest/harness.go
- lntest/itest/lnd_test.go
- lntest/node.go
- lntest/timeouts_etcd.go
- make/testing_flags.mk
- sample-lnd.conf
This PR adds `etcd` flag to the `itest` binary which controls whether new nodes created during tests should run on embedded etcd too. The flag is also added to the our makefile, such that running `make itest etcd=1` will run the integration tests with the `kvdb_etcd` build tag and also run integration tests with embedded etcd.
This PR is part of a multi PR effort to LND stable on etcd+bbolt:
~Key derivation: https://github.com/lightningnetwork/lnd/pull/4411~
~Reducing commit conflicts by lightweight tx queueing: https://github.com/lightningnetwork/lnd/pull/4457~
Rebased on: 
- ~External state reset: https://github.com/lightningnetwork/lnd/pull/4705~ merged
- ~Node restart before each icase: https://github.com/lightningnetwork/lnd/pull/4737~ merged
- ~@matheusd's flake fixes: …
> itests: option to run our integration tests on etcd + boltdb (remote/local)

- lntest/timeouts.go
- lntest/timeouts_darwin.go
- lntest/timeouts_etcd.go
This PR removes spaces from the timeout build predicates, which causes parsing errors
when compiling/linting darwin targets. We also correct the timeouts to use the etcd
timeouts when running w/ `darwin,kvdb_etcd`, which currently fall back to plain darwin
timeouts.
> lntest/timeouts: fix timeout build predicates

- autopilot/agent.go
Looks like we are allocating extra `len(c)` for the size of `res`.
> autopilot: fix returned map size in mergeNodeMaps

- .github/workflows/docker.yml
We add a GitHub workflow that is triggered whenever a new version tag is
pushed. It will trigger a docker image build for that version and
automatically push it to the specified repo.
For this to work, the GitHub repository needs the following two secrets to be configured:
```
DOCKER_USERNAME: <the user to log into Docker Hub>
DOCKER_API_KEY: <an API key generated by Docker Hub for the above user>
```
> GitHub: add workflow for building tagged docker images

- lnwallet/channel.go
- lnwallet/channel_test.go
This PR fixes a bug that would result in the wrong weight being calculated for the remote commitment for HTLCs close to the dustlimit.
> Correct HTLC dust calculation for remote commitment weight

- breacharbiter.go
- input/input.go
- input/size.go
- rpcserver.go
- sweep/backend_mock_test.go
- sweep/sweeper.go
- sweep/sweeper_test.go
- sweep/tx_input_set.go
- sweep/tx_input_set_test.go
- sweep/txgenerator.go
- sweep/walletsweep.go
- sweep/walletsweep_test.go
- sweep/weight_estimator.go
- sweep/weight_estimator_test.go
This PR adds support for inputs that put extra restrictions on the sweep tx, namely a locktime and accompanied output.
Two methods are added to the `Input` interface that for most normal inputs will do nothing:
```go
// RequiredTxOut returns a non-nil TxOut if input commits to a certain
// transaction output. This is used in the SINGLE|ANYONECANPAY case to
// make sure any presigned input is still valid by including the
// output.
RequiredTxOut() *wire.TxOut
// RequiredLockTime returns whether this input commits to a tx locktime
// that must be used in the transaction including it.
RequiredLockTime() (uint32, bool)
```
For certain inputs though, this is needed. Most notably we plan to use this for sweeping and aggregation of second level HTLC transactions for anchor channels. Since these …
> Sweeper: support Inputs with required locktimes and txOuts

- htlcswitch/link.go
- htlcswitch/link_test.go
Since it turned out borking channels on every received error could cause
us to bork channels in case of a sync error with C-lightning, we revert
this for now.
See #2018 and https://github.com/ElementsProject/lightning/issues/4212
Fixes https://github.com/lightningnetwork/lnd/issues/4776
> htlcswitch/link: revert borking channels on received Errors

- .github/workflows/release.yaml
- scripts/release.sh
This commit adds another GitHub workflow that is activated for each
pushed tag. The release binaries are compiled from that tag for all
supported architectures. A new release in the GitHub repository is then
created for the tag and the finished binary packages are uploaded to
that release.
Example build can be seen here: https://github.com/guggero/lnd/runs/1423819682?check_suite_focus=true
Result can be seen here: https://github.com/guggero/lnd/releases/tag/v0.0.0-beta.test3 (taken out of draft mode manually for it to be visible to anyone).
Before the manual edit, it looked like this (confirming draft mode):
> GitHub: build release binaries and upload to release

- channeldb/graph.go
- discovery/gossiper.go
- discovery/gossiper_test.go
- lnwire/channel_update.go
This change was largely motivated by an increase in high disk usage as a result of channel update spam and serves as an initial step towards https://github.com/lightningnetwork/lnd/issues/4724. With an in memory graph, this would've gone mostly undetected except for the increased bandwidth usage, which this doesn't aim to solve yet. To minimize the effects to disks, we begin to rate limit channel updates in two ways. Keep alive updates, those which only increase their timestamps to signal liveliness, are now limited to one per lnd's rebroadcast interval (current default of 24H). Non keep alive updates are now limited to one per block per direction.
> discovery: rate limit incoming channel updates

- batch/batch.go
- batch/interface.go
- batch/scheduler.go
- channeldb/db.go
- channeldb/graph.go
- channeldb/graph_test.go
- channeldb/options.go
- discovery/gossiper.go
- lncfg/db.go
- lnd.go
- lntest/itest/lnd_test.go
- lntest/node.go
- routing/router.go
- sample-lnd.conf
This PR introduces batched operations for channel graph ingestion in order to speed up IGD. Currently a single db transaction is used to process each `channel_announcement`, `channel_update`, and `node_announcement`, which with the current graph size results in around 160k-200k transactions.
With this PR we bring this down to linear in the duration it takes the sync the graph, as we'll no make at most 2 db transactions/sec. OMM I was able to get a 4 minute graph sync using this, implying only about 500 db transactions were made in total.
So far I'm seeing a 2x speedup in IGD. The CPU and memory usage should be much lower, but I'm still in the process of tuning and gathering exact performance metrics.
To accomplish this, we introduce a new `batch` package, which exposes a simple API for …
> Batched graph updates

- watchtower/wtclient/client.go
- watchtower/wtclient/client_test.go
- watchtower/wtclient/session_negotiator.go
Currently the ForceQuit call is scheduled after trying to stop the
backup queue. In certain cases, the call to stop the queue never
finishes, which means the force quit is never scheduled. We rememdy by
scheduling this call before any other operations to ensure we can always
exit ungracefully if necessary.
Fixes #4586
> wtclient: schedule ForceQuit first during Stop

- lnd.go
- tor/tor.go
- tor/tor_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/4803.
With https://github.com/lightningnetwork/lnd/pull/737 we intended to add Tor support for Neutrino backends.
Either something changed since that PR or we never fully tested this. Before this fix it was not possible to use an Onion v2 address for the `--neutrino.connect` flag.
With this PR we make it possible to use an Onion v2 hidden service
address as the Neutrino backend.
This failed before because an .onion address cannot be looked up and
converted into an IP address through the normal DNS resolving process,
even when using a Tor socks proxy.
Instead, we turn any v2 .onion address into a fake IPv6 representation
before giving it to Neutrino's address manager and turn it back into an
Onion host address when actually dialing.
To …
> Fix Onion v2 support for Neutrino backends

- discovery/gossiper.go
- discovery/gossiper_test.go
- lncfg/protocol_legacy_off.go
- lncfg/protocol_legacy_on.go
- lntest/node.go
- server.go
In this PR, we add a new legacy protocol config option to allow the itests to enable/disable gossip throttling for each new node (default is no throttling in the itests). We also pull in a commit meant to restore stability to the set of itests by reducing the number of parallel itests execution instances to 1 (effectively disabling the parallelization).
> multi: add new config option to toggle gossip rate limiting 

- lntest/itest/lnd_test.go
To avoid the "Error outside of test" log and to properly terminate the
test if a sub test fails, we need to correctly invoke them using the
RunTestCase method.
> itest: run sub itests correctly for watchtower tests

- lnd.go
Adds a newline to the end of a log statement.
[reference issue](https://github.com/lightningnetwork/lnd/issues/3801)
> Cosmetic: Add newline to end of log statement

- config.go
- lncfg/healthcheck.go
- sample-lnd.conf
- server.go
> In certain container set ups, it's useful to optionally have lnd just shutdown if it detects that its certs are expired, as assuming there's a hypervisor to restart the container/pod, then upon restart, lnd will have fully up to date certs.
Adds a configurable healthcheck that shuts down if an expired certificate is found.
[Reference issue](https://github.com/lightningnetwork/lnd/issues/4761)
> tls: Add healthcheck to shutdown if certificate is expired

- .gitignore
- .travis.yml
- Makefile
- chainntnfs/interface_test.go
- chainntnfs/test_utils.go
- go.mod
- go.sum
- lntest/btcd.go
- lntest/itest/lnd_test.go
- lntest/node.go
- lnwallet/interface_test.go
- make/testing_flags.mk
- routing/chainview/interface_test.go
- scripts/itest_part.sh
This PR updates `btcd` to current master and fixes some flakes that were caused by `btcd`'s random listening port selection during itests that sometimes resulted in collisions.
> Update btcd to master, make itest btcd harness more robust

- channeldb/channel.go
- channeldb/channel_test.go
- contractcourt/chain_watcher.go
- contractcourt/chain_watcher_test.go
- contractcourt/utils_test.go
- lnwallet/channel.go
- lnwallet/test_utils.go
This PR fixes a bug within the chain watcher, in case we lost state or attempted recovery **after** we had force closed. In this scenario we would use the wrong state number when deriving our local script, which caused us to ignore the `to_local` output and fail sweeping the funds.
Since we cannot tell from the state number directly if it's a local or remote force close, we move to first handle all known states before we use the state number to derive the scripts for our "future" state.
The scenario in question is added to the tests cases.
> chainwatcher: properly derive to_local script for "future" local force closes

- lntest/itest/lnd_forward_interceptor_test.go
While investigating the source of:
```
lnd_forward_interceptor_test.go:117: failed to send payment rpc error: code = Unknown desc = cannot attach payment addr
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeb4f01]
goroutine 2911 [running]:
github.com/lightningnetwork/lnd/lntest/itest.testForwardInterceptor.func2(0xc00036a130, 0xc00079aa40, 0x4, 0x4, 0xc0000d6cb0, 0xc0006c8540)
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_forward_interceptor_test.go:123 +0x221
created by github.com/lightningnetwork/lnd/lntest/itest.testForwardInterceptor
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_forward_interceptor_test.go:105 +0x38a
```
I noticed that the test …
> itest: fwd interceptor fixes

- htlcswitch/switch.go
Log message would look like
```
2020-12-08 13:43:51.445 [INF] HSWC: %v: hash=%v, pid=%d payment was resolved on-chain, then canceled back c5047d3bc9dcbd5a7754f759e1d56146c540fc5b647ca78535cc479bcd3e7d1e 2
```
> [trivial] htlcswitch: log with format

- lntest/itest/lnd_channel_backup_test.go
This PR fixes a bug in the current itest harness, resulting in this error on neutrino:
```
test_harness.go:91: Error outside of test: *errors.errorString unable to find Carol's force close tx in mempool: wanted 2, found 1 txs in mempool: [306027425abd0b846c54599169b911127cbc247b03b5ab4feb7fb2655f4f032e]
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:9574 (0xe98f5e)
assertDLPExecuted: t.Fatalf("unable to find Carol's force close tx in mempool: %v",
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_channel_backup_test.go:1065 (0xe45ab1)
testChanRestoreScenario: assertDLPExecuted(
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_channel_backup_test.go:374 (0xebb9db)
testChannelBackupRestore.func9: …
```
> itest: increase recovery payment amount so htlc isn't dust

- sweep/sweeper_test.go
- sweep/txgenerator.go
This commit fixes an issue that would arise if inputs without required TxOuts would be swept together with inputs with required TxOuts. In this case we would add the required ones first to the transaction, but did not change the order we signed the inputs, resulting in signing the wrong input index.
A unit test that triggers the scenario is added.
> sweep/txgenerator: fix input witness ordering

- channeldb/kvdb/etcd/embed.go
Instead of letting the OS pick a random port for us in a way that wasn't
concurrency safe, we use an atomically incremented port to avoid
collisions.
> etcd: increment port for embedded etcd server

- sweep/sweeper.go
- sweep/sweeper_test.go
We risked deadlocking on shutdown if a client (in our case a contract
resolver) attempted to schedule a sweep of an input after the
ChainNotifier had been shut down. This would cause the `collector`
goroutine to exit, and not handle incoming requests, causing a deadlock
(since the ChainArbitrator is being stopped before the Sweeper in the
server).
To fix this we could change the order these subsystems are stopped, but
this doesn't ensure there aren't other clients that could end up in the
same deadlock scenario. So instead we keep handling the incoming
requests even after the collector has exited (imemdiately returning an
error), until the sweeper is signalled to shutdown.
> sweeper: avoid deadlock on shutdown

- channeldb/graph.go
- channeldb/graph_test.go
- discovery/chan_series.go
- discovery/gossiper.go
- discovery/gossiper_test.go
- discovery/sync_manager.go
- discovery/sync_manager_test.go
- discovery/syncer.go
- discovery/syncer_test.go
As required by the spec, all channels for a block must fit within a single reply. `lnd` previously could not enforce this as it would allow an overlap of blocks across multiple replies. This became an even bigger issue as other implementations could send us a error due to the overlap and cause connect/disconnect cycles.
> discovery: adhere to proper channel chunk splitting for ReplyChannelRange

- lntest/itest/log_error_whitelist.txt
Looks like the neutrino itest builds currently fail mostly because of the new errors that aren't ignored.
> itest: add neutrino errors to whitelist

- chainntnfs/test/bitcoind/bitcoind_test.go
- chainntnfs/test/btcd/btcd_test.go
- chainntnfs/test/neutrino/neutrino_test.go
- chainntnfs/test/test_interface.go
- lnwallet/btcwallet/btcwallet_rpctest.go
- lnwallet/test/bitcoind/bitcoind_test.go
- lnwallet/test/btcd/btcd_test.go
- lnwallet/test/interface_test.go
- lnwallet/test/neutrino/neutrino_test.go
- lnwallet/test/test_interface.go
- make/testing_flags.mk
This predominately affects the lnwallet unit tests which are the bulk of
the execution time.
We also move around the way the interface tests are invoked, such that
they are called from distinct subpackages for each backend. This gives 
us free parallelism from the standard go test harness.
Together this shaves about 2 minutes (10%) of the `unit-race` execution
time.
> make: use low-scrypt + parallelization to speed up  unit-race

- .github/workflows/docker.yml
To enable building docker images for ARM64 platforms as well,
we just need to specify the desired target platforms and the Docker
Buildx service will do the job for us (provided the base images support
the given platforms, which is the case for golang).
The result of a test run on my private fork can be inspected here:
- Build: https://github.com/guggero/lnd/runs/1524288829?check_suite_focus=true
- Resulting image: https://hub.docker.com/layers/guggero/lnd/v0.0.0-docker-arm1/images/sha256-df8c7ddc94d3a08313f6e9506da852e060c4a31a1f0913eabf9351c35236fd25?context=explore (don't use for mainnet obviously!)
Big shoutout to @openoms who ran a quick sanity check of the above image on a 32bit Raspberry Pi to confirm the output binary format is indeed ARM compatible.
Full functional tests should …
> GitHub: specify docker image platforms to enable ARM image builds

- .github/workflows/main.yml
- .github/workflows/release.yaml
- .travis.yml
- Dockerfile
- dev.Dockerfile
Addendum to https://github.com/lightningnetwork/lnd/pull/4858: We need to update the golang patch version in the Docker files and release scripts as well to make sure all our upcoming RC deliverables will be built with the latest version.
> GitHub+Travis+docker: update golang patch version to 1.15.6 everywhere

- chanrestore.go
Fixes https://github.com/lightningnetwork/lnd/issues/4863.
The fix in https://github.com/lightningnetwork/lnd/pull/3719 was not correct.
If a channel backup from an old node is restored and a channel contained
within that file was unconfirmed at the time of the backup, the whole
channel short ID is 0:0:0. Unfortunately we got stuck in just the first
case and didn't fall through to the second one. To avoid that, we flip
the case logic because for the second case, the block height in the
short channel ID cannot be zero.
> chanrestore: flip case logic for old backup logic

- chanbackup/single.go
- channeldb/channel.go
- chanrestore.go
- feature/default_sets.go
- feature/manager.go
- fundingmanager.go
- lncfg/protocol.go
- lncfg/protocol_experimental_off.go
- lncfg/protocol_experimental_on.go
- lncfg/protocol_rpctest.go
- lnwallet/commitment.go
- lnwallet/reservation.go
- lnwire/features.go
- sample-lnd.conf
- server.go
This PR enables an extension to the `anchor` commitment type that makes second-level HTLC transactions pay a zero fee, meaning they will have to have fees added as in #4779.
This PR adds this type to the already existing `anchors` type, meaning all new anchor channels being opened will have this enabled (as long as both nodes support it). Existing anchor channels will stay the same.
#4779
> [anchors] zero-fee HTLC secondlevel transactions

- lnd.go
- walletunlocker/service.go
- walletunlocker/service_test.go
Apparently dropping the wallet transaction history only fully takes
effect after opening the wallet from scratch again. To do this cleanly,
we need to do it in the unlocker instead of lnd.
Thanks to @githorray [for reporting this](https://github.com/lightningnetwork/lnd/commit/a7c81eb59579f55749ab4a190a2c9976add3c9dc#commitcomment-45013176)!
> lnd+walletunlocker: move wallet DB history drop to unlocker

- channeldb/kvdb/config.go
- channeldb/kvdb/etcd/db.go
- channeldb/kvdb/etcd/embed.go
- channeldb/kvdb/etcd/fixture_test.go
- channeldb/kvdb/kvdb_etcd.go
- sample-lnd.conf
This PR adds support for etcd namespaces. This is useful when
using a shared etcd database where separate users have access to
separate namespaces.
> etcd: add support for namespaces

- peer/brontide.go
- peer/brontide_test.go
In this commit, we fix an issue that would cause peers running lnd 0.12
to not be able to connect to existing peers due to a feature bit
compatibility issue. In a recent PR we started to downgrade our required
feature bit for static key from required to optional, if we had a legacy
(non-tweakless) open with the peer then we would unset the required bit
and set the optional bit to ensure we could still connect to them.
The change implementing this new version of downgrade failed _also_
unset the bit (the required bit) in the "legacy global" feature bit
section. This caused the `RawFeatureVector.Merge` method to fail as we
would have the required bit set in the `GlobalFeatures` section, but the
optional bit set in the `Features` section. The `Merge` method ensures
that a required and …
> peer: ensure consistent local+global feature bits when downgrading

- chanacceptor/chainedacceptor.go
- help lnd avoid a bug in the `sync/atomic` package which requires 64-bit alignment of atomically accessed fields
Addresses: https://github.com/lightningnetwork/lnd/issues/4886
logging level
per default)
already exist
> ensure 64bit alignment of atomically accessed field in ChannelAcceptor

- rpcserver.go
Fixes a typo and missing format 'verb' in the RPCS debug log.
> rpcserver: fix log statement in channelbalance

- watchtower/wtclient/client.go
- watchtower/wtclient/session_negotiator.go
- watchtower/wtclient/session_queue.go
- watchtower/wtclient/task_pipeline.go
Follow up from #4782, adds the `(legacy)` or `(anchor)` prefix to logs output by the individual sub-clients
> watchtower/wtclient: add prefix logging

- discovery/gossiper.go
- discovery/gossiper_test.go
- lntest/itest/log_error_whitelist.txt
As similarly done with premature channel announcements, we'll no longer allow premature channel updates to be rebroadcast once mature. This is no longer necessary as channel announcements that we're not aware of are usually broadcast to us with their accompanying channel updates.
> discovery: prevent rebroadcast of premature channel updates

- .github/workflows/main.yml
- .github/workflows/release.yaml
- .travis.yml
- Dockerfile
- Makefile
- dev.Dockerfile
- docs/release.md
- make/builder.Dockerfile
- make/release_flags.mk
- scripts/release.sh
Fixes a number of small issues that lead to the release artifact hashes not matching up with local builds.
1. Fetch full git history to make sure `git describe` works correctly.
2. Use `git describe --tags` to identify the commit name compiled into the binaries.
3. Use fixed/deterministic file order, file timestamps and file attributes when creating the `.tar.gz` and `.zip` files.
A test run is in progress on GitHub: https://github.com/guggero/lnd/runs/1669502010?check_suite_focus=true
Will validate against my local build and report back on it.
Anyone trying to reproduce the same hashes can do the following (using **`go 1.15.6`**!):
```
git remote add guggero git@github.com:guggero/lnd.git
git fetch guggero
git checkout v0.12.0-beta.rc3-testbuild7
SKIP_VERSION_CHECK=1 make release …
```
> release: actually create deterministic release archives

- config.go
- docs/INSTALL.md
- lncfg/neutrino.go
- sample-lnd.conf
Fixes #4906 by updating the descriptions of the top-level `feeurl` and deprecated `neutrino.feeurl` options and adding a valid example URL to the `sample-lnd.conf` file.
We also update the installation instructions to point novice users towards official release binaries.
> doc+config: fix feeurl description and example, update installation instructions

- config.go
- sample-lnd.conf
Some nodes still having issues with health check, #4913, despite upgrade to uptime call. This PR bumps out defaults to be more tolerant of slower bitcoinds.
> config: increase chain backend healthcheck timeout and backoff

- lntest/itest/lnd_test.go
If the last channel fail, eh indexing into nodeNames would panic. We
instead name the channels, such that the slices will be of the same
length.
> itest: fix node names out of bounds

- .travis.yml
- Makefile
- channeldb/kvdb/backend.go
- channeldb/kvdb/config.go
- channeldb/kvdb/etcd/db.go
- channeldb/kvdb/etcd/embed.go
- channeldb/kvdb/etcd/fixture_test.go
- channeldb/kvdb/interface.go
- channeldb/kvdb/kvdb_etcd.go
- channeldb/kvdb/kvdb_no_etcd.go
- contractcourt/chain_watcher.go
- lncfg/db.go
- lntest/node.go
- sample-lnd.conf
This PR adds optional user defined ports for the embedded etcd instance in order to fix the issue when parallel itests try to open the same ports. The last commit adds support for CI testing of our etcd stack (on bitcoind).
> etcd+itests: use itest generated ports for embedded etcd and add etcd itests to travis CI

- .github/workflows/release.yaml
- Dockerfile
- Makefile
- docs/DOCKER.md
- docs/release.md
- scripts/release.sh
- scripts/verify-install.sh
Fixes https://github.com/lightningnetwork/lnd/issues/4904.
This PR makes the binaries that are built inside the docker container reproducible as well.
In addition to storing the SHA256 hashes of the built binaries inside the container for easy manual verification, we also add a script that verifies those hashes against a public release that contains signatures from our team members.
The script queries GitHub to get the signatures of a release. Therefore this can only be done in an online environment and if the release was already signed by at least one person who's key is in the `scripts/verify-install.sh` script.
Because of this prerequisite the verification script isn't executed automatically on container start!
This can be tested with an image I pushed to my personal fork (signed …
> docker: add verification script

- lntest/itest/lnd_onchain_test.go
- lntest/itest/lnd_test_list_on_test.go
- lntest/itest/log_error_whitelist.txt
- lnwallet/chanfunding/assembler.go
- lnwallet/chanfunding/canned_assembler.go
- lnwallet/chanfunding/psbt_assembler.go
- lnwallet/chanfunding/wallet_assembler.go
- lnwallet/wallet.go
- rpcserver.go
- sweep/sweeper.go
- sweep/sweeper_test.go
- sweep/txgenerator.go
- sweep/txgenerator_test.go
- sweep/walletsweep.go
- sweep/walletsweep_test.go
The recently introduced anchor commitment format has several advantages, most notably that one can decide on channel closure how much fees to apply to the commitment transaction. However, in order to do this fee bumping, one need to have a UTXO available. This PR attempts to make sure such a UTXO is kept around, by disallowing transactions that would spend what we have left in the wallet.
This PR starts by checking the final wallet balance in cases of `channel open` and `send all`. More cases could be added later, in particular the regular `send coins` call is not performing this check, since the tx is crafted and published directly by the wallet.
> [anchors] Reserve wallet balance for anchor fee bumping

- amp/child.go
- amp/derivation_test.go
- amp/sharer.go
WIP since spec is still in flux, primarily looking for feedback on the interface.
> amp: introduce child preimage and hash derivation

- netann/chan_status_manager.go
- netann/channel_update.go
Since the funding manager might be in process of adding the edge to the
graph, we ignore the error.
Fixes #4798
> netann: ignore unknown channel update on startup

- docker/lnd/start-lnd.sh
Make sure the lncli command can be used inside of the container without
needing to specify the --rpcserver flag all the time. Issue: #4937
logging level
per default)
already exist
> docker: add an extra listener for localhost

- lnrpc/README.md
As per this [stack overflow answer](https://stackoverflow.com/questions/21151731/where-are-clang-format-and-clang-format-py-in-mac-os-x-with-xcode-command-line-t) mac doesn't ship with clang-format.
I've added instructions for installing
logging level
per default)
already exist
> docs: Add clang-format instructions for mac

- .github/workflows/docker.yml
- .github/workflows/release.yaml
To avoid leaking any sensitive information like Docker Hub credentials
because of compromised actions repositories, we use our own, vendored
actions for all steps that potentially touch sensitive information.
> GitHub: use vendored actions for steps with sensitive info

- scripts/verify-install.sh
When verifying the release signatures, we don't want to fail if a
signer's signature is not available in the gpg key ring. Instead we just
don't want to count the signature for now and still succeed if there's
at least one other good sig with a known key.
> scripts: don't fail signature verification on missing public key

- Makefile
- monitoring/monitoring_on.go
This PR defines `make imports` for running `goimports` on the source. It also enables it for the linter and formats the affected files.
> [Makefile] Define `make imports`

- rpcserver.go
So that API users don't need to string match.
> rpcserver: use NotFound http status code in GetNodeInfo

- lnrpc/invoicesrpc/config_active.go
- lnrpc/invoicesrpc/invoices_server.go
- rpcserver.go
- subrpcserver_config.go
`AddHodlInvoice` as copying `AddInvoiceConfig`, leaving out the `Graph` member which later on resulted in a `nil` pointer reference.
> invoices+rpc: add missing channel graph to the AddInvoiceConfig

- lnrpc/routerrpc/router_backend.go
- routing/payment_session.go
LND was allowing MPP payments to destinations that do not support them. We noticed this when an open amount invoice with MPP disabled received a multi part payment (which of course triggered a bug in our implementation 🤷 too).
I'm not sure how to go around adding tests for this given that both affected structs have little tests.
logging level
already exist
> routerrpc,routing: limit max parts if the invoice doesn't declare MPP support

- lnrpc/gen_protos_docker.sh
This allows users to see progress whenever the docker image is
[re]built, and (esp on non-linux hosts) track the size of the build
context being uploaded. Currently no output is displayed, so it's hard
to attribute the source of latency, e.g. network latency, building
layers, a large work directory, etc.
> gen_protos_docker: make image build non-quiet

- routing/integrated_routing_context_test.go
- routing/integrated_routing_test.go
This test case ensures that we won't try to split payment if the dest
has the payment addr bit, but NOT the mpp optional/require bit.
> routing: add new TestPaymentAddrOnlyNoSplit test case 

- channeldb/channel.go
- htlcswitch/link_test.go
- lnwallet/channel.go
With this pull request, we store a boolean per channel under the new `lastWasRevokeKey`. This key determines if the last material update our channel *sent* was a `CommitSig` or `RevokeAndAck`.  When the link calls `SignNextCommitment`, `false` is stored under the key.  When the link calls `RevokeAndAck`, `true` is stored under the key.
For new channels with no updates yet exchanged, nothing is stored and so the key contains `nil`.
For existing channels updating to this patch, the default `nil` is also stored.  The next update sent will store something under the key. 
Fixes https://github.com/lightningnetwork/lnd/issues/4799
Fixes #4613
> multi: store bool to determine retransmission ordering

- lncfg/address.go
logging level
per default)
already exist
> fix: correct no-rest-tls parameter in error message

- lntest/itest/lnd_test.go
This PR updates the hold invoice itest to create a private
channel, and sets the private option on the invoices created
to add coverage for the addition of hop hints.
> itest: add coverage for hold invoices with hop hints

- discovery/sync_manager.go
- discovery/sync_manager_test.go
- lntest/itest/lnd_test.go
Depends on #4934, only the last commit is new.
Changes behavior when `numgraphsyncpeers=0` to forgo syncing entirely.
> discovery: no graph sync
