lightningnetwork/lnd

- config.go
- fundingmanager.go
- glide.lock
- glide.yaml
- lnd.go
- lnd_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- lnwallet/config.go
- lnwallet/wallet.go
- lnwire/error_generic.go
- lnwire/error_generic_test.go
- lnwire/single_funding_open_proof.go
- lnwire/single_funding_signcomplete.go
- networktest.go
- peer.go
- rpcserver.go
**Issue:** [Only allow a single pending channel per-peer #32] (https://github.com/lightningnetwork/lnd/issues/32)
> Only allow a single pending channel per-peer #32

- lnd_test.go
As was discussed before segregated `test structure` changes in additional `PR`.
> Partially restore previous test structure to fix defer+goroutine 

- chainntnfs/btcdnotify/btcd.go
- chainntnfs/interface_test.go
> Chainnntfs: check historical data to determine if notification can be immediately dispatched

- channeldb/channel.go
- channeldb/channel_test.go
- fundingmanager.go
- lnd_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- lnwallet/interface_test.go
- lnwallet/parameters.go
- lnwallet/reservation.go
- lnwallet/wallet.go
- lnwire/error_generic.go
- lnwire/htlc_addrequest.go
- lnwire/htlc_addrequest_test.go
- lnwire/lnwire.go
- lnwire/single_funding_request.go
- lnwire/single_funding_request_test.go
- lnwire/single_funding_response.go
- lnwire/single_funding_response_test.go
- peer.go
- rpcserver.go
- server.go
> Clearing and settling of HTLC's below the dust limit #48 

- chainntnfs/btcdnotify/btcd.go
- lnd_test.go
Fixed two issues that were intermittently breaking integration tests.
> Fixed multi-hop test concurrency bug, epoch notification restart bug

- contrib/lncli.bash-completion
bash completion for all the basic commands listed in "lncli help" and the global options.
> basic bash completion for lndcli

- routing/pathfind.go
- routing/pathfind_test.go
- routing/testdata/excessive_hops.json
This PR aims to fix the bug reported in #114. See commit message for more details.
I just started looking at the routing code, so I am assuming there may be better ways to solve this.
Edit: Moved the check prior to building the route.
> Fix routing bug that reports MaxHopsExceeded incorrectly

- peer.go
- server.go
> panic during peer connection 

- docs/grpc/python.md
I added instructions for writing gRPC clients for the lightning network daemon in Python
> documentation: added instructions for writing gRPC clients in Python

- cmd/lncli/commands.go
[WIP] Adds support for positional arguments for the most used commands as described in #31 
The argument can also be used in a mixed fashion. However positional arguments have to be in order.
The following examples are all the same:
`openchannel <node_key> <local_amt> <push_amt>`
`openchannel <node_key> --local_amt=N <push_amt>`
`openchannel --node_key=X <local_amt> --push_amt=N`
`openchannel --node_key=X --local_amt=N <push_amt>`
`openchannel --node_key=X --local_amt=N --push_amt=N`
> lncli: add support for positional arguments for several commands

- cmd/lncli/commands.go
- cmd/lncli/main.go
This is a first integration of the command into lncli.
Next Step would be paging according to #133 .
> lncli: add listchaintxns (GetTransactions RPC call) command (#133)

- gotest.sh
Add check that vendor directory is installed and if not we should run
glide install, also if additional flag '-i' is specified than script will reinstall
dependencies.
> goclean: add vendor check; add '-i' flag

- lnwallet/wallet.go
Previously, if an error was returned during handleSingleFunderSigs or
handleFundingCounterPartySigs, the wallet would hang waiting for
the completeChan channel to be populated. This commit adds nil returns for
the completeChan when errors are propagated.
> lnwallet: fix error propagation for funding messages

- discovery/service.go
- discovery/service_test.go
In case of the situation when we receive remote announcement with channel id which pointing out to unknown channel the announcement have been silently rejected. Now such announcement will
be added to the waiting proof map. 
Such solution has a serious drawback - by adding the announcement proof without information about channel itself (that this announcement have been received from the node eligible to sending it), we allow overwriting the waiting proof map by `Eve` node.
> discovery: fix silent remote orphan announcement proof rejection

- chainntnfs/log.go
- channeldb/log.go
- config.go
- discovery/log.go
- glide.lock
- glide.yaml
- gotest.sh
- htlcswitch/log.go
- htlcswitch/test_utils.go
- lnd.go
- lnd_test.go
- lnwallet/log.go
- log.go
- routing/chainview/log.go
- routing/log.go
In order to complete PR we need:
1.  Update `roasbeef` `btcd` client
2. Make changes in the `ltcd` client
Link: [btcd example of removing](https://github.com/btcsuite/btcd/commit/a6965d493fdfb833b6b3a83c3958ab18968fe24e)
> Remove seelog logger

- networktest.go
The flag can be used to show the log output from the seed nodes, which is useful for debugging failing test cases.
> integration tests: add -showoutput flag 

- htlcswitch/circuit.go
- htlcswitch/failure.go
- htlcswitch/interfaces.go
- htlcswitch/iterator.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/packet.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- htlcswitch/test_utils.go
- lnd_test.go
- lnwire/lnwire.go
- lnwire/lnwire_test.go
- lnwire/message.go
- lnwire/onion_error.go
- lnwire/onion_error_test.go
- lnwire/update_fail_htlc.go
- lnwire/update_fail_malformed_htlc.go
- peer.go
- routing/router.go
- routing/router_test.go
- server.go
> #79: Add Sphinx error propogation

- routing/notifications_test.go
Modifies the test cases in `TestEdgeUpdateNotification` and `TestNodeUpdateNotification` to check for the possibility of notifications being delivered out of order.  This addresses some sporadic failures that were observed when running the test suite. 
I looked through some of the open issues but didn't see any addressing this issue in particular, but if someone could point me to any relevant issues that would be much appreciated!
Issue
-----
Currently the test suite validates notifications received in the order they are submitted. The check fails because the verification of each notification is statically linked to the order in which they are delivered, seen [here](https://github.com/cfromknecht/lnd/blob/1be4d67ce41e65feee8ea05332dfc67a3437813d/routing/notifications_test.go#L403) and …
> routing/notifs: order invariant testing of ntfn delivery

- README.md
Hi,
Looks like this is meant to be plural.
> BOLT's -> BOLTs

- lnd_test.go
This commit prevents the case where `btcd` stops before `lnd` is fully started, thus making `lnd_test` hang on trying to stop `lnd` using `StopDaemon`. The underlying issue is that while `lnd` is trying to start the server and subscribe to block notifications from `btcd`, `btcd` stops, and `lnd` continues to attempt to reconnect before it ever starts the interrupt handler. This reversal avoids that issue by making sure `lnd` is stopped before `btcd`.
> lnd_test: reverse the order of teardown for lnd and btcd harnesses

- docker/README.md
Should fix one of the problems encountered in #279, and also removes the no longer existing num_conf flag.
> Update docker readme.

- lnd.go
Added the new more secure Crypto algorithms available in Go 1.8
As per [issue](https://github.com/lightningnetwork/lnd/issues/281)
> Added CBC and SHA256 crypto algorithms

- cmd/lncli/commands.go
- lnwallet/wallet.go
Closes https://github.com/lightningnetwork/lnd/issues/354
> Specify need for witness outputs for funding channels

- lnwallet/script_utils_test.go
- shachain/element_test.go
- shachain/store_test.go
https://github.com/lightningnetwork/lnd/issues/300
> shachain & lnwallet: Complete implementation of BOLT-3 Appendix D & E tests

- docker/README.md
This PR fixes the lnd docs for the docker setup.
> Fix spelling in docker docs

- cmd/lncli/commands.go
- cmd/lncli/main.go
lncli: Short command for invoice payment
> lncli: short command for invoice payment

- discovery/gossiper.go
This commit refactors the SyncronizeNode logic such that it can be called without interacting with the gossiper's main execution loop. This method does not require access to any of the gossiper's internal state, making the change fairly straightforward. The primary motivation behind this change is to minimize the likelihood of deadlock scenarios between the gossiper and server.
> Gossiper: Isolate SynchronizeNode from query loop

- peer.go
This PR adds an asynchronous, in-order queue for delivering remote channel announcements between the peer's readHandler and the authenticated gossiper. The graph topology integration test exhibited fairly consistent failures stating that notifications were never received, whose cause seems to be related to the interlocking between the peer and gossiper. By using the async, in-order queue, we allow the readHandler to unblock and continue processing messages from the wire. This seems to have resolved the problem, it's unclear if this may have had a positive effect on the reliability of other itests, but overall travis seems much happier 🎉
The fix was implemented by modifying the existing chanMsgStream to use an `apply` closure, which can potentially be reused for other subsystems where we …
> peer: add async queue for gossiper msgs

- peer.go
This commit addresses an issue that could occur if a
message was attempted added to the sendQueue by the
queueHandler before the writeHandler had started.
If a message was sent to the queueHandler before the
writeHandler was ready to accept messages on the
sendQueue, the message would be added to the
pendingMsg queue, but would not be attempted sent
on the sendQueue again before a new incoming message
triggered a new attempt.
> peer: avoid blocked writeHandler<->queueHandler interaction

- docs/INSTALL.md
> Fix tutorial URL

- walletunlocker/service.go
> walletunlocker: check that password is non-empty

- channeldb/channel_test.go
Fixes scoping error documented in: https://github.com/lightningnetwork/lnd/issues/442
> channeldb: fix channel_test scoping error

- htlcswitch/queue.go
In this commit, we fix an existing issue that would cause lnd to panic
on 32-bit systems. Within the packetQueue we utilize atomics heavily.
However, it's the caller's job to ensure 64-bit alignment of 64-bit words
accessed atomically. This is documented within the sync/atomic package
as a set of known bugs.
The old alignment of this struct was:
⛰  structlayout github.com/lightningnetwork/lnd/htlcswitch packetQueue
packetQueue.queueLen int32: 0-4 (size 4, align 4)
padding: 4-8 (size 4, align 0)
packetQueue.totalHtlcAmt int64: 8-16 (size 8, align 8)
packetQueue.queueCond *sync.Cond: 16-24 (size 8, align 8)
packetQueue.queueMtx.state int32: 24-28 (size 4, align 4)
packetQueue.queueMtx.sema uint32: 28-32 (size 4, align 4)
packetQueue.queue …
> htlcswitch: fix alignment of the packetQueue's fields for 32-bit systems

- zpay32/invoice.go
- zpay32/invoice_test.go
Fixes #479.
Updates the way fees are handled for routing payments.
See lightningnetwork/lightning-rfc#317.
> bolt11: handle r field fee spec change

- lnwallet/btcwallet/blockchain.go
This commit adds an additional check in GetUtxo that tests for the nil-ness of the spend report returned by the neutrino backend. Previously, a nil error and spend report could be returned if the rescan did not find the output at or above the start height. This was observed to have cause a nil pointer dereference when the returning line attempted to access the output. This case is now handled by returning a distinct error signaling that the output was not found.
> Properly Handle Nil Spend Report from Neutrino Rescan

- docker/lnd/start-lnd.sh
- docs/INSTALL.md
- sample-lnd.conf
This PR updates documentation, examples, and the Docker configuration files to use the configuration options in use as of #447.
> docker, docs, sample-lnd.conf: update examples for new command-line options

- channeldb/db.go
- utxonursery.go
Fixes a bug in the recovery logic of the utxonursery that causes it to register for commitment confirmations with an incorrect height hint. Previously, the nursery would use the last graduated height, which advances with each block epoch. This can lead to race conditions on startup, especially if many blocks were mined while lnd was offline.
In order to get an accurate height hint, this changes adds a `FetchClosedChannel` method to channeldb, allowing the nursery to query for the close channel summary. The summary contains the `CloseHeight`, which records the height at which we detected the channel was closed. To prevent the race condition, we use the close height as the beginning of the rescan period, with a fudge factor of `ConfDepth` to handle potential reorgs.
> Fix UtxoNursery Commit Sweep Height-Hint

- zpay32/amountunits.go
- zpay32/invoice.go
- zpay32/invoice_internal_test.go
> invoice: avoid negative msat amounts

- lnrpc/README.md
I have put the README in sync with the current state of the rpc.proto file
> rpc: update README according to current rpc.proto file

- docs/INSTALL.md
Add sample bitcoin.conf for use with lnd
[request](https://github.com/lightningnetwork/lnd/issues/638)
Fixes #720.
> Update install instructions to provide a sample bitcoin.conf

- docker/ltcd/start-ltcd.sh
> Adds --txindex to ltcd docker container

- htlcswitch/switch.go
This commit fixes a deadlock scenario caused when some
switch methods are waiting for a response on the
command's done/err chan. However, no such response will
be delivered if the main event loop has already exited.
This is resolved by selecting on the command's done/err chan
and the server's quit chan simultaneously.
> htlcswitch/switch: select on quit channels for switch commands

- breacharbiter.go
After a shutdown has been initiated, both registrations
for spend ntfns and publishing txns can fail. The current
behavior in the face of such failures is to continue trying,
which is fine if we are online. However, this causes an
infinite loop during shutdown, and lnd cannot exit since
the routine is tracked by the brar's waitgroup.
A simple fix is to select on the brar's quit channel after
detecting a failure from either, allowing the breach arbiter
to break out of this death cycle.
> breacharbiter: avoid infinite loop in exactRetribution

- server.go
This commit adds a backoff policy to the peer termination watcher to avoid getting stuck in tight connection loops with failing peers. The maximum backoff is currently set to 128s, and each backoff is randomized so that two instances using the same algorithm have some hope of desynchronizing. Note, a peer's backoff will only be reset if we manually disconnect via `DisconnectPeer` or restart the server.
> server: adds truncated exponential backoff + rand for retry

- cmd/lncli/commands.go
Fixes #554.
Adds the option to connect to a node before opening the channel by
passing the node's `host:port` via the `--connect` flag.
> lncli: add 'connect' flag to openchannel command

- lnd.go
In this commit, we modify our initial cert generation to *only* generate
and advertise cipher suites that purely use ECC. We do this is as
switching to ECC results in much faster startup time for a fresh
installation, and is also more modern crypto.  # Please enter the commit
message for your changes. Lines starting
> lnd: switch to using ECC certs for the rpcserver

- brontide/noise.go
In this commit, we reduce the total number of allocations that a
brontide session will incur over its lifetime. Profiling on one of my
nodes showed that we were generating a lot of garbage due to
re-creating a 65KB buffer to read the next message each time the
ReadMessage method was called.
To reduce the total number of memory allocations, we’ll now simply
re-use a buffer for both the cipher text header, and the cipher text
itself.
> brontide: reduce memory allocs by using static buf for next header+msg

- docs/grpc/java.md
- docs/macaroons.md
> Add more details on using macaroons with GRPC.

- rpcserver.go
Cosmetic change: Get the forgotten payments.fee from the Payment structure and present it.
For now I rounded to satoshis.
> Added the missing fee to ListPayments (was always 0)

- discovery/gossiper.go
- discovery/gossiper_test.go
- routing/router.go
- routing/router_test.go
In this PR, we reduce the amount of unnecessary work that the gossiper can carry out. When CPU profiling some nodes, I noticed that we’d spend a lot of time validating the signatures for an announcement, only to realize that the router already had it.
To remedy this, we’ll use the new methods added to the channel router in order to avoid unnecessarily validating an announcement that is actually stale. This should reduce memory usage (since it uses big int’s under the scenes), and also idle CPU usage.
The new methods added to the channel router's `ChannelGraphSource` interface are: 
```go
// IsStaleNode returns true if the graph source has a node announcement
// for the target node with a more recent timestamp.
IsStaleNode(node Vertex, timestamp time.Time) bool
// IsKnownEdge returns true …
```
> routing+gossiper: avoid unnecessarily validating sigs for announcement that is "stale"

- cmd/lncli/commands.go
- cmd/lncli/main.go
> cmd/lncli: add closeallchannels command

- htlcswitch/switch.go
This is a small PR that makes three small change to improve the safety of switch shutdown.
1. If the switch fails to reforward Settle/Fail packets found in forwarding packages, we will now call `Stop()` to properly shutdown any active goroutines.
1. In `Stop()`, we wait until all goroutines have been terminated before stopping the individual mailboxes. This prevents unintended access/modification to the `mailboxes` map.
1. Break out early of `ForwardPackets` if we have already received a shutdown signal, which should prevent weird race conditions on the switch's `WaitGroup`.
> htlcswitch/switch: improve safety of switch shutdown

- cmd/lncli/main.go
> cmd/lncli: correctly set modified macaroon path

- version.go
as per the following https://github.com/lightningnetwork/lnd/issues/845 attempting my first PR
Fixes https://github.com/lightningnetwork/lnd/issues/845
> fixing version to beta 

- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
Discussed here: https://github.com/lightningnetwork/lnd/issues/687#issuecomment-373400452
> rpc: Fix typo in OpenChannelRequest

- breacharbiter.go
This commit fixes a broadcast loop within the breach arbiter, that would
occur when HTLC outputs had been taken to the second level. The breach
arbiter would register for a spend event, but would immediately go on to
create and publish the justice, without waiting for the response to be
received on the spend channel. This lead to a race, where the outpoint
could actually already have been spent, but the notification would
arrive after the breach arbiter checked the channel, and publishing the
justice TX would fail because it was a double spend. This would create a
"broadcast loop", as seen in the logs from the integration test
revoked_uncooperative_close_retribution_remote_hodl.
This is fixed by reusing an existing spend event for the outputs,
meaning we will actually receive on the first …
> breacharbiter: reuse spend events instead of re-registering

- chainparams.go
- rpcserver.go
- sample-lnd.conf
Minor fixes for litecoin related stuff.
Was trying to get LND running on litecoin testnet, noticed some problems in the sample config file. This also fixes [bug reported by justin on slack](https://lightningcommunity.slack.com/archives/C6BFMETDL/p1521496526000030).
Closes #936 and #914
> Litecoin fixes

- .github/ISSUE_TEMPLATE.md
https://github.com/lightningnetwork/lnd/issues/913
> Adding GitHub issue template

- chainregistry.go
Fixes #944 [reference](https://github.com/litecoin-project/litecoin/blob/master/src/test/transaction_tests.cpp#L696)
> chainregistery: correct ltc dust limit

- docs/INSTALL.md
- docs/MAKEFILE.md
Updates `docs/INSTALL.md` to show installation with `make`, and adds `docs/MAKEFILE.md` which describes the availble commands.
> Makefile docs

- LICENSE
> year Update LICENSE

- peer.go
In this commit, we might a very small change to the way writing messages
works in the peer, which should have large implications w.r.t reducing
memory usage amongst chatty nodes.
When profiling the heap on one of my nodes earlier, I noticed this
fragment:
```
Showing top 20 nodes out of 68
flat  flat%   sum%        cum   cum%
0     0%     0%    75.53MB 54.61%  main.(*peer).writeHandler
75.53MB 54.61% 54.61%    75.53MB 54.61%  main.(*peer).writeMessage
```
Which points to an inefficiency with the way we handle allocations when
writing new messages, drilling down further we see:
```
(pprof) list writeMessage
Total: 138.31MB
ROUTINE ======================== main.(*peer).writeMessage in /root/go/src/github.com/lightningnetwork/lnd/peer.go
75.53MB    75.53MB (flat, cum) 54.61% of Total
. …
```
> peer: re-use a static writeBuf within writeMessage optimize memory usage

- chainntnfs/bitcoindnotify/bitcoind.go
> chainntnfs/bitcoindnotify: rescan blocks manually instead of rewinding

- docs/grpc/python.md
This PR fixes the doc as there are no more witness_only data
> remove witness_only in doc

- server_test.go
Server tests shouldn't run during integration testing.
> [trivial] server test: add !rpctest build flag

- docs/INSTALL.md
Added a one-liner to symlink the binary instead of adding stuff to $PATH.
> Added suggestion to INSTALL.md

- lnwallet/channel.go
I also fixed an error message in this check, makes more sense to me to say that the new balance would dip below channel reserve.
> Fix logic in validateFeeRate to account for old fee  being added back to balance (don't merge yet)

- chainntnfs/interface_test.go
Make sure new clients get notified about txs that are already in the mempool.
> Close #1074: expand test for mempool spend notifications

- htlcswitch/link.go
This commit makes the call to forwardBatch after locking
in Adds synchronous. This ensures that circuits for any Add
packets are added to the switch in the same order that they
are prescribed in the channel state. Though it is very unlikely
this case would arise, it may happen under more greater loads.
In addition, this also makes some trivial optimizations wrt. to
not spawning unnecessary goroutines if no settle/fail packets
are locked in.
> htlcswitch/link: ensure circuits are committed in-order

- peer.go
- server.go
This commit attempts to resolve some potential deadlock
scenarios during a peer disconnect.
Currently, writeMessage returns a nil error when disconnecting.
This should have minimal impact on the writeHanlder, as the
subsequent loop selects on the quit chan, and will cause it to
exit. However, if this happens when sending the init message,
the Start() method will attempt to proceed even though the peer
has been disconnected.
In addition, this commit changes the behavior of synchronous
write errors, by using a non-blocking select. Though unlikely,
this prevents any cases where multiple errors are returned, and
the errors are not being pulled from the other side of the errChan.
This removes any naked sends on the errChan from stalling the peer's
shutdown.
Lastly, we skip creating errChans …
> peer/server: Remove Broadcast err chans

- Gopkg.lock
- Gopkg.toml
- htlcswitch/circuit_test.go
- htlcswitch/decayedlog.go
- htlcswitch/decayedlog_test.go
- htlcswitch/mock.go
- server.go
See https://github.com/lightningnetwork/lightning-onion/pull/22 for rationale.
@cfromknecht
> Move DecayedLog from lightning-onion to htlcswitch.

- lnd_test.go
In this commit, we address a timeout issue on our Travis builds within
the update channel policy integration test. Before asserting the policy
for the channel between Alice and Bob, we need to make sure we receive
the updates responsible for modifying this policy first. At times, the
update wasn't received in time before checking the policy, which led to
us checking the old policy. We fix this by explicitly making sure we wait
for the updates first.
> test: fix update channel policy flake

- contractcourt/channel_arbitrator_test.go
This commit adds a test for the case where the ChannelArbitrator fails
to broadcast its commitment during a force close because of
ErrDoubleSpend. We test that in this case it will still wait for a
commitment getting confirmed in-chain, then resolve.
> [test] add TestChannelArbitratorLocalForceDoubleSpend

- docs/grpc/ruby.md
The ruby docs needed some updating including information on `GRPC_SSL_CIPHER_SUITES` and on macaroons. I based it off of the python docs which I found quite helpful.
> Add macaroon and SSL Cipher info to Ruby gRPC docs

- peer.go
In this commit, we fix a recently introduced bug. The issue is that
while we're failing the link, the peer we're attempting to force close
on may disconnect. As a result, if the peerTerminationWatcher exits
before we can add to the wait group (it's waiting on that), then we'll
run into a panic as we're attempting to increment the wait group while
another goroutine is calling wait.
The fix is to first check that the server isn't shutting down, and then
use the server's wait group rather than the peer to synchronize
goroutines.
Fixes #1285.
> peer: when failing link, depend on server wg, not peer

- htlcswitch/decayedlog_test.go
This commit changes the decayed log tests to create
a new temporary database for each test. Previously, all
instances referenced the same db path. Since the tests
are run in parallel, the tests would create/delete the
shared db out from under each other, causing flakes in
the unit tests.
> htlcswitch/decayedlog_test: create unique test dbs

- Makefile
- make/testing_flags.mk
Two commits to make flake hunting more useful.
> [Makefile] Remove logs between runs, print date

- channeldb/graph.go
- channeldb/graph_test.go
In this commit, we fix an existing bug in the new graph query sync
feature. Before this commit, when a block is pruned, we would never
actually delete the update index entries. This is due to the fact that
we would attempt to delete the entries from the update index _after_ we
had already removed the edges from the update index.
We fix this by simply swapping the order: first we delete from the
update index, then we delete the edges themselves. A test ensuring that
the entires are cleared (which failed before this commit), has been
added.
> channeldb: ensure items from the update index are actually deleted

- htlcswitch/queue.go
In this commit, we ensure that the packet queue will always exit, by
continually signalling the main goroutine until it atomically sets a
bool that indicates its has been fully shutdown. It has been observed
that at times the main goroutine will wake up (due to the signal), but
then bypass the select and actually miss the quit signal, as a result
another signal is required. We'll continue to signals in a lazy loop
until the goroutine has fully exited.
> htlcswitch: ensure the packet queue exits on stop

- docs/INSTALL.md
See https://github.com/lightningnetwork/lnd/pull/751
Thanks to molz on IRC
> Updating in line with a PR

- fundingmanager.go
- peer.go
> peer: prevent processing close msg if channel is not found

- htlcswitch/decayedlog_test.go
This commit fixes a bug in the
TestDecayedLogPersistentGarbageCollector unit test.
The test generates a second hash prefix, which is never
added to the log, and used to query for the final
existence check. This commit reverts the behavior so
that the same hash prefix is used throughout the test.
> htlcswitch/decayedlog_test: fix bug in gc unit test

- brontide/listener.go
> brontide: identify remote address of failed connection

- config.go
> Fix the ability to disable p2p listening

- README.md
> Use HTTPS instead of HTTP in README.md

- config.go
> config: use config file within lnddir unless overwritten

- lnd_test.go
let's see what travis thinks...
> lnd_test: remove itest race caused by mining extra block

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/interface_test.go
This commit fix a bug within the bitcoind notifier logic, which would
ignore the passed mempool argument, and notify spentness whether the
spending transaction was confirmed or not. The logic used to fix this is
similar to what is already done for the btcd backend.
NOTE: mempool spends will be removed entirely in the near future. 
Fixes #1341.
> Filter out bitcoind mempool spends

- channeldb/db.go
- channeldb/graph.go
- channeldb/graph_test.go
- channeldb/nodes.go
- channeldb/nodes_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_watcher.go
- contractcourt/channel_arbitrator.go
- lnd_test.go
- peer.go
- server.go
> server: prune link nodes without any open channels

- Gopkg.lock
> build: sync Gopkg.lock with Gopkg.toml

- peer.go
- server.go
In this PR, we add relaxation to a peer's reconnection backoff, proportional to the duration of the last established connection. Each peer tracks its own start time, which is then used by the server when adjusting the duration it should wait before retrying.
Currently, we use a randomized exponential backoff policy. However, the backoffs are not reset until the server restarts, though they are bounded at 1 hour. In order to tolerate disconnections more gracefully, this calls for a method of returning to the default state after connections with a peer begin to stabilize.
Ignoring the randomization, we'll say that currently our backoffs roughly double in duration with each disconnect, i.e `2*lastBackofff`. The new proposed method is to compute: `2*(lastBackoff - connectionDuration)`, which …
> server: peer backoff backoff

- contractcourt/chain_arbitrator.go
This commit fixes a potential race condition during
shutdown, that could allow the chain arb's
activeWatchers or activeChannels map to be modified
while ranging over their contents. We fix this by
copying the contents into new maps with the mutex
held, before releasing the mutex and shutting down
each watcher or channel arbitrator.
> contractcourt/chain_arbitrator: fix potential shutdown race

- Makefile
- htlcswitch/circuit_test.go
- routing/chainview/interface_test.go
Reported that old linter didn't behave the consistently on different machines, v2 seems to be more stable.
> Makefile: move linter v2

- cmd/lncli/commands.go
Resolves #1455.
Also looks like gofmt wasn't run on this file since the last commit that checked-in closedchannels, so I ran it too.
> Adds extra confirmation to payinvoice and sendpayment, can be bypassed by force.

- contractcourt/briefcase_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_watcher.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
alternative to #1678.
Fixes #1571.
> contractcourt handoff 2

- Gopkg.lock
- Gopkg.toml
- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/bitcoindnotify/bitcoind_debug.go
- chainntnfs/bitcoindnotify/bitcoind_test.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/btcdnotify/btcd_debug.go
- chainntnfs/btcdnotify/btcd_test.go
- chainntnfs/interface.go
- chainntnfs/interface_debug.go
- chainntnfs/interface_test.go
- chainntnfs/neutrinonotify/neutrino.go
- chainntnfs/neutrinonotify/neutrino_debug.go
- chainntnfs/test_utils.go
- lnd_test.go
- lnwallet/interface_test.go
- routing/chainview/interface_test.go
- routing/chainview/neutrino.go
Successor to #1585 and updates btcd/neutrino/btcwallet to point to mainline.
Fixes #1729. 
Closes #1585
> Txindex proper fallback

- lnd_test.go
In this PR, we make the `channel_force_closure` itest more reliable, by adding `WaitPredicate` to all remaining assertions of the `pendingchannels` rpc response.  We parse this information to determine the current state out outputs within the nursery as the test progresses, though there exists asynchrony between when transactions are confirmed and when the nursery processes the event. To handle this, we will block until our requirements are fulfilled instead of simply failing on the first attempt.
> lnd_test: add wait predicates to pending channel checks

- peer.go
This PR three primary issues:
- not disconnecting peers after failing to receive channel reestablish messages
- processing channel force closures w/in the peer life cycle, instead of handling them asynchronously, reducing number of invocations for flapping peers. this ensures we only do so once
- properly prune from persistent peers if failing channel is the last active channel
question: should disconnecting be made optional depending on the link failure?
> peer: ensure link failures are processed in peer life cycle

- server.go
This commit modifies the connection peer backoff
logic such that it will always backoff for "unstable"
peers. Unstable in this context is determined by
connections whose duration is shorter than 10
minutes. If a disconnect happens with a peer
whose connection lasts longer than 10 minutes,
we will scale back our stored backoff for that peer.
This resolves an issue that would result in a tight
connection loop with remote peers. This stemmed
from the connection duration being very short,
and always driving the backoff to the default
backoff of 1 second. Short connections like
this are now caught by the stable connection
threshold.
> server: always backoff for unstable peers

- contractcourt/channel_arbitrator.go
Fix is up, tests to come
Fixes #1760.
> contractcourt/channel_arbitrator: handle onchain close race on restart

- autopilot/agent.go
At startup, when lots of new nodes are added to the graph, we'll stack up an update in a goroutine for each added node. 
```
goroutine profile: total 1653
1368 @ 0x102ea0a 0x103e690 0x177a6b7 0x105b481
#	0x177a6b6	github.com/lightningnetwork/lnd/autopilot.(*Agent).OnNodeUpdates.func1+0x136	
~/golang/src/github.com/lightningnetwork/lnd/autopilot/agent.go:236
```
This PR fixes this by letting `nodeUpdates` being sent on their own channel, keeping at most one pending update at a time.
EDIT:
Same change is now done for pending opens, and open failures.
TODO:
> Reduce goroutine overhead on autopilot updates

- chainntnfs/interface_test.go
After joining the two forked chains, it is necessary to ensure they both agree on the same best hash before proceeding to `UnsafeStart` the notifier.
This is because when the `BitcoindClient` starts, it retrieves its best known block then calls `GetBlockHeaderVerbose` on the hash of the retrieved block. This block could be a reorged block if `JoinNodes` has not completed sync between the two chains. If it is the case that the best block retrieved has been reorged out of the chain, `GetBlockHeaderVerbose` errors because bitcoind sets the number of confirmations to -1 on reorged blocks, and the btcd rpc client panics when parsing a block whose number of confirmations is negative.
This parsing error should be fixed, and as a more permanent solution chain backends should ensure that the `best …
> chainntnfs/interface_test: fix unreliable historical block ntfns test

- server.go
In this commit, we restrict the persistent connection logic on startup
to only attempt to establish connections to Tor addresses if Tor
outbound support is enabled. Otherwise, we'll continually attempt to
reach the address even though we never will.
> server: ensure persistent connections to tor addrs are made if active

- contractcourt/chain_arbitrator.go
This commit restructures the initialization procedure
for chain watchers such that they can proceed in parallel.
This is primarily to help nodes running with the neutrino
backend, which otherwise forces a serial rescan for each
active channel to check for spentness.
Doing so allows the rescans to take advantage of batch
scheduling in registering for the spend notifications,
ensuring that only one or two passes are made, as opposed
to one for each channel.
Lastly, this commit ensures that the chain arb is properly
shutdown if any of it's chain watchers or channel arbs
fails to start, so as to cancel their goroutines before
exiting.
> contractcourt/chain_arbitrator: parallel chain watcher start

- Makefile
I noticed that there are some spaces missing in the Makefile so I added them.
> Added missing spaces to Makefile

- cmd/lncli/commands.go
> cmd/lncli: Fixed conflicting payinvoice amount output

- channeldb/migrations.go
This commit modifies the edge update index
migration to avoid repetitive calls to
Cursor.First(). Instead, we construct a set
of all edge update keys to remove, and then do
a second pass to remove each from the bucket.
Additional log messages are included to notify
users on progress, as some have reported long
migration times.
Fixes #1924
> channeldb/migrations: improve performance of edge update migration

- contractcourt/chain_watcher_test.go
- contractcourt/channel_arbitrator_test.go
Adds channel_arbitor test that exercises the htlcOutgoingContestResolver.
> cnct: add channel_arbitor htlcOutgoingContestResolver test

- docker/README.md
there are two markdown issues in docker/README.md, so i fixed them.
> docs:fix markdown issues in docker/README.md

- lntest/node.go
In this PR, we modify the test harness to persist the state of prior subscription events across restarts. @offerm discovered that the `testSwitchCircuitPersistence` fails probabilistically, depending on which node established the connection after a restart.
The test only seemed to fail whenever the restarted node connects successfully. Since a topology update is ignored if we detect a duplicate, after restarting this event will not be replayed to any `SubscribeChannelGraph` clients.
Thus after a restart, a node would not deliver another event, even though it had already seen the channel. In our testing harness, we currently wipe the state of subscriptions during restart, since the maps for tracking prior updates were not tied to the `HarnessNode` struct. The fix is then to keep these …
> lntest/node: persist network subscription state across restarts

- rpcserver.go
In this commit, we extend the AbandonChannel RPC method to store as much
information as possible within the CloseSummary. Most importantly, we
store the current and next (if available) revocation of the remote party
along with the channel config for the local party. With this
information, we have enough data to be able to generate a custom signer
for a new commitment state, or to prove that the channel was indeed
ours if needed.
> rpc: populate additional information in AbandonChannel close summary

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/neutrinonotify/neutrino.go
- chainntnfs/txconfnotifier.go
This PR modifies the chainntnfs package to properly commit height hints before delivering notifications. The primary motiviation is to ensure that downstream clients are provided with an externally consistent and crash consistent view of the notifier.
This PR comprises the first four commits in #1787
> chainntnfs: Reorder commit hints and notify

- Gopkg.lock
- Gopkg.toml
- chainntnfs/neutrinonotify/neutrino.go
- chainntnfs/neutrinonotify/neutrino_dev.go
- lnwallet/btcwallet/btcwallet.go
- routing/chainview/neutrino.go
This PR makes `lnd` compatible with the Neutrino API changed in https://github.com/lightninglabs/neutrino/pull/96 and https://github.com/btcsuite/btcwallet/pull/541
> Update to new Neutrino API

- autopilot/agent.go
- autopilot/graph.go
- autopilot/prefattach.go
> Autopilot: Typo fixes

- lntest/node.go
> [Trivial] lntest/node: remove extraneous externalip

- lnd_test.go
- lntest/harness.go
- lntest/node.go
> [Integration tests] mine reorged funding tx

- server.go
- server_test.go
Improved the color hex format validation code using regexp.
> Improving color validation

- lntest/node.go
> [Trivial] lntest: make DBPath aware of active net

- Gopkg.lock
- Gopkg.toml
- lnwallet/btcwallet/btcwallet.go
- lnwallet/interface.go
- lnwallet/interface_test.go
- mock.go
- rpcserver.go
Depends on https://github.com/btcsuite/btcwallet/pull/568/files (merged)
> lnwallet: update to new SendOutputs signature

- lnd_test.go
Split off from #2116.
This commit introduces a new utility method
waitForChannelPendingForceClose, that is used to ensure a force closed
channel has been recognized by the UTXO nursery, and is ready to be
swept as soon as it matures.
The commit also utilizes this method to properly wait before mining
blocks in certain tests, as it makes sure that the UTXO nursery will
react properly to the new blocks.
Fixes #2165
> lnd_test: add waitForChannelPendingForceClose

- Dockerfile
See EXPOSE additional directive line 32
> Add EXPOSE directive for 9735 (p2p) & 10009 (rpc)

- rpcserver.go
> rpc: properly set output index in OpenChannelSync resp

- lnd_test.go
> [trivial] lnd_test: make tests use global defaultCSV

- lntest/harness.go
Split off from #2116 
Adds a timeout to the `connect` calls, that could fail in tests if the backend was in the process of syncing the chain.
> lntest/harness: retry ConnectPeer of chain backend still syncing

- docs/INSTALL.md
In this commit, we aim to revamp the `INSTALL.md` file in order to make
it easier to parse, and more explicit. We've added a table of contents
to allow users to skip down to relevant sections and obtain a snapshot
of the contents of the document. Additionally, we've now modified the
headings to express a more clear delineation of the various sections.
> docs: revamp INSTALL.md

- autopilot/manager.go
This commit fixes a subtle bug within the autopilot manager, that would
cause the active pilot to not be reset in case it wasn't started
successfully.
We also make sure the associated goroutines close over the started
pilot, and not the active pilot.
> autopilot/manager: only set m.pilot if started successfully

- go.mod
- go.sum
When building LND docker image I got the following error when populating go modules
```
go: github.com/ltcsuite/ltcd@v0.0.0-20180701083835-cdab10132e8c: unknown revision cdab10132e8c
```
The commit in question `cdab10132e8c`, doesn't seem to be part of the master branch so I suspect that's why it's failing
Updating the revision of `ltcd` resolved the issue
Fixes #2394.
> Fix go module issue

- peer.go
In this commit, we modify the peer's writeMessage
method to properly handle errors returned from
encoding an lnwire message and from setting the
write deadline on the connection. Since an error
would likely result in an empty byte slice, the
worse case seems to be that we may have tried to
send an empty message on the wire.
Lastly, we correct the way we compute bytes sent
on the wire to properly count the number of bytes
*written*, and not just the length of the encoded
message.
> peer: handle message encoding errors on write

- aezeed/README.md
Most of these don't apply to pure documentation, but I checked anyhow.
logging level
per default)
already exist
> Fixup aezeed README (typos)

- lntest/node.go
Update documentation for `FetchNodeInfo` & `initLightningClient`.
> [trivial] lntest: FetchNodeInfo/initLightningClient docs update

- watchtower/lookout/justice_descriptor.go
- watchtower/lookout/justice_descriptor_test.go
- watchtower/wtdb/session_info.go
- watchtower/wtpolicy/policy.go
This PR adds the necessary calculations for deriving a justice transaction that gives all funds back to the client, and no reward for the tower. 
This facilitates watchtower modes where the client and tower have an existing relation, e.g. you are running your own tower, and it doesn't make sense to split fees off for the tower. Towers operating only in this mode could even be created without an on-chain wallet, which makes them even more lightweight than those that collect rewards. Since the initial rollout is tailored to private towers, this gives operators and users another useful configuration for backing up revoked states.
Depends on:
> watchtower/wtpolicy: altruist output calculation

- routing/missioncontrol.go
- routing/payment_session.go
Preparation to keep better overview for upcoming routing related work.
> routing: move payment session to separate file

- autopilot/agent.go
- autopilot/agent_test.go
To ensure a call to ConnectToPeer doesn't block the agent from
shutting down, we'll launch it in a non-waitgrouped goroutine, that
will signal when a result is returned.
This could cause `disabling` autopilot to hang if there were pending connections.
> autopilot: don't block Stop on pending connection

- aezeed/README.md
Just text changes
logging level
per default)
already exist
> Add a links to KDF and BIP39

- chainregistry.go
This PR implements proper "clean up" code in case there is a failure in the creation of neutrino ChainService.
More specifically, in case of error, close the database that was opened and stop the service if already started.
> Proper cleanup neutrino database in case of error

- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
> lnrpc: fix minor comment typo

- lnd_test.go
A few, trivial fixes encountered when running integration test with the Neutrino backend.
> Small integration test fixes

- rpcserver.go
This fixes #2552 using the solution suggested by @cfromknecht here https://github.com/lightningnetwork/lnd/issues/2552#issuecomment-459597592
> rpcserver: prevent overflow in channel count

- routing/router.go
Preparation for further mission control work.
> routing: sendPayment broken down into multiple functions

- cmd/lncli/commands.go
- walletunlocker/service.go
> Add password length validation condition on create wallet cli

- docs/code_contribution_guidelines.md
logging level
per default)
already exist
> docs: fix typo

- contractcourt/channel_arbitrator.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/test_utils.go
- lnd_test.go
- peer.go
- server.go
This PR is a rebase and extension of #2145 
Fixes #2144
> link: increase expiry grace delta for exit hop and forwarded htlcs

- lnd.go
- rpcserver.go
This commit restructures the creation of various TLS related objects. It also fixes a bug where wildcard IP addresses where only instantiated for the main RPC server (#2247) and not the WalletUnlocker service.
Broken off of #2428.
> lnd+rpcserver: refactor TLS configuration

- docs/configuring_tor.md
- Remove TOC entries of removed docs sections
- Add hint about complete inbound connection docs section after command
examples for inbound connections to prevent people from overseeing the
listen=localhost flag
logging level
per default)
already exist
> docs: fix broken TOC in Tor docs

- .github/pull_request_template.md
- docs/code_contribution_guidelines.md
- Update Go version 1.11 to 1.12
- Fix broken link in GitHub PR template
- Fix inconsistent number of spaces after checkbox
- Add proper link to "Ideal Git Commit structure"
logging level
per default)
already exist
> docs: update contribution checklist

- htlcswitch/link.go
This commit adds a brief delay when sending our channel reestablish
message if the link contains a restored channel to ensure we first have
a stable connection. Sending the message will cause the remote peer to
force close the channel, which currently may not be resumed reliably if
the connection is being torn down simultaneously. This delay can be
removed after the force close is reliable, but in the meantime it
improves the reliability of successfully closing out the channel and
allows the `channel_backup_restore/restore_during_creation` to pass
reliably.
> htlcswitch/link: delay restored channel reestablish

- go.mod
- go.sum
This new version of neutrino includes a number of fixes to the query
functionality of neutrino, stuck syncing issues, and peer connection
handling and banning.
> build: update to latest version of neutrino

- lnd_test.go
Instead of sleeping, we wait for at least one update to one of our
channels. This to make sure the HTLC has actually been committed.
> [lnd_test] wait for state update in completePaymentRequests

- lnd_test.go
> lnd_test: check Dave's balance in WaitNoErr

- lntest/node.go
This race was possible due to us making a subscription request before the ChannelRouter has started. We address it by creating a dummy subscription before proceeding to the real one to ensure we can do so successfully. We use a dummy one in order to not consume an update from the real one. This addresses the common "timed out waiting for opened channel" flake within the integration test suite since the subscription was never properly created, so we'd never be notified of when new graph updates were received.
> lntest: use test subscription to prevent SubscribeChannelGraph race

- channeldb/payments.go
- channeldb/payments_test.go
- lnrpc/routerrpc/router_backend.go
- lnrpc/routerrpc/router_backend_test.go
- lnrpc/routerrpc/router_server.go
- routing/route/route.go
- routing/router_test.go
- rpcserver.go
Instead get it on demand using method TotalFees().
As pointed out in https://github.com/lightningnetwork/lnd/pull/3064#discussion_r283911175
> routing/route+multi: remove redundant TotalFees field

- sample-lnd.conf
Just add minchansize description in sample config file to make to the user be aware of this option with a quick review.
> Add minchansize to sample config file

- cmd/lncli/commands.go
Fixes https://github.com/lightningnetwork/lnd/issues/3102.
> cmd/lncli: properly parse channel backup within lncli create

- go.mod
- go.sum
Includes a fix to make the tx broadcaster async: https://github.com/lightninglabs/neutrino/pull/150
> [dependency update]: update to latest neutrino dep

- lnrpc/routerrpc/router_backend_test.go
Run `make fmt` on `lnrpc/routerrpc/router_backend_test.go`
> [trivial] routerrpc test: run make fmt

- chainntnfs/neutrinonotify/neutrino.go
Since GetUtxo is a potentially long running call, we would see
RegisterSpendNtfn block in some cases, in particular on starting the
chain watcher, causing lnd to hang on startup.
This commit makes the call to GetUtxo in a go routine, letting
RegisterSpendNtfn return immediately when the notification events are
created.
> neutrinonotify: async call GetUtxo from RegisterSpendNtfn

- routing/router.go
- routing/router_test.go
Previously we would mistakenly use the payment value from the dummy
LightningPayment struct, which would obviously be 0 always. Now we
instead calculate the value from the given route.
This regression was introduced in https://github.com/lightningnetwork/lnd/pull/2761/commits/de1bf8a518145e7b33a6af6d64b05d560bf2cf73#diff-01ada5680aaa18fc79cbf78b2d55a37b, where we changed from using the route to calculate the amount, to using the LightningPayment.
Fixes https://github.com/lightningnetwork/lnd/issues/3146.
> routing/router: correct SendToRoute's amount record in DB

- docker/docker-compose.yml
it never passes, so the btcd service connects to simnet everytime
shoutout to @darwin for the help
logging level
per default)
already exist
> Added NETWORK env var to btcd service

- discovery/gossiper.go
We do this to ensure the node announcement propagates to our channel counterparty. At times, the node announcement does not propagate to them when opening our first channel due to a race condition between IsPublicNode and processing announcement signatures. This isn't necessary for channel updates as we already send those reliably.
Fixes #3058.
> discovery: set source of node announcement broadcast to belonging node

- channeldb/migrations.go
Previously the migration would fail if the source node was not set in
the database. Since we know that the source node must have been set
before making any payments, we check whether there actually are any
payments to migrate, and return early if not.
> channeldb/migrations: skip migration for empty outgoing payments bucket

- go.mod
- go.sum
> build: update btcwallet to version with seed restore fix

- lnrpc/watchtowerrpc/config_active.go
- lnrpc/watchtowerrpc/handler.go
- subrpcserver_config.go
> lnrpc/watchtowerrpc: prevent watchtowerrpc panic when tower not active

- routing/router.go
This commit moves the call to `PruneGraph` outside of the loop that collates all of the `spentOutputs` in `syncGraphWithChain`. With this change, if a node has been offline for a long period of time, resyncing with the chain no longer takes up as much memory (1MB vs 200MB in some cases) or time. Previously, PruneGraph was called for every block and allocated a very large map further down in the pruneGraphNodes function. Now, pruneGraphNodes is only called once.
I found this by profiling lnd and noticed that it allocated a huge amount of memory in the `pruneGraphNodes` function.  This was after my node was offline for several hundred blocks.  The `syncGraphWithChain` function also took ~20 seconds.
```
ROUTINE ======================== …
```
> routing: move call to PruneGraph outside of the collating loop

- cmd/lncli/commands.go
> cmd/lncli/commands: fix updatechanpolicy lowest possible fee msg

- cmd/lncli/commands.go
suer should be user
logging level
per default)
already exist
> trivial: typo fix (closes #3268)

- lnwallet/btcwallet/signer.go
In this commit, we fix an existing bug that would cause us to be unable
to derive the very first key in a key family if the wallet hadn't
already derived it in the past. This can happen if a user keeps their
same `channel.db`, but restores their wallet resulting in fresh
`wallet.db` state.
This is an existing issue due to the fact that we don't properly
distinguish between an empty key locator, and the very first key in a
`KeyFamily`: `(0, 0)`. Atm, `KeyLocator{0, 0}.IsEmpty() == True`,
causing us to be unable to retrieve this key in certain cases since we
fall through and attempt address based derivation.
In order to remedy this, we add a new special case (until we upgrade
`KeyLocator` formats, but needed for legacy reasons) to _try_ a regular
`KeyLocator` based derivation if we fail to …
> lnwallet: fix key derivation for very first key in family

- docs/recovery.md
minor typo on line 286, said 'implement' twice
logging level
per default)
already exist
> Update recovery.md (typo)

- docs/MAKEFILE.md
Just a small change - thought I'd try to clarify what the "itestcase" arg is in the make itest section. 
This confused me a bit, so figured I'd propose more explicit instructions in case anyone else has the same problem :)
> MAKEFILE: Clarify what the testcase argument is

- .gitignore
- lntest/harness.go
- lntest/itest/lnd_test.go
- lntest/node.go
- make/testing_flags.mk
Fixup of https://github.com/lightningnetwork/lnd/pull/1529
Fixes #1219
Replaces #1529
> [lnd test] write goroutine snapshot on integration test failure

- lntest/itest/lnd_test.go
In this PR, we fix this Travis flake:
```
--- FAIL: TestLightningNetworkDaemon/multiple_channel_creation_and_update_subscription (13.43s)
lnd_test.go:75: Failed: (multiple channel creation and update subscription): exited with error: 
*errors.errorString errored verifying close updates: timeout waiting for channel notifications, only received 3/4 chanupds
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:5923 (0xc01d59)
testBasicChannelCreationAndUpdates: t.Fatalf("errored verifying close updates: %v", err)
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:100 (0xbdfcc6)
(*harnessTest).RunTestCase: testCase.test(net, h)
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:13401 (0xc3fa84)
TestLightningNetworkDaemon.func4: …
```
> lnd_test: fix channel event subscription test flake.

- lnd.go
In this PR, we establish a new pattern to always log errors before returning them to the higher level caller, which then prints the error to stdout/stderr. Errors returned are usually lowercase, but we decide not to apply this rule here as these errors should not be chained forward.
Fixes https://github.com/lightningnetwork/lnd/issues/3323.
> lnd: log error if any throughout initialization

- lnwallet/btcwallet/signer.go
- lnwallet/interface_test.go
In this commit, we address an edge case that can happen a user rescans
w/ their seed, while retaining their existing `channel.db`. Once they
rescan, if they go to sign for a channel sweep for example, the
commitment key family (actually an account) may not yet have been
created, causing the signing attempt to fail.
We remedy this always creating the account if we go to sign, and the
account isn't found. The change has been structured to make this the
exception, so we'll avoid always needing to do 2 DB hits (check if
account exists, sign), each time we sign.
A new test has been added to exercise this behavior. If the diff from
the `signer.go` file is removed, then the test will fail.
> lnwallet: when signing create account if not found

- discovery/gossiper.go
- pilot.go
- utxonursery.go
> pilot+discovery: die spew

- lnwire/features.go
- zpay32/invoice.go
- zpay32/invoice_test.go
An implementation of https://github.com/lightningnetwork/lightning-rfc/pull/656
> zpay32: BOLT 11 Feature Bits

- rpcserver.go
> rpcserver: order updates in getnodeinfo by increasing pubkey

- lntest/itest/lnd_test.go
Alice and Dave don't need to be connected in order to receive the node announcement as we assume that she can receive it from Bob because they are connected at the beginning of every test.
> lntest/itest: prevent direct connection within testNodeAnnouncement

- lntest/itest/lnd_test.go
The test assumed that transactions would be broadcast and confirmed at incorrect heights. Due to timing issues, it was possible for the test to still succeed, resulting in a flake.
The test assumes that Bob will sweep a pending outgoing HTLC and commit output back to their wallet. This commit ensures that these operations are done when expected, i.e.:
1. Bob force closes the channel due to the HTLC timing out.
2. Once the channel is confirmed, Bob broadcasts their HTLC timeout transaction.
3. Bob broadcasts their commit output sweep transaction once its CSV expires.
4. Bob broadcasts their second layer sweep transaction for the timed out HTLC once its CSV expires.
> lntest/itest: resolve mempool flake in multi-hop htlc local timeout test

- htlcswitch/circuit.go
- htlcswitch/circuit_map.go
- htlcswitch/circuit_test.go
- htlcswitch/failure.go
- htlcswitch/hop/error_encryptor.go
- htlcswitch/hop/iterator.go
- htlcswitch/hop/iterator_test.go
- htlcswitch/hop/log.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/log.go
- htlcswitch/mock.go
- htlcswitch/packet.go
- htlcswitch/switch.go
- htlcswitch/test_utils.go
- server.go
Prepares for onion blob decoding outside of htlcswitch.
> htlcswitch: move hop iterator into htlcswitch/hop package

- chainntnfs/btcdnotify/btcd.go
- chainntnfs/neutrinonotify/neutrino.go
We would establish the connection to the chain backend and start getting
block notifications before we had started the concurrent queues, which
would lead to the OnBlockConnected call being blocked, and a deadlock
(since GetBestBlock would never return).
Instead we make sure to start the queues before establishing the
connection, consuming the notifications right away.
This should fix the "router not started" error seen during integration tests.
> chainntnfs: start concurrent queues prior to connection

- brontide/noise_test.go
This PR fixes a test in `brontide` where two of the error conditions could never be recorded, because they were happening in a goroutine.
`T.Fatal()` is a convenience function that combines `T.Log()` and `T.FailNow()`. 
From the godoc of `T.FailNow()`: 
> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.
To see this in action, take a look at `main_test.go` in my [example repo](https://github.com/alrs/fatalfail/).
> brontide: fix test goroutine

- config.go
> config: fix configfile flags

- README.md
Fixes #3542 
Also fixes markdown for link.
- [ x] If this is your first time contributing, we recommend you read the [Code
- [ x] All changes are Go version 1.12 compliant
- [ x] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [ x] For new code: Code is accompanied by tests which exercise both
- [ x] For bug fixes: Code is accompanied by new tests which trigger
- [ x] Any new logging statements use an appropriate …
> README: Fixing link to gpg key for security@lightning.engineering

- docs/watchtower.md
- lncfg/wtclient.go
- lnrpc/wtclientrpc/driver.go
- lnrpc/wtclientrpc/wtclient.go
Fixes https://github.com/lightningnetwork/lnd/issues/3375.
> docs: update watchtower docs to include wtclientrpc info

- config.go
config: allow mainnet neutrino
> config: allow mainnet neutrino

- peer.go
- server.go
Without waiting, we would proceed to retrieve the remote peer's supported features, which may have not been set due to not yet receiving their Init message.
Fixes https://github.com/lightningnetwork/lnd/issues/3553.
> peer+server: wait until peer is active to begin channel opening process

- server.go
> server: don't prune manual perm connections

- routing/pathfind.go
To help diagnose problems in this area.
> routing: log performance metrics

- contractcourt/channel_arbitrator.go
In this commit, we fix a bug that would prevent users that had
unresolved contracts at the time of update from starting their nodes.
Before we added the conf commit set, the information needed to
supplement the resolvers was found in the chain action map. As a result,
if the conf commit set is nil, then we also need to check this legacy
data to ensure that we can supplement the resolvers to the best of our
ability based on the available data.
Fixes #3549.
> contractcourt: use legacy chain actions of commitSet not found

- routing/router_test.go
This PR replaces the use of a `testing.T.Fatal()` inside a goroutine with an error channel.
`T.Fatal()` is a convenience function that logs and then calls `T.FailNow()`.
From the `T.FailNow()` godoc:
> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.
> routing: fix use of T.Fatal() in test goroutine

- docs/macaroons.md
- macaroons/README.md
Updates the `docs/macaroons.md` and `macaroons/README.md` with information about the recently merged macaroon bakery.
> doc: describe macaroon bakery

- mobile/README.md
> trivial: fix typo

- macaroons/store.go
Found while testing out watchtowers with the race detector. Calling `lncli tower info` followed by shutting down the `lnd` instance led to this race. The `tower info` call was reading with the key while the `defer Close()` call zeroed the key out.
```
Write at 0x00c0002321e0 by main goroutine:
github.com/lightningnetwork/lnd/macaroons.(*RootKeyStorage).Close()
/Users/nsa/go/pkg/mod/github.com/btcsuite/btcwallet@v0.10.0/internal/zero/array.go:10 +0xed
github.com/lightningnetwork/lnd/macaroons.(*Service).Close()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/macaroons/service.go:192 +0x50
github.com/lightningnetwork/lnd.Main()
/Users/nsa/go/src/github.com/lightningnetwork/lnd/lnd.go:660 +0x2cd9
main.main() …
```
> macaroons: add encKeyMtx to prevent race condition

- go.mod
- go.sum
This version of Neutrino brings several improvements:
https://github.com/lightninglabs/neutrino/pull/189
https://github.com/lightninglabs/neutrino/pull/179
https://github.com/lightninglabs/neutrino/pull/191
> mod: update neutrino dep

- chainntnfs/txnotifier_test.go
TestTxNotifierSpendDuringHistoricalRescan checks that the height hints and
spend notifications behave as expected when a spend is found at tip during a
historical rescan.
> [test only] add TestTxNotifierSpendDuringHistoricalRescan

- sample-lnd.conf
Minor addition to #2704, because I was wondering how to set multiple tlsextra entries.
> Document setting multiple tlsextra entries

- lntest/node.go
Fixes a slight race condition that could happen since Alice and Bob are
created in different goroutines, leading to using the same listening
ports.
> lntest/node: add numActiveNodesMtx

- lntest/node.go
This changes TCP port selection in integration tests from being
sequential, based on the node ID to being sequential but tested before
assigment.
This should reduce the number of flaky tests that fail due to the port
already being used by another process in the CI server.
Example of a test that failed due to this: https://travis-ci.org/lightningnetwork/lnd/jobs/612299358#L337
> lntest: Use TCP ports not based in nodeID

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/interface.go
- chainntnfs/txnotifier.go
To help track down the root cause for #3692
> [chainntnfs] add more logging for spend requests

- config.go
Correct `diconnecting` to `disconnecting`
> trivial: typo fix

- discovery/syncer.go
logging level
per default)
already exist
> fix order in wrong chain error message

- lnrpc/signrpc/signer.pb.go
Looks like the docs were changed w/o recompiling.
> signrpc: fix uncommitted changes from proto

- sample-lnd.conf
Fixes #3810.
logging level
per default)
- ❌ Running `make check` does not fail any tests
- `github.com/lightningnetwork/lnd/chainntnfs` tests fail, but I don't think this is because of the changes in the PR.
already exist
> config: Make bools in sample-lnd.conf consistent

- build/release/release.sh
Enhances the release script to check that the specified tag is also the tag that is currently checked out. In addition to that, the script also ensures that the tag and the version specified in version.go match.
> build: add version checks to release script

- routing/pathfind_test.go
Modifies TestMissingFeatureDep and TestDestPaymentAddr to use the test
ctx directly instead of generating a closure and using local state to
modify restrictions.
> routing/pathfind_test: use ctx in recent tests

- discovery/syncer.go
- discovery/syncer_test.go
If the provided ChainHash in a QueryChannelRange message does not match that of our current chain, then we should send a blank response, rather than reply with channels for the wrong chain.
Fixes https://github.com/lightningnetwork/lnd/issues/3921.
> discovery: check ChainHash in QueryChannelRange messages

- rpcserver.go
This change instructs the REST proxy server to overwrite its default
JSON marshaler settings. That allows us to set EmitDefaults to true
which will result in all JSON fields returned in REST responses to
be fully populated, even if their values are falsey.
Fixes #2087.
> rpcserver: instruct REST marshaler to emit default values

- invoices/invoice_expiry_watcher.go
- invoices/invoiceregistry.go
This PR fixes incorrect log messages.
> invoices: fix log messages

- lnwallet/channel.go
- lnwallet/channel_test.go
> lnwallet: fix invalid value use in restoreUpdate

- .golangci.yml
- make/testing_flags.mk
Remove remaining flags from makefile.
from #3515 now wtclientrpc is default
> Remove remaining wtclientrpc flags

- peer.go
This commit removes the `failedChannels` map from the peer.
Currently it is only read on peer startup before anything is entered
into the map.
> peer: remove unused failedChannels channels map

- pilot.go
> [trivial] pilot: log whether autopilot is active at startup

- lnd.go
- lnwallet/chanfunding/assembler.go
- lnwallet/wallet.go
- sweep/interface.go
- sweep/store_test.go
- sweep/sweeper.go
- sweep/sweeper_test.go
- sweep/test_utils.go
- sweep/walletsweep.go
> trivial: typo fixes

- fuzz/wtwire/create_session.go
- fuzz/wtwire/create_session_reply.go
- fuzz/wtwire/delete_session.go
- fuzz/wtwire/delete_session_reply.go
- fuzz/wtwire/error.go
- fuzz/wtwire/fuzz_utils.go
- fuzz/wtwire/init.go
- fuzz/wtwire/state_update.go
- fuzz/wtwire/state_update_reply.go
This PR introduces fuzzing harnesses for the `wtwire` package.  These are simple serialization+de-serialization tests much like #1895.  
Coverage here: https://crypt-iq.github.io/wtwire.html
Corpus: https://github.com/Crypt-iQ/crypt-iq.github.io/tree/master/wtwire
> fuzz/wtwire: adding wtwire fuzzers

- routing/missioncontrol.go
- routing/pathfind.go
Adds several extra values to routing-related log statements as a preparation for mpp send diagnostics.
> routing+htlcswitch: logging improvements

- docker/README.md
This is a simple one-word readme update, so omitting the pull request checklist.
Fixes #4116.
> Fix text in docker readme

- peer.go
This ensures that our node announcement can propagate throughout the network even for nodes that were offline when we initially broadcast it.
Fixes https://github.com/lightningnetwork/lnd/issues/3928 with an alternative work-around. Channel updates aren't affected as much as node announcements, as those can be recovered from failed payment attempts.
> peer: send local node announcement upon establishing peer connections

- go.mod
- go.sum
The latest versions of the `psbt` package includes some decoding bug
fixes.
> build: update to latest btcutil and psbt versions

- invoices/invoice_expiry_watcher_test.go
This PR removes sleeps from invoice expiry watcher tests in favor of
a timeout guard.
> invoices: elminitate sleep from expiry watcher tests

- fundingmanager.go
This addresses a bug in which a funding reservation wasn't cleaned up properly if the remote peer didn't support upfront shutdown. Alternatively, we could just cancel the reservation on error, but instead we move the check above so that we don't attempt coin selection in the first place.
Fixes https://github.com/lightningnetwork/lnd/issues/4179.
> fundingmanager: check remote peer upfront shutdown support before reservation

- htlcswitch/mailbox_test.go
Modifies some of the older mailbox tests that were left untouched as of
PR #4174 to use the new mailbox test context. This ensures that the
config members of each mailbox's config are properly initialized. In
certain instances where travis is slow, this would cause test panics.
> htlcswitch/mailbox_test: use mailboxContext everywhere

- rpcserver.go
If the server hasn't fully started yet, it's possible that the channel event store hasn't either, so it won't be able to consume any requests until then. To prevent blocking, we'll just omit the uptime related fields for now.
> rpcserver: omit uptime in ListChannels response if server not started

- lnwallet/channel.go
- lnwallet/channel_test.go
This PR extracts relevant unit tests in #4093 so that we can increase coverage in this area, even if we decide not to go ahead with the refactor in the referenced PR.
> lnwallet/test: add coverage for evaluateHtlcView

- lntest/itest/log_error_whitelist.txt
PR to collect missing whitelist lines
Reply in comments with everything that is encountered.
> itest: extend whitelist

- lntest/itest/log_check_errors.sh
- lntest/itest/log_error_whitelist.txt
Continuation of #4249
Reply in comments with everything that is encountered.
> itest: extend whitelist 2

- htlcswitch/switch.go
Added log message for successfully forwarded HTLCs. Example:
`[INF] HSWC: Forwarded HTLC(2f9c512c6212d29484da553108b7a4d84855be506899e6d216e452ee300c1ad1) of 11700000 mSAT (fee: 590 mSAT) from IncomingChanId(1512615:22:0) to OutgoingChanId(1512621:51:1)`
logging level
per default)
already exist
> htlcswitch/switch: log successfully forwarded HTLCs

- clock/go.mod
- go.mod
- lntest/itest/log_error_whitelist.txt
This PR makes `clock` which makes it possible to use in other projects too.
> clock: add module support

- config.go
- lnrpc/routerrpc/router_backend.go
- lnrpc/routerrpc/router_backend_test.go
- lntest/itest/lnd_multi-hop-error-propagation.go
- rpcserver.go
> rpcserver+routerrpc: remove payment limit

- channeldb/db.go
- lnd.go
Noticed from logs in https://github.com/lightningnetwork/lnd/pull/2668#issuecomment-635115304
> channeldb: dry run migration logs

- fundingmanager.go
Fixes https://github.com/lightningnetwork/lnd/issues/4336.
> fundingmanager: log raw transaction on broadcast

- contractcourt/htlc_incoming_contest_resolver.go
> contractcourt/incoming_resolver: Improve comments

- invoices/invoiceregistry.go
SettleHodlInvoice and CancelInvoice both notifyClients after
notifyHodlSubscribers. This commit changes UpdateInvoice to follow the
same pattern so that we are consistent.
> invoices: ensure ntfns are sent in the same order

- channeldb/invoice_test.go
- channeldb/invoices.go
- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
This PR special-cases the all-zeros payment address during the invoice insertion
flow, preventing the invoices from being indexed in the payment address index. This
restores the keysend functionality in master which was broken as of #4285, due to the
fact that the blank payment addresses would collide and be rejected as duplicates 
when receiving more than one keysend payment.
The full fix would be to generate random payment addresses for keysend payment, and
bring them in line with all other invoices. However, we choose this path as a temporary 
measure until the additional AMP-related changes are in-places to avoid creating
an additional, persistent payment type, i.e. keysend invoices indexed by payment address.
When the full AMP changes are in, we'd like to index by both payment …
> invoices/invoiceregistry: special-case payaddr index insertion for keysend

- cert/selfsigned.go
- channeldb/kvdb/etcd/stm.go
- lntest/itest/lnd_forward_interceptor_test.go
- pilot.go
master missing `go fmt`, fix it.
> lnd: fix go fmt

- docs/INSTALL.md
> docs: update install docs to no longer use go get

- lnrpc/walletrpc/walletkit_server.go
- lntest/harness.go
- lntest/itest/lnd_test.go
- lntest/itest/onchain.go
- lntest/node.go
Various tweaks to improve flakiness of itests.
> lntest+itest improvements

- chainntnfs/bitcoindnotify/bitcoind_test.go
- chainntnfs/btcdnotify/btcd_test.go
- chainntnfs/height_hint_cache.go
- chainntnfs/height_hint_cache_test.go
- chainntnfs/interface_test.go
- chainregistry.go
- lnwallet/interface_test.go
Small PR to address @wpaulino's nits on #4412. Mostly just renaming + line wrapping, also adds a unit test.
> chainntfns: disable height-hint cache followups

- docs/INSTALL.md
- go.mod
6250ed1cf1670fea11ddff1c330a26193c3f0915 from #4141 uses [http.NewRequestWithContext](https://github.com/lightningnetwork/lnd/blame/87880c0d56937f2380acee37910492b2fc7b910f/lnrpc/websocket_proxy.go#L97). This will not compile with go 1.12 since this method was only introduced in go 1.13 [see changelog entry](https://golang.org/doc/go1.13).
Alternatively, a PR can be opened to remove the usage of this method.
logging level
per default)
already …
> chore: Update minimum golang version to 1.13

- .travis.yml
- Makefile
- channeldb/forwarding_log.go
- channeldb/forwarding_log_test.go
- go.mod
- go.sum
- lntest/btcd.go
- lntest/itest/lnd_multi-hop-payments.go
- lntest/itest/lnd_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/4453.
Depends on https://github.com/btcsuite/btcd/pull/1609.
Depends on #4408.
> travis: add integration test on Windows

- lntest/itest/log_error_whitelist.txt
- lntest/itest/log_substitutions.txt
Add outstanding error whitelist entries.
> lntest/itest: update error whitelist

- sample-lnd.conf
In this commit, we update the `sample-lnd.conf` example config file to
be up to date with all the new configuration parameters we've added over
the past few release.
> docs: update sample-lnd.conf

- config.go
- docs/macaroons.md
- lncfg/address.go
- lncfg/address_test.go
Fixes #3080
previous discussion can be found in #4258
> lncfg: allow no auth on private addresses

- chainregistry.go
- config.go
- contractcourt/anchor_resolver.go
- contractcourt/channel_arbitrator_test.go
- lncfg/neutrino.go
- lntest/fee_service.go
- lntest/fee_service_test.go
- lntest/harness.go
- lntest/node.go
- lnwallet/chainfee/estimator.go
- lnwallet/chainfee/estimator_test.go
- sweep/bucket_list.go
- sweep/sweeper.go
- sweep/tx_input_set.go
> cnct+sweep+itest: preparations for cpfp-aware sweeper

- go.mod
- go.sum
Includes a fix for #4016 in addition to some other bug fixes and
enhancements.
> build: update neutrino to latest version

- lntest/itest/lnd_test.go
- lntest/node.go
Current build has a test flake in `open_channel_reorg_test`, logs can be found [here](https://travis-ci.org/github/lightningnetwork/lnd/jobs/731354058). A timeout happened when setting up the temp miner.
To further assist the debugging, the temp miner's logs are saved.
> itest: save temp miner's logs

- fmgr/interfaces.go
- fundingmanager.go
- fundingmanager_test.go
- peer/brontide.go
- server.go
This will help with deleting some more of the fluff in the peer package.
> multi: add fmgr.Manager interface, change usage in peer to use Manager

- lnd.go
This will help to verify the debuglevel that is used
> lnd: show debug level at startup

- autopilot/agent.go
- autopilot/agent_constraints.go
- autopilot/agent_constraints_test.go
- autopilot/agent_test.go
- autopilot/combinedattach.go
- autopilot/externalscoreattach.go
- autopilot/graph.go
- autopilot/interface.go
- autopilot/manager.go
- autopilot/prefattach.go
- autopilot/prefattach_test.go
- autopilot/top_centrality.go
- autopilot/top_centrality_test.go
- pilot.go
> [autopilot] Use local channel balance in allocation calculation

- .gitignore
- Makefile
- go.mod
- go.sum
- make/fuzz_flags.mk
- scripts/fuzz.sh
I created this while reviewing/testing #4640.
This is basically what's described in https://github.com/lightningnetwork/lnd/blob/master/docs/fuzz.md but as make commands.
> Add fuzzing commands to Makefile

- cmd/lncli/cmd_pay.go
> lncli: allow configurable timeout in send payment

- lnrpc/walletrpc/walletkit.proto
> trivial: fix make rpc-format

- lntest/itest/lnd_test.go
This ensures the Carol and Dave nodes created in the single_hop series
of tests are synced to the latest chain tip generated by the miner
before creating the route that will eventually be used for payments.
This prevents a flake during CI tests where slow processing of blocks
by Carol could cause the generated route to have a final CLTV delta too
short for Dave to accept.
While at it, we switch the test to use the default CLTV delta provided
by QueryRoutes which is now the global default CLTV.
> itest: Sync nodes to chain during singleHop tests

- invoices/invoice_expiry_watcher.go
- invoices/invoice_expiry_watcher_test.go
- invoices/invoiceregistry.go
This PR reduces heap usage upon start by only caching `invoiceExpiry` objects rather than all active invoices before pushing them to the watcher. Although this is a one time thing, it may improve start time for nodes with large amount of invoices.
> invoices: reduce heap usage when starting the expiry watcher

- chainreg/log.go
- log.go
Previously not registered, so would not log anything.
> chainreg: register logger

- README.md
See 2b71e56a8843ee8a5b9ba351b1e5beb953b48f66 and b71cb0dbd884a9b8f2578d8c86627be2b20480be
> README: remove stray [

- docs/INSTALL.md
Neutrino will now work out of the box in LND
> docs: Add mention of support for Neutrino

- htlcswitch/payment_result.go
- htlcswitch/switch.go
- routing/payment_lifecycle.go
- routing/router.go
Adding some logs in aid of debugging https://github.com/lightningnetwork/lnd/issues/4788
> [logging] add more logging for failed payment shards

- htlcswitch/link_test.go
- htlcswitch/test_utils.go
> [test] Increase link test timeouts

- htlcswitch/link.go
- lnwire/error.go
> multi: small code fix

- lntest/itest/log_check_errors.sh
- lntest/itest/log_error_whitelist.txt
Because of changed log file paths, the error whitelist check script needs an update.
> itest: fix error whitelist script

- .github/workflows/main.yml
- scripts/check-commit.sh
- scripts/check-each-commit.sh
Inspired by Rust Lightning's GH action :)
during local development, you can run `./scripts/check-each-commit.sh origin/master`
to see if your commits pass before pushing.
> build: check compilation of each commit

- peer/brontide.go
- peer/brontide_test.go
- peer/test_utils.go
This PR updates the peer package to downgrade the static remote key feature bit from required to optional in the case where we have legacy channels with the peer. Without this change, `lnd` will not connect to peers that do not recognize the feature bit, and any legacy channels with these peers will be unusable. 
The last commit in this PR adds a workflow which tests the upgrade path, since we do not have a way to test different versions in our itests. Rather than spin up an eclair mobile node (which does not recognize the feature bit), test test uses lnd `0.7.0-beta`, which does not recognize the feature bit, to test the upgrade path. **To be removed before merge.**
Fixes #4800
> peer: do not require static remote for peers with legacy channels

- aezeed/cipherseed.go
- autopilot/interface.go
- autopilot/manager.go
- brontide/conn.go
- brontide/listener.go
- brontide/noise.go
- lnwire/announcement_signatures.go
- lnwire/channel_reestablish.go
- lnwire/channel_update.go
- lnwire/commit_sig.go
- lnwire/error.go
- lnwire/features.go
- lnwire/init_message.go
- lnwire/node_announcement.go
- lnwire/onion_error.go
- lnwire/open_channel.go
- lnwire/query_short_chan_ids.go
- lnwire/reply_short_chan_ids_end.go
- lnwire/revoke_and_ack.go
- peer/brontide.go
- pool/read_buffer.go
- pool/write.go
- pool/write_buffer.go
A collection of typo fixes while reading the code.
> multi: Typo fix

- cmd/lncli/commands.go
- docs/recovery.md
logging level
per default)
already exist
> Fix typo in restorechanbackup command description

- lnrpc/routerrpc/router.proto
- lnrpc/routerrpc/router.swagger.json
Unformatted protos are aking travis fail.
> lnrpc: format protos

- .github/workflows/main.yml
- .github/workflows/release.yaml
- build/version.go
Included PRs since v0.12.1-beta.rc2:
- #5013
> v0.12.1-beta.rc3

- scripts/verify-install.sh
Instead of only allowing the installed versions of lnd and lncli to be
verified, we now also support specifying explicit paths to binaries that
we want to verify.
> scripts: allow verification of custom binary

- build/version.go
- routing/router.go
- routing/router_test.go
PRs included since v0.12.1-beta.rc5:
- #5043
> v0.12.1-beta.rc6

- lnd.go
After unification of the WalletUnlocker and RPC services on the same gRPC
server, the WalletUnlocker will no longer be shut down after the wallet
has been unlocked.
In case --no-macaroons was used, this lead to the caller getting stuck
after unlocking the wallet, since we would wait for a response on the
MacResponseChan. Earlier we would close the MacResponseChan always
when shutting down the WalletUnlocker, but this is no longer done.
To fix this we close this channel after the wallet is unlocked,
regardless of which combination of --no-macaroons and --noseedbackup
that is being used.
cc @hsjoberg
> lnd: close MacResponseChan when wallet is unlocked

- cmd/lncli/cmd_invoice.go
* pass amt and amt_msat to rpc, letting server give an error if both
are present
* take amt from an extra argument if neither amt nor amt_ms are
present
implementation analogous to 298f35cdfbcfbf171fb7de645e90bdf6a368d6c8,
which is for addholdinvoice.
logging level
per default)
already exist
> lncli addinvoice: allow specifying msat with --amt_msat

- sample-lnd.conf
This explains the purpose of `accept-keysend` and its planned deprecation in detail.
Fixes #5190
This is documentation change, so the checklist shouldn't apply.
logging level
per default)
already exist
> Better document the nature of accept-keysend

- routing/router.go
Small optimization that removes a chain backend call that fetches a number that we already have.
> routing: no backend call to fetch best block

- .travis.yml
- lntest/harness.go
- lntest/itest/lnd_channel_backup_test.go
- lntest/itest/log_error_whitelist.txt
- lntest/node.go
Not sure if this will have an effect on the itest runs on Travis, just testing.
> Travis: fix Windows itest

- build/version.go
Version bump to rc3 for 0.13, includes:
* https://github.com/lightningnetwork/lnd/pull/5303
* https://github.com/lightningnetwork/lnd/pull/5309
* https://github.com/lightningnetwork/lnd/pull/5226
* https://github.com/lightningnetwork/lnd/pull/5247
* https://github.com/lightningnetwork/lnd/pull/5305
> build: bump version to v0.13.0-beta.rc3

- rpcserver.go
Fixes #5325.
Corrects a problem introduced in #5281 that caused the synced_to_chain
flag in the GetInfo call to never become true when the router subsystem
is running in Neutrino mode (channel validation turned off).
> rpcserver: check router state only if it is validating

- docs/INSTALL.md
you must be root  to be able to install go on /usr/local/
without  "sudo" the command fails with :  
tar: go/src/cmd/go/main.go: Cannot open: No such file or directory
logging level
per default)
already exist
> Update INSTALL.md : update command line to install go 

- go.mod
- go.sum
- htlcswitch/hop/iterator.go
Onion decoding is a cpu-intensive operation. This PR modifies the logic to decode a batch of onion packets in parallel.
depends on https://github.com/lightningnetwork/lightning-onion/pull/49
> htlcswitch: concurrent onion decoding

- rpcserver.go
Fixes https://github.com/lightningnetwork/lnd/issues/5359.
If the wallet recovery chain rescan was aborted before it finished, the
user would need to remember to use a positive recovery_window value the
next time they unlock the wallet for the rescan to continue. Because
forgetting to do so could lead to an incomplete wallet state (and
therefore potential missing funds) we rather don't allow shutting down
lnd through the RPC while a rescan is in progress.
This won't prevent any user from manually signaling Ctrl+C to kill lnd.
But that user might also check the log and see there's still something
going on that's preventing lnd from shutting down.
To properly fix this we should probably persist the recovery progress in the wallet. I have a PR on my TODO list that improves some things in the …
> rpcserver: prevent shutdown during wallet recovery

- lntest/itest/lnd_onchain_test.go
- lnwallet/wallet.go
This PR aims to address a flaw in our anchor reserve enforcement logic in which an inbound "legacy" channel (i.e. a channel with a commitment type that precedes anchors) would be rejected by the recipient if they have at least one opened channel using the anchors commitment type and do not have enough on-chain funds to meet the anchors reserve.
The first commit shows how the test fails due to the bug addressed in the second commit.
Fixes https://github.com/lightningnetwork/lnd/issues/5381.
> lnwallet: prevent anchor reserve enforcement on legacy inbound channel

- docs/release-notes/release-notes-0.13.1.md
- lntest/itest/log_error_whitelist.txt
This PR updates the release notes ahead of the upcoming tag of `v0.13.1-beta.rc1`
> lnd: v0.13.1 rc1 branch prep

- docs/leader_election.md
This PR adds basic user documentation for testing LND clustering with leader election.
> docs: leader election docs

- htlcswitch/link.go
> htlcswitch: log amount for failures

- .travis.yml
- lntest/harness.go
- lntest/itest/lnd_test.go
- lntest/node.go
- make/testing_flags.mk
This PR makes several changes to the itest framework to prepare for multiple db backend support.
> itest: prepare for multiple db backends

- docs/release-notes/release-notes-0.13.1.md
- go.mod
- go.sum
Fixes https://github.com/lightningnetwork/lnd/issues/5467
Depends on https://github.com/btcsuite/btcwallet/pull/754
> btcwallet: filter out expired leases

- README.md
> README: minor typo fix

- kvdb/etcd/embed.go
- lntest/harness.go
Fix for https://github.com/lightningnetwork/lnd/issues/5491
> harness: remove killed nodes from active nodes

- cmd/lncli/invoicesrpc_active.go
- docs/release-notes/release-notes-0.14.0.md
Removed an unused error check in invoice.
> invoice: unused error check

- docs/release-notes/release-notes-0.14.0.md
- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
This PR fixes a couple of minor typos.
> Fix typos in `dest_custom_records` comment

- docs/INSTALL.md
- docs/release-notes/release-notes-0.14.0.md
[Pruning is supported since 0.13](https://github.com/lightningnetwork/lnd/pull/5154)
This is just docs change.
> Remove warning about pruned nodes

- cmd/lncli/cmd_profile.go
- cmd/lncli/commands.go
- cmd/lncli/invoicesrpc_active.go
- docs/release-notes/release-notes-0.14.0.md
Found some missing dots in the command line interface.
> trivial: missing dots

- docs/release-notes/release-notes-0.14.0.md
- lntest/itest/lnd_payment_test.go
Minor bug fix to payments test to include correct object in test fail message.
> itest: fix payment test error message

- config.go
- lncfg/tor.go
- lnd.go
- sample-lnd.conf
- tor/net.go
- tor/tor.go
###
Closes https://github.com/lightningnetwork/lnd/issues/5042
This PR allows the Tor dialer (`ProxyNet`) to avoid routing traffic via Tor for targets which can be contacted via clearnet. 
logging level
per default)
already exist
> Add Tor hybrid connectivity mode

- docs/release-notes/release-notes-0.14.0.md
Minor fix in the 0.14 release doc.
> docs: release note fix

- docs/code_contribution_guidelines.md
I missed reviewing #5614, so this is more a follow-up grammar and typo suggestion turned fix.
> trivial: minor grammar and typo fix [skip ci]

- docs/safety.md
In #5553 `docs/INSTALL.md` was updated to reflect that prune nodes are supported.
> docs: Remove pruned node warning.

- docs/release-notes/release-notes-0.14.0.md
- rpcserver.go
> lnd: adds NOT_FOUND status code for LookupInvoice

- lntest/harness.go
This commit fixes a nil pointer issue when a node fails to start up.
Because require.NoErrorf() doesn't abort a test immediately if run
inside a goroutine, this lead to the test continuing with nil node
references which lead to a panic later on.
> lntest: use errgroup for node startup [skip ci]

- docs/leader_election.md
fix for https://github.com/lightningnetwork/lnd/issues/5908
> docs: update leader election docs [skip ci]

- docs/release-notes/release-notes-0.14.0.md
- invoices/invoice_expiry_watcher.go
fixes https://github.com/lightningnetwork/lnd/issues/5911
> invoices: do not log when invoice is already deleted

- mobile/README.md
Fixes https://github.com/lightningnetwork/lnd/issues/5812
> Added instructions on how to build proto definitions for Swift

- docs/release-notes/release-notes-0.14.0.md
- lntest/harness.go
- lntest/itest/lnd_onchain_test.go
- lntest/itest/lnd_rest_api_test.go
Fixes two flakes.
Fixes https://github.com/lightningnetwork/lnd/issues/5920
> itest: fix two flakes

- chainreg/chainregistry.go
- config.go
- config_builder.go
- docs/release-notes/release-notes-0.14.0.md
- kvdb/kvdb_no_postgres.go
- kvdb/kvdb_postgres.go
- kvdb/postgres/db.go
- kvdb/postgres/db_test.go
- kvdb/postgres/driver.go
- kvdb/postgres/fixture.go
- kvdb/postgres/readwrite_bucket.go
- kvdb/postgres/readwrite_cursor.go
- kvdb/postgres/readwrite_tx.go
- kvdb/postgres_test.go
- lnd.go
- macaroons/service.go
Fixes https://github.com/lightningnetwork/lnd/issues/5936.
Fixes https://github.com/lightningnetwork/lnd/issues/5927.
> Fix logging issues, cleanup config parsing

- docs/release-notes/release-notes-0.14.0.md
- go.mod
- go.sum
See this PR for context: https://github.com/btcsuite/btcwallet/pull/778
Fixes https://github.com/lightningnetwork/lnd/issues/5962
Fixes https://github.com/lightningnetwork/lnd/issues/5960 
Fixes https://github.com/lightningnetwork/lnd/issues/5517
Fixes https://github.com/lightningnetwork/lnd/issues/5844
> build: update to new btcwallet version w/ pruned node fix

- docs/release-notes/release-notes-0.14.1.md
- kvdb/bolt_compact.go
> kvdb/bolt_compact: have log message take account space multiplier

- htlcswitch/link_test.go
> htlcswitch: fix hint in link tests [skip ci]

- docs/release-notes/release-notes-0.14.2.md
- go.mod
- kvdb/etcd/config.go
- kvdb/etcd/db.go
- lncfg/db.go
- sample-lnd.conf
Fixes: https://github.com/lightningnetwork/lnd/issues/6045
> etcd: make max message size configurable

- docs/release-notes/release-notes-0.14.2.md
- lntest/bitcoind_common.go
Allows these values to be accessed upstream
> lntest: export attributes of type BitcoindBackendConfig

- docs/release-notes/release-notes-0.14.2.md
- go.mod
- kvdb/postgres/fixture.go
- kvdb/postgres/readwrite_bucket.go
- kvdb/postgres/readwrite_cursor.go
- kvdb/postgres/readwrite_tx.go
> kvdb/postgres: fix context cancellation

- lntest/bitcoind_common.go
- lntest/btcd.go
- lntest/harness_node.go
- lntest/neutrino.go
Reverts and replaces https://github.com/lightningnetwork/lnd/pull/6050, as the values were not accessible if the type was the `BackendConfig` interface
> Export backend credentials

- .golangci.yml
- channeldb/channel.go
- channeldb/graph.go
- channeldb/payments.go
- config.go
- contrib/init/lnd.service
- docs/DOCKER.md
- docs/INSTALL.md
- docs/code_contribution_guidelines.md
- docs/grpc/java.md
- docs/grpc/javascript.md
- docs/postgres.md
- docs/recovery.md
- docs/release-notes/release-notes-0.15.0.md
- lntest/harness_net.go
- lntest/harness_node.go
- lntest/itest/assertions.go
- lnwire/writer.go
Replaces https://github.com/lightningnetwork/lnd/pull/5578.
Replaces https://github.com/lightningnetwork/lnd/pull/5653.
Replaces https://github.com/lightningnetwork/lnd/pull/5942.
Replaces https://github.com/lightningnetwork/lnd/pull/5947.
Replaces https://github.com/lightningnetwork/lnd/pull/6051.
Replaces https://github.com/lightningnetwork/lnd/pull/5747.
Replaces https://github.com/lightningnetwork/lnd/pull/5848.
Replaces https://github.com/lightningnetwork/lnd/pull/2621.
Replaces https://github.com/lightningnetwork/lnd/pull/5094.
Replaces https://github.com/lightningnetwork/lnd/pull/5606.
> multi: consolidate trivial PRs that are stuck on CI pipeline steps

- .github/workflows/docker.yml
- docs/release-notes/release-notes-0.15.0.md
Fixes https://github.com/lightningnetwork/lnd/issues/6157.
> github: add schedule for nightly docker build

- .gitignore
- docs/release-notes/release-notes-0.15.0.md
Update .gitignore to ignore .vs/ folder
> Ignore .vs/ folder

- mobile/README.md
Added missing single quote
Removed extra backticks
> docs: fixed typos in mobile readme

- docs/code_contribution_guidelines.md
> Tiny Formatting Change

- Dockerfile
- docs/DOCKER.md
- docs/release-notes/release-notes-0.15.0.md
Allows overriding source repository for docker images
> docker: add git_url build-arg

- docs/release-notes/release-notes-0.15.0.md
- invoices/invoiceregistry.go
Attempts to fix: https://github.com/lightningnetwork/lnd/issues/6331
> invoices: fix deadlock in invoice registry

- docs/INSTALL.md
Change docs on the default configuration of macaroon.
https://github.com/lightningnetwork/lnd/issues/5444
> correct misinformation on default macaroon setup

- contractcourt/channel_arbitrator.go
found some typos while trying to debug an issue
> fix some typos

- docs/release-notes/release-notes-0.15.0.md
- go.mod
- go.sum
Fixes: https://github.com/lightningnetwork/lnd/issues/6372
> build: update to latest btcutil/psbt version

- docs/postgres.md
https://github.com/lightningnetwork/lnd/issues/6395
> Warn about selecting synchronous replication mode

- docs/release-notes/release-notes-0.15.0.md
- lnrpc/chainrpc/chainnotifier.proto
- lnrpc/chainrpc/chainnotifier.swagger.json
- lnrpc/chainrpc/chainnotifier_grpc.pb.go
Closes #6443.
Clarify the comment on RegisterConfirmationsNtfn. The output script
is in fact mandatory, not optional.
N/A
> chainrpc: clarify documentation

- docs/release-notes/release-notes-0.15.0.md
- input/musig2.go
- input/test_utils.go
- lnrpc/signrpc/signer.pb.go
- lnrpc/signrpc/signer.pb.gw.go
- lnrpc/signrpc/signer.pb.json.go
- lnrpc/signrpc/signer.proto
- lnrpc/signrpc/signer.swagger.json
- lnrpc/signrpc/signer.yaml
- lnrpc/signrpc/signer_grpc.pb.go
- lnrpc/signrpc/signer_server.go
- lntest/itest/lnd_taproot_test.go
- lntest/mock/signer.go
- lnwallet/btcwallet/signer.go
- lnwallet/rpcwallet/rpcwallet.go
- watchtower/wtmock/signer.go
Fixes https://github.com/lightningnetwork/lnd/issues/6494 by adding a `MuSig2Cleanup` RPC.
> MuSig2: Add session cleanup RPC

- cmd/lncli/cmd_invoice.go
- docs/release-notes/release-notes-0.15.0.md
> cmd/lncli: make hop hint inclusion opt-in for addinvoice

- lnrpc/invoicesrpc/invoices.swagger.json
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
> lnrpc: improves invoice documentation

- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
> lnrpc: fix comment and formatting in ConnectPeerRequest [skip ci]

- cmd/lncli/invoicesrpc_active.go
- docs/release-notes/release-notes-0.15.0.md
Relates to  #6523 and changes it also for `lncli addholdinvoice`
> Hop hints opt in addholdinvoice

- docs/release-notes/release-notes-0.15.1.md
- lntest/itest/lnd_psbt_test.go
- lnwallet/btcwallet/psbt.go
- lnwallet/btcwallet/psbt_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/6626.
> walletrpc: Fix SignPsbt for NP2WKH inputs

- cmd/lncli/peersrpc_active.go
- lnrpc/peersrpc/peers.proto
Fixed typo newtwork -> network
N/A
N/A
N/A
> Fixed typo

- docs/watchtower.md
- watchtower/wtwire/state_update.go
fix document / comment typo
N/A
N/A
N/A
> docs: fix typo in watchtower document and code comment

- docs/psbt.md
> doc: update psbt.md

- build/version.go
- docs/release-notes/release-notes-0.15.2.md
- go.mod
- go.sum
This PR branches directly off of 0.15.1.
> release: create v0.15.2 hot fix branch to fix wire parsing issue

- docs/release-notes/release-notes-0.16.0.md
- funding/manager.go
Simplifies and deduplicates the code.
> funding: create waitForPeerOnline helper

- lnd.go
> fixes adming typo

- build/version.go
- docs/release-notes/release-notes-0.15.4.md
- funding/manager.go
- go.mod
- go.sum
Fixes https://github.com/lightningnetwork/lnd/issues/7096.
> mod+build: bump btcd version to v0.23.3 and bump lnd version to v0.15.4-beta

- .gitignore
- Makefile
- build/dependencies.go
- docs/fuzz.md
- docs/release-notes/release-notes-0.16.0.md
- go.mod
- go.sum
- make/fuzz_flags.mk
- scripts/fuzz.sh
- tools/go.mod
- tools/go.sum
- tools/tools.go
This is https://github.com/lightningnetwork/lnd/pull/6862 rebased, with some minor build issues fixed and the go-fuzz dependency completely removed.
> make+scripts+docs: update fuzzing script and make fuzz

- cmd/lncli/cmd_invoice.go
- cmd/lncli/invoicesrpc_active.go
- lnrpc/invoicesrpc/addinvoice.go
- lnrpc/routerrpc/router_backend.go
- rpcserver.go
Revise help text for addinvoice lncli command
> revise help text for addinvoice lncli command

- dev.Dockerfile
> docker: correct comment concerning lnd build/install

- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
> proto: fix typo [skip ci]

- docs/release-notes/release-notes-0.16.0.md
- tools/go.mod
- tools/go.sum
This change updates the test coverage tool go-acc to its latest release version.
> CI: update test coverage library go-acc

- sample-lnd.conf
> docs: Fix lnd.conf typo

- cmd/lncli/cmd_invoice.go
- cmd/lncli/invoicesrpc_active.go
- docs/release-notes/release-notes-0.16.0.md
- lnrpc/invoicesrpc/invoices.pb.go
- lnrpc/invoicesrpc/invoices.proto
- lnrpc/invoicesrpc/invoices.swagger.json
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
https://github.com/lightningnetwork/lnd/issues/7278
N/A
~~- [ ] Your PR passes all CI checks.~~
~~- [ ] Tests covering the positive and negative (error paths) are included.~~
~~- [ ] Bug fixes contain tests triggering the bug to prevent regressions.~~
~~- [ ] Any new logging statements use an appropriate subsystem and logging level.~~
> Docs invoice default expiry

- cert/selfsigned.go
This pull request fixes two typos in the `selfsigned.go` file.
I don't think any testing is required since this pull request only changes typos in comments.
> Fix typos in selfsigned.go

- .golangci.yml
- channeldb/invoices.go
- cmd/lncli/cmd_payments.go
- docs/release-notes/release-notes-0.16.0.md
- invoices/test_utils.go
- watchtower/wtdb/migration4/client_db.go
- watchtower/wtdb/migration4/range_index.go
- watchtower/wtdb/range_index.go
Fix the annoying "magic number" linter.
> lint: disable gomnd

- cmd/lncli/peersrpc_active.go
- docs/release-notes/release-notes-0.16.0.md
Splitting this bugfix out from #7168. 
> bugfix/trivial: fix update node announcement feature bit add /remove

- .github/workflows/main.yml
- .github/workflows/release.yaml
- .travis.yml
- Dockerfile
- dev.Dockerfile
- docs/INSTALL.md
- go.mod
- make/builder.Dockerfile
Fixes https://github.com/lightningnetwork/lnd/issues/7495
> build: bump min Go version to 1.19

- build/version.go
- config_builder.go
- lnutils/chan.go
- lnwallet/mock.go
- lnwallet/rebroadcaster_test.go
- lnwallet/wallet.go
Fix all the linter problems for the `v0.16.0-beta.rc3`.
> multi: make linter happy

- build/version.go
Diff from the last rc: https://github.com/lightningnetwork/lnd/compare/v0.16.0-beta.rc2...Roasbeef:lnd:v0-16-0-branch-rc3?expand=1
> build: bump version to v0.16.0-rc3

- discovery/gossiper.go
- discovery/message_store.go
- htlcswitch/link.go
- peer/brontide.go
This PR adds more trace logs to aid debugging.
> multi: add more trace logs regarding link activate flow

- docs/remote-signing.md
With this commit we update the docs according to the latest changes that were necessary to support loop and pool (which requires all 255 internally used accounts to be imported at wallet creation time).
Fixes #7567.
> docs: update remote signing docs

- contractcourt/channel_arbitrator.go
- contractcourt/htlc_timeout_resolver.go
Previously when a block spend is found for the outpoint, our htlc
timeout resolver will do a checkpoint, which implicitly creates a db
record if there isn't one. Now, if the spend is found in mempool,
the resolver will be deleted once the contract is resolved. Later on,
when the spend is found in the block again, the resolver will be created
again, but never gets resolved this time.
> contractcourt: skip checkpoint htlc outgoing resolver if it's resolved

- build/version.go
- contractcourt/channel_arbitrator.go
- contractcourt/htlc_timeout_resolver.go
- docs/release-notes/release-notes-0.16.2.md
- go.mod
- go.sum
- sweeper_wallet.go
Includes the following hot fix PRs: 
* https://github.com/lightningnetwork/lnd/pull/7641
* https://github.com/lightningnetwork/lnd/pull/7637
* https://github.com/lightningnetwork/lnd/pull/7647
> release: create v0.16.2 branch

- docker/btcd/Dockerfile
- docker/ltcd/Dockerfile
- lnrpc/Dockerfile
- lnrpc/gen_protos_docker.sh
> Update docker images

- docs/release-notes/release-notes-0.16.3.md
- go.mod
- go.sum
- itest/lnd_mpp_test.go
- itest/lnd_multi-hop_test.go
- itest/lnd_switch_test.go
- lntest/harness.go
Update btcwallet's version to include an optimized mempool lookup.
Fixes #7675
> mod: update btcwallet's version

- contractcourt/chain_arbitrator.go
When we create a temporary `chanPoint` variable to shorten up the code, we should use it everywhere for consistency and clarity.
Just a drive-by nit.
> contractcourt: fully use chanPoint variable

- lnd.go
Looks like it's causing too many redirects error for some machines.
> lnd: fix pprof server redirects

- docs/release-notes/release-notes-0.17.0.md
- go.mod
- go.sum
Depends on https://github.com/btcsuite/btcwallet/pull/872
Fixes mempool memory leak.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/7767)
> Fix mempool memory usage

- peer/brontide.go
The two methods were nearly identical, so we can simplify by combining them.
> peer: combine handleWarning and handleError

- .github/workflows/main.yml
- Makefile
- docs/MAKEFILE.md
- docs/release-notes/release-notes-0.17.0.md
- sample-lnd.conf
- scripts/check-sample-lnd-conf.sh
This PR fixes #7612 . A new validation script was added and included in the makefile. Also sample-lnd.conf was revised 
The script performs different checks on the sample-lnd.conf file:
1. Checks that all relevant options of lnd are included
2. Verifies that defaults are labeled if there are also further examples
3. Checks that all default values of lnd are mentioned correctly, including empty defaults and booleans which are set to false by default.
sample-lnd.conf was revised as well, to distinguesh between defaults and examples.
There seems to be some default values which are not included in `lnd --help` (see #7769). Such values are now marked as example value in sample-lnd.conf
make sample-conf-check
📝 Please see our  [Contribution …
> Revision of default values in sample-lnd.conf and building of a check script

- scripts/check-sample-lnd-conf.sh
We are directing the output of 'lnd --help' to a file, as there is currently an issue when an option is mentioned in the help text.
Fixes the problem which occured in #7867 
Tested the following cases on the current master and on the removeLitecoin branch:
```
#login case
make sample-conf-check
#nologin case
stty cols 80
echo | scripts/check-sample-lnd-conf.sh "autopilotrpc signrpc walletrpc chainrpc invoicesrpc watchtowerrpc neutrinorpc monitoring peersrpc kvdb_postgres kvdb_etcd kvdb_sqlite"
```
> scripts: Direct 'lnd --help' output to a file

- build/version.go
Changes since rc1: https://github.com/lightningnetwork/lnd/compare/v0.17.0-beta.rc1...Roasbeef:lnd:v0-17-0-branch-rc2?expand=1
> build: bump version to v0.17.0-rc2

- build/version.go
Changes since rc4: https://github.com/lightningnetwork/lnd/compare/v0.17.0-beta.rc4...Roasbeef:lnd:0-17-rc5
> build: bump version to v0.17.0 rc5

- build/version.go
Changes since `rc5`: https://github.com/lightningnetwork/lnd/compare/v0.17.0-beta.rc5...Roasbeef:lnd:0-17-rc6
> build: bump version to v0.17.0 rc6

- cmd/lncli/commands.go
Fix description of `lncli connect` & `lncli disconnect`
`lncli connect --help` & `lncli disconnect --help`
> lncli: fix description of connect/disconnect peer

- docs/grpc/python.md
Use mypy to generate .pyi files as well. These files are useful for type hinting in IDEs.
Run commands as listed in guide.
> Add instructions to generate type hints

- scripts/install_bitcoind.sh
> CI: upgrade bitcoind version to 0.25

- .github/workflows/main.yml
- build/version.go
- cmd/lncli/commands.go
- go.mod
- go.sum
Just includes a dep update so far.
> release: create v0.17.1 rc2 release branch

- build/version.go
- channeldb/channel.go
- docs/release-notes/release-notes-0.17.3.md
- go.mod
- go.sum
- htlcswitch/link.go
- input/musig2_session_manager.go
- lntest/harness.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- peer/brontide.go
- routing/router.go
This release branch includes the following PRs from the `v0.17.3` milestone: 
* https://github.com/lightningnetwork/lnd/milestone/48?closed=1
> release: create v0.17.3-beta.rc1 release branch 

- docs/code_contribution_guidelines.md
There are some typos in the document and use this PR to correct them.
> fix: rectify the typos in the docs

- channeldb/invoices.go
- feature/deps.go
- input/taproot_test.go
- invoices/interface.go
- peer/brontide.go
- rpcserver.go
> docs: fix typos

- sqldb/interfaces.go
There is typo in the comment and need to correct them. No need to run CI so [skip ci]
> fix: correct the typo [skip ci]

- cmd/lncli/cmd_macaroon.go
- cmd/lncli/peersrpc_active.go
- cmd/lncli/walletrpc_active.go
- kvdb/config.go
- kvdb/etcd/commit_queue.go
- kvdb/etcd/readwrite_tx.go
- kvdb/readwrite_bucket_test.go
- lntest/harness.go
- lntest/harness_node_manager.go
- sweep/sweeper_test.go
- sweep/txgenerator.go
> chore: fix typos [skip ci]

- docs/grpc/javascript.md
Fixes #8333 by not using the outdated `bytebuffer` library anymore.
> docs: update Node.JS example

- cmd/lncli/commands.go
Fix for the issue : https://github.com/lightningnetwork/lnd/issues/7946
> Wrong documentation on lncli

- lntest/harness.go
Add the ability to create a test harness with nodes in a remote signing configuration. At the moment this change makes the remote signing setup available to users of the `lntest` library via the exported `SetupRemoteSigningStandbyNodes` test harness method. We could consider updating code [here](https://github.com/lightningnetwork/lnd/blob/v0.17.3-beta/itest/lnd_test.go#L104) to allow for either the default or remote signing configuration to be used within the `lnd` itests.
- make itest
> lntest: standby test nodes in remote signing configuration

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/interface.go
- chainntnfs/neutrinonotify/neutrino.go
- lnwallet/test/test_interface.go
- routing/chainview/bitcoind.go
- routing/chainview/btcd.go
- routing/chainview/neutrino.go
- routing/notifications_test.go
- routing/router.go
- watchtower/lookout/lookout.go
Deep copy any transaction we obtain from the `GetBlock` call.
Closes 2nd task in #5075
> routing: deep copy any transaction we obtain from `GetBlock` call.

- docs/release-notes/release-notes-0.18.0.md
- internal/musig2v040/context.go
- internal/musig2v040/musig2_test.go
> fix: typos [skip ci]

- fn/conc_queue.go
- fn/either.go
- fn/events.go
- fn/func.go
- fn/go.mod
- fn/go.sum
- fn/option.go
- fn/queue.go
- fn/recv.go
- fn/send.go
- fn/set.go
Adds some new stuff used in an upcoming PR to the `fn` package. Done in a distinct PR as we'll need to tag a module version before it can be used. 
This builds off https://github.com/lightningnetwork/lnd/pull/8334 as they're part of a series.
> fn: add some new goodies to sub-module to be used in future PRs

- config.go
docs: mention that `--lnddir` option overwrites all other directory options [skip ci]
Closes #8408
> docs: mention that `--lnddir` option overwrites all other directory options [skip ci]

- batch/interface.go
- cert/tls.go
- cluster/etcd_elector.go
- htlcswitch/switch.go
- invoices/invoice_expiry_watcher.go
- kvdb/etcd/stm.go
- lnrpc/signrpc/signer.pb.go
- lnrpc/signrpc/signer.proto
- lnrpc/signrpc/signer.swagger.json
- lnwallet/chainfee/rates.go
- lnwallet/chanfunding/coin_select.go
- queue/priority_queue.go
- sample-lnd.conf
- sweep/sweeper.go
- watchtower/wtserver/server.go
> chore: remove repetitive words

- itest/lnd_watchtower_test.go
In the tower session itest, we make sure to mine blocks on session count assertion failure. This required because the session count is expected to change only when 2 things both happen: 1) a closable session is queued and 2) a new block notification comes through _after_ the session has been queued. Only then will it be deleted. So we need to do this to prevent the case where all the block notifications are consumed _before_ the session is queued for deletion. This flake tended to happen in the windows itest.
This same pattern has been used previously in other watchtower itests. 
An example of the flake failure can be seen [here](https://github.com/lightningnetwork/lnd/actions/runs/8333246594/job/22804251071?pr=8159)
> itest: mine blocks on tower session assertion failure

- aezeed/bench_test.go
- autopilot/agent_test.go
- pilot.go
- rpcserver.go
- server.go
> chore: fix function names in comment

- lnrpc/walletrpc/walletkit.pb.go
- lnrpc/walletrpc/walletkit.proto
- lnrpc/walletrpc/walletkit.swagger.json
- lnrpc/walletrpc/walletkit_grpc.pb.go
Fix typo in recently touched RPCs.
> lnrpc: fix typo

- sweep/fee_bumper.go
> sweep: make `TxPublisher.currentHeight` atomic

- cmd/lncli/cmd_payments.go
> cli: add `--amp` to `SendPaymentRequest` in `payinvoice`

- build/version.go
Changes since rc1:
* https://github.com/lightningnetwork/lnd/compare/v0.18.0-beta.rc1...master
> build: bump version to v0.18.0-beta.rc2

- fn/map.go
- fn/map_test.go
- fn/slice.go
- fn/slice_test.go
This adds new functions to the fn packages.
Changes include:
- A new file for map functions accompanied with a test file.
- Added new functions for slice accompanied with test.
This is required for this PR: https://github.com/lightningnetwork/lnd/pull/8516/
> Add new  functions to the fn package

- build/version.go
Changes since rc:
* https://github.com/lightningnetwork/lnd/compare/v0.18.0-beta.rc2...master
> build: bump verison to v0.18.0-beta.rc3

- build/version.go
Changes since `rc2`: 
* https://github.com/lightningnetwork/lnd/compare/v0.18.0-beta.rc3...master
> build: bump version to v0.18.0-beta.rc4

- funding/manager.go
- lnwallet/wallet.go
> chore: fix some comments

- lnwallet/chancloser/chancloser.go
- rpcserver.go
Fixes two bugs found during testing of co-op closing custom channels.
> [custom channels]: co-op closing bugfix

- .github/workflows/main.yml
- chainntnfs/bitcoindnotify/bitcoind_test.go
- itest/lnd_route_blinding_test.go
- lntest/wait/timeouts.go
- lntest/wait/timeouts_darwin.go
- lntest/wait/timeouts_remote_db.go
A temp fix for the itest to unblock other PRs.
> lntest: increase timeout for postgres backend

- itest/lnd_channel_force_close_test.go
Provide a mitigation over the following failed CI:
```
harness_miner.go:217: 
Error Trace:    /home/runner/work/lnd/lnd/lntest/harness_miner.go:217
/home/runner/work/lnd/lnd/itest/lnd_channel_force_close_test.go:700
/home/runner/work/lnd/lnd/itest/lnd_channel_force_close_test.go:84
Error:          Received unexpected error:
want 1, got 2 in mempool: [92760fe5fed94d38f51b4a505f060364beb3c30f1e0a755683412e42faa008bf d494d352da6ae6c557ad329a81ba369cc59cfbc7ed0af66276bf13357faf2958]
Test:           TestLightningNetworkDaemon/tranche05/53-of-156/neutrino/channel_force_closure/committype=SIMPLE_TAPROOT
Messages:       assert tx in mempool timeout
harness.go:438: finished test: channel_force_closure, start height=617, end height=713, mined blocks=96
```
A proper fix is being worked on (the …
> itest: provide a temporary fix to unblock CI

- cmd/lncli/commands.go
> lncli: fix typo in inbound fee help text

- fn/result.go
`NewResult` makes it easy to wrap a normal function call in a result value.
`Err` can be used to check the error case of the result without unpacking the entire thing.
`AndThen2` allows a caller to compose a function on two results values, with the closure only executing if both values are non-error.
> fn: add additional utility methods for Result[T]

- routing/bandwidth.go
This PR updates the traffic shaper's bandwidth query method to accept the link bandwidth as a parameter. This allows an external
traffic shaper to optionally return the link bandwidth as the payment bandwidth.
> routing: pass link bandwidth to traffic shaper's bandwidth query

- brontide/noise_test.go
- chainntnfs/txnotifier_test.go
> chore: fix some function names

- docs/safety.md
Replaces https://github.com/lightningnetwork/lnd/pull/8724, commit author preserved.
Remove dead conjoin implementations.
> docs: update safety.md, remove specific CoinJoin implementations

- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/test_utils.go
Spun off from #8270 [comment](https://github.com/lightningnetwork/lnd/pull/8270#issuecomment-2260439007)
Just read the diff.
> [NANO]: Refactor/quiescence micro spinoffs

- routing/router_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/8964
> routing: fix race in TestNewRouteRequest

- lnwire/fuzz_test.go
- lnwire/lnwire_test.go
- lnwire/message.go
- lnwire/stfu.go
- peer/brontide.go
This is a spinoff of #8270. There are still some design questions in flux with the rest of the PR but this part is stable, uncontroversial, and non-invasive.
make unit pkg=lnwire
> [MICRO]: add wire messages for quiescence

- lnwallet/update_log.go
It's ugly to look at `map[T]struct{}` to indicate what is fundamentally a Set. A while back we created the type in fn and so we use it here.
make unit pkg=lnwallet
> [NANO]: lnwallet: update updateLog.modifiedHtlcs to use fn.Set

- lnwallet/channel.go
- lnwallet/channel_test.go
gopls informed me that these parameters are not used and when I remove them, they are indeed not necessary.
make unit pkg=lnwallet
> [NANO]: Remove useless appendages from lnwallet/channel.go

- docs/release-notes/release-notes-0.18.3.md
- itest/list_on_test.go
- itest/lnd_route_blinding_test.go
- lnwallet/channel.go
re-opening https://github.com/lightningnetwork/lnd/pull/9023 but pointing at master branch
> lnwallet: correctly set UpdateAddHTLC.BlindingPoint on reload from disk

- itest/lnd_route_blinding_test.go
Reported in:
https://github.com/lightningnetwork/lnd/actions/runs/10587596457/job/29338618874?pr=9036
Relevant logs revealed that nodes where not properly connected that why the payment failed:
from the log of Carol which after restart should forward the intercepted payment:
Carol log:
```
024-08-28 01:34:47.899 [ERR] HSWC: link not eligible
2024-08-28 01:34:47.899 [ERR] HSWC: Unhandled error while reforwarding htlc settle/fail over htlcswitch: link not eligible
2024-08-28 01:34:47.899 [DBG] HSWC: ChannelLink(61d353d2554148cb0c05c5830571a8f77c07b31324c9bd73c02f9e8404a725f3:0): queueing removal of FAIL closed circuit: (Chan ID=1274:1:0, HTLC ID=0)->(Chan ID=1281:1:0, HTLC ID=0)
```
Alice does not succeed the payment thats why the testcase fails:
```
2024-08-28 01:34:48.092 [WRN] CRTR: …
```
> fix blinded path itest.

- lnwallet/chanfunding/coin_select.go
Remove unsupported directive: `level=warning msg="[runner/nolint] Found unknown linters in //nolint directives: ifelsechain"`
> chanfunding: remove unsupported linter directive.

- htlcswitch/mailbox_test.go
fix incorrect parameters in test cases
`recvdMessages` --> `sentMessages`
> bug: fix incorrect parameters in test cases

- fn/set.go
As discussed adding those methods.
> fn: Add Size and IsEmpty methods to Set

- cmd/commands/commands.go
This PR fixes the display of the amount when
selecting utxos for the sendcoins command and
combining it with the `-sweepall` flag. Prior this would show the full balance of the wallet. Now it
shows the total amount of the selected utxos.
Tested with a local lnd regtest env.
Closes #9225
> cmd/sendcoins: fix display amount if select utxo and sweepall is set

- lnrpc/routerrpc/router.pb.go
- lnrpc/routerrpc/router.proto
- lnrpc/routerrpc/router.swagger.json
> routerrpc/trivial: add docs to forward interceptor

- fn/go.mod
NOTE: This is simply a copying of the existing fn source files which were already updated to a v2 API in a previous commit. In order to actually ingest these changes we need them to be in a v2 folder.
> fn: update go.mod to v2

- fn/set.go
Needed for https://github.com/lightningnetwork/lnd/pull/9241
> fn: add set copy method Copy

- .github/actions/setup-go/action.yml
- .github/workflows/main.yml
- .github/workflows/release.yaml
> .github: update actions versions

- docs/release-notes/release-notes-0.20.0.md
Just creating release-notes-0.20.0.md
> doc: creating release-notes-0.20.0.md

- go.mod
- go.sum
~Testing https://github.com/btcsuite/btcwallet/pull/979~
~See commit tree https://github.com/JoeGruffins/btcwallet/commits/v0.16.10/~
Fixes the issue stated here https://github.com/btcsuite/btcwallet/issues/978
> deps: Update btcwallet to v0.16.10.

- cmd/commands/commands.go
Fixes a bug introduced by #9605, fixes #9648.
We need to use the "Unimplemented" code to detect whether the wallet is already unlocked. Otherwise we'll always get the wrong error message. But because the Unimplemented code can also occur if there is a mismatch between the build tags used for lncli and lnd, we also need to include that possibility in the erorr message to make sure the user can fix the problem.
> cmd: fix incorrect error code

- README.md
- docs/code_contribution_guidelines.md
- docs/review.md
We want to encourage new contributors to review code instead of creating their own PRs as a first contribution.
> README+docs: add code review checklist

- invoices/sql_migration.go
Fixes: https://github.com/lightningnetwork/lnd/issues/9661
> invoices: reduce log spam when migrating invoices to SQL

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/neutrinonotify/neutrino.go
Follow the same schema as for other subsystems.
> chainntnfs: increase logging of the subsystems

- chainntnfs/btcdnotify/btcd.go
Observed this flake in:
https://github.com/lightningnetwork/lnd/actions/runs/14362611877/job/40267746145
Basically we fetched the latest blockheight, but when the block notifiers were registered the block height had already changed.
That's why the blockdispatcher got stuck:
```
2025-04-09 16:50:37.084 [INF] CHIO dispatcher.go:117: BlockbeatDispatcher is starting with 1 consumer queues
2025-04-09 16:50:37.085 [INF] NTFN btcd.go:398: New block epoch subscription
2025-04-09 16:50:37.085 [DBG] CHIO dispatcher.go:124: BlockbeatDispatcher started
2025-04-09 16:50:37.085 [DBG] CHIO dispatcher.go:163: ================================================================================
2025-04-09 16:50:37.085 [DBG] CHIO dispatcher.go:165: Received new block …
```
> Change RPC call order for the btcd notifier

- channeldb/invoices.go
- channeldb/payment_control.go
- channeldb/payments.go
- cmd/commands/cmd_payments.go
- invoices/invoiceregistry.go
- invoices/sql_store.go
- routing/control_tower.go
- routing/router.go
- **lncli: return more clear error msg for deletepayments**
- **multi: add more logging when fetching invoices and payments.**
> Improve logging when fetching invoices and payments

- docs/release-notes/release-notes-0.19.0.md
Fixes #9768 
Release notes for 0.19 updated to provide details regarding RBF coop close changes
> docs: update release notes with more detail on the RBF coop close section

- channeldb/migration/lnwire21/msat.go
- go.mod
- go.sum
- lnwire/msat.go
update tlv package to make use of changes in https://github.com/lightningnetwork/lnd/pull/9793
> multi: use updated TLV SizeFunc signature

- graph/db/addr_test.go
- graph/db/graph_test.go
This PR contains the last few preparation commits of the graph/db tests that we need before things can smoothly be
run against a new SQLStore DB backend. 
This is the final preparation step of https://github.com/lightningnetwork/lnd/issues/9795
> graph/db: final test preparation before SQL impl

- channeldb/forwarding_log.go
This commit simplifies the code of the ForwardingLog.Query method by removing a confusing for-loop. The for-loop makes it seem as though multiple events could be encoded under a single timestamp. But from the time that this forwarding log was introduced, it was never possible to encode multiple events under the same timestamp and so this loop will never execute successfully more than once per timestamp and can thus be removed. This paves the way such that future expansions of the method can be added easily.
See the initial commit that introduced this code [here](https://github.com/lightningnetwork/lnd/commit/f2cd668bcfb423fb212e78282c786dea166e0168). In this commit you can see that from the start it was never possible to have more than one event in a single timestamp since any previous …
> channeldb: remove unnecessary for loop from Query method

- go.mod
- go.sum
- routing/blindedpath/blinded_path.go
Make sure we use the latest version of the Sphinx Package.
> multi: update sphinx lib to latest version

- graph/db/kv_store.go
Fix the panic found in multiple CI builds, eg, [here](https://github.com/lightningnetwork/lnd/actions/runs/15646479060/job/44084812653), and [here](https://github.com/lightningnetwork/lnd/actions/runs/15653042335/job/44100329085?pr=9815), turns out there's a panic, tho only happens in windows build,
```
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x19ac7f3]
goroutine 267 [running]:
github.com/lightningnetwork/lnd/graph/db/models.NewCachedPolicy(...)
C:/a/lnd/lnd/graph/db/models/cached_edge_policy.go:93
github.com/lightningnetwork/lnd/graph/db.(*KVStore).ForEachChannelCacheable.func1.1({0xc001824150?, 0xb6f5ba?, 0x29e7b4f7219?}, {0xc001824158, 0xe0, 0xe0})
C:/a/lnd/lnd/graph/db/kv_store.go:517 +0x3b …
```
> graph: fix nil pointer deference in `ForEachChannelCacheable`

- lncfg/db.go
- sample-lnd.conf
fixes https://github.com/lightningnetwork/lnd/issues/9675
> sqldb: clarify native sql options in `lnd.conf`

- .gemini/config.yaml
So far, most of the AI code review tools I've seen in the wild have been pretty lackluster. I figure we should give the new Gemini Code Assist variant a try: https://github.com/marketplace/gemini-code-assist/.
> CI: add config.yaml for gemini code review

- htlcswitch/switch.go
- routing/bandwidth.go
- routing/pathfind.go
- routing/unified_edges.go
Will allow to find out what the problem is in https://github.com/lightningnetwork/lnd/issues/10039
> routing: add logs to debug potential payment sending issue
