- batch/interface.go
- batch/scheduler.go
- channeldb/graph.go
- discovery/gossiper.go
- discovery/gossiper_test.go
- routing/router.go
Since the batch interval can potentially be long, adding local updates
to the graph could be slow. This would slow down operations like adding
our own channel update and announcements during the funding process, and
updating edge policies for local channels.
Now we instead check whether the update is remote or not, and use the
SchedulerOption to immediately add local updates to the graph.
Companion PR to #4958
> channeldb+routing+gossiper: add local updates to graph immediately

- lncfg/address.go
> lncfg: add IPv6 resolution bypass & account for local hostname aliases 

- lncfg/address.go
With this commit, if `--tor.active` is specified, then IPv6 addresses will no longer go through the `connmgr.TorLookupIP` function from btcd.  This function does not have proper IPv6 support and would fail with the error "tor general error".  Instead, use the system resolver.
Fixes #2541
> lncfg: add isIPv6Host helper to force v6 addrs through system resolver

- discovery/gossiper.go
- discovery/gossiper_test.go
- server.go
Fixes https://github.com/lightningnetwork/lnd/issues/4690
> [gossiper] Ignore received ChannelAnnouncements for own channels

- .github/workflows/main.yml
- .github/workflows/release.yaml
Modifies the test/release script to pin to the _exact_ `GO_VERSION` specified in our environment variables. Currently the `setup-go` action was passed `~GO_VERSION` allowing actions to bump the version as new versions of go are released.
This caused an issue during v0.12.1-beta.rc2 release cycle where the release binaries were built with go1.15.8, which had been released earlier this week, rather than go1.15.7 which is pinned in our release/verify docker containers. As a result, building the release locally did not match the binaries uploaded by github to the release.
> github/workflows: pin exact docker release

- config.go
Fixes https://github.com/lightningnetwork/lnd/issues/5011.
Because the CleanAndExpandPath function wasn't applied to the backup
file path, any path that contained a tilde for the home directory didn't
work.
> config: clean and expand backup file path

- .github/workflows/release.yaml
- docs/release.md
- scripts/release.sh
- scripts/verify-install.sh
Fixes https://github.com/lightningnetwork/lnd/issues/4966.
This PR updates the verification script to now look for detached signatures instead of clear signed ones.
Can be tested on `v0.12.1-beta.rc3`, I've uploaded a detached signature.
Also fixes an issue with the `sha256sum` command not being available on MacOS.
> release: create and verify detached signatures, fix hashing command on MacOS

- scripts/verify-install.sh
This is a precaution is done to protect against rogue/accidental behavior of any one of the seven signers,
due to the fact that only one valid signatures is currently required in order for `scripts/verify_install.sh` to
accept a binary.
There are two cases where this is relevant:
- When only one signature is required, the first signer is able to upload/replace the manifest by themselves
and cause the initial set of installs to accept a potentially malicious binary. Normally this would be rectified
after one other signer has added their signatures, which sign the _correct_ manifest as it will fail the
verification script due to signature disagreements.
- When only one signatures is required, another signer may remove the signatures after the initial release
is published on the valid …
> scripts/verify-install: require 5 of 7 signatures before accepting

- lntest/itest/log_error_whitelist.txt
Fixes two itests flakes by adding now-common logs to the whitelist.
> lntest: update error log whitelist

- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/test_utils.go
If the tests don't execute quick enough, the link will try to sample the
network fee and cause a panic. This happens semi-regularly on travis.
> htlcswitch: init mockFeeEstimator in other LinkChannelConfigs

- Makefile
- scripts/verify-install.sh
To fix an issue where the golang version would be picked up from the
host system if the docker-release command was used, we switch over to
using make inside of the container as well instead of feeding the
parameters into the release script manually.
We only pass in the flags that we might actually want to overwrite.
Additionally, the shasum command isn't available in Alpine linux while the sha256sum
command isn't available on MacOS. We add a simple switch that tries to
detect which one is available.
> release: fix golang version issue in docker-release and shasum issue in verification script

- .github/workflows/main.yml
- Makefile
- build/version.go
- cmd/lncli/cmd_pay.go
- lnrpc/routerrpc/router_backend.go
- lntest/itest/lnd_multi-hop-error-propagation_test.go
- scripts/verify-install.sh
PRs included since v0.12.1-beta.rc4:
- #5037 
I've also included a commit to modify the base branch from `upstream/master` to `v0.12.0-beta`, to fix the issue noted in https://github.com/lightningnetwork/lnd/pull/5027#issuecomment-780154676.
The default `MaxParts` via RPC has been reverted from 16 back to 1, since this was reported to introduce a breaking change wrt to the failure message returned in v0.12.0-beta.
> v0.12.1-beta.rc5

- lntest/itest/log_error_whitelist.txt
Hit this on the itests when building v0.12.1-beta.rc6.
> lntest/itest: add websocket close to error whitelist

- routing/router.go
- routing/router_test.go
This commit reduces the number of concurrent validation operations the
router will perform when fully validating the channel graph. Reports
from several users indicate that GetInfo would hang for several minutes,
which is believed to be caused by attempting to validate massive amounts
of channels in parallel. This commit returns the limit back to its
original state before adding the batched gossip improvements.
We keep the 1000 concurrent validation request limit for
AssumeChannelValid, since we don't fetch blocks in that case. This
allows us to still keep the performance benefits on mobile/low-resource
devices.
Fixes #4892
> routing: dial back max concurrent block fetches

- Makefile
- make/testing_flags.mk
This PR adds a new `make unit-debug` target which runs the unit tests with `-v`. A while back, the go toolchain changed to not print stdout if `-v` was not set, which nerfed all the work we did in conditionally compiling production logging into our unit tests.
The work around I've been using is to run `make unit`, then copy the actual command being run and add a `-v`, which is very tedious. So instead, we just add a new target that includes this automatically.
Output when running the unit tests with production debug logs on master:
```
❯ make unit pkg=netann log="stdlog debug"
Installing btcd.
cd /tmp && GO111MODULE=on go get -v github.com/btcsuite/btcd@v0.21.0-beta.0.20201208033208-6bd4c64a54fa
Running unit tests.
GO111MODULE=on go test  -tags="dev stdlog debug"  -test.timeout=40m …
```
> make: add unit-debug target

- breacharbiter_test.go
- lnwallet/commitment.go
Noticed we could make the capacity check stricter in `lnwallet/commitment.go` by adding the `commitFee`. After doing this, noticed that the breacharbiter tests were failing.
> lnd+lnwallet: make capacity check stricter by adding fee

- build/version.go
In this commit we bump the version to v0.12.99-beta to reflect that the
master branch is a super set of the recently released v0.12.1-beta.
> build: bump version to v0.12.99-beta

- lnrpc/routerrpc/router.pb.go
- lnrpc/routerrpc/router.proto
- lnrpc/routerrpc/router.swagger.json
Update comment on PenaltyHalfLife, as identified [here](https://github.com/lightningnetwork/lnd/pull/4909#issuecomment-790926865).
> lnrpc: correct comment on half life seconds

- lnrpc/routerrpc/router_server.go
Use newline for map key to match other keys
logging level
per default)
already exist
> trivial: match newline style

- chanbackup/single.go
- channeldb/channel.go
- channeldb/channel_test.go
- chanrestore.go
- lntest/itest/lnd_channel_backup_test.go
- lnwallet/reservation.go
- lnwallet/revocation_producer.go
- lnwallet/revocation_producer_itest.go
- lnwallet/wallet.go
Closes #2659
Related #3929 
By adding the `RevocationKeyLocator` in the same PR, we get away with not adding a version to SCB as we know that if an `OpenChannel` has a populated `RevocationKeyLocator`, they are using `ECDH` derivation for the sha chain root key.
The question then is if this is better, or more confusing down the line and a version would come with the least amount of headaches.
> multi: store KeyLocator in OpenChannel, use ECDH instead of DerivePrivKey

- lnwire/accept_channel.go
- lnwire/announcement_signatures.go
- lnwire/channel_announcement.go
- lnwire/channel_reestablish.go
- lnwire/channel_update.go
- lnwire/closing_signed.go
- lnwire/commit_sig.go
- lnwire/error.go
- lnwire/funding_created.go
- lnwire/funding_locked.go
- lnwire/funding_signed.go
- lnwire/gossip_timestamp_range.go
- lnwire/init_message.go
- lnwire/lnwire_test.go
- lnwire/message.go
- lnwire/node_announcement.go
- lnwire/open_channel.go
- lnwire/ping.go
- lnwire/pong.go
- lnwire/query_channel_range.go
- lnwire/query_short_chan_ids.go
- lnwire/reply_channel_range.go
- lnwire/reply_short_chan_ids_end.go
- lnwire/revoke_and_ack.go
- lnwire/shutdown.go
- lnwire/update_add_htlc.go
- lnwire/update_fail_htlc.go
- lnwire/update_fail_malformed_htlc.go
- lnwire/update_fee.go
- lnwire/update_fulfill_htlc.go
Removes the `MaxPayloadLength` function from the `lnwire.Message` interface since each message can now be up to 65535 bytes including the 2-byte type.  This PR also fixes the `ping` and `pong` payloads which were previously coded as 65532, instead of 65533.
> lnwire: remove MaxPayloadLength from lnwire.Message interface

- input/size.go
- input/size_test.go
- lnwallet/channel.go
- lnwallet/transactions.go
- sweep/txgenerator_test.go
We ensure the size constants and their godoc checks out.
See https://github.com/lightningnetwork/lightning-rfc/pull/815 for a disagreement with the spec that was found in the process.
> [input/size] Check tx size constants

- cmd/lncli/cmd_open_channel.go
- lntest/itest/log_error_whitelist.txt
Fixes #5080.
The N_TTY_BUF_SIZE kernel parameter dictates how many characters can be
pasted into a terminal window. This cannot be circumvented by reading
the input in a different manner.
To avoid the problem fully, we instead allso allow the user to type in a
path to a text file that is read if it exists. That way the PSBT can be
as long as needed.
> lncli: allow PSBT to be read from file

- lnd.go
- lnrpc/autopilotrpc/autopilot_server.go
- lnrpc/autopilotrpc/driver.go
- lnrpc/chainrpc/chainnotifier_server.go
- lnrpc/chainrpc/driver.go
- lnrpc/invoicesrpc/driver.go
- lnrpc/invoicesrpc/invoices_server.go
- lnrpc/routerrpc/driver.go
- lnrpc/routerrpc/router_server.go
- lnrpc/signrpc/driver.go
- lnrpc/signrpc/signer_server.go
- lnrpc/sub_server.go
- lnrpc/verrpc/driver.go
- lnrpc/verrpc/server.go
- lnrpc/walletrpc/driver.go
- lnrpc/walletrpc/walletkit_server.go
- lnrpc/watchtowerrpc/driver.go
- lnrpc/watchtowerrpc/handler.go
- lnrpc/wtclientrpc/driver.go
- lnrpc/wtclientrpc/wtclient.go
- lntest/harness.go
- lntest/itest/log_error_whitelist.txt
- lntest/itest/log_substitutions.txt
- lntest/node.go
- log.go
- macaroons/service.go
- rpcperms/interceptor.go
- rpcserver.go
- walletunlocker/service.go
This PR unifies the gRPC server used for the `WalletUnlockerService` and `LightningService`, making both services available at all times. This addresses a long-standing issue of the gRPC server being torn down and restarted after unlocking the wallet.
The reason for the original design of tearing down the gRPC server after unlocking the wallet, was that the RPC server (`LightningService`) was dependent on the wallet being unlocked in order to being created. We mitigate this by now creating the RPC server before the wallet is unlocked, in a "non-functioning" state just in order to register its interface with the gRPC server. After the wallet is finally unlocked, we can populate the dependencies of the root RPC server and its subservers, enabling the full `LightningService` to be …
> [gRPC] WalletUnlocker and RPCServer unification

- mobile/bindings.go
Instead of killing the app, report an error back to the application.
NOTE: this PR depends on https://github.com/lightningnetwork/lnd/pull/5010 as there we remove the `unlockerReady` callback.
Fixes https://github.com/lightningnetwork/lnd/issues/5077
> mobile: gracefully exit if lnd fails to start

- routing/payment_session.go
When no nodes are available, `lnd` will give a segfault. 
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1805e47]
goroutine 356 [running]:
github.com/lightningnetwork/lnd/lnwire.(*FeatureVector).HasFeature(...)
.../lnd/lnwire/features.go:409
github.com/lightningnetwork/lnd/routing.(*paymentSession).RequestRoute(0xc0003349a0, 0x1388, 0x1388, 0x19f00000000, 0x2, 0x0, 0xffffffffffffffff)
.../lnd/routing/payment_session.go:300 +0x7c7
github.com/lightningnetwork/lnd/routing.(*paymentLifecycle).resumePayment(0xc000459e68, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
.../lnd/routing/payment_lifecycle.go:208 +0x8dd
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).sendPayment(0xc0001b68c0, 0x1388, 0x1388, …
```
> routing: check payment.DestFeatures against nil

- cmd/lncli/commands.go
- config.go
- peer/brontide.go
- rpcserver.go
- sample-lnd.conf
- server.go
Fixes #4732 
This PR adds a flag that allows a user to override the default conf target used to estimate the fee that lnd uses when attempting a co-op close.
Currently the value can be set if the channel closure is initiated locally but no option exists for channel closures that are initiated remotely and a hard coded conf target of 6 is used. So this PR just adds a flag so that the user can set this value.
- Commit 1: Adds a new `--coop-close-conf-target` flag used to override the default value used for fee estimation during the channel closure initiated by a _remote_ peer.
- Commit 2: Uses the new `CoopCloseTargetConfs` config value as the default to use for the target conf value to be used for a channel closure initiated _locally_ if the `conf_target` flag has not been set.
> multi: allow setting target confs for co-op close

- cmd/lncli/autopilotrpc_active.go
- cmd/lncli/cmd_build_route.go
- cmd/lncli/cmd_invoice.go
- cmd/lncli/cmd_macaroon.go
- cmd/lncli/cmd_mc_cfg_get.go
- cmd/lncli/cmd_mc_cfg_set.go
- cmd/lncli/cmd_open_channel.go
- cmd/lncli/cmd_pay.go
- cmd/lncli/cmd_query_mission_control.go
- cmd/lncli/cmd_query_probability.go
- cmd/lncli/cmd_reset_mission_control.go
- cmd/lncli/cmd_update_chan_status.go
- cmd/lncli/cmd_version.go
- cmd/lncli/cmd_walletunlocker.go
- cmd/lncli/commands.go
- cmd/lncli/invoicesrpc_active.go
- cmd/lncli/walletrpc_active.go
- cmd/lncli/watchtower_active.go
- cmd/lncli/wtclient.go
Fixes #2133
This PR makes the lncli gPRC contexts cancelable. An os signal interrupt handler is added which cancels the context is an os signal is received. A follow up PR can address #2134 which will make the server context aware. This is a rebase and continuation of the #2147.
One thing here is that it can perhaps be easy to forget to use this new cancellable context in future when new lncli commands are added. So perhaps a github workflow that checks the lncli dir and to make sure that `context.Background` is only called once (shout out to @carlaKC for this idea).
> lncli: cancel RPC context on OS interrupts

- cmd/lncli/cmd_open_channel.go
- cmd/lncli/commands.go
Signal Intercept function needs to be called if the signal shutdown
channel will be listened on. Fixing the bug caught in comment: https://github.com/lightningnetwork/lnd/pull/5097#issuecomment-801415227
> lncli: start signal interceptor in getContext

- build/log_shutdown.go
- build/logrotator.go
- cmd/lncli/cmd_open_channel.go
- cmd/lncli/commands.go
- cmd/lnd/main.go
- config.go
- lnd.go
- log.go
- mobile/bindings.go
- rpcserver.go
- signal/signal.go
This PR addresses issues related to the mobile lnd builds, where calling `stopDaemon` and subsequently calling LndMobile's `Start` results in panic.
This is a part of an on-going work to address mobile restarting problems #4492.
> signal: handle shutdown properly

- channeldb/invoices.go
This PR was created in order to help to debug the failures in:
https://github.com/lightningnetwork/lnd/issues/5113
We add some more contextual errors so we can figure out where the
assumptions of the current scan to delete function in the invoice
registry is incorrect.
> channeldb: return more detailed errors in DeleteInvoice

- lntest/harness.go
- lntest/itest/lnd_test.go
- rpcserver.go
[Previously](https://github.com/lightningnetwork/lnd/pull/5064/files#diff-674c79ba02b6e9c45a994388392689814f3538800351b2fd43fb3ade21e1effbR2323) the rpcserver would not use the remote conf target as its local conf target and this behavior is desirable.
This also re-allows setting a fee rate when cooperatively closing a channel
> rpcserver: revert target conf to previous behavior

- discovery/gossiper.go
- discovery/gossiper_test.go
- routing/router.go
- routing/validation_barrier.go
- routing/validation_barrier_test.go
Previously, we would always allow dependent jobs to be processed, regardless of the result of its parent job's validation. This isn't correct, as a parent job contains actions necessary to successfully process a dependent job. A prime example of this can be found within the AuthenticatedGossiper, where an incoming channel announcement and update are both processed, but if the channel announcement job fails to complete, then the gossiper is unable to properly validate the update. This commit aims to address this by preventing the dependent jobs to run.
> discovery+routing: cancel dependent jobs if parent validation fails

- routing/missioncontrol.go
Fixes the following potential deadlock situation:
* Pathfinding holds a database lock and tries to obtain a mission control lock via GetProbability
* ReportPaymentSuccess/ReportPaymentFail holds a mission control lock and tries to obtain a database lock to store the payment result.
Fixes https://github.com/lightningnetwork/lnd/issues/5104
> routing: fix mission control deadlock

- config.go
- lnd.go
Otherwise, if the port is connectable, anybody can connect and see debugging information.
See: https://mmcloughlin.com/posts/your-pprof-is-showing
> lnd: optionally serve pprof on localhost for better security

- lnd.go
- lnrpc/Dockerfile
- mobile/bindings.go
- mobile/gen_bindings.sh
It's been a long standing issue that React Native only supports a single callback, which was a problem with the `unlockerReady` and `rpcReady` callbacks we used in the start method.
This PR builds on top of #5005 to circumvent this by exposing the `StateAPI` also on mobile. This let the client start LND, and immediately start using the new API to determine whether the `walletUnlocker` is ready, and finally when the RPC is.
Depends on
> [mobile] Allow state API on mobile, simplify callback mechanism

- Makefile
- lnrpc/gen_protos_docker.sh
- mobile/gen_bindings.sh
This PR fixes a regression after moving to generating the mobile RPCs in docker, as the `prefix` environment  variable wasn't threaded through.
cc @hsjoberg 
Fixes #5177
> make: pass mobile subserver prefix to docker when generating mobile RPC

- chainntnfs/test_utils.go
- chainreg/chainregistry.go
- config.go
- go.mod
- go.sum
- lncfg/bitcoind.go
- lnd.go
- lnwallet/test/test_interface.go
- routing/chainview/interface_test.go
- sample-lnd.conf
To minimally support lnd deployments connected to pruned nodes, we've extended our bitcoind RPC client with the ability to request blocks that the server has already pruned. This is done by connecting to the server's full node peers and querying them directly. The number of peers we connect to can be set through the new `pruned-node-max-peers` config option; it is configured with a default of 4 at the moment. Ideally, this is a capability supported by the server, though this is not yet possible with bitcoind.
Block caching is not done yet, but will be expected to roll out along with this feature as a separate PR to minimize bandwidth consumption.
Note that a lot of the diff is unrelated due to a name change within the updated btcd dependency that caused changes across several files in the …
> build+lncfg: support pruned bitcoind backends

- config.go
- peer/brontide.go
- sample-lnd.conf
- server.go
Channel state update batching is an important mechanism to increase the throughput of a Lightning node. With high degrees of batching many synchronous and expensive disk writes can be avoided. Batching comes at the cost of increased latency. For high-frequency (streaming) applications this may be an acceptable trade-off. 
This PR simply makes the batch timer configurable to allow node operators to tune their node to a particular traffic pattern.
As a follow-up it could be worth to consider a dynamic batch interval based on system load ("commit on idle").
> config: add commit time parameter

- Makefile
`DEPGET` is failing for `go-acc` because it can't get the `ory/x` dep (tag deleted somewhere?). This dependency has been [removed](https://github.com/ory/go-acc/pull/17) from `go-acc`, although the issue on the repo that it fixes is not the same. 
```
go: github.com/ory/x@v0.0.216 requires
github.com/ory/cli@v0.0.49 requires
github.com/ory/kratos@v0.5.5-alpha.1.0.20210319103511-3726ed4d145a requires
github.com/ory/kratos/corp@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
Bumping our `go-acc` commit to one which does not contain the problematic dep fixes `unit-cover`
> makefile: bump goacc commit

- routing/pathfind.go
Found a  nil pointer dereference when writing tests in other PRs, send a fix here.
> routing: fix pathfind edge features being nil

- lncfg/neutrino.go
- lncfg/routing.go
- lnd.go
- lntest/neutrino.go
- sample-lnd.conf
Replaces https://github.com/lightningnetwork/lnd/pull/5151.
Fixes #5149.
Downloading every block that contains a channel point takes a very long
time when syncing the graph on mainnet with Neutrino. Therefore it makes
sense to use routing.assumechanvalid=true since by using Neutrino a user
already accepts the different trust model.
Apparently the existence or meaning of the routing.assumechanvalid flag
is unknown to a lot of users and is overlooked.
This PR basically sets the default to routing.assumechanvalid=true
for Neutrino. Because the CLI library doesn't support setting a bool
value to false by the user if the default is true, we need to add an
additional flag that is the inverse of the routing one, just for the
case where a Neutrino user explicitly wants to turn on channel …
> Use routing.assumechanvalid=true by default in Neutrino mode

- channeldb/invoice_test.go
- channeldb/invoices.go
This PR fixes a regression introduced in #5108.
Without this check, it's possible to send a probe HTLC w/ a valid
payment address but invalid payment hash that gets settled. Because
there was no assertion that the HTLC's payment hash matches the
invoice, the link would fail when it receives an invalid preimage for
the HTLC on its commitment.
> channeldb/invoice: only allow pay-addr lookup w/ no query hash

- chainntnfs/neutrinonotify/neutrino.go
This PR follows up to neutrino PR: https://github.com/lightninglabs/neutrino/pull/198 and handles the use case where 
old channels unable to finish their re-scan on mobile devices waisting lots of bandwidth on every restart.
While there is a mechanism of "SpendHint" cache to persist the rescan progress, it is only get updated at the end of the process. 
This PR adds additional updates along the way in a similar way to how btcwallet does for the initial rescan.
> Persist rescan progress.

- lntest/itest/assertions.go
- lntest/itest/lnd_funding_test.go
- lntest/itest/lnd_multi-hop_test.go
- lntest/itest/lnd_test.go
- lntest/node.go
I was reading the test logs to understand why the tests were flaky, and made a few changes in assisting me to locate tests.
> itest: logging for subtests and refactor WaitForBlockchainSync

- lnrpc/Dockerfile
- mobile/bindings.go
This PR updates the mobile package to work with falafel changes purposed in this PR: https://github.com/lightninglabs/falafel/pull/8.
It is also is a part of an on-going work to address mobile restarting problems #4492.
N.B: the falafel changes has to be merged before this PR can be merged.
Fixes https://github.com/lightningnetwork/lnd/issues/4492
> mobile: re-initialize listeners via RecreateListeners

- lnwallet/chanfunding/coin_select.go
- lnwallet/chanfunding/coin_select_test.go
- lnwallet/chanfunding/wallet_assembler.go
This PR adds a dust-limit to `CoinSelect` and lets the fee estimation account for if a change output is used or not. Any change output below the dust limit goes towards the fee instead.
It would also be useful for #4029, allowing better interoperability between the two coin-select algorithms `CoinSelect` and `CoinSelectSubtractFees`.
> chanfunding: fee estimation based on change output in `CoinSelect`

- mobile/bindings.go
This PR moves the check if lnd has already been started to the top of the function. The reason for this is that the following code on line 59 before it would also return an error, making the lndStarted check superfluous:
```golang
shutdownInterceptor, err := signal.Intercept()
if err != nil {
_, _ = fmt.Fprintln(os.Stderr, err)
rpcReady.OnError(err)
return
}
```
Cheers!
> mobile: Move lndStarted check to the top of the Start function

- lntest/itest/log_error_whitelist.txt
Assume this is from recent neutrino bump in  f4530d67.
> itest: whitelist neutrino shutting down error

- .github/workflows/main.yml
- .github/workflows/release.yaml
- .travis.yml
- Dockerfile
- dev.Dockerfile
- docker/btcd/Dockerfile
- docker/ltcd/Dockerfile
- docs/INSTALL.md
- go.mod
- lnrpc/Dockerfile
- make/builder.Dockerfile
- make/release_flags.mk
Creating this early so we can feel out if there're any changes in Go 1.16 that affect `lnd` itself. 
I have an M1 laptop now, and I've been using `go1.16beta` up until now. I didn't notice any thing out of the ordinary, other than certain tests being extremely slow to the point they don't pass as they timeout with the default settings. An example of such a test is: `htclswitch/TestChannelLinkCancelFullCommitment`. Our "async payment benchmark" tests pass, but advertise "2 TPS" (to be taken with a grain of salt ofc). My early analysis leads me to beleive there's a concurrency interaction in the switch's mailbox code that ends up soft live locking on the M1.
> build: switch all builds systems and CI/ID to go 1.16, update min go version, add support for compiling M1 binaries

- channeldb/graph.go
- channeldb/graph_test.go
- discovery/gossiper.go
- discovery/gossiper_test.go
- lncfg/routing.go
- routing/router.go
- routing/router_test.go
- rpcserver.go
- sample-lnd.conf
- server.go
This PR revives an old PR to implement the stricter version of zombie pruning [that was added to the spec](https://github.com/lightningnetwork/lightning-rfc/pull/767). The main change is that we'll prune something as a zombie if only _one_ of the edges fails to send out its 2 week hear beat. 
In practice, this'll "shrink" the channel graph for many, and also fix an issue in the current "double disable" logic for those running with `--routing.assumechanvalid`. If such a peer never gets a disable from one side before closing, then they may retain the closed channel in their graph long after it actually closes on chain. 
One side effect of this change is that it may cause routing nodes to remove channels from their graph prematurely if they never get a heart beat for some reason. However in …
> channeldb+discovery: implement strict zombie pruning 

- go.mod
We need to remove the retract as it's a new directive that isn't
understood by Go versions < 1.16.
> build: set Go version to 1.15 remove retract

- chainreg/chainregistry.go
- channelnotifier/channelnotifier.go
- discovery/gossiper.go
- funding/manager.go
- funding/manager_test.go
- htlcswitch/htlcnotifier.go
- htlcswitch/switch_test.go
- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
- invoices/test_utils_test.go
- lnd.go
- peernotifier/peernotifier.go
- server.go
This PR suggests a way to cleanup/release resources in case the server failed to start. 
In case the `Start` function of the server returns an error, there isn't any attempt to stop the sub systems that have been started before the error.
While this behavior doesn't create any major problem when LND is used as an executable, it is problematic when LND is used as a library and needs to be restarted.
For example currently if LND is started without internet connection (common in mobile) it exits and any attempt to run it again (as library) result in a  hang. This hang is due to some systems are still running, not properly stopped and as a result not releasing resources, db files, etc...
The suggested solution here is to trigger cleanup before returning the error, making sure the Start …
> Cleanup in case of server failed to start

- lnrpc/invoicesrpc/invoices_server.go
- lntest/itest/log_error_whitelist.txt
- rpcserver.go
This PR makes all the Subscribe RCP's context aware so that they
stop executing when the request context is cancelled.
Rebases part of #2147 and as suggested by [this comment](https://github.com/lightningnetwork/lnd/pull/2147#discussion_r459357893), this PR only adds context awareness to the `Subscribe` RPCs (which don't write any state). A few follow up PRs can be made to add context awareness to more RPCs. 
Fixes #2134
> rpcserver+lnrpc: make Subscribe RPCs context aware

- lnrpc/wtclientrpc/wtclient.go
- watchtower/wtclient/stats.go
We'd never decrement the number of pending backups upon a watchtower accepting one, making it confusing for users to determine whether their backups have actually been accepted. Along the way, we also rename NumTasksReceived to NumTasksPending to better reflect its purpose.
Fixes https://github.com/lightningnetwork/lnd/issues/5183.
> wtclient: decrement pending tasks stats upon accepted task

- mobile/sample_lnd.conf
This PR addresses new restrictions in Android 11 which causes `net.InterfaceAddrs()` to return an error, which in turn causes lnd to crash. Adding `tlsdisableautofill=1` makes sure that the code-path concerned is [never executed](https://github.com/lightningnetwork/lnd/blob/213b264e4c0f92a23c7dd8a42e0b68e4958a7e3a/cert/selfsigned.go#L47-L52). In fact it doesn't even have to as the code to make in-mem gRPC to work is [here](https://github.com/lightningnetwork/lnd/blob/213b264e4c0f92a23c7dd8a42e0b68e4958a7e3a/cert/selfsigned.go#L108).
For more context see this issue: https://github.com/golang/go/issues/40569.
Cheers.
> mobile: add tlsdisableautofill to sample config

- config.go
Path package only supports the unix path format, not the windows path format.
``` go
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Package path implements utility routines for manipulating slash-separated
// paths.
//
// The path package should only be used for paths separated by forward
// slashes, such as the paths in URLs. This package does not deal with
// Windows paths with drive letters or backslashes; to manipulate
// operating system paths, use the path/filepath package.
package path
```
> lnd: fix #1990 LND can't read .cookie file in Bitcoin datadir (Windows 10)

- docker/docker-compose.ltc.yml
- docker/lnd/start-lnd.sh
A mistake in the entrypoint for the LND container and in the configuration for the Litecoin LND container prevents from actually spinning up a Litecoin LND node using the provided `docker-compose.yml` file.
This PR fixes the entrypoint and adds the Litecoin chain parameter to the docker-compose configartion file.
> docker: fix chain for lnd_ltc

- channeldb/payment_control.go
- channeldb/payment_control_test.go
- routing/mock_test.go
- routing/payment_lifecycle.go
- routing/payment_lifecycle_test.go
As per @halseth's [exceptional explanation](https://github.com/lightningnetwork/lnd/issues/4788#issuecomment-804093718), our payment lifecycle fails to cover the following scenario:
- Shard 0 is dispatched
- Shard 1 is dispatched
- Path finding for shard 2 begins
- Shard 0 returns a fatal error
- Shard 2's [`launchShard`](https://github.com/lightningnetwork/lnd/blob/master/routing/payment_lifecycle.go#L249) fails with `ErrPaymentAlreadyFailed`
- Shard 1 gets stuck in flight and the payment's state is never updated to failed
Fixes: #4788
Fixes: #4501
The [handling](https://github.com/lightningnetwork/lnd/blob/a329c8061266418bccd797aa5d7d277c736ee930/routing/router.go#L1911) in `SendToRoute` is not updated because we want to fail attempts to launch shards for already failed payments, and we …
> routing: handle failure to launch shard after permanent failure

- docs/psbt.md
- lnwallet/chanfunding/psbt_assembler.go
- lnwallet/chanfunding/psbt_assembler_test.go
Fixes a malleability vector where users create the funding transaction with inputs spending P2PKH or P2SH scripts.  We check that all inputs are segwit spends.
> lnwallet/chanfunding: check all PSBT inputs have witness stack

- go.sum
- tools.go
This is a workaround to fix the windows build. Apparently there was a
change in go 1.16 in how the go.sum entries are calculated. Dependencies
that aren't directly depended on are stripped. Because we need this
indirect windows dependency for the integration tests, we add a
workaround that makes sure the entry is kept in go.sum.
> mod+tools: pin down build flag dependent go.sum entry

- htlcswitch/interceptable_switch.go
- lntest/itest/lnd_forward_interceptor_test.go
This PR updates intercepted payments to send channel updates with `TemporaryChannelFailure` as is required by the spec. 
Replaces #5059.
> multi: send channel update for failed interceptor packets

- invoices/invoice_expiry_watcher.go
- invoices/invoice_expiry_watcher_test.go
- invoices/invoiceregistry.go
- lntest/itest/lnd_hold_invoice_force_test.go
- lntest/itest/lnd_multi-hop_htlc_aggregation_test.go
- lntest/itest/lnd_multi-hop_remote_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/lnd_test.go
- lntest/itest/lnd_test_list_on_test.go
This PR adds some tests that demonstrate two bugs in our hodl invoice state machine: 
- #4587 : clients can still settle hodl invoices which have expired (and can't be claimed)
- #4987: when a hodl invoice with active htlcs expires and goes to chain, its htlcs remain in accepted state
A test is also added to demonstrate that we force close channels with active hodl invoices on them when they expire, and some refactoring is done to prepare for the addition of a height-based invoice expiry watcher, which will address these issues.
> invoices: add test to demonstrate hodl invoice bug and refactor

- blockcache/blockcache.go
- blockcache/blockcache_test.go
- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/bitcoindnotify/bitcoind_test.go
- chainntnfs/bitcoindnotify/driver.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/btcdnotify/btcd_test.go
- chainntnfs/btcdnotify/driver.go
- chainntnfs/neutrinonotify/driver.go
- chainntnfs/neutrinonotify/neutrino.go
- chainntnfs/test/test_interface.go
- chainreg/chainregistry.go
- config.go
- lnd.go
- lnwallet/btcwallet/blockchain.go
- lnwallet/btcwallet/btcwallet.go
- lnwallet/btcwallet/driver.go
- lnwallet/test/test_interface.go
- routing/chainview/bitcoind.go
- routing/chainview/btcd.go
- routing/chainview/interface_test.go
- routing/chainview/neutrino.go
- sample-lnd.conf
This PR adds a blockcache package. An lnd-wide blockcache is instantiated and passed to which ever chain backend is being used.
Addresses step 1 of #5075
> blockcache: add blockcache pkg and pass it to all backends

- channeldb/invoice_test.go
- channeldb/invoices.go
- invoices/invoiceregistry.go
This PR relaxes `DeleteInvoice` failure cases by removing the requirement that the invoice needs to be indexed by the payment address. Since payment address index was introduced with an empty migration it is possible that users have old invoices which were never added to this index causing invoice garbage collection to get stuck.
Migration reference (with discussion):  https://github.com/lightningnetwork/lnd/pull/4285/commits/cbf71b5452fa1d3036a43309e490787c5f7f08dc#r426368127
> invoices: do not fail DeleteInvoice if payment addr isn't indexed

- config.go
- docs/rest/websockets.md
- lnd.go
- lnrpc/metadata.go
- lnrpc/rest-annotations.yaml
- lnrpc/rpc.pb.gw.go
- lnrpc/rpc.swagger.json
- lnrpc/websocket_proxy.go
- lntest/itest/lnd_rest_api_test.go
- lntest/itest/log_error_whitelist.txt
- sample-lnd.conf
Fixes #4120
Fixes #4497
This PR fixes the WebSocket support for client-streaming (request-streaming) RPCs.
At the moment this is the `lnrpc.Lightning.ChannelAcceptor`, `lnrpc.Lightning.SendPayment` and `routerrpc.HtlcInterceptor`.
At the same time we also fix the keep-alive issue where the WebSocket server wouldn't respond to ping messages correctly.
> REST: Enable support for bi-directional streaming RPCs over REST, fix ping/pong support

- discovery/gossiper.go
- routing/router.go
This ensures the waiting receiving channel always receives an error to prevent a deadlock when processing a network update that fails due to the validation barrier.
On commit d5aedbc:
```
1000 @ 0x43a285 0x44a38f 0xc42e86 0xc80fda 0xc8682d 0xc976c9 0x46fce1
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).AddNode+0x245                      github.com/lightningnetwork/lnd/routing/router.go:2218
github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).addNode+0x3b9            github.com/lightningnetwork/lnd/discovery/gossiper.go:1510
github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement+0x574c github.com/lightningnetwork/lnd/discovery/gossiper.go:1554
github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.fu …
```
> routing: return err on validation barrier failure of network update

- channeldb/graph.go
- channeldb/graph_test.go
- routing/errors.go
- routing/notifications_test.go
- routing/router.go
- routing/router_test.go
In this commit, we start to add any channels that fail the normal chain
validation to the zombie index. With this change, we'll ensure that we
won't continue to re-process the same set of spent channels over and
over again.
Fixes #5191.
> routing: add chans rejected due to failed chain validation to zombie index

- breacharbiter.go
- breacharbiter_test.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_watcher.go
- server.go
This commit makes the handoff procedure between the breachabiter and
chainwatcher use a function closure to mark the channel pending closed
in the DB. Doing it this way we know that the channel has been markd
pending closed in the DB when ProcessACK returns.
The reason we do this is that we really need a "two-way ACK" to have the
breacharbiter know it can go on with the breach handling. Earlier it
would just send the ACK on the channel and continue. This lead to a race
where breach handling could finish before the chain watcher had marked
the channel pending closed in the database, which again lead to the
breacharbiter failing to mark the channel fully closed.
We saw this causing flakes during itests.
> breacharbiter<->chainwatcher two-way handoff

- go.mod
- go.sum
Only change is the addition of witness support to the `CreateBlock` rpctest API: https://github.com/btcsuite/btcd/pull/1716
> mod: update btcd to latest master

- channeldb/channel.go
- lnwallet/channel.go
- lnwallet/channel_test.go
**Commits:**
- 9d0d5bdfaf130af695cbb420a774da1bf028aa8f modifies a comment
- 97007fc4faf984932b0e67a29b7fb77df3d7e9c8 fixes logUpdate scope in range loop
- 7da2080a3dfbe0ca74ff9408f29e6006c0cf05d0 is the patch (+1, -1)
- 0547364091ee8bf3f6c8ceeb925a1f625666d473 is the previously failing unit test
**Patch summary:**
- `getUnsignedAckedUpdates` is a function used to restore on channel restart the signed updates our peer has sent us, but that we haven't signed for yet.  It only includes settles and fails.  `RevokeCurrentCommitment` calls it.  The state transition looks like this, before we store them:
```
us     <----fail----  peer
<----sig-----
-----rev---->
```
- `getUnsignedAckedUpdates` previously would only select remote updates with `LogIndex` satisfying:
- `< …
> lnwallet: use tail not tip in getUnsignedAckedUpdates

- lntest/harness.go
- lntest/itest/lnd_test.go
- lntest/itest/log_error_whitelist.txt
- lntest/itest/log_substitutions.txt
- routing/router.go
- rpcserver.go
This PR makes sure the router subsystem is always in sync with the wallet during our itests by adding a condition to the `synced_to_graph` flag in the `GetInfo` RPC.
It also fixes a small issue that #5246 seems to have introduced (based upon a comment I made) that caused the router to sometimes miss the first few blocks during the itests and then error out continuously with `out of order block: expecting height=1, got height=XXX`.
> itest flakes: fix multiple issues around router subsystem being out of sync

- config.go
- docs/INSTALL.md
- docs/wallet.md
- lnd.go
- sample-lnd.conf
- walletunlocker/service.go
Extracted 2 commits from https://github.com/lightningnetwork/lnd/pull/5150
In automated or unattended setups such as cluster/container
environments, unlocking the wallet through RPC presents a set of
challenges. Usually the password is present as a file somewhere in the
container already anyway so we might also just read it from there.
> Auto-unlock wallet from password file

- config.go
- htlcswitch/mock.go
- invoices/invoice_expiry_watcher.go
- invoices/invoice_expiry_watcher_test.go
- invoices/invoiceregistry.go
- invoices/invoiceregistry_test.go
- invoices/test_utils_test.go
- lncfg/invoices.go
- lntest/itest/lnd_hold_invoice_force_test.go
- lntest/itest/lnd_multi-hop_remote_force_close_on_chain_htlc_timeout_test.go
- lntest/itest/log_error_whitelist.txt
- sample-lnd.conf
- server.go
This PR adds a height-based expiry watcher for hodl invoices which will cancel these invoices back before they expire. This prevents lnd from force-closing when an invoice is not released by its creator. Resolving these htlcs properly addresses two state machine issues we run into when a hodl invoice expires: 
- Fixes #4587 : clients can still settle hodl invoices which have expired (and can't be claimed)
- Fixes #4987: when a hodl invoice with active htlcs expires and goes to chain, its htlcs remain in accepted state
An alternative approach was explored in #5136, however there are multiple race issues that arise when the invoice registry does not drive changes in invoice state, so instead an expiry watcher which keeps control in the invoice registry was chosen.
> invoices: add height based expiry watcher

- breacharbiter.go
- breacharbiter_test.go
- input/script_utils.go
- lntest/mock/spendnotifier.go
This PR attempts to solve the theoretical pinning issue that can occur for anchor type channels in the breach case: https://github.com/lightningnetwork/lightning-rfc/pull/803
If 4 blocks pass without the justie tx confirming (it is created using a confirmation target of 2), we will attempt to sweep the commitment outputs separately from the HTLC outputs.
TODO
> [breacharbiter] Split justice tx in case of delayed confirmation.

- lncfg/protocol_rpctest.go
- lnwallet/wallet.go
We cap the maximum value we'll reserve for anchor channel fee bumping at
10 times the per-channel amount such that nodes with a high number of
channels don't have to keep around a very large amount for the unlikely
scanario that they all close at the same time.
> [anchors] cap value reserved for anchor fee bumping

- lnwallet/chanfunding/psbt_assembler.go
- lnwallet/chanfunding/psbt_assembler_test.go
Fixes #5287.
The PSBT spec is a bit vague when it comes to the WitnessUtxo field of
an input as it's not strictly required for witness inputs. Therefore
Electrum for example does not include the field.
We need to make the SegWit input check a bit more elaborate by looking
at the output script of the UTXO and also the redeem script in case it's
a nested SegWit spend.
> chanfunding: extend PSBT witness input check

- lnrpc/routerrpc/router_backend.go
- lnrpc/routerrpc/router_backend_test.go
- routing/payment_session.go
- routing/payment_session_test.go
- rpcserver.go
With this patch, we'll fail out earlier in the cycle in case of some wonky parameters, and not leave zombie payments in the router which currently are not cleaned up.
> multi: validate payment params at RPC layer

- rpcserver.go
GetNodeInfo retrieves the policies for every edge the node belongs to. When these policies are retrieved from the database, they're returned in the following order: the first policy is the outgoing policy from the node, and the second is the incoming policy to the node. This ordering is not consistent with the ordering we have within our other RPCs like GetChanInfo and DescribeGraph, where policies are sorted based on the smaller public key of the nodes within an edge.
Fixes https://github.com/lightningnetwork/lnd/issues/3426.
> rpc: fix policy order for GetNodeInfo

- build/version.go
Includes:
- #5260 
- #5295 
Also fixes a bug in the release script caused by the `v0.13.0-beta.rc1` and `kvdb/v1.0.0` tags being on the same commit. This caused the release binaries to be compiled with `kvdb/v1.0.0` as the version, which fails to pass `verify-install.sh`.
`v0.13.0-beta.rc1` has been pulled.
> build/version: bump to v0.13.0-beta.rc2

- rpcserver.go
Fixes #5301.
This was introduced with #5295. Since either policies can be nil, we
need to always check that first.
I'm not sure if this is sufficient to still get the correct ordering. Do we perhaps also need to check the `ChanUpdateDirection` of `c2`, just in case `c1` is nil?
> rpcserver: add nil check to policy ordering

- lnrpc/rest-annotations.yaml
- lnrpc/routerrpc/router.pb.gw.go
- lnrpc/routerrpc/router.swagger.json
Fixes #5307.
Corrects some typos in the REST annotations for the routerrpc subserver.
Unfortunately these mistakes aren't caught by the current version of the
grpc-gateway library. But we intend to update to v2 soon which will
output alerts as mentioned in #5307.
> lnrpc: fix typos in REST annotations for routerrpc

- invoices/invoiceregistry.go
Was reading code and found `notifyClients` has an unused param `state channeldb.ContractState`, this PR fixes it.
> invoices: remove unused param in notifyClients

- channeldb/duplicate_payments.go
- channeldb/mp_payment.go
- channeldb/mp_payment_test.go
- channeldb/payment_control_test.go
- channeldb/payments.go
- channeldb/payments_test.go
- routing/control_tower_test.go
- routing/payment_lifecycle.go
When running on a node with a lot of payments (+900k), we see a significant performance slowdown from the ec ops in `btcec.PrivKeyFromBytes` used to deserialize the session key for the attempt. 
Part of profile for `ListPayments` (can't take full screenshot at high enough res): 
We don't actually need this value after it's been read off disk, except for when we resume an in-flight payment and [regenerate its sphinx packet](https://github.com/lightningnetwork/lnd/blob/d771ed761678f8074bd396db1d77c7b7b859abdc/routing/payment_lifecycle.go#L501) so we can lazily read the raw bytes off disk, and perform the expensive EC ops only when required. Since the serialized session key is just `[32]byte`, we can just swap out the field in the `HtlcAttemptInfo` without a migration. 
PR is can probably be …
> channeldb: read HtlcAttemptInfo session key raw bytes

- go.mod
- go.sum
This pulls in the latest btcutil & btcutil/psbt commit that includes a panic fix for malformed PSBT inputs.
> go.mod: update to use latest btcutil commit with psbt fix

- breacharbiter_test.go
Since publication would deadlock on publishing the tx in case the test
had failed we also select on the brar quit channel.
> breacharbiter_test: select on quit chan on publication

- docs/grpc/python.md
Small change to `rpc.proto` in order to fix issue described in issue #5163 affecting python gRPC PolicyUpdateRequest requests.
This changes the variable in `PolicyUpdateRequest` from `global` to `update_all`.
> Update PolicyUpdateRequest to avoid python clash

- discovery/gossiper.go
This log can be "spammy" while nodes throughout the network have yet to upgrade to v0.13.0-beta, which includes several enhancements to prevent the broadcast of zombie edges/updates.
> discovery: demote err log to debug from processZombieUpdate

- chainreg/chainparams.go
- chainreg/chainregistry.go
- cmd/lncli/main.go
- config.go
- go.mod
- go.sum
- lncfg/chain.go
- lnd.go
- sample-lnd.conf
- server.go
- zpay32/decode.go
- zpay32/encode.go
Fixes https://github.com/lightningnetwork/lnd/issues/5018.
Depends on https://github.com/btcsuite/btcd/pull/1692.
Depends on https://github.com/btcsuite/btcwallet/pull/735.
Updates to the latest `btcd` version (which is why the diff is that large) and adds basic signet support.
> Add basic bitcoin signet support

- go.mod
- go.sum
Depends on https://github.com/btcsuite/btcutil/pull/198.
Fixes https://github.com/lightningnetwork/lnd/issues/5337.
Bumps the btcutil dependency to the latest version that fixes a bug in
parsing addresses.
> mod: update btcutil dependency

- cmd/lncli/walletrpc_active.go
- lnwallet/btcwallet/btcwallet.go
As I was writing https://github.com/lightningnetwork/lnd/pull/5322, I noticed it was possible to invoke the NewAddress RPC to generate a NP2WKH address for a P2WKH account, which shouldn't be allowed.
> lnwallet: check if requested address type is compatible with account

- lnrpc/invoicesrpc/addinvoice.go
- lnrpc/routerrpc/router_backend.go
- lntest/itest/lnd_amp_test.go
- lntest/itest/lnd_mpp_test.go
This PR permits an AMP invoice to be "pseudo-reusable", where the invoice
paramters can be used multiple times so long as a new payment address is
supplied. This prevents additional round trips between payer and payee
to obtain a new invoice, even though the payments/invoices won't be
logically associated via the RPC interface like they would when the full
reusable invoices are deployed.
It also increases the default MPP expiry from 1 hour to 1 day. For the new AMP
invoices, we increase the interval to 1 month. The longer time frames
for AMP invoices is used so that the invoice can be pseudo reused as
implemented in the prior commit.
The BOLT 11 default of 1 hour is still preserved whenever the field is
missing in the payment request itself, but as of this commit the field
will always be …
> lnrpc: allow AMP pay-addr override + bump invoice timeouts

- lnrpc/walletrpc/walletkit_server.go
Small typo on the returned response
> Fix typo on FundPsbt fee definition error

- chainreg/chainregistry.go
- config.go
This addresses the issue pointed out in https://github.com/lightningnetwork/lnd/pull/5025#discussion_r641044138.
> config+chainreg: fix default rpc params for signet bitcoind

- build/version.go
Diff from prior rc includes: 
* https://github.com/lightningnetwork/lnd/pull/5311
*  https://github.com/lightningnetwork/lnd/pull/5316
* https://github.com/lightningnetwork/lnd/pull/5164
* https://github.com/lightningnetwork/lnd/pull/5334
* https://github.com/lightningnetwork/lnd/pull/5155
* https://github.com/lightningnetwork/lnd/pull/5025 (signet support)
* https://github.com/lightningnetwork/lnd/pull/5322
* https://github.com/lightningnetwork/lnd/pull/5333 
* https://github.com/lightningnetwork/lnd/pull/5336
* https://github.com/lightningnetwork/lnd/pull/5331
* https://github.com/lightningnetwork/lnd/pull/5328
* https://github.com/lightningnetwork/lnd/pull/5351
> build: bump version to v0.13.0-beta.rc4

- make/release_flags.mk
Removes the os/architecture combinations from the release target list
that had 0 downloads for v0.12.1-beta.
> make: drop unused release targets

- .github/workflows/release.yaml
The golang build cache seems to only grow over time and is now causing
disk space issues on the release builder. Since the release build has to
build for targets that aren't built during other GH actions and our
releases are too far apart to be hitting the cache anyway we suspect the
cache doesn't actually help that much.
Removing it might mean the build takes a bit longer but at least won't
cause any problems with full virtual disks anymore.
> GitHub: remove build cache for release builder

- .github/workflows/release.yaml
- make/release_flags.mk
Replaces #5379.
Discussed with @Roasbeef, since the monitoring server still needs to be enabled with `prometheus.enable`, we're happy to include `monitoring` tag in our default build.
> multi: enable monitoring build by default

- htlcswitch/link.go
- lntest/itest/log_error_whitelist.txt
This fixes #5250 so that node admins can optimize channel balances to avoid failed routing attempts.
The code contribution guidelines state:
> Only use error for internal errors that are never expected to happen during normal operation. No event triggered by external sources (rpc, chain backend, etc) should lead to an error log.
I think that this particular message should be a warning instead, but I also see similar errors. This is why I copied the existing behaviour.
Do I need to update `log_error_whitelist.txt`?
> add detailed log message for "insufficient bandwidth" error

- rpcserver.go
- sweep/walletsweep.go
- sweep/walletsweep_test.go
`SendCoins` ignored the parameter when `SendAll` was set. We now propagate `minConfs` down to `sweeper.CraftSweepAllTx`.
> sweep,rpc: honor minConfs paramater when SendAll is set

- lntest/itest/lnd_test.go
Was looking at the channel force close test and found the wrong node was used to query the balance. (weird as it should have been caught by the test?)
`testChannelForceClosure` has only two relevant participants, `Alice`(not `net.Alice`) and `Carol`, seems like `net.Bob` doesn't belong here.
> itest: fix wrong node queried for balance

- rpcserver.go
A quick fix for #4968. An alternative solution would be to create an distinct interface for SubscribeTransactions so we could use a dedicated log (TXN:) instance.
Here, the log a message will be `[INF] RPCS: New transaction subscription client`.
Fixes #4968.
> rpcserver: log connections to transaction subscription stream

- lntest/harness.go
- lntest/itest/lnd_channel_backup_test.go
- lntest/itest/lnd_forward_interceptor_test.go
- lntest/itest/lnd_funding_test.go
- lntest/itest/lnd_hold_persistence_test.go
- lntest/itest/lnd_max_channel_size_test.go
- lntest/itest/lnd_mpp_test.go
- lntest/itest/lnd_multi-hop-error-propagation_test.go
- lntest/itest/lnd_multi-hop-payments_test.go
- lntest/itest/lnd_multi-hop_test.go
- lntest/itest/lnd_network_test.go
- lntest/itest/lnd_onchain_test.go
- lntest/itest/lnd_psbt_test.go
- lntest/itest/lnd_test.go
- lntest/itest/lnd_wallet_import_test.go
- lntest/itest/lnd_wumbo_channels_test.go
Depends on #5365 , only the second commit is relevant.
This is the second step in this stage, that we no longer need to check the err returned from `net.SendCoins`.
> itest: use require inside net.SendCoins

- lntest/harness.go
- lntest/itest/lnd_channel_backup_test.go
- lntest/itest/lnd_forward_interceptor_test.go
- lntest/itest/lnd_funding_test.go
- lntest/itest/lnd_hold_persistence_test.go
- lntest/itest/lnd_max_channel_size_test.go
- lntest/itest/lnd_mpp_test.go
- lntest/itest/lnd_multi-hop-error-propagation_test.go
- lntest/itest/lnd_multi-hop-payments_test.go
- lntest/itest/lnd_multi-hop_test.go
- lntest/itest/lnd_network_test.go
- lntest/itest/lnd_onchain_test.go
- lntest/itest/lnd_psbt_test.go
- lntest/itest/lnd_test.go
- lntest/itest/lnd_wallet_import_test.go
- lntest/itest/lnd_wumbo_channels_test.go
This PR will be one of my many attempts to refactor the `itest` in the hope that the flakes will be fixed and it would be more enjoyable to write new test cases.
The first stage will be using `require` whenever we can to reduce the number of lines inside each test. This is the first step in this stage, that we no longer need to check the `err` returned from `net.NewNode`.
> itest: use require inside net.NewNode

- funding/manager_test.go
- lnwallet/wallet.go
Otherwise, we would get non-standard txn's and fail to broadcast them when cooperatively closing a channel. This wouldn't affect funds security as no HTLCs would be active to steal. This is just a safety measure as we should only generate standard txn's.
BOLT#02: https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements-5
> lnwallet+funding: sanitize upfront_shutdown_script

- lnrpc/rpc.pb.go
- lnrpc/rpc.proto
- lnrpc/rpc.swagger.json
Issue: https://github.com/lightningnetwork/lnd/issues/5306
Action Taken: Updated v1 switch API documentation in lnd/lnrpc/rpc.proto per discussion in issue above.  Ran make 'rpc-format' and compiled with 'make rpc' which updated rpc.pb.go and rpc.swagger.json appropriately.   Documentation only fix.
- [NA] All changes are Go version 1.12 compliant
- [NA] For new code: Code is accompanied by tests which exercise both
- [NA] For bug fixes: Code is accompanied by new tests which trigger
- [NA] Any new logging statements use an appropriate subsystem and
logging level …
> lnrpc: fix v1 switch API doc

- sample-lnd.conf
Fixes the routing.strictgraphpruning example which doesn't work. It should be in the routing section and not have the -- command line prefix.
While at it, moved the nearby neutrino and other routing options to their respective sections.
> sample-lnd.conf: fix, move astray neutrino and routing options

- docs/release-notes/release-notes-0.13.1.md
- docs/release-notes/release-notes-0.14.0.md
In this commit, we add a new folder within the `docs` directory that will
house the release notes for all versions of `lnd` going forward.  Moving to
use `git` for the release notes rather than the normal drafting procedure
lets us keep track of the set of changes more consistency over time, lets
contributors add their release notes over time, and also means we'll no
longer need to do a crunch at the tail end of the release process to fill in
the set of release notes.
For the 0.13.1 release notes, I've done a scan and added anything that has
been merged since the last major version tag.  In a follow up change, we'll
add a new Github action that fails the build if an entry in the release
notes linking to the newly added PR isn't committed as well. Until then, any
PRs merged in should …
> docs/release-notes: add new in-tree location for release notes

- docs/release-notes/release-notes-0.13.1.md
- routing/router.go
This reverts commit cdddaaca75bba03f408991702e30d581df80daad.
During further testing, we realized that at times neutrino clients may not have an up to date height, meaning they'll incorrectly use a nearer block height leading to a failed payment. We need to investigate this further, but this might be fixed by https://github.com/lightningnetwork/lnd/pull/5315. With regards to this optimization, now that we have https://github.com/lightningnetwork/lnd/pull/5156 it'll be the case that this height is already cached at this point, meaning at most we'll fetch this block twice. Reverting this lets us ensure proper consistency at the send payment call site. 
Fixes #5421
Fixes #5406
Fixes #5415
> Revert "routing: no backend call to fetch best block"

- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/mock.go
- lntest/itest/lnd_max_htlcs_test.go
- lntest/itest/lnd_test_list_on_test.go
- lnwallet/channel.go
- server.go
This PR updates our bandwidth hints to report a zero balance when we're not allowed to add any more htlcs to the remote party's commitment. This prevents pathfinding from using the channel at all; previously it would endlessly try to send shard on the channel. 
The first commit just demonstrates the endless cycle of htlcs by logging (couldn't think of a better way), and should be squashed with the second commit to include a test that asserts that we don't use full channels. Open to other testing options besides an itest, but it's difficult to do because this is a combination of multiple elements - pathfinding + payment lifecycle + link - so mocking this didn't feel like it would meaningfully add much (would be testing the mock rather than the code itself).
Fixes #5297
Fixes #4656
> multi: set zero bandwidth hint for channels that do not have any available slots

- rpcserver.go
This PR addresses an issue where not defining a payment address with the `SendPaymentRequest` results in a `payment_incorrect_details` error for:
* keysend payments, and 
* in LND versions <=0.11 when defining the payment directly using the pubkey in `Dest` and `PaymentHash` instead of using an invoice with `PaymentRequest`.
The error occurs as not defining a payment address with the `SendPaymentRequest` results in an _empty_ payment address byte array in the `paymentIntent` instead of a nil-value.
fixes #5413
> lnd: only set payment address if not empty in PaymentRequest

- lntest/itest/lnd_test.go
- lntest/node.go
In #5364 we added a new error path in the `StopDaemon` method to return
an error if shutdown was attempted while a rescan/recover instance was
in progress. Since the wallet actually won't fully stop (atm)
mid-recovery, the call effectively didn't do anything in that scenario,
so we started to return an error to properly reflect that. However this
causes certain itests to fail, as during recovery, the stop attempt will
fail leading to the test itself failing.
In this commit, we wrap the calls to stop a running daemon within a
`wait.NoError` call so we'll continually try to shut down the daemon
rather than quit on the first try.
Fixes #5423.
> lntest: retry node shutdown attempts to recovery tests

- sample-lnd.conf
Remove deprecated "protocol.anchors" setting from sample-lnd.conf (after it has been replaced by protocol.no-anchors)
This is to avoid confusion, given that several popular guides still mention the older protocol.anchors setting (e.g., RaspiBolt).
> Remove deprecated "protocol.anchors" setting from sample-lnd.conf

- cmd/lncli/profile.go
Fixes #5109.
Instead of checking the existence of the tls file, from global options, we are looking at the string itself. If the file is missing it will return the error message:
`[lncli] could not load global options: could not load TLS cert file: open .lnd/missing_tls.cert: no such file or directory`
If the tls cert path string is empty we proceed like before.
> lncli: check for existence of tls file

- lntest/harness.go
- lntest/itest/lnd_channel_backup_test.go
- lntest/itest/lnd_etcd_failover_test.go
- lntest/itest/lnd_forward_interceptor_test.go
- lntest/itest/lnd_funding_test.go
- lntest/itest/lnd_hold_persistence_test.go
- lntest/itest/lnd_max_channel_size_test.go
- lntest/itest/lnd_mpp_test.go
- lntest/itest/lnd_multi-hop-error-propagation_test.go
- lntest/itest/lnd_multi-hop-payments_test.go
- lntest/itest/lnd_multi-hop_test.go
- lntest/itest/lnd_onchain_test.go
- lntest/itest/lnd_psbt_test.go
- lntest/itest/lnd_rest_api_test.go
- lntest/itest/lnd_routing_test.go
- lntest/itest/lnd_test.go
- lntest/itest/lnd_wallet_import_test.go
- lntest/itest/lnd_wumbo_channels_test.go
This is the continued part (and hopefully the final part) of replacing error checking with `require`.
The next step will be refactoring some of the assertions used.
> itest: use require inside net.EnsureConnected/net.ConnectNodes

- routing/payment_lifecycle.go
- routing/payment_lifecycle_test.go
A follow-up commit for PR #5332 . In this commit we add more docs, rename
function updatePaymentState to fetchePaymentState, and add back the
check for `channeldb.ErrPaymentTerminal` after we launch shard.
> routing: rename method and add err check when launch shard

- contractcourt/chain_arbitrator.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
- contractcourt/commit_sweep_resolver_test.go
- docs/release-notes/release-notes-0.13.1.md
- lntest/fee_service.go
- lntest/fee_service_test.go
- lntest/harness.go
- lntest/itest/lnd_channel_force_close.go
- lntest/itest/lnd_test_list_on_test.go
- lnwallet/chainfee/estimator.go
- lnwallet/chainfee/estimator_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
Pushing for concept ack before moving forward.
Current design records the deadline in `AnchorResolution`, we can also calculate the deadlines inside [the `sweepAnchor`](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/channel_arbitrator.go#L1090). The former design has the advantage as we can fine control what deadlines are for remote/local commitment transactions, the latter one however can give much smaller code change and retain the deadline logic inside `contractcourt`.
Another thing to consider is when extracting info from mempool is supported, things is likely to change here?
Next step,
- extend the deadline to HTLC claims
- add unit test and itest
- make the sweeper use the deadline (the new conf target), ie, build a new fee estimator
For `to_local` and `to_remote` …
> sweeper+contractcourt: deadline aware in sweeping anchors

- cmd/lncli/walletrpc_active.go
The sat_per_vbyte parameter was ignored because of a default value for conf_target.
As a side note: I think it may be better to do parameter validation server-side, because it needs to happen there anyway. In this case for `FundPsbt`, it doesn't seem strict enough because the server allows both `TargetConf` and `SatPerVbyte` to be set, silently ignoring the latter.
> lncli: fix psbt fund parameter parsing

- aezeed/cipherseed.go
- aezeed/cipherseed_test.go
- aezeed/wordlist.go
To make it possible to use the wordlist used for aezeed outside of the
aezeed package we export certain properties of the word list and the
word list itself.
> aezeed: export wordlist and properties

- htlcswitch/interceptable_switch.go
- lntest/itest/lnd_forward_interceptor_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/5115
The problem was several layers removed from the fix. The link decides to
clean up a `fwdPkg` only if it's completed, otherwise it renotifies the
HTLCs. A package is only set to complete if it's `addAck` and
`settleFail` filters are full. For forwarded HTLCs, the `addAck` was
never being set so it would never be considered complete under this
criteria.
`addAck` is set for an HTLC when signing the next commitment TX in the
`LightningChannel`. The path for this is:
* `LightningChannel#SettleHtlc` adds the HTLC to `localUpdates`
* `LightningChannel#SignNextCommitment` builds the `ackAddRef` for all
updates with `SourceRef != nil`.
* `LightningChannel#SignNextCommitment` then passes the list of
`ackAddRef` to …
> htlcswitch: set sourceRef when resolving packets through interceptor

- config.go
- lnd.go
- sample-lnd.conf
As requested by users of node bundle software. They want to use the
wallet-unlock-password-file configuration option in their
default/template config file. This makes the first-time lnd setup a bit
more tricky since lnd will fail with an error if no wallet exists yet
while that config option is used.
The new wallet-unlock-allow-create option instructs lnd to not fail if
no wallet exists yet but instead spin up its unlocker RPC as it would
without the wallet-unlock-password-file being present.
This is not recommended for auto-provisioned or high-security systems
because the wallet creation RPC is unauthenticated and an attacker could
inject a seed while lnd is in that state.
> lnd+config+sample-lnd.conf: add wallet-unlock-allow-create flag

- lnwallet/channel.go
- lnwallet/channel_test.go
In this PR, we fix a payment regression introduced by https://github.com/lightningnetwork/lnd/pull/5355. The newly added `MayAddOutgoingHtlc` method uses the min HTLC value to add a "mock HTLC" to see if any constraints are violated. However in practice, it's possible that an implementation sends over a min HTLC amount of `0 mSAT`. This would cause us to add a zero value HTLC, which would then trigger the `ErrInvalidHTLCAmt` error, causing the bandwidth hints for the link to show up as "zero". 
The initial fix is straight forward: ensure zero is never used. 
The proper fix here is to use the actual HTLC amount as discuseed in #5355. 
Fixes #5468.
> lnwallet: fix payment regression introduced by MayAddOutgoingHtlc

- channeldb/payment_control.go
- routing/payment_lifecycle.go
- routing/router.go
- routing/router_test.go
In this commit, we fix a regression introduced by a recent bug fix in
this area. Before this change, we'd inspect the error returned by
`processSendError`, and then fail the payment from the PoV of mission
control using the returned error.
A recent refactoring removed `processSendError` and combined the logic
with `tryApplyChannelUpdate` in order to introduce a new
`handleSendError` method that consolidates the logic within the
`shardHandler`. Along the way, the behavior of the prior check was
replicated in the form of a new internal `failPayment` closure. However,
the new function closure ends up returning a `channeldb.FailureReason`
instance, which is actually an `error`.
In the wild, when `SendToRoute` fails due to an error at the
destination, then this new logic caused the …
> lnrpc/routerrrpc+routing: fix send to route error propagation

- tor/onionaddr.go
Caught a typo in a comment.
Omitting checklist because of trivial change.
> Fixed typo in comment

- sample-lnd.conf
973e87b remove extra whitespace and harmonizes the separators between config sections
2c92958 deletes a duplicate "nolisten=true" line + comment
> sample-lnd.conf: remove duplicate setting and clean up section separators

- cmd/lncli/walletrpc_active.go
Trivial typo fix for consistency in the usage description.
> trivial: walletrpc typo

- Makefile
- docs/fuzz.md
Updates documentation and Makefile.  While doing this, I found that `make fuzz-build` would break.  This PR fixes this by also installing `go-fuzz/go-fuzz-dep`. Would greatly appreciate if others could verify that these build steps work for them!
> docs+Makefile: update fuzz.md to explain new build/run process

- .github/workflows/main.yml
- docs/release-notes/release-notes-0.14.0.md
- scripts/check-release-notes.sh
In this commit, we add a simple bash script to parse out the current PR
number from an environment variable in the GH actions context, and use
that to check to see if the PR has been referenced in the release notes
or not. This isn't 100% fool proof, but it should catch most of the
common cases.
> build: add new GH actions to require release note updates

- .github/pull_request_template.md
- docs/release-notes/release-notes-0.14.0.md
- go.mod
The golang version always needs to be in sync between the go.mod, the PR
checklist and the installation instructions.
We also add a new entry to the PR checklist for the recently added
release notes check.
Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)
being fixed to prevent regressions
per default)
cases it can be justifiable to violate …
> mod+GitHub: shorten PR template, bump golang to 1.15

- docs/code_contribution_guidelines.md
- docs/release-notes/release-notes-0.14.0.md
This PR only fixes a minor typo and phrasing.
> docs: minor fixes to contribution guidelines

- kvdb/debug.go
- kvdb/etcd/debug.go
- kvdb/etcd/nodebug.go
- kvdb/etcd/readwrite_bucket.go
- kvdb/etcd/readwrite_cursor.go
- kvdb/etcd_test.go
- kvdb/nodebug.go
This PR fixes a bug in the cursor where `Delete` would step the cursor to the next element after the deleted one which is incompatible with bbolt. 
Furthermore we remove an assertion that would prevent us from creating a value with a key that already is used for a bucket.  While enforcing this rule is helpful it's impractical as we don't have such buckets and values. Removing this assertion improves etcd Put performance considerably.
Benchmark with the fix (`dbbackend=etcd`):
```
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon/37-of-82/btcd/async_payments_benchmark
test_harness.go:120: 	Benchmark info: Elapsed time:  6.096842747s
test_harness.go:120: 	Benchmark info: TPS:  79.22133144038592
--- PASS: TestLightningNetworkDaemon (17.10s)
--- PASS: …
```
> etcd: kvdb fixes

- docs/release-notes/release-notes-0.14.0.md
- scripts/check-release-notes.sh
Without this commit, the build may break if a PR commit is created, as
that shows the `PR_NUMBER` field we parse out as "master", reflecting
that its a merge commit into the master branch.
> scripts: account for master branch merges in release notes script

- docs/release-notes/release-notes-0.14.0.md
- kvdb/etcd/config.go
- kvdb/etcd/db.go
- kvdb/etcd/fixture.go
- kvdb/etcd/readwrite_tx.go
- kvdb/etcd_test.go
This PR adds a new configuration option to the etcd kvdb backend that allows us to reduce concurrency to single writer (and multiple readers) vs the default commit queue based key set defined concurrency. This will make sure that in a fully remote mode we can instantiate separate backend for legacy code, eg. the wallet database to ensure reverse compatibility.
> etcd: optionally reduce concurrency to single writer for legacy code

- docs/release-notes/release-notes-0.14.0.md
- go.sum
- healthcheck/diskcheck.go
- healthcheck/diskcheck_js.go
- kvdb/backend.go
- kvdb/backend_js.go
- kvdb/bolt_compact.go
- kvdb/interface.go
- lnwallet/btcwallet/config.go
When using parts of `lnd` as a library in other projects that are compiled to WASM, there can't be any direct uses of non-supported syscalls. The main place where such syscalls currently exist are the `bbolt` library and our own `healthcheck` package.
We prevent those packages to be pulled in by guarding them with specific build tags.
> Allow lnd to be imported into projects that are compiled to WASM

- channeldb/payment_control.go
- docs/release-notes/release-notes-0.14.0.md
The bucket sequence we use as payment sequence makes the DB update in
InitPayment conflict and therefore queue up when many concurrent
payments happen. This change allocates payment sequences in blocks
of 1000 to avoid these conflicts.
Without this fix (`dbbackend=etcd`):
```
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon/37-of-82/btcd/async_payments_benchmark
test_harness.go:120: 	Benchmark info: Elapsed time:  6.222378347s
test_harness.go:120: 	Benchmark info: TPS:  77.62305232256877
--- PASS: TestLightningNetworkDaemon (16.93s
```
With this fix  (`dbbackend=etcd`):
```
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon/37-of-82/btcd/async_payments_benchmark
test_harness.go:120: 	Benchmark info: Elapsed time:  4.894176887s …
```
> payments: allocate payment sequences in blocks

- Makefile
- docs/release-notes/release-notes-0.14.0.md
This PR adds `itest-race` build target that can be used with
individual itests to detect and catch uncovered data races.
> build: add itest-race build target to catch data races with itests

- docs/release-notes/release-notes-0.14.0.md
- lnrpc/routerrpc/config.go
- lnrpc/routerrpc/routing_config.go
- routing/missioncontrol.go
- routing/missioncontrol_store.go
- routing/missioncontrol_store_test.go
- routing/missioncontrol_test.go
- sample-lnd.conf
- server.go
This PR changes missioncontrol's store update from per payment to
every second. Updating the missioncontrol store on every payment caused
gradual slowdown when using etcd.
We also completely eliminate the use of the cursor, further reducing
the performance bottleneck. One more Get could be removed if we don't care
about idempotency check (we really shouldn't as it's not efficient to do
so with a remote DB).
Using the `itest=aync_payments_benchmark dbbackend=etcd`:
```
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon/37-of-82/btcd/async_payments_benchmark
test_harness.go:120: 	Benchmark info: Elapsed time:  5.808059726s
test_harness.go:120: 	Benchmark info: TPS:  83.16030185396204
--- PASS: TestLightningNetworkDaemon (15.93s)
--- PASS: …
```
> routing: store missioncontrol state in blocks and eliminate cursor use

- docs/release-notes/release-notes-0.14.0.md
- go.mod
- go.sum
We're using an old and potentially vulnerable version of the DNS
resolution library. This commit bumps the library to the latest
recommended version.
> mod: upgrade miekg/dns library to fix dependabot alert

- docs/release-notes/release-notes-0.14.0.md
- lntest/itest/lnd_payment_test.go
Fixes timeout flakes that rarely happen when `dbbackend=etcd`:
```test_harness.go:88: Failed: (async bidirectional payments): exited with error: 
*errors.errorString alice's remote balance is incorrect, got 771000, expected 1000000
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_payment_test.go:550 (0x13f6ea9)
testBidirectionalAsyncPayments: t.Fatalf("alice's remote balance is incorrect, got %v, "+
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/test_harness.go:112 (0x13a8ace)
(*harnessTest).RunTestCase: testCase.test(h.lndHarness, h)
/home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:247 (0x144c00f)
TestLightningNetworkDaemon.func4: ht.RunTestCase(testCase) …
```
> itest: fix async payment benchmark timeout flakes

- docs/release-notes/release-notes-0.14.0.md
- lnd.go
This changes file creation mode on admin macaroon from 0600 to 0640. The
reason is to make permission management easier.
Closes #4385
**Is this safe?**
Yes, it is. Assuming a reasonably secure Linux system, it will have a
separate group for each user. E.g. a new user `lnd` gets assigned group
`lnd` which nothing else blongs to. A system that does not do this is
inherently broken already.
Since there is no other user in the group, no other user can read admin
macaroon unless the administrator explicitly allowed it. Thus there's no
harm allowing group read.
Because of how trivial the change is, I didn't bother to run tests myself, will let CI do that.
the positive and negative …
> Allow group reading admin macaroon

- docs/release-notes/release-notes-0.14.0.md
- go.mod
- healthcheck/diskcheck_js.go
> build: fix JS health check and module git tag

- docs/release-notes/release-notes-0.14.0.md
- routing/mock_test.go
- routing/router_test.go
Fix #5530. Turns out there's a better way to manage what to return in the mock call. Previously the `failReason` was accessed by concurrent `ReportPaymentFail` calls which ended in a data race. This change also makes `MissionController` mock "cleaner" as it needs to worry about the internal state (`failReason`) no more.
> routing: fix race in TestSendMPPaymentFailed

- Makefile
- docs/release-notes/release-notes-0.14.0.md
Since we don't really do anything with the errors we check in the itest
error whitelist but get a lot of failed Travis runs because of it, we
disable the check for the moment.
> make: disable itest error whitelist check

- docs/release-notes/release-notes-0.14.0.md
- lntest/itest/log_error_whitelist.txt
- lnwallet/wallet.go
See https://github.com/lightningnetwork/lnd/issues/5523
Improve 'ErrReservedValueInvalidated' error string to explain that the
error is triggered by a transaction that would deplete funds reserved for
potential future anchor channel closings (via CPFP)
Add hint that further details can be found in the debug log
Update strings in 'lntest/itest/log_error_whitelist.txt' correspondingly
> lnwallet/wallet.go: clarify anchor chan error str

- docs/release-notes/release-notes-0.14.0.md
- server.go
- server_test.go
In this commit, we fix a bug that would cause nodes attempting to run
using the signet chain, to waste CPU as they attempted to boostrap to a
non-existent DNS seed. We fix this by ignoring the DNS boostrapper is
signet is active. Along the way, we refactor the conditional sightly to
be more readable, and easily extensible.
> server: disable DNS boostrap for SigNet nodes

- lntest/itest/lnd_mpp_test.go
- lntest/node.go
In this commit, we attempt to fix a race condition that may occur in the
current AMP and MPP tests.
It appears the following scenario is possible:
* The `mppTestContext` [is used to create 6 channels back to
back](https://github.com/lightningnetwork/lnd/blob/master/lntest/itest/lnd_amp_test.go#L43)
* The method used to create the channel ends up calling
[`openChannelAndAssert`](https://github.com/lightningnetwork/lnd/blob/edd4152682dc8f70e11da541cd3be4692db4b011/lntest/itest/lnd_mpp_test.go#L300)
which'll open the channel, mine 6 blocks, [then ensure that the
channel gets
advertised](https://github.com/lightningnetwork/lnd/blob/edd4152682dc8f70e11da541cd3be4692db4b011/lntest/itest/assertions.go#L78)
* Later on, [we wait for all nodes to hear about all channels on the
network …
> lntest: fix possible race condition re asserting channel propagation

- docs/release-notes/release-notes-0.14.0.md
- lntest/harness.go
- lntest/itest/assertions.go
- lntest/itest/lnd_channel_backup_test.go
- lntest/itest/lnd_channel_force_close.go
- lntest/itest/lnd_misc_test.go
- lntest/itest/log_error_whitelist.txt
- lntest/itest/test_harness.go
- lntest/node.go
Fixes #5015.
Fixes #5492 (though indirectly, that never caused the tests to fail in the first place).
Fixes two of our most elusive neutrino itest flakes, both in context of anchor output channels.
I'm not 100% sure I can explain properly _why_ this seems to only happen with Neutrino, but this is what I got so far:
- for anchor outputs, we always try to sweep our anchor of our local commit TX and our anchor in the remote commit TX (since we possibly don't know who force closed)
- so if we force close from our end, we always create 1 valid sweep TX (our anchor in the local commitment) and an orphaned one (our anchor in the remote commitment)
- normally the first sweep succeeds and the second sweep fails because we don't have a spare UTXO to anchor it down. so we never actually publish the …
> itest: neutrino anchor output flake fix

- cmd/lncli/cmd_pay.go
- docs/release-notes/release-notes-0.13.2.md
In this commit, we fix a bug that would cause attempts to re-use an AMP
invoice to fail. Without this commit, we would only attempt to parse the
payment addr if no invoice was specified, so a user manually specifying the
pubkey of the detonation. The fix is straight forward: always parse the
`pay_addr` field as the user may be attempting to re-use an AMP invoice w/o
open coding each of the sections.
> cmd/lncli: always parse the pay_addr field for sendpayment

- docs/release-notes/release-notes-0.14.0.md
- kvdb/etcd/commit_queue.go
- kvdb/etcd/commit_queue_test.go
- kvdb/etcd/db.go
- kvdb/etcd/stm.go
- kvdb/etcd/stm_test.go
This commit splits the commit queue changes from https://github.com/lightningnetwork/lnd/pull/5392.
The original idea with the commit queue was to enable seamless concurrency for transactions that are non blocking, while queuing up all txns such that the number of individual retries is minimized. The old design failed to correctly implement the queuing up part which may have resulted in contention on certain keys and slowing things down considerably. This PR attempts to fix these issues by making the queue design simpler and more scalable. 
Design changes heavily inspired by https://github.com/lightningnetwork/lnd/pull/5153
~Rebased on: https://github.com/lightningnetwork/lnd/pull/5579~
> etcd: fix dereferencing issue in commit queue causing contention and change design to be more scalable

- cmd/lncli/walletrpc_active.go
- docs/release-notes/release-notes-0.14.0.md
This pr adds a rpc command for PublishTransaction for the wallet sub-server. As is, this feature is only available though the rest interface. This pr was requested by #5438.
Command will look like: `lncli wallet publishtx <hex-encoded_raw_transaction> --label="name"` were the flag label is optional.
> lncli: add command for publishtransaction

- docs/release-notes/release-notes-0.14.0.md
- lntest/itest/lnd_payment_test.go
This issue has been fixed before in https://github.com/lightningnetwork/lnd/pull/5579 but it seems like one more left flaking occasionally.
> itests: payments test flake fix

- .github/pull_request_template.md
- docs/code_contribution_guidelines.md
- docs/release-notes/release-notes-0.14.0.md
This should save reviewers (and contributors!) a bit of time, by making the new requirements w.r.t population of the release notes more explicit.
> docs: add release notes to PR checklist and contributor guidelines

- docs/code_contribution_guidelines.md
This PR tries to skip the release note check for trivial fix. This is accomplished in the github actions by checking the git message.
> trivial: skip release note for trivial fixes

- cmd/lncli/commands.go
- docs/recovery.md
- lntest/itest/lnd_channel_backup_test.go
- lntest/node.go
I bumped into this earlier when looking at SCB.
Default SCB file name is `channel.backup`, but several bits of documentation and code comments reference `channels.backup` (which is the incorrect file name).
Let me know if you need me to split the commits in a different way, but looking through your contribution guidelines I think I have it right.
> docs: fix inconsistent naming of channel.backup [skip ci]

- docs/grpc/javascript.md
npm module grpc is deprecated as of April 2021. 
The recommended replacement is @grpc/grpc-js. 
The replacement is compatible with the use cases presented in JS examples and so switching examples to it requires only changes to the list of npm modules to install and changes to the imports at the beginning of the files to import.
In my own npm project I have replaced the deprecated module and not noticed any changes in grpc communication with lnd. Additionally the docs for the replacement ie. @grpc/grpc-js claim compatibility. Nonetheless I may be missing a use case or the @grpc/grpc-js developers might have missed a compatibility issue which would require more changes be made to the examples to ensure compatibility with a module being actively maintained.
Source for deprecation: …
> Docs: Replacing deprecated import in JS readme

- docs/release-notes/release-notes-0.14.0.md
- htlcswitch/link.go
- lntest/itest/log_error_whitelist.txt
Changes so that a grep on the log files with just a channel point will yield all link ~and peer~ activity for that channel.
> peer+htlcswitch: improve logging

- cmd/lncli/walletrpc_active.go
- docs/release-notes/release-notes-0.14.0.md
- lnrpc/walletrpc/walletkit_server.go
To support the cpfp fee bump use case where no external outputs are required.
Depends on https://github.com/btcsuite/btcwallet/pull/753
> walletrpc+lncli: allow zero output psbt funding

- docs/release-notes/release-notes-0.14.0.md
- rpcserver.go
Missed this check in PR #5293.
> rpcserver: validate FinalCltvDelta and CltvLimit for REST

- contractcourt/channel_arbitrator.go
- docs/release-notes/release-notes-0.14.0.md
- lntest/itest/assertions.go
- lntest/itest/lnd_channel_force_close.go
The anchor sweeping tx consumes a UTXO from the closing tx (local/remote anchor output), which is an unconfirmed output when the sweep tx is created. ~~IIRC, neutrino doesn't support spending from an unconfirmed output, so this test is skipped.~~
Regarding the mempool, we should have 2 transactions there, the closing tx and the sweeping tx. Sometimes we do create yet another sweeping tx (one for local and one for remote), and it will be discarded as an orphan in `btcd` backend.
Partially fixes #5495
> itest: fix commit deadline for neutrino backend

- docs/release-notes/release-notes-0.14.0.md
- go.mod
- lnd.go
- signal/signal.go
This adds support for notifying systemd about the state of LND. It
notifies systemd just before waiting for wallet password or, if
`wallet-password-file` was specified, right after unlocking the wallet.
This means that "ready" represents RPC being available for intended use.
It's intentional, so that client services can use `After=` in `systemd`
configuration to avoid misleading error messages about missing files or
refused connections.
Part of #4470
Meta:
* I'm not sure what's your policy on dependencies - is this OK? I reviewed the code of the called function and it looks OK. It's quite short so copying it may be even reasonable but if we add socket activation it might get messy.
* I'm really not sure how to test it - docker containers usually don't have systemd. We would probably need …
> Implemented systemd notify

- docs/release-notes/release-notes-0.14.0.md
- lntest/btcd.go
- lntest/node.go
This pr adds the compressed log files (.gz) from logrorate. Right now, only the uncompressed logs are saved. Partly solves #4584. 
Second part will be addressed in a separate pr.
> itest: include compressed btcd backend logs from logrotate

- breacharbiter_test.go
- docs/release-notes/release-notes-0.14.0.md
- walletunlocker/service_test.go
It seems that the GitHub CI runners share a CPU and therefore only have
very few resources available. This causes the wallet unlocker and breach
arbiter tests to fail if we don't give them enough time to complete.
> multi: fix unit test for high CPU load envs

- chanbackup/backup.go
- chanbackup/backup_test.go
- channeldb/db.go
- channeldb/db_test.go
- channelnotifier/channelnotifier.go
- contractcourt/chain_arbitrator.go
- discovery/gossiper.go
- discovery/gossiper_test.go
- docs/release-notes/release-notes-0.14.0.md
- pilot.go
- routing/localchans/manager.go
- routing/localchans/manager_test.go
- routing/router.go
- rpcserver.go
This PR fixes a bug where a db tx is opened within another db tx.
> routing/localchans: fix nested db tx

- docs/release-notes/release-notes-0.14.0.md
- go.mod
- go.sum
- keychain/bench_test.go
- keychain/btcwallet.go
- lnwallet/btcwallet/signer.go
In this commit, we start to optimistically use the new private key cache
that was added to btcwallet. As is, btcwallet will cache the decrypted
account keys for each scope in memory. However, the existing methods
to derive a child key from those account keys requires a write database
transaction, and will re-derive the private key using BIP-32 each time.
The newly added `DeriveFromKeyPathCache` lets us skip all this and
directly use a cache assuming the account info is already cached. The
new logic will try to use this method, but if it fails fall back to the
existing `DeriveFromKeyPath` method. All calls after this will use this
new cached key.
Fixes #5125.
Basic benchmark before the btcwallet change and after:
```
benchmark                    old ns/op     new ns/op     delta …
```
> keychain+lnwallet: when fetching priv keys or signing try to use cache 

- brontide/bench_test.go
- brontide/noise.go
- docs/release-notes/release-notes-0.14.0.md
- peer/brontide.go
In this commit, we implement a simple optimization that dramatically
reduces reduces the number of allocations we need to make when we
decrypt a new message. Before this commit, we would pass in a `nil`
value to the `Decrypt` method which meant that it would always allocate
a new buffers.
Rather than force this behavior, in this commit, we pass in the
ciphertext buffer (with a length of zero), such that the decryption
operation will simply copy the plaintext bytes over the cipher text in
place. This works as the cipher text is always larger than the
plaintext, since the plaintext doesn't have a MAC attached.
The amount the perf increase, amount of allocations, and amount of bytes
allocated are pretty nice:
```
benchmark                        old ns/op     new ns/op     delta …
```
> peer+brontide: when decrypting re-use the allocated ciphertext buf & ensure buf pool buf doesn't escape

- chainntnfs/neutrinonotify/neutrino.go
- chainntnfs/neutrinonotify/neutrino_dev.go
- chainntnfs/txnotifier.go
- docs/release-notes/release-notes-0.14.0.md
**Commit Overview:** 
- `chainntnfs: skip conf dispatch if ntfn already dispatched` is a minor change that prevents a double dispatch scenario in later logic. It mirrors the spending case.
- `chainntnfs/neutrinonotify: make chainUpdates a buffered chan` changes `chainUpdates` from `ConcurrentQueue` to `chan *filteredBlock`.
- `chainntnfs/neutrinonotify: call drainChainUpdates when updating filter` calls `drainChainUpdates` after applying the filter which will take everything off of `chainUpdates` and handle each update before giving control back to the filter update caller.
- `chainntnfs/neutrinonotify: update EndHeight after filter update` updates the `EndHeight` of a historical dispatch *after* updating the filter. This allows us to catch confirmations / spends that happened in this …
> chainntnfs: neutrinonotify patches

- docs/release-notes/release-notes-0.14.0.md
- lnrpc/chainrpc/chainnotifier_server.go
Fixes #4873
Removes error logs from chain notifier if context is canceled. Errors from an exceeded deadline will still be logged as before.
> chainnotifier: remove error logs

- docs/safety.md
Fixes #5691.
With this commit we update the safety guidelines for migrating lnd data
between 32bit ARM and 64bit ARM devices.
> docs: update safety warning in migration guide [skip ci]

- .travis.yml
- docs/release-notes/release-notes-0.14.0.md
Attempted fix for: https://github.com/lightningnetwork/lnd/issues/5532
~Timeout flake has been appearing on Travis lately due to possible performance degradation. In the log it clearly shows that while we scan the chain while running the wallet recovery we do run out of the 30 sec default timeout window: https://termbin.com/ytdy~
Edit:
After some discussion it turned out to be a `btcd` issue so the attempted solution for this flake is to (at least temporarily) switch the ARM itest build on Travis to use `bitcoind`.
> itest: fix on-chain recovery flake caused by short timeout/btcd on ARM

- channeldb/db.go
- channeldb/migration23/migration.go
- channeldb/migration23/migration_test.go
- channeldb/payment_control.go
- channeldb/payments.go
- docs/release-notes/release-notes-0.14.0.md
This PR is a split from https://github.com/lightningnetwork/lnd/pull/5392 where in order to be able to fetch htlc attempts of a payment in one backend transaction, we flatten the `payment-htlcs-bucket` such that it won't include a sub bucket for each individual attempt, but instead we will postfix attempt info keys with the attempt ID. Furthermore we shorten the key prefixes for convenience.
**Why this flattening is important?** 
When using a remote DB backend (etcd or Postgres) fetching a payment can be especially heavy since each DB operation will result in a round-trip to the DB. By flattening the htlc's bucket where each attempt uses a global ID we may be able to fetch the bucket in one go. An implementation of such strategy can be found here: …
> channeldb: flatten the htlc attempts bucket

- docs/release-notes/release-notes-0.14.0.md
- lnrpc/invoicesrpc/addinvoice.go
selectHopHints is the function which constructs hophints otherwise found
in an invoice created with the private flag.
In this commit, we expose that functionality a little more to workaround
needing to create an invoice to retrieve routing hints.
> invoicesrpc: expose selectHopHints

- README.md
This PR changes a link in the section Developer Resources from dev.lightning.community (unmaintained) to docs.lightning.engineering.
It also specifies more clearly what readers can expect to find there.
> trivial: link from readme to builder's guide [skip ci]

- docs/release-notes/release-notes-0.14.0.md
- rpcperms/interceptor.go
- rpcserver.go
Fixes #5694.
This PR removes error logs from the state command, subscribechannelevents, subscribepeerevents, subscribeinvoices, subscribetransactions,  subscribechannelgraph and subscribechannelbackups if context is canceled. Errors from an exceeded deadline will still be logged as before.
> lncli: remove error logs

- docs/release-notes/release-notes-0.14.0.md
- kvdb/backend.go
- kvdb/etcd/config.go
- kvdb/etcd/embed.go
- kvdb/etcd/fixture.go
- kvdb/kvdb_etcd.go
- kvdb/kvdb_no_etcd.go
- lncfg/db.go
- lntest/itest/lnd_etcd_failover_test.go
- lntest/node.go
- sample-lnd.conf
To help debugging issues where the embedded etcd server might fail we redirect etcd logs (info and above) to a node specific log file in itests and will copy it next to the node logs when the test has finished.
> itest: save etcd logs along node logs in separate files

- channeldb/payment_control_test.go
- channeldb/payments.go
- docs/release-notes/release-notes-0.14.0.md
- lnrpc/lightning.pb.go
- lnrpc/lightning.pb.gw.go
- lnrpc/lightning.pb.json.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
- lnrpc/lightning.yaml
- lnrpc/lightning_grpc.pb.go
- rpcserver.go
This PR adds a RPC `DeletePayment` that allows to delete a payment by specifying its payment hash. It also has the option to only delete _failed_ HTLCs of a payment by setting the `failed_htlcs_only` option.
Similar to `DeleteAllPayments` payments that have status InFlight are not touched as they cannot be removed safely. Instead an error is returned.
> add DeletePayment that allows to delete a specific payment or its failed HTLCs

- cluster/etcd_elector_test.go
It looks like #5702 was merged prematurely and broke the kvdb unit
tests.
> cluster: fix kvdb unit test

- chainntnfs/txnotifier.go
- chainntnfs/txnotifier_test.go
- docs/release-notes/release-notes-0.14.0.md
If lnd restarts, a historical dispatch is performed, and then a
re-org of the spend occurs at tip, the caller would never be
notified of the re-org.
> chainntnfs: populate spendsByHeight during historical dispatch

- docs/release-notes/release-notes-0.14.0.md
- lntest/itest/lnd_amp_test.go
Fixes timing issue that caused missed invoice notification.
> lntest/itest: fix SendPaymentAMP test

- .travis.yml
- docs/release-notes/release-notes-0.14.0.md
Reduces the number of concurrent tranches of itests running to two on
ARM in an attempt to make the tests less flaky because of very high CPU
usage with the default 4 parallel tranches.
> Travis: reduce ARM itest parallelism to 2

- peer/brontide.go
This commit adds a missing return statement to pingHandler. This prevents a nil pointer dereference panic from happening if an error is returned from RegisterBlockEpochNtfn.
Found this after getting this travis job failure:
```
=== CONT  TestLightningNetworkDaemon
test_harness.go:118: lnd finished with error (stderr):
exit status 2
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xae1550]
goroutine 1000 [running]:
github.com/lightningnetwork/lnd/peer.(*Brontide).pingHandler(0x3939200)
/home/travis/gopath/src/github.com/lightningnetwork/lnd/peer/brontide.go:2034 +0xc8
created by github.com/lightningnetwork/lnd/peer.(*Brontide).Start
/home/travis/gopath/src/github.com/lightningnetwork/lnd/peer/brontide.go:57 …
```
> peer: return from pingHandler if error

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/neutrinonotify/neutrino.go
- channelnotifier/channelnotifier.go
- contractcourt/chain_arbitrator.go
- discovery/gossiper.go
- docs/release-notes/release-notes-0.14.0.md
- healthcheck/healthcheck.go
- healthcheck/healthcheck_test.go
- htlcswitch/hop/iterator.go
- htlcswitch/htlcnotifier.go
- htlcswitch/switch.go
- invoices/invoiceregistry.go
- netann/chan_status_manager.go
- netann/host_ann.go
- peernotifier/peernotifier.go
- routing/router.go
- sweep/sweeper.go
This is something I found while investigating #5667. When the shutdown cannot complete, the `healthcheck` will be polling the check forever even after the max attempts are reached. This PR fixes it, also adds shutdown logs for assisting debug.
> healthcheck: quit checking when max attempts are reached

- .travis.yml
- docs/release-notes/release-notes-0.14.0.md
The latest ARM build seems to have only ran half of the itests: https://app.travis-ci.com/github/lightningnetwork/lnd/jobs/537407681
This PR attempts to fix itest parallelism by fixing the number of tranches to the parallelism param.
> build: fix itest parallelism

- docs/release-notes/release-notes-0.14.0.md
- record/amp.go
- record/mpp.go
There's a stray log call with a `nil` amp in https://github.com/lightningnetwork/lnd/blob/master/invoices/invoiceregistry.go#L915.
Fixes #5742.
> record: fix nil pointer in log string

- go.mod
- go.sum
We forgot to push a tag after #5702.
> mod: update kvdb to kvdb/v1.0.2 [skip ci]

- docs/release-notes/release-notes-0.14.0.md
- server.go
Default human readable format of NetAddress already contains pubkey:
https://github.com/lightningnetwork/lnd/blob/a329c8061266418bccd797aa5d7d277c736ee930/channeldb/migration/lnwire21/netaddress.go#L38-L47
> server.go: dedupe pubkey output in debug/log msgs

- docs/release-notes/release-notes-0.14.0.md
- go.mod
- go.sum
- kvdb/go.mod
- kvdb/go.sum
The  `github.com/dgrijalva/jwt-go ` is no longer maintained has this CVE https://github.com/advisories/GHSA-w73w-5m7g-f7qc
But it is being used by https://github.com/etcd-io/etcd/issues/13254 which `lnd` uses.
The https://github.com/golang-jwt/jwt/releases/tag/v3.2.1 is a fork of the same version which was  `3.2.0` with the security fix.
> mod : Replace for OSV GO-2020-0017 JWT

- docs/release-notes/release-notes-0.14.0.md
- routing/router_test.go
This fixes a flake I've seen in the wild lately:
```
--- FAIL: TestBlockDifferenceFix (0.01s)
router_test.go:4335: height should have been updated to 5, instead got 4
FAIL
FAIL	github.com/lightningnetwork/lnd/routing	3.865s
FAIL
```
> routing: add wait.NoError to TestBlockDifferenceFix assertion [skip ci]

- channeldb/payment_control.go
- docs/release-notes/release-notes-0.14.0.md
- kvdb/bolt_test.go
- kvdb/etcd/db.go
- kvdb/etcd/readwrite_bucket.go
- kvdb/etcd/readwrite_tx.go
- kvdb/etcd/stm.go
- kvdb/etcd/stm_test.go
- kvdb/etcd_test.go
- kvdb/go.mod
- kvdb/interface.go
- kvdb/prefetch_test.go
This PR is a reworked and cleaned up split from https://github.com/lightningnetwork/lnd/pull/5392. With this API extension `kvdb` drivers are able to add bucket prefetches to reduce the number of round trips later on in a given transaction. The PR adds this functionality to the `etcd` driver as well as demonstrates the speedup it provides on the flattened htlc attempts bucket.
The PR builds on: https://github.com/lightningnetwork/lnd/pull/5635
> kvdb+channeld: extend `kvdb` with `Prefetch` for prefetching buckets in one go and speed up payment control by prefetching payments on hot paths

- docs/release-notes/release-notes-0.14.0.md
- lnrpc/websocket_proxy.go
- lntest/itest/lnd_rest_api_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/5680.
To make sure we're always reading from the WebSocket connection, we need
to always have an ongoing (but blocking) conn.ReadMessage() call going
on. To achieve this, we do the read in a separate goroutine and write to
a buffered channel. That way we can always read the next message while
the current one is being forwarded. This allows incoming ping messages
to be received and processed which then leads to the deadlines to be
extended correctly.
> lnrpc: Fix WebSocket write deadline not being extended

- docs/release-notes/release-notes-0.14.0.md
- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/linkfailure.go
- htlcswitch/mock.go
- lnwallet/chancloser/chancloser.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- peer/brontide.go
- peer/brontide_test.go
- peer/test_utils.go
**Commit overview**:
- `lnwallet: add IsChannelClean method and related tests` modifies `LightningChannel` with a method that returns a boolean indicating whether the channel state is clean or not.  Clean in this case means that no side has lingering updates, no HTLC's, and no pending commitments.  This can be used in dynamic commitments or to ensure cooperative close can start.
- `htlcswitch: extend ChannelLink interface with ShutdownIfChannelClean` exports a method that allows the caller to optimistically shutdown the link if and only if the underlying channel state is clean.
- `peer: add mockUpdateHandler for use in mockMessageSwitch` allows link mocking in the peer unit tests by implementing the `htlcswitch.ChannelUpdateHandler` interface.
- `peer+chancloser: tryLinkShutdown during …
> multi: optimistically shutdown link during coop close

- cmd/lncli/main.go
- go.mod
The use of golang.org/x/crypto/ssh/terminal was marked as deprecated
since that code was moved to its own repo golang.org/x/term.
With this commit we use the new package name directly, which was already
pulled in under its new name anyway.
> mod+lncli: remove deprecated package [skip ci]

- rpcserver.go
Fixes #5796.
Some historical channels might not have the forwarding packages
recorded. And since the error might be silenced, the historical channel
might be nil.
> rpcserver: fix nil issue with historical channels

- docs/grpc/c#.md
- docs/grpc/java.md
- docs/grpc/javascript.md
- docs/grpc/python.md
- docs/grpc/ruby.md
- docs/release-notes/release-notes-0.14.0.md
The `Grpc.Core` NuGet package is in maintentance mode. `Grpc.Net.Client` is now the [recommended](https://github.com/grpc/grpc-dotnet#grpc-for-net-is-now-the-recommended-implementation) implementation.
This is an update to the C# grpc documentation to use the `Grpc.Net.Client` package.
> Update C# grpc docs to use Grpc.Net.Client

- docs/release-notes/release-notes-0.14.0.md
- htlcswitch/link_test.go
When Alice receives a CommitSig near the end of the test, the test assumed that she wouldn't reply with a RevokeAndAck message before shutdownAssert was called. This led to a test flake. Instead, only call shutdownAssert after we've received the RevokeAndAck.
> htlcswitch: fix flake in TestShutdownIfChannelClean

- cmd/lnd/main.go
- docs/release-notes/release-notes-0.14.0.md
- lncfg/address.go
This PR prints more verbose error to the console when the given address is failed to be parsed from the config upon startup.
Fix #5318.
The new error output,
```go
failed to load config: parse address 0.0.0.0::9735 got err: tor general error
```
Fixes #5318
> lndcfg: give verbose err when failed to load config

- config.go
- docs/release-notes/release-notes-0.13.3.md
- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/mailbox.go
- htlcswitch/mailbox_test.go
- htlcswitch/mock.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- lntest/itest/lnd_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- lnwallet/commitment.go
- lnwallet/test_utils.go
- sample-lnd.conf
- server.go
**Commit overview**:
- `lnwallet: introduce GetDustSum method to calculate worst-case dust sum` adds a method on `LightningChannel` to calculate worst-case dust on a commitment. It uses an over-estimation currently, but can be changed if somebody can figure out an exact method to count dust w/o under-counting.
- `htlcswitch: extend Mailbox iface with dust, fee methods` allows the mailbox to be dust-aware.  Dust is tracked from the time a packet is added (`AddPacket`) to the time it's removed (`AckPacket`).
- `htlcswitch: extend ChannelLink iface with dustHandler iface` allows the link to call `Mailbox.SetDustLimits` and bubble up results from `LightningChannel.GetDustSum`.
- `htlcswitch: call evaluateDustThreshold in SendHTLC, handlePacketForward` modifies the switch to be dust-aware so …
> lnwallet+htlcswitch: make Switch dust-aware

- docs/release-notes/release-notes-0.14.0.md
- lnwallet/wallet.go
- rpcserver.go
Currently a whole UTXO is reserved when anchor-channels is used. This means that if the node has a single UTXO, it cannot be spend even if a change output would leave sufficient funds for the reserve in the wallet.
This PR makes use of the returned `txauthor.AuthoredTx` struct that contains a field for an eventual change index. The reason that this is not automatically detected by the `CheckReservedValueTx` function is because the authored transaction is created in dry-run, meaning it does not add the used change output to the wallet to watch for.
This PR hence assumes that the change index from the authored transaction returned by `WalletController.CreateSimpleTx` will indeed be a change output controlled by the wallet. 
Fixes #5648
> lnd: use change output index from authoring TX to check reserved value

- docs/release-notes/release-notes-0.14.0.md
- go.mod
- go.sum
- kvdb/go.mod
- kvdb/go.sum
The gogo/protobuf has OSV GO-2021-0053
https://deps.dev/advisory/OSV/GO-2021-0053?from=%2Fgo%2Fgithub.com%252Flightningnetwork%252Flnd
This is used indirectly and has to be replaced in go.mod to avoid the
direct reference to that version.
The OSV has been addressed in version v1.3.2
> mod:replace gogo/protobuf for GO-2021-0053

- docs/release-notes/release-notes-0.14.0.md
- lntest/harness.go
- lntest/itest/assertions.go
- lntest/itest/lnd_misc_test.go
- lntest/itest/lnd_network_test.go
- lntest/itest/lnd_test_list_on_test.go
- server.go
Fixes #5377 
With this PR, we ensure that when a persistent outbound peer changes its IP address we can reconnect to it. This is done by periodically fetching the peer's latest advertised IP address from the DB and updating the connection request to the peer accordingly.
A new itest, `reconnect_after_ip_change` demonstrates that the original bug and shows how this PR fixes the bug
> multi: refresh peer IP during reconnect

- .github/workflows/main.yml
- .travis.yml
- Makefile
- docs/release-notes/release-notes-0.14.0.md
- go.mod
- go.sum
- lntest/btcd.go
- lntest/itest/lnd_channel_force_close_test.go
- lntest/itest/test_harness.go
- lntest/node.go
- make/testing_flags.mk
Depends on https://github.com/btcsuite/btcd/pull/1752.
Fixes two problems in the itest:
- Some instances of premature channel announcements caused by not all subsystems being in sync --> We fix this by always waiting 50 (or maybe 20 would be enough?) milliseconds after each mined block.
- Some instances of the mining `btcd` and chain backend `btcd` node losing their connection because of the peer stall detection in `btcd` --> We fix this by disabling stall detection
> CI: fix more flakes, move itests to GitHub (except ARM itest)

- .github/workflows/main.yml
- channeldb/db_test.go
- channeldb/setup_test.go
- contractcourt/setup_test.go
- docs/release-notes/release-notes-0.14.0.md
- kvdb/backend.go
- kvdb/kvdb_no_postgres.go
- kvdb/kvdb_postgres.go
- kvdb/postgres/db.go
- kvdb/postgres/db_test.go
- kvdb/postgres/fixture.go
- kvdb/postgres/fixture_interface.go
- kvdb/postgres_test.go
- kvdb/test_utils.go
- routing/setup_test.go
- sweep/setup_test.go
Extend test coverage by running the existing channeldb test suite on the postgres backend. This also includes a modest refactoring of the postgres test fixture to allow the same postgres test instance to be reused, each time with a fresh database. The channeldb tests concurrently instantiate countless databases and it wouldn't be feasible to spin up a new postgres instance on a unique port for each test.
> kvdb: run channeldb test suite on postgres

- docs/release-notes/release-notes-0.14.0.md
- kvdb/bolt_compact.go
Printing the raw bucket name lead to weird characters and even sounds
being printed.
> kvdb/bolt_compact: filter out non-ASCII from bucket name before printing

- lnrpc/signrpc/signer.pb.go
- lnrpc/signrpc/signer.proto
- lnrpc/signrpc/signer.swagger.json
- lnrpc/walletrpc/walletkit.swagger.json
Clarification that KeyDescriptor describes the public key in
raw_key_bytes and the key_loc identifies the private key. Helps
clarify responses from calls like DeriveKey and DeriveNextKey from
WalletKit.
Fixes #5899
> lnrpc: add public key detail to signrpc KeyDescriptor [skip ci]

- .github/workflows/main.yml
- .travis.yml
- docs/release-notes/release-notes-0.14.0.md
- scripts/install_bitcoind.sh
Also switches things over to our own image generated by this repo: https://github.com/lightninglabs/docker-bitcoin-core
> script: update CI to bitcoind 22

- discovery/gossiper.go
- docs/release-notes/release-notes-0.14.0.md
Turns out we need it right now to handle some low latency race
conditions in our integration tests, so we'll opt to simply cap the size
of it to a low amount. We use a basic LRU caching mechainsm.
Fixes https://github.com/lightningnetwork/lnd/issues/5076
> discovery: revamp premature update map

- channeldb/graph.go
- channeldb/graph_cache.go
- channeldb/graph_cache_test.go
- channeldb/graph_test.go
- docs/release-notes/release-notes-0.14.0.md
- lncfg/caches.go
- lntest/node.go
- rpcserver.go
- sample-lnd.conf
This PR moves to optimize our two heaviest RPC calls (`DescribeGraph` and `GetNetworkInfo`) by cache either the raw data or using the existing channel graph cache. A new command line flag has been added to enable/disable the cache for `DescribeGraph`. This PR is meant to significantly reduce the memory overhead of running `lndmon` as it tends to hit these RPC calls pretty frequently.
> channeldb+rpc: optimize graph related RPC calls 

- docs/release-notes/release-notes-0.14.0.md
- server.go
Currently if a peer has multiple working addresses (like 1 clearnet & 1 tor) we will, on startup and during reconnection, attempt to connect to all their advertised addresses at once. The peer will then accept the first connection and so we will cancel the second one _but_ it already reaches the peer and so then _they_ close the first connection in favour of the second one. 
I have tested that this would also happen pre #5538 when `establishPersistentConnections` would kickoff all the connReqs at once but it would then recover since `peerTerminationWatcher` would only try to connect to a single address. With #5538, `peerTerminationWatcher` also uses all the advertised addresses during it's reconnection attempt and so the issue just keeps repeating itself.
In this PR: if we have multiple …
> server: stagger connReqs to multi-address peers

- config_builder.go
- docs/release-notes/release-notes-0.14.0.md
- lnd.go
A follow-up change to https://github.com/lightningnetwork/lnd/pull/5777 that fixes the macaroon creation in local regtest development mode where we use `--noseedbackup` flag in LiT.
> config_builder: always send admin macaroon

- channeldb/graph_cache.go
- docs/release-notes/release-notes-0.14.0.md
Attempted fix for the deadlock reported in https://github.com/lightningnetwork/lnd/issues/5914
It may happen that we do pathfinding while also attempt to change the
graph. In this case changing the database, channel state, graph while
reading from the same sources may create deadlocks. To resolve this we
change locking policy in the graph cache when pathfinding.
An example of such deadlock inserted here to aid the review:
```
1 @ 0x489e0 0x5a7f8 0x5a7e9 0x795e0 0x678a10 0x67898d 0x70ca3c 0x740858 0x740984 0x75ff10 0x601440 0x5f185c 0x741e58 0x7490c0 0x74ab00 0x758d18 0xabdb34 0xbe6394 0xa2b22c 0xaece20 0xae6bb8 0xaec990 0xae6bb8 0xaecb30 0xae6bb8 0xaec628 0xae6bb8 0xae6d5c 0xa0b9bc 0x97fedc 0x983580 0x98f9b4
#	0x795df		sync.runtime_SemacquireMutex+0x3f …
```
> channeldb: avoid locking the graph cache while iterating channels

- cmd/lncli/cmd_payments.go
Fixes #5989.
Fixes a panic in lncli if a payment request and the --data flag is used
at the same time.
> cmd/lncli: fix nil map in payment req [skip ci]

- cmd/lncli/cmd_payments.go
- docs/release-notes/release-notes-0.14.0.md
In this commit, we remove the `--amp-reuse` flag as with the latest
version of lnd that implements properly re-useable AMP invoices, this
flag is no longer needed.
> cmd/lncli: remove --amp-reuse flag from lncli payinvoice

- Makefile
- docs/release-notes/release-notes-0.14.0.md
- kvdb/postgres/config.go
- kvdb/postgres/db.go
- kvdb/postgres/db_conn_set.go
- kvdb/postgres/no_db.go
- lncfg/db.go
- sample-lnd.conf
Currently lnd does not apply a limit to the number of open postgres connections. In high load scenarios, the postgres server may reject new connections, leading to errors in lnd. 
This is also why the connection limit is set to 500 to pass the async benchmark integration test:
https://github.com/lightningnetwork/lnd/blob/b0fa19e8b0430b221e3eace92d619f858deabaf0/Makefile#L197
This PR adds a configuration option to set the maximum number of connections in lnd. By setting this to a value that is below the server limit, it shouldn't be possible to run into errors because of being denied another connection.
Fixes https://github.com/lightningnetwork/lnd/issues/5981
> postgres: add connection limit

- docs/release-notes/release-notes-0.14.0.md
Replaces #5995 (took over to clean up commit according to contribution guidelines, fix typo and add the `[skip ci]` together with some additional formatting fixes).
We link to `master` in the release so I think it's okay to update the release notes _after_ the release has been published.
> docs: fix release notes for 0.14.0 release

- .github/workflows/main.yml
- go.mod
- scripts/check-submodule-version.sh
PR #5992 was merged without a bump in the kvdb version which results in
an error when trying to pull in lnd 0.14.0-beta as a library in other
projects.
I already pushed the kvdb/v1.2.1 tag, so this just fixes the import in external projects.
To avoid this problem in the future, a new script is added that checks for changes in submodules without a bump in the version.
The new procedure for changing submodules now is:
1. Create a PR with the changes to a submodule, for example `kvdb`.
2. In the PR, bump the version of that submodule in the root `go.mod`. That version will not exist as a tag yet. But because of our local `replace` directives, that will not matter to any of the CI scripts as they all just follow the `replace` directive.
3. Once the PR is merged, all that needs to be done is …
> mod: bump version of kvdb submodule

- channeldb/db.go
- docs/release-notes/release-notes-0.14.1.md
It uses the return value without checking for errors in `fetchOpenChannel()`.
> channeldb: check fetchOpenChannel() error

- .github/workflows/main.yml
As is customary with new GitHub actions, they don't work on first
attempt if you don't test them *sigh*
We need to use a more recent version of golang than is pre-installed to
avoid the "unknown directive: retract" error message.
> GitHub: use go version that understands retract directive

- docs/release-notes/release-notes-0.14.1.md
- healthcheck/tor_connection.go
- tor/cmd_info.go
- tor/cmd_info_test.go
Fixes #6013.
This commit fixes the Tor healthcheck that would previously fail if
there were multiple hidden service registered.
In the controller, we only need to know that our service is contained in
the list of active services. But we can't do a string equality check
since there might be multiple services, comma separated.
> tor+healthcheck: fix healthcheck for multiple services

- contractcourt/channel_arbitrator.go
- docs/release-notes/release-notes-0.14.1.md
- feature/manager.go
- feature/manager_internal_test.go
- funding/commitment_type_negotiation.go
- funding/commitment_type_negotiation_test.go
- funding/manager.go
Replaces #6007.
Replaces #6003.
Fixes #6001.
Fixes #6002.
Fixes #5890.
Addresses an issue with explicit channel type negotiation that caused incompatibilities when opening channels with the latest versions of c-lightning and eclair (#5890).
> Rebase bugfix PRs, prepare for minor release

- docs/release-notes/release-notes-0.14.1.md
- funding/commitment_type_negotiation.go
- funding/commitment_type_negotiation_test.go
- funding/manager.go
In this commit, we fix an API inconsistency introduced by a recent fix.
Without this commit, it would be possible for a local user to attempt an
explicit funding type, but then _fallback_ to implicit negotiation if
the remote party didn't have the bit set.
We resolve this by adding a new bit of information to ensure that if
we're the funder and want explicit chan negotiation, we don't settle
for anything less. A new test case has been added to exercise this
behavior.
To recap for posterity, the following issues were found and fixed in the
negotiation logic:
1. If the remote party sent a channel type (in accept channel), but we
didn't, then we would error out. [We no longer error out and instead
ensure the channel type they sent matches what we derived via
implicit …
> funding: ensure a local funding w/ explicit type can't be downgraded

- sample-lnd.conf
this parameter takes time unit h/m/s or else the lnd does not start.
; payments-expiration-grace-period=69h
[skip ci]
> payments-expiration-grace-period needs time unit

- cmd/lncli/cmd_payments.go
- docs/release-notes/release-notes-0.14.2.md
Fixes [issue](https://github.com/lightningnetwork/lnd/issues/5867) by adding json flag to the cli command to allow printLivePayment method to log in json format if specified.
- Flag properly shows in help ✅ 
```bash
bash-5.1# lncli --network=simnet trackpayment --help
NAME:
lncli trackpayment - Track progress of an existing payment.
USAGE:
lncli trackpayment [command options] hash
CATEGORY:
Payments
DESCRIPTION:
Pick up monitoring the progression of a previously initiated payment
specified by the hash argument.
OPTIONS:
--json  if set, payment updates are printed as json messages. Set by default on Windows because table formatting is unsupported.
```
- Using json flag properly logs json ✅ 
```bash
bash-5.1# lncli --network=simnet trackpayment --json …
```
> lncli: Add json flag to trackpayment

- lnrpc/routerrpc/router_backend.go
This PR fixes two error messages in the router_backend.
When payment_hash or final_cltv_delta and payment_request was set, the error message showed that the parameters shouldn't be set with dest instead of payment_request
> routerrpc: fix wrong error messages

- docs/release-notes/release-notes-0.14.2.md
- lnwallet/chainfee/estimator.go
- lnwallet/chainfee/estimator_test.go
Instead of returning an error, we now log the error and return a default fee rate when a given conf target cannot be found from the web fee estimator.
Fixes #6056.
> chainfee: return floor fee rate when a given target is not found

- docs/release-notes/release-notes-0.14.2.md
- routing/missioncontrol_store.go
Potential fix for https://github.com/lightningnetwork/lnd/issues/6061
The crash in the linked issue may have happened due our local references of bbolt's internal data.
> routing: fix memory corruption in MC store

- docs/release-notes/release-notes-0.14.2.md
- lntest/itest/lnd_psbt_test.go
- lntest/itest/lnd_test_list_on_test.go
- lnwallet/wallet.go
This change avoids enforcing new reserved value when PSBT funding is not
finished yet as new inputs and outputs may still be added that could
change the outcome of the check.
This originally failed in the scenario when funding a channel from
external wallet *and depositing to on-chain wallet* was done
simultaneously in a single transaction. If such transaction confirms
then reserved UTXO is guaranteed to be available but the check didn't
take it into account.
The enforcement still occurs in the final step of PSBT funding flow, so
it is safe. It also occurs in case of non-PSBT funding.
This partially fixes https://github.com/lightningnetwork/lnd/pull/5363#issuecomment-875766968
For full fix it'd be great to be able to optionally avoid anchor commitments (to improve privacy).
I will look at …
> Do not enforce new reserved value in PSBT midstep

- docs/release-notes/release-notes-0.14.2.md
- lnrpc/rpc_utils.go
- rpcserver.go
Currently inside `SubscribeTransactions` the streamed `lnrpc.Transaction` structure does not get its `Label` field populated, which seems to be an oversight. 
This PR adds a helper function `lnrpc.RPCTransaction` to return a single `lnrpc.Transaction` and refactors the helper function `lnrpc.RPCTransactionDetails`. This is alos used inside `SubscribeTransactions` to make sure the `Label` field is correctly populated and have the creation of a RPC Transaction in one place.
Fixes #5853
> Adds helper function lnrpc.RPCTransaction to create a single lnrpc.Transaction and refactors lnrpc.RPCTransactionDetails

- docs/release-notes/release-notes-0.14.2.md
- netann/chan_status_manager.go
Fixes https://github.com/lightningnetwork/lnd/issues/5518
> netann: clarify invalid config timeout constraints [skip ci]

- chainreg/chainregistry.go
- docs/release-notes/release-notes-0.15.0.md
Fixes #4636
This PR makes sure lnd listens to the correct zmq notifications.
Right now, a potentially dangerous situation can occur if the ports of `zmqpubrawtx`/`zmqpubrawblock` (bitcoind) and `bitcoind.zmqpubrawtx`/`bitcoind.zmqpubrawblock` (lnd) gets mixed up (as described in #4636). This would result in lnd not being notified of new transactions and/or blocks.
Another potential risk right now stems from users, by misstake, using `zmqpubhashtx` instead of `zmqpubrawtx` and `zmqpubhashblock` instead of `zmqpubrawblock` when configuring bitcoind (as described in https://github.com/lightningnetwork/lnd/issues/4636#issuecomment-884892299). This would cause the same issue.
> config: misconfigured bitcoind zmq

- docs/key_import.md
Documentation update to fix English language ambiguity in key import docs describing `watch_only` parameter.
Seems too trivial to add to `release-notes`, but let me know if you disagree.
> Docs: fix language ambiguity in key import

- cmd/lncli/commands.go
- cmd/lncli/main.go
- docs/INSTALL.md
- docs/release-notes/release-notes-0.15.0.md
- go.mod
- go.sum
`urfave/cli` added functionality for generating Fish shell tab-completions a few releases ago. We bump the dependency version to get access to this functionality, and add a new, hidden subcommand that generates Fish shell compatible tab-completions. 
This PR supersedes #2844
> Add auto-generated Fish shell lncli-completions

- channeldb/db.go
- channeldb/graph.go
- channeldb/graph_test.go
- channeldb/options.go
- docs/release-notes/release-notes-0.15.0.md
- routing/pathfind_test.go
Allow read-only access to a DB backend if the `channeldb` package is used as a library in external projects. For example, this is very useful in `chantools`.
> channeldb: allow to be used read-only in external tools

- docs/release-notes/release-notes-0.15.0.md
- rpcserver.go
Add the missing field `RemoteBalance`. Fixes #5924.
Not sure if this balance is accurate?
> rpcserver: add remote balance for pending force close

- docs/release-notes/release-notes-0.14.2.md
- lnwallet/chainfee/minfeemanager.go
- lnwallet/chainfee/minfeemanager_test.go
The minimum relay fee is always ensured to be above our fee floor except
in the very first min relay fee query to bitcoind. This commit ensures
that the fee floor is respected in this first query.
Fixes #6072
> lnwallet+docs: minrelayfee always above fee floor

- docs/release-notes/release-notes-0.14.2.md
- funding/commitment_type_negotiation.go
- funding/commitment_type_negotiation_test.go
- funding/manager.go
In this commit, we switch to always sending a channel type when we're in
explicit mode. This is compatible with prior versions of lnd as they
won't send a channel type, and we'll just arrive at the same type via
the existing implicit funding.
Fixes https://github.com/lightningnetwork/lnd/issues/6067
> funding: always send a channel type in explicit mode

- docs/code_contribution_guidelines.md
Add the review bot commands to the contribution guidelines so that we
can link to these commands from the bots readme.
> docs: add review bot commands to guidelines [skip ci]

- docs/release-notes/release-notes-0.15.0.md
- mobile/README.md
Improvements on instructions on how to build for mobile:
* Cleaned up markdown headings
* Included necessary commands to install and init gomobile
* Added command on how to go to the correct src folder before building libraries (due to a known limitation in gomobile)
* Added command on how to checkout the last tagged release of lnd before building libraries
* Fixed incorrect link to Dockerfile
* Use go 1.17.3 instead of 1.17.2 in the Dockerfile.
* For convenience, added command on how to move all the generated Swift protoc definition files to the  same directory as the framework file.
> docs: Improvements to mobile instructions [skip ci]

- docs/release-notes/release-notes-0.14.2.md
- signal/signal.go
The log message was confusing because it was emitted even when running
within systemd if the service type was **not** `notify`. This clarifies
the message by mentioning the edge case.
Being able to distinguish the two cases would be nicer but there doesn't
seem to be a reasonably simple, obvious, reliable way to do it.
Complicated solutions are most likely not worth it for a simple log
message.
> (trivial) signal: clarify the log message about systemd

- Makefile
- docs/release-notes/release-notes-0.15.0.md
Disable compiler optimizations and function inlining on a debug build to
improve debugging experience.
> make: don't optimize debug binaries

- docs/release-notes/release-notes-0.15.0.md
- invoices/invoiceregistry.go
- lnrpc/invoicesrpc/invoices_server.go
Commits cherry-picked from #5940 when attempting to fix itest flakes. Previously we've seen test failures re an invoice state not updated before timeout, especially in tests like `aync_payment_benchmark`. 
When a new subscription client is created followed by an immediate cancel, it's likely the client will be removed from the registry's map(noop) and then added to its map again. This subscription will then be kept in the registry until lnd is restarted. Another more serious issue is when multiple subscriptions are made for the same invoice, when the above case happens, other subscriptions may never send invoice updates because a previous client has a stopped notification queue that blocks
following notifications.
> invoice: fix inactive client not cleaned from invoice registry 

- discovery/bootstrapper.go
- docs/release-notes/release-notes-0.14.2.md
- lnwallet/channel.go
- lnwallet/wallet.go
- peer/brontide.go
- peer/test_utils.go
- routing/notifications.go
- server.go
When `lnd` starts, two types of connections are made, the persistent connection and the bootstrapping connection. In short, the persistent connection is made in three steps,
1. `lnd`'s server caches the connection request and sends it to `connMgr`
2. `connMgr` makes the connection and sends it back
3. `lnd` caches the connection so it remembers the peer being connected.
In bootstrapping, we don't rely on `connMgr` (maybe we should?), instead, we directly use `brontide` to make a new connection. Plus, we only attempt to connect with peers that are not connected yet, which is decided by looking into the server's cache.
The above two types are both run inside goroutines. Now suppose the persistent connection finishes to step 2 and is waiting on step 3, before the server remembers the peer …
> peer: fix competing connections to the same peer

- cmd/lncli/walletrpc_active.go
- docs/release-notes/release-notes-0.15.0.md
Adds the complement of `releaseoutput`. Also extends `releaseoutput` with the lock id flag.
> lncli: add leaseoutput command

- Makefile
- docs/release-notes/release-notes-0.14.2.md
Reverts the `Makefile` change in 274faff980a49fe8c104cb98cfe17a9ad7184e52, because that didn't take into account that itests run multiple lnd instances concurrently.
> itest: increase pg database connection limit

- chainntnfs/txnotifier.go
- discovery/gossiper.go
- discovery/reliable_sender.go
- discovery/sync_manager.go
- docs/release-notes/release-notes-0.15.0.md
- funding/manager.go
- routing/errors.go
- routing/router.go
- routing/validation_barrier.go
- routing/validation_barrier_test.go
Commits cherry-picked from #5940 when attempting to fix itest flakes. Previously we've seen test failures re channel not being open after timeout. Turns out it's not a flake so much.
When a message has a height greater than the gossiper's height, the message is ignored and never processed. This PR puts the premature messages into a cache and process them when the gossiper has received new blocks.
> discovery: resend premature messages when block height reached

- contractcourt/channel_arbitrator.go
- docs/release-notes/release-notes-0.15.0.md
Messages that lead to a channel being force-closed by lnd are now logged on "info" log level. Without this, users may be unable to determine the reason for a specific force-close.
I do not understand the logic in `checkRemoteDiffActions` (https://github.com/lightningnetwork/lnd/blob/5d9b59ac5ade96467ddce4469c832fa3d8c481fe/contractcourt/channel_arbitrator.go#L1835). Maybe there's no need to force-close a channel with "dangling commitments"?
Related to #5324
> contractcourt: use "info" log level for messages leading to force-closes

- lntest/harness_miner.go
- lntest/harness_net.go
- lntest/harness_node.go
- lntest/itest/assertions.go
- lntest/itest/lnd_channel_force_close_test.go
- lntest/itest/lnd_open_channel_test.go
- lntest/itest/lnd_rpc_middleware_interceptor_test.go
- lntest/itest/lnd_test.go
- lntest/test_common.go
This PR has commits pulled out from #5939 for easier reviewing, only the last 6 commits are new.
Depends on #5756.
> itest: prepare itest for major refactor

- docs/release-notes/release-notes-0.14.2.md
- lntest/harness_net.go
- lntest/harness_node.go
- lntest/itest/lnd_channel_backup_test.go
- lntest/itest/lnd_network_test.go
- lntest/test_common.go
This PR refactors the `lntest.NodeConfig` so it can be re-used in LiT.
Eventually we'll also want to refactor `lntest.HarnessNode` and `lntest.NetworkHarness`, but those are too tightly integrated right now and the diff would be very large.
The goal is to get this in for 0.14.2 so we can bump the integrated `lnd` version of LiT to that.
> itest: refactor for re-use in LiT

- docs/release-notes/release-notes-0.14.2.md
- go.mod
- htlcswitch/decayedlog.go
- htlcswitch/decayedlog_test.go
- kvdb/postgres/db.go
The decayed log database opening and closing is managed at a higher level in config_builder.go.
> htlcswitch: fix duplicate close

- config.go
This clarifies the usage of the `externalhosts` option and brings its documentation in line with similar options such as `externalip`.
Related issue: #6141
Note: I skipped ci for this commit since it's just a 1 line documentation change and I didn't want to have to update the change log just for this, but I don't mind to re-enable ci and update the change log if that's preferable.
> docs: clarify --externalhosts usage

- docs/release-notes/release-notes-0.14.2.md
- lnwire/lnwire_test.go
- lnwire/ping.go
- lnwire/pong.go
- peer/brontide.go
- peer/brontide_test.go
- server.go
In this commit, we fix an inadvertent memory leak by ensuring we always
use `defer` to clean up the allocated objects/memory we use to be
notified of new blocks to update what we send within the set of ping
headers.
A further optimization here would be using a single global block epoch
housed within the server, that all peer `pingHandler` goroutines use
directly.
Fixes #6143.
> peer: always defer clean up of the block epoch client used for ping headers

- cmd/lncli/commands.go
- cmd/lncli/commands_test.go
- docs/release-notes/release-notes-0.15.0.md
Adds optional `chan_point` flag to lncli `closechannel` command allowing to close channels with channel point as opposed to providing `funding_txid`  and `output_index` separately (e.g. `lncli closechannel --chan_point XX:1`). In case `chan_point` is set, `funding_txid`/`output_index`  (if set) is ignored. 
Addresses issue https://github.com/lightningnetwork/lnd/issues/6131
> lncli: closechannel chan_point flag 

- channeldb/db.go
- channeldb/db_test.go
- contractcourt/channel_arbitrator.go
- docs/release-notes/release-notes-0.14.2.md
For older nodes, this bucket was never created, so we'll get an error if
we try and query it. In this commit, we catch this error like we do when
a given channel doesn't have the information (but the bucket actually
exists).
Fixes #6155
> contractcourt: catch error when no historical bucket exists

- docs/release-notes/release-notes-0.15.0.md
- server.go
We don't have a chain backend to check when we're just running a signer, so we disable the chain healthcheck. 
An alternative would be to have it off by default, but its a good check for regular nodes to have imo.
> server: disable chain health check if we're running without backend

- .github/workflows/docker.yml
Testing GitHub Actions is hard. Testing schedule based actions is even harder... So naturally, it didn't work on first attempt...
Not adding release notes because we already had those for https://github.com/lightningnetwork/lnd/pull/6160. Also not adding `[skip ci]` to make sure the cron job isn't ignored because of it.
> GitHub: fix daily docker build

- channeldb/graph.go
- channeldb/graph_cache.go
- channeldb/graph_test.go
- docs/release-notes/release-notes-0.14.2.md
- go.mod
- kvdb/etcd/readwrite_bucket.go
- kvdb/interface.go
- kvdb/postgres/readwrite_bucket.go
- kvdb/postgres/readwrite_tx.go
- kvdb/postgres_test.go
- kvdb/readwrite_bucket_test.go
- routing/router.go
This PR adds `ForAll` to `kvdb` to allow for efficient range queries. The graph cache loader is rewritten to take advantage of this new method, improving loading time on my machine by approx 150x.
Fixes https://github.com/lightningnetwork/lnd/issues/6041
Fixes https://github.com/lightningnetwork/lnd/issues/6107
> kvdb+channeldb: speed up graph cache

- .github/workflows/main.yml
Zipping logs usually take a few seconds. This commit adds a step timeout in case anything goes wrong with `7z` which has caused the build to run for over 6 hours. 
`[skip ci]` is not used to see the build results, and it might be too trivial to add a release note...
> github: add timeout when zipping log files

- lntest/harness_net.go
The previous comment assumed use of boolean as a second return parameter, but it is an error instead.
> itest: fix documentation for LookupNodeByPub [skip ci]

- docs/INSTALL.md
- docs/release-notes/release-notes-0.14.2.md
- mobile/README.md
I reformatted my Mac, installing macOS Monterey. I therefore had the chance of trying to build the mobile libraries and proto definitions from scratch. Found some issues in the current instructions, which are addressed in this PR:
* Using details and summary tags, we can create sections that can be expanded on click. This makes the document appear shorter and easier to read.
* Simplyfied the instructions for creating LND mobile, especially the setup part
* Fixed bug in checkout of latest tagged release
* Fixed bug in command for moving proto definitions to same folder as xcframework file
* Use Go 1.17.6 for building the Swift proto definitions
* Added link to LND Builder’s Guide
> General improvements to mobile instructions

- docs/release-notes/release-notes-0.14.2.md
- lntest/itest/lnd_rpc_middleware_interceptor_test.go
- macaroons/constraints.go
- macaroons/constraints_test.go
- rpcperms/interceptor.go
macaroons: add GetCustomCaveatCondition func 
This adds a `GetCustomCaveatCondition` function that returns the custom
caveat condition for a given macaroon and caveat name. Previously there
was no function for getting the custom caveat condition from a macaroon,
only for setting one.
rpcperms: set CustomCaveatCondition on middleware req 
This sets the `CustomCaveatCondition` value on rpc middleware requests
if one exists. Previously, this value was always blank even if the
macaroon had a value set for its custom caveat condition.
Fixes #6164.
Edit: I have tested this locally with a grpc interceptor service and verified that it fixed the related issue, the `custom_caveat_condition` field has a value as expected (and no value when none is set while baking the macaroon).
> rpcperms: set CustomCaveatCondition on middleware req

- contractcourt/breach_resolver.go
- contractcourt/breacharbiter.go
- contractcourt/briefcase.go
- contractcourt/chain_arbitrator.go
- contractcourt/chain_watcher.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
- docs/release-notes/release-notes-0.14.2.md
- server.go
This pull request fails back HTLCs if we detect our remote party has broadcasted a breach transaction. This is accomplished by launching a `breachResolver` like any other resolver. A nice bonus is that since the breach-lifecycle is now tracked in the channel arbitrator, we can tack on an `anchorResolver` and sweep the anchor output. This would also allow the breacharbiter code to be moved into this `breachResolver` in a later changeset.
Fixes https://github.com/lightningnetwork/lnd/issues/3494
> server+contractcourt: create breachResolver to ensure htlc's are failed back

- docs/release-notes/release-notes-0.15.0.md
- lntest/harness_node.go
Fixes https://github.com/lightningnetwork/lnd/issues/6199.
If we only set the --datadir flag then lnd will create empty directories
(for letsencrypt and watchtower client) in the default user's home .lnd
directory and will also pick up a config file from there if one exists.
To instruct lnd to only act within the temp itest directory, we need to
use the --lnddir flag instead.
Using the --lnddir flag also overwrites the TLS cert/key path and the
log dir, so we don't need to explicitly set those anymore.
But we need to make sure the node's variables point to the correct
default files/directories.
> lntest: set --lnddir instead of --datadir

- lntest/itest/lnd_channel_policy_test.go
Ran into a flake [here](https://github.com/lightningnetwork/lnd/runs/4936505456?check_suite_focus=true), fix is to just make sure we're connected before we disconnect.
```
=== RUN   TestLightningNetworkDaemon/tranche01/37-of-92/neutrino/derive_shared_key
test_harness.go:90: Failed: (send update disable channel): exited with error: 
*errors.errorString unable to disconnect Carol from Eve: rpc error: code = Unknown desc = unable to disconnect peer: peer 03fc352c7aa5d0bfa5b49d74db1434e9b54fec3b6ee4d4c14a44a9fec9bf42f95a is not connected
/home/runner/work/lnd/lnd/lntest/itest/lnd_channel_policy_test.go:612 (0xee2f1c)
testSendUpdateDisableChannel: t.Fatalf("unable to disconnect Carol from Eve: %v", err)
/home/runner/work/lnd/lnd/lntest/itest/test_harness.go:114 (0xec153c) …
```
> lntest/test: ensure nodes connected before disconnecting

- docs/release-notes/release-notes-0.15.0.md
- lnrpc/invoicesrpc/addinvoice.go
- lnrpc/invoicesrpc/addinvoice_test.go
This PR updates `SelectHopHints` to abstract away the use of lnd's internals (such as access to the graph and switch, and `channeldb.OpenChannel` so that it can be called by code outside of lnd. This is useful because there is currently no way to get a set of hop hints for a node without creating an invoice on your node. 
With the new refactoring, unit testing is miles simpler so I've also added some tests.
> invoicerpc: refactor SelectHopHints to allow external use

- .github/pull_request_template.md
- docs/code_contribution_guidelines.md
This PR contains a proposed change to our PR template (which has been copied in here): 
* Simplify wording on checklist so that its less to read. This makes it more likely that people will engage, with the tradeoff of being more descriptive.
* Add Description + Steps to Test sections
The template proposed has been copied into this PR as an example.
> github: simplify PR template and add more sections

- Makefile
- docs/release-notes/release-notes-0.15.0.md
`rpc-check` is used in our CI pipeline to detect any difference
between the committed and the automatically generated rpc files.
Unfortunately, the current method only detects changes in the
already existing files and won't fail if `make rpc` generates
a totally new file.
`git status --porcelain` makes the trick, it returns a line for
each file that has been modified, created or deleted.
How to test this: 
- Delete any `***.pb.gw.go` from a subserver in the `lnrpc` folder
- Commit the change and push to a new branch
- See the `rpc-check` pass in CI
- Rebase this branch (or apply the change in the Makefile)
- Commit the changes, push it and see the step fail
> makefile: fail rpc-check after finding any changes

- lnrpc/devrpc/dev.proto
- lnrpc/devrpc/dev.swagger.json
- lnrpc/devrpc/dev_grpc.pb.go
The API doc generator failed after merging #6149 because of the `lncli
importgraph` tag in the proto file.
We could also fix the API doc generator by adding the "dev" build tag,
but not including any dev only features in the API docs is probably the
preferred path.
None
> devrpc: remove lncli API docs tag [skip ci]

- docs/code_contribution_guidelines.md
Clarify what style is accepted for go function declarations.
> docs: add guidelines for func declarations [skip ci]

- cmd/lncli/cmd_payments.go
- docs/release-notes/release-notes-0.14.2.md
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
- lnrpc/marshall_utils.go
- lnwallet/parameters.go
- lnwallet/parameters_test.go
Changes the default off-chain/routing fee to be amount dependent and no longer 100% of the payment amount in any case.
This only affects the older RPCs (`SendPayment`, `SendPaymentSync`, `QueryRoutes`) that had this default value of 100% set if the user didn't specify the limit explicitly.
The newer RPCs (`SendPaymentV2`) use a default value of 0 which forces the (API) user to set an explicit value.
We cannot do the same on the older RPCs as that would break backward compatibility of applications and annoy many users (because the symptom is a `NO_ROUTE` error instead of a more explicit `not enough fees` error).
> Fix default value for fee limit

- docs/code_contribution_guidelines.md
Improves our section about formatting and style rules in the contribution guidelines.
> docs: rewrite and regroup formatting rules [skip ci]

- docs/release-notes/release-notes-0.14.2.md
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
- lnwallet/parameters.go
- lnwallet/parameters_test.go
In this commit, we increase the legacy fee limit threshold (the amount
below which we'll allow 100% of funds to go to fees for the non-v2 RPC
calls) from 50 sats to 1k sats.
> lnwallet: increase legacy fee limit threshold to 1k sats

- docs/release-notes/release-notes-0.15.0.md
- lnrpc/invoicesrpc/addinvoice.go
- lnrpc/invoicesrpc/addinvoice_test.go
- lntest/itest/lnd_hold_persistence_test.go
This PR adds limits to our first pass of adding hop hints to invoices. 
- Previously: if we had 100 channels where `remoteBalance > invoice amount` , we would add 100 hints
- Now: we will add up to 20 channels, or enough hints to each incoming bandwidth 2 * invoice amount
The first commit also updates one of our existing itests to ensure we have hop hint coverage, where previously we said that we were adding coverage but did not check that our invoice actually had hints. 
Fixes #6225.
There is an itest reproducing this issue on [this branch](https://github.com/carlaKC/lnd/tree/6225-invoicetoolarge). 
- Run the itest against master -> fails with "invoice too large"
- Run the itest against this branch -> only adds 20 hop hints + passes
Note: the itest takes quite long because it creates …
> invoicesrpc: limit first pass of hop hint selection

- lnwallet/rpcwallet/rpcwallet.go
If we're signing for an UTXO that isn't known to the wallet, then the
UTXO's pk script _must_ be set in the sign descriptor. Otherwise we run
into a generic PSBT serialization error when running in a remote signing
setup.
Fixes https://github.com/lightningnetwork/lnd/issues/6227 (at least as far as the error message goes, actual fix needs to be done in Loop: https://github.com/lightninglabs/loop/issues/457).
> rpcwallet: disallow empty UTXO pk script [skip ci]

- LICENSE
- build/version.go
- channeldb/migration/lnwire21/message.go
- cmd/lncli/main.go
- config.go
- lnd.go
- lnwire/message.go
- signal/signal.go
Update licenses to 2022.
Mention license updates in release notes.
> multi: Update licenses to 2022 [skip ci]

- docs/release-notes/release-notes-0.15.0.md
- lncfg/monitoring_on.go
- monitoring/monitoring_on.go
- sample-lnd.conf
In this commit, we expose a new monitoring option to allow users to
export gRPC performance metrics. These metrics can be used to see how
long certain calls are taking, the total amount of time spent handling
calls, broken down by service and also call.
This option consumes additional memory and disk space for the Prometheus
server, which is why we're opting to make it an optional flag.
> monitoring+cfg: add new option to export gRPC perf metrics

- lntest/harness_net.go
> itest: check feeService against nil upon shutdown [skip ci]

- go.mod
Apparently we already pushed a tag named tlv/v1.0.0 a while ago (which
points to a commit not in master)...
We need to bump the version of the tag to v1.0.1 since we cannot replace
old tags (without causing a lot of caching problems).
> mod: bump tlv version to v1.0.1 [skip ci]

- chanbackup/pubsub.go
- chanfitness/chaneventstore.go
- channelnotifier/channelnotifier.go
- contractcourt/breacharbiter.go
- contractcourt/chain_arbitrator.go
- contractcourt/utxonursery.go
- discovery/gossiper.go
- docs/release-notes/release-notes-0.15.0.md
- funding/manager.go
- htlcswitch/hop/iterator.go
- htlcswitch/htlcnotifier.go
- htlcswitch/switch.go
- invoices/invoiceregistry.go
- lnwallet/sigpool.go
- netann/chan_status_manager.go
- netann/host_ann.go
- routing/router.go
- server.go
- sweep/sweeper.go
- watchtower/wtclient/client.go
After a recent change, a consistent failure has been showing in the test `revoked_uncooperative_close_retribution_zero_value_remote_output` from [the build with `backend=bitcoind dbbackend=postgres`](https://github.com/lightningnetwork/lnd/runs/4991713031?check_suite_focus=true), `lnd` node was stuck at starting channel arbitrator. Here's what could happen.
Suppose a node starts with a channel breached with a state `StateContractClosed`,
1. chain arbitrator starts -> channel arbitrator starts
2. when starting channel arbitrator, we advance the channel state
3. in that `advanceState`, when we begin with `StateContractClosed`, it will send msg to `htlcswitch` via `c.cfg.DeliverResolutionMsg`
4. `htlcswitch` hasn't started yet, causing the above function never returns, and the node will be …
> server: start htlcswitch early in the pipeline

- contractcourt/chain_arbitrator.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/test_utils.go
- peer/brontide.go
This is achieved by changing the 1-way handoff to a 2-way handoff with a done channel. This is a more ideal pattern for subsystem handoff than the existing way and is ideally how all of our existing 1-way handoffs should be. This is done, for example, in the breacharbiter & chain_watcher handoff.
> multi: reliable hand-off from htlcswitch to contractcourt

- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/link.go
- htlcswitch/link_test.go
The counter-party shouldn't be doing this anyways as they would be giving away a preimage for free. Them doing this would bork their own channel due to open circuits not getting trimmed on startup. Removing this faulty behavior also makes it easier to reason about the circuit logic.
> htlcswitch: only pipeline settle if add is locked-in

- config.go
- docs/release-notes/release-notes-0.15.0.md
- sample-lnd.conf
Minor change that clamps `channel-commit-interval` to a max of 1h. Probably other config options should have sensible clamps, but I decided to only do this one for now.
> config: clamp channel-commit-interval to reasonable time

- cmd/lncli/cmd_state.go
- docs/release-notes/release-notes-0.15.0.md
This updates the description that is provided for `lncli state` to match
the states that are currently returned by lnd. `RPC_READY` no longer
exists and is replaced by `RPC_ACTIVE` with a revised description, and
`SERVER_ACTIVE` is added as the status that indicates lnd is fully
ready to accept RPC calls.
See `enum WalletState` in `stateservice.proto`.
> lncli: update `lncli state` description

- autopilot/graph.go
- autopilot/simple_graph.go
- autopilot/simple_graph_test.go
- docs/release-notes/release-notes-0.15.0.md
- rpcserver.go
Computes the Lightning Network's diameter using breadth-first-search (BFS) implemented in `autopilot.SimpleGraph` and via a more efficient method, and exposes it to the `getnetworkinfo` results. Fixes #180.
The calculation of the graph diameter (longest shortest path or maximal eccentricity in the graph) with all-pairs shortest path lengths is cumbersome as noted in previous work #417. It takes about 2 minutes to evaluate the whole graph on my machine, with some optimizations already in place. Other optimizations could be investigated, needing a method to generate and benchmark large graphs. We are looking for a ~100x improvement for the `getnetworkinfo` rpc call to return quickly, which requires probably more than only the optimization of BFS.
* Instead of using *all*-pairs shortest …
> autopilot+lnrpc: add graph diameter calculation to getnetworkinfo

- .github/workflows/docker.yml
Changes the daily testing build to use a unique tag `daily-testing-<YYYYmmdd>` instead of re-using `daily-testing-only`. This provides better compatibility for image registries with immutable tags enabled.
After merging this to master, check the daily build for the new tag format in https://hub.docker.com/r/lightninglabs/lnd/tags
> github: daily builds use a unique tag

- docs/release-notes/release-notes-0.15.0.md
- lnrpc/walletrpc/walletkit_server.go
Return an error to the client if attempting to finalize a PSBS with no missing signatures.
> walletrpc: return an error when finalizing an already complete PSBT

- discovery/gossiper.go
- docs/release-notes/release-notes-0.15.0.md
To improve the readability of the massive function. It may be possible to split them even further.
> discovery: refactor processNetworkAnnouncement into smaller functions

- config.go
- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/interceptable_switch.go
- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/switch_test.go
- htlcswitch/test_utils.go
- lnrpc/routerrpc/forward_interceptor.go
- lnrpc/routerrpc/router_server.go
- peer/test_utils.go
- sample-lnd.conf
- server.go
Adds a flag that makes htlc interception a requirement. The switch will queue htlcs as long as there is no interceptor connected. When the stream disconnects, htlcs waiting for resolution will not resume automatically.
Supersedes #6165 
Solves #6161
> htlcswitch: add an always on mode to htlc interceptor

- cluster/etcd_elector.go
- cluster/etcd_elector_factory.go
- cluster/etcd_elector_test.go
- docs/release-notes/release-notes-0.15.0.md
- lncfg/cluster.go
- lntest/harness_net.go
- lntest/itest/lnd_etcd_failover_test.go
- sample-lnd.conf
This PR makes it possible to configure leader election session timeout. This way failover can be fast if the leader is decommissioned abruptly (killed/crashed).
> cluster: configurable session TTL for the leader elector

- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/switch_test.go
Fixes:
```
Read at 0x00c071c8dcb0 by goroutine 1594:
runtime.mapiternext()
/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/map.go:851 +0x0
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).setInterceptor()
/home/runner/work/lnd/lnd/htlcswitch/interceptable_switch.go:205 +0x3b8
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).run()
/home/runner/work/lnd/lnd/htlcswitch/interceptable_switch.go:161 +0x20a
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).Start.func1()
/home/runner/work/lnd/lnd/htlcswitch/interceptable_switch.go:143 +0x76
Previous write at 0x00c071c8dcb0 by goroutine 103:
runtime.mapdelete()
/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/map.go:685 +0x0 …
```
> switch+test: fix race condition in the interceptor unit test

- channeldb/invoices.go
Was instead returning ErrTypeForEncodingErr. This could technically add the correct length here and in decodeCircuitKeys, but I omitted that.
> channeldb: change to ErrTypeForDecodingErr for amp state

- docs/release-notes/release-notes-0.14.3.md
- lnd.go
It turns out that when a REST call to an endpoint (in this specific
example /v1/payments, which for GET returns all payments but for DELETE
removes all payments) is made with POST instead of the correct
registered method, the grpc-gateway tried to find a fallback method.
That resulted in randomly choosing between any of the calls with the
same URI pattern.
This is of course catasrophic if the user attempts to query the list of
payments (but using POST instead of GET by accident) and then ending up
calling the DELETE endpoint instead.
Turn off fallback mechanis
To reproduce:
```
curl -d '{"num_max_payments": 1000000, "start_time": 0}' -X POST -k --header "$MACAROON_HEADER" https://localhost:8080/v1/payments
```
This will randomly call `ListPayments` or `DeleteAllPayments`.
After this fix, …
> lnd: disable REST proxy HTTP method fallback

- config.go
- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/link.go
- lnwallet/channel.go
- peer/brontide.go
- sample-lnd.conf
- server.go
Fixed an issue while debugging itest flake, where our `PendingCommitTicker` needs to be reset when batch updating commit txes. This PR also makes this value configurable.
> htlcswitch: fix PendingCommitTicker and make it configurable

- docs/release-notes/release-notes-0.15.0.md
- lntest/itest/lnd_forward_interceptor_test.go
Don't shut down the same test node multiple times.
> itest: fix node shutdown in interceptor itests

- config_builder.go
- docs/release-notes/release-notes-0.14.3.md
- lnrpc/walletrpc/walletkit_server.go
- lntest/itest/lnd_remote_signer_test.go
- lntest/itest/lnd_signer_test.go
- lntest/itest/lnd_test_list_on_test.go
- lntest/itest/utils.go
- lntest/mock/walletcontroller.go
- lnwallet/btcwallet/btcwallet.go
- lnwallet/interface.go
- lnwallet/rpcwallet/healthcheck.go
- lnwallet/rpcwallet/rpcwallet.go
Fixes the remote signing setup for Loop and Pool (partially fixes https://github.com/lightninglabs/loop/issues/457):
The `SignOutputRaw` allows signing with a key descriptor that _only_ contains the public key or _only_ the key family and index. In the remote signing setup that information is not sufficient for the remote signing node and we need to make sure we always send both the public key _and_ the full derivation info over the signing RPC.
Fixes https://github.com/lightningnetwork/lnd/issues/6329.
Set up a remote signing node pair and connect the Loop or Pool client to it.
TODO:
- ~Actually run a full manual test suite of using a remote signing node pair for the Loop and Pool clients (and servers).~
> remote signer: fix SignOutputRaw RPC for incomplete key info, fix healthcheck connection leak

- .github/workflows/docker.yml
- docs/DOCKER.md
Re-adds a rolling container image tag, but this one is built and pushed on every update to `master` instead of nightly.
After merging this to master, verify that an image with the `master` tag is present in https://hub.docker.com/r/lightninglabs/lnd/tags
> github: re-add rolling tag 'daily-testing-only'

- docs/release-notes/release-notes-0.15.0.md
- lnwallet/btcwallet/btcwallet.go
If new default scopes are added to the underlying btcwallet
implementation, then they aren't automatically created for _existing_
wallets, only for new ones. So on startup we need to make sure all
scopes are present.
Fixes https://github.com/lightningnetwork/lnd/issues/6377.
1. Create a regtest wallet with `lnd v0.14.2-beta`
2. Upgrade to `master`
3. Start `lnd` and then run `lncli walletbalance`
4. The wallet balance should show, no error should be shown
> btcwallet: always make sure default scopes exist

- docs/release-notes/release-notes-0.15.0.md
- lnrpc/websocket_proxy.go
Was discovered in a race unit test in lightning node connect that uses
the websocket proxy to connect to the hashmail server on the client
side.
By not shadowing the err variable we end up reading and writing to the
same variable from two different goroutines, which causes the data race.
> lnrpc: fix websocket proxy data race

- Makefile
- docs/release-notes/release-notes-0.15.0.md
Hey.
This PR adds two new gomobile related Makefile tasks:
`macos` task: compiles lnd to an XCFramework that can then be embedded into macOS apps.
`apple` task: compiles lnd to an XCFramework that can then be embedded into both iOS and macOS apps.  
I've also updated the `ios` task to build for iOS simulator too.
I separated the commits for clarity, could probably be squashed into master.
> mobile: Add macos and apple Makefile tasks

- rpcperms/middleware_handler.go
This fixes a typo in a gRPC middleware warning log message.
> rpcperms: fix typo

- cmd/lncli/commands.go
Fixes linter issue that was merged with a contributor PR that had the `[skip ci]` suffix. I guess we shouldn't allow that for new contributors if actual code is changed.
I confirmed locally that the linter doesn't complain anymore.
> cmd/lncli: fix linter issues after contributor PR [skip ci]

- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/interceptable_switch.go
- htlcswitch/mock.go
- htlcswitch/switch_test.go
- peer/test_utils.go
- server.go
Adds a basic protection to make sure that we aren't letting the interceptor handle htlcs that are too close to the channel force-close broadcast height.
> htlcswitch: interceptor expiry check

- docs/release-notes/release-notes-0.15.0.md
- routing/payment_lifecycle.go
- routing/router_test.go
When a terminal payment failure happens, in-flight shard failures were not handled cleanly due to the shard handler quitting prematurely. This PR attempts to fix this synchronization issue by making sure that we always wait for the Switch to report back network results for active shards. 
Details of how the bug happens:
1. multiple shards launched
2. one of the shards fails with a terminal failure => it'll also signal the shard handler to quit
3. in `collectResult()` we select on the shard handler's `quit` channel and return there
4. this may work out if the Switch was able to send all results in time, but sometimes we quit prematurely
5. this in turn may result in some htlc attempts that don't have their status set in the channel db
6. in the end the payment will have a final failure …
> routing: fail in-flight attempts cleanly on terminal payment failure

- docs/release-notes/release-notes-0.15.0.md
- lnrpc/signrpc/signer_server.go
- lntest/itest/lnd_taproot_test.go
- rpcserver.go
Fixes https://github.com/lightningnetwork/lnd/issues/6396.
Also fixes a value that wasn't copied to the RPC counterpart.
> signrpc: fix panic with missing UTXO information when signing Taproot output

- docs/release-notes/release-notes-0.15.0.md
- go.mod
- go.sum
Depends on https://github.com/btcsuite/btcwallet/pull/799.
Found while testing https://github.com/lightningnetwork/lnd/pull/6387.
Makes sure that P2TR addresses are being marked as used correctly.
> wallet: fix p2tr addresses not being marked as used

- contractcourt/channel_arbitrator.go
- contractcourt/htlc_incoming_contest_resolver.go
- contractcourt/htlc_incoming_resolver_test.go
- contractcourt/htlc_timeout_resolver_test.go
- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/interceptable_switch.go
- htlcswitch/mock.go
- intercepted_forward.go
- server.go
- witness_beacon.go
- witness_beacon_test.go
Adds interception functionality for the onchain resolution flow.
Fixes #6040
> contractcourt: onchain htlc interceptor

- .github/workflows/main.yml
- .github/workflows/release.yaml
- .travis.yml
- Dockerfile
- chainntnfs/bitcoindnotify/bitcoind_test.go
- discovery/gossiper_test.go
- discovery/syncer_test.go
- docs/INSTALL.md
- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/circuit_test.go
- lnrpc/routerrpc/router_backend_test.go
- make/builder.Dockerfile
In this PR, we update our build scripts to always use Go 1.18 which was released today. We also update the posted min Go version to 1.18, so we can use the new features packaged in this release sooner (the new fuzzing package, type params, etc).
> build: update to Go 1.18 

- docs/release-notes/release-notes-0.15.0.md
- feature/default_sets.go
- feature/deps.go
- feature/manager.go
- lnwire/features.go
- server.go
In this commit, we add the keysend feature bit to our NodeAnnouncement
if the accept-keysend option is set.
Fixes #5044 
Note that since many nodes out there currently support keysend without signalling for the feature bit, I think we should (for now at least) not require the optional feature bit before sending a keyspend payment to the peer. This mimics CL's behaviour too: https://github.com/ElementsProject/lightning/commit/8252ac5a6e1a382b6fd68b0fc429dd517c811889
When majority of nodes start announcing the bit, we can make this more strict in order to not unnecessarily lock up liquidity
> multi: announce Keysend feature bit

- docs/release-notes/release-notes-0.15.0.md
- go.mod
- go.sum
Fixes #6386.
Bumps the btcutil/psbt library to the latest version v1.1.3 that fixes
an issue with de-serializing a PSBT that contains an unsigned
transaction with no inputs.
> mod+docs: bump btcutil/psbt library to v1.1.3

- docs/release-notes/release-notes-0.15.0.md
- routing/chainview/interface_test.go
Depends on #6353.
Attempts to fix this flake in the postgres unit test:
```
--- FAIL: TestFilteredChainView (20.34s)
interface_test.go:943: Testing 'bitcoind_zmq' implementation of FilteredChainView
interface_test.go:943: Testing 'p2p_neutrino' implementation of FilteredChainView
interface_test.go:943: Testing 'btcd_websockets' implementation of FilteredChainView
--- FAIL: TestFilteredChainView/btcd_websockets:_filter_block_disconnected (9.53s)
interface_test.go:552: unable to set up mining node: connection timeout
FAIL
FAIL	github.com/lightningnetwork/lnd/routing/chainview	20.362s
FAIL
```
> chainview: fix unit test timeout

- docs/release-notes/release-notes-0.15.0.md
- tlv/go.mod
- tlv/go.sum
- tlv/primitive.go
- tlv/record.go
- tlv/stream_test.go
This PR introduces a new record type, via `MakeBigSizeRecord`, that takes a uint64 or uint32 and encodes it using `BigSize` format, which can save us extra bytes for certain fields.
> tlv: add new record type to encode `BigSize`

- config.go
- docs/release-notes/release-notes-0.15.0.md
- lncfg/address.go
- lntest/itest/lnd_network_test.go
- lntest/itest/lnd_test_list_on_test.go
- sample-lnd.conf
- server.go
Adds a new parameter to LND that makes a peer connection to a node on start up, similar to `--neutrino.addpeer`. The parameter takes an input of a node's connection string (`<pubkey>@<ip or onion>:<port>`) & when LND starts up it attempts make a peering connection to the node before any other connections.
> lnd: Adds addpeer flag

- cmd/lncli/main.go
- docs/release-notes/release-notes-0.15.0.md
_(This change was previously reviewed in PR https://github.com/lightningnetwork/lnd/pull/6279)_
This PR adds a `--socksproxy` option to `lncli` to allow for RPC calls via Tor. 
Example: `lncli --rpcserver=remoterpchost.onion:10009 --socksproxy=localhost:9050 --tlscertpath=/cert/path/tls.cert --macaroonpath=/macaroon/path/admin.macaroon fwdinghistory --start_time "-1h"`
I have tested the above example on two physically remote systems and was able to retrieve the forwarding history.
> #4939 Add socks proxy support to lncli

- config.go
- docs/release-notes/release-notes-0.15.0.md
- lncfg/bitcoind.go
- sample-lnd.conf
```
Currently, the Bitcoind.Dir configuration option is used as the base
directory for locating both the bitcoind configuration file and the RPC
cookie file. However, it is quite common for Bitcoin Core to be packaged
in such a way that the configuration file and the RPC cookie file reside
in different directories: "/etc/bitcoin/bitcoin.conf" and
"/var/lib/bitcoind/.cookie".
This change makes it such that --bitcoind.config and
--bitcoind.rpccookie options can be specified to override the default
auto-detection logic, and if either is unspecified, the auto-detection
logic will still do its job.
```
Fixes https://github.com/lightningnetwork/lnd/issues/4439
> config: Add bitcoind.{config,rpccookie} configuration options

- docs/release-notes/release-notes-0.15.0.md
- lnwallet/chancloser/chancloser.go
- peer/brontide.go
Fixes https://github.com/lightningnetwork/lnd/issues/4819
Fixes https://github.com/lightningnetwork/lnd/issues/6458
This is done by checking if a cooperative close transaction exists in the database and the channel has the CoopBroadcasted status flag. Most of it is actually a refactor to de-dupe some code. There is one downside to this change:
- If we go down after sending ClosingSigned and the counter-party receives it and broadcasts the coop close txn, on restart we will populate a `ChanCloser` and think we are in the negotiation phase. Even when the channel is fully closed on-chain, this will be the case until another peer disconnect + connect. This is benign, but not elegant.
Another thing I noticed that doesn't seem straightforward to fix given some interactions with the `server` …
> peer: allow restart during cooperative close

- contractcourt/channel_arbitrator.go
- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/circuit_map.go
- htlcswitch/circuit_map_test.go
- htlcswitch/circuit_test.go
- htlcswitch/resolution_store.go
- htlcswitch/resolution_store_test.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
- lntest/itest/lnd_res_handoff_test.go
- lntest/itest/lnd_test_list_on_test.go
This patch creates a store for `ResolutionMsg` that the `htlcswitch.Switch` receives from the `contractcourt.ChannelArbitrator` in a way that lnd going down (power loss, `SIGKILL`, anything else) at any point in the process should allow it to recover. If the `htlcswitch.ProcessContractResolution` hand-off fails for any reason, the caller (`contractcourt.ChannelArbitrator` or `contractcourt.htlcTimeoutResolver`) is notified of the error and will refuse to advance its state and will try again on another pass. On start-up the switch will cleanup the store by removing messages whose circuits have been deleted. This PR depends on https://github.com/lightningnetwork/lnd/pull/6214 to avoid deadlock on start-up but I have not included those commits. I will rebase after those changes are in. …
> htlcswitch+lntest: create resolutionStore to persist ResolutionMsg

- invoices/invoiceregistry.go
I found a typo in the comments which describes the function scanInvoicesOnStart in invoiceregistery.go
Not applicable
> fix typo comment for scanInvoicesOnStart function

- chainreg/chainregistry.go
- docs/release-notes/release-notes-0.15.0.md
Fixes #6333.
This pr reverse the changes in #5710. 
As is, lnd can not connect to a bitcoind node, through zmq, running inside a docker container.
#5710 was added as a safeguard against mixing up the port values of zmqpubrawtx and zmqpubrawblock, which would result in lnd not being notified of new transactions and/or blocks.
> zmq: remove port checker

- contractcourt/chain_arbitrator.go
- contractcourt/channel_arbitrator.go
- contractcourt/channel_arbitrator_test.go
- docs/release-notes/release-notes-0.15.0.md
An attempt to fix https://github.com/lightningnetwork/lnd/issues/6312
The main idea is that `NotifyContractUpdate` adds the `ContractUpdate` to a map `unmerged`. It is populated in `Start` by shallow-copying the `activeHTLCs` map values (`htlcSet`). The `htlcSet`s underlying maps are not copied, and so `unmerged` will just contain pointers to them. This should be fine since `unmerged` will not modify them. At the call-sites of `activeHTLCs`, it is updated to include the `unmerged` sets. This happens with a mutex and should not cause any data race, even though it is copying the underlying map pointers. No persistence should be necessary since on restart, `activeHTLCs` and `unmerged` will just be populated again.
Fixes https://github.com/lightningnetwork/lnd/issues/6312
> contractcourt: deadlock fix via temporary unmerged map

- channeldb/channel.go
- channeldb/doc.go
- channeldb/fees.go
- channeldb/migration/lnwire21/update_fail_htlc.go
- htlcswitch/link.go
- htlcswitch/mailbox.go
- lnwallet/channel.go
- lnwire/update_fail_htlc.go
Various documentation typo fixes, a simple code modification, and removal of two empty files
None
> Typo fixes and code cleanup

- docs/release-notes/release-notes-0.15.0.md
- lnwire/lnwire.go
- lnwire/lnwire_test.go
- lnwire/opaque_addrs.go
- lnwire/writer.go
Fixes #6432 
Ignore an address with an unknown type along with any addresses after it.
> lnwire: ignore unknown addresses in NodeAnnouncement

- .github/workflows/release.yaml
- docs/INSTALL.md
- docs/release-notes/release-notes-0.15.0.md
This adds a list of tags that can be used when building or installing
lnd from source. Links to relevant code, protobuf definitions, or
documentation are included to illustrate the purpose of each tag.
Closes #3598.
> docs/INSTALL.md: add list of build tags 

- docs/release-notes/release-notes-0.15.0.md
- lntest/harness_net.go
- lntest/itest/lnd_funding_test.go
- lntest/itest/lnd_test_list_on_test.go
- lnwallet/btcwallet/signer.go
- lnwallet/chanfunding/coin_select.go
- lnwallet/chanfunding/wallet_assembler.go
Fixes https://github.com/lightningnetwork/lnd/issues/6519 by properly detecting and supporting p2tr inputs in channel funding transactions.
> chanfunding: properly support p2tr inputs in funding TX

- .github/workflows/main.yml
- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/bitcoindnotify/bitcoind_test.go
- chainntnfs/bitcoindnotify/driver.go
- chainntnfs/test/bitcoind/bitcoind_test.go
- chainntnfs/test/test_interface.go
- chainntnfs/test_utils.go
- chainreg/chainregistry.go
- config.go
- docs/release-notes/release-notes-0.15.0.md
- go.mod
- go.sum
- lncfg/bitcoind.go
- lntest/bitcoind_common.go
- lntest/bitcoind_notxindex.go
- lntest/bitcoind_rpcpolling.go
- lnwallet/btcwallet/btcwallet.go
- lnwallet/test/bitcoind/bitcoind_test.go
- lnwallet/test/test_interface.go
- routing/chainview/interface_test.go
- sample-lnd.conf
replaces #6117 
Depends on https://github.com/btcsuite/btcwallet/pull/795
Thanks to @orbitalturtle for the original lnd and btcwallet PRs 🚀 
Note, this PR also adds a new itest backend.
> multi: bitcoind rpc polling option

- Makefile
- docs/release-notes/release-notes-0.15.0.md
- mobile/README.md
- mobile/gen_bindings.sh
Update the mobile build system to also properly expose all the sub-severs in a proper namespace.
Previously, only `autopilotrpc` was exposed.
Now we'll also expose:
- `chainrpc`
- `invoicesrpc`
- `peersrpc`
- `routerrpc`
- `signrpc`
- `verrpc`
- `walletrpc`
- `watchtowerrpc`
- `wtclientrpc`
TODO
> Mobile builds: expose main sub-servers by default

- channeldb/invoices.go
- docs/release-notes/release-notes-0.15.0.md
- invoices/invoiceregistry.go
- invoices/update.go
Noticed some things to tidy up here. The AMP copy is added to be consistent with the other invoice copying and can be used in a later PR to surface this information at the rpc layer.
> channeldb+invoices: refactor invoice logic when updating

- docs/release-notes/release-notes-0.15.0.md
- invoices/invoiceregistry.go
Prior to this change, if SubscribeSingleInvoice was called, it was possible that a state change would never be delivered to the client. The sequence of events would be:
- deliverSingleBacklogEvents called with invoice in Open state
- invoice goes to the Accepted state, no client to notify
- client added to map
This is fixed by adding the client to the map first. However, with this change it then becomes possible (though perhaps unlikely) that the client receives an Accepted and then an Open notification since the notifications occur in different goroutines. Whether this is an acceptable tradeoff is an Open question
Fixes https://github.com/lightningnetwork/lnd/issues/6475
> invoices: add client to map before delivering backlog notif

- aezeed/cipherseed.go
- aezeed/cipherseed_test.go
- aezeed/errors.go
- config_builder.go
- docs/release-notes/release-notes-0.15.0.md
- keychain/derivation.go
- walletunlocker/service.go
- walletunlocker/service_test.go
This PR bumps the internal derivation version of the seed from 0 to 1 to mark the introduction of Taproot derivation paths.
The new version doesn't actually do anything just yet, but can be used to optimize certain chain rescan scenarios in the future.
> aezeed+keychain: bump internal version of seed to 1

- invoices/update.go
Fixes https://github.com/lightningnetwork/lnd/issues/6436
Instead of setting the preimage to `inv.Terms.PaymentPreimage`, it is now set to `htlc.AMP.Preimage` if the former is nil. Also removed a redundant comparison since the `HTLCSet` logic already checks it.
> invoices: properly set Preimage field for success resolution

- lntest/itest/lnd_misc_test.go
- rpcserver.go
Fixes #6537.
NOTE: skipped the release note as it's fixing a merge that happened in the same release.
> rpcserver: fix wrong unit used in PushAmountSat

- config.go
- docs/release-notes/release-notes-0.15.0.md
Fixes #6516.
Returns an error message if bitcoind.rpccookie is defined but the corresponding cookie file is not found, while both bitcoind.rpcuser and bitcoind.rpcpassword is undefined.
> config: error msg for missing bitcoind cookie file

- config.go
- docs/release-notes/release-notes-0.15.0.md
Minor fix to how bitcoind.rpccookie and bitcoind.config are parsed from config file. Had issues with the tilde sign in a linux setup.
This applies to litecoind too.
> config: fix path to bitcoind/litecoind rpccookie and config

- channeldb/db.go
- docs/release-notes/release-notes-0.15.0.md
This can cause an intermittent panic otherwise if bbolt remaps itself
via munmap and mmap. From bbolt's documentation:
* Byte slices returned from Bolt are only valid during a transaction.
Once the transaction has been committed or rolled back then the memory
they point to can be reused by a new page or can be unmapped from
virtual memory and you'll see an unexpected fault address panic when
accessing it.
Happened in: https://github.com/lightningnetwork/lnd/runs/6462328626?check_suite_focus=true
<details>
<summary>Stack trace</summary>
<br>
```
test_harness.go:118: lnd finished with error (stderr):
exit status 2
unexpected fault address 0x7fee7997132d
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fee7997132d pc=0x1060fa7]
goroutine 3997 [running]: …
```
> channeldb: copy value from boltdb's Get instead of using it directly

- channeldb/channel.go
- channeldb/db.go
- channeldb/migration25/channel.go
- channeldb/migration25/migration.go
- channeldb/migration25/migration_test.go
- channeldb/migration26/channel.go
- channeldb/migration26/log.go
- channeldb/migration26/migration.go
- channeldb/migration26/migration_test.go
- channeldb/migration27/channel.go
- channeldb/migration27/log.go
- channeldb/migration27/migration.go
- channeldb/migration27/migration_test.go
- docs/release-notes/release-notes-0.15.0.md
This PR makes two changes,
1. use tlv to store the two balance fields.
2. patch empty balance values to historical channels. Since the revocation logs are removed when the channel is closed, it's not possible to find the balance info again. To avoid serialization/deserialization errors, we patch them with empty values. For historical channels after the revocation log PR, those fields should have the values again.
Fixes #6549 #6548
> channeldb: change balance fields to tlv records and migrate historical bucket

- channeldb/migration25/channel.go
- channeldb/migration26/channel.go
- channeldb/migration27/channel.go
- channeldb/migration27/migration_test.go
- docs/release-notes/release-notes-0.15.0.md
Fixes #6558.
Previously, in `migration25.OpenChannel`, there was a private field `chanStatus` used to keep track of the channel status. The following migrations, `migration26` and `migration27` also have their own `OpenChannel` defined, with `migration26` inherited from `migration25`, and `migration27` inherited from `migration26`. The private field `chanStatus`, however, is NOT inherited and each of the migrations uses its own. This is fine for reading and writing as, under the hood, the `chanStatus` is just a `uint8` value. Because each migration has its own fetcher and putter, it can safely access its private field to read and write it correctly.
The issue pops up when we use the method `migration25.FundingTxPresent()`. Because it's evaluating its channel status using its own private …
> multi: export channel status field in migration25

- docs/release-notes/release-notes-0.15.0.md
- htlcswitch/interfaces.go
- htlcswitch/link.go
- htlcswitch/linkfailure.go
- htlcswitch/mock.go
- htlcswitch/switch.go
- htlcswitch/switch_test.go
This allows Switch-initiated payments to be failed back if they don't
make it into a commitment. Prior to this commit, a Switch-initiated
HTLC could get "lost" meaning the circuit wouldn't get deleted except
if conditions were "right" and the network result store would never
be made aware of the HTLC's fate. Switch-initiated HTLC's are now
passed to the link's mailbox to ensure they can be failed back.
This change also special-cases the ErrDuplicateKeystone error from
OpenCircuits(...) so that callers of updateCommitTx() in the link
don't send an Error to the peer if they encounter the keystone error.
With the first async change, the keystone error should now always
be recoverable.
Fixes https://github.com/lightningnetwork/lnd/issues/6485
Fixes …
> htlcswitch: remove synchronous link handoff, special-case keystone err

- contractcourt/chain_arbitrator.go
This prevents a panic where an insert is attempted on a nil map via
updateActiveHTLCs. This panic would occur if the channel arbitrator
was in a buggy state, possibly introduced by power loss or via
SIGKILL.
Fixes https://github.com/lightningnetwork/lnd/issues/6585
> contractcourt: make empty htlcSets for closed channels

- channeldb/revocation_log_test.go
- docs/release-notes/release-notes-0.15.0.md
When testing serializing revocation log, we need to also copy its
`HTLCEntries` as the serialization of the HTLC involves a writing to the
`htlc.amtTlv` field.
The build,
```
Read at 0x000000eba590 by goroutine 169:
reflect.Value.Uint()
/opt/hostedtoolcache/go/1.18.2/x64/src/reflect/value.go:2506 +0xb0d
reflect.deepValueEqual()
/opt/hostedtoolcache/go/1.18.2/x64/src/reflect/deepequal.go:162 +0xa60
reflect.deepValueEqual()
/opt/hostedtoolcache/go/1.18.2/x64/src/reflect/deepequal.go:130 +0x209b
reflect.deepValueEqual()
/opt/hostedtoolcache/go/1.18.2/x64/src/reflect/deepequal.go:127 +0xf79
reflect.deepValueEqual()
/opt/hostedtoolcache/go/1.18.2/x64/src/reflect/deepequal.go:113 +0x1f35
reflect.deepValueEqual()
/opt/hostedtoolcache/go/1.18.2/x64/src/reflect/deepequal.go:130 …
```
> channeldb: fix data race in TestSerializeRevocationLog

- go.mod
- go.sum
This commit upgrades to the latest version of btcwallet that fixes an
issue that would cause us to not properly sign a validate populated PSBT
in certain scenarios.
Fixes https://github.com/lightningnetwork/lnd/issues/6579
> build: upgrade to latest version of btcwallet

- docs/release-notes/release-notes-0.15.0.md
- invoices/invoiceregistry.go
This PR fixes two deadlocks, both resulting from interaction between the invoice registry event loop and different internal data structures. Found while checking CI logs (https://github.com/lightningnetwork/lnd/runs/6659386315?check_suite_focus=true).
The deadlock in the first commit is presented below, the second one didn't manifest. It is not easy to reproduce as we need to fill up the `invoiceEvents` channel too.
```
goroutine 3483 [semacquire, 59 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0xa0?, 0x0?)
/opt/hostedtoolcache/go/1.18.2/x64/src/runtime/sema.go:71 +0x25
sync.(*RWMutex).RLock(...)
/opt/hostedtoolcache/go/1.18.2/x64/src/sync/rwmutex.go:63
github.com/lightningnetwork/lnd/invoices.(*InvoiceRegistry).copySingleClients(0xc0281da980) …
```
> invoices: fix deadlock in the invoice registry

- contractcourt/channel_arbitrator.go
- contractcourt/htlc_incoming_contest_resolver.go
- contractcourt/htlc_lease_resolver.go
- contractcourt/htlc_outgoing_contest_resolver.go
- contractcourt/htlc_success_resolver.go
- contractcourt/htlc_timeout_resolver.go
- docs/release-notes/release-notes-0.15.0.md
In this commit, we consolidate the _lease specific_ logic for the
success and timeout HTLC resolvers. We do this with the addition of a
new struct which is then composed via struct embedding with the two
existing structs. This fixes a flake in the integration tests by
ensuring the height is set up front, rather than eventually once the
height matches the lock time.
> contractcourt: unify the lease specific HTLC sweeping logic

- docs/release-notes/release-notes-0.15.0.md
- lnrpc/walletrpc/walletkit_server.go
Without this the RPC panics if UTXO information isn't specified. 
Fixes https://github.com/lightningnetwork/lnd/issues/6567
> lnrpc/walletrpc: reject PSBT packets w/o any UTXO input info

- lnrpc/walletrpc/walletkit_server.go
- lnwallet/rpcwallet/rpcwallet.go
- sweep/tx_input_set.go
Fixed three more occurrences of address type enums that didn't yet support P2TR inputs.
NOTE: I didn't add anything to the release notes since this should've been added by any of the previous P2TR pull requests.
> walletkit+sweeper: add forgotten P2TR address type

- cmd/lncli/commands.go
Looks like this was missed when p2tr support was added.
> Add p2tr to supported address help message

- autopilot/simple_graph.go
- docs/release-notes/release-notes-0.15.0.md
Fixes an `index out of range [0] with length 0` error when running `lncli getnetworkinfo` with an empty graph (on the remote signing instance for example).
> bugfix: avoid panic with empty graph

- cmd/lncli/cmd_payments.go
- docs/release-notes/release-notes-0.15.0.md
Fixes #6575 
In this PR, the `payment_addr` flag is added for the `buildroute` lncli command so that the mpp record doesnt need to be manually set.
1. Generate an invoice (should contain a payment address) at a destination.
2. Query a route to the destination and use this to construct a route using `buildroute`. Use the payment_addr field here.
3. now use `sendtoroute` to send to the above route.
4. if the payment_addr field was _not_ specified in step 2 then step 3 will fail with `incorrect payment details` and if the `payment_addr` field _is_ specified in step 2 (along with the correct amt flag), then the payment should succeed
> lncli: add payment-addr flag to buildroute 

- channeldb/revocation_log_test.go
- docs/release-notes/release-notes-0.15.1.md
> channeldb: fix data race in TestSerializeHTLCEntries

- docs/release-notes/release-notes-0.15.1.md
- go.mod
- go.sum
Fixes: https://github.com/lightningnetwork/lnd/issues/6674
This PR updates the urfave/cli package to v.1.22.9 to avoid a flag parsing bug.
> dep: update urfave/cli package

- .gitignore
- docs/release-notes/release-notes-0.15.1.md
Fixes #6672.
A new metadata tag called `build.vcs.modified` was added in Go 1.18.x that
indicates whether there were any untracked files present during the
build or not.
Because the `make release` command creates a directory in which the
output packages are created, and because that directory was not added
to git and also not ignored by it, the build.vcs.modified flag was
different to the docker build which resulted in a different digest of
the resulting binary.
> Fix release reproducibility

- docs/release-notes/release-notes-0.15.1.md
- lntest/itest/lnd_switch_test.go
- server.go
Without this, calls to DisconnectPeer would bypass the peerTerminationWatcher and allow subsequent connect requests to go through before the peer's links were fully shut down. This could lead to force closes.
One way it could trigger a force close that made it _look_ like the user lost state is:
- The existing link has sent a `CommitSig` and is waiting for `RevokeAndAck`. The database state is persisted under the commit diff key
- The node's `peer.Brontide` object receives the `RevokeAndAck` and will attempt to pass it to the link.
- The node issues a `DisconnectPeer` call. `removePeer` is called which removes the `peer.Brontide` object from the map without waiting for the associated `ChannelLink`s to stop. This bypasses the `peerTerminationWatcher`!
- The node hands the `RevokeAndAck` to …
> server.go: replace call to removePeer with Disconnect in DisconnectPeer

- docs/release-notes/release-notes-0.15.1.md
- input/signer.go
- lnrpc/signrpc/signer.proto
- lnrpc/signrpc/signer.swagger.json
- lnrpc/signrpc/signer_grpc.pb.go
- lnrpc/signrpc/signer_server.go
- lntest/itest/lnd_remote_signer_test.go
- lntest/itest/lnd_taproot_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/6678 by correctly using the `PrevOutputs` parameter.
> Taproot: Fix p2tr support in `ComputeInputScript`

- docs/release-notes/release-notes-0.16.0.md
- htlcswitch/link.go
- lnwire/lnwire_test.go
- lnwire/message.go
- lnwire/warning.go
- peer/brontide.go
This PR updates LND to recognize [warning messages](https://github.com/lightning/bolts/blob/master/01-messaging.md#the-error-and-warning-messages) and log them when they are received from peers. 
This PR does not update LND to _send_ warnings itself, that will be done in a follow up. The benefit of this PR in isolation is that it will clear the "unknown message" logs that nodes see when they receive warnings from implementations that do send them. 
Partially addresses #5602. 
* Run two LND nodes and open a channel between them: 
* `Alice` - running the code in this PR
* `Bob` - running [testing code](https://github.com/carlaKC/lnd/tree/test-950-warningmessages) which sends an error every 5 seconds
* Observe that Alice logs warnings: `Received Warning(chan_id=000...00000, err=test {x}) …
> lnwire/peer: add ability to read + log peer warning messages

- docs/release-notes/release-notes-0.15.1.md
- htlcswitch/switch.go
With this, extra calls to RemoveLink will wait for the link to
fully stop. This is accomplished by a map that stores a single stop
channel that callers to RemoveLink will listen on. This map is not
consulted when the Switch is shutting down and calls Stop on each
individual link. Though that could be added in the future, it is
not necessary.
Fixes #6593
> htlcswitch: add linkStopIndex to cleanly shutdown ChannelLink

- docs/release-notes/release-notes-0.15.0.md
- docs/release-notes/release-notes-0.15.1.md
Fixes a few things in the 0.15.0 and 0.15.1 release notes.
> Release notes: Move 0.15.1 item, remove duplicate headings, fix formatting

- channeldb/db.go
- channeldb/options.go
- channeldb/payment_control.go
- channeldb/payment_control_test.go
- config.go
- config_builder.go
- docs/release-notes/release-notes-0.15.1.md
- routing/control_tower.go
- routing/control_tower_test.go
- routing/mock_test.go
- routing/payment_lifecycle.go
- routing/router_test.go
- sample-lnd.conf
Fixes #6318
Failed payment attempts are deleted from channel.db for successfully settled payments, unless the `keep-failed-payment-attempts` flag is specified in configuration.
Summarizing part of the discussion below:
We only want to delete failed attempts for _settled_ payments. If we were to delete failed attempts for failed payments, that would leave all failed payments as empty shells, so we might as well delete the whole payment. This might be a nice optional feature to have, but should be handled in a separate PR (if at all). And we don't want to delete failed attempts for inflight payments since inflight payments could end up failing.
> Delete failed payment attempts for successfully settled payments

- docs/release-notes/release-notes-0.15.1.md
- peer/brontide.go
- peer/brontide_test.go
Fixes #6589
This adds the peer's pubkey as a prefix to most log messages in "brontide.go". One example that is improved by this:
BEFORE:
```
[INF] CHCL: ChannelPoint(123:1): computing fee compromise, ideal=284, last_sent=804, remote_offer=1327
[ERR] PEER: unable to process close msg: couldn't find compromise fee
```
AFTER (where abc is the peer's pubkey):
```
[INF] CHCL: ChannelPoint(123:1): computing fee compromise, ideal=284, last_sent=804, remote_offer=1327
[ERR] PEER: Peer(abc): unable to process close msg: couldn't find compromise fee
```
> peer: add pubkey to log messages

- blockcache/blockcache_test.go
- channeldb/payment_control_test.go
- clock/test_clock_test.go
- docs/release-notes/release-notes-0.15.1.md
- peer/brontide_test.go
Migrate instances of `assert.NoError` to `require.NoError`. There are several thousand instances of the latter version in the codebase, but only a handful of the former. This change makes the calls consistent by always using `require`.
> Migrate assert.NoError to require.NoError

- cmd/lncli/cmd_open_channel.go
This corrects the help text described in #6697
> Fix batchopenchannel help text

- .editorconfig
- .vscode/settings.json
- docs/code_contribution_guidelines.md
- docs/code_formatting_rules.md
- docs/release-notes/release-notes-0.15.1.md
- routing/payment_lifecycle.go
Instructs the most common graphical editors to use 8 spaces for the tab character and to show a vertical ruler at 80 characters.
This should help beginners to not fall into the `nit: line too long` trap with their first contribution.
> Add settings files for most common editors

- config_builder.go
- docs/release-notes/release-notes-0.16.0.md
- macaroons/service.go
- macaroons/service_test.go
- walletunlocker/service.go
In this commit, we modify the `macaroons.NewService` consturctor to
accept the main interface rather than the raw DB. This allows us to use
other backends other than bolt or the kvdb interface to store the
macaroon root keys.
We also create a new ExtendedRootKeyStore interface that implements some
of the more advanced features we use such as macaroon encryption and
password rotation.
> macaroons: futher abstract NewService from root key store impl

- docs/release-notes/release-notes-0.15.1.md
- rpcperms/interceptor.go
In this commit, we let the registered middleware interceptors be stored
in a slice rather than a map so that the order in which the interceptors
are executed is guarenteed to be the same as the order in which they
were registered.
> rpcperms: guarantee execution order of interceptors

- docs/release-notes/release-notes-0.15.1.md
- lntest/harness_node.go
In this commit, we fix a detected flake: we go to make a payment, and
then want to assert that 2 attempts we required. The existing logic
assumes that the success and the payment will still be on disk. With a
recent PR, we now delete failed payments by default, but after the fact,
in a non-atomic fashion.
We fix this issue simply by having all the nodes keep around failed
payments for the sake of all the old itests that assumed this
information would always be on disk.
Introduced in: https://github.com/lightningnetwork/lnd/pull/6438.
Fixes https://github.com/lightningnetwork/lnd/issues/6711.
> lntest: keep all failed payments by default for HarnessNode

- docs/release-notes/release-notes-0.15.1.md
- lntest/itest/lnd_psbt_test.go
- lnwallet/btcwallet/btcwallet.go
With a change in #6379 we made sure that all default scopes are added to
the the wallet. Unfortunately this included the BIP044 key scope that
our wallet doesn't really use. This breaks the remote signing setup
because we don't export the account of the BIP044 scope and therefore
run into an issue on the watch-only side when attempting to create the
wallet.
> lnwallet: don't create BIP044 key scope by default

- cmd/lncli/commands.go
- docs/release-notes/release-notes-0.15.1.md
This PR adds a `--chan_point` option to `lncli abandonchannel` in the same fashion that it was added for `lncli updatechanpolicy` which was addressed here: https://github.com/lightningnetwork/lnd/issues/6699
> lncli: chan_point option for abandonchannel

- docs/release-notes/release-notes-0.15.1.md
- rpcperms/interceptor.go
After removing a registered middleware from the slice, we need to update
the index lookup map with the updated index for each middleware.
> rpcperms: re-init mw lookup map after removal of one

- docs/release-notes/release-notes-0.15.1.md
- lntest/itest/lnd_psbt_test.go
Ensure the wallet has synced the blockchain before attempting to spend
funds.
Prior to this fix, I get the following error:
```
rpc error: code = Unknown desc = wallet couldn't fund PSBT: error
creating funding TX: insufficient funds available to construct
transaction
```
> itest: fix sign_psbt failure

- docs/INSTALL.md
Change go version from v1.17.1 to v1.18 to armv6 section in INSTALL.md to use the same go version throughout the document.
> fix: go version in ARMv6 section of INSTALL.md

- lnrpc/invoicesrpc/invoices.swagger.json
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
This documents how to deal with `settled` being deprecated. It took me quite a bit of digging without such documentation.
> doc: Deprecation reason of `settled` on `Invoice`

- config.go
- docs/release-notes/release-notes-0.15.1.md
Fixes #6613. The bitcoind `.cookie` file contains an auto generated user (`__cookie__`) and password (random string), which can be used instead of the rpc user name and password. This commit allows for running against bitcoind without having to access `bitcoin.conf` like in the case for pure user/password/zmq configuration.
Note that here we check explicitly that rpc password/user is not set at the same time with the cookie path (could break some malconfigured setups, previously that was allowed because one took precedence over the other).
The path for the bitcoind cookie file can be specified with `rpccookiefile` (see #6613).
> config: allow independent rpccookie config

- docs/release-notes/release-notes-0.15.1.md
- feature/deps.go
The [spec](https://github.com/lightning/bolts/blob/master/09-features.md) does not specify a dependency between `ScidAliasOptional` (47) and`ExplicitChannelTypeOptional` (45).
This bug lead to some connectivity issues with peers not setting the 45 feature bit while setting the 47. The issue [6802](https://github.com/lightningnetwork/lnd/issues/6802) is an example of this.
Fixes [#6802](https://github.com/lightningnetwork/lnd/issues/6802)
> Remove `ScidAliasOptional` feature dependency on `ExplicitChannelTypeOptional`

- chainreg/chainregistry.go
- chainreg/taproot_check.go
- docs/release-notes/release-notes-0.15.1.md
In this commit, we add a check during normal node construction to see if
the backend node supports Taproot. If it doesn't, then we want to
shutdown and force the user to take note.
To check if the node supports Taproot, we'll first try the normal
getblockchaininfo call. If this works, cool, then we can rely on the
value. If it doesn't, then we'll fall back to the getdeploymentinfo call
which was added in a recent version of bitcoind [1]. Newer versions of
bitcoind might also have this call, and the getblockchaininfo call, but
not actually populate the softforks field [2]. In this case, we'll fall
back, and we also account for the case when the getblockchaininfo RPC is
removed all together.
[1]: https://github.com/bitcoin/bitcoin/pull/23508
[2]: …
> chainreg: shutdown if backend node doesn't support taproot

- docs/release-notes/release-notes-0.15.1.md
- lntest/itest/lnd_nonstd_sweep_test.go
- lntest/itest/lnd_test_list_on_test.go
- sweep/sweeper_test.go
- sweep/txgenerator.go
- sweep/txgenerator_test.go
- sweep/weight_estimator.go
With this change, transactions created via craftSweepTx will be
standard. Previously, p2wsh scripts passed in via SendCoins would
be weighted as p2wpkh scripts. With a feerate of 1 sat/vbyte,
transactions returned would be non-standard. Luckily, the critical
sweeper subsystem only used p2wpkh scripts so this only affected
callers from the rpcserver.
Fixes #6747
> sweep: account for all script types in craftSweepTx

- docs/release-notes/release-notes-0.15.1.md
- feature/default_sets.go
- feature/manager.go
- funding/manager.go
- funding/manager_test.go
- lncfg/protocol.go
- lncfg/protocol_rpctest.go
- lntest/itest/lnd_taproot_test.go
- lntest/itest/lnd_test_list_on_test.go
- lnwallet/chancloser/chancloser.go
- lnwallet/chancloser/chancloser_test.go
- lnwallet/wallet.go
- lnwire/features.go
- peer/brontide.go
- peer/brontide_test.go
- peer/test_utils.go
- sample-lnd.conf
- server.go
In this commit, we implement the new `option_any_segwit` feature bit which enables us to start sending P2TR addresses for co-op closes as well as for upfront shutdown addresses. Along the way, we tighten up our validation a bit to only allow segwit v0 and v1 addresses.
> multi: send P2TR addrs by default for co-op close, add new `option_any_segwit` feature bit

- contractcourt/breacharbiter.go
- docs/release-notes/release-notes-0.15.1.md
- lnd.go
- lnwallet/chanfunding/coin_select.go
- lnwallet/chanfunding/coin_select_test.go
- lnwallet/chanfunding/wallet_assembler.go
- lnwallet/test/test_interface.go
- lnwallet/wallet.go
- rpcserver.go
- server.go
- sweep/tx_input_set.go
- sweep/txgenerator.go
- watchtower/lookout/justice_descriptor.go
- watchtower/wtclient/backup_task.go
- watchtower/wtclient/backup_task_internal_test.go
- watchtower/wtclient/client_test.go
- watchtower/wtpolicy/policy.go
- watchtower/wtserver/server_test.go
With this PR, we'll start to use taproot addresses by default when: sweeping all funds from the wallet, funding channels, and sending blobs to watch towers. 
Fixes https://github.com/lightningnetwork/lnd/issues/6666
> multi: use taproot errwhere applicable for change/delivery/tower addresses

- docs/release-notes/release-notes-0.15.1.md
- funding/manager.go
- funding/manager_test.go
This is required by BOLT#07 as otherwise the counter-party will
discard the channel_update as they may not consider the channel
"ready" or reorg-safe. Most other implementations besides eclair
have work-arounds for this, but it is nice to be spec-compliant.
Fixes https://github.com/lightningnetwork/lnd/issues/3651
> funding: defer sending channel_update until received funding_locked

- chainreg/taproot_check.go
- docs/release-notes/release-notes-0.15.1.md
Bitcoind 23 will use the new `getdeploymentinfo` while versions after 19
(but below 23) will use the `UnifiedSoftForks` field instead of the
`SoftForks UnifiedSoftForks` field.
With this PR the taproot gating logic has been tested on bitcoind
versions: 21, 22, and 23. 21 is when the taproot logic was first added.
> chainreg: update tapoort node awareness to account for bitcoind 19+

- build/version.go
We forgot to do this after 0.15 was tagged, but usually we use a x.99
version to indicate that the commits in master are between releases.
This might also make it easier to help identify exactly which version a
user is running in issue reports.
[skip-ci]
> build: bump version to v0.15.99

- cmd/lncli/commands.go
- cmd/lncli/main.go
- cmd/lncli/profile.go
- docs/release-notes/release-notes-0.16.0.md
This PR makes 3 changes (1 per commit):
1. Add a new `metadata` string slice global flag to lncli. This allows the caller to specify key-value string pairs to append to the outgoing grpc call's context. 
2. Add an `insecure` flag to lncli that skips TLS auth when connection to the target rpc server.
3. Change the bitsize used in lncli to parse an output index from 32 to 64 in order to allow for values that would be valid given the types used in lnrpc protos for output index (uint32 and int64).
> cmd/lncli: add metadata and insecure flags

- docs/release-notes/release-notes-0.16.0.md
- tor/controller.go
- tor/controller_test.go
Replies may contain quoted values that include spaces, newlines and/or escaped characters (including doublequote itself). Not accounting for that leads to errors when e. g. `COOKIEFILE` path contains spaces.
https://github.com/lightningnetwork/lnd/issues/1697#issuecomment-487238128
- Configure Tor to store the cookie in a directory path to which contains spaces
- Run the current version, it'll crash
- Build the package with this patch applied, it'll run successfully
> tor: fix parsing replies

- .github/workflows/main.yml
See more on [using concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency).
This PR uses `concurrency` to run a single job at a time. Intentionally left out a release note since it's small but also want to see the results.
Tested with a force push with the current PR and the [previous workflow](https://github.com/lightningnetwork/lnd/actions/runs/2877861206) was canceled by the push.
> github: cancel concurrent workflows for the same PR/push

- cmd/lncli/walletrpc_active.go
- docs/release-notes/release-notes-0.16.0.md
- lnrpc/walletrpc/walletkit.pb.go
- lnrpc/walletrpc/walletkit.pb.gw.go
- lnrpc/walletrpc/walletkit.pb.json.go
- lnrpc/walletrpc/walletkit.proto
- lnrpc/walletrpc/walletkit.swagger.json
- lnrpc/walletrpc/walletkit.yaml
- lnrpc/walletrpc/walletkit_grpc.pb.go
- lnrpc/walletrpc/walletkit_server.go
- lntest/itest/lnd_misc_test.go
- lntest/itest/lnd_test_list_on_test.go
- lntest/itest/utils.go
- lntest/mock/walletcontroller.go
- lnwallet/btcwallet/btcwallet.go
- lnwallet/interface.go
Related: #2498 
Command: `lncli wallet addresses list --account_name "default"`
> lnrpc+lnwallet: adds listaddresses RPC

- docs/release-notes/release-notes-0.16.0.md
- go.mod
- go.sum
After merging #6829 and pushing a new tag, we now need to use that new version to make use of the bug fixed.
> mod: bump tor to v1.0.2

- docs/release-notes/release-notes-0.15.1.md
- rpcserver.go
This commit adds a default case to the address type switch statement in
the NewAddress rpc server function. This catches any invalid address
types and returns an error.
Fixex https://github.com/lightningnetwork/lnd/issues/6846
> rpcserver+docs: add default case to addr type switch

- clock/test_clock_test.go
Introduced from [this commit](https://github.com/lightningnetwork/lnd/commit/834756c53c9399855b9ae17583f598cb9a3645c4), the package is missing importing `require`. Weird it's not caught by our build process.
> clock: add missing package `require`

- build/version.go
- docs/release-notes/release-notes-0.15.1.md
- rpcserver.go
This PR is a staging ground for the second release candidate for 0.15.1. So far we have just one bug fix, but another potential candidate is including https://github.com/btcsuite/btcd/pull/1876 as that fixes a long standing issue w.r.t resolving IPv6 addresses over Tor.
> release: create v0.15.1-rc2 release branch

- cmd/lncli/cmd_payments.go
- docs/release-notes/release-notes-0.16.0.md
Payment address isn't parsed correctly from the unnamed args. This makes it impossible to use the unnamed format with `lncli sendpayment`.
> lncli: fix sendpayment arg parsing

- cmd/lncli/cmd_profile.go
- docs/release-notes/release-notes-0.16.0.md
If `lncli profile remove` is called when there are no existing profiles,
it will cause a "cap out of range" panic. So in this commit, a length
check is added to avoid this.
> cmd+docs: fix cap out of range error in profile command

- docs/release-notes/release-notes-0.16.0.md
- tor/cmd_onion.go
- tor/cmd_onion_test.go
- tor/onionaddr.go
This PR lays the groundwork for #6500, which adds the ability to encrypt a Tor private key on disk. We originally had this all in one PR, but needed to split out this refactoring up because changes to the Tor module need to be added in another PR. 
Summary of Changes:
- Lays groundwork in Tor package for encrypting private key
> Update Tor module to add option to encrypt Tor key

- .travis.yml
Golang uses semver `X.Y.Z` but when `Z` is zero it gets dropped from the
version. Ex: `1.18`, `1.19` instead of `1.18.0` and `1.19.0`.
P.S: I don't think this deserves being added to a release note.
> ci: fix go version for travis jobs

- sample-lnd.conf
Change formatting of `bitcoin.node` configuration, add warning about changing BETWEEN chain back-ends
Replaces #6335 which already has 2 reviews, so going to merge right away.
> sample-conf: Chain backend documentation reformat, add warning [skip ci]

- docs/release-notes/release-notes-0.16.0.md
- tlv/stream.go
- tlv/stream_test.go
- tlv/tlv_test.go
Changes the `tlv` package such that:
- `Decode` can decode records > 65535 bytes
- `DecodeWithParsedTypes` can decode records > 65535 bytes
- Introduces `DecodeP2P` which cannot decode records > 65535 bytes
- Introduces `DecodeWithParsedTypesP2P` which cannot decode records > 65535 bytes
This is necessary for future changes to lnd and for other projects that want larger record sizes. Untrusted input should _always_ use the `*P2P` variants
> tlv: allow tlv streams to use large records

- docs/release-notes/release-notes-0.15.2.md
- lnrpc/lightning.pb.gw.go
- lnrpc/lightning.swagger.json
- lnrpc/lightning.yaml
Lists with non-primitive members aren't supported in the query string of a GET request with the current version of the `grpc-gateway` library. To allow route_hints to be set through REST, we also offer a POST endpoint for that call where the encoding of the request parameter can be specified as JSON.
Fixes https://github.com/lightningnetwork/lnd/issues/6752.
> lnrpc: add additional REST binding for QueryRoutes

- docs/release-notes/release-notes-0.15.2.md
- server.go
This fixes a bug where a caller would:
- call NotifyWhenOnline and pass in a channel
- the server's mutex is held and the pubStr is checked in peersByPub
- the peer object is in the peersByPub map
- the peer object has its quit channel closed
- QuitSignal is called in the select statement, and the function returns
- the caller is still waiting for the channel to be sent on forever since it was never sent on or added to the peerConnectedListeners slice.
This patch fixes the above bug by adding the channel to the peerConnectedListeners slice if the QuitSignal select case is called.
Fixes #6882 
An integration test that makes the bug pop up once in a while is here: https://github.com/Crypt-iQ/lnd/tree/iss6882_notifywhenonline
- The bug has occurred when there is a "peer quit signal" log soon …
> server.go: add peerChan to peerConnectedListeners in NotifyWhenOnline

- lnrpc/stateservice.pb.go
- lnrpc/stateservice.proto
- lnrpc/stateservice.swagger.json
Only `SERVER_ACTIVE` had a description, I copied these descriptions from 
https://github.com/lightningnetwork/lnd/blob/2b1bb3bce041973c03e6139ce7fec47f87cfb30a/cmd/lncli/cmd_state.go#L21
> Add comments for all wallet states

- docs/release-notes/release-notes-0.16.0.md
- rpcserver.go
In this commit, we catch and error on the specific case where an openchannel request has a zero-value local funding amount. This is just to ensure that the error message returned makes more sense.
Fixes https://github.com/lightningnetwork/lnd/issues/6943
> rpcserver: error on zero local balance in openchan req

- chanbackup/backupfile_test.go
- chanbackup/crypto.go
- chanbackup/multi.go
- chanbackup/multi_test.go
- chanbackup/pubsub_test.go
- chanbackup/recover_test.go
- chanbackup/single.go
- chanbackup/single_test.go
- docs/configuring_tor.md
- docs/release-notes/release-notes-0.16.0.md
- go.mod
- go.sum
- keychain/derivation.go
- lncfg/tor.go
- lnd.go
- lnencrypt/crypto.go
- lnencrypt/crypto_test.go
- lnencrypt/test_utils.go
- sample-lnd.conf
- server.go
- watchtower/config.go
- watchtower/standalone.go
This PR replaces #4458. Since I've been making some of the changes for @gkrizek and it's been a bit tricky to manage making PRs into his PRs... we thought it would be nice to have a fresh start. :)
Depends on #6526 
Graham's original PR description:
It's possible that a user might not want the Tor private key to sit on the disk in plaintext (it is a private key after all). So this commit adds a new flag to encrypt the Tor private key on disk using the wallet's seed. When the --tor.encryptkey flag is used, LND will still write the Tor key to the same file, however it will now be encrypted instead of plaintext. This essentially uses the same method to encrypt the Tor private key as is used to encrypt the Static Channel Backup file.
Summary of Changes:
- Moves the crypto.go file from …
> [tor] Add ability to encrypt the Tor private key on disk

- docs/release-notes/release-notes-0.16.0.md
- htlcswitch/mock.go
- htlcswitch/switch.go
- server.go
Previously, the Switch would not check waiting-close channels' fwdpkgs
for settles or fails to reforward. This could result in a force close
in a rare edge case if a restart occurred at the wrong time. Now,
waiting-close fwdpkgs are checked and the issue is avoided.
> server+htlcswitch: check waiting-close fwdpkgs in reforwardResponses

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
With this PR we configure GitHub to show a new "triage" page when the user clicks the "New Issue" button in the repository·
That page will show the following choices:
- "Bug report": Create a new issue with today's issue template, the `[bug]: ` title prefix and `bug, triage` labels applied.
- "Feature request": Create a new issue with a new template, the `[feature]: ` title prefix and `enhancement` label applied.
- "Discussions": Link to https://github.com/lightningnetwork/lnd/discussions
- "Documentation for lnd and lightning-terminal": Link to https://docs.lightning.engineering/
- "Lightning Community Slack": Link to https://lightning.engineering/slack.html
- "Security issue disclosure policy": Link to https://github.com/lightningnetwork/lnd#security
An example for such a triage page …
> GitHub: show issue triage page when submitting an issue

- cmd/lncli/walletrpc_active.go
- docs/release-notes/release-notes-0.15.0.md
- docs/release-notes/release-notes-0.15.1.md
- docs/release-notes/release-notes-0.15.2.md
- docs/remote-signing.md
Fixes the `lncli wallet accounts import` command to accept the address type `p2tr` which is required in order to upgrade a remote signing setup to `lnd v0.15.x-beta`.
We also add an instruction on how to upgrade such a setup to the latest `lnd` release.
If you were running a remote signing setup with `lnd v0.14.x-beta` and want to
upgrade to `lnd v0.15.x-beta`, you need to manually import the newly added
Taproot account to the watch-only node, otherwise you will encounter errors such
as `account 0 not found` when doing on-chain operations that require creating
(change) P2TR addresses.
**NOTE**: For this to work, you need to upgrade to at least `lnd v0.15.2-beta`
or later!
The upgrade process should look like this:
1. Upgrade the "signer" node to `lnd v0.15.x-beta` and unlock it.
2. Run …
> lncli+docs: fix and document remote signing setup upgrade to lnd v0.15.2-beta

- .github/workflows/stats.yml
In this PR, we introduce a new Github work flow tool that should help us keep better track fo reviewer load across the proejct. Ideally this can also be used as a tool to help new PRs find a reviewer, and also for us to better balance out review load, and keep track of how long it takes to do PR turnaround.
Trying to push directly to the repo now which might actually trigger the build properly?
> build: add PR stats to github workflow

- docs/release-notes/release-notes-0.15.2.md
- funding/manager.go
This is so that if the funding transaction hasn't been confirmed in 2016 blocks, the channel isn't marked as closed by the responder.
> funding: ignore maxWaitNumBlocksFundingConf for zero conf channels

- sample-lnd.conf
Documentation clarification
`bitcoin.rpcpolling` has to be set to true, otherwise `malformed key=value (bitcoind.rpcpolling)` error happens during initialization, not explicitly stated right now.
> Clarification sample-lnd.conf

- docs/release-notes/release-notes-0.15.2.md
- docs/release-notes/release-notes-0.15.3.md
- go.mod
- go.sum
Fixes https://github.com/lightningnetwork/lnd/issues/7002
> build: update to version of btcd with wire parsing bug fix

- docs/release-notes/release-notes-0.15.3.md
- lntest/itest/lnd_wallet_import_test.go
- lnwallet/chancloser/chancloser.go
- lnwallet/chancloser/chancloser_test.go
- lnwallet/channel.go
- peer/brontide.go
In this commit, we modify the way we compute the starting ideal fee for the co-op close transaction. Before this commit, channel.CalcFee was used, which'll compute the fee based on the commitment transaction itself, rathern than the co-op close transaction. As the co-op close transaction is potentailly bigger (two P2TR outputs) than the commitment transaction, this can cause us to under estimate the fee, which can result in the fee rate being too low to propagate.
To remedy this, we now compute a fee estimate from scratch, based on the delivery fees of the two parties.
Fixes #6953
> lnwallet/chancloser: properly compute initial fee of cop close txn

- build/version.go
- go.mod
- go.sum
This branch builds directly on top of v0.14.3.
> release: create v0.14.4 branch to back port block parsing bug fix 

- .github/workflows/main.yml
- .github/workflows/release.yaml
- .travis.yml
- Dockerfile
- dev.Dockerfile
- docker/btcd/Dockerfile
- docker/ltcd/Dockerfile
- docs/release-notes/release-notes-0.16.0.md
- lnrpc/Dockerfile
- make/builder.Dockerfile
- tools/Dockerfile
This PR bumps all Golang versions in our docker and CI files to v1.19.2 which aims to fix https://github.com/lightningnetwork/lnd/issues/6923.
> build: bump Golang version to v1.19.2

- docs/release-notes/release-notes-0.16.0.md
- htlcswitch/circuit_test.go
- htlcswitch/link_test.go
- htlcswitch/mock.go
- htlcswitch/payment_result_test.go
- htlcswitch/switch_test.go
Hi there, first time contributor :wave: 
Fixes #6707 
The htlcswitch tests were creating temporary database files but failing to close them or remove them.
We fix this by making it obvious when temporary db files are created, and cleaning up those resources where necessary in the tests.
```
go test -tags dev ./htlcswitch
```
Afterwords, confirmed in `/tmp` that no temporary files were left behind by the test suite.
> htlcswitch: clean up test resources and temporary files

- channeldb/db.go
- channeldb/meta.go
- channeldb/meta_test.go
- docs/release-notes/release-notes-0.16.0.md
- kvdb/etcd/bucket.go
- kvdb/etcd/bucket_test.go
- kvdb/etcd/db.go
- kvdb/etcd/db_test.go
- kvdb/etcd/fixture.go
- kvdb/etcd/readwrite_bucket.go
- lncfg/db.go
EDIT: The main migration tool has moved to https://github.com/lightninglabs/lndinit/pull/21 (still not ready for production/mainnet use!)
The code in this PR is now purely a refactor to allow `lndinit` to access the required library code.
> kvdb: refactor as preparation for DB migration command in lndinit

- docs/release-notes/release-notes-0.16.0.md
- watchtower/wtclient/client.go
- watchtower/wtclient/interface.go
- watchtower/wtdb/client_db.go
- watchtower/wtdb/client_db_test.go
- watchtower/wtdb/codec_test.go
- watchtower/wtdb/log.go
- watchtower/wtdb/migration1/client_db.go
- watchtower/wtdb/migration1/client_db_test.go
- watchtower/wtdb/migration1/codec.go
- watchtower/wtdb/migration1/log.go
- watchtower/wtdb/tower_db_test.go
- watchtower/wtdb/version.go
- watchtower/wtmock/client_db.go
This PR does a couple of things: 
1. Adds a new towerID-to-sessionID index (along with a migration function for building this index) to the watchtower client DB. This will greatly improve the lookup time of tower sessions. 
2. Add tighter coupling between ClientSessions and Towers by:
- Failing the creation of a new ClientSession if the TowerID it refers to does not correspond with a known tower in the DB
- Always populating the Tower member of a ClientSession when fetching a session from the DB
3. Improve the efficiency of the client's `New` function by making use of the new index and also by _first_ listing all towers and _then_ only listing the sessions for each of the towers. This allow the users running into issue #6101 to start LND. For more info please see [the …
> watchtower: add towerID-to-sessionID index

- docs/release-notes/release-notes-0.16.0.md
- lnrpc/wtclientrpc/wtclient.go
- watchtower/wtclient/client.go
- watchtower/wtclient/interface.go
- watchtower/wtclient/session_queue.go
- watchtower/wtdb/client_db.go
- watchtower/wtdb/client_db_test.go
- watchtower/wtdb/client_session.go
- watchtower/wtmock/client_db.go
In this PR, the `AckedUpdates` and `CommittedUpdate` fields are removed from `ClientSession` so that these are not populated each time we fetch a `ClientSession` from the DB. Instead, we now provide the caller with some functional options that they can use to pass in their own callback functions to act on the session's `AckedUpdates` and `CommittedUpdates`. 
Fixes https://github.com/lightningnetwork/lnd/issues/6660
Shout-out to @C-Otto for the [PoC PR](https://github.com/lightningnetwork/lnd/pull/6885) that got the momentum going 🙏
> multi: remove AckedUpdates & CommittedUpdates from ClientSession struct

- Makefile
- build/version.go
- docs/release-notes/release-notes-0.16.0.md
Since `go1.18` the runtime has a package that provides information about module versions, version control information, and build flags embedded in executable files built by the go command.
The new packages allows us to get information needed by the `version` command without having to rely on `ldflags` set at build time.
This can be really helpful while debugging errors from people using custom binaries. For example a build from master.
- Build binaries from this branch
- run lnd
- call `lncli version`
You can see what information the binary contains with `go version -m {lnd,lncli}`, this already works in the latest lnd versions that have been compiled with `>go1.18`
> build: get binary build info from `debug/buildinfo`

- watchtower/wtclient/client.go
- watchtower/wtclient/interface.go
- watchtower/wtclient/session_queue.go
- watchtower/wtclient/stats.go
- watchtower/wtdb/client_db.go
- watchtower/wtwire/delete_session_reply.go
This fixes the documentation for wtserver's `ListClientSessions` in addition to some typo/grammar fixes.
> watchtower: docu fixes

- Makefile
I forgot the `-ldflags` before setting the ldflags for the `install` target.
> [skip ci] build: fix makefile targets using `RELEASE_LDFLAGS`

- docs/release-notes/release-notes-0.16.0.md
- watchtower/wtclient/addr_iterator.go
- watchtower/wtclient/addr_iterator_test.go
- watchtower/wtclient/backup_task_internal_test.go
- watchtower/wtclient/candidate_iterator.go
- watchtower/wtclient/candidate_iterator_test.go
- watchtower/wtclient/client.go
- watchtower/wtclient/client_test.go
- watchtower/wtclient/errors.go
- watchtower/wtclient/interface.go
- watchtower/wtclient/session_negotiator.go
- watchtower/wtclient/session_queue.go
- watchtower/wtdb/client_db.go
- watchtower/wtdb/client_db_test.go
- watchtower/wtdb/client_session.go
- watchtower/wtdb/tower.go
- watchtower/wtmock/client_db.go
This PR introduces an `AddressIterator` to the wtclient package. Each `Tower` now has an AddressIterator instead of just a list of addresses. This allows concurrent access to a tower's addresses. The iterator also allows a caller to place a lock on an address - this will prevent other callers from removing the address from the iterator. 
This fixes 2 issues:
In this issue, the user is able to add new tower addresses but the addresses are never utilised until LND is restarted. This is fixed in this PR by passing the AddressIterator for a tower around instead of just having a fixed address for a tower.
In this issue, users are unable to to remove _any_ towers (or tower addresses) if session negotiation is in progress _even if_ the negotiation in progress is not using the address/tower in …
> watchtower: introduce an AddressIterator

- config_builder.go
- docs/release-notes/release-notes-0.16.0.md
Use the correct wallet birthday when creating a watch-only wallet.
```
lncli createwatchonly /tmp/accounts.json
Input wallet password: 
Confirm password: 
Input an optional wallet birthday unix timestamp of first block to start scanning from (default 0): 1666033027
...
```
Check the logs to see that the wallet birthday (`timestamp=`) is used correctly:
```
Found birthday block: height=196, hash=3ebdd7b2677069982ceb3195db59d52425fa401dfce6c23fc39b6a8777a50c4d, timestamp=2022-10-14 18:32:24 +0200 CEST
```
Thanks @openoms for reporting.
> wallet: use correct birthday timestamp when creating watch-only wallet

- .golangci.yml
- config.go
- docs/release-notes/release-notes-0.16.0.md
- kvdb/etcd/config.go
- kvdb/postgres/config.go
- lncfg/autopilot.go
- lncfg/bitcoind.go
- lncfg/btcd.go
- lncfg/caches.go
- lncfg/chain.go
- lncfg/db.go
- lncfg/gossip.go
- lncfg/healthcheck.go
- lncfg/invoices.go
- lncfg/monitoring_on.go
- lncfg/neutrino.go
- lncfg/protocol.go
- lncfg/protocol_legacy_on.go
- lncfg/protocol_rpctest.go
- lncfg/remotesigner.go
- lncfg/routing.go
- lncfg/rpcmiddleware.go
- lncfg/sweeper.go
- lncfg/tor.go
- lncfg/watchtower.go
- lncfg/workers.go
- lncfg/wtclient.go
This PR enables the line length check and other previously disabled linters for newly added code. The line too long check should save some reviewers' time.
> lint: enable line too long check and other linters

- .golangci.yml
In this PR we further disable two linters, `gofumpt` and `wsl`, due to the known issues(see the comments). Unless we are willing to accept the following format,
```go
// LookupInvoiceV2 queries the node's invoices using the invoice client's.
func (h *HarnessRPC) LookupInvoiceV2(
req *invoicesrpc.LookupInvoiceMsg,
) *lnrpc.Invoice {
ctxt, cancel := context.WithTimeout(h.runCtx, DefaultTimeout)
defer cancel()
resp, err := h.Invoice.LookupInvoiceV2(ctxt, req)
h.NoError(err, "LookupInvoiceV2")
return resp
}
```
`gofumpt` will **sometimes** report failure if it's not formatted as above. And `wsl` will **sometimes** report `block should not start with a whitespace` error for the above code, which means we cannot add a newline when a function signature is defined in multiple lines.
This means …
> golangci: fine-tune enabled linters

- docs/release-notes/release-notes-0.16.0.md
- funding/manager.go
- funding/manager_test.go
- htlcswitch/link.go
- htlcswitch/link_test.go
- lnwire/lnwire.go
- lnwire/warning.go
- lnwire/writer.go
- peer/brontide.go
Stop casting warnings to errors before passing it to the service handling the message. BOLT1 talks about [error and warning messages]( #6801) so I created a new interface called `ErrorLike`.
Warning messages for pending channels are now handled by the funding manager. Until now they were simply ignored.
Currently, the only action triggered by a warning messages sent by our peers  is logging.
Fixes #6801
> Fix warning messages

- docs/release-notes/release-notes-0.16.0.md
- funding/manager.go
- lnwire/error.go
This fixes https://github.com/lightningnetwork/lnd/issues/7034 where an LND node reveals that is it vulnerable to chain tip sync problems such as https://github.com/lightningnetwork/lnd/issues/7002, which may be exploited by those with existing channels with the node by broadcasting a previous channel state. It would be better if other actors do not know if a node is synced or not. 
1. Be out of sync
2. Attempt to open channel with out of sync node
3. See what error is returned on the wire (should now be `funding failed due to internal error`)
> Remove ErrSynchronizingChain

- build/version.go
- go.mod
- go.sum
This PR fixes the recently discovered block parsing bug fix in lnd by updating btcd from `v0.22.2` to `v0.22.3`
> All itests failing is expected since we use a btcd option that's not in the back-ported branch: --nostalldetect. Confirming itests running correctly locally, will report back as soon as all test cases completed.
https://github.com/lightningnetwork/lnd/pull/7016#issuecomment-1273735334
> release: create v0.14.5 branch to back port block parsing bug fix

- docs/release-notes/release-notes-0.15.4.md
- docs/release-notes/release-notes-0.16.0.md
- go.mod
- go.sum
Ports over the changes from #7098 onto the master branch too.
> mod+docs: bump btcd version to v0.23.3 on master branch

- .github/workflows/main.yml
- docs/release-notes/release-notes-0.16.0.md
Instead of always checking commits against upstream master, check them against the target base branch.
> github: check commits against base branch

- docs/release-notes/release-notes-0.16.0.md
- funding/manager.go
In the itest this log is seen over 3k times before a channel advanced its state,
```
2022-10-29 11:06:16.931 [DBG] FNDG: Channel(fa5d17f622c8f4345bc3bdb867051721483f3090ad41fefe449fe52497d8a071) with ShortChanID 697:1:0 has opening state fundingLocked
```
A dummy time sleep is added to avoid the CPU spike.
> funding: wait for one sec if funding locked is not received

- .github/workflows/main.yml
- docs/release-notes/release-notes-0.16.0.md
For push actions (as opposed to pull-requests), there is no base reference and so the commit-check doesnt work in this case. Realised this mistake when seeing the result of the "check-commits" when PRs are merged into master. 
But we in any case dont need this check on anything but PR actions. Push actions result in a rebase against nothing.
> github: only check commits on PR events

- docs/release-notes/release-notes-0.16.0.md
- funding/config_rpctest.go
- funding/manager.go
- lntest/itest/assertions.go
- lntest/itest/lnd_channel_policy_test.go
This PR adds a temporary fix to the itest before our new itest is merged, also decreases the sleep interval used in checking funding lock message.
> itest+funding: decrease sleep time and add a temporary fix for itest

- docs/release-notes/release-notes-0.16.0.md
- routing/integrated_routing_context_test.go
- routing/integrated_routing_test.go
- routing/mock_graph_test.go
- routing/pathfind.go
- routing/pathfind_test.go
- routing/router_test.go
Add ignore condition to additional edges that connect to self. These
edges are already known and avoiding these hints protect the payment
from malformed channel ids which could lead to infinite loop.
Fixes #6169.
The #6169 issue explains the steps to reproduce the issue.
> routing: Fix possible infinite loop on first hop unknown next peer

- cmd/lncli/cmd_invoice.go
- docs/release-notes/release-notes-0.16.0.md
- lnrpc/invoicesrpc/addinvoice.go
- lnrpc/invoicesrpc/addinvoice_test.go
- lnrpc/invoicesrpc/invoices.swagger.json
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
- lntest/itest/lnd_routing_test.go
This change allows creating no-amount private invoices that do provide hop hints, up to `maxHopHints`.
Fixes #6738
The `testInvoiceRoutingHints` itest was expanded to account for this use case.
If someone can provide some pointers on how to easily decode the payment request response from `lncli addinvoice`, I'd be glad to provide an example from the end-user's perspective.
This itest and the added unit test case fail before the change to `addinvoice.go` (given that change was so minimal, I clubbed it together in the same commit with the unit test change, but I can separate them if deemed necessary :slightly_smiling_face: ).
> addinvoice: provide hop hints for no-amount invoice

- docs/release-notes/release-notes-0.16.0.md
- lnwire/fuzz_test.go
- lnwire/message_test.go
Adds a missing benchmark and fuzz test for the warning message.
Tested with:
```shell
$ cd lnwire
$ go test -bench=Benchmark
...
$ go test -fuzz=FuzzWarning
```
Fixes #7141.
> lnwire: add missing tests for Warning

- docs/release-notes/release-notes-0.16.0.md
- funding/manager.go
Caught from itest. I think we need to mark the tx label first before notifying the client to properly report the state.
> funding: mark tx label before notifying channel open event

- cmd/lncli/arg_parse.go
- cmd/lncli/arg_parse_test.go
- cmd/lncli/cmd_invoice.go
- cmd/lncli/cmd_payments.go
- docs/release-notes/release-notes-0.16.0.md
> lncli: strip accidentally copied 'lightning:' prefix from pay_req

- cmd/lncli/walletrpc_active.go
Pass down a context from bumpCloseFee to getWaitingCloseCommitments, to avoid another call to getContext that used to fail with "intercept already active"
Fixes #7161
Run `lncli wallet bumpclosefee` with valid arguments. Before this patch, you get "intercept already started" even before checking for channel existence
> cmd/lncli/walletrpc_active.go: avoid nested getContext

- docs/release-notes/release-notes-0.16.0.md
- lntest/itest/lnd_remote_signer_test.go
- lntest/itest/lnd_taproot_test.go
This is a temporary fix for my lazyness (re-using the same context for multiple tests) until this is properly fixed in https://github.com/lightningnetwork/lnd/pull/6824. This should turn some of the old itests green until we fully migrate to the new itests.
> itest: temporary fix for taproot test failing on bitcoind

- chainntnfs/bitcoindnotify/bitcoind.go
- chainntnfs/btcdnotify/btcd.go
- chainntnfs/neutrinonotify/neutrino.go
- discovery/gossiper.go
- docs/release-notes/release-notes-0.16.0.md
- funding/manager.go
- healthcheck/healthcheck.go
- htlcswitch/switch.go
- lntest/itest/utils.go
- lnwallet/btcwallet/btcwallet.go
- rpcperms/middleware_handler.go
- rpcserver.go
- sweep/sweeper.go
- ticker/force.go
- watchtower/wtclient/session_queue.go
Inspired by https://github.com/lightningnetwork/lnd/pull/7186.
I checked all anonymous goroutines to make sure they don't access any loop or other temporary variables.
This PR fixes the found instances and also contains some readability improvements to visually highlight `defer` statements better.
> Don't access loop variables in goroutines directly

- docs/release-notes/release-notes-0.15.5.md
- go.mod
- go.sum
- lntest/itest/lnd_recovery_test.go
- lntest/itest/lnd_wallet_import_test.go
- lnwallet/test/test_interface.go
Replaces https://github.com/lightningnetwork/lnd/pull/7147.
In this PR, we specify the default key scope as BIP 86, which means taproot addresses will be used for default by all on chain sends.
Fixes https://github.com/lightningnetwork/lnd/issues/7144.
> lnwallet/btcwallet: use taproot addrs for change outputs from SendCoins

- docs/release-notes/release-notes-0.16.0.md
- lncfg/gossip.go
Fixes https://github.com/lightningnetwork/lnd/issues/7205.
The gossip.pinned-syncers flag is declared as a string slice which means
it should not be a comma separated list of elements but the flag should
be specified multiple times instead.
> lncfg: fix gossip.pinned-syncers flag description

- build/version.go
Two release candidates later, I think we're ready to drop the final release of the year!
> release: bump version to v0.15.5-beta

- docs/release-notes/release-notes-0.16.0.md
- go.mod
- go.sum
- htlcswitch/hop/payload.go
- lnwire/extra_bytes.go
- rpcserver.go
This changes the call-sites in several places to use the *P2P variants to not trigger an OOM on untrusted input. This makes the code safe with the new tlv version. Note that the call-sites prior to this change were also safe.
> multi: update to tlv/v1.1.0 and use new *P2P tlv decoding variants

- docs/release-notes/release-notes-0.16.0.md
- go.mod
- go.sum
~Depends on https://github.com/btcsuite/btcwallet/pull/837.~
This is required after merging #7193 which switches all change outputs over to P2TR.
In order to create a proper Taproot exclusion proof for P2TR change outputs in Taro we need to know the internal key and how the P2TR output key was constructed.
> mod+docs: bump btcwallet to latest version

- docs/release-notes/release-notes-0.16.0.md
- lntemp/rpc/chain_kit.go
- lntest/itest/lnd_onchain_test.go
This PR adds the newly added `ChainKitClient` to `HarnessRPC`, which can be used in other tests.
> itest+lntemp: add `ChainKitClient` RPCs and refactor `testChainKit`

- discovery/gossiper.go
- discovery/reliable_sender.go
- discovery/sync_manager.go
- discovery/syncer.go
- docs/release-notes/release-notes-0.16.0.md
- peer/brontide.go
- routing/router.go
- routing/validation_barrier.go
[This failure](https://github.com/lightningnetwork/lnd/actions/runs/3509259108/jobs/5878235809) has been seen in the refactored itest quite often, leading to an investigation over the gossip/routing package. This PR refactored the related code to the point where the potential bug finally manifested itself in the logs.
The actual fix was simple, as shown in the last commit. Basically, we may get a deny signal from `handleChanAnnouncement` when processing an announcement that is ignored by routing because the channel edge info was already created. Please check the commit message for details.
Another fix is to replace the pattern,
```go
select {
case variable := <-channel:
go func() {
// Some actions here...
// Now access the variable, which might be referencing to a different one. …
```
> Fix potential channel announcements missing

- docs/release-notes/release-notes-0.16.0.md
- lntemp/harness.go
- lntemp/harness_assertion.go
Ensure active nodes are synced to the latest block mined, since the nodes may actually be "fully synced" to an old block when SyncedToChain is true.
This patch was useful for diagnosing #7241 and may reduce test flakiness.
@yyforyongyu
> lntemp: after mining, sync to latest block

- docs/release-notes/release-notes-0.16.0.md
- go.mod
- go.sum
- lntemp/harness_assertion.go
- lntemp/rpc/signer.go
- lntemp/rpc/wallet_kit.go
- lntest/itest/list_on_test.go
- lntest/itest/lnd_recovery_test.go
- walletunlocker/service.go
Fixes https://github.com/lightningnetwork/lnd/issues/6434 by bumping the `btcwallet` version to the latest version that includes the fix in https://github.com/btcsuite/btcwallet/pull/838.
We also add an integration test that was able to show the problem.
Fixes https://github.com/lightningnetwork/lnd/issues/6434
> wallet: fix ghost UTXOs not being detected

- .github/actions/setup-go/action.yml
- .github/workflows/main.yml
- docs/release-notes/release-notes-0.16.0.md
- tools/Dockerfile
Looks like `golang:1.19.2-buster` is not maintained, switch to `golang:1.19` to get the latest build. A minor refactor is also applied to the action yml.
> tools: fix docker version

- discovery/gossiper.go
- discovery/gossiper_test.go
- docs/release-notes/release-notes-0.16.0.md
- fn/stream.go
In this commit, we modify our gossip broadcast logic to ensure that we
always will send out our own gossip messages regardless of the
filtering/feature policies of the peer.
Before this commit, it was possible that when we went to broadcast an
announcement, none of our peers actually had us as a syncer peer (lnd
terminology). In this case, the FilterGossipMsg function wouldn't do
anything, as they don't have an active timestamp filter set. When we go
to them merge the syncer map, we'd add all these peers we didn't send
to, meaning we would skip them when it came to broadcast time.
In this commit, we now split things into two phases: we'll broadcast
_our_ own announcements to all our peers, but then do the normal
filtering and chunking for the announcements we got from a remote peer.
Fixes …
> discovery: ensure we prioritize sending out our own local announcements

- cmd/lncli/walletrpc_active.go
Was reading the `bumpfee` docs and it said to check `lncli pendingsweeps`, which should be `lncli wallet pendingsweeps`. 
N/A just docstring changes
> Fix bumpfee command doc, incorrect reference to pendingsweeps

- docs/release-notes/release-notes-0.16.0.md
- funding/manager.go
- funding/manager_test.go
In this commit, the error returned from `getInitialFwdingPolicy` is checked in order to avoid a nil pointer dereference panic during the TestFundingManagerCustomChannelParameters test.
Ran into this in one of my other PRs:
```
--- FAIL: TestFundingManagerCustomChannelParameters (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe33a20]
goroutine 41 [running]:
testing.tRunner.func1.2({0xf61e60, 0x1acc570})
/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1399 +0x39f
panic({0xf61e60, 0x1acc570}) …
```
> funding: check error to avoid panic during test

- docs/release-notes/release-notes-0.16.0.md
- lnwire/onion_error.go
- lnwire/onion_error_test.go
Fixes a bug where channel update data is read until the end of the stream rather than stopping after the specified length. This is problematic when failure message tlv data is present, because this data is interpreted as channel update tlv data. The extra data isn't covered by the channel update signature, and the channel update is discarded.
Thanks to @t-bast for pointing this out.
> lnwire: limit channel update reader

- .golangci.yml
- docs/release-notes/release-notes-0.16.0.md
- lnwire/onion_error_test.go
We often split tests into separate test functions. If we are forced to
call `t.Helper()` within those functions, we lose the information where
exactly a test failed in the generated failure stack trace.
> lint: disable `thelper` linter

- .github/actions/setup-go/action.yml
- .github/workflows/main.yml
- docs/release-notes/release-notes-0.16.0.md
For some reason we used to override the `GOCACHE` and `GOPATH` variables
earlier. This now causes the updated cache action not to pick up any
caches. As the overrides shouldn't be needed anymore, we remove them.
> GitHub: fix Golang build cache in actions

- config.go
- docs/release-notes/release-notes-0.16.0.md
- lncfg/protocol_experimental_off.go
- lncfg/protocol_experimental_on.go
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
- lnrpc/lightning_grpc.pb.go
- lntest/itest/lnd_custom_message.go
- lntest/itest/lnd_test_list_on_test.go
- lnwire/custom.go
- lnwire/message.go
This PR adds the handling of protocol-range messages via the existing custom mesage APIs. This functionality is protected behind the `dev` built tag, and must be opted-into on a per-message level because it is an advanced features. 
Fixes #7093. 
This approach uses a simple global of overriden message numbers to set our list of message types that can be sent with the custom messaging API. Since we only write to this value on startup (and have no cause to write to it otherwise), I went with the simplicity of this approach. Threading through to [makeEmptyMessage](https://github.com/lightningnetwork/lnd/blob/master/lnwire/message.go#L177) would otherwise require a much larger refactor. 
Test sending a protocol level message from Alice to Bob. 
* `lncli-bob subscribecustom`
* `lncli-alice …
> multi: Add ability to handle protocol-range messages in Custom Message APIs

- lnrpc/routerrpc/router.proto
- lnrpc/routerrpc/router.swagger.json
- lnrpc/routerrpc/router_grpc.pb.go
Changes the docstring of `QueryProbability` to reflect changes that were introduced in #6857.
> routerrpc: update QueryProbability documentation

- docs/release-notes/release-notes-0.16.0.md
- lntemp/rpc/harness_rpc.go
- lntemp/rpc/neutrino_kit.go
- lntest/harness_node.go
- lntest/itest/list_on_test.go
- lntest/itest/lnd_neutrino_test.go
Requested by @yyforyongyu. This PR add an itest for some of the functions (excluding isbanned and disconnect peer) of the neutrino sub-server, and incorporate the neutrino sub-server as a client in the harnessnode. For this to work neutrino has to be chosen as the backend (`make itest backend=neutrino`).
I did not include t.Skip messages for non-neutrino backend tests.
> itest: neutrino sub-server

- docs/release-notes/release-notes-0.16.0.md
- funding/batch.go
- funding/commitment_type_negotiation.go
- funding/manager.go
- funding/manager_test.go
This PR aims to clean up some code style issues in the `funding` package mostly around line length issues.
Code structure and logic changes are only applied if the linter is asking for it.
> funding: code style cleanup in the funding package

- cmd/lncli/cmd_payments.go
This PR clarifies the htlc failure case in the lncli payment
command, by using the cardinal number as well as 'hop' in the
failure message.
closes #7304
> lncli/sendpayment: more descriptive failure log

- .golangci.yml
- docs/release-notes/release-notes-0.16.0.md
- htlcswitch/circuit_map.go
- htlcswitch/mailbox.go
- htlcswitch/mailbox_test.go
- lnmock/clock.go
As seen in [this](https://github.com/lightningnetwork/lnd/actions/runs/3893392874/jobs/6645944322) and several other builds, the `TestMailBoxAddExpiry` sometimes fails and this PR fixes it.
The reason behind the failure is probably due to the setup of the test clock. I think this implementation of `clock.Clock` brings more complexity into our unit tests(which are supposed to be simple and straightforward), so a mock clock is used instead.
> htlcswitch: fix test flake in `TestMailBoxAddExpiry`

- cmd/lncli/cmd_payments.go
- docs/release-notes/release-notes-0.16.0.md
Skip the gomnd lint check in lncli switch statement
> lncli+docs: skip gomnd check in switch statement

- docs/release-notes/release-notes-0.16.0.md
- lnwallet/channel.go
This adds a log message that helps curious users understand why a wrong local balance is reported.
See #7108 for further information.
> lnwallet: add log message for edge case

- channeldb/migration30/migration_test.go
- channeldb/migtest/migtest.go
- docs/release-notes/release-notes-0.16.0.md
- lnrpc/wtclientrpc/wtclient.go
- watchtower/log.go
- watchtower/wtclient/client.go
- watchtower/wtclient/interface.go
- watchtower/wtdb/client_db.go
- watchtower/wtdb/client_db_test.go
- watchtower/wtdb/codec_test.go
- watchtower/wtdb/log.go
- watchtower/wtdb/migration2/client_db.go
- watchtower/wtdb/migration2/client_db_test.go
- watchtower/wtdb/migration2/codec.go
- watchtower/wtdb/migration2/log.go
- watchtower/wtdb/migration3/client_db.go
- watchtower/wtdb/migration3/client_db_test.go
- watchtower/wtdb/migration3/codec.go
- watchtower/wtdb/migration3/log.go
- watchtower/wtdb/migration4/client_db.go
- watchtower/wtdb/migration4/client_db_test.go
- watchtower/wtdb/migration4/codec.go
- watchtower/wtdb/migration4/log.go
- watchtower/wtdb/migration4/range_index.go
- watchtower/wtdb/range_index.go
- watchtower/wtdb/range_index_test.go
- watchtower/wtdb/version.go
- watchtower/wtmock/client_db.go
This PR contains a few migrations of the watchtower client DB. 
1. It greatly reduces the storage requirements of the session `AckedUpdates` through the use of a new `RangeIndex` model.
2. The various indexes added in this PR nicely sets us up for a follow up PR in which we we will be able to determine which sessions we can delete (and tell the tower server that it can delete) based on if all channels that the session has updates for have been deleted. (Ie, this is a step towards #6259, #7035)
A `ChannelDetails` bucket is added and each registered channel gets its own sub-bucket in this bucket. The existing channel summaries are moved here under the `cChannelSummary` key and the old top-level `cChanSummaryBkt` is deleted. This is done so that we can store more details about a channel …
> watchtower: reduce AckedUpdate storage footprint

- docs/release-notes/release-notes-0.16.0.md
- routing/payment_lifecycle_test.go
The test cases in `TestUpdatePaymentState` run in parallel. One of the parameters is a pointer and the value to the struct it points to gets modified during the test.
The race condition was introduced in 8d49dfb07ea00352effc9ed99ce995db270b78e6 To test the fix run from the main folder `go test  ./routing/. -race` before this fix and after.
> routing: fix reace condition in `TestUpdatePaymentState`

- channeldb/invoices.go
- docs/release-notes/release-notes-0.16.0.md
- invoices/invoices.go
- lnrpc/invoicesrpc/utils.go
The only way to know if an invoice is AMP, Keysend, etc is to look at its shape/characteristics. This commit adds a couple of helper functions to encapsulate the logic of these checks.
If all these types cannot intersect: an invoice cannot be AMP and Keysend or Keysend and Bolt12, etc it could be useful to add an extra field to store this information instead of relying on checking how the invoice looks like.
> channeldb/invoices: add `IsAMP` and `IsKeysend` helpers

- docs/release-notes/release-notes-0.16.0.md
- lnwire/fuzz_test.go
This PR addresses #7237 and adds the custom message of the lnwire package to the fuzz tests.
@Crypt-iQ could you take a look and check whether I am missing something before I set it to "ready for review", thanks in advance :)
Run the fuzz test suite for the lnwire package with `make fuzz pkg=lnwire` or test the new fuzz test explicitly with 
`go test -fuzz=FuzzCustomMessage` in the lnwire directory
> Add Custom Message to Fuzz Testing

- aliasmgr/aliasmgr.go
- aliasmgr/aliasmgr_test.go
- channeldb/graph.go
- docs/release-notes/release-notes-0.16.0.md
- lntest/itest/list_on_test.go
- lntest/itest/lnd_zero_conf_test.go
Fixes #7229 
Description of issue:
When a block is disconnected due to a reorg, DisconnectBlockAtHeight is called for the block height. Prior to this patch, it would delete every SCID in the graph with a block height greater than the disconnected height. This meant that a reorg would delete every zero-conf channel edge from the graph. The fix simply iterates up until the StartingAlias and deletes every SCID between the disconnected height and the StartingAlias height.
An integration test is included that asserts that the fix works.
> aliasmgr+channeldb: stop deleting zero-conf edges from graph if reorg occurs

- docs/release-notes/release-notes-0.16.0.md
- tools/Dockerfile
Linter fails again, and copied fix from https://github.com/lightninglabs/taro/pull/219.
> ci: fix lint VSC permissions error

- .github/workflows/main.yml
This PR allows skipping parts of the CI by specifying labels on the PR:
- `no-itest`: Skips all integration tests (useful for changes that only affect unit tests or documentation)
- `no-changelog`: Skips the "check release notes" step (useful for small changes that don't need to be mentioned in the release notes).
This PR demonstrates the use by setting both labels.
> GitHub: allow skipping itest and changelog check with labels

- docs/release-notes/release-notes-0.16.0.md
- walletunlocker/service_test.go
This fixes a unit test flake that occurred sometimes if the temporary directory was attempted to be deleted but the wallet or macaroon DB hasn't been closed yet.
````
--- FAIL: TestChangeWalletPasswordNewRootkey (1.63s)
testing.go:1097: TempDir RemoveAll cleanup: unlinkat /tmp/TestChangeWalletPasswordNewRootkey3063283009/001/mainnet: directory not empty
FAIL
FAIL	github.com/lightningnetwork/lnd/walletunlocker	6.171s
FAIL
````
> walletunlocker: fix unit test flake by closing DB

- channeldb/channel_test.go
- channeldb/db_test.go
- invoices/invoiceregistry_test.go
From this [build](https://github.com/lightningnetwork/lnd/actions/runs/4128434176/jobs/7132878444),
```
--- FAIL: TestFetchChannels (0.00s)
--- FAIL: TestFetchChannels/not_waiting_close_channels (0.01s)
channel_test.go:195: unable to save and serialize channel state: channel already exists
FAIL
```
Though a tiny chance, it looks like the `rand.Uint32()` produced the same value twice. We now avoid this possibility by making the outpoint unique deterministically.
Also from this [build](https://github.com/lightningnetwork/lnd/actions/runs/4142208064/jobs/7162611176),
```
--- FAIL: TestInvoiceExpiryWithRegistry (0.53s)
invoiceregistry_test.go:1028: 
Error Trace:	/home/runner/work/lnd/lnd/invoices/invoiceregistry_test.go:1028
Error:      	Not equal: 
expected: 0x2
actual  : 0x0
Test: …
```
> channeldb+invoices: fix unit test flakes

- docs/release-notes/release-notes-0.16.0.md
- lnrpc/routerrpc/forward_interceptor.go
This fixes an issue where LND can crash due to an invalid RPC message from an HTLC interceptor.  Not a security or DoS concern as this is from authenticated messages coming in on grpc, but it's a pretty easy mistake to make on the interceptor side (just leave off the `IncomingCircuit`) so I think it's worth fixing.
All this PR does is add a `==nil` check and returns an error if `IncomingCircuit` is nil.  
Other places you could put this check would be in `(r *forwardInterceptor) run()` above (or maybe in the `Recv()` function somehow?) but this seemed like the most straightforward place.
To test: 
Run LND.  
Connect an HTLC interceptor, but in the interceptor code, don't specify an `IncomingCircuitKey` in the `routerrpc.ForwardHtlcInterceptResponse`.  
The first time LND tries to forward …
> HTLC Interceptor: Fix nil pointer dereference

- sample-lnd.conf
This PR fixes whitespace in `sample-lnd.conf` in two ways:
- removes dangling spaces at end of the lines `s/ *$//`
- adds extra space after `^;` where needed (once instance)
> docs: fix whitespace in sample-lnd.conf

- docs/release-notes/release-notes-0.16.0.md
- funding/manager.go
- lntest/itest/lnd_funding_test.go
- lntest/itest/lnd_remote_signer_test.go
- lnwallet/chanfunding/wallet_assembler.go
- lnwallet/rpcwallet/rpcwallet.go
Fixes https://github.com/lightningnetwork/lnd/issues/7276.
This fixes an issue where channels couldn't be opened if there were a number of mixed type (p2tr and p2wkh for example) inputs used for the funding transaction.
> remote signer: fix channel funding with mixed funding input types

- cmd/lncli/cmd_mission_control.go
- config.go
- docs/release-notes/release-notes-0.16.0.md
- lnrpc/routerrpc/config.go
- lnrpc/routerrpc/router.pb.go
- lnrpc/routerrpc/router.proto
- lnrpc/routerrpc/router.swagger.json
- lnrpc/routerrpc/router_server.go
- lnrpc/routerrpc/routing_config.go
- lntemp/rpc/router.go
- lntest/itest/lnd_routing_test.go
- routing/integrated_routing_context_test.go
- routing/integrated_routing_test.go
- routing/missioncontrol.go
- routing/missioncontrol_test.go
- routing/pathfind.go
- routing/probability_apriori.go
- routing/probability_apriori_test.go
- routing/probability_bimodal.go
- routing/probability_bimodal_test.go
- routing/probability_estimator.go
- routing/probability_estimator_test.go
- routing/router_test.go
- sample-lnd.conf
- server.go
This PR implements an additional probability estimator ("bimodal") based on a probability theory framework using channel capacities and previous learnings from payments as inputs. The specific assumed liquidity distribution of channel liquidity is based on research in [#5988](https://github.com/lightningnetwork/lnd/issues/5988#issuecomment-1131234858).
The computed probability consists of:
* the direct channel probability, which is estimated based on a depleted liquidity distribution model, our formulas are derived after Pickhardt et al. [arXiv:2103.08576](https://arxiv.org/abs/2103.08576)
* an extension of the probability model to incorporate knowledge decay after time for previous successes and failures
* a mixed node probability taking into account successes/failures on other channels …
> pathfinding: probability for bimodal distribution

- cmd/lncli/cmd_open_channel.go
Fixes linter line length issues in `cmd/lncli/cmd_open_channel.go`.
> lncli: fix line length issues

- .github/workflows/main.yml
In this commit, we activate the merge queue by using the new merge_group selector. Without this, the CI won't report back the progress of a CI run to the merge queue, so things won't get auto merged.
> build: use the new merge_group selector for the merge queue

- .github/workflows/main.yml
Oops, I should have taken a look at the Taro PR, apparently the setting for the merge queue is called `merge_group` and not `merge_queue`.
> github: fix merge group directive

- channeldb/channel.go
- channeldb/db.go
- channeldb/meta_test.go
- channeldb/migration30/migration.go
- channeldb/migration30/migration_test.go
- channeldb/migration30/revocation_log.go
- channeldb/migration30/test_utils.go
- channeldb/migtest/migtest.go
- channeldb/options.go
- channeldb/revocation_log.go
- channeldb/revocation_log_test.go
- config.go
- config_builder.go
- docs/release-notes/release-notes-0.16.0.md
- lncfg/db.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- sample-lnd.conf
- watchtower/wtdb/migration4/client_db_test.go
This PR re-adds the `LocalBalance` and `RemoteBalance` fields to the `RevocationLog`. It also tweaks the existing `channeldb/migration30` to include these fields so that users who have not yet run the optional migration dont have to lose these fields. 
The reason for re-adding these fields is for a use cases where we want to be able to construct an `lnwallet.BreachRetribution` _without_ having access to the actual breach transaction. An example of this use case is with watchtowers where we might want to re-play a backup onto a different tower's session queue which means we will need to re-sign the justice transaction. This is required for [this PR](https://github.com/lightningnetwork/lnd/pull/7380) in order to solve [this issue](https://github.com/lightningnetwork/lnd/issues/5983)
By …
> multi: add local and remote amount fields to revocation log

- lnwallet/wallet.go
It's not removed for the responder of the funding flow, but it is initialized for the responder of the funding flow
> lnwallet: remove from reservationIDs

- discovery/gossiper.go
> discovery: fix heap escape on `cachedMsgs`

- cmd/lncli/cmd_walletunlocker.go
- docs/release-notes/release-notes-0.16.0.md
Fixes https://github.com/lightningnetwork/lnd/issues/7457 by adding the `--stateless_init` flag to the `createwatchonly` command.
@saubyk Would be great to get this in for 0.16.0. I would classify it as a bug fix, as the flag was simply forgotten when the `createwatchonly` command was created.
> remote signer: allow stateless init of watch-only node

- itest/list_on_test.go
- itest/lnd_htlc_test.go
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
- lnrpc/lightning_grpc.pb.go
- lntest/harness.go
- lntest/rpc/lnd.go
- rpcserver.go
This is a follow-up on #7341. The change is trivial - that we disable `LookupHtlc` when the flag is not set, and added an itest case.
> disable lookup when not opted-in and add itest for `LookupHtlc`

- docs/release-notes/release-notes-0.16.0.md
- rpcserver.go
This PR removes the error handling of the peer alias lookups in the RPCs `ListChannels` and `ForwardingHistory` in order to run the commands uninterrupted in case the peer alias can't be found for a channel or a forwarding event. See discussion https://github.com/lightningnetwork/lnd/pull/7322#issuecomment-1450328599
Cc @saubyk @guggero
> rpc: assign peer alias lookup error string

- discovery/gossiper.go
- discovery/gossiper_test.go
- go.mod
- go.sum
Fixes #7396. This PR flattens the slice used in future message cache and increases the cache size.
Depends on https://github.com/lightninglabs/neutrino/pull/268
> discovery: flatten future msg cache and increase its size

- chainntnfs/bitcoindnotify/bitcoind_test.go
- chainntnfs/test_utils.go
- lntest/wait/wait.go
This PR makes a few miscellaneous changes to some test related code:
1. Fixes a bug in the wait.NoError function. If the predicate
function, f, passed to the NoError function would hang for the full
timeout, then the `predErr` would remain nil and so a nil error would be
returned from the function. This PR handles that case.
2. Rename some sub tests to correctly reflect what they are testing
3. Small fixes to the `NewBitcoindBackend` test util func
> multi: fix wait.NoError and sub-test names

- discovery/gossiper.go
- discovery/syncer.go
- lntest/node/config.go
- server.go
This PR adds more logs the `discovery` and uses `trace` for `DISC` in itest - we will keep it there for a while until all gossip related flakes have been fixed.
> Add trace logs for `discovery` to catch test flakes

- config_builder.go
- docs/release-notes/release-notes-0.16.0.md
- lnutils/chan.go
- lnwallet/config.go
- lnwallet/mock.go
- lnwallet/rebroadcaster.go
- lnwallet/rebroadcaster_test.go
- lnwallet/wallet.go
In this commit, we add a new Rebroadcaster interface to be used for publishing transactions passively in the background until they've been confirmed on chain. This is useful if a tx drops out of the mempool, but then the pool clears down and has more space available to accept the tx at the current fee level.
@Roasbeef
> lnwallet: add new rebroadcaster interface, use for background tx publish

- cmd/lncli/walletrpc_active.go
- docs/release-notes/release-notes-0.16.1.md
The RPC has received the `MinConfs` and `SpendUnconfirmed` fields a while ago, we just never added them to `lncli`.
This PR adds a new flag `--min_confs` with a default value of 1 (which corresponds to the current fallback value) that can be overwritten to 0 if unconfirmed inputs should be used.
> lncli: allow specifying `--min_confs` in `wallet psbt fund` to select unconfirmed inputs

- itest/lnd_htlc_test.go
- lntest/harness.go
Fixed a case where the cleanup is missed and validated the state when the tests end.
> itest+lntest: make sure states are cleaned when tests end

- docs/release-notes/release-notes-0.16.1.md
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/switch_test.go
Replaces #6417 and fixes #5721.
The comments from the original PR have been addressed.
> Return FEE_INSUFFICIENT before checking balance for incoming low-fee HTLCs

- Makefile
- make/testing_flags.mk
Make sure the `TEST_FLAGS` is also used in coverage test, e.g., timeout.
> Makefile: add testing_flags to coverage test

- docs/release-notes/release-notes-0.16.1.md
- itest/lnd_onchain_test.go
- rpcperms/interceptor.go
- rpcserver.go
Found a new flake from [this build](https://github.com/lightningnetwork/lnd/actions/runs/4422237723/jobs/7753851726):
```
harness_rpc.go:97: 
Error Trace:	/home/runner/work/lnd/lnd/itest/harness_rpc.go:97
/home/runner/work/lnd/lnd/itest/lnd.go:372
/home/runner/work/lnd/lnd/itest/lnd_onchain_test.go:443
/home/runner/work/lnd/lnd/itest/harness.go:286
/home/runner/work/lnd/lnd/itest/lnd_test.go:136
Error:      	Received unexpected error:
rpc error: code = Unknown desc = reserved wallet balance invalidated: transaction would leave insufficient funds for fee bumping anchor channel closings (see debug log for details)
Messages:   	Alice: failed to call SendCoins
harness.go:342: finished test: 3rd_party_anchor_spend, start height=506, end height=514, mined blocks=8
harness.go:348: test failed, …
```
> itest+rpcserver: fix itest flake in `3rd_party_anchor_spend`

- .travis.yml
Observed on this build: https://app.travis-ci.com/github/lightningnetwork/lnd/builds/261672783
Sounds like Travis is red most of the time because it simply takes longer than 30 minutes to run the build.
> travis: increase timeout to 120 minutes

- lntest/harness.go
- lnwallet/chainfee/estimator_test.go
Two flakes were found in [this build](https://github.com/lightningnetwork/lnd/actions/runs/4482285819/jobs/7880172996?pr=7520),
For the web fee estimator, we need more verbose logs to understand the failure. For the channel close under windows, we just increase the waiting period, which could be removed once the new coop flow is merged.
> Fix web fee estimator test flake and increase retry timeout for channel close

- cmd/lncli/commands.go
- cmd/lncli/commands_test.go
- config.go
- docs/release-notes/release-notes-0.16.1.md
- lnrpc/invoicesrpc/addinvoice.go
- routing/router.go
- rpcserver.go
Signed-off-by: Eval EXEC <execvy@gmail.com>
This PR want to add time_lock_delta overflow check in rpcServer, the maximum time_lock_delta should be `max(uint16)`, fix #7320
> [rpcServer]: add time_lock_delta overflow check for UpdateChannelPolicy

- itest/lnd_misc_test.go
- itest/lnd_psbt_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/6918.
It turns out that the main body of work for https://github.com/lightningnetwork/lnd/issues/6918 was already done in https://github.com/lightningnetwork/lnd/pull/7348 and https://github.com/lightningnetwork/lnd/pull/7209 (through https://github.com/btcsuite/btcwallet/pull/837).
So all we need to add are integration tests that assert these new assumptions around change outputs.
NOTE: I decided that we shouldn't add a change output type field to `SendCoins`, `SendMany` or `EstimateFee`. If anyone needs more control over creating on-chain transactions, they should use the PSBT APIs which can replace all three of those calls.
> itest: assert change output type

- build/version.go
Bump version definition for final release version of `v0.16.0-beta`.
> build: bump to version v0.16.0-beta final

- docs/release-notes/release-notes-0.16.1.md
- watchtower/wtclient/addr_iterator.go
- watchtower/wtclient/addr_iterator_test.go
- watchtower/wtclient/candidate_iterator.go
Two successive calls to the `AddressIterator`'s `Next` method could cause a panic _iff_ the iterator is
at the end of its list & if `Reset` is not called between calls. This PR fixes this to avoid this panic.
Fixes https://github.com/lightningnetwork/lnd/issues/7552
NOTE that this is not the ideal fix but will do for now. A better solution will be possible once https://github.com/lightningnetwork/lnd/pull/6895 is in which will allow us to shutdown sessionQueues correctly.
> wtclient: address iterator fix

- docs/release-notes/release-notes-0.16.1.md
- go.mod
- go.sum
- itest/lnd_psbt_test.go
- lntest/rpc/wallet_kit.go
- lnwallet/btcwallet/psbt.go
- lnwallet/rpcwallet/rpcwallet.go
This relates to #7527, btcsuite/btcwallet#852, btcsuite/btcd#1964
I guess we also want to use the new `InputsReadyToSign` when using the remote signer setup and the `SignPsbt` function.
If so, then I still need to add some tests for `FinalizePsbt` and `SignPsbt`.  I would introduce those tests at the rpc level ? Maybe in a new `walletkit_server_test.go`?
> Check for nonWitness UTXO or witness UTXO data in the psbt inputs

- docs/release-notes/release-notes-0.16.1.md
- watchtower/wtclient/client_test.go
- watchtower/wtclient/errors.go
- watchtower/wtclient/interface.go
- watchtower/wtclient/session_negotiator.go
- watchtower/wtdb/client_db.go
- watchtower/wtdb/client_db_test.go
- watchtower/wtmock/client_db.go
Since the watchtower subserver was added, if ever users have run into issues, 
the common advice has been to delete the `wtclient.db`. This however, leads
to the linked issues. Basically: session IDs are derived deterministically from an 
incrementing DB key. This means that if a client had a session (`A`) with a server
and pushed some updates to the server using session `A`, but then deleted
the `wtclient.db` file, they would then still derive the same ID they used for the 
original session `A`. This means that the client would end up sending a state
update to the server over session `A` with sequence number 1 while the server 
would be expecting a higher sequence number and so would return the 
`StateUpdateCodeClientBehind` error code back to the client. 
If the client receives the …
> watchtower: let client recover after data loss

- Makefile
- docs/release-notes/release-notes-0.16.0.md
- docs/release-notes/release-notes-0.16.1.md
- go.mod
- go.sum
- mobile/README.md
- mobile/bindings.go
PR [6963](https://github.com/lightningnetwork/lnd/pull/6963) refactored the Makefile to have a more streamlined approach to ldflags. However, in the process it also introduced two subtle but critical errors.
1. The `-ldflags` parameter is missing.
2. The ldflags themselves are not wrapped in a string.
The result is that the arguments are mangled, and gomobile complains about `-s` not being a parameter.
Before 6963:
```GO111MODULE=off /home/synthlock/go/bin/gomobile bind -target=android -tags="mobile dev autopilotrpc chainrpc invoicesrpc neutrinorpc peersrpc routerrpc signrpc verrpc walletrpc watchtowerrpc wtclientrpc" -ldflags " -s -w -X github.com/lightningnetwork/lnd/build.Commit=v0.15.5-beta -X github.com/lightningnetwork/lnd/build.CommitHash=c0a09209782b1c62c3393fcea0844e095c25046b -X …
```
> build: fix Makefile ldflags for mac and mobile, bump gomobile deps, enable gomodules

- build/version.go
In this commit, we bump the version of the master branch to v0.16.99. This reflects the fact that master will be a super set of all the minor releases until v0.17, and will also include changes towards v0.17.
> build: bump version to v0.16.99

- docker/btcd/Dockerfile
- docs/INSTALL.md
Update instructions and tutorial `btcd` version to allow sync on testnet.
> docker+docs: bump btcd version

- docs/postgres.md
- docs/release-notes/release-notes-0.16.0.md
Adding notes on how Postgres DB is currently used as a Key-Value store, and which tables are included.
Addresses Issue #6619 - "Missing documentation for postgresql database structure"
Key/Value pairs are not all TLV-encoded. Schema/structure is unclear (outside of K/V column names). However, some Key Names and Values are possible to decode into human-readable strings. For example: I used Python + psycopg2 + text processing to decode some of these, such as Node names (see comment on Gist): https://gist.github.com/84adam/d85f5f40e8821925585f263f68b655eb
SQL statements do not reveal any consistent encoding or structure:
```
select * from channeldb_kv limit 5;
key                   | value | parent_id | id | sequence 
----------------------------------------+-------+-----------+----+--------- …
```
> docs: add notes on contents of Postgres DB as Key-Value store to Postgres.md

- lnutils/sync_map.go
- lnutils/sync_map_test.go
Add more methods to `SyncMap`, which are used in multiple PRs now.
> lnutils: add methods `ForEach`, `Len` and `LoadOrStore` to `SyncMap`

- docs/release-notes/release-notes-0.16.1.md
Related to https://github.com/lightningnetwork/lnd/issues/7505.
~Depends on https://github.com/btcsuite/btcwallet/pull/851.~
The logging around transaction broadcast failures has been improved by always logging the causing error and the raw transaction as hex.
> wallet: improve logging around transaction broadcast failures

- config.go
In this commit, we fix a bug that would cause the walletrpc on the simnet chain to not be able to respond to all RPC calls. The issue is that for the SimNet backend, within chainparams.go: https://github.com/lightningnetwork/lnd/blob/6e0a67d05bd375c4b39db53dc45df74157227a57/chainreg/chainparams.go#L45-L51, we set a new CoinType for Simnet in order to match the RegTest value.
Later on, when we go to verify the on disk accounts against the in-memory cointype, we fall through to an error case as the in-memory cointype is 115, while the on disk cointype is 1.
To fix this, when we know we're doing simnet mode, we'll override the cointype similar to the way we did/do for LTC.
Fixes https://github.com/lightningnetwork/lnd/issues/6807.
> config: fix bug in walletrpc interaction due to mismatched coin type

- lnrpc/gen_protos_docker.sh
Remove the need for golang on the host by utilizing golang docker containers to obtain protobuf and grpc gateway versions.
Improve the dockerized protobuf generation by removing the need for golang on the host system. Makes life easier for those of us who prefers to our host systems clean and use vscode devcontainers or docker containers for their development environment.
> lnrpc: fully dockerize protobuf generation

- docs/release-notes/release-notes-0.16.1.md
- funding/batch.go
- itest/lnd_funding_test.go
- lntest/harness_assertion.go
fixes https://github.com/lightningnetwork/lnd/issues/7601
In LND v0.15.1, batch_open_channel used p2tr by default for change output. However, in a later version, a breaking change has been fixed in FundPSBT to make the change type configurable (default to p2wkh). As batch_open_channel uses FundPsbt, we need to put back p2tr as default for change output for this specific case
> funding: use p2tr by default for batch_open_channel

- docs/release-notes/release-notes-0.16.1.md
- netann/chan_status_manager.go
Mini Driveby PR I came across today.
```
2023-04-17 10:33:05.717 [DBG] NANN: Channel(%!v(MISSING)) already enabled, skipped announcement
```
> Log Output Fix (Missing Value)

- Makefile
Currently `make lint` creates a new container each time it runs. We can automatically delete these containers once linting is done by using the `--rm` flag.
Tested:
```shell
make lint
docker ps -a  # no new containers created
```
> make: clean up container after linting

- docs/release-notes/release-notes-0.16.1.md
- funding/manager.go
- funding/manager_test.go
In this commit, a bug is fixed in the funding manager that could result in the funding process erroring out if the persisted initial forwarding policy is not found. This could occur if a node restarts after opening a channel that is not yet fully confirmed and also upgrades their node from a pre-0.16 version to 0.16 since the values are only expected to be persisted after 0.16 (which includes the changes made in https://github.com/lightningnetwork/lnd/pull/6753). 
This addresses the issue reported in [this comment](https://github.com/lightningnetwork/lnd/issues/6987#issuecomment-1510377248)
> funding: use default forwarding policy if persisted values not found

- chainreg/chainregistry.go
- docs/release-notes/release-notes-0.16.1.md
- sample-lnd.conf
In this commit, we increase the default CTLV value to 80 blocks. Initially this was set to 144 blocks in the early days, but then was lowered to 40 blocks as the lnd implementation matured. By setting this to a higher value, we increase the safety window (MTTR) when it comes to node downtime, and also add some buffer room around time locks which may become more stressed in the future assuming the current mempool load remains persistent.
> chainreg: increase default CLTV value to 80 blocks (~13 hrs)

- lnd.go
- lntest/node/harness_node.go
- lntest/wait/timeouts.go
This commit makes sure when lnd is shutting down, the optional pprof server is also gracefully shutting down.
Errors from itest build,
```
itest error from [multi_hop_htlc_local_chain_claim:Bob]: timeout waiting for process to exit
=== NAME  TestLightningNetworkDaemon
harness_rpc.go:97: 
Error Trace:	/home/runner/work/lnd/lnd/itest/harness_rpc.go:97
/home/runner/work/lnd/lnd/itest/lnd.go:84
/home/runner/work/lnd/lnd/itest/harness_node.go:603
/home/runner/work/lnd/lnd/itest/harness_node.go:565
/home/runner/work/lnd/lnd/itest/harness_node.go:457
/home/runner/work/lnd/lnd/itest/harness_node_manager.go:146
/home/runner/work/lnd/lnd/itest/harness.go:525
/home/runner/work/lnd/lnd/itest/harness.go:565
/home/runner/work/lnd/lnd/itest/harness.go:301
/home/runner/work/lnd/lnd/itest/harness.go:328 …
```
> lntest+lnd: gracefully shutdown pprof server

- sweeper_wallet.go
There's a panic in our itest when we try to cancel rebroadcast when using neutrino backend,
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12a0e0c]
goroutine 362 [running]:
github.com/lightningnetwork/lnd.(*sweeperWallet).CancelRebroadcast(0xc00003efc0?, {0x32, 0x4a, 0x4f, 0x97, 0x6e, 0x13, 0xe5, 0x4e, 0x53, ...})
/home/runner/work/lnd/lnd/sweeper_wallet.go:24 +0x2c
github.com/lightningnetwork/lnd/sweep.(*UtxoSweeper).removeLastSweepDescendants(0xc00040b000, 0xc00168d000)
/home/runner/work/lnd/lnd/sweep/sweeper.go:588 +0x611
github.com/lightningnetwork/lnd/sweep.(*UtxoSweeper).collector(0xc00040b000, 0xc0004cade0)
/home/runner/work/lnd/lnd/sweep/sweeper.go:713 +0x48e …
```
> Fix panic when canceling rebroadcast for neutrino backend

- routing/router.go
This PR changes the error log for failing to add a node to the graph so that it prints the pub key as hex and not as a byte array.
> routing: log node pubkey as hex

- config_builder.go
- docs/release-notes/release-notes-0.17.0.md
- lnd.go
This modifies the `genMacaroons` logic to indepently check for each of the three default macaroons (admin, readonly, invoice) and generate whichever are missing. Previously, this was an all or nothing routine. In other words, either all three didn't exist on disk and all three are created, or no macaroons are created. Although that works for the first run of a new node, it can result in inconsistent states if only one or two of the macaroons is deleted.
See https://github.com/lightningnetwork/lnd/discussions/7566.
1. Start fresh lnd node and create a wallet.
2. Observer that default macaroons including `admin.macaroon` are created.
3. Delete `admin.macaroon`.
4. Restart lnd node.
5. Observe that `admin.macaroon` has been recreated.
> lnd: generate default macaroons independently

- channeldb/channel.go
- channeldb/legacy_serialization.go
- funding/manager.go
- funding/manager_test.go
- htlcswitch/link.go
- htlcswitch/switch_test.go
A follow-up from https://github.com/lightningnetwork/lnd/pull/7517, found a few more 
instances of the "funding locked" strings (again have left the ones found in any 
migration files)
> multi: catch a few uncaught instances of "funding locked" 

- docs/release-notes/release-notes-0.16.2.md
- go.mod
- go.sum
This version of btcwallet demotes some spammy logs (txns replaced in the mempool), and makes the initial mempool scan async.
Fixes https://github.com/lightningnetwork/lnd/issues/7640
> build: update to btcwallet version with async mempool scan

- docs/release-notes/release-notes-0.17.0.md
- itest/lnd_onchain_test.go
- lnrpc/walletrpc/errors.go
- lnrpc/walletrpc/walletkit_server.go
- lntest/rpc/wallet_kit.go
Fixes https://github.com/lightningnetwork/lnd/issues/7591.
This PR adds a check to the `SendOutputs` RPC to prevent it from undershooting the anchor reserve requirement.
> rpc: anchor reserve check for `SendOutputs`

- htlcswitch/link.go
While analysing a bug this small output redundancy caught my eye, the type SatPerKWeight already has the dimension in it:
```
13:58:28.355 [INF] HSWC: ChannelLink(3d18e199b8b8e3a2da0e905d379125707b5148440d5e9387934cfbf1813bbaac:1): updating commit fee to 750 sat/kw sat/kw
```
> [skip ci] htlcswitch: fix double sat/kw output

- docs/release-notes/release-notes-0.17.0.md
- tls_manager.go
c0f44a17b75784f018652cb382c6ef4cd34d7ae0, available since `v0.16.x`, broke support for certificate private keys encoded in the widely-used
`PKCS8` format.
`PKCS8` is also used by [nix-bitcoin](https://nixbitcoin.org/)'s cert generation scheme for lnd instances.
Consequently, lnd `v0.16.x` is broken on all nix-bitcoin based deployments.
Further reading: [ECDSA private key formats (stackexchange)](https://security.stackexchange.com/a/218410).
This PR has a trivial fix.
To make this more robust and handle some rare edge cases that were previously covered by the prefix check, we might want to use a regexp or a double string match instead.
> Restore support for `PKCS8`-encoded cert private keys

- docs/release-notes/release-notes-0.17.0.md
- funding/batch.go
- lnrpc/marshall_utils.go
- lnrpc/walletrpc/walletkit_server.go
- routing/localchans/manager.go
- rpcserver.go
This commit adds a a new `MarshalOutPoint` helper in the `lnrpc` package that can be used to convert a `wire.Outpoint` to an `lnrpc.Outpoint`. By using this helper, we are less likely to forget to populate both the string and byte form of the TXID.
Fixes https://github.com/lightningnetwork/lnd/issues/7605
> multi: populate both string and byte TXID in lnrpc.Outpoint

- Makefile
- docs/release-notes/release-notes-0.17.0.md
- lnwire/message_test.go
- make/testing_flags.mk
This PR fixes #7152
The benchmark tests failed as described in the issue. Currently the tests produce random data for the `ExtraOpaqueData` field of most of the message types. This can be dangerous as soon as new data is added to a msg type via a tlv record. In this case other tests will fail too, if they use the random data generator for the tlv part.  
The benchmark tests failed now, because the `funding_locked` msg type is the first message in the code base which has an tlv record nested in the overall message type therefore this behaviour was not observed before. Except the `Open_channel` msg but this is a special kind of message because the `upfront_script` has to be always in the tlv_data therefore the tests swap the `ExtraOpaqueData` and encode the relevant `upfront_script` record …
> Fix Benchmark Test (BenchmarkReadMessage/Funding_Locked) in the lnwire  package

- lnrpc/invoicesrpc/invoices.swagger.json
- lnrpc/lightning.pb.go
- lnrpc/lightning.proto
- lnrpc/lightning.swagger.json
This corrects the documentation for the `amt_paid` and `amt_paid_msat` fields on the `Invoice` message to indicate that the fields will be set if the state of the invoice is either accepted or settled, not only settled. This reflects the actual behavior of lnd, as demonstrated in the below `lncli` output:
```
"amt_paid": "10000",
"amt_paid_sat": "10",
"amt_paid_msat": "10000",
"state": "ACCEPTED",
```
> lnrpc: update docs for invoice amt_paid

- docs/release-notes/release-notes-0.17.0.md
- lnwire/fuzz_test.go
We call lnwire's signature parsing and conversion functions from many places in LND, often with untrusted inputs, and existing fuzz tests had incomplete coverage of these functions.
No crashes found after 100+ CPU-hours of fuzzing for each fuzz target.
> lnwire: signature parsing/conversion fuzz tests

- watchtower/blob/type.go
- watchtower/wtclient/client.go
This PR is a small follow up to https://github.com/lightningnetwork/lnd/pull/7380 which added a disk over flow queue to the tower client. 
The first commit adds a few missing error checks. The second commit, changes the identifier used by the client to store its
disk queue under to be a more stable value. This is required because currently, the `blob.Type` `String` method is used to get an identifier but this value is _not stable_ because the name includes any feature bits that it does _not include_. In other words, we could have a situation where we have an anchor client. Its Blob String would return: `[FlagAnchorChannel|FlagCommitOutputs|No-FlagReward]` but then as soon as we start supporting taproot channels and add a taproot client, the value for the anchor client will change to: …
> watchtower: miscellaneous fixes

- .github/workflows/main.yml
- docs/release-notes/release-notes-0.17.0.md
Downloads and extracts the fuzz test seed corpora into the LND tree so that "make unit" automatically runs the fuzz tests on the seeds.
The PR currently uses my own [repository](https://github.com/morehouse/lnd-fuzz-seed-corpus) to host the seeds, since one doesn't exist under https://github.com/lightningnetwork yet.  @Crypt-iQ: Can you set up an official repo for this?
I verified this works by modifying `FuzzAcceptChannel` to fail on certain seed inputs and checking that the fuzz test failure showed up in unit tests in CI.
Updates https://github.com/lightningnetwork/lnd/issues/7452.
> github: run fuzz tests with unit tests

- cmd/lncli/main.go
- docs/release-notes/release-notes-0.17.0.md
Adds ability to global flags to de config using ENV variables.
This is extremely useful when running `lncli` in containers and lnd not using default values or they do not exist at all.
Compile `lncli` run no command or help command manually.
Testing is covered by `urfave/cli` library
> lncli: Global flags to accept ENV vars overrides

- docs/release-notes/release-notes-0.16.3.md
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/linkfailure.go
- peer/brontide.go
In this commit, we add a new LinkFailureDisconnect action that'll be
used if we detect that the remote party hasn't sent a revoke and ack
when it actually should.
Before this commit, we would log our action, tear down the link, but
then not actually force a connection recycle, as we assumed that if the
TCP connection was actually stale, then the read/write timeout would
expire.
In practice this doesn't always seem to be the case, so we make a strong
action here to actually force a disconnection in hopes that either side
will reconnect and keep the good times rollin' 🕺.
Fixes https://github.com/lightningnetwork/lnd/issues/6098
Fixes https://github.com/lightningnetwork/lnd/issues/7682
> htlcswitch+peer: actually actually disconnect if we detect a stalled remote channel state machine 

- docs/release-notes/release-notes-0.17.0.md
- itest/lnd_multi-hop_test.go
- lnrpc/routerrpc/router_server.go
- routing/router.go
Fix an itest flake from [this build](https://github.com/lightningnetwork/lnd/actions/runs/5044112934/jobs/9046751557),
```
lnd_max_htlcs_test.go:141: 
Error Trace:	/home/runner/work/lnd/lnd/itest/lnd_max_htlcs_test.go:141
/home/runner/work/lnd/lnd/itest/lnd_max_htlcs_test.go:40
/home/runner/work/lnd/lnd/itest/harness.go:286
/home/runner/work/lnd/lnd/itest/lnd_test.go:136
Error:      	Should be empty, but was [attempt_id:4  route:{total_time_lock:1336  total_amt:10  hops:{chan_id:1372190511529985  chan_capacity:1000000  amt_to_forward:10  expiry:1336  amt_to_forward_msat:10000  pub_key:"03262458bb5f1c0684b26b595ae5a01fd64217d0087a481d62e61fb15f474f7014"  tlv_payload:true  mpp_record:{payment_addr:"W\x1d\x01\x0f\xd4W\xa8\xfc\xa5\xf6\xf4\xa2\xeanU\xd1\xcaw\x1c\xb6p\x86\xd2\xe7\xd1\xf4\x97v\x0 …
```
> routing+lnrpc: subscribe payment stream before sending it

- input/script_utils.go
- input/script_utils_test.go
- input/taproot.go
- input/taproot_test.go
- input/test_utils.go
In this commit, we add the current draft set of taproot scripts, control block handling logic, and also spending routines. 
Reviewers will want to be familiar with the current spec draft before diving in: https://github.com/Roasbeef/lightning-rfc/blob/simple-taproot-chans/bolt-simple-taproot.md
This PR is a draft PR, as it still needs tests for all the new routines (they work in #6877) and also the witness estimate constants to be updated. 
> [2/?] - input: add taproot chan scripts, control block logic, and spending routines 

- contractcourt/htlc_timeout_resolver.go
- contractcourt/utxonursery.go
- docs/release-notes/release-notes-0.16.3.md
In this commit, we attempt to fix an issue that may lead to force closes due to small value HTLCs. The sweeper has built in a "negative yield" heuristic where it won't sweep something that'll result in paying more fees than the HTLC amount. However for HTLCs, we want to always sweep them, as we don't cancel back the HTLCs before the outgoing contract is fully resolved.
In the future, we'll start to make more economical decisions about if we should go to chain at all for small value HTLCs, and also do things like cancel back early if the HTLC is small and we think we might be contested by chain fees.
> contractcourt: force the sweeper to always resolve outgoing HTLCs

- build/version.go
- contractcourt/htlc_timeout_resolver.go
- contractcourt/utxonursery.go
- docs/release-notes/release-notes-0.16.3.md
- go.mod
- go.sum
- htlcswitch/link.go
- htlcswitch/link_test.go
- htlcswitch/linkfailure.go
- itest/lnd_mpp_test.go
- itest/lnd_multi-hop_test.go
- itest/lnd_switch_test.go
- lntest/harness.go
- macaroons/store.go
- macaroons/store_test.go
- peer/brontide.go
This PR makes a new release branch for a point release to further improve performance of the new mempool logic, and also fix a bug to ensure we try to force a reconnect if a connection or remote stale machine seems stalled. 
Included PRs:
* https://github.com/lightningnetwork/lnd/pull/7705
* https://github.com/lightningnetwork/lnd/pull/7711 (pending build) 
* https://github.com/lightningnetwork/lnd/pull/7681
Milestone: https://github.com/lightningnetwork/lnd/milestone/44
> build: create v0.16.3 release branch

- docs/release-notes/release-notes-0.17.0.md
- lnrpc/rpc_utils.go
- rpcserver.go
- sweep/walletsweep.go
- sweep/walletsweep_test.go
Fixes #7512 by enforcing that if a manual fee rate is provided in RPC calls then that fee rate is no less than the relay fee of the underlying chain node. To achieve this, as suggested, the `calculateFeeRate()` function was refactored out of `rpcserver.go` and into `rpc_utils.go`, and reused in `walletkit_server.go`. This way `FundPsbt` rpc call can use the same fee estimation logic as `OpenChannel`, `SendCoins`, etc. `FundPsbt` will be handled in a follow-up PR.
I've tried my best to follow the required practices (code style, linting, comments etc.). Since this is my first PR, I'd love any feedback about what I may have overlooked :slightly_smiling_face: 
Attempt any one of the rpc calls whilst providing a manual sat per vbyte which would fall below the relay fee of the chain node that …
> sweep+lnrpc: enforce provided fee rate is no less than relay fee

- contractcourt/channel_arbitrator.go
Update the logs to differentiate which set of dangling HTLCs is canceled.
> contractcourt: improve logging for failing dangling htlcs

- config.go
- docs/release-notes/release-notes-0.17.0.md
- lnd.go
- sample-lnd.conf
Fixes https://github.com/lightningnetwork/lnd/issues/7727.
Adds the following new config options to `lnd`:
```
grpc:
--grpc.server-ping-time=                                               How long the server waits on a gRPC stream with no inactivity before pinging the
client. (default: 1m0s)
--grpc.server-ping-timeout=                                            How long the server waits for the response from the client for the keepalive ping
response. (default: 20s)
--grpc.client-ping-min-wait=                                           The minimum amount of time the client should wait before sending a keepalive ping.
(default: 5s)
```
Tested with a node.js client (`GRPC_TRACE=all GRPC_VERBOSITY=DEBUG node test.js`):
```
let lightning = new lnrpc.Lightning(
'localhost:10019', credentials, …
```
> config+grpc: allow configuring gRPC keepalive params

- docs/release-notes/release-notes-0.17.0.md
- watchtower/wtclient/fuzz_test.go
Test `AddressIterator` for the absence of panics, nil addresses, and empty lists.
This fuzz test exercises every line of code in `watchtower/wtclient/addr_iterator.go` and finds https://github.com/lightningnetwork/lnd/issues/7552 in seconds. No other panics found after 300 CPU-hours of fuzzing.
> wtclient: AddressIterator fuzz test

- cmd/lncli/walletrpc_active.go
- docs/release-notes/release-notes-0.17.0.md
- itest/lnd_wallet_import_test.go
- lntest/rpc/wallet_kit.go
- lnwallet/btcwallet/btcwallet.go
- lnwallet/btcwallet/psbt.go
This PR fixes: https://github.com/lightningnetwork/lnd/issues/7265
1) fix non-deterministic behaviour for custom accounts with same name but different key scopes (ListAccounts/LookupAccount)
2) Forbid users to create a custom account if the name is already used
This PR was tested, here are the steps to test:
1) -> You will need to cherry-pick the two first commit (otherwise the 3rd commit will prevent you from create 2 custom accounts with the same name). Then import 2 accounts (different key scope but same name) and check if `ListAccounts` returns the 2 accounts (and not only one as before)
2) -> Now, you can include the 3rd commit, check that you cant import 2 accounts with the same name anymore
> Fix non-deterministic behaviour for custom accounts

- config.go
- docs/release-notes/release-notes-0.17.0.md
- lncfg/watchtower.go
- lncfg/wtclient.go
- sample-lnd.conf
- server.go
- watchtower/conf.go
Add `DefaultWtclientCfg` and `DefaultWatchtowerConfig` functions that populate 
defaults for the `lncfg.Wtclient` and `lncfg.Watchtower` config structs. These are 
then used in the main LND config struct so that the defaults are shown to a user  in 
the `lnd --help` command. 
This PR also removes the deprecated `PrivateTowerURIs` member from the `Wtclient`
config struct since it has been deprecated since `v0.8.0-beta` and currently LND would
fail to start if a user specified it. 
Fixes #7769
> multi: add tower config defaults

- channeldb/channel.go
- channeldb/channel_test.go
- contractcourt/briefcase_test.go
- contractcourt/htlc_incoming_contest_resolver.go
- contractcourt/htlc_incoming_resolver_test.go
- contractcourt/htlc_outgoing_contest_resolver_test.go
- contractcourt/htlc_success_resolver_test.go
- docs/release-notes/release-notes-0.17.0.md
- lnmock/routing.go
- lnwallet/channel.go
Opening this in draft to illustrate the scope of a possible solution for #7297. 
This PR demonstrates a workaround for persisting TLV data that is transmitted in `update_add_hltc`: 
- HTLCs are serialized inline (so we can't easily add on another field, because we wouldn't know when it is / isn't there easily).
- The `OnionBlob` for HTLCs is serialized as var bytes, but we know this will *always* be 1366 bytes (as the [spec](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#adding-an-htlc-update_add_htlc) demands).
- We can use this variable encoding to squeeze in our TLVs as follows: 
- Write `OnionBlob` + `TLVStream` as a _single_ var bytes blob where we previously had just `OnionBlob`
- This will write a lengh prefix of `1366 + len(TLV stream)`
- To deserialize, read …
> Channeldb: Store HTLC Extra TLVs in Onion Blob Varbytes

- itest/lnd_open_channel_test.go
- itest/lnd_zero_conf_test.go
- lntest/btcd.go
- lntest/harness_miner.go
- peer/brontide.go
- server.go
Some code changes from working on other issues - one commit for decreasing duplication round temp miner creation and the other for more verbose logging.
> Better temp miner management and more verbose loggings

- lnd.go
Add debug logs in case syncing to blockchain is too slow.
> lnd: add debug log when syncing blocks

- scripts/check-release-notes.sh
Without this commit, PRs can fail to be merged via the merge queue, as it'll fail with this error:
```
Run scripts/check-release-notes.sh
PR gh-readonly-queue didn't update release notes
Error: Process completed with exit code 1.
```
Sample failugre: https://github.com/lightningnetwork/lnd/actions/runs/5274576933/jobs/9539169490
> scripts: update release notes check for merge queue usage

- config.go
- docs/release-notes/release-notes-0.17.0.md
- funding/manager_test.go
Relates to #7770 where we found that this asymmetry is not really practical especially because a node runner can suffer from a peer burdening him with a csv delay for the local outputs of almost 10 weeks.
> Change defaultMaxLocalCSVDelay to protect user from high delays

- tor/tor.go
With this commit we avoid calling LookupHost if we already have an IPv4 or IPv6 address, as we can return that directly.
This avoids asking Tor to resolve an IPv6 address, which it cannot do.
See https://github.com/lightningnetwork/lnd/issues/6493 for context.
This does not yet fix that issue, as we'll need to push a tag for the `tor` submodule first and create another PR. That's why this one also doesn't contain a change log and skips integration tests.
> tor: short circuit host lookup if connecting to IP

- lnrpc/walletrpc/walletkit_server.go
This PR exports the existing `walletkit` function
```
unmarshallOutPoint(op *lnrpc.OutPoint) (*wire.OutPoint, error)
```
I think this function should be exported because it is useful when interpreting RPC return data.
This PR also modifies `unmarshallOutPoint` such that it accepts an `lnrpc.OutPoint` which has both txid fields populated. I think this change is useful because some RPC endpoints return `lnrpc.OutPoint` with both txid fields populated (`WalletKit.ListLeases` is one such RPC endpoint). I don't see why it should raise an error rather than make a best attempt at unmarshalling.
Ensure unit tests and itests pass.
> Export unmarshall outpoint functionality

- go.mod
- go.sum
This is necessary after #7796 to apply the change made in the kvdb submodule to the main module.
> mod: bump kvdb submodule to v1.4.2

- log.go
Found this issue while debugging the mempool issue. This commit fixed a wrong ordering of initializing subsystem loggers. We need to make sure "third party" loggers are initialized first such that when we customize the names later in `lnd`'s packages, the overwriting of the logger names will take effect.
> lnd: fix orders when initializing subsystem loggers

- funding/manager.go
- peer/brontide.go
- peer/test_utils.go
This PR extracts the first 5 commits from #7518 to provide a better view experience. In this PR, we focus on replacing normal maps with `SyncMap`, providing abstracted methods to determine a given channel's state(pending/active/loaded from disk), and adding a new method `handleNewActiveChannel` to handle new channels in a more structured manner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/7794)
> brontide: refactor peer to prepare channel ready fix

- docker/btcd/Dockerfile
docker-compose run -d --name alice --volume simnet_lnd_alice:/root/.lnd lnd
=> ERROR [builder 4/4] RUN git clone https://github.com/btcsuite/btcd.git .     && git checkout v0.23  6.2s
------
> [builder 4/4] RUN git clone https://github.com/btcsuite/btcd.git .     && git checkout v0.23.5     && go install -v . ./cmd/...:
#0 0.253 Cloning into '.'...
#0 6.059 error: pathspec 'v0.23.5' did not match any file(s) known to git ------
failed to solve: executor failed running [/bin/sh -c git clone https://github.com/btcsuite/btcd.git .     && git checkout $BTCD_VERSION     && go install -v . ./cmd/...]: exit code: 1
```
$cd docker 
$docker-compose run -d --name alice --volume …
```
> Fix docker compose run issue
