docs/release-notes/release-notes-0.17.0.md, htlcswitch/link.go, htlcswitch/link_test.go, invoices/invoiceregistry_test.go, invoices/update.go
This change addresses #7589. The spec was updated [here](https://github.com/lightning/bolts/pull/1032/files) and [here](https://github.com/lightning/bolts/pull/1063) to relax the final hop htlc integrity checks, allowing the final htlc to have a higher payment amount or a higher cltv delta than what is specified in the onion packet.
**Please take special care to review the test cases**. I believe they currently capture all of the invariants we are trying to satisfy as specified in the spec change. However, it appears as though there is some ambiguity related to what these checks are for. According to the spec these are integrity checks to make sure that the incoming HTLC is *more favorable* than what is specified in the packet (presumably to detect any tampering along the route). However, …
=> invoices+htlcswitch: fix spurious htlc rejections from overly strict onion packet integrity checks

docs/release-notes/release-notes-0.17.0.md, tls_manager.go, tls_manager_test.go
As the getConfig() function would previously overwrite the GetCertificate function of the tls config, the autocert manager would never be used.
This PR moves the `setUpLetsEncrypt` func to where it would correctly override the `GetCertificate` function.
Closes https://github.com/lightningnetwork/lnd/issues/7734
=> tlsmanager: fix autocert autogeneration

docs/release-notes/release-notes-0.17.0.md, go.mod, go.sum
Depends on https://github.com/lightningnetwork/lnd/pull/7782.
Fixes https://github.com/lightningnetwork/lnd/issues/6493.
=> mod: bump tor submodule to v1.1.1

invoices/invoiceregistry_test.go
Fixes: #7825.
I think the tests in this part of the codebase could use some cleanup (more trivial data races _asking_ to happen the way we have it now), but that can follow IMO. This is the smallest possible fix to address the current race to clear up uphappy builds ❌
=> invoices/test: fix data race in TestMppPaymentWithOverpayment

docs/release-notes/release-notes-0.17.0.md, htlcswitch/interfaces.go, server.go, watchtower/wtclient/client.go, watchtower/wtclient/client_test.go, watchtower/wtclient/interface.go, watchtower/wtclient/session_queue.go, watchtower/wtdb/client_db.go, watchtower/wtdb/client_db_test.go, watchtower/wtmock/client_db.go
This PR demonstrates 2 main issues and then fixes them:
1. If `backupTasks` have been "bound" to a session's `pendingQueue` and then the associated Tower is removed, those pending updates are just quietly lost at the moment. This PR makes sure that these tasks are replayed onto the main task pipeline.
2. If a `CommittedUpdate` has been persisted but the session does not respond with an Ack and then the client requests to remove the tower, this will currently fail with "tower has unacked updates". This is fixed by also replaying these updates onto the main task pipeline.
With this PR, the tower client can shutdown as soon as it is requested to since any un-acked updates or pending updates will just be persisted. This is nice since there will no longer be a 10 second wait on shutdown :) …
=> wtclient: replay pending and unacked updates

docs/release-notes/release-notes-0.17.0.md, zpay32/fuzz_test.go
Even after 200+ CPU hours, the fuzzer was unable to generate *any* serialized invoices with a valid checksum (see https://github.com/lightninglabs/lnd-fuzz/pull/5#issue-1673287212).  This PR helps the fuzzer out by appending the required checksum manually.  As a result, the fuzz tests now have pretty decent coverage of both invoice decoding and encoding.
The PR also contains other minor improvements and simplifications of the fuzz tests.
=> zpay32: improve fuzz tests

channeldb/channel.go, contractcourt/breacharbiter_test.go, contractcourt/chain_watcher_test.go, htlcswitch/link.go, htlcswitch/link_isolated_test.go, htlcswitch/link_test.go, input/musig2_session_manager.go, lnwallet/chancloser/chancloser.go, lnwallet/chancloser/chancloser_test.go, lnwallet/chancloser/interface.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/chanvalidate/validate.go, lnwallet/commitment.go, lnwallet/musig_session.go, lnwallet/revocation_producer.go, lnwallet/revocation_producer_itest.go, lnwallet/sigpool.go, lnwallet/test_utils.go, lnwallet/transactions.go, lnwallet/transactions_test.go, lnwallet/wallet.go, peer/brontide.go, peer/musig_chan_closer.go
In this PR, we update the channel state machine to be aware of the new musig2 flow. Along the way, we update some util functions to ensure we can use them to generate scripts/transactions for both segwit v0 and v1 channels. 
In this new flow, each time we send a signature, we sig a partial sig along with the nonce that we used to sign. Upon receiving that signature, the remote party will use the nonce to complete their local session (for that state).
Each time a signature is received, a party will generate another nonce that'll be used to create their next local state. This next local/verification nonce is then sent alongside the revoke_and_ack message. Upon receiving the revocation, the party that originally sent the sig, can then use the new local nonce to prep the session for the next …
=> [6/?] - lnwallet+chancloser: update channel state machine and co-op close for musig2 flow

docs/release-notes/release-notes-0.17.0.md, itest/lnd_network_test.go
This makes the test work even if the local OS has no outside network connections available or if DNS lookups are failing.
This was motivated because I was running the complete set of tests while being offline from the internet, thus the DNS queries for "lightning.engineering" were failing (instead of the desired connection timeout).
This also has a small privacy benefit because it prevents announcing to the upstream DNS providers whenever you're running the suite of tests.
=> itest: bind to local addr in network test

invoices/invoiceregistry_test.go, invoices/test_utils_test.go
~Depends on #7826 (just the first commit).~ Rebased!
This PR cleans up some of the test values used in invoice registry tests: 
* Move away from global variables that can be mutated, using constructors where appropriate 
* Make all tests parallel, so that any "hidden races" between tests that are run in series are revealed 
* Simplify the ambiguously named global vars (testInvoiceAmt vs testInvoiceAmount, fml)
=> invoices/test: Cleanup Invoice Registry Tests

contractcourt/chain_watcher.go, discovery/mock_test.go, feature/default_sets.go, feature/deps.go, funding/commitment_type_negotiation.go, funding/manager.go, funding/manager_test.go, htlcswitch/link.go, htlcswitch/link_test.go, htlcswitch/mock.go, lnpeer/peer.go, lntest/mock/signer.go, lnwallet/channel.go, lnwallet/musig_session.go, peer/brontide.go, routing/router.go
Depends on https://github.com/lightningnetwork/lnd/pull/7345. 
Only the **last 6 commits** are new. 
In this PR, we build on the prior PR that updated the channel state machine to update the funding manager to be aware of the new funding flow. 
This flow is identical to the existing flow, but both sides need to exchange local nonces up front, and then signatures sent are now partial signatures instead of regular signatures.
The funding manager also gains some new state of the local nonces it needs to generate in order to send the funding locked message, and also process the funding locked message from the remote party.
In order to allow the funding manger to generate the nonces that need to be applied to each channel, then AddNewChannel method has been modified to accept a set of options …
=> [7/?] - funding: update funding manager w/ new musig2+taproot funding flow 

docs/release-notes/release-notes-0.17.0.md, peer/brontide.go
In this commit, we make sure that all the `wg.Add(1)` calls succeed
before we attempt to wait on the shutdown of all the goroutines. Under
rare scheduling scenarios, if both `Start` and `Disconnect` are called
concurrently, then this internal race error can be hit, causing the
panic to occur.
Fixes https://github.com/lightningnetwork/lnd/issues/7853
=> peer: ensure the peer has been started before Disconnect can be called

routing/router.go, routing/router_test.go
Make sure that we do not crash the node trying to access an invalid position for an array (-1) in `BuildRoute`.
Fixes https://github.com/lightningnetwork/lnd/issues/7798
=> routing: fix `index out of range` panic

htlcswitch/mailbox.go
The goroutine is very long and littered with switches on `courierType`. By separating the implementation into different methods for each `courierType` we eliminate the cruft and improve readability.
=> htlcswitch: split mailCourier by courierType

chainntnfs/test/test_interface.go, chainntnfs/txnotifier.go
Noticed this while updating to latest `master` in another project: If there are two notifications for the same output being registered and the first one does _NOT_ request the block to be included, then the second one also will not receive the block, even if it explicitly requests it.
This is caused by the block being removed from the original confirmation set instead of a copy (as it is done in `NotifyHeight` and `UpdateConfDetails`).
Fixes https://github.com/lightningnetwork/lnd/issues/7501
=> chainntnfs: remove block info from conf detail copy

lnd.go, rpcserver.go
This commit moves the registration of the State server with a REST proxy into the `RegisterWithRestProxy` method in order to keep all the REST registrations in one place.
=> refactor: move State server REST registration

.golangci.yml, config.go, discovery/mock_test.go, docs/release-notes/release-notes-0.17.0.md, funding/manager.go, funding/manager_test.go, htlcswitch/link_test.go, htlcswitch/mock.go, itest/list_on_test.go, itest/lnd_open_channel_test.go, lncfg/dev.go, lncfg/dev_integration.go, lnpeer/mock_peer.go, lnpeer/peer.go, peer/brontide.go, peer/brontide_test.go, server.go
Depends on 
- #7517 
- https://github.com/lightninglabs/neutrino/pull/279
- #7794 
This PR starts tracking pending open channels in `peer.Brontide`. Suppose a message is received for this pending channel, it will be cached and processed once this channel becomes active.
Fixes #7401
=> Fix race between `channel_ready` and link update

docs/release-notes/release-notes-0.17.0.md, lnwallet/wallet.go, rpcserver.go
Resulted from discussions in #7746.
Short follow-up PR which makes sure we do not end up confirming a channel although we already abandoned it.
More detailed description [here](https://github.com/lightningnetwork/lnd/pull/7746#discussion_r1249338471)
=> Cancel the Rebroadcasting of a Transaction when Abandoning a Channel

cmd/lncli/commands.go, rpcserver.go
Trivial typo and format fixes.
=> typos: fix updatechanpolicy typos

docs/release-notes/release-notes-0.17.0.md, funding/commitment_type_negotiation.go, funding/commitment_type_negotiation_test.go, funding/manager.go, funding/manager_test.go
The bug manifests when a nil `ChannelType` is passed to the funding manager in `InitFundingMsg`. A default value for `ChannelType` is selected and sent in the `OpenChannel` message. However, a nil `ChannelType` is stored in the reservation context. This causes our `ChannelType` checks in `handleFundingAccept` to be bypassed.
Usually this makes us end up in the "peer unexpectedly sent explicit `ChannelType`" case, where we can still recover by reselecting a default `ChannelType` and verifying it matches the one the peer sent. But if the peer sends a nil `ChannelType`, we miss it.
While fixing the bug, I also tried to simplify the negotiation logic, as the complexity is likely what hid the bug in the first place.
Now `negotiateCommitmentType` only returns the `ChannelType` to be used in …
=> funding: fix channel type negotiation bug

contractcourt/channel_arbitrator.go, contractcourt/htlc_success_resolver.go, input/input.go, sweep/sweeper.go
Found some trivial issues during code reviews. This PR fixes/improves the logging, renamed a variable name to avoid confusion, and, makes sure registration for confirmation notification happens before publishing the tx.
=> trivial: fix loggings, variable names and conf notification order

lnwire/lnwire_test.go
Found a unit test flake from [this build](https://github.com/lightningnetwork/lnd/actions/runs/5888391278/job/15969508055?pr=7881), turns out we need to subtract the 2 bytes used to encode the padding bytes length.
=> trivial: fix unit test flake for `Ping` message

chainreg/chainregistry.go, channeldb/db.go, channeldb/forwarding_policy.go, channeldb/models/channel.go, funding/manager.go, funding/manager_test.go, htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/link_test.go, htlcswitch/mock.go, htlcswitch/switch.go, htlcswitch/test_utils.go, peer/brontide.go, routing/localchans/manager.go, routing/localchans/manager_test.go, server.go
Partially reverts changes of #7597, in order to fix an itest flake.
=> funding: fix flake in itest caused by persistent fee param changes

channeldb/migration_01_to_11/route.go, docs/release-notes/release-notes-0.17.0.md, go.mod, go.sum, routing/route/route.go
Update the lighting-onion dependency to include the latest changes 
which support route blinding.
Opening in draft mode for now since a replace directive is still used. 
Depends on https://github.com/lightningnetwork/lightning-onion/pull/57
This is required for https://github.com/lightningnetwork/lnd/pull/7267
=> multi: update lightning-onion version

docs/release-notes/release-notes-0.17.0.md
Added a table of contents at the top and various sections to navigate to, to make it easy to parse and read the release notes.
=> Release notes for 0.17 updated to the new format

.github/workflows/main.yml, .github/workflows/release.yaml, .travis.yml, build/version.go, dev.Dockerfile, make/builder.Dockerfile
With this PR, we kick off the start of the v0.17 rc cycle. We first update the build system to use the latest version of Go, then bump to the latest v0.17.0 rc1 version.
=> build: bump Go version to v1.21.0, lnd version to v0.17.0 rc1

channeldb/channel.go, docs/release-notes/release-notes-0.17.0.md
In the release notes for [v0.17.0](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.17.0.md), it states to use the startup flag `--simple-taproot-channels` but the correct flag is named `--simple-taproot-chans`. This PR just updates this typo. 
I also found one more reference to `simple-taproot-channels` in a comment of the [channel.go](https://github.com/jamaljsr/lnd/blob/79b766579c3d709e86e8400d18e90c3cdd9b8893/channeldb/channel.go) file so I fixed that as well.
This fixes only documentation and code comments. There are no test steps to perform.
=> docs: fix simple-taproot-channels typo [skip ci]

itest/lnd_channel_backup_test.go
Changed "chanenl" to "channel"
=> itest: fix typo [skip ci]

itest/list_on_test.go, itest/lnd_psbt_test.go, itest/lnd_remote_signer_test.go, lntest/harness.go, lnwallet/chanfunding/psbt_assembler.go
Fixes https://github.com/lightningnetwork/lnd/issues/7929.
Also adds PSBT funding integration tests for simple taproot channels.
Adding the `no-changelog` label as this is part of the RC bug fixing effort.
=> psbt: fix channel funding address for simple taproot channels

contractcourt/channel_arbitrator.go
Related to this fix https://github.com/lightningnetwork/lnd/commit/5a285827194f85af10c138da735b35a1faee97aa, we may not have the historical data for old channels so we skip it here too.
Fixes #7935
=> contractcourt: fix potential panic during startup

peer/brontide.go
In this commit, we attempt to fix circular waiting scenario introduced inadvertently when [fixing a race condition
scenario](https://github.com/lightningnetwork/lnd/pull/7856). With that PR, we added a new channel that would block `Disconnect`, and `WaitForDisconnect` to ensure that only until the `Start` method has finished would those calls be allowed to succeed.
The issue is that if the server is trying to disconnect a peer due to a concurrent connection, but `Start` is blocked on `maybeSendNodeAnn`, which then wants to grab the main server mutex, then `Start` can never exit, which causes `startReady` to never be closed, which then causes the server to be blocked.
This PR attempts to fix the issue by calling `maybeSendNodeAnn` in a goroutine, so it can grab the server mutex and not …
=> peer: eliminate circular waiting by calling maybeSendNodeAnn async

docs/release-notes/release-notes-0.17.0.md, htlcswitch/link.go, htlcswitch/linkfailure.go, kvdb/sqlbase/db.go, kvdb/sqlbase/readwrite_tx.go, lnwallet/channel.go, peer/brontide.go
This PR resolves two outstanding issues:
1. If a revoke failed in the past, we wouldn't tear down the link. This could lead to desynchornized state, eventually leading to a force close. 
2. For the `kvdb` SQL emulation backends, if we got an error (`SQLITE_BUSY`, etc), we should just fail right then. We now implement an exponential back off with some jitter to give other writing goroutines time to finish/interleave their writes. 
For 1, I tacked on an extra commit to just tear down the link all together. This may save us from a scenario where Alice had a DB failure, Bob then tries to send a new state, but Alice has torn down the link, but _not_ the TCP connection. In this case, Bob is now "stuck" as she's sent out a sig, and if Alice never recovers, they may need to go on chain to time …
=> multi: ensure link is always torn down due to db failures, add exponential back off for sql-kvdb failures

.github/workflows/main.yml, Makefile, kvdb/go.mod, kvdb/go.sum, kvdb/sqlbase/db.go, kvdb/sqlbase/sqlerrors.go, scripts/tidy_modules.sh, scripts/unit_test_modules.sh
Realized the params used in `randRetryDelay`, causing us to always wait for 5s after the first attempt.
=> kvdb/sqlbase: fix params used in `randRetryDelay`

aezeed/cipherseed_test.go, chainntnfs/bitcoindnotify/bitcoind_test.go, contractcourt/taproot_briefcase_test.go, lnwallet/chainfee/estimator.go, lnwallet/chainfee/estimator_test.go
Fix three uint test flakes,
```
--- FAIL: TestWebAPIFeeEstimator (5.00s)
--- FAIL: TestWebAPIFeeEstimator/API-omitted_target (0.00s)
estimator_test.go:253: 
Error Trace:    /home/runner/work/lnd/lnd/lnwallet/chainfee/estimator_test.go:253
Error:          Not equal: 
expected: 25300
actual  : 253
Test:           TestWebAPIFeeEstimator/API-omitted_target
Messages:       target 2 failed, fee map is map[20:101200 100:42]
--- FAIL: TestWebAPIFeeEstimator/valid_target (0.00s)
estimator_test.go:253: 
Error Trace:    /home/runner/work/lnd/lnd/lnwallet/chainfee/estimator_test.go:253
Error:          Not equal: 
expected: 25300
actual  : 253
Test:           TestWebAPIFeeEstimator/valid_target
Messages:       target 20 failed, fee map is map[20:101200 100:42]
--- FAIL: …
```
=> multi: fix unit test flakes

contractcourt/htlc_timeout_resolver.go
We added this change in #7726, but it was removed in master, probably due to recent rebase.
=> contractcourt: make sure we force sweep outgoing htlcs

docs/release-notes/release-notes-0.17.0.md, lnrpc/websocket_proxy.go
In this commit, we increase the max message size for the ws proxy. We have a similar setting for the normal gRPC server which was tuned to be able to support decoding `GetNetworkInfo` as the channel graph got larger. We keep the default buffer size of 64 KB, but allow that to be expanded to up to 4 MB (current value) to decode larger messages.
One alternative would be to modify the `Split` function to break up larger lines into smaller ones. We'd need to double check that the libraries at a higher level of abstraction can handle the chunks. The scan function would look something like:
```go
splitFunc := func(data []byte, eof bool) (int, []byte, error) {
if len(data) >= chunkSize {
return chunkSize, data[:chunkSize], nil
}
return bufio.ScanLines(data, eof))
}
scanner.Split(splitFunc)
```
=> lnrpc: increase max message size for ws proxy

config.go, docs/release-notes/release-notes-0.17.0.md, lnd.go, sample-lnd.conf
In this commit, we add the ability to obtain blocking and mutex profiles. The blocking profile will show which goroutines are consistently blocked on synchronization primitives like channels, or I/O. The mutex profile will show which mutexes are very contested.
The blocking profile can be enabled with a new arg: `--blockingprofile`. The mutex profile can be enabled with a new arg: `--mutexprofile`. These are both ignored if the profile port isn't set.
Activating these profiles requires the caller to pass in a sampling rate. For now I've set it just to `1` to test things out. Unfortunately documentation is rather scarce, so there aren't any good guides re what these values should be set to. AFAICT, these add more overhead than the other prowling options, so they shouldn't necessarily be …
=> lnd+config: add ability to obtain blocking and mutex profiles

lnwire/onion_error.go, lnwire/onion_error_test.go
For about [a year](https://github.com/lightning/bolts/pull/979), the spec has prescribed encoding `channel_updates` with their type prefix (`0x0102`) in onion failure messages. LND can decode correctly with or without the prefix but hasn't been writing the prefix during encoding. This PR starts writing the prefix.
I ran across this while running some new encoding/decoding fuzz tests for onion errors, which I intend to submit in a separate PR.  Those fuzz tests offer additional regression testing for this change.
Resolves https://github.com/lightningnetwork/lnd/issues/6461.
=> lnwire: encode channel_update type in onion errors

Makefile, chainntnfs/bitcoindnotify/bitcoind.go, chainntnfs/btcdnotify/btcd.go, chainntnfs/mempool.go, chainntnfs/neutrinonotify/neutrino.go, chanbackup/pubsub.go, chanfitness/chaneventstore.go, channelnotifier/channelnotifier.go, contractcourt/breacharbiter.go, contractcourt/chain_arbitrator.go, contractcourt/utxonursery.go, discovery/gossiper.go, funding/manager.go, healthcheck/healthcheck.go, htlcswitch/hop/iterator.go, htlcswitch/htlcnotifier.go, htlcswitch/switch.go, invoices/invoiceregistry.go, netann/chan_status_manager.go, netann/host_ann.go, peernotifier/peernotifier.go, routing/missioncontrol.go, routing/router.go, scripts/itest_parallel.sh, server.go, sweep/sweeper.go
When one of the itest tranches fails, because we are running tests in parallel, other tranches will still be running, which caused 7z to fail at zipping the logs because race reads. This commit fixes it by making sure we are waiting for other tranches to finish because moving to zipping and uploading the logs.
=> itest: fix itest logs upload

config.go, docs/release-notes/release-notes-0.18.0.md, itest/lnd_onchain_test.go, lncfg/sweeper.go, lnwallet/chainfee/rates.go, lnwallet/chainfee/rates_test.go, rpcserver.go, sample-lnd.conf, server.go, sweep/defaults.go, sweep/sweeper.go, sweep/sweeper_test.go, sweep/tx_input_set.go, sweep/tx_input_set_test.go, sweep/txgenerator.go, sweep/txgenerator_test.go, sweep/walletsweep.go, sweep/walletsweep_test.go, sweep/weight_estimator.go, sweep/weight_estimator_test.go
This PR decreases the max fee rate by 10x and makes it configurable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/7823)
=> sweeper: lower the default max fee rate and make it configurable

.github/workflows/release.yaml
I assume this is the correct place to do this.
=> Fix capitalization of OpenTimestamps in release notes

peer/brontide.go
This PR is a follow up, to a [follow
up](https://github.com/lightningnetwork/lnd/pull/7938) of an [initial concurrency issue](https://github.com/lightningnetwork/lnd/pull/7856) fixed in the peer goroutine.
In #7938, we noticed that the introduction of `p.startReady` can cause `Disconnect` to block. This happens as `Disconnect` cannot be called until `p.startReady` has been closed. `Disconnect` is also called from `InboundPeerConnected` (the case of concurrent peers, so we need to remove one of the connections) while the main server mutex is held. If `p.Start` blocks for any reason, then this leads to the deadlock as: we can't disconnect until we've finished starting, and we can't finish starting as we need the disconnect caller to exit as it has the mutex.
In this commit, we now make the …
=> peer: launch persistent peer pruning in background goroutine

itest/list_on_test.go, itest/lnd_payment_test.go, lnwallet/channel.go, rpcserver.go
Fix the weight calculation found in multiple places.
Fix #8036
=> lnwallet+rpcserver: fix weight calculation for taproot channels

funding/manager.go, lnwallet/test/test_interface.go, lnwallet/wallet.go, lnwallet/wallet_test.go
A follow up PR from #7518, this PR removes the unused `newChanBarriers`, renames some of the methods for clarity, and adds a sanity check to make sure `pendingChanID` is not set to zero.
=> funding: remove dead code and sanity check pending chan ID

tlv/fuzz_test.go
Based on https://github.com/lightningnetwork/lnd/pull/4641.
=> tlv: fuzz test encoding/decoding

.github/workflows/main.yml, scripts/itest_parallel.sh
For some reason lnd doesn't properly shut down on some windows itests, and the process still running makes it impossible to access its log files.
So for the Windows integration test, we attempt to kill the whole process tree once the process indicates it is done.
Replaces https://github.com/lightningnetwork/lnd/pull/8015, can't re-open because base branch doesn't exist anymore (restoring didn't allow me to change base unfortunately).
=> scripts: kill lnd on windows to access log files

docs/release-notes/release-notes-0.17.1.md, htlcswitch/hop/iterator.go, itest/lnd_misc_test.go
The link will send an update_fail_malformed_htlc, so we need to set the BADONION bit. Since there isn't a replay-specific error, we set the failure code to InvalidOnionVersion which has the BADONION bit.
It would be nice if there was a replay-specific failure code in the spec
Fixes https://github.com/lightningnetwork/lnd/issues/7851, https://github.com/lightningnetwork/lnd/issues/5792, https://github.com/lightningnetwork/lnd/issues/5443
=> htlcswitch/hop: use InvalidOnionVersion for replayed packets

channeldb/db.go, channeldb/invoice_test.go, channeldb/invoices.go, contractcourt/channel_arbitrator.go, contractcourt/interfaces.go, contractcourt/mock_registry_test.go, docs/release-notes/release-notes-0.18.0.md, htlcswitch/interfaces.go, htlcswitch/link_test.go, htlcswitch/mock.go, htlcswitch/switch_test.go, htlcswitch/test_utils.go, invoices/interface.go, invoices/invoiceregistry.go, invoices/invoiceregistry_test.go, lnrpc/invoicesrpc/addinvoice.go, lnrpc/invoicesrpc/invoices_server.go, rpcserver.go
In preparation of the SQL based `InvoiceDB` implementation (draft in https://github.com/lightningnetwork/lnd/pull/8052) we add context to all `InvoiceDB` methods. This in turn results in some of the `InvocieRegistry` methods also requiring external context passed in.
Part of https://github.com/lightningnetwork/lnd/issues/6288
=> multi: extend `InvoiceDB` methods with a context argument

.github/workflows/main.yml
Start printing logs for unit tests in CI so it's easier to analyze flakes.
=> github: print debug logs for failed unit tests

lnwallet/btcwallet/btcwallet.go
=> chore: pkg import only once

.golangci.yml, funding/manager_test.go, input/taproot_test.go, lnwallet/channel_test.go, lnwallet/musig_session_test.go, lnwallet/rebroadcaster_test.go, peer/brontide_test.go
Running the test locally,
`make unit log="stdlog debug" pkg=peer case=TestHandleRemovePendingChannel timeout=1m`
gives the following error
```
Running unit tests.
go test -tags="dev stdlog debug"  -test.run=TestHandleRemovePendingChannel -test.timeout=1m github.com/lightningnetwork/lnd/peer
2023-10-12 23:53:15.863 [ERR] PEER: Peer(000000000000000000000000000000000000000000000000000000000000000000): Channel(0000000000000000000000000000000000000000000000000000000000000000) is active, ignoring remove request
2023-10-12 23:53:15.863 [WRN] PEER: Peer(000000000000000000000000000000000000000000000000000000000000000000): Channel(0100000000000000000000000000000000000000000000000000000000000000) not found, removing it anyway
--- FAIL: TestHandleRemovePendingChannel (0.00s)
--- FAIL: …
```
=> multi: fix peer unit test and disable `paralleltest`

htlcswitch/link.go, peer/brontide.go
Resulting from discussions in the noderunner group where someone could not co-op close a channel but was not able to understand why:
Logs where only showing:
```
==> /var/log/syslog <==
Oct 10 13:21:09 lnd[1591]: 2023-10-10 13:21:09.933 [INF] PEER: Peer(xxx): Local close channel request delivered to peer
==> /home/bitcoin/.lnd/logs/bitcoin/mainnet/lnd.log <==2023-10-10 13:21:09.950 [ERR] PEER: Peer(xxx): failed link shutdown: link failed to shutdown
```
This had the appearance that the peer somehow was not willing to cooperate ("request delivered to peer"), now we give the user better feedback what's happening.
Now would be:
```
2023-10-12 11:22:08.349 [INF] PEER: Peer(0355402a07589a522375f83b6f6c42c4144d219ec3810e0a2aefb8ae99bdabd095): Local close channel request is going to be delivered …
```
=> Add more information when a co-op close is failing.

config.go, docs/release-notes/release-notes-0.18.0.md, lnd.go, lntest/fee_service.go, sample-lnd.conf, tls_manager.go
Add ReadHeaderTimeout for HTTP client in lntests.
Fixes #7232 
The same code can be found here: https://github.com/lightningnetwork/lnd/blob/master/tls_manager.go#L424
=> lntest: set ReadHeaderTimeout for http client

channeldb/invoice_test.go, channeldb/invoices.go, docs/release-notes/release-notes-0.18.0.md, invoices/interface.go, invoices/invoiceregistry.go, invoices/mock.go
This PR removes `ScanInvoices` from `InvoiceDB` (and the channeldb implementation) and adds two specific methods that can be expressed in SQL more efficiently. Builds on top of https://github.com/lightningnetwork/lnd/pull/8066 and is a pre-requirement for https://github.com/lightningnetwork/lnd/pull/8052
The downside of the refactor is that for k/v implementations we'll need to scan invoices twice, but since we're fully migrating to SQL this is just a temporary issue.
Part of https://github.com/lightningnetwork/lnd/issues/6288
=> invoices: refactor `InvoiceDB` to eliminate `ScanInvoices`

Makefile, discovery/chan_series.go, discovery/syncer_test.go, scripts/release.sh
In this commit, [we prep for some upcoming changes in Go](https://go.dev/blog/loopvar-preview) by running our tests with `GOEXPERIMENT=loopvar`. This changes the loop semantics to fix a common bug where a scoping issue causes a variable to be re-used, which can cause unintended bugs down the line.
If everything passes with this flag on, then we can keep it on, and also rest a bit easier knowing that the compiler will fix a class of bugs that would previously pop up for us.
=> build: prep for Go 1.22 by using GOEXPERIMENT=loopvar for tests

docs/release-notes/release-notes-0.18.0.md, itest/lnd_channel_backup_test.go, itest/lnd_channel_force_close_test.go, itest/lnd_multi-hop_test.go, itest/lnd_routing_test.go, server.go, sweep/sweeper.go, sweep/sweeper_test.go
Depends on some of the test framework from,
- #7965 
- #7824
Fixes #7972 and possible #7181
This PR removes a possible case that when sweeping new and old inputs, the new inputs may end up in a second transaction which accidentally attempts an RBF(and fails). It also refactors the sweeper and simplified the ticker logic, preparing for incoming refactors.
=> sweep: remove possible RBF when sweeping new inputs

README.md
*Safe and fast to merge PR*:  
Added the `release build` and `go report` status badges to the readme in order to upgrade docs quality.  
See the outlook in my [fork](https://github.com/R3DRUN3/lnd/blob/master/README.md).
No need to test, no code modification.
=> add release build and go report status badges

docs/INSTALL.md
Lightning needs witness data, but bitcoind allows for a setting where all rpc commands are stripped of this data. I think we can only mention this in the docs but cannot really check otherwise?
Refers to: #8028
=> docs: Add requirement for bitcoind.

docs/release-notes/release-notes-0.18.0.md, lnwire/fuzz_test.go
Fuzz tests for decoding and encoding of onion failure messages, based on the fuzz harness for other lnwire messages. The onion failure messages were not covered by existing fuzz tests.
Some of these fuzz tests will fail until https://github.com/lightningnetwork/lnd/pull/7665 is merged, since the decode-encode-decode of messages with `channel_updates` currently can mutate the `channel_update`.  See https://github.com/lightningnetwork/lnd/issues/6461#issuecomment-1533438743.
No crashes found after 50+ CPU-hours of fuzzing for each target with https://github.com/lightningnetwork/lnd/pull/7665 patched in.
=> lnwire: fuzz onion failure messages

invoices/invoiceregistry_test.go, itest/lnd_multi-hop_test.go, lntest/harness.go
Fix these flakes,
```
harness_miner.go:218: 
Error Trace:	/home/runner/work/lnd/lnd/lntest/harness_miner.go:218
/home/runner/work/lnd/lnd/lntest/harness.go:1641
/home/runner/work/lnd/lnd/itest/lnd_multi-hop_test.go:2207
/home/runner/work/lnd/lnd/itest/lnd_multi-hop_test.go:152
Error:      	Received unexpected error:
want 2, got 3 in mempool: [a7cbb5724e39579cfc75d0469270f691988cb67fcc51a332256cafb193cf40bd b12a03a0622a3cf7d53867f060a6de8166e564a1a3109bc2be1ec0b720f305da 073d66885ccded1a770dc9aa5f1d44c8e10ac4e916e5ab50ef5149a5649ec8ba]
Test:       	TestLightningNetworkDaemon/tranche03/130-of-135/neutrino/htlc_timeout_resolver_extract_preimage_remote/zeroconf=false/committype=SIMPLE_TAPROOT
Messages:   	assert tx in mempool timeout
harness.go:339: finished test: …
```
=> multi: fix test flakes in unit tests and itests

docs/release-notes/release-notes-0.17.1.md, itest/list_on_test.go, itest/lnd_open_channel_test.go, lntest/harness_assertion.go, lnwallet/channel.go, peer/brontide.go
Prior to this commit, taproot channels had a bug:
- If a disconnect happened before `peer.AddNewChannel` was called, then the subsequent reconnect would call `peer.AddNewChannel` and attempt the ChannelReestablish dance.
- `peer.AddNewChannel` would call `NewLightningChannel` with populated nonce ChannelOpts. This in turn would call `InitRemoteMusigNonces` which would create a new musig pair session and set the channel's `pendingVerificationNonce` to nil.
- During the reestablish dance, `ProcessChanSyncMsg` would be called. This would also call `InitRemoteMusigNonces`, except it would fail since `pendingVerificationNonce` was set to nil in the previous invocation.
To fix this, a new function `SkipNonceInit` is exposed on `LightningChannel` that will skip the next call to …
=> multi: skip InitRemoteMusigNonces if we've already called it

docs/release-notes/release-notes-0.17.1.md, itest/lnd_macaroons_test.go, macaroons/constraints_test.go, macaroons/service.go, macaroons/service_test.go
We've only ever made macaroons with the v2 versions, so we should explicitly reject those that aren't actually v2. We add a basic test along the way, and also add a similar check for the version encoded in the macaroon ID.
=> macaroons: reject unknown macaroon versions

chainntnfs/bitcoindnotify/bitcoind.go, chainntnfs/btcdnotify/btcd.go, chainntnfs/interface.go, chainntnfs/mempool.go, chainntnfs/mempool_test.go, chainntnfs/txnotifier.go, chainntnfs/txnotifier_test.go, contractcourt/htlc_timeout_resolver.go, contractcourt/htlc_timeout_resolver_test.go, docs/release-notes/release-notes-0.18.0.md
This is the first commit from #7615. Making a PR for it so affected users can apply the patch first.
This commit adds a length check in `isPreimageSpend` to make sure it won't ever panic and adds a unit test to verify it.
=> contractcourt: stop lnd when received witness is empty

docs/release-notes/release-notes-0.17.1.md, peer/brontide.go
Without this the following could happen:
* `InboundPeerConnected` is called while we already have an inbound connection with the peer. This calls `removePeer` which calls `Disconnect`.
* If the peer is starting up in Start, it may be sending messages synchronously via `SendMessage(true, ...)`. This eventually calls the `writeMessage` function which will exit if disconnect is set to 1.
* Since `Disconnect` was called, disconnect will be 1 and `writeMessage` will exit, causing `writeHandler` to exit.
* If there is more than 1 message being sent, later messages will queue in `queueHandler` but be unable to get into `sendQueue` as the `writeHandler` goroutine has exited.
* The synchronous sends will be waiting on the `errChan` indefinitely and `startReady` will never get closed meaning …
=> peer: send messages in Start via writeMessage to bypass writeHandler 

build/version.go, docs/release-notes/release-notes-0.17.1.md, peer/brontide.go
Includes a bug fix for a potential deadlock in the peer handling logic.
=> build: create v0.17.1 rc3 release branch

contractcourt/channel_arbitrator.go, docs/release-notes/release-notes-0.18.0.md
This PR adds logging of the amount of incoming and outcoming HTLCs when they timeout. This helps to identify HTLCs with sub-dust amount.
=> contractcourt: log amount if incoming htlc times out

docs/release-notes/release-notes-0.18.0.md, fn/option.go, lnwire/channel_reestablish.go, lnwire/dyn_ack.go, lnwire/dyn_propose.go, lnwire/dyn_reject.go, lnwire/fuzz_test.go, lnwire/kickoff_sig.go, lnwire/lnwire.go, lnwire/lnwire_test.go, lnwire/message.go
This PR introduces new datatypes to LND as described in the [Dynamic Commitments](https://github.com/ProofOfKeags/bolts/blob/extension/dynamic-commitments/ext-dynamic-commitments.md#specification) spec.
make unit
=> lnwire: add wire types for dynamic commitments

channeldb/error.go, channeldb/graph.go, channeldb/graph_test.go, discovery/gossiper.go, docs/release-notes/release-notes-0.18.0.md
Before this PR, the following will happen when we receive a channel
update for one we have already marked as a zombie:
1. `handleChanUpdate` calls `ChannelRouter.GetChannelByID` which calls `ChannelGraph.FetchChannelEdgesByID`
2. In the case that the wanted channel is a zombie, `FetchChannelEdgeByID` will [return the `ErrZombieEdge` error along with a `ChannelEdgeInfo` which _only_ has the `NodeKey1Bytes` and `NodeKey2Bytes` fields populated](https://github.com/lightningnetwork/lnd/blob/master/channeldb/graph.go#L3266-L3274). 
3. This `ChannelEdgeInfo` object then gets passed to `processZombieUpdate`. 
4. In `processZombieUpdate` the `ChannelID` field of the passed `ChannelEdgeInfo` [gets used](https://github.com/lightningnetwork/lnd/blob/master/discovery/gossiper.go#L2058-L2059) meaning …
=> channeldb+discovery: pass correct SCID to `MarkEdgeLive`

peer/brontide_test.go
While flakehunting #8128, I ran into another flake in the `peer` tests: 
```
--- FAIL: TestHandleNewPendingChannel (0.00s)
--- FAIL: TestHandleNewPendingChannel/noop_on_active_channel (0.00s)
brontide_test.go:1250:
Error Trace:    /Users/carla/Work/lnd/peer/brontide_test.go:1250
Error:          Not equal:
expected: 2
actual  : 3
Test:           TestHandleNewPendingChannel/noop_on_active_channel
FAIL
FAIL    [github.com/lightningnetwork/lnd/peer](http://github.com/lightningnetwork/lnd/peer)    9.065s
```
We're not getting the number of channels that we expect because the parallel test cases are all updating the same peer. It can therefore be the case that: 
- `noop on active channel` checks how many channels we start with = 2
- `new channel should be added` checks how many channels we …
=> peer/test: fix race in TestHandleNewPendingChannel

peer/brontide.go
This is to avoid a race on `WriteMessage` and `Flush` internals. Because there is no locking on `WriteMessage` or `Flush`, if we allow `writeMessage` calls in `Start` after the `writeHandler` has started, the `writeMessage` calls may call `WriteMessage`/`Flush` at the same time that `writeMessage` calls from the `writeHandler` does. Since there is no locking, internals like `b.nextHeaderSend` can race and cause panics.
Fixes https://github.com/lightningnetwork/lnd/issues/8184
=> peer: send reestablish, shutdown messages before starting writeHandler

tlv/primitive.go, tlv/truncated.go
The typeless functions can directly call the typed functions after the type check.
=> tlv: simplify encoding functions

itest/lnd_multi-hop_test.go
Fix a flake found in almost every recent builds.
=> itest: fix flake in `multi_hop_htlc_remote_chain_claim`

peer/brontide_test.go, peer/test_utils.go
The test case reliably triggers https://github.com/lightningnetwork/lnd/issues/8184 under the race detector.
Tested:
```shell
$ make unit-race pkg=peer
...
ok      github.com/lightningnetwork/lnd/peer    8.960s
$ git revert 7556402ea44048393bda99d257f60853521e077e
$ make unit-race pkg=peer
...
WARNING: DATA RACE 
Read at 0x00c0001e6090 by goroutine 85:
...
--- FAIL: TestStartupWriteMessageRace (0.10s) 
```
=> peer: test for startup writeHander data race

build/version.go, docs/release-notes/release-notes-0.17.2.md, peer/brontide.go, peer/brontide_test.go, peer/test_utils.go
This release includes a single hot fix:
* https://github.com/lightningnetwork/lnd/pull/8186
=> release: create v0.17.2-beta release branch

docs/release-notes/release-notes-0.17.3.md, input/musig2_session_manager.go, lntest/harness.go
Found in this build failure [here](https://github.com/lightningnetwork/lnd/actions/runs/6983952648/job/19005955561?pr=8220), with trimmed logs,
```
2023-11-24 18:42:14.279 [INF] LNWL: Generating new musig2 sig for session=d413f8d90016497feb2b3ab7d4a9c24bcc4143c34a7ca6e42ab5192818f5beed, nonces=NoncePair(verification_nonce=02b2fd60a28bbb66839d5ccc47589513d60cdbc088a59131d7e825c10e33aff27b0281c5a51ac94a49a16fb80ea3aa8396fab7fe4bd5af25496a026328e41a8b8642, signing_nonce=02078f4cb5fb0f9f15e4979ba5fbd4bd5a33992ec9518cf9283238d699138d20ad02039e81f96c9ec7e2541e9b864d74992b9318b23933771ef5d9efd42adb3e97c5)
2023-11-24 18:42:14.279 [INF] LNWL: Generating new musig2 sig for session=6c8b4b33a72b585d6cc8f16b4e52fd49eeae829d986798d6711527fb281a4df7, …
```
=> input: fix `fatal error: concurrent map writes`

docs/release-notes/release-notes-0.14.0.md, docs/release-notes/release-notes-0.16.1.md, sample-lnd.conf
=> docs: fix typos [skip ci]

docs/release-notes/release-notes-0.18.0.md, watchtower/wtclient/client.go, watchtower/wtclient/interface.go, watchtower/wtdb/client_chan_summary.go, watchtower/wtdb/client_db.go, watchtower/wtdb/client_db_test.go, watchtower/wtdb/log.go, watchtower/wtdb/migration8/codec.go, watchtower/wtdb/migration8/log.go, watchtower/wtdb/migration8/migration.go, watchtower/wtdb/migration8/migration_test.go, watchtower/wtdb/migration8/range_index.go, watchtower/wtdb/queue.go, watchtower/wtdb/queue_test.go, watchtower/wtdb/version.go
See the problem described in detail here: https://github.com/lightningnetwork/lnd/issues/8221
- the client keeps an in-mem map of map[channelID] max-commit-height. This map represents the maximum commitment height of a backup for a channel that the client has received. It uses this map in various places.
- the issue is the population of this map (which is done at startup) : it will currently range over every session (which could be in the ten thousands) and for every session, it goes through each of its range indices to get the max height per channel backed up with the session.
This PR implements the first solution step defined in the issue. I'll repeat it here:
This PR removes the need to iterate through all the sessions & range indices on each start-up. 
It does this by: 
1. adding a …
=> wtclient+migration: start storing chan max height in channel details bucket

channeldb/channel.go, docs/release-notes/release-notes-0.17.3.md, htlcswitch/link.go, lnwallet/channel.go, lnwallet/channel_test.go, peer/brontide.go
Attempt to provide more logs so we can find out what's the root cause in #8130
=> multi: fix loopvar and enhance logging around channel reestablishment

docs/release-notes/release-notes-0.17.3.md, routing/router.go
This commit introduces a wrapper function `fetchFundingTxWrapper` which calls `fetchFundingTx` in a goroutine. This is to avoid an issue with pruned nodes where the router is attempting to stop, but the `prunedBlockDispatcher` is waiting to connect to peers that can serve the block. This can cause the shutdown process to hang until we connect to a peer that can send us the block.  Marking as draft for now until I can test this.  I opted for this approach rather than passing in a `quit` channel to `GetBlock`.
See https://github.com/lightningnetwork/lnd/issues/7928#issuecomment-1791061270 for more info
=> routing: launch fetchFundingTx in goroutine so router can exit

docs/release-notes/release-notes-0.17.3.md, go.mod, go.sum
This PR updates the `go.mod` to take advantage of the optimization introduced in https://github.com/btcsuite/btcwallet/pull/896
=> gomod: update `btcwallet` version

fn/go.mod, go.mod
In this commit, we make a new sub-module from the `fn` package. This lets other projects use it w/o pulling in all of lnd, and also other sub-packages within lnd.
Fixes https://github.com/lightningnetwork/lnd/issues/8216
=> fn: create new sub-module

channeldb/graph.go, channeldb/graph_test.go, discovery/chan_series.go, discovery/gossiper.go, discovery/sync_manager.go, discovery/sync_manager_test.go, discovery/syncer.go, discovery/syncer_test.go, docs/release-notes/release-notes-0.18.0.md, lncfg/protocol.go, lncfg/protocol_integration.go, lnwire/encoding.go, lnwire/lnwire.go, lnwire/lnwire_test.go, lnwire/query_channel_range.go, lnwire/query_channel_range_test.go, lnwire/query_options.go, lnwire/query_short_chan_ids.go, lnwire/query_short_chan_ids_test.go, lnwire/reply_channel_range.go, lnwire/reply_channel_range_test.go, lnwire/timestamps.go, lnwire/writer.go, lnwire/writer_test.go, routing/router.go, sample-lnd.conf, server.go
In this PR, we start supporting the timestamps query option in the `query_channel_range` message. If we receive such a message with that bit set then we now populate the timestamps field of the `reply_channel_range` message. 
With this feature we can now ask for the timestamps for the latest channel updates for a channel to be sent along with the SCID. Thus, if we have marked one of the channels in the list as a zombie but we see that the timestamp sent with it make it not a zombie, then we request the channel_update messages for that channel so that we can perhaps awaken the channel. 
See this comment: https://github.com/lightningnetwork/lnd/pull/8030#issuecomment-1808145257
Fixes https://github.com/lightningnetwork/lnd/issues/7989
=> multi: query chan update timestamps

docs/release-notes/release-notes-0.18.0.md, zpay32/hophint.go
We already do not allow a `min_final_cltv_expiry_delta` for invoices lower than 18 and default to 80 when not specified:
https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/addinvoice.go#L364-L380.
Lately during a chat with CDecker we found out that CLN will not always provide a `min_cltv_expiry_delta` in their invoice. In that case we would default to 9 when paying the invoice which hower CLN would reject because the delta is too low for them.
So this PR is mostly to smoothen out some interoperability issues between CLN<=>LND
For more infos see: https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#cltv_expiry_delta-selection
Hmm looking at https://github.com/lightningnetwork/lnd/blob/master/lncfg/config.go we might analyse all our constants because I think …
=> zpay32: Change min_final_cltv_expiry_delta.

lnwallet/channel.go
Makes the logging in case of a mismatch of the remote `msg.NextLocalCommitHeight` more clear. Results from #8306
Current logging would report something like this which which is not quite right:
`sync failed: remote's next commit height is 0, while we believe it is 0!`
should be:
`sync failed: remote's next commit height is 0, while we believe it is 1!`
Fixes https://github.com/lightningnetwork/lnd/issues/8306
=> lnwallet: fix logging.

lnwallet/wallet.go
There are some unnecessary duplicate words in the source file. Use this change to remove them. The CI can be skipped.
=> fix: remove duplicate words [skip ci]

tlv/internal/gen/gen_tlv_types.go, tlv/record_type.go, tlv/record_type_test.go, tlv/tlv_type_param.go, tlv/tlv_types_generated.go
In this PR, we modify the RecordT type to allow callers to re-use
the Record definition of a different type, but use the new type param to
override the integer type used on the wire.
This will let use do things like encode a signature using the same
RecordProducer instance, but with a diff type in another context.
The upcoming use for this is allowing our `lnwire.Sig` type to be
encoded in the same message using distinct TLV integer types (new co-op
close protocol).
We also add a new method that'll make parsing an `tlv.OptionalRecord[T]` 
easier. For these records, we want to set to `fn.Some`, but only when 
the record was decoded. We can use this new method and the `typeMap`
to figure out if we were able to parse out a value or not.
=> tlv: various enhancements to the new RecordT type 

docs/code_formatting_rules.md
docs: fix typo "paren" to "parenthesis" in `code_formatting_rules.md` [skip ci]
=> docs: fix typo "paren" to "parenthesis" in `code_formatting_rules.md` [skip ci]

lnrpc/routerrpc/router_server.go, routing/router.go
Fix #8344 
Since `SendPaymentAsync` now never returns an error, there's no need to catch it and check it in `SendPaymentV2`.
=> routing+routerrpc: remove redudant error check

docs/release-notes/release-notes-0.18.0.md, htlcswitch/link.go, htlcswitch/link_test.go, itest/lnd_amp_test.go, itest/lnd_multi-hop-error-propagation_test.go, itest/lnd_send_multi_path_payment_test.go, lntest/utils.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/transactions_test.go, routing/pathfind.go
Fixes #7657/#7721
This change introduces a fee buffer which accounts for a 100% fee rate increase plus an additional htlc output on the commitment transaction ~~at the current fee rate~~. This equals the behaviour what CLN does currently and is spec compliant IMO. It's a conservative approach because we are not taking any trimmed Htlcs at higher fee rates into account, but this has a positive side effect when fee rates decrease and dust htlcs become normal outputs (only relevant for non-anchor channels because they have to pay for the second-level covenant transaction).
~~Still need to write tests in the coming days. Change seems small at first glance but lets wait until tests are ready.~~
~~EDIT: Before updating all the unit tests and thinking of itests, I would be happy to receive first …
=> lnwallet: Introduce a fee buffer.

fn/option.go
We had an unsafe extraction API for Options to aid with unit test situations where we want to panic out if something is None. It should be noted that this should never be used outside tests. The API is prefixed with "Unsafe" to indicate very clearly not to use it in real code.
This blocks #8167 
=> fn: add UnsafeFromSome to Option API

docs/release-notes/release-notes-0.18.0.md, watchtower/wtclient/client.go, watchtower/wtclient/client_test.go, watchtower/wtdb/client_db.go
This PR addresses an edge case that could lead to the "tower has un-acked updates" error 
when a user tries to remove a tower. See the issue [here](https://github.com/lightningnetwork/lnd/issues/6397). 
Currently, if you call "remove tower", then only sessions from that tower that are loaded into memory on 
startup are terminated correctly. And we only load in sessions where `session.SeqNum < session.policy.MaxUpdates`. 
So the issue occurs when the session is technically exhausted _but_ there is still an un-acked update on disk. 
This means that we would not terminate such a session properly on tower removal and so would run into "tower has un-acked updates". 
So with this PR, we make sure to load a session into memory if there are still un-acked updates that it needs to deal with. 
1. …
=> wtclient: handle un-acked updates for exhausted sessions

sweep/tx_input_set.go, sweep/tx_input_set_test.go
We now use p2tr outputs as change
Fixes https://github.com/lightningnetwork/lnd/issues/7893
=> sweep: use p2tr output as change weight

cmd/lncli/cmd_payments.go, docs/release-notes/release-notes-0.18.0.md, lnrpc/routerrpc/router.proto, lnrpc/routerrpc/router.swagger.json, lnrpc/routerrpc/router_grpc.pb.go, lnrpc/routerrpc/router_server.go
Fixes https://github.com/lightningnetwork/lnd/issues/8380.
Now the lncli does not provide a default value but we check on the lnd side and if its not provided we use the lnd default.
Moreover improves the docs.
=> buildroute use lnd default

channeldb/invoice_test.go, docs/release-notes/release-notes-0.18.0.md, feature/default_sets.go, feature/deps_test.go, feature/manager_internal_test.go, funding/commitment_type_negotiation_test.go, invoices/invoiceregistry.go, invoices/invoiceregistry_test.go, itest/lnd_channel_force_close_test.go, itest/lnd_funding_test.go, itest/lnd_multi-hop_test.go, itest/lnd_payment_test.go, itest/lnd_revocation_test.go, peer/brontide.go, peer/brontide_test.go, routing/integrated_routing_context_test.go, routing/integrated_routing_test.go, routing/pathfind_test.go
This PR makes some legacy feature bits compulsory. Closes #8048 
=> multi: make legacy feature bits compulsory

htlcswitch/hop/fuzz_test.go
Route blinding added some new fields to hop.Payload and route.Hop, which we need to copy over to the fuzzPayload tests.
The fuzz tests quickly fail prior to this commit.
=> htlcswitch: update fuzzPayload for route blinding

channeldb/channel.go
fix: fix typo "(cltv_expiry" to "(cltv_expiry)" in `channeldb/channel.go` [skip ci]
=> fix: fix typo "(cltv_expiry" to "(cltv_expiry)" in `channeldb/channel.go` [skip ci]

docs/release-notes/release-notes-0.17.4.md
Adding this so that each 0.17.4 PR can just add a single entry rather than needing to add the whole template since nothing has been merged yet.
=> docs: add template for 0.17.4

Makefile
This commit adds a description to each make goal that is printed when `make help` is run.
Idea borrowed from btcsuite/btcd#2107.
Generated output:
```
$ make help
Listing commands:
android                Build mobile RPC stubs and project template for Android
apple                  Build mobile RPC stubs and project template for iOS and macOS
build                  Build lnd and lncli binaries, place them in project directory
build-itest            Build integration test binaries, place them in itest directory
build-itest-race       Build integration test binaries in race detector mode, place them in itest directory
check                  Run unit and integration tests
clean-mobile           Remove all generated mobile files
clean                  Remove all generated files
docker-release …
```
=> Makefile: add `make help` command that describes goals

.github/workflows/main.yml, .protolint.yaml, Makefile, lnrpc/devrpc/dev.proto, lnrpc/invoicesrpc/invoices.proto, lnrpc/lnclipb/lncli.proto, lnrpc/peersrpc/peers.proto, lnrpc/routerrpc/router.proto, lnrpc/walletrpc/walletkit.proto, lnrpc/walletunlocker.proto
Install [protolint](https://github.com/yoheimuta/protolint) to enforce the protobuf style guide rules in the CI.
Closes #8301
It could be tested either by running `./scripts/install_protolint.sh` script or in the `CI`.
=> [CI]: Install protolint to enforce the protobuf style guide rules in the CI

channeldb/payments.go, channeldb/payments_test.go, docs/release-notes/release-notes-0.18.0.md, itest/lnd_amp_test.go, lnrpc/routerrpc/router_backend.go
The AMP struct in a hop was never being set when deserizlied. Also, the AMP TLV record was not being added when the hop was serialized. This sets the TLV record when serializing and correctly sets the AMP struct on the hop when that record is present.
1. Send an AMP payment to someone.
2. Observe the `amp_record` is now set in the hops array when using `listpayments`
=> Serialize/deserialize AMP struct in hop

lnrpc/routerrpc/router.proto, lnrpc/routerrpc/router.swagger.json, lnrpc/routerrpc/router_grpc.pb.go
Fixes https://github.com/lightninglabs/lightning-terminal/issues/714.
Makes it more explicit that when no fee limit is set, the default limit of 0 sats is used which often results in `FAILURE_REASON_NO_ROUTE`.
=> routerrpc: make use of fee limit obvious in SendPaymentV2

docs/release-notes/release-notes-0.17.4.md, go.mod, go.sum
Fixes for https://github.com/lightningnetwork/lnd/issues/8250 happened in btcwallet (https://github.com/btcsuite/btcwallet/pull/903), this just bumps the version.
=> Fix Pruned Node Loss Sync Issue.

docs/release-notes/release-notes-0.17.4.md, tls_manager.go
Similarly to what is done in [LiT](https://github.com/lightninglabs/lightning-terminal/blob/20fa2c0915de0d43f793f4c22a140e514dcbdbad/terminal.go#L1454), we let the REST proxy skip TLS
verification when connecting to the gRPC server. This is necessary to fix [this](https://github.com/lightninglabs/lightning-terminal/issues/696) bug that appears in LiT that happens when the `--tlsencryptkey` flag is used. This flag results
in an ephemeral tls key&cert being used which is swapped out with the permanent tls key/cert once LND is unlocked. After a day, the ephemeral cert expires but the client continues trying to use that key. 
Since this is just LND connecting to itself, it should be fine to skip TLS verification here.
=> tls_manager: let REST proxy skip tls cert verification

peer/brontide.go, peer/brontide_test.go
This fixes an issue where we would just echo the same shutdown message back that we received from the remote in the case where the link was already removed from the switch.
New tests have been added that fail prior to the main code change presented here and pass afterwards.
=> peer: fix issue where we echo remote Shutdown

tlv/record_type.go
In this commit, we add a new `Zero` method for the `RecordT` type. This method allows a caller to create the zero record for a type without needing to reference the actual TLV type.
With this we go from this:
```go
sig1 := tlv.ZeroRecordT[tlv.TlvType1, Sig]()
```
To this:
```
sig1 := c.CloserNoClosee.Zero()
```
=> tlv: add new Zero method on RecordT

.github/CODEOWNERS, lnwire/closing_complete.go, lnwire/closing_sig.go, lnwire/fuzz_test.go, lnwire/lnwire_test.go, lnwire/message.go, lnwire/signature.go
These two messages will be used to implement the new and improved co-op
closing protocol. This PR also show cases how to use the new
`tlv.OptionalRecord` type to define and handle TLV level parsing.
I think we can make one additional helper function to clean up some of
the boiler plate for the encode/decode.
A sneak peak of what's to come: https://gist.github.com/Roasbeef/acc4ff51b9dff127230228a05553cdfe
=> lnwire: add new closing_complete and closing_sig messages 

docker/README.md
I follow "Create lightning network cluster" in docker/README.md, but found some issue with as flowing. After some troubleshooting, I found why it happened.
```
weili@mbp14 docker % docker exec -it btcd /start-btcctl.sh generate 1
-32603: No payment addresses specified via --miningaddr
weili@mbp14 docker %
```
When initiating new containers using `docker-compose run`, the `MINING_ADDRESS` environment variable was found to reset to an empty state. This behavior resulted in failures when attempting to generate new blocks with `btcd`, as the mining address was not specified, throwing an error `-32603: No payment addresses specified via --miningaddr`.
Up btcd with MINING_ADDRESS inline, btcd container will setting the MINING_ADDRESS.
```
weili@mbp14 docker % …
```
=> docs: preserve MINING_ADDRESS across docker-compose sessions

lnrpc/invoicesrpc/invoices.pb.go, lnrpc/invoicesrpc/invoices.proto, lnrpc/invoicesrpc/invoices.swagger.json, lnrpc/lightning.pb.go, lnrpc/lightning.proto, lnrpc/lightning.swagger.json, lnrpc/routerrpc/router.pb.go, lnrpc/routerrpc/router.proto, lnrpc/routerrpc/router.swagger.json
Fix #7438, adding clarification statements in lnrpc proto files. Originally proposed by daredevil3435 in PR #7873 and PR #7885.
The usage of "payment address" over "payment secret" appears to have caused some confusion among users.  This PR attempts to provide a minimal change to provide clarity, focusing on comment wording rather than functional code changes.
As PR #7885 appears to be dormant, this PR attempts to move forward with the clarification changes.
Possibly N/A, comment update.  `make rpc` is successful.
=> lnrpc: Clarify payment_addr and payment_secret

.github/workflows/stats.yml
In an attempt to fix the broken PR stats, this PR updates the version and sets the recommended permissions.
=> github: bump pull-resquest-stats to v2.11.0

docs/MAKEFILE.md, docs/code_contribution_guidelines.md, docs/code_formatting_rules.md
- docs: fix makefile typo
- docs: fix contribution guide links
=> docs: fix typo and links

channeldb/channel.go, channeldb/channel_test.go, docs/release-notes/release-notes-0.18.0.md, htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/link_test.go, htlcswitch/mock.go, itest/lnd_coop_close_with_htlcs_test.go, lnwallet/chancloser/chancloser.go, lnwallet/chancloser/chancloser_test.go, lnwallet/chancloser/interface.go, lnwallet/channel.go, peer/brontide.go, peer/test_utils.go
~ Replaces #8447 -> opening new PR since this approach is different & so comments wont all transfer. ~
In this PR we ensure that if a re-establish happens after `shutdown` is 
sent but before fee negotiation starts, then `shutdown` is correctly 
re-sent and the coop closure continues. This includes ensuring that 
the delivery address sent in the first `shutdown` is the one that is
used in the final co-op close tx. 
The issue is that we only mark a channel as `ChanStatusCoopBroadcasted`
at the time of actually doing the broadcast. This means that if there is a 
re-connect between the `shutdown` message being sent and the coop 
close tx being finalised then we will forget that we were in the middle of a 
shutdown and will continue with normal operation on restart. This is not
compliant with …
=> multi: resend shutdown on reestablish

chainreg/chainregistry.go, config_builder.go, funding/manager_test.go, lnwallet/config.go, lnwallet/parameters.go, lnwallet/reservation.go, lnwallet/test/test_interface.go, lnwallet/wallet.go
In an investigation on how `ChannelConstraints` were used throughout the codebase (in preparation for dynamic commitments), I stumbled on some dead code/data structures. This PR trims them to the smallest used set. In theory this should result in no semantics changes.
CI should handle finding any regressions
=> Remove `DefaultChannelConstraints` from PartialChainControl and lnwallet.Config

fn/option.go
In this commit, we add two new methods that simplify usage of an handling a value wrapped in an Option. These methods allow a caller to force the nil/None check up front, and either obtain the value, or fail the current execution or test.
This should replace most usages of `UnsafeFromSome` today.
=> fn: add UnwrapOrErr and UnwrapOrFail to Option

channeldb/channel.go, funding/manager.go, go.mod, go.sum, lnwallet/chancloser/chancloser.go, lnwallet/chancloser/chancloser_test.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwire/accept_channel.go, lnwire/channel_ready.go, lnwire/channel_reestablish.go, lnwire/closing_complete.go, lnwire/closing_signed.go, lnwire/commit_sig.go, lnwire/funding_created.go, lnwire/funding_signed.go, lnwire/lnwire_test.go, lnwire/musig2.go, lnwire/open_channel.go, lnwire/partial_sig.go, lnwire/revoke_and_ack.go, lnwire/shutdown.go
In this commit, we update new Taproot related TLVs (nonces, partial sig,
sig with nonce, etc). Along the way we were able to get rid of some
boiler plate, but most importantly, we're able to better protect against
API misuse (using a nonce that isn't initialized, etc) with the new
options API. In some areas this introduces a bit of extra boiler plate,
and where applicable I used some new helper functions to help cut down
on the noise.
**Note to reviewers**: this is done as a single commit, as changing the API
breaks all callers, so if we want things to compile it needs to be in a
wumbo commit.
=> multi: upgrade new taproot TLVs to use tlv.OptionalRecordT 

build/version.go
In this commit, we bump the version of the master branch to v0.17.99. This reflects the fact that master will be a super set of all the minor releases until v0.18, and will also include changes towards v0.18.
=> build: bump version to v0.17.99

Makefile
This commit gives the linter container access to the local machine's build and module cache, drastically decreasing the run time of subsequent linter runs (no difference on first run with this change).
Back port from [Taproot Assets](https://github.com/lightninglabs/taproot-assets/blob/main/Makefile#L58) where we've been using this successfully for a while.
=> make: use Golang build and module cache for linter

docs/release-notes/release-notes-0.18.0.md, go.mod, go.sum, lnwallet/btcwallet/btcwallet.go
Depends on:
- https://github.com/btcsuite/btcd/pull/2125
- https://github.com/btcsuite/btcwallet/pull/910
=> lnwallet: skip `testmempoolaccept` when the backend version is too low

cmd/lncli/commands.go, docs/release-notes/release-notes-0.18.0.md
Fixes https://github.com/lightningnetwork/lnd/issues/6743.
=> cli: add confirmation prompt to closeallchannels

docs/release-notes/release-notes-0.18.0.md, healthcheck/healthcheck.go, healthcheck/healthcheck_test.go
This PR expands the `healthcheck` package such that it can support:
- the ability to specify callbacks to fire on success and reaching failure threshold.
- the ability to dynamically add observations (health check routines) after initializing the monitor.
The idea is to use this in the _**payment service**_ to health check a collection of _**lnd**_ backends. Such an application would like to spin up health checks as backends come online and then take some action on health check success/failure beyond just exiting. If these changes are not desired here, then we can always write a custom health checking library which suits these needs.
This change should be transparent to existing users of the package. The callbacks default to no-ops and are configurable via functional option.
Steps for …
=> lnd/healthcheck: add checks after initialization + success/failure callbacks

.github/actions/setup-go/action.yml, .github/workflows/main.yml
To avoid build caches getting larger and larger, causing our builds to fail, we separate the caches of the different job types. If we don't separate them, then the caches can end up being a combination of the different jobs, which isn't useful (for example the build cache of the cross compilation build isn't useful in an integration test and vice versa).
NOTE: Not yet sure if this works, will assign review once it seems it does work as expected.
=> GitHub: separate build caches

lnwallet/channel.go
This commit addresses clarification in the `availableCommitmentBalance` function in `lnwallet/channel.go` by adjusting the log message to better reflect the context of balance reduction.
Closes #8152 
N/A
=> fix: clarify available commitment balance log message

config.go, config_test.go, docs/release-notes/release-notes-0.18.0.md
- Added `supplyEnvValue` function in `config.go` that returns The value of the specified environment variable, or the default value if provided, or the original input string if no matching variable is found or set.
- Called `supplyEnvValue` function in `parseRPCParams` function in `config.go` file where `rpcuser` and `rpcpass` fields are being parsed.
Fixes #8295
Added the test cases for `supplyEnvVale` in the `config_test.go` file covering the happy and sad paths.
=> lnconfig: Support utilizing Environment Variables in `lnd.conf` for `rpcuser` and `rpcpass` fields.

routing/router.go
https://github.com/lightningnetwork/lnd/issues/3658
During a rescan, which can happen for a variety of reasons, there is a section where LND is querying the chain backend for blocks and filtering transactions in order to update its DB. Prior to this change, the entire time that it spends querying the backend, there are little to no useful logs being generated, even at lower debuglevels.
This change tells the user via the log file what block height it is currently scanning so they get the sanity check that their node is not broken and stuck in a loop.
Things like block hash could also be logged, but at a lower level (debug/trace) if people desire that.
Trigger a wallet rescan:
Start LND with this flag:
`lnd --reset-wallet-transactions`
📝 …
=> routerrpc: Add detailed info logging during a rescan

config_builder.go, docs/release-notes/release-notes-0.18.0.md, itest/list_on_test.go, itest/lnd_misc_test.go, lncfg/db.go, lntest/node/harness_node.go
This PR is a temporary measure for 0.18 as we don't plan to add invoice migration yet for native SQL invoice DB.
=> lnd: ensure that LND won't start in native SQL mode if it has any KV invoices 

docs/release-notes/release-notes-0.18.0.md
This commit removes a merge artifact introduced by a rebase of a previous PR.
While we're at it, we streamline the grammar, formatting and general look-and-feel of the release notes.
=> docs: remove merge artifact, polish

docs/release-notes/release-notes-0.18.0.md, lnwallet/chainfee/estimator.go, lnwallet/chainfee/filtermanager.go, lnwallet/chainfee/filtermanager_test.go
This commit introduces a filterManager that uses our outbound peers' feefilter values to determine an acceptable minimum feerate that ensures successful transaction propagation. Under the hood, a moving median is used as it is more resistant to shocks than a moving average.
Mostly looking for an approach ACK on:
- the choice of a moving median compared to a moving average
- the choice of exclusively using outbound peers' feefilter to avoid manipulation by an inbound attacker. The downside is that we get less datapoints
- the choice of constants (polling interval and the moving window) which will affect the overall result
- a quicker polling interval means more up-to-date data but at the cost of taking up the window size with potentially stale data
- a larger moving window would give the …
=> chainfee: introduce filterManager and use it for fee floor

docs/release-notes/release-notes-0.18.0.md, kvdb/backend.go, watchtower/wtclient/session_negotiator.go
=> kvdb+watchtower: fix unreachable code

chainntnfs/test/test_interface.go
Found this race in this sweeper PR [build](https://github.com/lightningnetwork/lnd/actions/runs/8430170345/job/23085602197?pr=8423),
```
Write at 0x00c00054a110 by goroutine 11:
github.com/lightningnetwork/lnd/chainntnfs/btcdnotify.New()
/home/runner/work/lnd/lnd/chainntnfs/btcdnotify/btcd.go:135 +0xa2d
github.com/lightningnetwork/lnd/chainntnfs/test.TestInterfaces.func3()
/home/runner/work/lnd/lnd/chainntnfs/test/test_interface.go:1958 +0x70
github.com/lightningnetwork/lnd/chainntnfs/test.TestInterfaces()
/home/runner/work/lnd/lnd/chainntnfs/test/test_interface.go:2025 +0x1444
github.com/lightningnetwork/lnd/chainntnfs/test/btcd_test.TestInterfaces()
/home/runner/work/lnd/lnd/chainntnfs/test/btcd/btcd_test.go:15 +0x32
testing.tRunner() …
```
=> chainntnfs: fix race in `TestInterfaces`

channeldb/channel.go
It seems all other places check the return value of `ReadWriteBucket` not being `nil` before using it.
=> channeldb: check return value of ReadWriteBucket

go.mod, go.sum
Update `fn` version so the sweeper can use the `fn.Map`.
=> gomod: bump `fn` version to v1.0.5

channeldb/graph.go, channeldb/graph_cache.go, channeldb/graph_cache_test.go, channeldb/graph_test.go, docs/release-notes/release-notes-0.18.0.md, itest/lnd_multi-hop-payments_test.go, routing/graph.go, routing/heap.go, routing/pathfind.go, routing/pathfind_test.go, routing/payment_session_test.go, routing/router.go, routing/router_test.go, routing/unified_edges.go, routing/unified_edges_test.go
Implements send support for inbound routing fees. The receiver side is implemented in #6703 and this PR is based off of that.
* The `channel_update` extra opaque data isn't validated before it was stored in the database. This means that everywhere we read this data, a tlv error might be encountered. In this PR, this case is handled in a mostly defensive way, skipping over the channel policy.
Based on #6703. Review first commits there.
Support for inbound fees in `BuildRoute` is explored in #7060.
=> routing: inbound fees send support

docs/release-notes/release-notes-0.18.0.md, sqldb/invoices.go
As SQL serializaton errors can lead to transaction retries we need to ensure that we reset any out of scope containers where we accumulate results. Otherwise partial data from a previously executed transacton retry may be returned along with the latest result.
This is a potential fix for the flake reported in https://github.com/lightningnetwork/lnd/issues/8583
=> sqldb: reset out of scope containers on potential ExecTx retry

docs/release-notes/release-notes-0.18.0.md, rpcserver.go
Fixes https://github.com/lightningnetwork/lnd/issues/8608
I think no more itests or unit tests are needed because this behavior could not have resulted in a bug because we catch the 0 sat/vbyte behaviour in your fee-estimation code.
=> lnd: fix sweepall argument call.

contractcourt/breach_arbitrator.go, contractcourt/breach_arbitrator_test.go, contractcourt/htlc_success_resolver_test.go, contractcourt/htlc_timeout_resolver_test.go, contractcourt/nursery_store.go, contractcourt/utxonursery.go, contractcourt/utxonursery_test.go, input/input.go, input/mocks.go, input/taproot.go, lnrpc/walletrpc/walletkit_server.go, lnwallet/chainfee/estimator.go, server.go, sweep/aggregator.go, sweep/aggregator_test.go, sweep/bucket_list.go, sweep/fee_bumper.go, sweep/fee_bumper_test.go, sweep/fee_function.go, sweep/fee_function_test.go, sweep/mock_test.go, sweep/sweeper.go, sweep/sweeper_test.go, sweep/tx_input_set.go, sweep/tx_input_set_test.go, sweep/txgenerator.go, sweep/weight_estimator.go, sweep/weight_estimator_test.go, watchtower/wtclient/backup_task.go, watchtower/wtclient/backup_task_internal_test.go
This PR addresses the comments collected from previous sweeper PRs to avoid too many rebase conflicts there,
In addition, it also makes some changes based on the final PR #8514 so edgy cases are now caught so the sweeper can be ready to be used in all the contract resolvers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/8581)
=>  [6/5]sweep: make sweeper ready to be used in `contractcourt`

config.go, contractcourt/htlc_incoming_contest_resolver.go, contractcourt/htlc_incoming_contest_resolver_test.go, contractcourt/interfaces.go, docs/release-notes/release-notes-0.18.0.md, htlcswitch/hop/forwarding_info.go, htlcswitch/hop/fuzz_test.go, htlcswitch/hop/iterator.go, htlcswitch/hop/iterator_test.go, htlcswitch/hop/payload.go, htlcswitch/hop/payload_test.go, htlcswitch/link.go, itest/list_on_test.go, itest/lnd_route_blinding_test.go, lncfg/protocol.go, lncfg/protocol_integration.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwire/update_add_htlc.go, peer/brontide.go, sample-lnd.conf, server.go
This PR is the second in a series to add the ability for LND to forward payments to blinded routes.
**Reviewer Notes**: 
* This PR does not signal the route blinding feature yet because it does not include error handling for blinded forwards, which is critical to receiver privacy so LND should not advertise the feature until it fully support it.
* Itests can be squashed, they're broken into multiple commits to aid readability. 
Replaces #7376 
Fixes #7298
=> [2/3]: Support Forwarding of Blinded Payments

docs/release-notes/release-notes-0.18.0.md, feature/default_sets.go, feature/manager_internal_test.go, peer/brontide.go, peer/brontide_test.go
This reverts commit 717facc2020315652f66988cdab15bc75c313357.
It turns out that we can't do this since it would result in incompatibility with LDK. The spec has been updated to reallow optional gossip queries so we revert this commit.
The spec change commit that subsequently relaxed this restriction it originally introduced can be found [here](https://github.com/lightning/bolts/pull/1092/commits/e0ee59f3c92b7c98be8dfc47b7db358b45baf9de)
=> Revert "feature: make gossip queries compulsory"

chainreg/chainregistry.go, docs/release-notes/release-notes-0.18.0.md
=> healthcheck: make sure chain backend has enough outbound peers

docs/release-notes/release-notes-0.18.0.md, go.mod, go.sum
Fixes #8626.
Depends on https://github.com/btcsuite/btcwallet/pull/925.
This commit updates btcwallet to the latest version that correctly includes the MasterKeyFingerprint for all generated addresses, including change addresses derived from imported watch-only accounts.
=> mod: bump btcwallet to latest version

.github/workflows/main.yml, docs/release-notes/release-notes-0.18.0.md, go.mod, go.sum, scripts/install_bitcoind.sh
With this PR we want to assert compatibility with `bitcoind v27.0` while it's still in RC.
Fixes #8571.
Depends on https://github.com/btcsuite/btcd/pull/2142.
=> GitHub: use bitcoind v27.0 for CI

tlv/record.go
This commit introduces a RecordProducer implementation for Record that serves as the identity function. This makes it easier for us to mix Primitive and Dynamic records in the same RecordProducer collections.
=> tlv: add axiomatic RecordProducer implementation for Record

cmd/lncli/commands.go, config.go, docs/release-notes/release-notes-0.18.0.md, rpcserver.go, sample-lnd.conf
Positive inbound are now rejected by default. The user can enable positive inbound fees with the option 'no-reject-positive-inbound-fees'.
Tested with `lncli updatechanpolicy` with positive and negative inbound fees and with enabled and disabled option
=> lnrpc: rejects positive inbound fees by default

.github/workflows/main.yml, build/version.go, chainntnfs/test_utils.go, docs/release-notes/release-notes-0.17.5.md, go.mod, go.sum, lnwallet/test/test_interface.go, routing/chainview/interface_test.go, scripts/install_bitcoind.sh
This release includes a single PR: #8573. This fixes an issue with bitcoind which starts to explicitly reject values it deems to be high fee from `sendrawtransaction`. See #8571 for more details.
=> release: create v0.17.5 release branch 

itest/lnd_mpp_test.go
This PR fixes the ascii so that it's the same as the one [here](https://github.com/lightningnetwork/lnd/blob/b76f733a9edc452385ad8e5a3ed8fe391d827182/itest/lnd_mpp_test.go#L177).
=> itest: fix ascii

lntest/node/harness_node.go
In this commit we add the LND node name to the temporary directory's name. This change makes it easier to identify a particular test node's temporary directory.
This commit also replaces the depreciated `ioutil.TempDir` function call with `os.MkdirTemp`.
1. Create a new test harness node with a unique name.
2. Observe the node's directory in the system tmp directory.
=> lntest: add test node name to tmp directory name

cmd/lncli/walletrpc_active.go, docs/release-notes/release-notes-0.18.0.md
Simple fix of the `lncli wallet bumpfee` parsing of the immediate/force flag.
=> fix lncli bumpfee flag parsing

docs/release-notes/release-notes-0.18.0.md, itest/lnd_amp_test.go, lnrpc/routerrpc/router_backend.go, lntest/harness.go
In this commit, we fix an inconsistent in the API related to AMP payments. When a payment request isn't specified, we require the `--amp` flag on the CLI to make an AMP payment. However, for payment requests, we don't require this flag. To fix this inconsistency, we now require the `--amp` flag to _also_ be set for payment requests.
=> lnrpc: ensure parsing of the Amp flag for payments is consistent

docs/release-notes/release-notes-0.18.0.md, itest/lnd_misc_test.go, rpcserver.go, sweep/walletsweep.go
The itest has been reverted to test the default behavior.
=> rpc: add default conf target back

channeldb/forwarding_package_test.go
In this commit, we fix a race in the `TestPackager` series on channeldb. A few tests were sharing the same global variable of the set of log updates, which includes a pointer to an HTLC. The `ExtraData` value of the HTLC would then be mutated once we go to encode the message on disk.
To fix this, we the global with a function that returns a new instance of all the test data.
```
Write at 0x0000021b0a48 by goroutine 2896:
github.com/lightningnetwork/lnd/lnwire.(*ExtraOpaqueData).PackRecords()
/home/runner/work/lnd/lnd/lnwire/extra_bytes.go:74 +0x546
github.com/lightningnetwork/lnd/lnwire.EncodeMessageExtraData()
/home/runner/work/lnd/lnd/lnwire/extra_bytes.go:121 +0x4d
github.com/lightningnetwork/lnd/lnwire.(*UpdateAddHTLC).Encode() …
```
=> channeldb: fix race in TestPackager by removing global test var

Makefile
Mounts a local temporary folder to the linter docker container in order to persist the linter cache across runs.
This may speed up linting, depending on which files are modified, some sample:
* `Execution took 1m9s`: no cache
* `Execution took 55s`: modified `channeldb` package
* `Execution took 24s`: modified `routing` package
* `Execution took 13s`: modified `server.go`
* `Execution took 2s`: no changes
Not sure if the `mkdir` command will interfere with windows setups, or how to circumvent that best?
=> make: add cache directory for linter

docs/release-notes/release-notes-0.18.0.md
Adds contributors found through `git shortlog -sne v0.17.5-beta..v0.18.0-beta.rc1` (with some manual work to arrive at GitHub usernames or name/surname if available).
Also polishes the release notes somewhat.
=> 0.18: add contributors from git log, polish release notes

channeldb/channel.go, channeldb/channel_test.go, contractcourt/chain_watcher.go, funding/manager.go, input/script_utils.go, lnwallet/chancloser/chancloser_test.go, lnwallet/chanfunding/canned_assembler.go, lnwallet/chanfunding/interface.go, lnwallet/chanfunding/psbt_assembler.go, lnwallet/chanfunding/wallet_assembler.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/musig_session.go, lnwallet/reservation.go, lnwallet/test_utils.go, lnwallet/wallet.go, peer/musig_chan_closer.go, routing/router.go
Replaces https://github.com/lightningnetwork/lnd/pull/8546 (with correct base branch and upstream feature branch).
In this PR, we add the initial plumbing that'll allow users to create and use musig2 channels that also commit to a tapscript root. Along the way, we start to store a new optional tapscript root in the `channeldb.OpenChannel` struct within the existing TLV stream appended to the older hard coded byte stream. The musig2 session itself will now conditionally pass in a tapscript root to the key aggregation and signing operations. We've also hooked up the lower half of the funding flow (lnwallet reservations) as well to ensure the new field gets propagated all the way down the relevant call stacks. 
Link to all PRs in the saga:
- 1/?: …
=> [1/?]: multi: add ability to fund+use musig2 channels that commit to a tapscript root

channeldb/invoices.go, invoices/invoices_test.go
In 0.18 we no longer check the pending invoices for deletion count. This will cause a failure to start in LND. This fixes it by making a noop in the `DeleteCanceledInvoices` func.
1. Startup lnd node with no invoices and `gc-canceled-invoices-on-startup=true`
=> invoices: if there are no invoices make gc noop

itest/lnd_route_blinding_test.go
In [build](https://github.com/lightningnetwork/lnd/actions/runs/8856782353/job/24323472072), we're failing because we need to wait for an on chain resolution of a htlc timeout to complete _then_ assert that it's been removed from the sender's channels. which takes pretty long. 
This PR adds more checks in between mining the timeout tx and asserting that the htlc is cleared out so that slower machines won't time out. 
```
=== RUN   TestLightningNetworkDaemon/tranche03/145-of-154/neutrino/on_chain_to_blinded
harness.go:437: finished test: multi_hop_local_force_close_on-chain_htlc_timeout, start height=1716, end height=1759, mined blocks=43
=== RUN   TestLightningNetworkDaemon/tranche00/37-of-154/neutrino/multi_hop_local_force_close_on-chain_htlc_timeout/zeroconf=false/committype=SCRIPT_ENFOR …
```
=> itest/flake: add more comprehensive assertions before HTLC cleared check

invoices/invoiceregistry_test.go, invoices/invoices_test.go
Add a temporary mutex around the call to sqldb.NewTestSqliteDB in the TestInvoiceRegistry test to ensure that only a single thread can access it at a time. This is a temporary work around that can be removed once this race condition in the sqlite repo has been resolved: https://gitlab.com/cznic/sqlite/-/issues/180
=> invoices: ensure synchronous access to NewTestSqliteDB

.github/workflows/main.yml, .gitignore, Makefile, make/testing_flags.mk, scripts/itest_part.sh
Fixes https://github.com/lightningnetwork/lnd/issues/7363.
Adds integration test coverage tracking instrumentation.
Since `Golang v1.20.x` allows writing coverage data even for processes that are started as their own sub process (which we do with `lnd` during the integration tests), we can now better assess the actual test coverage of our code as a combination of unit and integration tests.
=> Add test coverage for integration tests

Makefile, dev.Dockerfile, docs/release-notes/release-notes-0.18.0.md
Add a new `make install-all` command that will perform all `make install` actions along with generating the manpages. The `manpages` command is then removed from the existing `make install` command. The docker build is then updated to use the new `make install-all` command. This is done because some users running `make install` may be doing so in environments where they do not have write access to the directory where the man pages need to be written to.
=> makefile+dev.Dockerfile: add install-all command

docs/release-notes/release-notes-0.18.0.md, routing/notifications.go, routing/notifications_test.go, rpcserver.go
Adds inbound fees to notifications, used in the `SubscribeChannelGraph`
=> add inbound fees channel updates to notifications

routing/unified_edges.go
Fix logging issue encountered during work on https://github.com/lightningnetwork/lnd/pull/8734.
=> routing: log edge when skipping it

config.go, docs/release-notes/release-notes-0.18.0.md, lncfg/protocol.go, lncfg/protocol_experimental_off.go, lncfg/protocol_experimental_on.go, lncfg/protocol_integration.go, sample-lnd.conf, server.go
This PR simply moves the experimental custom message config options to the main protocol config, so that the dev build flag doesn't need to be set to use them. Closes issue #8536.
We've gotten multiple requests for this at LNDK -- people don't want to be running LND in dev mode in production. There hasn't been any discussion on the #8536 issue, so hoping to at least spur discussion on what needs to happen to make this change feasible. :)
Tested this with LNDK to confirm it works properly.
The config options set in `sample-lnd.conf` should be possible to set without the dev flag.
=> cfg: move experimental options to main protocol cfg

funding/manager.go
Add missing error logs when the ChannelAcceptor does not enable zero-conf in the ChannelAcceptResponse to an incoming funding request with the zero-conf feature enabled.
To test this connect a channel acceptor to the lnd node that accepts incoming channels but sets zero_conf to false.
For example a Python script that connects through gRPC:
```python
import lightning_pb2 as lnd
import lightning_pb2_grpc as lndrpc
import grpc
import os
import queue
import codecs
os.environ["GRPC_SSL_CIPHER_SUITES"] = "HIGH+ECDSA"
with open(os.path.expanduser("~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon"), "rb") as macaroon_file:
macaroon = macaroon_file.read()
macaroon = codecs.encode(macaroon, "hex")
with open(os.path.expanduser("~/.lnd/tls.cert"), "rb") as cert_file:
cert = cert_file.read()
def …
```
=> funding: add absent error logs for failed inbound funding requests

chainntnfs/txnotifier.go, cmd/lncli/walletrpc_active.go, contractcourt/chain_arbitrator.go, contractcourt/channel_arbitrator.go, contractcourt/channel_arbitrator_test.go, itest/list_on_test.go, itest/lnd_channel_force_close_test.go, itest/lnd_multi-hop_test.go, itest/lnd_sweep_test.go, sweep/README.md, sweep/fee_bumper.go, sweep/fee_function.go, sweep/fee_function_test.go, sweep/sweeper.go, sweep/sweeper_test.go, sweep/tx_input_set.go
Fixes #8741 
Fixes #8738
TODO:
=> contractcourt+sweep: fix fee function and deadline issue

peer/brontide_test.go, peer/test_utils.go
This pull request is an off shoot of the peer backup PR (currently halted): https://github.com/lightningnetwork/lnd/pull/8490
It removes the duplicity in creating a peer instance and starting a peer in brontide tests.
It does not require a change log.
=> [code-health]: reduce duplication in brontide test.

fn/slice.go, fn/slice_test.go
This PR adds a new function to check if the values in a slice have duplicates.
=> fn: Added `HasDuplicates` function to slice

peer/brontide.go, peer/ping_manager.go, peer/ping_manager_test.go
Here we do the following things to increase stability with tor peers:
1. Reduce maximum pong payload size to ease bandwidth consumption
2. Make PingManager.Stop infallible so that it doesn't pollute the logs with false errors in the case where we fail to send or receive the `init` message.
3. If we detect that the connection with our peer is over tor (heuristic), then we will triple the timeout parameters to give them more time to respond.
Run this patch with a bunch of tor peers and see if it improves the long term stability of those peers.
=> Adjust ping parameters to improve tor stability

config_builder.go, htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/mock.go, lnwallet/channel.go, routing/bandwidth.go, routing/bandwidth_test.go, routing/integrated_routing_context_test.go, routing/mock_test.go, routing/pathfind.go, routing/payment_lifecycle.go, routing/payment_session.go, routing/payment_session_source.go, routing/payment_session_test.go, routing/router.go, routing/unified_edges.go, routing/unified_edges_test.go, server.go
Closes #8617 
Based on #8660
This PR adds a `TlvTrafficShaper` function as part of the bandwidth hints. This function can be optionally defined to provide an external way of evaluating whether a channel is capable of carrying out a payment or not.
=> routing: add TlvTrafficShaper to bandwidth hints

channeldb/models/channel_edge_info.go, config_builder.go, discovery/gossiper.go, funding/aux_funding.go, funding/manager.go, itest/lnd_psbt_test.go, lnwallet/chanfunding/canned_assembler.go, lnwallet/chanfunding/psbt_assembler.go, lnwallet/reservation.go, lnwallet/test/test_interface.go, lnwallet/wallet.go, log.go, peer/brontide.go, protofsm/log.go, protofsm/msg_router.go, protofsm/msg_router_test.go, routing/router.go, server.go
Depends on https://github.com/lightningnetwork/lnd/pull/8684.
In this commit, we add the `AuxFundingController` interface that can be used to implement a class of custom funding channels that only requires some additional data to be inserted into the tapscript leaves for the funding/HTLC/commitment outputs. This controller _also_ implements the `MsgEndpoint` interface (see https://github.com/lightningnetwork/lnd/pull/8520) as well. This allows the controller to intercept certain custom messages related to the funding process (think extra sigs for a channel factory), and even the existing funding messages. 
We then create a new top level config entry for this interface. This allows an external program to instantiate a `AuxFundingController`, make a `MsgRouter`, register that, then pass …
=> [3/5]: multi: add new AuxFundingController for custom external funding flows 

chainreg/chainregistry.go, config_builder.go, contractcourt/chain_arbitrator.go, funding/manager.go, htlcswitch/link.go, lnwallet/aux_signer.go, lnwallet/channel.go, lnwallet/commitment.go, lnwallet/config.go, lnwallet/sigpool.go, lnwallet/wallet.go, peer/brontide.go, server.go
Depends on https://github.com/lightningnetwork/lnd/pull/8622.
In this PR, we add a new aux signer interface that's meant to mirror the SigPool. If present, this'll be used to (maybe) obtain signatures for second level HTLCs for certain classes of custom channels.
Link to all PRs in the saga:
- 1/5: https://github.com/lightningnetwork/lnd/pull/8683
- 2/5: https://github.com/lightningnetwork/lnd/pull/8684
- 3/5: https://github.com/lightningnetwork/lnd/pull/8622
- 4/5: https://github.com/lightningnetwork/lnd/pull/8632
- 5/5: https://github.com/lightningnetwork/lnd/pull/8641
- 6/5: https://github.com/lightningnetwork/lnd/pull/8771
=> [4/5]: lnwallet: add new AuxSigner interface to mirror SigPool 

fn/result.go
Add a new `Result` type to the `fn` submodule, which is just Either[A, error]. This is useful as we can always pass around/accept a single value. We add an Unpack() method which is the most idiomatic way of handling errors in Go, as we revert back to (A, error) when necessary.
=> fn: add Result type

docs/release-notes/release-notes-0.18.1.md
So that each PR currently open and aimed at 0.18.1 doesnt need to add this doc :)
=> docs: add release notes template for 0.18.1

cmd/lncli/cmd_import_mission_control.go, docs/release-notes/release-notes-0.18.1.md, lnrpc/routerrpc/router_server.go
Aims to fix #8778 
Do not throw an error when importing a `HistoryPair` with a zero failure amount. A zero failure amount can happen, since the amount won't be saved on a node failure, like [here](https://github.com/lightningnetwork/lnd/blob/22f4724260f74619799ca8a7774e10f5c581000e/routing/missioncontrol_state.go#L148-L149)
You can import a history pair with a 0 failure amount
=> Allow 0 failure amt on importmc

fn/predicate.go
This is a commit needed for #8800. I'm peeling it off into a separate PR to allow CI to pass there since we need to push tags for CI to recognize the new functions in the `fn` package.
n/a
=> fn: add predicate combinators for && and ||

cmd/lncli/cmd_payments.go, docs/release-notes/release-notes-0.18.1.md
Previously when sending an AMP payment specifying the payment request and the `--amp` flag together the `Amp` field of the `SendPaymentRequest` was not filled properly. This PR attempts to fix this.
=> lncli: fix parsing of --amp when sending a payment

channeldb/graph.go, contractcourt/breach_arbitrator_test.go, discovery/gossiper.go, funding/manager.go, netann/chan_status_manager.go, peer/brontide.go, rpcserver.go, server.go
Fixed complaints from IDE and linters, and improved returned errors when creating this [analysis](https://github.com/lightningnetwork/lnd/issues/7261#issuecomment-2153008660).
=> trivial: fix linter errors and return verbose errors

contractcourt/chain_watcher.go, docs/release-notes/release-notes-0.18.1.md, go.mod, go.sum, itest/list_on_test.go, itest/lnd_coop_close_external_delivery_test.go, lntest/harness.go
This commit fixes https://github.com/lightningnetwork/lnd/issues/8535 by changing how we assess toSelfAmount inside
the chainWatcher.
In certain cases users may wish to close out channel funds to external
delivery addresses set either during open or close.
Prior to this change we only consider addresses that our wallet is
aware of and permitted the possibility of multiple to_self outputs,
which is impossible according to the protocol.
This change now identifies to_self outputs based off of matching
delivery scripts, and if no delivery script is set, fall back to
the first output that our wallet can recognize.
NOTE FOR REVIEWERS: The itest commit is ordered first to confirm that the test fails prior to the change. After the fix commit, the test passes. If you want to confirm that the test …
=> contractcourt: consider delivery addresses when evaluating toSelfAmount

.github/actions/rebase/action.yml, .github/workflows/main.yml
That way, we should be able to re-trigger the CI tests if a flake fix has been merged and we want to see that the CI passes in a given PR without needing the author to rebase.
=> .github: rebase before running itests & unit tests

itest/lnd_misc_test.go, lntest/harness_assertion.go
Fixes itest flake found in [this build](https://github.com/lightningnetwork/lnd/actions/runs/9499362448/job/26180102404) in the `abandonchannel` test. 
When abandoning a channel, we remove it from the graph and then add it to the zombie channel index. However, if we then process a ChannelUpdate for this channel it will result in us calling `processZombieUpdate` which will delete the edge from the zombie index. The abandon channel itest currently asserts that a channel is no longer in the graph by asserting that when querying for the channel we get a "marked as zombie" error but to account for the above series of operations, we now also allow it to just not be found at all ("edge not found").
1. AbandonChannel: 
1. remove from open channel bucket & add close channel entry 
2. remove from …
=> itest+lntest: let abandoned channel be either not found or in zombie

config.go, docs/release-notes/release-notes-0.18.1.md
Fixes the issue of @theborakompanioni when updating to LND v0.18.0-beta: https://github.com/lightningnetwork/lnd/pull/7867#issuecomment-2158279005
Having removed option groups in the config caused the config file parser to throw an error, but that error is `flags.Error` which only printed a warning but did not prevent starting the node.
=> cfg: fail startup on flags.Error parsing error

docs/release-notes/release-notes-0.18.1.md, routing/missioncontrol_store.go, routing/missioncontrol_store_test.go
The current implementation of the Misson Control Store [has a one second ticker](https://github.com/lightningnetwork/lnd/blob/d9887f32129b21e40cf88c79512b16dc5d1715fb/routing/missioncontrol_store.go#L284) that trims the DB, ensuring only the latest 1000 entries are kept.
That ticker was added in https://github.com/lightningnetwork/lnd/pull/5515 as a way to improve performance by batching and de-duplicating the updates to the db.
However, its current implementation can be significantly improved by doing a few pointed changes. In particular:
1. There is no need to open a db tx when there is no work.
2. The ticker does not need to run continuously, only when there are items in the queue that need to be persisted.
3. The current implementation duplicates the entire in-memory cache of the …
=> Misson Control Store: Improve performance

cmd/lncli/walletrpc_types.go
Turns out the `pendingsweeps` cli doesn't use the proto directly so we need to update the returned response to reflect the new fields.
=> cli: update `pendingsweeps` response

docs/INSTALL.md
Building current lnd `0.18` fails with older go (`1.19.7`).
* Updated go download path to 1.22.4
* Updated hashes
* Added `rm -rf` instructions as per [go.dev instructions](https://go.dev/doc/install)
Please:
* Check lnd works fine on 1.22.4 (it does for me)
* Verify the hashes I updated
N/A
N/A -- only updated paths
=> [docs] Update go instructions

docs/release-notes/release-notes-0.18.1.md, docs/release-notes/release-notes-0.18.2.md, go.mod, go.sum
Here's what happened,
1.  `lnd` asks `btcwallet` to publish a tx -> calls `btcd` RPC
2. an old `btcd` is running, and gives an error back: `already have transaction ...`
3. `btcwallet` tries to map the error, using a method imported from new `btcd/rpcclient`, which matches against `already have transaction in mempool ...`, which is an error string returned from this new `btcd`
4. the match failed
Diving deeper about how to avoid this from a design perspective,
- remove the broadcaster, which is designed for `neutrino` backend, and replace it with a mempool rebroadcaster - today we always broadcast twice for each tx, and rebroadcast it in every new block - this is unnecessary or not enough as the tx may fall out of the mempool during the 10min. I think a better approach is to poll the …
=> Fix an error string match between different `btcd` versions

build/version.go, docs/release-notes/release-notes-0.18.1.md, go.mod, go.sum
Re-opening #8863 with update to btcd to point to latest pushed tag
=> build: create v0.18.1-beta release branch

routing/pathfind.go, routing/pathfind_test.go
This commit removes another check for TLV payload support of the destination node. We assume TLV payloads as the default everywhere else, so we just remove two checks that were previously forgotten.
=> routing: remove TLV feature bit check

docs/release-notes/release-notes-0.18.2.md, routing/pathfind.go, routing/pathfind_test.go
Repeat of https://github.com/lightningnetwork/lnd/pull/8873 but aimed at master. 
This PR removes some left over TLV feature bit checks that were forgotten in https://github.com/lightningnetwork/lnd/pull/8791.
=> routing: remove left over TLV feature bit checks

docs/release-notes/release-notes-0.18.2.md, funding/manager.go
~If our peer indicates to us that they are OK with a zero conf channel (ie, they trust us) by setting min-depth to 0 in accept_channel, then as long as they support SCID aliases, we should just upgrade the channel to ZeroConf and continue the funding flow.~
EDIT: updated to just allow the peer to set min-depth to 0. We dont upgrade the channel type.
Fixes #8783 
NOTE: we already allow ourselves to do this when our peer sends us an OpenChannel without a zero-conf channel type: https://github.com/lightningnetwork/lnd/blob/fed760913ff98a89c73414acde6cf29f8728321a/funding/manager.go#L1570-L1583
So all this PR does is allow our peer to do this too :)
=> multi: allow min-depth of zero for non-zero conf channels

chainreg/no_chain_backend.go, config_builder.go, docs/release-notes/release-notes-0.18.2.md, docs/release-notes/release-notes-0.18.3.md, go.mod, go.sum, lnmock/chain.go, lnwallet/btcwallet/btcwallet.go, lnwallet/btcwallet/btcwallet_test.go, lnwallet/test/test_interface.go, sweep/fee_bumper.go, sweep/fee_bumper_test.go
This PR fixes the matching errors used in `lnwallet.ErrDoubleSpend`, a misuse of error found in the rebroadcaster's `broadcastErrorMapper`, and updates the `btcd` version to fix another error str mismatch among different versions.
Depends on,
- https://github.com/btcsuite/btcwallet/pull/937
=> multi: fix `lnwallet.ErrDoubleSpend`

docs/release-notes/release-notes-0.18.3.md, go.mod, go.sum, invoices/invoices_test.go, invoices/sql_store.go, sqldb/go.mod, sqldb/go.sum, sqldb/migrations.go, sqldb/migrations_test.go, sqldb/postgres.go, sqldb/postgres_fixture.go, sqldb/postgres_test.go, sqldb/sqlc/migrations/000004_invoice_expiry_fix.down.sql, sqldb/sqlc/migrations/000004_invoice_expiry_fix.up.sql, sqldb/sqlite.go, sqldb/sqlite_test.go
Previously, when using the native schema, invoice expiries were incorrectly stored as 64-bit values (expiry in nanoseconds instead of seconds), causing overflow issues. Since we cannot determine the original values, we will set the expiries for existing invoices to 1 hour with this migration.
Based on https://github.com/lightningnetwork/lnd/pull/8854 only the last 5 commits are part of this PR.
=> sqldb+invoices: fix incorrectly stored invoice expiries when using native SQL

peer/brontide.go
In this commit, we fix a bug that would cause a global message router to be stopped anytime a peer disconnected. The global msg router only allows `Start` to be called once, so afterwards, no messages would properly be routed.
=> peer: don't stop global msg router

cmd/lncli/cmd_payments.go, docs/release-notes/release-notes-0.18.3.md, htlcswitch/hop/iterator.go, htlcswitch/hop/iterator_test.go, htlcswitch/hop/payload_test.go, itest/lnd_route_blinding_test.go, lnrpc/invoicesrpc/utils.go, lnrpc/lightning.pb.go, lnrpc/lightning.proto, lnrpc/lightning.swagger.json, record/blinded_data.go, record/blinded_data_test.go, routing/additional_edge.go, routing/additional_edge_test.go, routing/blinding.go, routing/blinding_test.go, routing/pathfind.go, routing/pathfind_test.go, routing/router.go, routing/unified_edges.go, routing/unified_edges_test.go, rpcserver.go, zpay32/blinded_path.go, zpay32/decode.go, zpay32/encode.go, zpay32/invoice.go, zpay32/invoice_test.go
To make review a bit more manageable, I've split out some of the groundwork needed for 
the main route blinding receives PR. This PR thus has no functional changes. 
Tracking Issue: https://github.com/lightningnetwork/lnd/issues/6690
1) a couple of refactors & interface expansions so that we have easy access to the `BlindedPayment` associated with an edge in path finding later on. 
2) Remove the need to communicate the "TLV Option" in a blinded path feature bit vector. This bit can be assumed for any nodes in a blinded path. 
3) Add fields to `BlindedRouteData` that will be required for receives. Namely, PathID and Padding. 
4) Bolt11 blinded payment path encoding
EDIT:  bLIP proposal here: https://github.com/lightning/blips/pull/39
=> [1/4] Route Blinding Receives: Groundwork

contractcourt/chain_watcher.go, contractcourt/commit_sweep_resolver.go
This PR fixes two bugs with Taproot Channel closures. These bugs never had corresponding issue documentation so they will be described here:
---
1. The first bug is an issue wherein we only identified a coop close transaction as one that had the finalized squence number. Since taproot channels use the new RBF coop close process, they will have the max RBF-able sequence number instead. Right now we do not correctly identify this RBF coop close transaction for taproot channels.
SOLUTION: include the max RBF sequence number in the heuristic for identifying coop close transactions.
---
2. The second bug is an issue wherein we fail to properly identify whether the commitment transaction was broadcast by the local or remote party because we use a broken heuristic when analyzing the output …
=> contractcourt: Taproot Channel Bugfixes

docs/release-notes/release-notes-0.18.3.md, go.mod, go.sum
Depends on https://github.com/btcsuite/btcwallet/pull/941.
Fixes https://github.com/lightningnetwork/lnd/issues/8697 by updating `btcwallet` to the latest version.
=> btcwallet: bump dependency to fix duplicate address creation

go.mod, go.sum, lnwallet/aux_signer.go, lnwallet/channel.go
We can use this space as we'll properly encode the blinded paths data along with our custom fields before we go to write the HTLCs to the wire.
=> lnwallet: store aux sig in custom data within the HTLC

.github/workflows/release.yaml, go.mod, go.sum
Depends on https://github.com/lightninglabs/gh-actions/pull/2.
This fixes the problem where releases wouldn't be created anymore due to the GitHub Action for creating the draft release being out of date.
I've confirmed this works with the following run in my fork of the repository: https://github.com/guggero/lnd/actions/runs/10058716669/job/27802410976
=> GitHub: update vendored release script

chainntnfs/bitcoindnotify/bitcoind_test.go, chainntnfs/test_utils.go, lntest/unittest/backend.go
[This flake](https://github.com/lightningnetwork/lnd/actions/runs/9987408253/job/27601725201) has popped up multiple times,
```
2024/07/18 08:06:20 Running ChainNotifier interface tests for: btcd
--- FAIL: TestInterfaces (67.92s)
--- FAIL: TestInterfaces/btcd_historical_spend_dispatch (30.06s)
test_interface.go:872: spend ntfn never received
FAIL
FAIL	github.com/lightningnetwork/lnd/chainntnfs/test/btcd	67.937s
FAIL
```
Turns out it's failing here, where we rescan blocks to find the relevant spending tx,
https://github.com/lightningnetwork/lnd/blob/6dea86428d031171af30119e3f6599820dc5454a/chainntnfs/txnotifier.go#L1310-L1315
It's also easy to reproduce - need to run it multiple times tho,
```sh
case=TestInterfaces/btcd_historical_spend_dispatch_with_script_dispatch …
```
=> chainntnfs+lntest: fix `TestInterfaces`

docs/release-notes/release-notes-0.18.3.md, itest/lnd_funding_test.go, rpcserver.go, server.go
Simple fix, though the underlying design probably needs some refactor because even for the batchopen flow we don't really need to do the fee-calculation for every channel but rather for the whole request.
Fixes https://github.com/lightningnetwork/lnd/issues/8895
Will add release-notes as soon as we decided in which release this will be included.
=> Fix batchopen fee calculation

cmd/commands/cmd_payments.go
We want to re-use the logic of the SendPaymentRequest code, most notably the logic that prints the payment updates as a nicely formatted table to the console, in other projects.
=> cmd/commands: refactor SendPaymentRequest for re-use

docs/leader_election.md
Add the missing SERVER_ACTIVE state to the readiness probe. Without
this, a node that is ready to accept RPC calls would be incorrectly
considered not ready.
`lncli state`
=> docs: fix leader node readiness probe example

docs/release-notes/release-notes-0.18.3.md, itest/list_on_test.go, itest/lnd_routing_test.go, lntest/node/watcher.go, routing/pathfind.go
When iterating edges, pathfinding checks early whether using an edge would violate the requested total fee limit for a route. This check is done on the net amount (an amount the inbound fee is calculated with). However, a possible next hop's fee discount leads to a reduction in fees and as such using the net amount leads to assuming a higher cumulative fee than the route really has, excluding the path erroneously. With this PR, we perform the fee limit check on the amount to send, which includes both inbound and outbound fees, to fix #8940.
Todo:
- remove itest, add more lightweight test?
=> routing: fix fee limit condition

contractcourt/channel_arbitrator.go, docs/release-notes/release-notes-0.18.3.md, itest/lnd_sweep_test.go
Resulted from https://github.com/lightningnetwork/lnd/pull/8843
Splitted the PR to first address the bugfix.
Fixes https://github.com/lightningnetwork/lnd/issues/8837
=> Fix bumpforceclose behavior for force closes without htlcs.

config.go, docs/release-notes/release-notes-0.18.3.md, htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/link_test.go, htlcswitch/mock.go, htlcswitch/switch.go, htlcswitch/switch_test.go, itest/lnd_payment_test.go, lnwallet/channel.go, lnwallet/channel_test.go, peer/brontide.go, server.go
Small-ish change to the link to include commitment fees in dust calculation.
=> multi: include commitment fees in dust calculation

docs/release-notes/release-notes-0.18.3.md, kvdb/etcd/config.go, kvdb/etcd/db.go, kvdb/etcd/fixture.go, sample-lnd.conf
This patch allow set multiple etcd servers. like an etcd cluster in docker swarm/kubernetes.
./lnd-debug \
--db.backend=etcd \
--db.etcd.host=etcd1:2379,etcd2:2379 \
=> Allow multiple etcd host

channeldb/channel.go, channeldb/channel_test.go, channeldb/db_test.go, contractcourt/chain_arbitrator_test.go, contractcourt/chain_watcher.go, contractcourt/channel_arbitrator.go, contractcourt/channel_arbitrator_test.go, htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/mailbox.go, htlcswitch/mock.go, htlcswitch/switch.go, htlcswitch/switch_test.go, input/script_utils.go, input/size_test.go, input/taproot_test.go, lntypes/channel_party.go, lnwallet/chancloser/chancloser.go, lnwallet/chancloser/chancloser_test.go, lnwallet/chancloser/interface.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/commitment.go, lnwallet/wallet.go, peer/brontide.go
This PR introduces a new fundamental type ChannelParty for the purposes of disambiguating all of the Local/Remote/Incoming/Outgoing stuff found throughout the codebase. This will reduce incidence of [boolean blindness](https://existentialtype.wordpress.com/2011/03/15/boolean-blindness/) and will compose well with other additions later on. 
make unit pkg=lnwallet
=> [MILLI]: Introduce and use ChannelParty

fn/req.go
It is common throughout the codebase to send data to a remote goroutine for processing. Typically, along with the data we are processing, we also send a one-shot channel where we intend to listen for the response. This type encapsulates that pattern.
This was spun off during discussion [here](https://github.com/lightningnetwork/lnd/pull/8270#discussion_r1617694428)
=> [MICRO]: fn: Add new Req type to abstract the pattern of remote processing.

docs/release-notes/release-notes-0.18.3.md, itest/list_on_test.go, itest/lnd_route_blinding_test.go, lnrpc/routerrpc/router_backend.go, routing/blinding.go, routing/blinding_test.go, routing/pathfind.go, routing/pathfind_test.go, routing/payment_session.go, routing/router.go, routing/router_test.go, rpcserver.go, zpay32/blinded_path.go
In this PR, we remove the restriction of only being able to send to a single blinded payment path.
Nodes will now be able to take advantage of the multiple blinded paths provided for a given 
payment to perform MPP if needed. 
Depends on: https://github.com/lightningnetwork/lnd/pull/8735
Tracking Issue: https://github.com/lightningnetwork/lnd/issues/6690
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/8764)
=> [3/4] Route Blinding: send MPP over multiple blinded paths  

cluster/etcd_elector.go, cluster/etcd_elector_test.go, cluster/interface.go, config.go, docs/release-notes/release-notes-0.18.3.md, go.mod, go.sum, healthcheck/healthcheck.go, itest/list_on_test.go, itest/lnd_etcd_failover_test.go, itest/lnd_no_etcd_dummy_failover_test.go, kvdb/etcd/stm.go, lncfg/cluster.go, lncfg/healthcheck.go, lnd.go, lntest/node/config.go, sample-lnd.conf, server.go
LND currently holds the leader lease until shutdown, at which point it will resign. In some scenarios, it may be desirable for LND to relinquish leadership and shut down if it becomes partitioned from the etcd cluster. This PR aims to implement this behavior by adding a leader status check to the existing health checks, which will verify the leader status every minute. To prevent hanging due to network issues, we also introduce reasonable timeouts for etcd calls. This allows for a clean shutdown upon a request from the health check module.
Fixes: https://github.com/lightningnetwork/lnd/issues/8913
```make itest backend=bitcoind dbbackend=etcd icase=leader_health_check```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> multi: check leader status with our health checker to correctly shut down LND if network partitions

chainntnfs/bitcoindnotify/bitcoind.go, chainntnfs/neutrinonotify/neutrino.go, chanfitness/chaneventstore.go, discovery/gossiper.go, docs/release-notes/release-notes-0.18.3.md, graph/builder.go, htlcswitch/interceptable_switch.go, htlcswitch/link.go, invoices/invoiceregistry.go, lnd.go, lnwallet/chainfee/estimator.go, server.go, sweep/fee_bumper.go, tor/controller.go
~~Fixes https://github.com/lightningnetwork/lnd/issues/8489~~
EDIT: Fixes https://github.com/lightningnetwork/lnd/issues/8721
So in the above linked issue, the channel graph could not be synced correctly so the ChanRouter:
```
2024-02-20 11:18:39.217 [INF] CRTR: Syncing channel graph from height=830127 (hash=00000000000000000003a7ed3b7a5f5fd5571a658972e9db0af2a650f6ade198) to height=831246 (hash=00000000000000000002946973960d53538a7d93333ff7d4653a37a577ba4b58)
```
...
```
2024-02-20 11:19:11.325 [WRN] LNWL: Query(34) from peer 142.132.193.144:8333 failed, rescheduling: did not get response before timeout
2024-02-20 11:19:11.326 [DBG] BTCN: Sending getdata (witness block 000000000000000000028352e09a42f6d26d0514a3d483f7f1fb56b2c2954361) to 142.132.193.144:8333 (outbound)
2024-02-20 …
```
=> routing: shutdown chanrouter correctly.

.golangci.yml, Makefile, docker/btcd/Dockerfile, docs/INSTALL.md, lnrpc/Dockerfile, scripts/check-go-version-dockerfile.sh, scripts/check-go-version-yaml.sh
This PR adds two checks to the linter. These checks ensure that the Go version used in Dockerfile files and YAML files are consistent and as expected.
This PR also ensures that Go version 1.22.5 is used throughout the project.
(Note that I couldn't re-open https://github.com/lightningnetwork/lnd/pull/8211 I think it's because I forced pushed to the branch before re-opening?)
=> Linter checks go versions in Dockerfile and YAML files

lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/commitment_chain.go, lnwallet/update_log.go
depends on #8950.
lnwallet: refactor channel to use new typed List
Go didn't used to have parametric polymorphism (generics). Now it does. In a prior commit we introduced a more principled type to encapsulate a linked list, here we move the core structures in lnwallet/channel to use the new parametric type.
make unit pkg=lnwallet
=> [MICRO]: lnwallet: refactor channel to use new typed List

chanbackup/single_test.go, channeldb/channel.go, channeldb/channel_test.go, channeldb/db_test.go, contractcourt/breach_arbitrator_test.go, funding/manager.go, htlcswitch/test_utils.go, lnwallet/reservation.go, lnwallet/test/test_interface.go, lnwallet/test_utils.go, lnwallet/transactions_test.go, lnwallet/wallet.go, peer/test_utils.go, routing/localchans/manager.go, routing/localchans/manager_test.go
This commit breaks the ChannelConstraints structure into two sub-structures that reflect the fundamental differences in how these parameters are used. On its face it may not seem necessary, however the distinction introduced here is relevant for how we will be implementing the Dynamic Commitments proposal.
=> [MICRO]: multi: break ChannelConstraints into two sub-structures

go.mod, go.sum
To enable the changes from https://github.com/lightningnetwork/lnd/pull/8845, we need to use the new version of the `kvdb` submodule.
=> mod: bump kvdb to v1.4.10

channeldb/channel.go, lnwallet/channel.go
Spinoff from #8755. Useful for #8270 refactor. Simple API addition to convert database boolean representation to the ChannelParty domain type.
n/a
=> [MICRO]: channeldb+lnwallet: add OpeningParty API

go.mod, lnrpc/gen_protos_docker.sh
Because the Go version used to run the `go list` commands is below the minimum version specified in the main go.mod file, every time the `make rpc` command is executed, the Golang runtime is downloaded twice, which looks like this and takes a couple of seconds at least:
```
go: downloading go1.21.4 (linux/amd64)
go: downloading go1.21.4 (linux/amd64)
```
Example run: https://github.com/lightningnetwork/lnd/actions/runs/10270305816/job/28417733765
We fix this by using the correct minimum version.
=> lnrpc: avoid needing to download Golang

channeldb/graph_test.go, channeldb/models/cached_edge_policy.go, channeldb/models/channel_edge_policy.go, docs/release-notes/release-notes-0.18.3.md, lnrpc/routerrpc/router_server.go, routing/router.go, routing/router_test.go
This PR attempts to add support for inbound fees to `BuildRoute`. The three passes `BuildRoute` goes through (see https://github.com/lightningnetwork/lnd/issues/8814#issuecomment-2160012218 for an explanation) are altered to determine the edges in the backward pass (from receiver to sender) as opposed to the previous approach where this is done in the forward pass (sender to receiver). This way we get fixed edges that can be used to determine the minimal sender/maximal receiver amount with inbound fees, doing a reverse amount calculation (thanks to @feelancer21 for the analysis https://github.com/lightningnetwork/lnd/issues/8814#issuecomment-2168351570). The computation for the outgoing amount based on the incoming amount is done using `big.Int` arithmetic.
Previous work on this: …
=> routing: inbound fees support for BuildRoute

channeldb/forwarding_package.go, channeldb/payment_control.go, channeldb/payment_control_test.go, docs/release-notes/release-notes-0.18.3.md, htlcswitch/link.go, htlcswitch/payment_result.go, htlcswitch/switch.go, itest/list_on_test.go, itest/lnd_payment_test.go, lntest/harness.go, lntest/harness_miner.go, routing/mock_test.go, routing/payment_lifecycle.go, routing/router.go, routing/router_test.go, server.go
Replaces #8150, this PR attempts to fix #8146.
The original assumption was, when the HTLC timed out, the attempt result wasn't sent back the payment lifecycle, thus causing the payment to be in stuck. However, this assumption is not true, as shown in the newly added itest - when an outgoing HTLC has timed out, the payment will be marked as failed. Moreover, if the outgoing HTLC is swept by the remote via the preimage path, the payment will be marked as succeeded. All these are expected behavior.
If there's already a result in db, `GetAttemptResult` will return it, so the result must not be found in db. Also notice that, since there's no result in db, the only line we can hit is:
https://github.com/lightningnetwork/lnd/blob/e6fbaafda4a9cfe08ccee5106aa6dc1da62bcebc/htlcswitch/switch.go#L466 …
=> routing: fix stuck inflight payments

docs/release-notes/release-notes-0.18.3.md, peer/brontide.go, peer/brontide_test.go, peer/test_utils.go
We have existing logic to attempt to reliably send a channel update to the remote peer. In the wild, we've seen this fail, as it's possible right when we send the update the peer disconnects.
In this commit, we implement a simple fix which is just to send the chan update each time we connect to the remote party.
Fixes https://github.com/lightningnetwork/lnd/issues/6870.
=> peer: always send channel update on reconnect

cmd/lncli/walletrpc_active.go
Follow-up for https://github.com/lightningnetwork/lnd/pull/8986.
This commit adds the new value that was added to the RPC response to the CLI output as well.
=> cmd/lncli: add min relay fee to `lncli wallet estimatefeerate`

discovery/gossiper.go, docs/release-notes/release-notes-0.18.3.md
Initially in lnd, we didn't store the extra TLV data that could be dangling off of gossip messages. This was fixed initially in lnd v0.5 with this PR: https://github.com/lightningnetwork/lnd/pull/1825.
Within the PR, we incorrectly set the `ExtraOpaqueData` (extra TLV blob) of the `ChannelAnnouncement` to the value stored in `edge`, which is actually our channel update. As 6-ish years ago we didn't yet have anything that used the TLV gossip fields, this went unnoticed.
Fast forward to 2024, we shipped an experimental version of inbound fee discounts. This starts to store additional data in the `ExtraOpaqueData` field: the TLV for the inbound fee discount. Initially, everything is valid when the first `ChannelAnnouncement` is sent, but as soon as a user attempts to set an inbound fee …
=> discovery: fix bug that can lead to sending invalid chan_ann msgs

docs/release-notes/release-notes-0.19.0.md, routing/missioncontrol.go, rpcserver.go, server.go
Fixes #8793	
modified:   rpcserver.go
modified:   server.go
modified:   routing/missioncontrol.go
Changed the DebugLevel function to start updating the main cfg DebugLevel variable.
Created the function UpdateRoutingConfig to just update the main cfg  values, this function is a callback function propagated by NewMissionControl function called when creating a new server on server.go. And finally, call the callback function on SetConfig on routing/missioncontrol.go
After running LND with the wallet unlocked, send the lncli commands to change the debuglevel and estimator and check if they are updated unsing 'getdebuginfo'.
=> Fixing the current state update when lncli debuglevel and lncli setmccfg are called

lntypes/channel_party.go
This commit introduces a new type Dual[A] to make it easier to manage symmetric configurations or state for lightning channels.
I'm extracting this commit from #8755 because it is proving to be useful in #8270 as well. It has applications anywhere we have symmetric structure, which in the channel state machine is ubiquitous.
N/A
=> [MICRO]: lntypes: Add Dual[A] primitive type

config_builder.go, go.mod, go.sum, lnd.go, msgmux/log.go, msgmux/msg_router.go, msgmux/msg_router_test.go, peer/brontide.go, server.go
In this commit, we add a new abstract message router. Over time, the goal is that this message router replaces the logic we currently have in the readHandler (the giant switch for each message).
With this new abstraction, can reduce the responsibilities of the readHandler to *just* reading messages off the wire and handing them off to the msg router. The readHandler no longer needs to know *where* the messages should go, or how they should be dispatched.
This will be used in tandem with the new `protofsm` module in an upcoming PR implementing the new rbf-coop close.
**NOTE**: This is a remade version of this branch, see this comment: https://github.com/lightningnetwork/lnd/pull/8434#issuecomment-1978017668
=> [2/4] - peer: add new abstract message router

channeldb/graph.go, channeldb/graph_test.go, discovery/gossiper.go, discovery/sync_manager.go, discovery/syncer.go, discovery/syncer_test.go, docs/release-notes/release-notes-0.18.3.md
Fixes parts of https://github.com/lightningnetwork/lnd/issues/8889 especially nr. 1-3 in comment https://github.com/lightningnetwork/lnd/issues/8889#issuecomment-2289135744
The last commit introduces a check to not query channel which have outdated timestamp data. However I think we should also implement `encoded_query_flags ` of the `query_short_channel_ids ` msg. Meaning that we query for specific msg and therefore anticipate the correct msg from the peer. If the peer cannot send us a ChanUpdate although he claimed to have sone with a specific timestamp in the `RangeReply` which should probably punish him ?
=> Fix TimeStamp issue in the Gossip Syncer

docs/release-notes/release-notes-0.18.3.md, go.mod, go.sum, itest/lnd_hold_invoice_force_test.go, itest/lnd_psbt_test.go, itest/lnd_route_blinding_test.go, lnrpc/walletrpc/psbt.go, lnrpc/walletrpc/walletkit_server.go, lntest/mock/walletcontroller.go, lnwallet/btcwallet/btcwallet.go, lnwallet/btcwallet/signer.go, lnwallet/chanfunding/assembler.go, lnwallet/chanfunding/wallet_assembler.go, lnwallet/interface.go, lnwallet/mock.go, lnwallet/rpcwallet/rpcwallet.go, lnwallet/wallet.go, rpcserver.go, sweep/walletsweep.go, sweep/walletsweep_test.go
There's a wrapper built around `btcwallet.LeaseOutput` in `lnwallet`, which additionally calls `ListLeasedOutputs` to fetch the script and value info, which is rarely used and can be replaced with other queries when needed. More importantly this `ListLeasedOutputs` is very slow (detailed in https://github.com/btcsuite/btcwallet/issues/943), so we remove this call.
Once removed, we gained roughly 30s back in this test,
```
make itest icase=sign_psbt/fund_and_sign_psbt backend=bitcoind dbbackend=postgres
```
On this branch
```
--- PASS: TestLightningNetworkDaemon (185.49s)
--- PASS: TestLightningNetworkDaemon/tranche00/74-of-167/bitcoind/sign_psbt (95.03s)
--- PASS: TestLightningNetworkDaemon/tranche00/74-of-167/bitcoind/sign_psbt/fund_and_sign_psbt (88.34s)
```
On master,
```
--- PASS: …
```
=> Improve the performace of `LeaseOutput`

docs/release-notes/release-notes-0.18.3.md, itest/list_on_test.go, itest/lnd_route_blinding_test.go, lnwallet/channel.go
Correctly set the UpdateAddHTLC.BlindingPoint member when reading LogUpdates from disk. This PR also adds a test to cover this case.
=> lnwallet: correctly set UpdateAddHTLC.BlindingPoint on reload from disk

docs/release-notes/release-notes-0.18.3.md, routing/blindedpath/blinded_path.go
Fixes 2 bugs:
1. We don't need to strictly correlate the invoice expiry with the min_cltv_delta value.
2. Moreover we should respect the minHTLC constraint when creating the blinded route and moreover when adding a buffer to the channel policy when we try to blur the real policy values. 
~~Planning to also add the `SendToBlindedPath` feature when when the sending node is the introduction point.~~
=> blindedpath: Minor bug fixes and feature addition.

scripts/itest_part.sh
It's a bit annoying that we need to scroll down or search when trying to see which itest failed, so we remove the `-v` flag used in `make itest-parallel`, but keep it for local dev via `make itest`.
=> Makefile: silence testing log in `make itest-parallel`

docs/release-notes/release-notes-0.18.3.md, scripts/itest_parallel.sh
This PR ensures that when running itests in CI with `nativesql=true`, that option is passed correctly to LND. [Currently](https://github.com/lightningnetwork/lnd/actions/runs/10499052273/job/29085120784#step:6:253), `itest_parallel.sh` doesn't pass the option on to the per-tranche workers.
Note that this will cause the nativesql itests to fail, as there are test failures that have been masked by the fact that the tests aren't actually running with `nativesql=true`. #9022 fixes one, and several others will need to be fixed as well.
See the difference between the itests running on this PR vs. [on `master`](https://github.com/lightningnetwork/lnd/actions/runs/10499052273/job/29085120784#step:6:253).
📝 Please see our [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master …
=> itest: ensure LND gets correct CLI options when itest are parallel

channeldb/error.go, channeldb/graph.go, channeldb/graph_test.go, discovery/ban.go, discovery/ban_test.go, discovery/gossiper.go, discovery/gossiper_test.go, discovery/mock_test.go, discovery/reliable_sender_test.go, discovery/sync_manager.go, discovery/syncer.go, discovery/syncer_test.go, docs/release-notes/release-notes-0.18.3.md, funding/manager_test.go, graph/builder.go, graph/builder_test.go, graph/errors.go, graph/validation_barrier.go, htlcswitch/link_test.go, htlcswitch/mock.go, lnpeer/mock_peer.go, lnpeer/peer.go, server.go
Partially addresses #8889, specifically parts of #4 & #5 here: https://github.com/lightningnetwork/lnd/issues/8889#issuecomment-2289135744
This PR implements banning for invalid channel announcements:
- we will ignore all channel announcements from a peer until it becomes un-banned (after 48 hours).
- non-channel peers will be disconnected when their ban score reaches the ban threshold.
- channel peers won't be disconnected when their ban score reaches the threshold, but we will ignore their announcements. Note that this still allows us to create channels with them since the announcement isn't gossiped between channel peers.
This PR also keeps track of closed channels such that we won't attempt to validate channel announcements for closed channels. 
Future improvements:
- the banning is …
=> discovery: implement banning for invalid channel anns

rpcserver.go, rpcserver_test.go
We need to check if it has a tapsript root first, as if it has a tapscript root, then it's also a taproot channel. By checking if it has a tapscript root first, we'll now display the proper commitment type for RPC responses.
=> rpc: fix ordering of feature bit check in rpcCommitmentType

build/version.go, channeldb/error.go, channeldb/graph.go, channeldb/graph_test.go, discovery/ban.go, discovery/ban_test.go, discovery/gossiper.go, discovery/gossiper_test.go, discovery/mock_test.go, discovery/reliable_sender_test.go, discovery/sync_manager.go, discovery/syncer.go, discovery/syncer_test.go, docs/release-notes/release-notes-0.18.3.md, funding/manager_test.go, graph/builder.go, graph/builder_test.go, graph/errors.go, graph/validation_barrier.go, htlcswitch/link_test.go, htlcswitch/mock.go, lnpeer/mock_peer.go, lnpeer/peer.go, routing/blindedpath/blinded_path.go, server.go
Staging PR for the creation of v0.18.3 rc2. 
This PR includes cherry picks of the following PRs:
* #9002 
* #9026 
* #9011 
We also seek to include:
* https://github.com/lightningnetwork/lnd/pull/9009
PRs on deck for the next rc:
* https://github.com/lightningnetwork/lnd/pull/9022
* Fixes an issue in CI, which uncovered additional issues related to the SQL backend. May require another PR to resolve everything we've found so far. 
Once #9009 has been merged, I'll tack on an extra commit that bumps the version.
=> release: bump version to v0.18.3 rc2

docs/release-notes/release-notes-0.18.3.md, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/test_utils.go
In this PR, we fix an existing bug with the taproot channel type
that can cause force closes if a peer disconnects while attempting to
send the commitment signature.
Before this commit, since the `PartialSig` we send is never committed to
disk, the version read wouldn't contain the musig2 partial sig. We never
write these signatures to disk, as each time we make a new session, we
need to generate fresh nonces to avoid nonce-reuse.
Due to the above interaction, if we went to re-send a signature after a
disconnection, the `CommitSig` message we sent wouldn't actually contain
a `PartialSigWithNonce`, causing a protocol error.
=> lnwallet: ensure we re-sign retransmitted commits for taproot channels 

.golangci.yml, channeldb/invoices.go, docs/release-notes/release-notes-0.18.3.md, go.mod, go.sum, invoices/sql_store.go, itest/lnd_amp_test.go, sqldb/sqlc/amp_invoices.sql.go, sqldb/sqlc/invoices.sql.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/amp_invoices.sql, sqldb/sqlc/queries/invoices.sql
This PR fixes a few inconsistencies between KV and native SQL invoice DB implementations that caused numerous test failures on our CI:
```
--- FAIL: TestLightningNetworkDaemon/tranche05/107-of-168/bitcoind/sendpayment_amp_invoice_repeat (19.61s)
lnd_amp_test.go:300: 
Error Trace:	/home/runner/work/lnd/lnd/itest/lnd_amp_test.go:300
/home/runner/work/lnd/lnd/lntest/harness.go:386
/home/runner/work/lnd/lnd/itest/lnd_test.go:139
Error:      	Not equal: 
expected: 1
actual  : 2
Test:       	TestLightningNetworkDaemon/tranche05/107-of-168/bitcoind/sendpayment_amp_invoice_repeat
```
```
--- FAIL: TestLightningNetworkDaemon/tranche02/47-of-169/bitcoind/list_payments (24.16s)
--- FAIL: TestLightningNetworkDaemon/tranche02/47-of-169/bitcoind/list_payments/invoice_exact_end_date (0.00s) …
```
=> invoices+sqldb: small fixes to address some inconsistencies between KV and native SQL invoice DB implementations

internal/musig2v040/musig2_test.go
=> bug: fix json tag

go.mod, go.sum
Updates `go.mod` after merging https://github.com/lightningnetwork/lnd/pull/9050 and pushing a new tag.
=> mod: bump sqldb to latest version

.golangci.yml, build/version.go, channeldb/invoices.go, docs/release-notes/release-notes-0.18.3.md, go.mod, go.sum, invoices/sql_store.go, itest/lnd_amp_test.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/test_utils.go, sqldb/sqlc/amp_invoices.sql.go, sqldb/sqlc/invoices.sql.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/amp_invoices.sql, sqldb/sqlc/queries/invoices.sql
This is a staging PR for v0.18.3 rc3. 
Includes:
* #9046 
Will include: 
* https://github.com/lightningnetwork/lnd/pull/9050
Leaving it in draft until the scope is complete.
=> release: create branch for v0.18.3 rc3

Makefile
Just realized #9028 doesn't show the debug log if running through `make itest icase=xxx`.
=> Makefile: add `-test.v` for `make itest`

routing/probability_bimodal_test.go
`probabilityFormula` is expected to return an error if capacity is 0, so we should exclude that case from fuzzing.
Previously it was attempted to avoid this case by seeding the corpus with an input that had capacity 1. That is not an effective solution since the fuzzer can still generate an input with capacity 0.
=> routing: skip fuzzing when capacity is 0

cmd/commands/cmd_walletunlocker.go, docs/release-notes/release-notes-0.19.0.md
Update interactive input in create command description. Fixes #8897.
Run lnd and bitcoin backend, check the create command help text description by the command "lncli create --help".
- [Y] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [Y] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [Y] Any new logging statements use an appropriate subsystem and logging level.
- [Y] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [Y] [There is a change description in the release …
=> commands: update interactive input in create command description

discovery/syncer.go, lnwire/reply_channel_range.go
Currently if an incorrect number of timestamps is given, we fail later on in the GossipSyncer. It makes more sense to fail right away, since we already do that for incorrect SCID formats (e.g., unsorted or duplicate SCIDs). There is already a matching check in Encode for incorrect number of timestamps, so adding this check to Decode makes things symmetric.
@dergoegge found this by running the existing `FuzzReplyChannelRange` fuzz target.
Input:
```
go test fuzz v1
[]byte("00000000000000000000000000000000000000000\x00\x00\x01\t\x0000000000")
```
Trace:
```
--- FAIL: FuzzReplyChannelRange (0.15s)
--- FAIL: FuzzReplyChannelRange (0.00s)
fuzz_test.go:488:
Error Trace:    /workdir/lnd/lnwire/fuzz_test.go:47
/workdir/lnd/lnwire/fuzz_test.go:488
/usr/local/go/src/reflect/value.go:596 …
```
=> lnwire: detect invalid timestamp field

lnwire/fuzz_test.go
We can't use `require.Equal` because it considers nil slices and empty slices to be not equal.
The `Timestamps` field was introduced last year, and the fuzz test was never updated.
@dergoegge found this recently by running the existing `FuzzReplyChannelRange` fuzz target.
Input:
```
go test fuzz v1
[]byte("00000000000000000000000000000000000000000\x00\x00\x01\x01\x00")
```
Trace:
```
--- FAIL: FuzzReplyChannelRange (3.43s)
--- FAIL: FuzzReplyChannelRange (0.00s)
fuzz_test.go:488:
Error Trace:    /workdir/lnd/lnwire/fuzz_test.go:54
/workdir/lnd/lnwire/fuzz_test.go:488
/usr/local/go/src/reflect/value.go:596
/usr/local/go/src/reflect/value.go:380
/usr/local/go/src/testing/fuzz.go:335
Error:          Not equal:
expected: &lnwire.ReplyChannelRange{ChainHash:chainhash.Hash{0x30, 0x30, 0x30, …
```
=> lnwire: manually compare Timestamps in fuzz test

kvdb/go.mod, kvdb/go.sum
This cleans up `go.sum` a bit. After we land then, then I can update the top level module deps.
=> kvdb: update to latest walletdb version

build/log.go, build/logrotator.go, config.go, docs/release-notes/release-notes-0.19.0.md, go.mod, go.sum, sample-lnd.conf
Similar change to https://github.com/btcsuite/btcd/pull/2238 . Updates the log rotation dependency s.t. we can use ZSTD compression for logs instead of GZIP.
- Run this build outside of itests.
- Generate enough logs to cause log rotation.
- Try to unzip the logs with any zstd CLI tool. The upstream implementation, https://github.com/facebook/zstd , is packaged for many distributions.
=> log: bump logrotate dep, switch to zstd compressor

docs/grpc/javascript.md
I updated a `gprc.io` resource.
Additionally the article on [javascript protocol buffers](https://developers.google.com/protocol-buffers/docs/reference/javascript-generated) is no longer available. I believe [this article](https://protobuf.dev/protobuf-javascript/) replaces it and that Google has moved the protobuf documentation to another domain.
=> Update links in javascript.md

docs/grpc/c#.md
This pull request changes an outdated link as it causes issue [#670](https://github.com/lightninglabs/docs.lightning.engineering/pull/670). The document is mirrored on the Builder's Guide repo
=> Update http to https in c#.md

docs/code_contribution_guidelines.md
There are some links in this document that cause issues for pull request [#670](https://github.com/lightninglabs/docs.lightning.engineering/pull/670) in the Builder's Guide Repo.
=> Fix links to resolve issue in Builder's Guide (https and redirect)

lnwallet/channel.go
Fixes a panic caused by sending regular payments over a custom channel, in which case the `htlc.CustomRecords` map would be uninitialized.
=> lnwallet: fix panic on aux sig handling

routing/bandwidth.go
This field is needed in order for a more detailed payment bandwidth check to be performed.
=> routing: add htlcAmt to PaymentBandwidth method of TlvTrafficShaper

build/version.go
As is customary when preparing for the next major (or minor) release, we bump the version to .99 to allow us to set the minimum required version to something like v0.18.4-beta in lndclient and it would still accept the master branch (even if that target version hasn't been released/tagged yet).
See https://github.com/lightningnetwork/lnd/pull/8513 or https://github.com/lightningnetwork/lnd/pull/7574.
=> build: bump master to version v0.18.99-beta

fn/list.go, fn/list_test.go
This commit adds an immutable Filter method to the linked List API. This is useful because there are several instances wherein we iterate through the linked List and only process a subset of it in some way or another.
This adds a library method to capture the most common case we have where we iterate over the linked List structure.
make unit
=> fn: add Filter to List

channeldb/db.go, channeldb/log.go, channeldb/migration/lnwire21/custom_records.go, channeldb/migration/lnwire21/onion_error.go, channeldb/migration32/codec.go, channeldb/migration32/hop.go, channeldb/migration32/log.go, channeldb/migration32/migration.go, channeldb/migration32/migration_test.go, channeldb/migration32/mission_control_store.go, channeldb/migration32/route.go, docs/release-notes/release-notes-0.19.0.md, routing/missioncontrol.go, routing/missioncontrol_store.go, routing/missioncontrol_store_test.go, routing/result_interpretation.go, routing/result_interpretation_test.go
Before this commit, Mission Control would serialise the entire route.Route for each mission control entry. However, MC only uses a fraction of the info in route.Route. Continuing to persist the entire encoding may become more constly once we start sending to more blinded routes because then this encoding will also include the encrypted cipher text sent to each hop on the blinded path.
So this commit migrates the MC store to only persist the data that the MC actually uses.
=> routing+channeldb: use a more minimal encoding for MC routes

channeldb/db.go, channeldb/log.go, channeldb/migration33/log.go, channeldb/migration33/migration.go, channeldb/migration33/migration_test.go, docs/release-notes/release-notes-0.19.0.md, routing/integrated_routing_context_test.go, routing/missioncontrol.go, routing/missioncontrol_state.go, routing/missioncontrol_store.go, routing/missioncontrol_store_test.go, routing/missioncontrol_test.go, routing/mock_test.go, routing/payment_session.go, routing/payment_session_source.go, routing/router.go, routing/router_test.go, rpcserver.go, server.go
This PR:
- migrates the Mission control store so that all existing entries are moved to a new "default" namespace sub-bucket. 
- The MissionControlManager now handles returning mission control instances based on namespace. 
With this PR we still only use the default namespace, but this is a starting point for starting to make use of other namespaces. A follow up could add functionality to combine the results of 2 or more on-disk namespaces into one in-memory. 
Required for https://github.com/lightningnetwork/lnd/issues/8991 where we will want to report MC results in a different (non payment related) namespace. 
Addresses part of https://github.com/lightningnetwork/lnd/issues/7812
Addresses part of https://github.com/lightningnetwork/lnd/issues/8849
Depends on …
=> routing: Namespaced Mission Control

kvdb/postgres/db.go, kvdb/sqlbase/db.go, kvdb/sqlbase/readwrite_tx.go
In this commit, we remove the global application level lock from the postgres backend. This lock prevents multiple write transactions from happening at the same time, and will also block a writer if a read is on going. Since this lock was added, we know always open DB connections with the strongest level of concurrency control available: `LevelSerializable`. In concert with the new auto retry logic, we ensure that if db transactions conflict (writing the same key/row in this case), then the tx is retried automatically.
Removing this lock should increase perf for the postgres backend, as now concurrent write transactions can proceed, being serialized as needed. Rather then trying to handle concurrency at the application level, we'll set postgres do its job, with the application only …
=> kvdb/postgres: remove global application level lock

channeldb/migration_01_to_11/migration_11_invoices_test.go, go.mod, go.sum, invoices/test_utils.go, invoices/test_utils_test.go, keychain/btcwallet.go, keychain/signer.go, lnrpc/invoicesrpc/addinvoice.go, lnrpc/walletrpc/walletkit_server.go, lntest/mock/secretkeyring.go, zpay32/invoice_test.go
Makes sure LND is compatible with the newest bitcoind 28 release.
Fixes: https://github.com/lightningnetwork/lnd/issues/9053
=> multi: bump btcd version.

channeldb/migration/lnwire21/onion_error.go
Fix the signature of the Encode method so that it does in fact 
implement the Serializable interface defined in the lnwire21 
package. This differs slightly from the interface defined in the 
main lnwire package.
The issue was introduced in [this](https://github.com/lightningnetwork/lnd/pull/8911/commits/33ab4b9db95719d2e0d2803dc54e028d7a6805a1) commit which copied over the FailInvalidBlinding type over from lnwire to lnwire21. The issue was that the Serializable interface in lnwire differs slightly from the Serializable interface in lnwire21. 
No change log since this fixes a migration that is only in master.  
Fixes https://github.com/lightningnetwork/lnd/issues/9160
=> channeldb/mig/lnwire21: fix FailInvalidBlinding Encode sig

fn/slice.go, fn/slice_test.go
This adds a handful of useful fundamental slice projections. It is motivated by [this discussion](https://github.com/lightningnetwork/lnd/pull/9097#discussion_r1761797734). I'm not attached to the names but they are not arbitrary:
[uncons](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-List.html#v:uncons), [unsnoc](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-List.html#v:unsnoc), [head](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-List.html#v:head), [tail](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-List.html#v:tail), [init](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-List.html#v:init), [last](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-List.html#v:last)
make unit pkg=fn
📝 Please see our …
=> [MICRO]: fn: add uncons, unsnoc and its component projections

docs/musig2.md
This document contained a link to a MuSig2 draft BIP, which is no longer available. I have updated the link with the link to BIP327 in the bitcoin/bips repository.
=> Update link in musig2.md

fn/goroutine_manager.go, fn/goroutine_manager_test.go
The package provides type `GoroutineManager` which is used to launch goroutines until context expires or the manager is stopped. Stop method blocks until all started goroutines stop.
Original code by Andras https://go.dev/play/p/HhRpE-K2lA0
Adjustments and tests by Boris.
I also added another unrelated `fn` fix to this PR: `fn: generalize type of t in UnwrapOrFail`.
CI runs unit test. Also I used GoroutineManager in https://github.com/lightningnetwork/lnd/pull/9140
=> fn: add goroutine manager 

docs/release-notes/release-notes-0.19.0.md, feature/deps.go, feature/deps_test.go, rpcserver.go
Adds a new `SetBit` helper function in the features package which sets the 
given feature bit on the given feature bit vector along with any of its 
dependencies. If the bit is required, then all the dependencies are also set to
required, otherwise, the optional dependency bits are set. Existing bits are only
upgraded from optional to required but never downgraded from required to
optional.
This new helper is then used for setting the Bolt11 blinded path bit on an invoice 
containing a blinded path. This results in the feature required variant of the route blinding 
feature bit being set in the invoice. 
Related to the discussion from #9121
=> feature+rpcserver: add SetBit helper to set dependent bits 

log.go
Adding the logger of the rpc bitcoin connection via the subsystem name `RPCC`
=> lnd: add logger for rpcclient

docs/release-notes/release-notes-0.19.0.md, lnrpc/walletrpc/walletkit_server.go
Small bug-fix for the new `bumpforceclose` api.
=> error out when non-anchor channels are tried to bump the force close fee.

lnrpc/walletrpc/walletkit.proto, lnrpc/walletrpc/walletkit.swagger.json, lnrpc/walletrpc/walletkit_grpc.pb.go
Fixes the tag for `wallet pendingsweeps` and adds the tag for `wallet estimatefeerate`.
fixes #9156 
I think no change log required. But CI should run for rpc check.
=> lnrpc: fix lncli documentation tags in walletkit.proto

cmd/commands/cmd_macaroon.go, cmd/commands/cmd_walletunlocker.go, docs/macaroons.md, docs/release-notes/release-notes-0.19.0.md, macaroons/bake.go, macaroons/bake_test.go
This PR adds a new `--mac_root_key` flag to the `lncli create` and `lncli createwatchonly` commands that allow the deterministic initialization of the macaroon root key store.
That allows macaroons to be baked (with a new `--root_key` flag of the `lncli bakemacaroon` command) before a node is even started.
This will be especially useful in combination with the new reverse remote signer setup in https://github.com/lightningnetwork/lnd/pull/8754.
=> cmd: allow deterministic macaroon derivation with `lncli`

cmd/commands/commands.go, cmd/commands/commands_test.go, rpcserver.go
Fixes an error that occurred in `lncli listchannels` for non-custom channels.
=> rpcserver+lncli: fix custom channel data encoding issue

.gitignore, contractcourt/chain_watcher_test.go, htlcswitch/interceptable_switch.go, htlcswitch/link.go, htlcswitch/link_isolated_test.go, htlcswitch/link_test.go, htlcswitch/mailbox.go, htlcswitch/mailbox_test.go, htlcswitch/switch.go, htlcswitch/test_utils.go, lnwallet/aux_signer.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/mock.go, lnwallet/sigpool.go, lnwallet/test_utils.go, lnwallet/transactions_test.go
Addresses https://github.com/lightninglabs/taproot-assets/issues/1114 . Improves the safety of cancel channel usage, as the cancel signal can now be sent by `tapd` as well as `lnd`.
Unclear; not sure exactly which events led to the original user issue that caused the stack trace from https://github.com/lightninglabs/taproot-assets/issues/1114 .
=> lnwallet: aux signer batching fixes

docs/release-notes/release-notes-0.19.0.md, lnd.go
**Fixes** https://github.com/lightningnetwork/lnd/issues/9109
Before this PR, lnd could become unresponsive to shutdown signals during the `IsSynced` check, which can sometimes take a long time to complete. This caused delays in shutting down lnd.
I'm pushing this as a draft PR for now, as there are several possible solutions to consider:
1. **Cancelable context**: The cleanest approach might be to pass a cancelable context into the `IsSynced` function, allowing it to exit immediately when a shutdown signal is received. However, this would require updates to both the `btcwallet` and `btcd` repositories, and we would need to wait for new releases with these changes. There are also two `activeChainControl.ChainIO.GetBestBlock()` calls in `lnd.go`—just before and after this PR’s …
=> lnd: allow shutdown signal during `IsSynced` check

fn/context_guard.go
This adds the ContextGuard struct from the taproot-assets repository that has been in use there for a while.
The context guard allows for easy creation of contexts that depend on a central wait group and quit channel.
A context can either be created with a timeout and quit, meaning it will cancel either on reaching the timeout or when the central quit channel is closed.
Or a context can be created to block and use a timeout, meaning it will _not_ cancel on quit but rather block the shutdown until it is completed (or times out).
The third way is to create a context that just cancels on quit with no timeout.
Usage example: https://github.com/lightninglabs/taproot-assets/blob/7a6ee2ebaf26f0bed1041a4e4ea163f4371853c7/tapfreighter/chain_porter.go#L166
=> fn: add ContextGuard from tapd repo

peer/brontide.go
Previously, LND log used to have such records:
```
[WRN] PEER: Peer(...): Link=%!v(MISSING) is not active
```
Now the short channel ID is printed there instead of "%!v(MISSING)".
I got this message when opened a channel from a node using neutrino. I had to restart the node multiple times until the channel become active and I got this message after the first restart.
Also I found this message in the log of another node running with full bitcoin node.
=> peer: fix logging (missing argument) [skip ci]

.gitignore, contractcourt/chain_watcher_test.go, funding/manager_test.go, go.mod, go.sum, htlcswitch/interceptable_switch.go, htlcswitch/link.go, htlcswitch/link_isolated_test.go, htlcswitch/link_test.go, htlcswitch/mailbox.go, htlcswitch/mailbox_test.go, htlcswitch/switch.go, htlcswitch/test_utils.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/mock.go, lnwallet/test_utils.go, lnwallet/transactions_test.go, peer/test_utils.go
Depends on https://github.com/lightningnetwork/lnd/pull/9196.
This is a rebased (and slightly changed) version of https://github.com/lightningnetwork/lnd/pull/9074 that was already reviewed and merged into the `0-19-staging` branch.
The main difference to the staging branch version is that we use a `fn.ContextGuard` instead of a bare context in the link.
cc @jharveyb
=> [custom channels]: Aux signer batching fixes

config.go, docs/debugging_lnd.md, docs/release-notes/release-notes-0.19.0.md, invoices/modification_interceptor.go, lncfg/error.go, lncfg/pprof.go, lnd.go, rpcserver.go, sample-lnd.conf
1. Update the logging description of LND (also include a small code change which returns all the logging levels of the subsystems when the logger is updated)
2. Describe LND's internal profiler so that people can easily provide profile dumps when needed.
3. Also create its own config for the profiler to make it more clean.
4. Add proper logging to the HTLCModifier.
=> Detail LND's debug procedures.

Makefile, scripts/release.sh
This commit updates `scripts/release.sh` to include a check for the correct Go version before executing the release build. This ensures that the release binaries are built with the specified Go version, maintaining consistency and integrity for developer signatures.
=> makefile+scripts: add Go version check to release command

watchtower/lookout/lookout.go, watchtower/wtclient/backup_task.go, watchtower/wtclient/backup_task_internal_test.go
=> Fix comments regarding breach hint and key calculations

itest/lnd_payment_test.go, lntest/harness.go
Peel off some commits from #9227, fix the case,
```
--- FAIL: TestLightningNetworkDaemon/tranche01/46-of-191/bitcoind/payment_failure_reason_canceled (20.86s)
harness.go:2113:
Error Trace:	/home/runner/work/lnd/lnd/lntest/harness.go:2113
/home/runner/work/lnd/lnd/itest/lnd_payment_test.go:1183
/home/runner/work/lnd/lnd/itest/lnd_payment_test.go:1138
/home/runner/work/lnd/lnd/lntest/harness.go:396
/home/runner/work/lnd/lnd/itest/lnd_test.go:139
Error:      	err from HTLC interceptor stream
Test:       	TestLightningNetworkDaemon/tranche01/46-of-191/bitcoind/payment_failure_reason_canceled
Messages:   	received err from HTLC interceptor stream: rpc error: code = Unknown desc = interceptor already exists
```
=> itest: fix flake in `payment_failure_reason_canceled`

lnwallet/chanfunding/coin_select.go, lnwallet/chanfunding/coin_select_test.go
I was confused about this error msg, so I suggest this rewording.
=> chanfunding: improve sanityCheckFee error message for clarity

fn/option.go
Fix `Option` doc comment and add `MaybeSome` function for pointer conversion.
=> Improve Option documentation and add MaybeSome function

chainntnfs/btcdnotify/btcd.go
Fix a race case found [here](https://github.com/lightningnetwork/lnd/actions/runs/11575782146/job/32223203058?pr=8893),
```
Write at 0x00c000340110 by goroutine 11:
github.com/lightningnetwork/lnd/chainntnfs/btcdnotify.New()
/home/runner/work/lnd/lnd/chainntnfs/btcdnotify/btcd.go:135 +0xa2d
github.com/lightningnetwork/lnd/chainntnfs/test.TestInterfaces.func3()
/home/runner/work/lnd/lnd/chainntnfs/test/test_interface.go:1954 +0x70
github.com/lightningnetwork/lnd/chainntnfs/test.TestInterfaces()
/home/runner/work/lnd/lnd/chainntnfs/test/test_interface.go:2021 +0x[161](https://github.com/lightningnetwork/lnd/actions/runs/11575782146/job/32223203058?pr=8893#step:8:162)c
github.com/lightningnetwork/lnd/chainntnfs/test/btcd_test.TestInterfaces() …
```
=> chainntnfs/btcdnotify: remove redundant config params re-assignment

itest/lnd_coop_close_external_delivery_test.go, lnwallet/interface.go
Customize the itest with the type of external delivery address. Test with P2TR address type in addition to P2WKPH.
```
make itest icase='coop close with external delivery'
```
=> lnwallet: fix closechannel for P2TR external addr

docs/release-notes/release-notes-0.19.0.md, watchtower/lookout/lookout.go, watchtower/lookout/lookout_test.go, watchtower/standalone.go
Fixes #8205 , This change sets the total retry attempt count for fetching blocks to 4 (1 original attempt + 3 Retries).
I'm uncertain about how reviewers might naturally replicate a scenario in which the backend fails to deliver blocks to lnd. For testing purposes, I introduced a probabilistic failure in the GetBlock function (by returning a non-nil error). Below is the code snippet I used to implement this probabilistic error injection. For the purposes of testing, I have used bitcoind as backend.
```
type MyCustomError struct {
Msg string
}
func (e MyCustomError) Error() string {
return fmt.Sprintf("Error: %s", e.Msg)
}
func (b *BtcWallet) GetBlock(blockHash *chainhash.Hash) (*wire.MsgBlock, error) {
rand.Seed(time.Now().UnixNano())
randomNumber := rand.Intn(100) + 1
_, ok := …
```
=> watchtower: Add retry logic for fetching blocks

htlcswitch/link.go, htlcswitch/link_test.go, htlcswitch/switch_test.go, htlcswitch/test_utils.go
As seen from [this](https://github.com/lightningnetwork/lnd/actions/runs/11516841464/job/32060311070?pr=8893) and other builds,
```
--- FAIL: TestChannelLinkCancelFullCommitment (81.47s)
link_test.go:935: invoice still open
FAIL
```
=> htlcswitch: fix flake in `TestChannelLinkCancelFullCommitment`

channeldb/migration/lnwire21/msat.go, channeldb/migration/lnwire21/true_boolean.go, channeldb/migration32/migration_test.go, channeldb/migration32/mission_control_store.go, channeldb/migration32/route.go, docs/release-notes/release-notes-0.19.0.md, lnwire/channel_update_2.go, routing/missioncontrol.go, routing/missioncontrol_store.go, routing/missioncontrol_store_test.go, routing/result_interpretation.go, routing/result_interpretation_test.go, routing/route/route.go
In this commit, we update an existing migration which at the time of
writing has not been included in a release. We update it so that it
converts the format used for MissionControl result encoding to use pure
TLV instead. The 3 structs that have been updated are: `mcHop`,
`mcRoute` and `paymentResult`.
=> routing+migration32: update migration 32 to use pure TLV encoding for mission control results

fn/either.go, fn/either_test.go, fn/fn.go, fn/list_test.go, fn/option.go, fn/option_test.go, fn/result.go, fn/result_test.go, fn/slice.go, fn/slice_test.go
We add `fn` equivalents of the following Haskell functions:
- [`sequenceA`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Prelude.html#v:sequenceA) renamed to `Collect`, both the Option and Result variants
- [`traverse`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Prelude.html#v:traverse), both Option and Result variants
- [`mapMaybe`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Maybe.html#v:mapMaybe), renamed to FilterMap
- [`catMaybes`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Maybe.html#v:catMaybes), renamed to TrimNones
- [`note`](https://hackage.haskell.org/package/errors-2.3.0/docs/Control-Error-Util.html#v:note)
- [`hush`](https://hackage.haskell.org/package/errors-2.3.0/docs/Control-Error-Util.html#v:hush)
These are additions …
=> fn: more fn goodies

contractcourt/briefcase.go, contractcourt/briefcase_test.go, contractcourt/chain_watcher.go, contractcourt/channel_arbitrator.go, contractcourt/channel_arbitrator_test.go, contractcourt/htlc_timeout_resolver.go, docs/release-notes/release-notes-0.19.0.md, htlcswitch/switch.go, itest/lnd_multi-hop_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/7969
=> Cancel back outgoing dust htlcs before commitment is confirmed.

config.go, docs/release-notes/release-notes-0.19.0.md, htlcswitch/link.go, htlcswitch/switch_test.go, itest/lnd_payment_test.go, lntest/harness.go, sample-lnd.conf, scripts/check-sample-lnd-conf.sh
Introduced a more clear config value and deprecated the old `dust-threshold` value. The new setting is called `channel-max-fee-exposure`. Nothing has changed code wise, the new value behaves as the old one but is way clearer and removes the ambiguity
=> Deprecate dust-threshold config value

docs/release-notes/release-notes-0.19.0.md, htlcswitch/interceptable_switch.go, lnrpc/routerrpc/router.pb.go, lnrpc/routerrpc/router.proto, lnrpc/routerrpc/router.swagger.json
Update forward interceptor `MODIFY` to consistently merge custom records supplied by the interceptor with those already in LND (previously it would overwrite if set and merge if empty).
Note that this change does not provide the ability to clear any custom records (only overwrite them). If a use cases emerges for the ability to delete records, the API can be extended accordingly. 
See #9166 for further discussion.
=> htlcswitch: merge htlc custom records on modify

itest/lnd_channel_backup_test.go, itest/lnd_channel_policy_test.go, itest/lnd_coop_close_with_htlcs_test.go, itest/lnd_forward_interceptor_test.go, itest/lnd_funding_test.go, itest/lnd_hold_persistence_test.go, itest/lnd_invoice_acceptor_test.go, itest/lnd_misc_test.go, itest/lnd_mpp_test.go, itest/lnd_multi-hop-error-propagation_test.go, itest/lnd_multi-hop_test.go, itest/lnd_open_channel_test.go, itest/lnd_payment_test.go, itest/lnd_psbt_test.go, itest/lnd_res_handoff_test.go, itest/lnd_revocation_test.go, itest/lnd_route_blinding_test.go, itest/lnd_routing_test.go, itest/lnd_rpc_middleware_interceptor_test.go, itest/lnd_switch_test.go, itest/lnd_wallet_import_test.go, itest/lnd_watchtower_test.go, itest/lnd_wipe_fwdpkgs_test.go, itest/lnd_zero_conf_test.go, lntest/harness.go, lntest/harness_assertion.go, lntest/harness_node_manager.go, lntest/node/config.go, lntest/node/harness_node.go
Cherry-picked commits from the final `blockbeat` to reduce the PR size.
This PR makes a few trivial changes to fix the flakes found in the blockbeat itest.
=> trivial: prepare itest for `blockbeat`

lnwire/fuzz_test.go
Add fuzz targets for:
- 3 new gossip 1.75 messages
- 1 new route blinding message
- Schnorr signature conversions
- the `Fee` TLV
=> lnwire: add new fuzz targets

docs/release-notes/release-notes-0.19.0.md, lnrpc/marshall_utils.go
Fixes https://github.com/lightningnetwork/lnd/issues/9268
This PR intends to fix the handling of a negative fee limit in the `SendPayment_V2` rpc.
=> routerrpc: fix sendpayment_v2 negative fee limit

sweep/fee_bumper.go, sweep/fee_bumper_test.go, sweep/fee_function.go, sweep/mock_test.go, sweep/sweeper.go, sweep/sweeper_test.go, sweep/tx_input_set.go
NOTE: itest is fixed in the final PR #9227.
Depends on
- #8892
- #9237
- #9221
This PR prepares the incoming blockbeat PRs, the changes are,
- `BlockEpoch` now has the block data instead of the block header. This block data is used in the incoming blockbeat PR to query spending transactions.
- Added a new sweeping state, `TxError`. Inputs resulting in this state will be removed from the sweeper.
- check input's CSV and CLTV in the sweeper, and skip sweeping them if not matured.
- When calculating the deadline, make sure it's derived from mature height, not current height.
=> Beat [1/4]: handle sweeper's broadcast error

lntest/node/harness_node.go
In this commit, we start to print the PID of node's we created within an itest. This is useful when debugging itests with `dlv` by attaching to a given node. By printing out the PID, we facilitate such debugging attempts.
Example run: 
```
harness_node.go:403: Starting node (name=Alice) with PID=72474
```
=> lntest: print node PID when launching in itests

docs/release-notes/release-notes-0.19.0.md, peer/brontide.go, server.go
Cherry-picked commits from the final `blockbeat` to reduce the PR size.
This commit fixes a case where the peer blocks the shutdown process. During the shutdown, the server will call `s.DisconnectPeer`, which calls `peer.Disconnect`. Because the peer never enters `peer.Start` via `s.peerInitializer`, the `startReady` chan will not be closed, causing `peer.Disconnect` to hang forever. We now fix it by only block on `startReady` when the peer is started.
=> peer+lnd: fix peer blocking on node shutdown

config.go, lntest/harness_assertion.go, lntest/node/state.go
1) The `Node1Policy` and `Node2Policy` members of the `lnrpc.ChannelEdge` struct can be nil 
and so we should check for this before dereferencing.  ran into panics [here](https://github.com/lightningnetwork/lnd/actions/runs/11898396588/job/33154809901)
2) remove default values for some deprecated log config options
=> misc: nil checks and remove deprecated default values

sweep/fee_bumper.go, sweep/fee_bumper_test.go
In this commit, we complete a recently added feature by ensuring that even if we go through the RBF loop to create a txn, that we still populate the `outpointToIndex` map. Unit tests have been updated to ensure this is always set as expected.
=> sweep: update storeRecord to include utxo index

watchtower/wtwire/fuzz_test.go
A pure refactor to reduce code duplication and fluff, similar to https://github.com/lightningnetwork/lnd/pull/9263.
=> wtwire: simply fuzz targets

config.go, itest/config.go, itest/list_on_test.go
Previously, "lnd --debuglevel show" complained that bitcoin backend is not configured:
```
$ lnd --debuglevel show
failed to load config: ValidateConfig: either --bitcoin.mainnet, or bitcoin.testnet,bitcoin.simnet, bitcoin.regtest or bitcoin.signet must be specified
```
The command above is documented in [LND documentation](https://github.com/lightningnetwork/lnd/blob/bd36f765304f736391b752199aa9281b2e2ca5a7/docs/debugging_lnd.md#L38) and is expected to work without additional arguments.
To make it working, the user had to specify `--bitcoin.mainnet` and configure one of the backends, e.g. `--bitcoin.node neutrino`.
With this fix, the command works without any additional flags:
```
$ lnd --debuglevel show
Supported subsystems [ARPC ATPL BLPT BRAR BTCN BTWL CHAC CHBU CHCL CHDB CHFD CHFT …
```
=> config: fix "lnd --debuglevel show" command

watchtower/wtdb/version.go
Needed when migrating kv data from bolt db to kv sql here:
https://github.com/lightninglabs/lndinit/pull/21
=> wtdb: export versions of wtclient.db

protofsm/daemon_events.go, protofsm/log.go, protofsm/msg_mapper.go, protofsm/state_machine.go, protofsm/state_machine_test.go
In this PR, we create a new package, `protofsm` which is intended to
abstract away from something we've done dozens of time in the daemon:
create a new event-drive protocol FSM. One example of this is the co-op
close state machine, and also the channel state machine itself.
This packages picks out the common themes of:
* clear states and transitions between them
* calling out to special daemon adapters for I/O such as transaction
broadcast or sending a message to a peer
* cleaning up after state machine execution
* notifying relevant callers of updates to the state machine
The goal of this PR, is that devs can now implement a state machine
based off of this primary interface:
```go
// State defines an abstract state along, namely its state transition function
// that takes as input an …
```
=> [1/4] - protofsm: add new package for driving generic protocol FSMs 

chainntnfs/bitcoindnotify/bitcoind.go, chainntnfs/btcdnotify/btcd.go, chainntnfs/interface.go, chainntnfs/neutrinonotify/neutrino.go, chainntnfs/txnotifier.go, docs/release-notes/release-notes-0.19.0.md
Cherry-picked commits from the final `blockbeat` to reduce the PR size.
This PR made two minor changes,
1. we now always notify the txns first before the block, such that when the block arrives the relevant txn notification is also arrived.
2. make sure the conf notification is non-blocking and always sent.
=> chainntnfs: fix missing notifications

contractcourt/chain_arbitrator.go, contractcourt/chain_watcher.go, contractcourt/chain_watcher_test.go, contractcourt/channel_arbitrator.go, contractcourt/channel_arbitrator_test.go, docs/release-notes/release-notes-0.19.0.md, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/transactions_test.go, rpcserver.go
This PR does 2 things:
1) Fixes https://github.com/lightningnetwork/lnd/issues/8149, it now starts a chainArb level goroutine which is responsible to stop goroutines of the channel_arbitrators when they are fully resolved. 
2) Now starts the different channel arbitrator during startup in an errorGroup and collects the result concurrently. This makes sure LND starts-up correctly. Sometimes the channelArbs depend on other subsystems like for example taproot assets, so we need to make sure we do not block here forever.
EDIT:
Changed the approach. This will prevent the deadlock from happening. 
A separate PR will be created to start the arbitrator concurrently.
=> fix chanArb deadlock

chanacceptor/rpcacceptor.go, docs/release-notes/release-notes-0.18.4.md
We forgot to add the new commitment type to the channel acceptor. Noticed in https://github.com/lightninglabs/taproot-assets/pull/1132.
=> [custom channels]: add taproot overlay channel type to channel acceptor

server.go
Cherry-picked commits from the final blockbeat to reduce the PR size.
Looks like we forgot to call the `graphBuilder.Stop` during the shutdown process - since we start the `graphBuilder` after the `chainArb`, we stop it before `chainArb`.
=> lnd: stop `graphBuilder` during shutdown

lnwallet/channel.go, lnwallet/channel_test.go
Cherry-picked commits from the final blockbeat to reduce the PR size.
This PR makes sure we log the amounts in the same unit so it's easier to debug.
Before,
```
2024-11-20 06:30:24.312 [ERR] LNWL prefix_log.go:69: ChannelPoint(882a35d69a86c6c9dd753b94086c899df5ec42b15d2e2038e7bf4fcd3ae6ebdb:0): Cannot pay for the CommitmentFee of the ChannelState: ourBalance is negative after applying the fee: ourBalance=3850000, commitFee=0.00013350 BTC, feeBuffer=31000000 mSAT (type=feebuffer) local_chan_initiator
```
After,
```
2024-11-20 12:55:14.386 [ERR] LNWL prefix_log.go:69: ChannelPoint([ChanPoint: Alice=>dave]): Cannot pay for the CommitmentFee of the ChannelState: ourBalance is negative after applying the fee: ourBalance=3850000 mSAT, commitFee=13350000 mSAT, feeBuffer=31000000 mSAT …
```
=> lnwallet: log the amounts in the same unit

input/input.go, input/mocks.go, sweep/walletsweep.go, watchtower/wtwire/message.go
fix some function names in interface comment
=> multi: fix some function names in interface comment

protofsm/state_machine_test.go
In this commit, we fix an existing race in the new `protofsm` state machine executor tests.
The race would appear as such:
```
--- FAIL: TestStateMachineMsgMapper (0.00s)
state_machine_test.go:165:
Error Trace:/home/runner/work/lnd/lnd/protofsm/state_machine_test.go:165
/home/runner/work/lnd/lnd/protofsm/state_machine_test.go:451
Error:      Object expected to be of type *protofsm.dummyStateStart, but was *protofsm.dummyStateFin
Test:       TestStateMachineMsgMapper
FAIL
FAILgithub.com/lightningnetwork/lnd/protofsm0.116s
FAIL
```
This race condition was triggered as before we would start the state machine _then_ register for notifications. In `Start` we emit the starting event, then enter the main loop. If that event gets emitted before our subscription, then we'll miss the event, as the …
=> protofsm: fix race in state machine executor tests

docs/grpc/python.md, docs/grpc/ruby.md
Updated docs for python and ruby. Removed ``` grpcio googleapis-common-protos mypy-protobuf ``` and ``` google api ``` refernce  from python file.Also removed --mypy_out=. from line 38 and 56.
Removed references of googleapis from ruby docs.
**FIXES #9285** 
=> Update docs/grpc/python.md and ruby.md

cmd/commands/cmd_payments.go, docs/release-notes/release-notes-0.19.0.md
`lncli estimateroutefee --pay_req=...` would error in `router_backend.go` with
```
[lncli] rpc error: code = Unknown desc = timeout_seconds must be specified
```
because the cmd default param, which is `60s`, wasn't properly passed on.
=> cmd: fix default timeout for estimateroutefee

.github/workflows/main.yml, .github/workflows/release.yaml, .golangci.yml, Dockerfile, dev.Dockerfile, docker/btcd/Dockerfile, docs/INSTALL.md, go.mod, lnrpc/Dockerfile, make/builder.Dockerfile
As discovered in https://github.com/lightningnetwork/lnd/discussions/9327, the `docs/INSTALL.md` referenced an old version of Go that needs to be used.
=> docker+docs: update documentation around Golang minimum version

chainreg/chainregistry.go, docs/release-notes/release-notes-0.19.0.md
If feeurl is not provided and LND is running in bitcoind or btcd mode, use fee estimator provided by bitcoind or btcd instead of using static fee estimator (which always returns 50 sats/vbyte).
This enables simulating high feerate environment in regtest and simnet not only via feeurl, but also by filling mempool with high feerate transactions, which is closer to what happens in mainnet.
Also skip creating bitcoind or btcd fee estimator, if feeurl is provided. Before LND logged both "Initializing bitcoind backed fee estimator" and "Using external fee estimator" if running in bitcoind mode with feeurl provided, but actually feeurl was used, so this is not a change of behavior.
- Setup regtest/simnet network with LND, e.g. [in docker](https://github.com/lightningnetwork/lnd/blob/master/docker …
=> chainreg: use feerate estimator in regtest and simnet

discovery/gossiper.go, invoices/sql_store.go, lnwire/typed_fee.go
Looks like there are a few more occurrences of `lll` which need to be fixed.
=> multi: rename `lll` to `ll` and remove unused `nolint`

docs/code_contribution_guidelines.md
The documents didn't specify clearly which commit message should contain the command string to skip a workflow run.
This PR should not trigger a workflow run since it contains the command string `[skip ci]` in the HEAD commit.
So the PR is a test in itself.
=> clarify skipping the CI checks in the docs

contractcourt/channel_arbitrator.go, contractcourt/channel_arbitrator_test.go, docs/release-notes/release-notes-0.18.4.md
Replaces #9262
Fixes: https://github.com/lightningnetwork/lnd/issues/9323
=> Don't block on channel arbitator startup

config_builder.go, htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/link_test.go, htlcswitch/mock.go, htlcswitch/switch.go, peer/brontide.go, routing/bandwidth.go, routing/bandwidth_test.go, routing/mock_test.go, routing/payment_lifecycle.go, routing/payment_lifecycle_test.go, routing/payment_session_source.go, routing/router.go, routing/router_test.go, server.go
Renames and moves the `TlvTrafficShaper => AuxTrafficManager` and prepares it to be used for forwarding bandwidth checks as well.
=> [custom channels]: refactor AuxTrafficManager to be used for forwarding as well

docs/release-notes/release-notes-0.19.0.md, lnrpc/invoicesrpc/utils.go
Cherry-picked from #9260, we need this to have deterministic results from the RPC response.
=> lnrpc: sort `Invoice.HTLCs` based on `HtlcIndex`

fn/func.go
Copied the methods which are already used in the tapassets repo.
https://github.com/lightninglabs/taproot-assets/blob/fde673202d0d5dbb63c7e38058801753bb6355a7/fn/func.go#L114-L153
came up during implementation of: https://github.com/lightningnetwork/lnd/pull/9316
=> Add a deep copy generic harness to the internal fn package

docs/release-notes/release-notes-0.18.4.md, docs/release-notes/release-notes-0.19.0.md, input/script_utils.go, routing/blinding.go, routing/blinding_test.go, routing/pathfind.go, routing/pathfind_test.go, routing/result_interpretation.go, routing/result_interpretation_test.go
Because we hot swap the target public key when sending to a
blinded path we need to penalize all nodes after the introduction
point. 
Approach changed, see comment below.
~~We could also just penalize the first node after the introduction node, however that would mean we would do a bit of more pathfinding work and only fail after considering the rest of the blinded path. I think it is not super critical to have this bit more data persistent in memory.~~
=> routing: fix mc blinded path behaviour.

lnwallet/chancloser/chancloser.go, lnwallet/chancloser/chancloser_test.go, lnwallet/chancloser/interface.go, lnwallet/chancloser/mock.go, lnwallet/chancloser/rbf_coop_msg_mapper.go, lnwallet/chancloser/rbf_coop_states.go, lnwallet/chancloser/rbf_coop_test.go, lnwallet/chancloser/rbf_coop_transitions.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/close_test.go, lnwallet/commitment.go, lnwire/closing_complete.go, lnwire/lnwire_test.go, peer/brontide.go, protofsm/state_machine.go, protofsm/state_machine_test.go
In this PR, we add a new RBF based co-op channel close state machine. This uses the new `protofsm` package to define the states and transitions for the state machine. The new state machine is then also updated to become a `peer.MsgEndpoint` which allows us to use the new `peer.MsgRouter` to handle all message dispatch _into_ the state machine. A series of new wrapper structs (taking care to always accept interfaces to decouple from the concrete types) are created to be able to initialize the environment needed by the new state machine. 
This PR doesn't yet include integration within the peer struct. That will come in a follow up PR as we need some additional changes to be able to handle the two possible co-op types that will exist. 
The diff might look somewhat large, but over half of it …
=> [3/4] - lnwallet/chancloser: add new protofsm based RBF chan closer 

build/version.go, config_builder.go, contractcourt/channel_arbitrator.go, contractcourt/channel_arbitrator_test.go, docs/release-notes/release-notes-0.18.4.md, htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/link_test.go, htlcswitch/mock.go, htlcswitch/switch.go, input/script_utils.go, peer/brontide.go, routing/bandwidth.go, routing/bandwidth_test.go, routing/blinding.go, routing/blinding_test.go, routing/mock_test.go, routing/pathfind.go, routing/pathfind_test.go, routing/payment_lifecycle.go, routing/payment_lifecycle_test.go, routing/payment_session_source.go, routing/result_interpretation.go, routing/result_interpretation_test.go, routing/router.go, routing/router_test.go, server.go
Preparation PR to kick off the `v0.18.4-beta.rc2` release.
This PR includes rebased versions of the following PRs (in order):
- #9324
- #9333 
- #9316
=> release: create branch for v0.18.4-beta.rc2

docs/release-notes/release-notes-0.19.0.md, fn/goroutine_manager.go, fn/goroutine_manager_test.go
Updates the GoroutineManager to  avoid having its constructor take 
a context since this is an anti-pattern that I think we should avoid. The GoroutineManagers will 
generally be created within LND subserver constructors and these will not really ever take contexts 
and we want to avoid passing a fresh context to these
this PR was opened in response to reviewing [this](https://github.com/lightningnetwork/lnd/pull/9140) PR
=> fn: Remove ctx from GoroutineManager constructor

.github/workflows/main.yml
Update goveralls tools to support golang module versioning.
The goverall tool had a bug regarding the module versioning of
golang packages see also
https://github.com/mattn/goveralls/pull/222 for more background.
Goveralls is wrapped by another library to make it available for
github actions. So the relevant PR which is referenced here in
LND is:
https://github.com/shogo82148/actions-goveralls/pull/521.
=> github: update goveralls tool

contractcourt/anchor_resolver.go, contractcourt/breach_resolver.go, contractcourt/briefcase_test.go, contractcourt/channel_arbitrator.go, contractcourt/channel_arbitrator_test.go, contractcourt/commit_sweep_resolver.go, contractcourt/commit_sweep_resolver_test.go, contractcourt/contract_resolver.go, contractcourt/htlc_incoming_contest_resolver.go, contractcourt/htlc_incoming_contest_resolver_test.go, contractcourt/htlc_outgoing_contest_resolver.go, contractcourt/htlc_outgoing_contest_resolver_test.go, contractcourt/htlc_success_resolver.go, contractcourt/htlc_success_resolver_test.go, contractcourt/htlc_timeout_resolver.go, contractcourt/htlc_timeout_resolver_test.go, contractcourt/mock_registry_test.go, invoices/invoiceregistry.go
Depends on 
- #8894
NOTE: itest is fixed in the final PR 
- #9260
Turns out mounting `blockbeat` in `ChannelArbitrator` can be quite challenging (unit tests, itest, etc). This PR attempts to implement it in hopefully the least disruptive way - only `chainWatcher` implements `Consumer`, and the contract resolvers are kept stateless (in terms of blocks). The main changes are,
1. contract resolvers are refactored - the original `Resolve` method is broken into two steps: 1) `Launch` the resolver, which handles sending the sweep request, and 2) `Resolve` the resolver, which handles monitoring the spending of the output.
2. `chainWatcher` implements `Consumer` in the following PR.
The original attempt is to make the resolvers subscribe to a blockbeat chan, as implemented in #8717. The second …
=> Beat [3/4]: prepare resolvers to handle the `blockbeat`

chainntnfs/bitcoindnotify/bitcoind_test.go, chainntnfs/test/bitcoind/bitcoind_test.go, chainntnfs/txnotifier_test.go, go.mod, go.sum
Depends on https://github.com/btcsuite/btcd/pull/2277
Fix the following unit test. From a local observation, it looks like a previous node is still shutting down, causing the following test to fail.
```
--- FAIL: TestHistoricalConfDetailsTxIndex (0.00s)
--- FAIL: TestHistoricalConfDetailsTxIndex/rpc_polling_disabled (11.65s)
bitcoind_test.go:143: miner height=430, bitcoind height=0
...
bitcoind_test.go:143: miner height=430, bitcoind height=0
bitcoind_test.go:143: timed out in syncNotifierWithMiner, got err=<nil>, minerHeight=430, bitcoindHeight=0
FAIL
FAIL	github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify	13.323s
FAIL
```
=> chainntnfs: fix `TestHistoricalConfDetailsTxIndex`

fn/context_guard.go, fn/context_guard_test.go, fn/tests.go
In this commit, the ContextGuard struct is re-worked such that the context that its new main `WithCtx` method provides is cancelled in sync with a parent context being cancelled or with it's quit channel being cancelled. Tests are added to assert the behaviour. In order for the close of the quit channel to be consistent with the cancelling of the derived context, the quit channel _must_ be contained internal to the ContextGuard so that callers are only able to close the channel via the exposed Quit method which will then take care to first cancel any derived context that depend on the quit channel before returning.
Furthermore, the main `WithCtx` method, is extended to take a parent context such that any derived context extends the
parent instead of needing to create a fresh one. 
PR …
=> fn: expand the ContextGuard and add tests

chainntnfs/txnotifier.go, chanrestore.go, contractcourt/briefcase.go, contractcourt/chain_arbitrator.go, contractcourt/chain_watcher.go, contractcourt/chain_watcher_test.go, contractcourt/channel_arbitrator.go, docs/release-notes/release-notes-0.19.0.md
This PR implements the `Consumer` interface in `chainWatcher` with necessary refactors.
TODOs
Depends on
- #9276
NOTE: itest is fixed in the final PR
- #9260
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/9277)
=> Beat [4/4]: implement `Consumer` in `chainWatcher`

contractcourt/htlc_incoming_contest_resolver.go
When notifying the invoice registry for an exit hop htlc we also want to
include its custom records. The channelLink, the other caller of this
method, already populates this field. So we make sure the contest
resolver does so too.
=> contractcourt: include custom records on replayed htlc

fn/io.go, fn/io_test.go
Continue work of https://github.com/lightningnetwork/lnd/pull/8305.
A WriteFile function with sync and optional removal on error is added to fn module.
As described in [Use of Golang submodules](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#use-of-golang-submodules), in a second PR the usage of ioutil.WriteFile and os.WriteFile will be replaced with this new function to fix issue https://github.com/lightningnetwork/lnd/issues/6720.
=> fn: add synchronous write file

htlcswitch/packet.go, htlcswitch/switch.go, lnwallet/channel.go, routing/payment_lifecycle.go
This is the final cherry-picking from the blockbeat series PR #9260, which fixes the case on how we handle a closing circuit and a nil pointer dereference in the payment lifecycle:
```
2024-11-07 18:05:26.293 [CRT] CHDB log_shutdown.go:31: Caught unhandled error: ERROR: could not access status of transaction 330367 (SQLSTATE 58P01)
2024-11-07 18:05:26.293 [INF] CHDB log_shutdown.go:32: Sending request for shutdown
2024-11-07 18:05:26.293 [INF] LTND signal.go:181: Received shutdown request.
2024-11-07 18:05:26.293 [INF] LTND signal.go:166: Shutting down...
2024-11-07 18:05:26.293 [INF] LTND signal.go:185: Gracefully shutting down.
2024-11-07 18:05:26.294 [DBG] HSWC payment_result.go:166: Subscribing to result for attemptID=266
panic: runtime error: invalid memory address or nil pointer …
```
=> htlcswitch+routing: handle nil pointer dereference properly

build/version.go, contractcourt/htlc_incoming_contest_resolver.go
Preparation PR to kick off the v0.18.4-beta.rc3 release.
This PR includes rebased versions of the following PRs (in order):
- #9357
=> release: create branch for v0.18.4-beta

contractcourt/channel_arbitrator.go, htlcswitch/interfaces.go, witness_beacon.go
fix some problematic method name in comment
No need
=> chore: fix some problematic method name in comment

brontide/noise_test.go, graph/db/graph.go
=> fix check node1Err !=nil but return a nil value error err

.github/workflows/main.yml
Encountered this error multiple times today, and wanna try this approach mentioned [here](https://github.com/orgs/community/discussions/25678#discussioncomment-5242449).
=> workflows: fix no space left error

.github/workflows/main.yml
the `actions/upload-artifact@v3` is (or it seems might already be) [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). 
As per the [migration notes](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md), the only thing to be aware of is that we need to take care to namespace artifacts correctly so that jobs in the same CI run dont overwrite the artifacts of other jobs with the same name. Luckily though it seems we already namespace all our jobs. So It seems that only the version bump is required :)
=> .github: bump upload-artifact action to v4

docs/debugging_lnd.md, docs/signing_release_candidate.md
=> chore: fix some typos

build/sub_logger.go, chainio/consumer_test.go, chainio/dispatcher_test.go, chainntnfs/bitcoindnotify/bitcoind.go, chainntnfs/btcdnotify/btcd.go, channeldb/revocation_log_test.go, contractcourt/breach_arbitrator.go, contractcourt/htlc_timeout_resolver.go, discovery/gossiper_test.go, docs/code_contribution_guidelines.md, itest/lnd_switch_test.go
Fix some typos in docs and comments.
=> Fix some typos

fn/context_guard.go, fn/context_guard_test.go
Simplifies context cancellation handling by using context.AfterFunc instead of a goroutine to wait for context cancellation. This approach avoids the overhead of a goroutine during the waiting period.
Additional changes:
- added test of blocking context cancelling
- removed unneeded argument `cancel` of ctxBlocking
- clear store of cancel funcs after quitting
- test that the Create method does not launch any goroutines
```
cd fn
go test -race
```
=> fn: optimize context guard

build/version.go, docs/release-notes/release-notes-0.19.0.md, go.mod, go.sum, lnwallet/chancloser/rbf_coop_test.go, protofsm/log.go, protofsm/state_machine.go, protofsm/state_machine_test.go
This PR touches the protofsm package for 2 reasons:
1) update to use the latest GoroutineManager API introduced in: https://github.com/lightningnetwork/lnd/pull/9341
2) Update the StateMachine to thread a context through and to take a context via its API methods where it makes sense. With this update, logging can also be switched to the new structured logging pattern which allows us to avoid having to specify the `FSM(%V)` string for each log line
Depends on: https://github.com/btcsuite/btclog/pull/20
=> protofsm: update GR Manager usage and start using structured logging

go.mod, go.sum, htlcswitch/link.go, htlcswitch/link_test.go, htlcswitch/test_utils.go, protofsm/state_machine.go, protofsm/state_machine_test.go
This commit updates the fn dep to the version containing the updates to the ContextGuard implementation. Only the htlcswitch/link uses the guard at the moment so this is updated to make use of the new implementation.
Depends on https://github.com/lightningnetwork/lnd/pull/9342 (so only look at the last commit)
=> htlcswitch+go.mod: use updated fn.ContextGuard

lnrpc/autopilotrpc/autopilot_server.go, lnrpc/chainrpc/chain_server.go, lnrpc/devrpc/dev_server.go, lnrpc/neutrinorpc/neutrino_server.go, lnrpc/peersrpc/peers_server.go, lnrpc/routerrpc/router_server.go, lnrpc/signrpc/signer_server.go, lnrpc/watchtowerrpc/handler.go
chore: change 'register' to 'registered' in lnrpc starting debug logs [skip ci]
=> chore: change 'register' to 'registered' in lnrpc starting debug logs [skip ci]

chainntnfs/test/test_interface.go
From this [build](https://github.com/lightningnetwork/lnd/actions/runs/12412837954/job/34653467259), I suspect the block didn't include the tx so added a check to make sure it's mined - this may not completely fix the test, but should eliminate this possibility.
=> chainntnfs: fix test `testSingleConfirmationNotification`

contractcourt/taproot_briefcase_test.go
In this commit, we add a rapid derived fuzz test for the HtlcAuxBlob test. This uses the rapid (randomized property testing) into Go's built in fuzzer. This wrapper will use the fuzz stream, and pass that into rapid where the stream is used to make structured test inputs which are tested against the existing properties.
This can be done more widely in the codebase, we pick a simple example to port first before tackling others.
=> contractcourt: add rapid derived fuzz test for HtlcAuxBlob

contractcourt/htlc_timeout_resolver.go, docs/release-notes/release-notes-0.19.0.md, itest/lnd_sweep_test.go
Now since we are abandoning forwards early for dust htlcs, we can decrease this value.
=> The sweeper subsystem uses now also the configured budget values for HTLCs

routing/localchans/manager.go
Cherry-Picked from https://github.com/lightningnetwork/lnd/pull/8777.
=> bugfix createmissingedge

docs/release-notes/release-notes-0.19.0.md, itest/lnd_amp_test.go, itest/lnd_channel_balance_test.go, itest/lnd_channel_force_close_test.go, itest/lnd_channel_policy_test.go, itest/lnd_coop_close_with_htlcs_test.go, itest/lnd_hold_invoice_force_test.go, itest/lnd_hold_persistence_test.go, itest/lnd_htlc_timeout_resolver_test.go, itest/lnd_max_htlcs_test.go, itest/lnd_misc_test.go, itest/lnd_mpp_test.go, itest/lnd_multi-hop-error-propagation_test.go, itest/lnd_multi-hop_force_close_test.go, itest/lnd_open_channel_test.go, itest/lnd_payment_test.go, itest/lnd_quiescence_test.go, itest/lnd_route_blinding_test.go, itest/lnd_routing_test.go, itest/lnd_single_hop_invoice_test.go, itest/lnd_sweep_test.go, itest/lnd_trackpayments_test.go, itest/lnd_watchtower_test.go, lnrpc/routerrpc/router.pb.go, lnrpc/routerrpc/router.proto, lnrpc/routerrpc/router.swagger.json, lnrpc/routerrpc/router_backend.go, lnrpc/routerrpc/router_server.go
This PR introduces a default value of 60 seconds for the `timeout_seconds` field in the `SendPaymentV2` RPC call in the `routerrpc.SendPaymentRequest`.
Fixes: #9282 
- Make an RPC call to SendPaymentV2 with a valid non-zero value for timeout_seconds.
- Verify that the request behaves as expected and uses the provided value.
- Make an RPC call to SendPaymentV2 without including the timeout_seconds field.
- Verify that the default value of 60 seconds is applied and used during the request.
=> routerrpc: add a default value for timeout_seconds in SendPaymentV2

itest/lnd_sweep_test.go
Fix the following flake found in this [build](https://github.com/lightningnetwork/lnd/actions/runs/12830273599/job/35778121044?pr=9405),
```
--- FAIL: TestLightningNetworkDaemon (891.26s)
harness_setup.go:25: Setting up HarnessTest...
harness_setup.go:38: Prepare the miner and mine blocks to activate segwit...
harness_setup.go:46: Connecting the miner at 127.0.0.1:10023 with the chain backend...
--- FAIL: TestLightningNetworkDaemon/tranche00/12-of-269/bitcoind/sweep_htlcs (176.54s)
harness_node.go:403: Starting node (name=Alice) with PID=21999
harness_node.go:403: Starting node (name=Bob) with PID=22733
harness_node.go:403: Starting node (name=Carol) with PID=23043
harness_assertion.go:1363: 
Error Trace:	/home/runner/work/lnd/lnd/lntest/harness_assertion.go:1363 …
```
=> itest: fix flake in `testSweepHTLCs`

discovery/gossiper.go, discovery/sync_manager.go, discovery/sync_manager_test.go, discovery/syncer.go, docs/release-notes/release-notes-0.19.0.md, graph/builder.go, graph/db/graph.go, graph/db/graph_cache.go, graph/db/models/channel_edge_policy.go, routing/unified_edges.go
Fixed a long standing issue, which is also sometimes found in our itest,
```
--- FAIL: TestLightningNetworkDaemon/tranche09/156-of-269/bitcoind/receiver_blinded_error (57.25s)
harness_node.go:403: Starting node (name=Alice) with PID=14745
harness_node.go:403: Starting node (name=Bob) with PID=14777
harness_node.go:403: Starting node (name=Carol) with PID=14805
harness_node.go:403: Starting node (name=Dave) with PID=14878
harness_assertion.go:1879: 
Error Trace:	/home/runner/work/lnd/lnd/lntest/harness_assertion.go:1879
/home/runner/work/lnd/lnd/lntest/harness_assertion.go:1937
/home/runner/work/lnd/lnd/lntest/harness.go:2353
/home/runner/work/lnd/lnd/lntest/harness.go:2219
/home/runner/work/lnd/lnd/itest/lnd_route_blinding_test.go:373 …
```
=> multi: fix inconsistent state in gossip syncer

chanbackup/backupfile.go, chanbackup/backupfile_test.go, config.go, docs/release-notes/release-notes-0.19.0.md, sample-lnd.conf, server.go
Closes #8906 
From the [feature description](https://github.com/lightningnetwork/lnd/issues/8906):
> To ensure that certain classes of recovery are always possible, we should considering adding a mode to never delete channel backups, and only rename or move them to a special folder that stores archived channels. They're relatively small (~300 bytes or so), so it shouldn't take up a significant amount of disk space.
This PR allows for the archiving of channel backups, enabling users to choose whether to permanently delete previous backup files or archive them by moving them to a designated archives folder.
**Problem**:
LND currently overwrites old channel backup files when creating new ones. This means:
- If a user accidentally deletes a channel backup file, the backup is irretrievably …
=> chanbackup: archive old channel backup files

discovery/gossiper.go, discovery/validation_barrier.go, discovery/validation_barrier_test.go, docs/release-notes/release-notes-0.19.0.md, graph/builder.go, graph/errors.go, graph/validation_barrier.go, graph/validation_barrier_test.go
This PR changes the `ValidationBarrier` to track abstract job dependencies. This just means that every time a child job comes in (i.e. channel update or node announcement), we track the set of possible parent jobs that are related to it (channel announcement(s)) that have registered via `InitJobDependencies`.  The goroutines containing the child jobs will then wait to be notified every time one of their parent jobs completes. From the child job's POV, this just works as ref-counting except that you're only counting the parent jobs you're interested in.  
With this, we can now extend the `ValidationBarrier` to track any sort of abstract job that requires both concurrency and waiting for another job to finish. It also makes it possible in a future PR to very easily make node announcements …
=> discovery+graph: track job set dependencies in vb

lnrpc/routerrpc/router_server.go, lntest/harness_assertion.go
=> misc: fix incorrect inclusion of nil err in various formatted strings

itest/list_exclude_test.go, itest/list_on_test.go, itest/lnd_channel_force_close_test.go, itest/lnd_onchain_test.go
Cherry-picked from the sweeper PR.
When mining lots of blocks in the itest, the subsystems can be out of
sync in terms of the best block height. We now assert the num of pending
sweeps on Alice's node to give her more time to sync the blocks,
essentially behaving like a `time.Sleep` as in reality, the blocks would
never be generated this fast.
=> itest: fix flake in `testAnchorThirdPartySpend`

.github/workflows/main.yml, .github/workflows/release.yaml, .golangci.yml, Dockerfile, Makefile, dev.Dockerfile, docker/btcd/Dockerfile, docs/release-notes/release-notes-0.19.0.md, lnrpc/Dockerfile, lnrpc/gen_protos_docker.sh, make/builder.Dockerfile, tools/Dockerfile
With every minor release of Go some security issues are fixed. So updating regularly makes sense.
=> Update to Go 1.22.11

channeldb/invoices.go, docs/release-notes/release-notes-0.18.5.md, invoices/interface.go, invoices/invoiceregistry.go, invoices/invoiceregistry_test.go, invoices/sql_store.go, invoices/update_invoice.go
This PR makes sure that HTLCs in the accepted state will be canceled back if the invoice expires.
However as soon as a sub AMP invoice is settled we do not allow expiring the invoice anyways so canceling the invoice call will fail because we have a check for HTLC which are in the settled state and will return an error, never closing the invoice. This has the positive side-effect that all HTLCs in the accepted state will be cancelled via the `invoiceEventLoop`. However we should definitly fix this behaviour for AMP invoices and also close them, hence not accepting any new payment to it.
=> invoices: amp invoices bugfix.

channeldb/invoice_test.go, channeldb/invoices.go, config_builder.go, docs/release-notes/release-notes-0.19.0.md, itest/lnd_invoice_migration_test.go
This commit introduces the functionality to set a tombstone key in the invoice bucket after the migration to the native SQL database. The tombstone prevents the user from switching back to the KV invoice database, ensuring data consistency and avoiding potential issues like lingering invoices or partial state in KV tables. The tombstone is checked on startup to block any manual overrides that attempt to revert the migration.
Fixes https://github.com/lightningnetwork/lnd/issues/9434
=> channeldb+lnd: set invoice bucket tombstone after migration

go.mod, go.sum
Removes the now obsolete replace rule from `go.mod` in favor of the tagged `sqldb`.
=> build: use the tagged 1.0.7 version of sqldb

lntest/node/harness_node.go
Found a flake from this [build](https://github.com/lightningnetwork/lnd/actions/runs/13156723364/job/36715442041?pr=9446), the root cause is unknown, and we now add a timestamp to the console logs so it's easier to debug next time.
```
--- FAIL: TestLightningNetworkDaemon (631.00s)
harness_setup.go:25: Setting up HarnessTest...
harness_setup.go:38: Prepare the miner and mine blocks to activate segwit...
harness_setup.go:46: Connecting the miner at 127.0.0.1:10014 with the chain backend...
--- FAIL: TestLightningNetworkDaemon/tranche04/152-of-267/bitcoind/send_to_route_error_propagation (133.32s)
harness_node.go:403: Starting node (name=Alice) with PID=16073
harness_node.go:403: Starting node (name=Bob) with PID=16172
harness_node.go:403: Starting node (name=Carol) with PID=16257 …
```
=> lntest: log timestamp when printing errors

discovery/gossiper.go, docs/release-notes/release-notes-0.19.0.md, graph/db/addr.go, graph/db/graph_test.go, graph/db/models/node.go, lnwire/lnwire_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/9473
In https://github.com/lightningnetwork/lnd/pull/6435, we started to correctly handle the serialisation/deserialisation of unknown addresses in node announcement wire messages but we were still not persisting these node announcements correctly. 
In this PR, the bug is first demonstrated and then fixed by properly handing the `OpaqueAddrs` case when persisting the `models.LightningNode` type.
=> graph/db: correctly handle de(ser)ialisation of `models.LightningNode` opaque addresses

itest/lnd_forward_interceptor_test.go
Fix the flake found in this [build](https://github.com/lightningnetwork/lnd/actions/runs/13201855874/job/36855929097?pr=9477), and many other builds,
```
--- FAIL: TestLightningNetworkDaemon (115.68s)
harness_setup.go:25: Setting up HarnessTest...
harness_setup.go:38: Prepare the miner and mine blocks to activate segwit...
harness_setup.go:46: Connecting the miner at 127.0.0.1:10045 with the chain backend...
--- FAIL: TestLightningNetworkDaemon/tranche06/110-of-267/btcd/forward_interceptor_restart (29.50s)
harness_node.go:403: Starting node (name=Alice) with PID=5473
harness_node.go:403: Starting node (name=Bob) with PID=5507
harness_node.go:403: Starting node (name=Carol) with PID=5537
harness_node.go:403: Starting node (name=Dave) with PID=5570
harness_node.go:403: Starting node …
```
=> itest: fix flake in `testForwardInterceptorRestart`

discovery/gossiper.go, discovery/gossiper_test.go, docs/release-notes/release-notes-0.19.0.md, graph/builder.go, graph/builder_test.go, graph/errors.go, lnmock/chain.go
Part of https://github.com/lightningnetwork/lnd/issues/9475
This PR does some refactoring along with test preparation:
1) First, in preparation for moving the funding tx validation code from the graph.Builder to the gossiper, we convert some of the `graph.ErrorCode`s to just normal error variables. We do this for any error that is constructed during tx validation. This will make the commit which moves the actual validation code easier to review since then these errors will just be moved as is to to the `discovery` package. 
2) The rest of the commits are just about preparing the discovery package tests to test funding transaction validation later on. We pretty much duplicate how blocks/utxos are mocked and added from the `graph/notifications_test.go` file. None of this code is used yet. …
=> discovery+graph: various preparations for moving funding tx validation to the gossiper

graph/builder_test.go, graph/notifications_test.go
Observed in: https://github.com/lightningnetwork/lnd/actions/runs/13236175981/job/36941432766?pr=9491
We mock the ChainView with a buffered channel of 10 so there is the chance that no block is arrived and then we start our bestheight from the starting height, so we need to make sure the starting height is initialized.
=> fix graphbuilder flake

channeldb/mp_payment.go, channeldb/mp_payment_test.go, channeldb/payment_control_test.go, channeldb/payments_test.go, docs/release-notes/release-notes-0.19.0.md, itest/lnd_multi-hop_force_close_test.go, lntest/harness_assertion.go, routing/control_tower_test.go, routing/payment_lifecycle.go, routing/payment_lifecycle_test.go, routing/router.go, routing/router_test.go
Fix #8975 
This PR aims at fixing [a scenario](https://github.com/lightningnetwork/lnd/issues/8975#issuecomment-2270528222) where the payment could be stuck. Major changes are,
- all the db updates for a given payment now happens in a single goroutine (`resumePayment`)
- minor optimization on sphinx circuit creation - the error decryptor is now conditionally created when needed, i.e., when processing an `update_fail_htlc`.
TODOs
=> routing+htlcswitch: fix stuck inflight payments

docs/release-notes/release-notes-0.19.0.md, graph/db/graph.go, graph/db/graph_cache.go, graph/db/graph_cache_test.go, graph/db/graph_test.go
Today, each time the `GraphCache`s `AddNode` method is called, the DB is consulted and the node's 
known channels are iterated over and re-added to the cache. While this design made sense at the time
that the cache was added, it no longer is required with the updates to the architecture that have taken
place since. 
This change is part of https://github.com/lightningnetwork/lnd/issues/9494 as this removal of `AddNode` 
means that we no longer need to pass a `kvdb.RTx` to the `graphCache` methods and so it will be
easier to move the cache out of the CRUD layer in an upcoming PR. 
The AddNode method on the GraphCache calls `AddNodeFeatures` underneath
and then iterates through all the node's persisted channels and adds
them to the cache too via `AddChannel`.
This is, however, not required …
=> graph: remove redundant iteration through a node's persisted channels

.github/workflows/main.yml
Sometimes only the "Send coverage" step of a CI job will fail. This commit turns this step into a "best effort" step instead so that it does not block a CI job from passing.
It can, for example, often happen that a single job is re-run from the GH UI, it then passes but the "Send coverage" step fails due to the "Can't add a job to a build that is already closed." error meaning that the only way to get the CI step to pass is to re-push and retrigger a full CI run. (example: https://github.com/lightningnetwork/lnd/actions/runs/13257033750/job/37078871135?pr=9496)
=> .github: ignore Send coverage errors

discovery/gossiper.go, discovery/gossiper_test.go, docs/release-notes/release-notes-0.19.0.md, graph/builder.go, graph/builder_test.go, graph/db/models/channel_edge_info.go, graph/errors.go, graph/interfaces.go, graph/notifications_test.go, server.go
Depends on: 
- https://github.com/lightningnetwork/lnd/pull/9476
- https://github.com/lightningnetwork/lnd/pull/9477
Fixes https://github.com/lightningnetwork/lnd/issues/9475
```
This commit is a pure refactor. We move the transaction validation
(existence, spentness, correctness) from the `graph.Builder` to the
gossiper since this is where all protocol level checks should happen.
All tests involved are also updated/moved.
```
=> discovery+graph:  move funding tx validation to the gossiper

.github/workflows/main.yml
Looks like we have one more place to skip the coverage error, from this [build](https://github.com/lightningnetwork/lnd/actions/runs/13308276856/job/37167235848?pr=9447).
=> workflows: skip coverage error in job `finish`

cmd/commands/cmd_payments.go, cmd/commands/commands.go
In https://github.com/lightningnetwork/lnd/pull/9390, we added the SCID and the ChannelID to the output of the LNCLI, but for some cmds it makes things not really practical so for some cmds we do not replace the content with addtional data.
=> For some lncli cmds we should not replace the content with other data

graph/builder.go
We want to ensure that when a caller cancels a topology subscription, then any channel/node updates after that are not notified on the subscription. To ensure this, we make the Cancel function blocking.
In https://github.com/lightningnetwork/lnd/pull/9476, we removed announcement update handling (`case update := <-b.networkUpdates:`) from the main `networkHander` loop since the handling of any updates was immediately spun off into a goroutine anyways. 
However, this did serve some purpose because it ensured that if we did the following: 
1) cancel our subscription 
2) immediately send an update
then `case ntfnUpdate := <-b.ntfnClientUpdates:` would be hit first ensuring that the `<-b.networkUpdates` case could not be triggered. Then by the time the update is handled, when it went to …
=> graph: ensure topology subscriber handling and network msg handling is synchronous

lnrpc/walletrpc/walletkit.pb.go, lnrpc/walletrpc/walletkit.proto, lnrpc/walletrpc/walletkit.swagger.json
Changed description of option Immediate of https://pkg.go.dev/github.com/lightningnetwork/lnd@v0.18.5-beta/lnrpc/walletrpc#BumpFeeRequest
It waits for the next block and sends CPFP even if there are no other inputs to form a batch.
=> walletrpc: fix description of bumpfee.immediate

graph/builder.go, graph/db/graph.go, graph/interfaces.go
This commit restricts the graph CRUD interface such that one can only add a proof to a channel announcement and not update any other fields. This pattern is better suited for SQL land too.
This also fixes a bug where we were not doing a nil check on the `edges` bucket but instead on passed `edge` object.
=> graph: Restrict interface to update channel proof instead of entire channel

contractcourt/anchor_resolver.go, docs/release-notes/release-notes-0.19.0.md, itest/list_on_test.go, itest/lnd_channel_force_close_test.go, itest/lnd_sweep_test.go, sweep/fee_bumper.go, sweep/fee_bumper_test.go, sweep/mock_test.go, sweep/store.go, sweep/store_test.go, sweep/sweeper.go, sweep/sweeper_test.go
We now properly handle `missing inputs` error from either mempool acceptance check or publish transaction. 
Depends on,
- #9446 
- #9447 
- #9445
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/9448)
=> sweep: properly handle failed sweeping txns

htlcswitch/link.go, lnwallet/channel.go
Based on a user report that a debug output was printed several times because we were calling `l.Bandwidth` more than necessary.
=> multi: fix debug log

chainntnfs/mempool.go, contractcourt/anchor_resolver.go, docs/release-notes/release-notes-0.19.0.md, itest/list_on_test.go, itest/lnd_channel_force_close_test.go, itest/lnd_sweep_test.go, sweep/fee_bumper.go, sweep/fee_bumper_test.go, sweep/mock_test.go, sweep/store.go, sweep/store_test.go, sweep/sweeper.go, sweep/sweeper_test.go
There are two places tracking the spending status of a given input - one in the sweeper, the other in the fee bumper. We now move the tracking to be handled in the fee bumper so we always have a single source of truth. By the end of this fix, we should see that,
- the fee func will be kept on the original line when retrying sweeps.
- both the sweeper and the fee bumper can recover their state from a restart.
- for the neutrino backend, the initial sweeping tx is now always RBF-compliant.
The fix is made of two PRs to keep the size small - the first PR will enable tracking the spending status of inputs in the fee bumper, and the second will fix the rest.
Depends on,
- #9446
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> sweep: start tracking input spending status in the fee bumper

.github/actions/setup-go/action.yml
Turns out that actions/setup-go starting with @v4 also adds caching. With that, our cache size on disk has almost doubled, leading to the GitHub runner running out of space in certain situation. We fix that by disabling the automated caching since we already have our own, custom-tailored version.
=> GitHub: remove duplicate caching

graph/builder.go
The exposed `AddNode`, `AddEdge` and `UpdateEdge` methods of the Builder are currently synchronous since even though they pass messages to the network handler which spins off the handling in a goroutine, the public methods still wait for a response from the handling before returning. The only part that is actually done asynchronously is the topology notifications.
We previously tried to simplify things in [this
commit](https://github.com/lightningnetwork/lnd/pull/9476/commits/d757b3bcfc77b0fbb543ef5db800e6c6b058930f) but we soon realised that there was a reason for sending the messages to the central/synchronous network handler first: it was to ensure consistency for topology clients: ie, the ordering between when there is a new topology client or if it is cancelled needs to be consistent …
=> graph: refactor Builder network message handling

docs/release-notes/release-notes-0.19.0.md, lnrpc/routerrpc/router_server.go, lnrpc/routerrpc/router_server_test.go
This PR attempts to fix https://github.com/lightningnetwork/lnd/issues/9431, an edge case in `EstimateRouteFee`.
We want to send a probe in case a route hint contains a public edge.
=> routerrpc: fix estimateroutefee for public route hints

Makefile, make/release_flags.mk, make/testing_flags.mk
Fixes https://github.com/lightningnetwork/lnd/issues/6489.
Allows me to build with a different Golang version than is currently in `$PATH`:
```
make install GOCC=/usr/lib/go-1.21.9/bin/go GOROOT=/usr/lib/go-1.21.9
```
Depending on the setup, the `GOROOT=...` argument also needs to be specified to avoid an error like `compile: version "go1.21.0" does not match go tool version "go1.21.9"`.
=> Makefile: add GOCC variable

lnutils/fs.go, lnutils/fs_test.go
This is a follow-up PR addressing suggestions from this [comment](https://github.com/lightningnetwork/lnd/pull/9232#discussion_r1916665505). It adds the `createDir` function, which could potentially be used [here](https://github.com/lightningnetwork/lnd/blob/bac699df8f406824a4fb8a95140dc4e97d8bcd43/config.go#L904C2-L923C3) and [here](https://github.com/lightningnetwork/lnd/blob/bac699df8f406824a4fb8a95140dc4e97d8bcd43/chanbackup/backupfile.go#L216C1-L220C3). This is a common pattern repeated.
```bash
cd lnutils
go test -run TestCreateDir
```
=> lnutils: add CreateDir util function

autopilot/prefattach_test.go, config_builder.go, docs/release-notes/release-notes-0.19.0.md, graph/db/graph.go, graph/db/graph_test.go, graph/db/kv_store.go, graph/db/options.go, graph/notifications_test.go, peer/test_utils.go, routing/pathfind_test.go
** Part 2 **
In this PR, we first rename the existing KV store functional option type to be more context specific so that we 
free up the more general `Options` name for the new `ChannelGraph`. 
Then, we let the ChannelGraph init the KVStore using its config options. 
Finally, we let the ChannelGraph be responsible for the init of the graphCache. For now, both structs hold a pointer to the
graphCache. But the end of the series, the KVStore will no longer have a pointer to the graphCache
=> graph: extract cache from CRUD [2] 

docs/release-notes/release-notes-0.19.0.md, graph/db/graph.go, graph/db/graph_test.go, graph/db/kv_store.go
** PR 3 **
In this PR we move all the very basic cache read/write calls out from `KVStore` and into `ChannelGraph`.
By "basic" here, I just mean that no other refactoring needs to happen for these moves.
=> graph: extract cache from CRUD [3] 

Makefile, chainntnfs/bitcoindnotify/bitcoind_test.go, chainntnfs/test/test_interface.go, docs/release-notes/release-notes-0.19.0.md, lntest/unittest/backend.go, lnwallet/test/test_interface.go, routing/chainview/interface_test.go, scripts/unit-test-flake-hunter.sh
Fix a long standing flake found in our unit test,
```
--- FAIL: TestHistoricalConfDetailsTxIndex (0.00s)
--- FAIL: TestHistoricalConfDetailsTxIndex/rpc_polling_disabled (11.66s)
bitcoind_test.go:143: miner height=430, bitcoind height=0
...
bitcoind_test.go:143: miner height=430, bitcoind height=0
bitcoind_test.go:143: timed out in syncNotifierWithMiner, got err=<nil>, minerHeight=430, bitcoindHeight=0
FAIL
FAIL	github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify	13.353s
FAIL
```
It turns out the peer connection between the `bitcoind` node and the `btcd` node (miner) is broken, causing the chain backend to never be synced. This unexpected behavior only happens when the test runs multiple times (ranging from 50-ish to 200-ish). To reproduce, remove the second-to-last commit and run, …
=> Fix unit test flake `TestHistoricalConfDetailsTxIndex`

docs/release-notes/release-notes-0.19.0.md, graph/db/graph.go, graph/db/kv_store.go
** PR 4 ** (note: not dependent on PR 3)
In this PR, we move the cache writes for `DeleteChannelEdges`, `DisconnectBlockAtHeight, `PruneGraph`
and `PruneGraphNodes` from the KVStore to the ChannelGraph. These each need a bit of refactoring of some
helper methods first, so this PR does this refactoring too.
=> graph: extract cache from CRUD [4] 

docs/release-notes/release-notes-0.19.0.md, graph/db/graph.go, graph/db/graph_test.go, graph/db/kv_store.go
** PR 5 ** (note: not dependent on PR 3 or 4)
In this PR, we move the cache writes for `MarkEdgeZombie` and `UpdateEdgePolicy`  from the KVStore to the ChannelGraph. For the MarkEdgeZombie change, we first need to adjust `FilterKnownChanIDs` so that its zombie related business logic is moved out of the CRUD code and into the ChannelGraph layer - so this is done as a first commit here. Note that this part replaces [this](https://github.com/lightningnetwork/lnd/pull/9522) PR which made this move to the ChanSeries layer - but it makes more sense to keep this out of that layer.
=> graph: extract cache from CRUD [5] 

channeldb/channel.go, channeldb/migration32/mission_control_store.go, contractcourt/htlc_timeout_resolver.go, lnrpc/invoicesrpc/addinvoice_test.go, lnrpc/routerrpc/router_server_deprecated.go, routing/missioncontrol_store.go
use a more straightforward return value
=> refactor: use a more straightforward return value

autopilot/prefattach_test.go, docs/release-notes/release-notes-0.19.0.md, graph/db/graph.go, graph/db/graph_test.go, graph/db/kv_store.go, graph/notifications_test.go, peer/test_utils.go, routing/pathfind_test.go, server.go
** Final PR in the cache-RIP series **
In this PR, the extraction of the `graphCache` from the CRUD layer (`KVStore`) into the `ChannelGraph` layer is completed. 
The opportunity is also taken to move the graphCache population logic out of the constructor of the ChannelGraph and into
a new `Start` method instead.
=> graph: extract cache from CRUD [6]

itest/lnd_experimental_endorsement.go, itest/lnd_forward_interceptor_test.go, itest/lnd_hold_persistence_test.go, itest/lnd_htlc_timeout_resolver_test.go, itest/lnd_mpp_test.go, itest/lnd_multi-hop_force_close_test.go, itest/lnd_payment_test.go, itest/lnd_route_blinding_test.go, lntest/harness_assertion.go
So this can be used in other tests when we only care about the payment hash.
=> lntest+itest: change the method signature of `AssertPaymentStatus`

channeldb/channel.go, contractcourt/chain_watcher.go, feature/default_sets.go, htlcswitch/interfaces.go, htlcswitch/switch.go, input/fuzz_script_is_op_return_test.go, input/script_utils.go, lnwallet/chancloser/rbf_coop_msg_mapper.go, lnwallet/chancloser/rbf_coop_states.go, lnwallet/chancloser/rbf_coop_test.go, lnwallet/channel.go, lnwire/features.go, log.go, peer/brontide.go, peer/brontide_test.go, peer/chan_observer.go, peer/daemon_adapters.go, peer/test_utils.go, protofsm/msg_mapper.go, protofsm/state_machine.go, protofsm/state_machine_test.go, rpcserver.go, server.go
This PR contains a set of preliminary changes towards integrating the RBF close state machine. 
Spun off from: https://github.com/lightningnetwork/lnd/pull/8453
**NOTE**: the merge target here is a side feature branch: `rbf-staging`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/9559)
=> multi: preliminary changes towards integrating the new RBF close protocol feature

.github/pull_request_template.md, docs/code_contribution_guidelines.md
We've seen an unnaturally high number of typo fixes coming in lately.
Not sure if a new "typo analyzing LLM" is at work or a new competition that pays people tokens for contributions to popular repositories.
But the amount of work required to deal with those PRs outweighs the benefit in the eyes of the maintainers.
Also, GitHub added a security feature that prevents first-time contributors from running the CI. Distinguishing between honest users that just want to contribute from automated bots that open hundreds of PRs to multiple repositories in a short amount of time to get around those security measures is a non-trivial task.
Some examples, all within the couple of days (some of them even trying to fix the same typos in exactly the same commit structure, further hinting at bots at …
=> GitHub+docs: no longer accept typo fixes to fight PR spam

docs/release-notes/release-notes-0.19.0.md, itest/lnd_channel_policy_test.go
Channel Updates have a natural rate limit of 1 update per second due to the fact that the timestamp carried in the update is only accurate to the second. So we need to ensure that the next update we send in the burst is at least 1 second after the last one.
This flake was appearing in the `update channel policy` itest in the part of the tests where we are testing
the burst rate limit logic of Carol. It's flaky at the moment though due to Carol sometimes rejecting a channel update
due to the natural 1-update-per-second rate limit. So we need to ensure that Alice waits at least a second between
sending updates for this logic to be tested properly. The log line that appears after the channel updates are sent too quickly after each there ie:
`builder.go:1331: process network updates got: …
=> itest: make sure to not hit the natural ChannelUpdate rate limit

lnwallet/chancloser/rbf_coop_transitions.go, protofsm/state_machine.go
Fix the missing `ChannelPoint` and redundant string `target` in the logging.
=> lnwallet+protofsm: fix logging

build/config.go, build/config_dev.go, build/config_prod.go
For the `LogConfig` struct, add the `yaml:",inline"` tag to embedded structs.
This is needed for any project that uses the `LogConfig` struct to parse a `yaml` config file (like [aperture](https://github.com/lightninglabs/aperture/pull/148)).
=> build: add yaml tags to some LogConfig fields

lnwallet/chancloser/rbf_coop_states.go, lnwallet/chancloser/rbf_coop_test.go, lnwallet/chancloser/rbf_coop_transitions.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwire/closing_complete.go, lnwire/closing_sig.go, lnwire/lnwire_test.go, protofsm/state_machine.go
Spun off of https://github.com/lightningnetwork/lnd/pull/8453.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightningnetwork/lnd/9568)
=> lnwallet: update RBF state machine w/ latest spec guidelines

autopilot/manager.go, docs/release-notes/release-notes-0.19.0.md, docs/release-notes/release-notes-0.20.0.md, graph/builder.go, graph/db/graph.go, graph/db/graph_test.go, graph/db/notifications.go, graph/notifications_test.go, pilot.go, rpcserver.go, server.go
We plan to later on add an option for a remote graph source which will
be managed from the `ChannelGraph`. In such a set-up, a node would rely on
the remote graph source for graph updates instead of from gossip sync.
In this scenario, however, our topology subscription logic should still
notify clients of all updates and so it makes more sense to have the
logic as part of the `ChannelGraph` so that we can send updates we receive
from the remote graph.
Part of #9494
=> graph: move topology subscription to `ChannelGraph`

docs/release-notes/release-notes-0.19.0.md, lntest/node/watcher.go
Before this commit, it was possible for a request to be sent on the `chanWatchRequests` channel in `WaitForChannelPolicyUpdate` and then for the `ticker.C` case to select _before_ the `eventChan` select gets triggered when the `topologyWatcher` closes the `eventChan` in its call to `handlePolicyUpdateWatchRequest`. This could lead to a "close of a closed channel" panic.
To fix this, this commit ensures that we only move on to the next iteration of the select statement in `WaitForChannelPolicyUpdate` once the request sent on `chanWatchRequests` has been fully handled.
See [this build](https://github.com/lightningnetwork/lnd/actions/runs/13630660920/job/38097538076?pr=9544) for an instance of where this panic was triggered.
=> lntest: wait for ChanUpdate req to be fully processed before sending another

config.go
The `ValidateConfig` method needs to account for the caller already having an initialised build.SubLoggerManager and then should not override it.
This lets any callers of `ValidateConfig` (such as LiT), to initialise the sub logger manager themselves.
=> config: only create a sub-log manager if one doesnt already exist

lntest/harness.go
Nudging test authors towards not mining too many blocks makes sense, especially in lnd where we have a lot of integration tests. But the lntest package is also used in other projects where this restriction might lead to large refactors.
To be able to stage those refactors we also want to allow this limit to be configurable if lntest is used as a library.
=> lntest: make mining block limit configurable

discovery/gossiper.go, discovery/gossiper_test.go, docs/release-notes/release-notes-0.19.0.md
There exists an edge-case where we receive the _same_ ChannelUpdate from 2 different peers 
in quick succession. Both will make it past the initial IsStale check since neither have been 
persisted yet, this means that both updates will count towards the rate limit count for that peer:channel
combo. 
To fix this, we need to re-check the staleness of the update once the lock is acquired. 
This fixes the flake seen in this build: https://github.com/lightningnetwork/lnd/actions/runs/13583650550/job/37973971226
=> discovery: obtain channelMtx before doing any DB calls in `handleChannelUpdate`

docs/release-notes/release-notes-0.19.0.md, funding/manager.go, funding/manager_test.go, itest/list_on_test.go, itest/lnd_open_channel_test.go, lncfg/config.go, lncfg/dev.go, lncfg/dev_integration.go, rpcserver.go, server.go
Fixes: #9511 
This PR introduces a configurable parameter for the constant `MaxWaitNumBlocksFundingConf` used in funding manager. The change allows developers and integration environments to override the default value (2016 blocks) via a build tag, enabling the mining of fewer blocks to trigger timeout scenarios during testing. In production builds, the default value remains unchanged to ensure stability.
- **Configurable Timeout Constant:**
- Added MaxWaitNumBlocksFundingConf to DevConfig so that its value can be modified.
- **Production Safety:**
- Retains the default value of 2016 blocks for production, ensuring no impact on production behavior.
- **Improved Testing Flexibility:**
- Allows tests to simulate timeout conditions more efficiently by reducing the number of blocks that need …
=> Make MaxWaitNumBlocksFundingConf Configurable for itest

tor/controller_test.go
We now make sure the proxy server is running on a unique port. In addition, we close the old conn before making a new conn.
=> tor: fix `TestReconnectSucceed`

go.mod, go.sum
After merging #9581, the flake in the coverage unit test should be gone. All we have to do is update the submodule version to the fixed one (since during unit tests the module is used not the physical directory on disk).
Thanks @yyforyongyu for the actual fix in #9581!
=> mod: bump tor submodule to v1.1.5 to fix flake

contractcourt/commit_sweep_resolver.go, contractcourt/htlc_lease_resolver.go
The optional variadic functional parameters probably got lost during a rebase.
=> contractcourt: fix rebase issue with removed variadic option

chanbackup/backupfile_test.go
To make it easier to debug, we break the old test into smaller ones and fix a flake caused by uncleaned test dir.
Flake found in this [build](https://github.com/lightningnetwork/lnd/actions/runs/13563227666/job/37910474108?pr=9540), which can be reproduced locally via
`make flakehunter-unit pkg=chanbackup case=TestUpdateAndSwap`,
```
Flake hunting unit test.
scripts/unit-test-flake-hunter.sh chanbackup TestUpdateAndSwap
Test TestUpdateAndSwap passed, count: 1
...
Test TestUpdateAndSwap passed, count: 28
Test TestUpdateAndSwap passed, count: 29
Test TestUpdateAndSwap failed. Output:
Running debug unit tests.
GOEXPERIMENT=loopvar go test -v -tags="dev autopilotrpc chainrpc invoicesrpc neutrinorpc peersrpc routerrpc signrpc verrpc walletrpc watchtowerrpc wtclientrpc stdlog trace" …
```
=> chanbackup: fix test flake in `TestUpdateAndSwap`

discovery/syncer.go, discovery/syncer_test.go, docs/release-notes/release-notes-0.19.0.md, itest/lnd_forward_interceptor_test.go, lnrpc/routerrpc/forward_interceptor.go, tor/controller_test.go
Fix the following three flakes,
`TestReconnectSucceed` still fails, from this [build](https://github.com/yyforyongyu/lnd/actions/runs/13733368349/job/38414019489),
```
panic: Log in goroutine after TestReconnectSucceed has completed: 
Error Trace:    /home/runner/go/pkg/mod/github.com/lightningnetwork/lnd/tor@v1.1.5/controller_test.go:357
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/asm_amd64.s:1700
Error:          Received unexpected error:
EOF
Test:           TestReconnectSucceed
```
`forward_interceptor_restart` from this [build](https://github.com/yyforyongyu/lnd/actions/runs/13754484996/job/38459750034)
```
--- FAIL: TestLightningNetworkDaemon/tranche09/165-of-272/bitcoind/forward_interceptor_restart (30.28s)
harness_node.go:403: Starting node (name=Alice) with PID=10529 …
```
=> multi: fix flakes and gossip syncer

docs/release-notes/release-notes-0.19.0.md, htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/mock.go, routing/bandwidth.go, routing/mock_test.go
Avoids overwriting the HTLC amount if the aux bandwidth manager isn't handling the channel.
=> routing: don't set custom amount if manager isn't handling

config_builder.go, docs/release-notes/release-notes-0.19.0.md, lncfg/db.go, sample-lnd.conf
In future releases we will use this flag to make potentially failing kv to native SQL migrations optional. For this reason it is better to rename it to avoid confusion.
=> config: rename skip-sql-invoice-migration to skip-native-sql-migration

cmd/commands/commands.go, docs/release-notes/release-notes-0.19.0.md
A user was having trouble debugging its node, which was running in an `lnd` without the `walletrpc` enabled. The user then tried to build the `lncli` with the RPC enabled, but the `lnd` node could not be built since it was running remotely. Then the command failed with the following weird msg,
```
./lncli wallet pendingsweeps
[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.
```
This message is confusing as it doesn't show the RPC isn't built. This is now changed to,
```
./lncli-debug wallet pendingsweeps
[lncli] rpc error: code = Unimplemented desc = unknown service walletrpc.WalletKit
```
In addition, this error msg is also fixed,
```
./lncli unlock       
Input wallet password: 
[lncli] rpc …
```
=> cmd: fix error parsed from status

config.go, config_builder.go, docs/release-notes/release-notes-0.19.0.md, sample-lnd.conf
This enables users to set the config. We check that the currently set value of `MaxPeers` isn't below the previous default to protect users from misconfiguration. Seen in https://github.com/lightningnetwork/lnd/discussions/9599.
=> lnd: pass through neutrino MaxPeers config

fn/list_test.go
standard library package:slices already include slices.Contains since Go 1.21, remove experimental package `x/exp/slices` 
=> fn: remove x/exp/slices dependency

go.mod, go.sum, itest/flakes.go, itest/lnd_channel_backup_test.go, itest/lnd_coop_close_with_htlcs_test.go, itest/lnd_open_channel_test.go, itest/lnd_route_blinding_test.go, itest/lnd_sweep_test.go, itest/lnd_wipe_fwdpkgs_test.go, lntest/harness_assertion.go
Depends on #9595, only the last four commits are new.
From this [build](https://github.com/yyforyongyu/lnd/actions/runs/13746923229/job/38442991178)
```
--- FAIL: TestLightningNetworkDaemon/tranche06/206-of-272/bitcoind/coop_close_with_htlcs (176.61s)
--- FAIL: TestLightningNetworkDaemon/tranche06/206-of-272/bitcoind/coop_close_with_htlcs/with_restart (137.87s)
harness_node.go:403: Starting node (name=Alice) with PID=5843
harness_node.go:403: Starting node (name=bob) with PID=6028
harness_node.go:403: Starting node (name=Alice) with PID=6450
harness_node.go:403: Starting node (name=bob) with PID=6563
harness_assertion.go:403: 
Error Trace:	/home/runner/work/lnd/lnd/lntest/harness_assertion.go:403
/home/runner/work/lnd/lnd/lntest/harness_assertion.go:374 …
```
=> lntest+itest: document and fix more flakes

docs/release-notes/release-notes-0.19.0.md, go.mod, go.sum, itest/flakes.go, itest/list_exclude_test.go, itest/lnd_multi-hop_force_close_test.go, itest/lnd_sweep_test.go, lnwallet/btcwallet/btcwallet.go, lnwallet/btcwallet/log.go, lnwallet/btcwallet/signer.go, lnwallet/log.go, log.go, sqldb/interfaces.go, sweep/fee_bumper.go, sweep/sweeper.go
This PR fixes the issue which `listunspent` gives inaccurate wallet balance. In addition, it moves the `walletdb` code back to `btcwallet`, to make sure we only have a single place managing it.
By fixing the bug, the itest flake `flakeFundExtraUTXO` is also now fixed.
Depends on,
- #9602 
- https://github.com/btcsuite/btcwallet/pull/995
Down to the rabbit hole, there are multiple layers contributed to this bug.
**Watched filters are registered asynchronously**
The fix is at `btcwallet` side. When deciding to watch for an address, the registration was done in a goroutine, which could cause a relevant tx to be missed due to the watched address was not registered yet.
**Databse tx is too large**
It's common that we have a read and write tx as the following,
- `ListUnspentWitness`, which …
=> Fix inaccurate `listunspent` result

docs/release-notes/release-notes-0.19.0.md, lnrpc/routerrpc/router_server.go
Fixes https://github.com/lightningnetwork/lnd/issues/9633
Routing fee estimation via `lncli estimateroutefee --pay_req ...` for an invoice with zero amount crashes lnd.
=> routerrpc: add nil check for MilliSat

config.go, discovery/gossiper.go, discovery/sync_manager.go, discovery/sync_manager_test.go, discovery/syncer.go, discovery/syncer_test.go, docs/release-notes/release-notes-0.19.0.md, lncfg/gossip.go, sample-lnd.conf, server.go
In this commit, we revamp the old message based rate limiting. First, we
move to meter by bytes/s instead of messages/s. The old logic had an
error in that it limited groups of message replies, instead of each
message. With this new approach, we'll use the newly added
SerializedSize method to implement fine grained bandwidth metering.
We need to pick two values, the burst rate, and the msg bytes rate. The
burst rate is the max amt that can be sent in a given period of time. We
need to set this above 65 KB, or the max msg limit, otherwise no
messages can be sent. The bucket starts with this many tokens (bytes).
As those are depleted, the amount of tokens is refilled at the msg
bytes rate.
As conservative values, we've chosen 200 KB as the burst rate, and 100
KB/s as the limit.
Depends on …
=> discovery: unify rate.Limiter across all gossip peers

docs/release-notes/release-notes-0.19.0.md, itest/list_on_test.go, itest/lnd_trackpayments_test.go, routing/control_tower.go, routing/router.go, routing/router_test.go
We are not consistent when handling payment failures so we need to make sure we do not fail a payment twice overwriting its previous failure reason.
Thanks @feelancer21 for reporting. Fixes https://github.com/lightningnetwork/lnd/issues/9542
Observed in the `sendtoroute` cmd. When tracking the payment it can be observed that we overwrite the payment failure.
=> multi: fix payment failure overwrite

aliasmgr/aliasmgr.go, docs/release-notes/release-notes-0.19.0.md, fn/map.go, fn/set.go, lnrpc/marshall_utils.go, lnrpc/walletrpc/walletkit_server.go, sweep/walletsweep.go
follow up:https://github.com/lightningnetwork/lnd/pull/9604
The original returned the keys in a slice, but when it became 'native' the signature changed to return an iterator, so the new idiom is slices.Collect(maps.Keys(theMap)), unless of course the raw iterator can be used instead.
=> multi: remove x/exp/maps dependency

docs/release-notes/release-notes-0.19.0.md, itest/list_on_test.go, itest/lnd_payment_test.go, lnrpc/routerrpc/router_backend.go, record/custom_records.go, routing/router.go
While working on the payment lifecycle I came across this case. When trying to send a keysend with a max shard restriction we would not fail the payment properly and it would hang indefinitely being marked as `INFLIGHT` in the db although no payment was attempted.
Just try sending a payment via this cmd:
`lncli sendpayment --dest XXX  --amt 100 --keysend --max_shard_size_sat 10`
The payment lifecycle will fail here because keysend payments are not MPP payments but we try to shard them:
https://github.com/lightningnetwork/lnd/blob/5d921723b1929c08c7397bbbef52b8639a55ac21/channeldb/payment_control.go#L419-L422
=> payment lifecycle small fix

server.go
If we are in `nochainbackend` mode, we need to skip fetching the best block during startup, otherwise it will be blocked.
Thanks to @ViktorTigerstrom for finding this bug!
=> lnd: skip setting `blockbeat` for `nochainbackend` mode

docs/release-notes/release-notes-0.19.0.md
Adds all missing contributors since v0.18.0-beta, extracted from the git log.
=> docs: update release notes with contributors

docs/release-notes/release-notes-0.19.0.md, itest/list_on_test.go, itest/lnd_funding_test.go, itest/lnd_multi-hop_force_close_test.go, itest/lnd_sweep_test.go, lntest/harness.go, lntest/harness_miner.go, rpcserver.go, sweep/fee_bumper.go, sweep/fee_bumper_test.go, sweep/sweeper.go, sweep/sweeper_test.go, sweep/tx_input_set.go, sweep/tx_input_set_test.go
This PR fixes the issue of the sweep being delayed due to the current wallet UTXOs not being able to cover the full budget. An example case is this [sweeping tx](https://mempool.space/tx/df6e296f245de37eb097a2f16eeb97fd7fa82dc8ed291efe87bb81e502be4e95), in which an HTLC output was swept with overshooting fees. This happened because the sweeper requires the budget to be fully covered before attempting the sweep, otherwise the sweeper will wait until more wallet UTXOs are available - by that time, the deadline may already be very close, or even passed, causing the full budget to be used up at once.
This PR changes the *all or nothing* behavior by starting the sweeping process asap if the budget can be covered partially. Later on, when there are more wallet UTXOs, the sweeper will add them …
=> Sweep inputs even the budget cannot be covered

lnwallet/chancloser/rbf_coop_test.go, protofsm/state_machine.go
In this commit, we fix a flake in the
`TestRbfChannelFlushingTransitions/early_offer` test. The fix is simple:
this is actually an "iteration", as we have a self transition to the
ChannelNegotiation state first. We also don't need to send the
remoteOffer, so we set `sendInit` to false. The offer still needs to be
passed in to ensure that the assertions work however.
=> lnwallet/chancloser: fix flake in TestRbfChannelFlushingTransitions/early_offer

docs/release-notes/release-notes-0.19.0.md, go.mod, go.sum, sqldb/migrations.go, sqldb/migrations_test.go, sqldb/postgres.go, sqldb/sqlc/migrations/000001_invoices.up.sql, sqldb/sqlc/migrations/000003_invoice_events.up.sql, sqldb/sqlite.go
Previously, if a DB version wasn't available, we re-ran all schema migrations without verifying the schema version. However, setting a base schema version is essential because some earlier migrations were not idempotent. This commit addresses the issue by using the current schema version provided by `sqlc` as the base.
Additionally, this PR includes the following fixes:
- Makes schema migration 1 and 3 idempotent.
- Removes the dirty schema flag caused by running `v0.19.0-rc1` on nodes using SQLite or PostgreSQL backends.
=> sqldb: establish a base DB version even if it's not yet tracked

go.mod, go.sum
Removes the temporary `sqldb` replace in favor of the v1.0.8 tag.
=> mod: use sqldb v1.0.8

.github/workflows/release.yaml
vendor folder needs to be inside lnd-source folder for the following comands to work, but the two tar commands extract them in separate folder
Update quick build commands in release doc
Previous build commands did not build as is, now it does
=> Fix release build command

dev.Dockerfile, scripts/bw-compatibility-test/docker-compose.override.yaml, scripts/bw-compatibility-test/docker-compose.yaml, scripts/bw-compatibility-test/network.sh, scripts/bw-compatibility-test/test.sh
With this change, we'll test that a node with SQLite backend (using mixed KV and native schema) remains backward compatible.
It helps prevent incompatibility issues caused by SQL schema changes or invalid migrations, like the one fixed in: https://github.com/lightningnetwork/lnd/pull/9647.
=> scripts+bw-compatibility-test: update Dave and make it use sqlite

config_builder.go
This commit removes a log line that could be misunderstood in the context of bolt KV to SQL migration.
Fixes:  https://github.com/lightningnetwork/lnd/issues/9660
=> lnd: remove unnecessary debug log to avoid misunderstanding

go.mod, go.sum
After merging #9665, we can now bump to the tagged version.
=> mod: bump kvdb to latest tagged version v1.4.13

itest/list_on_test.go, itest/lnd_coop_close_with_htlcs_test.go, lncfg/protocol.go, lntest/node/config.go, peer/brontide.go, server.go
In this commit, we implement logic to downgrade to the legacy coop close
for taproot channels. Before this commit, we wouldn't allow nodes to
start up with both the taproot flag and the rbf flag activated.
In the future, once we implement the spec updates, we'll add support for
this combo, and can revert parts of this commit.
We then test all the combinations of rbf close and taproot
chans. This ensures that the downgrade logic works properly.
Along the way we refactor the tests slightly, and also split them up, as
running all the combos back to back mines more than 50 blocks in a test,
which triggers an error in the itest sanity checks.
=> multi: downgrade to legacy coop close for taproot channels

go.mod, go.sum, kvdb/sqlite/db.go, sqldb/sqlite.go
In this commit, we make a change that enables the `auto_vacuum = incremental` pragma for SQLite databases, but only when the database file is first created. Incremental auto-vacuum allows SQLite to reclaim unused space within the database file over time, preventing indefinite growth.
According to the SQLite documentation, the `auto_vacuum` mode must be set *before* any tables are created in the database. To achieve this, a new boolean parameter `isCreate` has been added to the `NewSqliteBackend` function.
The `createDBDriver` now passes `true` for this parameter, ensuring the pragma is set during initial database setup. Conversely, `openDBDriver` passes `false` when opening an existing database, leaving the existing vacuum mode untouched.
We also change, the internal representation of …
=> kvdb/sqlite: enable incremental auto_vacuum on DB creation

kvdb/backend.go, kvdb/etcd/db_test.go, kvdb/etcd/fixture.go, kvdb/etcd/readwrite_tx_test.go, kvdb/etcd/walletdb_interface_test.go, macaroons/service_test.go, macaroons/store_test.go
This is part of the last step required to complete https://github.com/lightningnetwork/lnd/issues/9494. We want all calls to the graph DB (and hence, ChannelGraph) to take a context since later, this context will be passed through to any remote graph RPC calls as well as any DB calls to a SQL graph backend. 
All this PR does is remove any existing `context.TODO()` invocations that are made in test code. We do this to improve the signal-to-noise ratio of the `context.TODO` call which should signal that work needs to be done to thread contexts through accordingly in order to remove the call. 
With this PR, there is only one remaining call to `context.TODO()` in the code base.
=> macaroons+kvdb: improve signal-to-noise ratio of `context.TODO`

discovery/gossiper.go, discovery/gossiper_test.go, discovery/reliable_sender.go, discovery/reliable_sender_test.go, lnd.go, server.go
This is part of the last step required to complete https://github.com/lightningnetwork/lnd/issues/9494. We want all calls to the graph DB (and hence, ChannelGraph) to take a context since later, this context will be passed through to any remote graph RPC calls as well as any DB calls to a SQL graph backend. 
We start in the `discovery` package since the gossiper and the syncers make calls to the graph. So we prepare accordingly by threading LND's parent context to the gossiper and threading it through to where we will use it later. 
This series of PRs is basically a big code refactor. So once 19 is shipped, we can merge any work that has been merged into `elle-graph` and from then on we can just merge into master.
=> discovery: thread context through in preparation for passing to graph DB

lnrpc/chainrpc/chain_server.go
They pointed to a non-existing type `ChainNotifierService`. The actual name of the interface is `ChainNotifierServer`.
=> chainrpc: fix description of several methods

discovery/bootstrapper.go, discovery/gossiper.go, discovery/gossiper_test.go, discovery/sync_manager.go, discovery/sync_manager_test.go, discovery/syncer.go, discovery/syncer_test.go, peer/brontide.go, server.go
This is part of the last step required to complete https://github.com/lightningnetwork/lnd/issues/9494. We want all calls to the graph DB (and hence, ChannelGraph) to take a context since later, this context will be passed through to any remote graph RPC calls as well as any DB calls to a SQL graph backend. 
We do the last bit of context threading in the `discovery` package by reading contexts through the syncer, sync manager and reliable sender. We also update the public `ProcessRemoteAnnouncement` method to take a context and leave a `context.TODO()` in the brontide package which calls it. This todo will be addressed in an upcoming PR in the series. 
This series of PRs is basically a big code refactor. So once 19 is shipped, we can merge any work that has been merged into `elle-graph` …
=> discovery: thread contexts through syncer, sync manager and reliable sender

graph/db/graph_test.go
This PR does some clean up in the `graph/db` test code to start preparing the tests to be ready to run against an abstract DB (either kvdb or sql schema).
=> graph/db: clean up test code in preparation for DB abtraction

autopilot/agent.go, autopilot/agent_test.go, autopilot/betweenness_centrality.go, autopilot/betweenness_centrality_test.go, autopilot/combinedattach.go, autopilot/externalscoreattach.go, autopilot/externalscoreattach_test.go, autopilot/graph.go, autopilot/interface.go, autopilot/manager.go, autopilot/prefattach.go, autopilot/prefattach_test.go, autopilot/simple_graph.go, autopilot/top_centrality.go, autopilot/top_centrality_test.go, discovery/bootstrapper.go, lnd.go, lnrpc/autopilotrpc/autopilot_server.go, rpcserver.go
This is part of the last step required to complete https://github.com/lightningnetwork/lnd/issues/9494. We want all calls to the graph DB (and hence, ChannelGraph) to take a context since later, this context will be passed through to any remote graph RPC calls as well as any DB calls to a SQL graph backend. 
In this PR, we tackle the `autopilot` package. This package has a `GraphSource` interface which redirects to the graph DB. So later on, all methods in this interface will take a context. In preparation for this, we update the autopilot server to thread contexts through accordingly. 
This series of PRs is basically a big code refactor. So once 19 is shipped, we can merge any work that has been merged into `elle-graph` and from then on we can just merge into master.
=> autopilot: thread contexts through in preparation for GraphSource methods taking a context

lntest/node/harness_node.go
Ensure shutdown assertions through log inspection are only performed when the harness node has an active log file handle. This avoids errors during shutdown when log file output is disabled.
Disable log file output via CLI flag, ensure harness nodes shutdown without error.
=> lntest: assert shutdown via logs only if log file handle is present

docs/release-notes/release-notes-0.19.0.md, routing/payment_lifecycle.go, routing/payment_lifecycle_test.go
Fix #9688 by making sure we always set the `Hash` field on legacy payments.
=> Patch htlc attempt hash for legacy payments

channeldb/db_test.go, channeldb/meta_test.go, graph/builder_test.go, graph/db/graph_test.go, graph/notifications_test.go
In this PR, we continue with some basic clean-up of the `graph/db`, `graph` and `channeldb` test code in preparation for plugging in a new graph backend DB type. See commit messages for more details. 
The goal is to get the unit tests in such a state so that in the PR that adds the new DB implementation, the unit tests dont need to change at all.
=> graph+channeldb: test clean-up in preparation for different graph DB backend

go.mod, go.sum
Bumps to the latest `kvdb` tag after merging https://github.com/lightningnetwork/lnd/pull/9684.
=> mod: bump kvdb to v1.4.15

config_builder.go, docs/release-notes/release-notes-0.19.0.md, lncfg/db.go
We now also move the neutrino data storage to postgres when we run the backend in postgres mode. This is still not natvie sql for neutrino but it moves everything in one place so we do not have the scattered db across multiple backends.
The migration tool will migrate the `neutrino.db` to the new sql-db schema. However if you were running postgres and neutrino initially this change will just start the `neutrino.db` from a fresh state because there is no critical data to preserve and it would just overcomplicate things to move the migration code from `lndinit` to this place.
Maybe the neutrino.db can be migrated as soon as we have the migration code in LND ?
=> Move neutrino db also to postgres when using postgres as a backend

scripts/bw-compatibility-test/network.sh
The backwards compatibility test sometimes fails due to the `[lncli] rpc error: code = Unknown desc = server is still in the process of starting` error when we try to connect nodes right after checking if they have started. This is cause the `has started` check currently only checks if the GetInfo call is available - but it can be available before LND has actually fully started.  
use The `StateServer` (via `lncli status`) when waiting for a node to be ready as this is a more reliable/accurate signal that the node is ready for other RPC calls.
=> scripts: use LND status to determine when a node is ready for RPC calls

htlcswitch/interfaces.go, htlcswitch/link.go, lnwallet/aux_leaf_store.go, lnwallet/aux_signer.go, lnwallet/channel.go, routing/bandwidth_test.go
This PR adds an extra argument to the `PaymentBandwidth` hook, which helps with computing a more precise aux htlc view, ultimately leading to more precise bandwidth results.
We expose the HtlcView from the lighting channel for the link to use when checking whether an HTLC can be added to the channel.
=> `AuxTrafficShaper.PaymentBandwidth` uses HTLC view

docs/release-notes/release-notes-0.19.0.md, go.mod, go.sum, itest/list_on_test.go, itest/lnd_wallet.go, lntest/harness.go, lntest/harness_assertion.go, rpcserver.go
Depends on https://github.com/btcsuite/btcwallet/pull/1002, in this PR we now fix the issue found in,
- #8786
=> Fix inaccurate `locked_balance`

itest/lnd_route_blinding_test.go
The itest framework now handles the closure of any channels opened during the test and so we dont need to manually close them. The manual closure code in the route blinding tests were resulting in the occasional test flake.
(I've lost the link to the build where I saw the flake since I triggered a re-run of the individual test 🙈 )
=> itest: remove manual channel closures from route blinding tests

htlcswitch/interfaces.go, htlcswitch/link.go, htlcswitch/switch.go, routing/bandwidth_test.go
Whether we should let the aux bandwidth manager decide what the
bandwidth of a channel is should also depend on whether the HTLC is a
custom HTLC, not just the channel.
=> Aux bandwidth manager: also pass HTLC blob to `ShouldHandleTraffic`

.github/workflows/main.yml, docs/release-notes/release-notes-0.19.0.md
Make sure `lnd 0.19.0-beta` will be compatible with `bitcoind v29.0`.
=> scripts+GitHub: use bitcoind v29.0

docs/release-notes/release-notes-0.19.0.md, go.mod, go.sum, kvdb/postgres/config.go, kvdb/postgres/db.go, kvdb/sqlbase/db.go, kvdb/sqlbase/readwrite_tx.go, lncfg/db.go
The wallet code is still not robust enough to run with a concurrent writer, therefore we add the single writer back but will remove it as soon as we refactored the wallet code.
=> Add the global lock for the wallet db back for postgres

accessman.go, lnutils/log.go, log.go
In this PR, we add logging to the new Access Manager. It was committed without any logs at all, which otherwise would've made it hard to monitor and debug the new sub-system.
=> accessman: add logging to new sub-system

channeldb/invoices.go, channeldb/payment_control.go, channeldb/payments.go, invoices/sql_store.go
Switched the batchsize to 30 seconds instead of number of payments
and invoices.
Fixes https://github.com/lightningnetwork/lnd/issues/9743
=> mulit: increase logprogress time

docs/release-notes/release-notes-0.19.0.md, lnwallet/channel.go
When running LND with an aux component injected we do not need to consult the aux component for non-anchor channels.
Probably we could add an itest or something on the LITD side.
=> lnwallet: no need to consult the aux unit for legacy channels

htlcswitch/interfaces.go, htlcswitch/link.go, routing/bandwidth_test.go
For certain auxiliary bandwidth checks we need to know the funding blob that was present when the channel was created.
=> htlcswitch+routing: add funding blob to PaymentBandwidth

docs/release-notes/release-notes-0.19.0.md, itest/list_exclude_test.go, itest/list_on_test.go, itest/lnd_coop_close_external_delivery_test.go, lnwallet/interface.go
If a Taproot address is added to LND using the [`ImportTapscript` RPC](https://api.lightning.community/api/lnd/wallet-kit/import-tapscript), LND previously failed to perform a cooperative close to that address.
The issue was originally reported in the Loop repository: https://github.com/lightninglabs/loop/issues/923
The root cause was in the [`lnwallet.InternalKeyForAddr`](https://github.com/lightningnetwork/lnd/blob/v0.19.0-beta.rc2/lnwallet/interface.go#L663-L667) function. This function assumed that all Taproot addresses implement the [`ManagedPubKeyAddress`](https://pkg.go.dev/github.com/btcsuite/btcwallet@v0.16.12/waddrmgr#ManagedPubKeyAddress) interface, implying that a private key is available. However, this assumption does not hold for externally imported addresses, which is why …
=> lnwallet: fix InternalKeyForAddr for imported addr

.github/workflows/release.yaml
Fixes the release build. Turns out the Golang installation is now also stored under the `/opt/hostedtoolcache` folder. So if we delete that _after_ installing Go, then things don't work as expected.
Successful run can be seen here: https://github.com/guggero/lnd/actions/runs/14635083197/job/41064400208
=> GitHub: fix order of operations for release build

docs/release-notes/release-notes-0.19.0.md
Indentations were messed up on the text for the RBF coop close section and were being rendered weird in markdown. It was hard to tell what text was actually part of RBF and what was related to other features discussed below it. This small change makes it much easier to read the rendered markdown.
=> docs/release-notes: fix indentation in RBF close section

channeldb/migration32/migration_test.go, channeldb/migration32/mission_control_store.go, docs/release-notes/release-notes-0.19.0.md, routing/missioncontrol.go, routing/missioncontrol_store_test.go, routing/result_interpretation.go, routing/result_interpretation_test.go
Tries to fix https://github.com/lightningnetwork/lnd/issues/9769.
Demonstrates the migration error and attempts a fix by making the failure message an optional tlv record. I'm not sure if we want to do this because it's strange that the failure message is nil in the first place. Perhaps we want to instead migrate nil failure messages to `CodeNone` instead or drop these entries.
=> routing+migration: fix mission control migration with nil failure msg

batch/interface.go, batch/scheduler.go, graph/db/kv_store.go
Currently, a few of the graph KVStore methods take the `batch.SchedularOptions` param. This is only used to set the `LazyAdd` option. A `SchedularOption` is a functional option that takes a `batch.Request` which has bbolt-specific fields in it. This commit restructures things a bit such that the `batch.Request` type is no longer part of the `batch.SchedularOptions` - this will make it easier to implement the graph store with a different DB backend (since we can then introduce an interface to describe the graph Store that is db agnostic and doesnt have bbolt specific types).
=> batch: dont expose kvdb.RwTx in batch.SchedulerOptions

tlv/primitive.go, tlv/record.go
Ensure that we do not silently return zero size if the type passed to SizeBigSize is not handled within the function.
This is an alternative to https://github.com/lightningnetwork/lnd/pull/9788 which opts for instead changing the function signature of SizeFunc so that we return explicit errors. This alternative allows us to fix this issue with a smaller impact zone. 
If this is merged, we can close https://github.com/lightningnetwork/lnd/pull/9788 and https://github.com/btcsuite/btcwallet/pull/1010 and then update https://github.com/lightningnetwork/lnd/pull/9789 to just point to this new `tlv` package version
=> tlv: catch unhandled type in SizeBigSize

autopilot/prefattach_test.go, config_builder.go, docs/release-notes/release-notes-0.20.0.md, graph/db/graph.go, graph/db/graph_test.go, graph/db/interfaces.go, graph/db/kv_store.go, graph/notifications_test.go, peer/test_utils.go, routing/pathfind_test.go
In this PR, we introduce the `V1Store` interface which the existing
`graphdb.KVStore` implements today. This is in preparation for adding
a SQL implementation of this interface eventually. 
We then start using this interface from within the `ChannelGraph` instead of directly using
a `KVStore` pointer.
=> graph/db: introduce a `V1Store` interface

docs/release-notes/release-notes-0.20.0.md, graph/db/graph_test.go, lnwire/channel_announcement.go, lnwire/channel_announcement_2.go, lnwire/channel_update.go, lnwire/channel_update_2.go, lnwire/extra_bytes.go, lnwire/node_announcement.go
In this PR, we start validating that any gossip message we decode has a valid TLV stream. 
This is in preparation for creating a SQL version of the graph store in which we will store the TLV
records in a normalised fashion instead of in a flat structure as is done today. 
part of https://github.com/lightningnetwork/lnd/issues/9795
=> graph+lnwire: start validating that extra lnwire msg bytes are valid TLV

docs/release-notes/release-notes-0.19.0.md, routing/probability_bimodal.go, routing/probability_bimodal_test.go
Fixes normalization bugs with respect to large channels and situations where the channel doesn't obey a bimodal distribution (fixes #8263 and #9085). 
The probability calculation is avoided for amounts smaller than the last success amount in order to speed things up. This also fixes a case where mission control has outdated values (fixes #7553).
=> bimodal pathfinding probability improvements

graph/db/graph_test.go, graph/db/kv_store.go
This PR expands the graph db unit tests to ensure that all the methods covered in the `V1Store` interface are covered. 
A couple other changes are also made to prepare the tests for the upcoming SQL implementation of the graph store - more detail for these commits is given in the commit messages. 
Part of #9795
=> graph/db: add test coverage for all V1Store methods 

docs/release-notes/release-notes-0.19.0.md, graph/db/graph.go, graph/db/notifications.go
In this commit, a race is fixed that could result in notifications being missed by a topology client if the notifications are sent too soon after the SubscribeTopology call is made due to the fact that the topology client is stored asynchronously at the moment in
`handleTopologySubscriptions`. This means that the client may only be stored _after_ `SubscribeTopology` has exited _and_ new notifications have already been sent. NOTE: this is only the case for notifications originating from `PruneGraph` as those are not currently forced to go via the `topologyUpdates` channel. This commit fixes that. 
See [this build](https://github.com/lightningnetwork/lnd/actions/runs/14904423814/job/41863427226?pr=9692) for an example of this race condition being triggered. 
To see the race in action: add a …
=> graph/db: synchronous topology client subscriptions/cancellations

config.go, docs/release-notes/release-notes-0.19.0.md, peer/brontide.go, peer/ping_manager.go, peer/ping_manager_test.go, sample-lnd.conf, server.go
In this commit, we add a new CLI option to control if we D/C on slow pongs or not. Due to the existence of head-of-the-line blocking at various levels of abstraction (app buffer, slow processing, TCP kernel buffers, etc), if there's a flurry of gossip messages (eg: 1K channel updates), then even with a reasonable processing latency, a peer may still not read our ping in time.
To combat this, we change the default behavior to just logging for slow pongs, and add a new CLI option to re-enable the old behavior.
Along the way, we also add some more enhanced logging, so we can tell when the last successful ping was, and also the deadline reached.
=> peer+lnd: add new CLI option to control if we D/C on slow pongs

build/version.go
Bumps the version to `v0.19.0-beta.rc5`.
Will be merged after https://github.com/lightningnetwork/lnd/pull/9801 has landed.
=> build: bump version to v0.19.0-beta.rc5

docs/release-notes/release-notes-0.19.0.md
The `lncli listchannels` command was changed and might cause breaking
changes for people relying on the `chan_id` return value in their
automation scripts.
=> Update release notes for LND 19 - lncli breaking change

batch/batch.go, batch/batch_test.go, batch/interface.go, batch/kvdb.go, batch/scheduler.go, graph/db/kv_store.go
In preparation for using the same logic for non-bbolt backends, we adapt
the batch.Schedular to be more generic.
We also add a new BenchmarkBoltBatching test that helps us benchmark the
performance when writing to a bbolt backend using various different
configurations. We test using N txs for N writes, 1 tx for N writes and
then various configurations when using the TimeScheduler.
Notice here the huge difference between N-for-N and 1-for-N. This shows us that batching in SQLite is preferable. So now we take a look at the batcher results and we can see that this confirms that batching is more efficient since when `lazy=true` the scheduler will batch more and this is more efficient. The sweet spot in terms of batch interval seems to be around 50ms. 
``` …
```
=> batch: generic scheduler + benchmark tests

sample-lnd.conf
Modified description regarding the real default value for the parameter `protocol.rbf-coop-close` to avoid confusion. Replaced: "disable" with "enable".
If not specified: `protocol.rbf-coop-close=true` on `lnd.conf`
After `lncli getinfo`, the following lines don't appear:
```
"161":  {
"name":  "rbf-coop-close-x",
"is_required":  false,
"is_known":  true
```
- PR with the sample-lnd.conf addition: https://github.com/lightningnetwork/lnd/pull/9610 line: https://github.com/lightningnetwork/lnd/pull/9610/files#diff-3a6efa92418cc425498701df4dbd84e1d143908b58b9872f566a952baa281200R1416
- Release note fragment where this default and correct state is mentioned: https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.19.0.md?plain=1#L154
=>  docs: fix description of protocol.rbf-coop-close default state in sample-lnd.conf

protofsm/state_machine_test.go
Update unit test to call `StateMachine.IsRunning()` to ensure the method has test coverage.
Should have been included here: https://github.com/lightningnetwork/lnd/pull/9883
=> protofsm: exercise `StateMachine.IsRunning()` in unit test

docs/release-notes/release-notes-0.19.1.md, itest/list_on_test.go, itest/lnd_coop_close_rbf_test.go, peer/brontide.go
In case when the rbf coop close feature was active we would not
properly disconnect the peer.
=> brontide: fix peer disconnection issue

graph/db/graph_test.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/queries/graph.sql
Fix the SQL implementation of `AddLightningNode` so that it's underlying `UpsertNode` query accounts
for the `last_update` field being null in the case of the initial node record being a shell node (a shell node
is one for which we only know the version and pubkey).
=> sqldb+graph/db: fix UpsertNode query to account for nullable `last_update` field

feature/default_sets.go, feature/manager.go, peer/brontide.go
In this commit, we start to signal the prod bit for the rbf coop close feature. We keep our signaling of the staging bit in place to ensure the protocol continues to work between those nodes in the wild that are still signaling the bit.
Fixes https://github.com/lightningnetwork/lnd/issues/9852
=> peer+feature: start to signal the prod rbf coop close bit

protofsm/daemon_events.go, protofsm/state_machine.go, protofsm/state_machine_test.go
In this PR, we add a new ConfMapper which is useful for state
machines that want to project some of the conf attributes into a new
event to be sent post conf.
We then unit tests for the existing `SpendMapper` alongside the 
new tests for the `ConfMapper`.
=> protofsm: add ConfMapper to allow conf attribute projection for new events

protofsm/daemon_events.go, protofsm/state_machine.go, protofsm/state_machine_test.go
In this PR, we add an option to allow a conf req caller to receive
the full block. This is useful if the caller wants to be able to create
an SPV proof.
=> protofsm: add option to allow conf resp to return full block

accessman.go, accessman_test.go, config.go, docs/release-notes/release-notes-0.19.1.md, sample-lnd.conf
If a peer has, or used to have a channel with us there's no need to check for the ban score.
=> accessman: remove restrictions on protected/temporary peers

htlcswitch/switch.go, lntest/harness.go
=> htlcswitch+lntest: add more debug logs

docs/release-notes/release-notes-0.20.0.md, graph/db/graph.go, graph/db/graph_cache.go, graph/db/graph_cache_test.go, graph/db/interfaces.go, graph/db/kv_store.go, graph/db/models/cached_edge_info.go, graph/db/models/cached_edge_policy.go, routing/unified_edges.go
In this PR, we adjust the various methods of the `GraphCache` such that they all only take the `models.Cached*` versions
of various types (namely `CachedEdgeInfo` and `CachedEdgePolicy`). 
This then allows us to implement a new `ForEachChannelCacheable` method which only requires the 
DB layer to fetch the info needed to construct the cache types. This will be useful when we add the SQL version 
of the graph store so that we can reduce the number of DB round trips. 
=> graph/db: only fetch required info for graph cache population

go.mod, go.sum
Bump `tlv` to `v1.3.2` and `sqldb` to `v1.0.10` & remove the respective `replace` directives in the `go.mod`. 
The `sqldb` replace will be re-added later. This is just to provide other projects the ability to build on the current 
state of `master` branch
=> go.mod: remove tlv and sqldb replace directives

docs/release-notes/release-notes-0.20.0.md, server.go
In this commit, we prevent partial mutation of the current node announcement during announcement signing. Previously, if node announcement signing failed, the current node announcement could become inconsistent.
This issue was discovered while working on issue #9455. Specifically, it was observed that:
- The enforcement of a single DNS hostname address related to Bolt 07 occurs in `WriteNetAddrs`.
- If there’s is an error, the error is correctly propagated from `netann.SignNodeAnnouncement`.
- However, part of the current node announcement (e.g., `Addresses []net.Addr` or CLI field `uris` from `getinfo`) was still being updated, leading to inconsistencies when inspecting with the command:
```bash
lncli --network=regtest getinfo | jq '.uris'
```
Steps for reviewers to follow to test the …
=> server.go: prevent partial mutation of `currentNodeAnn` in `server.genNodeAnnouncement` on `netann.SignNodeAnnouncement` failures

channeldb/db.go
Resolves https://github.com/lightningnetwork/lnd/issues/6155 by creating the top level buckets before the potential early return for metadata check.
1. Deploy lnd in remote-signer on an older version of LND.
2. Upgrade to 0.19.0-rc1.
The signer LND node should fail to start due to an error:
```
2025-03-26 14:33:08.912 [INF] CRTR: Loaded 0 mission control entries
2025-03-26 14:33:08.913 [ERR] LTND: Shutting down due to error in main method rev=0053fd err="historical channel bucket has not yet been created"
2025-03-26 14:33:08.914 [INF] LTND: Stopping pprof server... rev=0053fd
```
=> channeldb: perform init of top level buckets first

build/version.go
This version signifies a transitionary version of master between major versions.
=> build: bump version to v0.19.99

docs/SphinxReplayDB.md
Previouly the sphinx replay db would cause confusion for what it
is needed at all. We clarify it in a detailed document.
Resolves https://github.com/lightningnetwork/lnd/issues/6584
=> docs: add sphinx replay description

chainntnfs/bitcoindnotify/bitcoind.go, chainntnfs/btcdnotify/btcd.go, docs/release-notes/release-notes-0.19.2.md
While debugging #9917 I realized the rescan start height could be a bit off when the output has already been spent. We now fix it by always using the spent height as the rescan start height if the output has already spent, even if the caller is specifying a different height hint.
=> Use spent height as the rescan start height in `RegisterSpendNtfn`

docs/release-notes/release-notes-0.20.0.md, go.mod, go.sum, graph/db/graph_test.go, graph/db/sql_store.go, graph/db/test_postgres.go, graph/db/test_sqlite.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/migrations/000007_graph.down.sql, sqldb/sqlc/migrations/000007_graph.up.sql, sqldb/sqlc/models.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql
In this PR, the following schemas are defined for storing graph channel policy data. NOTE the nodes & channels tables here are only to show how they fit in - the full nodes & channels pictures can be seen [here](https://github.com/lightningnetwork/lnd/pull/9866) and [here](https://github.com/lightningnetwork/lnd/pull/9869).
NOTE: here we only define the schemas and add enough queries so that we can implement the `UpdateEdgePolicy`  method. So with this PR we are not really yet testing reading from these new tables. This is left to follow up PRs since those will be quite a lot of code and I want to keep this PR contained as it already contains new schemas etc. 
See https://github.com/lightningnetwork/lnd/pull/9932 for the full …
=> graph/db+sqldb: channel policy SQL schemas, queries and upsert CRUD

docs/release-notes/release-notes-0.20.0.md, graph/db/graph_test.go, graph/db/notifications.go, graph/db/sql_store.go, graph/notifications_test.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql
In this PR, the following methods are implemented on the graph SQLStore:
- ForEachNode
- ForEachNodeDirectedChannel
- ForEachNodeCacheable
- ForEachNodeChannel
Part of #9795 
See https://github.com/lightningnetwork/lnd/pull/9932 for the full picture that we are aiming at
=> [11] graph/db: Implement various "ForEach" methods on the graph SQLStore

autopilot/prefattach_test.go, discovery/chan_series.go, discovery/gossiper.go, discovery/gossiper_test.go, discovery/syncer.go, discovery/syncer_test.go, graph/builder.go, graph/builder_test.go, graph/db/graph.go, graph/db/graph_test.go, graph/db/interfaces.go, graph/db/kv_store.go, graph/db/sql_store.go, graph/interfaces.go, graph/notifications_test.go, lnd.go, lnrpc/devrpc/dev_server.go, lnrpc/peersrpc/config_active.go, lnrpc/peersrpc/peers_server.go, routing/localchans/manager.go, routing/localchans/manager_test.go, routing/pathfind_test.go, routing/router_test.go, rpcserver.go, server.go, subrpcserver_config.go
Continuing on from https://github.com/lightningnetwork/lnd/pull/9956...
In preparation for having the ChannelGraph perform some remote RPC calls, we need all its methods to take a context parameter so that those calls are cancellable. This also lets us remove some of the context.TODO() calls that we currently have in the SQLStore method implementations. More will be done in follow up PRs.
This PR threads contexts through to the following methods:
- SetSourceNode
- SourceNode
- AddChannelEdge
- UpdateEdgePolicy
- LookupAlias
- HightestChanID
Wherever we can we thread through existing contexts from call sites. In some places we just use a context.TODO for now where context threading will be more complicated. Removing these context.TODOs can happen in later PRs that are dedicated to adding …
=> multi: add context.Context param to more graphdb.V1Store methods

graph/db/graph.go, graph/db/kv_store.go
Similarly to https://github.com/lightningnetwork/lnd/pull/9951, here we make sure to do a nil 
check on ChannelEdgePolicy pointers before dereferencing them. In the graph/db code, we should
always expect a ChannelEdgePolicy to potentially be nil. 
The second commit addresses [this](https://github.com/lightningnetwork/lnd/pull/9951/files#r2149940819) comment
from the review of that PR.
=> graph/db: do nil check on ChannelEdgePolicy 

lnwire/onion_error_test.go
Ensure that tests can run in parallel without causing a data race by adding a `makeTestChannelUpdate` constructor rather than sharing the same `testChannelUpdate` type between tests. This is needed since some tests write to the type.
Data race seen in [this](https://github.com/lightningnetwork/lnd/actions/runs/15775488150/job/44468893481?pr=9937) build.
```
Write at 0x0000016898[30](https://github.com/lightningnetwork/lnd/actions/runs/15775488150/job/44468893481?pr=9937#step:9:31) by goroutine 64:
github.com/lightningnetwork/lnd/lnwire.(*ExtraOpaqueData).PackRecords()
/home/runner/work/lnd/lnd/lnwire/extra_bytes.go:101 +0x69
github.com/lightningnetwork/lnd/lnwire.EncodeMessageExtraData()
/home/runner/work/lnd/lnd/lnwire/extra_bytes.go:157 +0x4d …
```
=> lnwire: fix test data race

docs/release-notes/release-notes-0.20.0.md, lntest/bitcoind_common.go, lntest/btcd.go, lntest/neutrino.go, lntest/node/config.go
Previously, Neutrino could be enabled via the `neutrino` build tag, which affected all LND nodes involved in an itest and required using a `btcd` miner as the source of compact block headers. This PR introduces a more flexible setup: it is now possible to run some LND nodes with a regular `bitcoind` backend, while others use Neutrino with `bitcoind`'s P2P interface as the source of compact block headers. This allows testing more complex scenarios where some nodes have a local `bitcoind` instance, while others rely on Neutrino for lightweight syncing.
```bash
make itest
```
The change is fully backwards compatible, and all existing itests should continue to pass.
📝 Please see our [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines. …
=> lntest: enable neutrino testing with bitcoind

channeldb/db.go, channeldb/log.go, channeldb/meta.go, channeldb/meta_test.go, channeldb/migration34/log.go, channeldb/migration34/migration.go, channeldb/options.go, config_builder.go, docs/release-notes/release-notes-0.19.2.md, lncfg/db.go, sample-lnd.conf
Builds on top of https://github.com/lightningnetwork/lnd/pull/9929.
This PR adds an Optional Migration which is by default set to true.
~~Looking for ACK or NACK.~~
=> Decayed log optional migration

itest/lnd_sweep_test.go
Removed finished TODOs and fixed the itest flake found in several CIs, e.g., this [one](https://github.com/lightningnetwork/lnd/actions/runs/15774978611/job/44467279473?pr=9967),
```
--- FAIL: TestLightningNetworkDaemon/tranche01/64-of-298/bitcoind/sweep_cpfp_anchor_incoming_timeout (202.59s)
harness_node.go:403: Starting node (name=Alice) with PID=53262
harness_node.go:403: Starting node (name=Bob) with PID=55151
harness_node.go:403: Starting node (name=Carol) with PID=55931
lnd_sweep_test.go:608: Bob(position=3): txWeight=722 wu, expected: [fee=7686, feerate=10645 sat/kw], got: [fee=7692, feerate=10654] in tx 0988fecd73248a91ac56645dd78f0e2c9b0470443ba221c97578e2fe12583171
lnd_sweep_test.go:608: Bob(position=2): txWeight=722 wu, expected: [fee=13567, feerate=18791 sat/kw], got: …
```
=> itest: fix flake in `sweep_cpfp_anchor_incoming_timeout`

lntest/fee_service.go
If HTTP response is consumed slowly, this might block other HTTP requests to the fee service, because the mutex is held.
```
make itest
```
=> lntest: do not do IO under mutex in fee_service

docs/release-notes/release-notes-0.20.0.md, graph/db/graph_test.go, graph/db/kv_store.go, graph/db/sql_store.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/migrations/000007_graph.down.sql, sqldb/sqlc/migrations/000007_graph.up.sql, sqldb/sqlc/models.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql
This PR adds the schema, queries and CRUD for the zombie index. 
The following methods are implemented: 
- MarkEdgeZombie
- MarkEdgeLive
- IsZombieEdge
- NumZombies
- DeleteChannelEdges
This then lets us run `TestGraphZombieIndex` against the SQL backends.
Depends on https://github.com/lightningnetwork/lnd/pull/9936
See https://github.com/lightningnetwork/lnd/pull/9932 for the full picture that we are aiming at
=> [13] graph/db: SQL-ize the zombie index

docs/release-notes/release-notes-0.19.2.md, lnwallet/chainfee/rates.go, lnwallet/chainfee/rates_test.go
This PR adds method `FeeForWeightRoundUp` to the `chainfee` package which rounds up a calculated fee value to the nearest satoshi.
This is related to an issue we are seeing in loop: https://github.com/lightninglabs/loop/issues/966
=> chainfee: method to round up the fee for a given transaction weight

docs/release-notes/release-notes-0.20.0.md, graph/db/graph_test.go, graph/db/sql_store.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/migrations/000007_graph.down.sql, sqldb/sqlc/migrations/000007_graph.up.sql, sqldb/sqlc/models.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql
Here we add the schema, queries and CRUD for the prune log. The following methods are implemented:
- PruneGraphNodes
- PruneGraph
- PruneTip
- ChannelView
- DisconnectBlockAtHeight
Depends on https://github.com/lightningnetwork/lnd/pull/9938
See https://github.com/lightningnetwork/lnd/pull/9932 for the full picture that we are aiming at
=> [15] graph/db: SQL prune log

docs/release-notes/release-notes-0.20.0.md, graph/db/graph_test.go, graph/db/kv_store.go, graph/db/sql_store.go, routing/pathfind_test.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/migrations/000007_graph.down.sql, sqldb/sqlc/migrations/000007_graph.up.sql, sqldb/sqlc/models.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql
In this PR, we do a few things:
1) we define the SQL schema of the `closed_scid` index. This lets us then implement the following methods:
`PutClosedScid`, `IsClosedScid`
2) We also let the SQLStore implement the last couple of V1Store methods: `ForEachChannelCacheable`, `AddEdgeProof`, `GraphSession`
See https://github.com/lightningnetwork/lnd/pull/9932 for the full picture that we are aiming at
=> [16] graph/db: SQL closed SCIDs table and last few methods

docs/release-notes/release-notes-0.19.2.md, peer/brontide.go, rpcserver.go, server.go
In case we cannot guarantee that the peer has started up
completely we launch the disconnect method asynchronously to prevent potential deadlocks.
Fixes: https://github.com/lightningnetwork/lnd/issues/9970
=> multi: fix deadlock in p2p race condition

chainreg/chainregistry.go, docs/release-notes/release-notes-0.19.2.md
This points **_lnd_** at the new deployment of the **_lseed_** service used to provide candidate peers during initial network bootstrap. We also add lightning seed hostnames for the `testnet4` network.
- Start up an lnd with this change. Or update your `lnd.conf` file to point your node at the new service as demonstrated [here](https://github.com/lightningnetwork/lnd/blob/v0.19.1-beta/sample-lnd.conf#L709).
- And/or manually interact with the **_lseed_** service:
```
dig nodes.lightning.wiki SRV
dig test.nodes.lightning.wiki SRV
dig test4.nodes.lightning.wiki SRV
dig signet.nodes.lightning.wiki SRV
dig ln1q00n7z3066l22s56t9jxrnncfjfzk2vp4ks6lzw0alxeena3dst2wxe8xyt.nodes.lightning.wiki
ln1q00n7z3066l22s56t9jxrnncfjfzk2vp4ks6lzw0alxeena3dst2wxe8xyt --> …
```
=> chainreg: use new lseed service

docs/release-notes/release-notes-0.20.0.md, lnrpc/routerrpc/router_backend.go, lnrpc/routerrpc/router_backend_test.go, rpcserver.go
This PR introduces the initial phase of enforcing payment secret validation for invoices, as described in issue [#9718](https://github.com/lightningnetwork/lnd/issues/9718).
> Reject a payment to invoice that don't have a payment secret.
Adds validation to `extractIntentFromSendRequest` to ensure that an invoice includes either a payment address (payment secret) or at least one blinded path when parsing the SendRequest details.
Related to: #9700, #9718
=> routerrpc: reject payment to invoice that don't have payment secret or blinded paths

docs/release-notes/release-notes-0.20.0.md, invoices/invoiceregistry.go, itest/list_on_test.go, itest/lnd_payment_test.go
I added an additional test regarding MPP payments based on the new spec requiring the payment address to be set for the writer and the reader of an invoice.
=> itest coverage increase following the spec update regarding MPP payments

cmd/commands/wtclient.go
Just add the usage info to the terminal and session commands inside the wtclient. Solves https://github.com/lightningnetwork/lnd/issues/9583.
```
$ make
$ ./lncli-debug wtclient -h
...
session     Interact with watchtower client sessions.
...
$ ./lncli-debug wtclient session -h
...
terminate  Terminate a watchtower client session.
...
$ ./lncli-debug wtclient session terminate -h
NAME:
lncli wtclient session terminate - Terminate a watchtower client session.
USAGE:
lncli wtclient session terminate id
```
=> cmd/wtclient: add usage info for session and terminate commands

watchtower/lookout/justice_descriptor.go
Found some weird logging while working on dyn, this PR now fixes it,
Before,
```
2025-06-26 17:49:57.762 [DBG] WTWR justice_descriptor.go:263: Found to local witness output=&wire.TxOut{Value:4194303, PkScript:[]uint8{0x51, 0x20, 0x25, 0x6c, 0x9a, 0x3f, 0xc2, 0xc9, 0x37, 0x8d, 0x46, 0x56, 0x69, 0xf2, 0x35, 0x52, 0x1b, 0xae, 0x9a, 0xa7, 0xee, 0x14, 0xc9, 0xf5, 0x68, 0x83, 0xfd, 0xdf, 0xf7, 0x85, 0x99, 0xc4, 0x73, 0x9a}}, stack=[[9 64 239 233 98 57 8 0 181 241 152 136 30 149 224 106 54 212 107 17 202 245 131 230 142 28 138 142 116 62 232 126 17 51 221 245 25 15 234 189 189 181 155 161 19 206 82 119 165 176 31 117 250 153 187 159 223 213 224 114 63 226 131 212] [32 2 97 175 173 150 74 225 30 0 30 201 74 210 10 129 233 42 12 77 194 230 241 239 137 165 80 53 176 220 2 105 128 117 32 181 72 211 …
```
=> watchtower: fix logging and add comments

graph/db/graph_test.go, graph/db/sql_store.go, graph/db/test_postgres.go, graph/db/test_sqlite.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/migrations/000007_graph.up.sql, sqldb/sqlc/models.go, sqldb/sqlc/queries/graph.sql, sqldb/sqlutils.go
There is currently a bug in the SQL version of the graph store where
unknown message or channel flags in a channel_update are not persisted
correctly. This manifests if we receive a `channel_update` message containing 
either `message_flags` or `channel_flags` with bits that we don't explicitly parse. 
To fix this, we need to store the entire bitfields for both.
=> graph/db: explicitly store bitfields for channel_update message & channel flags

graph/db/kv_store.go, graph/db/sql_store.go
This PR is a pure refactor. It mainly just does some prep to make a couple of the kv store code re-useable so that we can call the code from the incoming SQL migration without needing to instantiate the entire `KVStore` struct.
=> refactor+graph/db: refactor preparations required for incoming SQL migration code

docs/release-notes/release-notes-0.20.0.md, lnrpc/devrpc/dev.swagger.json, lnrpc/lightning.pb.go, lnrpc/lightning.proto, lnrpc/lightning.swagger.json, lntest/node/watcher.go, rpcserver.go
Found from this [build](https://github.com/lightningnetwork/lnd/actions/runs/13583650550/job/37973971226), where the inbound fee info was set in the `custom_records` of a channel policy response,
```json
{
"time_lock_delta": 22,
"min_htlc": 1000,
"fee_base_msat": 800,
"fee_rate_milli_msat": 123000000,
"max_htlc_msat": 1000000,
"custom_records": {
"55555": "///+cP///8Q="
},
"inbound_fee_base_msat": -400,
"inbound_fee_rate_milli_msat": -60,
"connecting_node": "021f81f97732d32fd0eb39cca08bb05d2377486d1bd5cbbdcad176915364c17e2a",
"timestamp": "2025-02-28T08:10:22.626242157Z"
}
```
We remove the inbound fee record from `RoutingPolicy.CustomRecords` as we already have fields `InboundFeeBaseMsat` and `InboundFeeRateMilliMsat`.
=> rpcserver: remove duplicate info from `RoutingPolicy`

chainntnfs/interface.go, chainntnfs/txnotifier.go
Export NotifierOptions and its internal field to enable external satisfaction of the `protofsm.DaemonAdapters` interface.
=> chainntnfs: export NotifierOptions and internal field for interface use

docs/release-notes/release-notes-0.19.2.md, htlcswitch/switch.go
Fixes https://github.com/lightningnetwork/lnd/issues/10008
In the issue above we had a writer starvation because although we only aquire the RLock in:
`getLocalLink ` which if the balance is not enough creates a failUpdate (which also needs the RLock) so far so good that would not deadlock, however there is a chance a writer regssiters in between and if that happens we have a writer starvation and the parts of the system will deadlock.
In a above case the server mutex is locked and it will cause almost the whole system to lock down.
Important goroutine dump logs:
Here the `getLocalLink` call:
```
goroutine 216074 [sync.RWMutex.RLock, 4 minutes]: 1 times: [[216074]
sync.runtime_SemacquireRWMutexR(0xc2120595219f4ec4?, 0xc0?, 0x4691180?)
runtime/sema.go:100 +0x25
sync.(*RWMutex).RLock(...) …
```
=> fix switch deadlock

docs/release-notes/release-notes-0.20.0.md, graph/db/graph_test.go, graph/db/kv_store.go, graph/db/sql_migration.go, graph/db/sql_migration_test.go
This expands the graph migration code& tests to cover channels and channel policies.
Please see https://github.com/lightningnetwork/lnd/pull/10025 for the final result we are aiming for here.
Depends on https://github.com/lightningnetwork/lnd/pull/10036
=> [graph mig 2]: graph/db: migrate graph channels and policies from kvdb to SQL

channeldb/forwarding_package.go, htlcswitch/link.go
Introduced during development of 19.2 in https://github.com/lightningnetwork/lnd/pull/9911
Now that we do not process Fwds with zero ADDs we need to make sure that we also garbage collect them down the road.
This PR reverts changes made in PR #9911
=> channeldb: gc fwd packgages which have zero ADDs

docs/release-notes/release-notes-0.20.0.md, htlcswitch/link.go
This PR is mostly about moving code into their dedicated methods so it's easier to observe the overall flow in the link, which prepares the following dynamic commitment PRs.
=> Refactor link's long methods

contractcourt/utxonursery.go, contractcourt/utxonursery_test.go, docs/release-notes/release-notes-0.19.2.md
We introduced a new format for the Outpoints for the utxo-nursery in 19.0, however we also still need to support both formats because we don't want to add a migration.
=> contractcourt: fix encoding

.gemini/styleguide.md
I asked gemini-cli to produce its own `styleguilde.md` after first reading our style guidelines doc.  Initially it basically just copied the file as is. I asked if we could just link to the guidelines doc instead but it said no 
```
However, for me to use these guidelines, the rules need to be present as raw text directly within the .gemini/styleguide.md file. The system uses the content of that specific file to inform my code generation and
review process; it doesn't follow links to other documents.
```
so i instead asked it to produce a condensed version of the rules & only keep what it needs
=> .gemini: add styleguide.md

graph/db/graph_test.go, graph/db/sql_migration_test.go
Due to the merge of https://github.com/lightningnetwork/lnd/pull/10043, there is a compilation issue for the sqlite/postgres graph tests since the latest CI run of 10043 was completed before the merge of https://github.com/lightningnetwork/lnd/pull/10050)
=> graph/db: fix sql test compilation

docs/release-notes/release-notes-0.20.0.md, itest/list_on_test.go, itest/lnd_misc_test.go, lntest/rpc/lnd.go, rpcserver.go
Replaces https://github.com/lightningnetwork/lnd/pull/9810
Commit author credit has been retained 👍 
This PR fixes the GetChanInfo endpoint so that it returns the correct grpc status code in the
case where the channel is not found. 
LookupInvoice is also fixed to behave correctly in regards to this grpc status code. 
The GetChanInfo fix is needed for the "remote graph" project so that we can correctly convert `NotFound`
errors back to `graphdb.ErrEdgeNotFound` errors.
=> rpcserver: return consistent grpc NotFound error for GetChaninfo & LookupInvoice

invoices/invoiceregistry_test.go
Was debugging a flake found in [this build](https://github.com/lightningnetwork/lnd/actions/runs/16176630036/job/45663220730) and realized there's a global variable used in the test that may cause a race.
```
panic: timeout
goroutine 245789 [running]:
github.com/lightningnetwork/lnd/invoices_test.timeout.func1()
/home/runner/work/lnd/lnd/invoices/test_utils_test.go:264 +0x1a8
created by github.com/lightningnetwork/lnd/invoices_test.timeout in goroutine 245084
/home/runner/work/lnd/lnd/invoices/test_utils_test.go:256 +0x9d
FAIL	github.com/lightningnetwork/lnd/invoices	519.420s
FAIL
```
=> Fix invoice unit test `TestInvoiceRegistry`

docs/release-notes/release-notes-0.20.0.md, lnwire/dyn_ack.go, lnwire/dyn_ack_test.go, lnwire/dyn_commit.go, lnwire/dyn_commit_test.go, lnwire/dyn_propose.go, lnwire/dyn_propose_test.go, lnwire/extra_bytes.go, lnwire/lnwire_test.go, lnwire/test_message.go
This PR changes the encoding from `btcutil.Amount` to `BigSize` for efficiency. It also fixes the wrong encoding used in the dyn msg set. For instance, the extra data field is meant to hold extra data, but it actually holds the full tlv data,
before this change, notice the `ExtraData` holds `LocalNonce`,
```
dyn_ack_test.go:68: Encoded msg is (*lnwire.DynAck)(0x140002beea0)({
ChanID: (lnwire.ChannelID) (len=32 cap=32) 777b0cfd56e5b84a4bbe87f209b9eeb9218208e9a403c75e03d2981ecd91cf79,
Sig: (lnwire.Sig) {
bytes: ([64]uint8) (len=64 cap=64) {
00000000  b0 54 0e e8 6d 02 d1 e6  8f d9 95 a9 9d 49 60 5d  |.T..m........I`]|
00000010  eb 8e aa 16 4c 7d 26 47  60 10 b2 06 bd 97 8a 3e  |....L}&G`......>|
00000020  b2 73 05 c0 be 0c 14 ed  fd 64 b4 79 a0 7e 22 15  |.s.......d.y.~".|
00000030  96 f1 …
```
=> Fix `ExtraData` field and use `BigSize` encodine

config_test_native_sql.go, graph/db/sql_store.go, graph/db/test_postgres.go, graph/db/test_sqlite.go, itest/lnd_graph_migration_test.go, scripts/gen_sqlc_docker.sh, sqldb/paginate.go, sqldb/paginate_test.go, sqldb/postgres_test.go, sqldb/sqlc/db_custom.go, sqldb/sqlc/db_custom_test.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql, sqldb/sqlite_test.go
In this PR, the `/*SLICE:<field_name>*/` directive is made use of so that we can perform
`WHERE x IN <list of x type>` SQL queries. This then allows us to perform fewer DB calls. 
We dont want to give our SQL lib an unbound number of items in the parameter though so this
PR also adds an `ExecutePagedQuery` helper that gives us the ability to call these new types of
SQL queries in a paginated fashion,.
=> graph/db: use `/*SLICE:<field_name>*/` to optimise various graph queries

Makefile, lnwallet/chancloser/chancloser_test.go, lnwallet/chancloser/rbf_coop_states.go, lnwallet/chancloser/rbf_coop_test.go, lnwallet/chancloser/rbf_coop_transitions.go, protofsm/state_machine.go
Fixed by `gemini-cli`.
Attempts to fix the following flake:
```
--- FAIL: TestRbfCloseErr (0.00s)
--- FAIL: TestRbfCloseErr/send_offer_restart (0.00s)
rbf_coop_test.go:381: no dust field set, expected: no dust
rbf_coop_test.go:617: unexpected state transition: ClosingNegotiation(local=LocalOfferSent(proposed_fee=0.00010100 BTC), remote=<nil>)
rbf_coop_test.go:381: no dust field set, expected: no dust
--- FAIL: TestRbfCloseErr/recv_offer_restart (0.00s)
rbf_coop_test.go:696: unexpected state transition: ClosingNegotiation(local=<nil>, remote=ClosePending(txid=4ebd325a4b394cff8c57e8317ccf5a8d0e2bdf1b8526f8aad6c8e43d8240621a, party=Remote, fee_rate=1010 sat/vb))
--- FAIL: TestRbfCloseClosingNegotiationRemote (0.05s)
--- FAIL: TestRbfCloseClosingNegotiationRemote/recv_offer_rbf_loop_iterations …
```
=> chancloser: fix flakes in chancloser tests

contractcourt/chain_arbitrator.go, contractcourt/channel_arbitrator.go, contractcourt/channel_arbitrator_test.go, docs/release-notes/release-notes-0.20.0.md
Fix the following deadlock,
```
goroutine 12207 [sync.WaitGroup.Wait, 34 minutes]:
sync.runtime_SemacquireWaitGroup(0x2783f78?)
runtime/sema.go:110 +0x25
sync.(*WaitGroup).Wait(0xc007ef21c0?)
sync/waitgroup.go:118 +0x48
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).Stop(0x1fce980?)
github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:866 +0x186
github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).ResolveContract(0xc000570788, {{0x60, 0x32, 0x94, 0xff, 0x72, 0x53, 0xc5, 0x9f, 0xf, ...}, ...})
github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:546 +0x21c
github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).loadPendingCloseChannels.func4()
github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:1361 +0x78 …
```
=> Fix arbitrator deadlock found in `ResolveContract`

graph/db/sql_store.go
Here, we fix a bug that could lead to a nil pointer dereference.
NOTE: this code isn't "live" yet, so should not affect any production release. 
```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8c pc=0x1056c3a78]
goroutine 4078542 [running]:
github.com/lightningnetwork/lnd/graph/db.(*SQLStore).ForEachNodeCached.func1.1(0x2, {0x2, 0x0, 0x7, 0x2f, 0xd3, 0x1, 0xcb, 0x4a, 0x68, ...})
/Users/elle/LL/lnd/graph/db/sql_store.go:1259 +0x648
github.com/lightningnetwork/lnd/graph/db.forEachNodeCacheable({0x105b92578, 0x106299a40}, {0x105ba98c0, 0x14000b80050}, 0x14000047b40)
/Users/elle/LL/lnd/graph/db/sql_store.go:3210 +0x170
github.com/lightningnetwork/lnd/graph/db.(*SQLStore).ForEachNodeCached.func1({0x105ba98c0?, …
```
=> graph/db: fix potential policy swop

graph/db/benchmark_test.go, graph/db/log.go, graph/db/sql_migration.go, log.go
This PR adds:
- some helper tests that can be used to populate a local graph (with any backend type) from a source graph (also from any backend type). 
- Another helper is added that does the same but via the Migrate SQL function. 
- Then, a few benchmark tests are added that can be used to test cache loading and describe graph calls against various graph db backend types. 
These benchmarks will be useful for upcoming PRs which will start introducing some performance improvements. The benckmarks will let us ensure that we are in fact introducing valuable improvements
=> graph/db: helper tests and some benchmarks for SQL

scripts/fuzzy-match-release-branch.sh
This script compares a release branch against a source branch (e.g. master) to verify that all cherry-picked commits are unmodified. It first attempts fast matching using normalized patch hashes.
If no exact match is found, it falls back to a fuzzy matching mechanism:
- Filters source commits by matching author and commit subject
- Compares normalized diffs using diff -u
- Selects the closest match based on line difference count
Useful for verifying cherry-picks or rebased commits during release processes. Supports scan and compare limits for performance.
To test I ran it on the rc branch (https://github.com/lightningnetwork/lnd/pull/9986):
```
./scripts/fuzzy-match-release-branch.sh --source master --release 0-19-2-branch-rc1 --limit 92
```
=> scripts: add cherry-pick verification tool with fuzzy matching

cmd/commands/cmd_payments.go, cmd/commands/commands_test.go
Follow-up on https://github.com/lightningnetwork/lnd/pull/10057#discussion_r2206737427
This PR updates how we handle CLI args for channel ID in `fwdinghistory`, `sendpayment`, and `payinvoice`. We were initially using the `Int64Slice` flag, which doesn't cover all custom/alias `scid` range. Now, we're using the `StringSlice` flag and parsing the chanID to `uint64` later.
```bash
lncli payinvoice --outgoing_chan_id=17592186044552773633 # out of int64 range
```
=> commands: fix how we parse chan ids args at CLI level

docs/release-notes/release-notes-0.20.0.md, itest/list_on_test.go, itest/lnd_misc_test.go, itest/lnd_psbt_test.go, lnrpc/walletrpc/walletkit_server.go
Previously `walletrpc.EstimateFee` and `walletrpc.FundPsbt` used to fail if conf_target is 1.
This was discussed before in https://github.com/lightningnetwork/lnd/pull/9611
In this PR value 1 is allowed. An itest is added.
```
make itest icase='estimate_fee'
make itest icase='fund_psbt'
```
=> walletrpc: allow conf_target=1 in EstimateFee and FundPsbt

config.go, discovery/gossiper.go, discovery/sync_manager.go, discovery/syncer.go, discovery/syncer_atomic_test.go, discovery/syncer_queue_test.go, discovery/syncer_test.go, docs/gossip_rate_limiting.md, docs/release-notes/release-notes-0.19.3.md, lncfg/gossip.go, sample-lnd.conf, server.go
In this PR, we add an async processing queue for the gossip timestamp filter. This ensures that apply a filter never blocks another goroutine. If the queue is full, then the message is just dropped. 
We also make the filtering concurrency configurable. 
Finally, we add a new set of docs to explain how the various rate limiting config options work in tandem.
=> multi: make gossip filter sends non-blocking, only allow a single backlog catch up goroutine per peer

config_test_native_sql.go, graph/db/benchmark_test.go, graph/db/sql_store.go, graph/db/test_postgres.go, graph/db/test_sqlite.go, itest/lnd_graph_migration_test.go, sqldb/paginate.go, sqldb/paginate_test.go
This PR is a pure refactor. 
In it, we add a new helper in the `sqldb` package. 
1) first we rename the existing helper to `ExecuteBatchQuery` so that it more clearly indicates that it is to be used for doing batch fetches (ie, queries using the "WHERE x IN []slice" clause). 
2) Then , we add a new `ExecutePaginatedQuery` helper which can be used to wrap queries that use the "OFFSET & LIMIT" clauses to page through results. 
This refactor & the additional sql helper sets us up nicely for the upcoming PRs which will add performance improvements once again. 
Part of #9795
=> [4] sqldb+graph/db: add and use new pagination helper

graph/db/graph_test.go, graph/db/sql_migration_test.go, graph/db/sql_store.go, make/testing_flags.mk, sqldb/paginate.go, sqldb/paginate_test.go
In this PR we add a new helper method in the sqldb package:
ExecuteCollectAndBatchWithSharedDataQuery. This can be used to paginate
through items in the database while at the same time performing batch
data collection for those items.
Builds on https://github.com/lightningnetwork/lnd/pull/10118
Part of #9795
=> [5] sqldb+graph/db: add and use new paginate & batch helper

graph/db/benchmark_test.go, graph/db/sql_store.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql
The graph store performance improvement saga continues....
In this PR, the performance of the `SQLStore` `ForEachNodeCacheable` and `ForEachNodeCached` are improved. 
For both methods, previously we would iterate through all nodes and fetch one node's info (feature bits, tlv data, addresses) at a time. Now, both are updated to fetch this data in batches. (ie, for a set of nodes). 
Further more, the `ForEachNodeCached` previously would fetch the channels for each node (one node at a time), this is updated so that we fetch channel data for a set/page of nodes at a time. 
Here is the `benchstat` report. The old & new versions were run 10 times each. Note that the `-` indicates the speed up (ie, it can be read as "percentage speed reduction")
```
name                                      old …
```
=> [6] graph/db: use batch fetching to improve ForEachNode* performance

docs/release-notes/release-notes-0.19.3.md, go.mod, go.sum, itest/lnd_psbt_test.go, itest/lnd_remote_signer_test.go, itest/lnd_taproot_test.go
Depends on https://github.com/btcsuite/btcwallet/pull/1022.
Demonstrates the base issue that causes https://github.com/lightninglabs/lightning-terminal/issues/1123 and https://github.com/lightningnetwork/lnd/issues/10120.
Not yet sure what the issue is, perhaps this demonstration case can help find it.
@yyforyongyu you're digging deep into the wallet, perhaps you have an idea?
To see the difference between running the test in a normal setup and in a remote-signing one, you can run:
**Normal**:
```shell
$ make itest icase=taproot_import_scripts
--- PASS: TestLightningNetworkDaemon (5.76s)
--- PASS: TestLightningNetworkDaemon/tranche00/118-of-302/btcd/taproot_import_scripts (4.57s)
PASS
```
**With a remote signer**:
```shell
$ make itest icase=remote_signer-tapscript_import …
```
=> wallet: fix imported tapscript address behavior in watch-only mode

docs/release-notes/release-notes-0.19.2.md, docs/release-notes/release-notes-0.19.3.md, htlcswitch/link.go, itest/list_on_test.go, itest/lnd_max_htlc_path_test.go, routing/bandwidth.go, routing/integrated_routing_context_test.go, routing/unified_edges.go
Looking through some logs of bigger node-runners I saw a lot of these messages:
```
policy for local forward not satisfied
```
Making some local testing I realized that LND will easily end up in a 1 min endless loop always trying the same channel because local failures are currently not registered in the Mission-Control setup.
See here:
```
2025-08-02 16:04:49.472 [ERR] HSWC: Link 182:1:0 policy for local forward not satisfied
2025-08-02 16:04:49.472 [ERR] CRTR: Failed sending attempt 1724 for payment c5c98d82996f4a03d73aa85e10831ef6c0e2bf3b498af455fd073cf6d5c3d745 to switch: htlc exceeds maximum policy amount
2025-08-02 16:04:49.472 [ERR] CRTR: Channel update of ourselves received
2025-08-02 16:04:49.472 [WRN] CRTR: Routing failure for local channel {<nil> 200111116320768} occurred …
```
=> bugfix payment lifecycle payment attempts

.github/actions/setup-go/action.yml, .github/workflows/main.yml, .github/workflows/release.yaml, .golangci.yml, Dockerfile, Makefile, dev.Dockerfile, docker/btcd/Dockerfile, docs/INSTALL.md, docs/release-notes/release-notes-0.19.3.md, go.mod, healthcheck/go.mod, kvdb/go.mod, lnrpc/Dockerfile, lnrpc/gen_protos_docker.sh, make/builder.Dockerfile, sqldb/go.mod, tlv/go.mod, tools/Dockerfile, tools/go.mod, tor/go.mod
- **multi: bump Golang version to v1.23.12**
- **docs: add release notes**
=> update Golang version to v1.23.12 to fix potential SQL bug

server.go
This error is returned when one attempts to use Taproot overlay channels without the necessary auxiliary funding controller being supplied. In practice, when running lnd via litd, the latter will always supply 'tapd' as the aux funding controller, but a standalone lnd has no knowledge of that.
The previous message sort of reads like the lnd user has forgotten to set some available option or flag, but nothing or the sort actually exists. The update makes it clearer that the feature isn't available in the standalone build.
=> server: don't mention aux controllers in error message

docs/release-notes/release-notes-0.19.3.md, routing/payment_lifecycle.go, routing/payment_lifecycle_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/10130
=> fix stuck payment

config_builder.go, config_prod.go, config_test_native_sql.go, graph/builder.go, graph/db/benchmark_test.go, graph/db/sql_migration.go, graph/db/sql_migration_test.go, graph/db/sql_store.go, graph/db/test_postgres.go, graph/db/test_sqlite.go, itest/lnd_graph_migration_test.go, lncfg/db.go, sample-lnd.conf, sqldb/config.go, sqldb/paginate.go, sqldb/paginate_test.go
This PR does 2 things related to the `sqldb.QueryConfig`: 
1) plugs these values in to the main SQLite and Postgres config structs & makes the values configurable 
2) adds a benchmark which aided in finding better default values to use for sqlite and postgres for the query options. 
Part of #9795 
```
name                                                    old time/op  new time/op  delta
GraphReadMethods/ForEachNode-native-sqlite-10            269ms ± 1%   200ms ± 3%  -25.86%  (p=0.008 n=5+5)
GraphReadMethods/ForEachChannel-native-sqlite-10         1.53s ±12%   1.40s ± 1%   -8.58%  (p=0.016 n=5+4)
GraphReadMethods/NodeUpdatesInHorizon-native-sqlite-10   238ms ± 2%   239ms ± 4%     ~     (p=0.841 n=5+5)
GraphReadMethods/ForEachNodeCacheable-native-sqlite-10   136ms ± 1%   114ms ± 5% …
```
=> graph/db+sqldb: different defaults for SQLite and Postgres query options

graph/db/benchmark_test.go, graph/db/sql_migration.go, graph/db/sql_store.go, sqldb/paginate.go, sqldb/paginate_test.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql
Part of #9795 
This PR updates the graph SQL migration code to make use of batch fetching for validation instead of validating records one-by-one. This is especially important for when a postgres backend is being used. 
With this PR, the migration for a mainnet backend with
- 16216 nodes,
- 51239 channels
- 82029 policies
- 361511 prune log entries
- 17931 closed SCID index entries 
- 238183 zombie channel index entries 
Takes ~ 50 seconds on SQLite & 1m35s on Postgres 
(before this PR, it would take >11m on postgres)
=> graph/db: use batch validation to improve SQL migration performance

.github/workflows/release.yaml, scripts/check-pgp-expiry.sh
Closes #6281. This PR adds a new job to the CI pipeline that verifies the expiration of PGP keys. The job will fail if no valid signing-capable primary or subkey is found.
And, since we have some expired keys, the job is currently failing.
Run the script manually:
```bash
bash scripts/check-pgp-expiry.sh
```
Or simulate the CI job locally using:
```bash
act -j pgp-key-expiration-check
```
To inspect the expiration dates for debugging, use:
```bash
gpg --with-colons --import-options show-only --import "$key_file"
```
Output:
```
➜  lnd git:(check-pgp-keys-expiry) scripts/check-pgp-expiry.sh
Starting PGP key validation...
Found 14 key file(s) in ./scripts/keys
────────────────────────────────────────────────────────────────────
Checking bhandras.asc...
INFO: pub:80E5375C094198D8 (scESC) is …
```
=> CI: add pgp keys expiry check

.github/actions/setup-go/action.yml, .github/workflows/main.yml, .github/workflows/release.yaml, .golangci.yml, Dockerfile, Makefile, build/version.go, dev.Dockerfile, docker/btcd/Dockerfile, docs/INSTALL.md, docs/release-notes/release-notes-0.19.3.md, go.mod, healthcheck/go.mod, kvdb/go.mod, lnrpc/Dockerfile, lnrpc/gen_protos_docker.sh, lnwallet/aux_signer.go, lnwallet/channel.go, lnwallet/channel_test.go, lnwallet/payment_descriptor.go, make/builder.Dockerfile, routing/payment_lifecycle.go, routing/payment_lifecycle_test.go, sqldb/go.mod, tlv/go.mod, tools/Dockerfile, tools/go.mod, tor/go.mod
Includes the following PRs:
- https://github.com/lightningnetwork/lnd/pull/10141
- https://github.com/lightningnetwork/lnd/pull/9871
- https://github.com/lightningnetwork/lnd/pull/10139
=> release: create v0.19.3-rc2 branch

lnwallet/test/test_interface.go
That test `TestLightningWallet/btcwallet/neutrino:reorg_wallet_balance ` failed recently. It is not clear why it flaky failed. Currently the timeout was set to 10seconds but the error message said it is timeout after 30seconds. Increasing the timeout may give the wallet some time to sync as well as to match the error message:
https://github.com/lightningnetwork/lnd/actions/runs/16982438758/job/48145091023?pr=9455
=> lnwallet/test: increase wait for wallet to sync to `30s` to match with the returned error in case of timeout

.github/workflows/docker.yml, .github/workflows/release.yaml
based on https://github.com/lightningnetwork/lnd/pull/10112#issuecomment-3190755653, I don't think we need to fail in general because of expired keys, there will always be enough valid keys to sign the release IMO, wdyt ?
=> move pgp check to daily builds

config.go, discovery/ban.go, discovery/ban_test.go, discovery/chan_series.go, discovery/gossiper.go, discovery/gossiper_test.go, discovery/sync_manager.go, docs/gossip_rate_limiting.md, docs/release-notes/release-notes-0.20.0.md, lncfg/gossip.go, sample-lnd.conf, server.go
This PR adds two changes,
- update `UpdatesInHorizon` to be more robust about invalid announcements.
- record bad peers when processing invalid `channel_update`.
=> Catch bad gossip peer and fix `UpdatesInHorizon`

graph/db/sql_migration.go, graph/db/sql_migration_test.go, graph/db/sql_store.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/querier.go, sqldb/sqlc/queries/graph.sql
In this PR, we make sure that the graph SQL migration is retry safe. This is necessary since the source DB in the migration may execute retries & since we make use of call-backs to execute our migration to the destination DB, we need to make sure that the migration does not error if a retry occurs on the source DB. 
See the commit messages for details on how this has been done. Appropriate unit tests have been expanded to cover retry-safety. 
Part of #9795
=> graph/db+sqldb: Make the SQL migration retry-safe/idempotent

.gemini/styleguide.md
Gemini code review agent is bad at counting characters and is causing lots of noise during review.
=> .gemini: ignore char wrapping during code review

chanbackup/backup_test.go, chanbackup/multi_test.go, chanbackup/single_test.go, discovery/chan_series.go, discovery/gossiper.go, docs/release-notes/release-notes-0.20.0.md, graph/db/addr.go, graph/db/addr_test.go, graph/db/graph_test.go, graph/db/sql_store.go, lnwire/dns_addr.go, lnwire/dns_addr_test.go, lnwire/lnwire.go, lnwire/message_test.go, lnwire/writer.go, lnwire/writer_test.go, netann/node_announcement.go
Towards #6337.
Towards #9126.
Next #10159.
=> [1/2] discovery+lnwire: add support for DNS host name in NodeAnnouncement msg

autopilot/graph.go, autopilot/interface.go, autopilot/prefattach_test.go, channeldb/db_test.go, discovery/gossiper.go, discovery/gossiper_test.go, graph/builder.go, graph/builder_test.go, graph/db/benchmark_test.go, graph/db/graph.go, graph/db/graph_test.go, graph/db/interfaces.go, graph/db/kv_store.go, graph/db/models/node.go, graph/db/notifications.go, graph/db/sql_migration.go, graph/db/sql_migration_test.go, graph/db/sql_store.go, graph/interfaces.go, graph/notifications_test.go, lnrpc/devrpc/dev_server.go, routing/pathfind_test.go, routing/payment_session_source.go, routing/payment_session_test.go, routing/router_test.go, rpcserver.go, server.go
Rename the `models.LightningNode` struct to `models.Node`. 
Also rename any DB methods ending with `*LightningNode(...)` to `*Node(...)`. 
To keep the diff as small as possible, multi-line comments have not been reformatted (everything will still fit since the new naming is strictly shorter)
=> multi: Rename LightningNode to Node

graph/db/sql_migration.go, graph/db/sql_store.go, sqldb/sqlutils.go
The SQL* helpers are meant to always set the `Valid` field of the sql.Null* type to true. Otherwise they cannot be used to set a valid, empty field. In this commit, the SQLStr helper is fixed so that we can represent a valid/set empty string field.
This is important for something like storing node announcement data where fields like `Alias` might be present but might be a zero length string. The difference is important so that when we construct a pure TLV message, we know wether to include the field or not. 
We need this for https://github.com/lightningnetwork/lnd/issues/9795
=> sqldb: fix SQLStr helper

graph/db/sql_migration.go, graph/db/sql_migration_test.go
Due to a recent merge that happened just after a variable rename merge, the master build is broken. This 
PR fixes that.
=> graph/db: fix type name

cmd/commands/cmd_walletunlocker.go
Sometimes user can get scammed as they're unaware that sharing the seed can lead to loss of funds. With this message we emphasize the dangers of sharing.
=> commands: add extra warning on wallet creation

autopilot/agent.go, contractcourt/chain_watcher.go, contractcourt/htlc_timeout_resolver.go, contractcourt/utxonursery.go, discovery/gossiper.go, funding/manager.go, htlcswitch/switch.go, invoices/sql_store.go, lnwallet/btcwallet/btcwallet.go, lnwallet/chancloser/chancloser.go, lnwallet/chancloser/rbf_coop_transitions.go, lnwallet/channel.go, lnwallet/wallet.go, netann/channel_update.go, peer/brontide.go, routing/payment_lifecycle.go, routing/router.go, rpcserver.go, sweep/sweeper.go, watchtower/lookout/justice_descriptor.go
We added this helper function to address the common case of wanting to make a log closure to spew a struct. In this PR, we attempt to make this more uniform. Occurrences were found with the help of a simple grep script.
=> multi: attempt to more uniformly use SpewLogClosure across project

docs/release-notes/release-notes-0.20.0.md, zpay32/decode.go, zpay32/encode.go, zpay32/invoice_internal_test.go, zpay32/invoice_test.go
Fixes #9591
Add Support for P2TR Fallback Addresses in BOLT-11 invoices
lncli addinvoice --fallback_addr=bcrt1ps89hq0hxen5y6yxqqk88ssdyhe7hdr92fzudtcskk37p460ldazsl0sfsw
=> Add Support for P2TR Fallback Addresses in BOLT-11

chainntnfs/txnotifier.go, config_builder.go, docs/release-notes/release-notes-0.20.0.md, go.mod, go.sum, lnwallet/btcwallet/btcwallet.go, sweep/fee_bumper.go, sweep/fee_bumper_test.go, sweep/mock_test.go
Depends on:
https://github.com/btcsuite/btcwallet/pull/1053
Fixes:
https://github.com/lightninglabs/taproot-assets/issues/1770
and 
https://github.com/lightninglabs/lightning-terminal/issues/1139 (which needs to bump the corresponding LND version if this is merged.)
!!!ATTENTION!!! First 9 commits belong to https://github.com/lightningnetwork/lnd/pull/10209 !!!ATTENTION!!!
=> bugfix error matching sweeper

brontide/bench_test.go, brontide/conn.go, brontide/noise.go, docs/benchmark_perf_loop.md, peer/brontide.go
I got a bit nerd sniped and entered optimizoooor mode. 
In this PR, we eliminate _all_ the allocations from the `WriteMessage`+`Flush` methods. 
To achieve this, we mainly ensure that we re-use static buffers, and that none of those buffers escape to the heap. I also added some documentation that describes the set of tools/techniques I used, so future devs/contributors can follow a similar optimizooooor loop. 
The the start of this commit series, here's the benchmark output: 
```
goos: darwin
goarch: arm64
pkg: github.com/lightningnetwork/lnd/brontide
cpu: Apple M4 Max
BenchmarkWriteMessage-16    	   22736	     50667 ns/op	   73788 B/op	       5 allocs/op
BenchmarkWriteMessage-16    	   23217	     50463 ns/op	   73788 B/op	       5 allocs/op
BenchmarkWriteMessage-16    	   24241 …
```
=> brontide: eliminate all allocations from WriteMessage+Flush

config_builder.go, docs/release-notes/release-notes-0.20.0.md, funding/manager.go, htlcswitch/link.go, lnwallet/aux_leaf_store.go, lnwallet/aux_negotiator.go, lnwire/init_message.go, lnwire/init_message_test.go, lnwire/test_message.go, peer/brontide.go, server.go
Adds a new aux component named `AuxChannelNegotiator`. The responsibility of this component is to inject custom feature bits on the peer init & reestablish messages. The interface allows for both reading and setting any custom feature bits.
The aux feature bits are treated as a `tlv.Blob` by LND, and reside within their own TLV type. So any node that does not support/understand aux feature bits will simply drop the TLV and not read it.
=> Aux feature bits

config.go, itest/lnd_channel_graph_test.go, sample-lnd.conf, server.go
Fixes #10233
Currently, when a node restarts, persisted addresses are combined with addresses (externalip) set in config, resulting in the retention of addresses that may no longer be valid, in the node announcement. In this PR, we make addresses derived from `--externalip` config take precedence over persisted addresses. However, if `--externalip` is not set and a node restarts, we assume that the persisted addresses are still valid, and therefore we use them for the node announcement.
```bash
make build-itest
make itest-only icase="self node announcement persistence"
```
=> lnd: fix externalip retention issue

discovery/chan_series.go, discovery/syncer.go, discovery/syncer_test.go, docs/release-notes/release-notes-0.20.0.md, fn/go.mod, fn/iter.go, go.mod, go.sum, graph/builder.go, graph/db/benchmark_test.go, graph/db/graph_test.go, graph/db/interfaces.go, graph/db/kv_store.go, graph/db/options.go, graph/db/sql_store.go, graph/interfaces.go, sqldb/sqlc/graph.sql.go, sqldb/sqlc/queries/graph.sql
Haven't had an excuse to make an [iterator](https://pkg.go.dev/iter) yet, so I nerd-sniped myself into the creation of this PR. 
This PR does a few things:
* Updates nodes+chan updates in horizon to return an iterator of the contents.
* Even though most of the actual values we read out will already be in the channel graph cache, as is we can have a potentially very long running database transactions. 
* The new iterator versions accept a batch size and read in chunks, yielding out the responses. Callers are mostly unchanged. 
*  Optimizes public node filtering for nodes in horizon:
* Before in a new loop after we'd read all the nodes, we'd then check again to see which ones are public. This previously meant a new DB transaction for each node. Now we fold that into the underlying query. 
* …
=> multi: update ChanUpdatesInHorizon and NodeUpdatesInHorizon to return iterators (iter.Seq[T]) 

graph/builder.go, graph/db/graph_test.go, graph/db/sql_store.go, lncfg/db.go, sample-lnd.conf
- Update the `sample-lnd.conf` file to list the `Graph` subsystem as one which supports native SQL. Also update the description of the `db.use-native-sql` flag.
- update the graph SQLStore impl to gracefully handle the same exact node announcement or policy update to be inserted twice.  This is to handle the case where two of the same announcments are handled in the same db batch transaction.
=> graph/db+docs: handle duplicate announcements and update docs
